import fs from 'node:fs';
import {createRequire} from 'node:module';
const [port,modulePath,artifacts,resultPath,fkrEmail,otizEmail,password,pdfPath,reportDate,certificateDate,newDeadline]=process.argv.slice(2);
const {chromium}=createRequire(import.meta.url)(modulePath);
const browser=await chromium.launch({headless:true});
const base=`http://127.0.0.1:${port}`;const result={};
try{
 const login=async(email)=>{const context=await browser.newContext({viewport:{width:390,height:844},acceptDownloads:true});const page=await context.newPage();page.setDefaultTimeout(12000);await page.goto(base+'/pilot/login');await page.locator('[name=email]').fill(email);await page.locator('button[type=submit]').click();await page.locator('[name=password]').fill(password);await page.locator('button[type=submit]').click();await page.waitForURL(/\/pilot\/objects/);return page;};
 const fkr=await login(fkrEmail);await fkr.goto(base+'/pilot/objects/4512');await fkr.locator('a[href="/pilot/objects/4512/deadline-certificates"]').click();if(await fkr.locator('[name=sourceLabel], [name=sourceLocator]').count())throw new Error('RED_ASSERTION certificate upload must not require technical provenance fields');await fkr.locator('[name=certificateDate]').fill(certificateDate);await fkr.locator('[name=newDeadline]').fill(newDeadline);await fkr.locator('[name=pdf]').setInputFiles(pdfPath);result.certificateRequest=await fkr.locator('[name=requestId]').inputValue();await fkr.locator('form').filter({has:fkr.locator('[name=pdf]')}).locator('button[type=submit]').click();await fkr.waitForURL(/deadline-certificates$/);await fkr.locator('a[href$="/pdf"]').waitFor();result.certificateUploaded=true;
 const localizedDate=value=>{const [year,month,day]=value.split('-');return `${day}.${month}.${year}`;};
 const page=await login(otizEmail);await page.goto(base+'/pilot/otiz/payments');await page.locator('.shlz-date-field__input').fill(localizedDate(reportDate));result.firstOperation=await page.locator('input[name="operationId"]').inputValue();await page.getByRole('button',{name:'Подготовить расчёт'}).click();await page.waitForURL(/snapshots\/\d+\?created=1/);result.firstSnapshot=Number(new URL(page.url()).pathname.split('/').pop());
 const objectRow=page.locator('[data-otiz-snapshot-table] [data-otiz-object]').first();await objectRow.getByRole('button',{name:/Подробнее/}).click();const openDrawer=page.locator('[data-otiz-drawer][open]');await openDrawer.getByText('Как рассчитана сумма',{exact:true}).click();const text=await openDrawer.innerText();for(const label of ['Выплачено ранее','Остаток до штрафа','Штраф за просрочку','Справка о переносе срока','Исходный плановый срок','2026-09-05',newDeadline,'ПТО отсутствует'])if(!text.includes(label))throw new Error('Missing trace label '+label);const normalized=text.replace(/\s/g,'');for(const value of ['13000,00','260,00','12740,00'])if(!normalized.includes(value))throw new Error('Missing exact first trace value '+value);if(await openDrawer.locator('a[href*="deadline-certificates/"][href$="/pdf"]').count()!==1)throw new Error('Missing exact certificate revision link');result.trace=text;await openDrawer.locator('[data-shlz-drawer-close]').last().click();
 await page.screenshot({path:artifacts+'/excel-mobile-draft.png',fullPage:true});await page.getByRole('button',{name:'Подтвердить расчёт'}).click();await page.waitForURL(/accepted=1/);const downloadPromise=page.waitForEvent('download');await page.getByRole('link',{name:'Скачать реестр XLSX'}).click();await(await downloadPromise).saveAs(artifacts+'/excel.xlsx');await page.getByRole('button',{name:'Отметить выплаты выполненными'}).click();await page.getByRole('button',{name:'Зарегистрировать выплату'}).click();await page.waitForURL(/paid=1/);
 await page.goto(base+'/pilot/otiz/payments');await page.locator('.shlz-date-field__input').fill(localizedDate(reportDate));result.secondOperation=await page.locator('input[name="operationId"]').inputValue();if(result.secondOperation===result.firstOperation)throw new Error('Recalculation reused the prior operation id after a completed publication');await page.getByRole('button',{name:'Подготовить расчёт'}).click();await page.waitForURL(/snapshots\/\d+\?created=1/);result.secondSnapshot=Number(new URL(page.url()).pathname.split('/').pop());if(result.secondSnapshot===result.firstSnapshot)throw new Error('Recalculation replayed the prior snapshot instead of creating a new immutable snapshot');await page.screenshot({path:artifacts+'/excel-mobile-recalculated.png',fullPage:true});result.completed=true;fs.writeFileSync(resultPath,JSON.stringify(result));
}finally{await browser.close();}
