import fs from 'node:fs';import {createRequire} from 'node:module';import assert from 'node:assert/strict';
const c=JSON.parse(fs.readFileSync(process.argv[2],'utf8'));const{chromium}=createRequire(import.meta.url)(c.playwright);const browser=await chromium.launch({headless:true});
try {
  for(const viewport of[{width:1280,height:900},{width:390,height:844}]){
    const page=await browser.newPage({viewport});await page.goto(c.origin+'/pilot/login');await page.locator('input[name=email]').fill(c.email);await page.locator('input[name=email]').locator('xpath=ancestor::form').locator('button[type=submit]').click();await page.locator('input[name=password]').fill(c.password);await Promise.all([page.waitForURL(/\/pilot\/objects/),page.locator('button[type=submit]').click()]);await page.goto(c.origin+'/pilot/construction-control?ownership=all');
    const trigger=page.getByRole('button',{name:'Запланировать инспекцию'}).first();await trigger.focus();await trigger.press('Enter');const dialog=page.locator('[data-inspection-dialog]');assert.equal(await dialog.count(),1,'INTENDED_RED one dialog');assert.equal(await dialog.evaluate(e=>e.open),true);assert.match(await dialog.innerText(),/Инспекция появится в календаре и списке стройконтроля/);const date=dialog.locator('input[name=inspectionDate]');assert.equal(await date.evaluate(e=>e===document.activeElement),true,'date focused');await date.fill('2099-09-12');await page.keyboard.press('Escape');assert.equal(await dialog.evaluate(e=>e.open),false);assert.equal(await trigger.evaluate(e=>e===document.activeElement),true,'focus returned');await trigger.click();assert.equal(await date.inputValue(),'2099-09-12','draft retained');assert.equal((await dialog.boundingBox()).width<=viewport.width,true,'dialog fits viewport');
    await date.fill('2000-01-01');await dialog.locator('button[type=submit]').click();await page.getByText(/Дата.*не может быть в прошлом|Некорректная дата/i).waitFor();assert.equal(await date.inputValue(),'2000-01-01','confirmed rejection retains entered date');assert.equal(await dialog.locator('input[name=action]').inputValue(),'create','confirmed rejection retains action');assert.equal(await dialog.evaluate(e=>e.open),true,'confirmed rejection keeps dialog open');await date.fill('2099-09-12');
    let posts=0;await page.route('**/pilot/construction-control/objects/*/inspection-plan',async route=>{if(route.request().method()!=='POST')return route.continue();posts++;if(posts===1)return route.fulfill({status:503,contentType:'text/plain; charset=UTF-8',body:'Service unavailable.\n'});return route.continue();});await dialog.locator('button[type=submit]').click();await page.getByText(/Результат.*не подтверждён/).waitFor();assert.equal(posts,1,'server 503 is one unknown outcome');for(const[name,value]of[['inspectionDate','2099-09-12'],['action','create'],['expectedVersion','0']])assert.equal(await dialog.locator(`[name="${name}"]`).inputValue(),value,'unknown retains '+name);assert.match(await dialog.locator('[name=requestId]').inputValue(),/^[0-9a-f-]{36}$/,'unknown retains request identity');await page.waitForTimeout(500);assert.equal(posts,1,'no hidden retry');await Promise.all([page.waitForNavigation(),dialog.locator('button[type=submit]').click()]);assert.equal(posts,2,'explicit retry only');await page.getByText(/Инспекция запланирована на 12\.09\.2099/).waitFor();await page.goto(c.origin+'/pilot/calendar?date=2099-09-12');assert.equal(await page.locator('a[href="/pilot/objects/451201"]').count(),1,'calendar agrees after create');await page.goto(c.origin+'/pilot/construction-control?ownership=all');
    const move=page.getByRole('button',{name:'Перенести'}).first();await move.focus();await move.press('Enter');const same=page.locator('[data-inspection-dialog]');assert.equal(await same.count(),1,'same dialog for reschedule');assert.equal(await same.locator('input[name=inspectionDate]').evaluate(e=>e===document.activeElement),true,'reschedule date focused');await page.keyboard.press('Escape');assert.equal(await move.evaluate(e=>e===document.activeElement),true,'reschedule focus returned');await move.press('Enter');await same.locator('input[name=inspectionDate]').fill('2099-09-15');await Promise.all([page.waitForNavigation(),same.locator('button[type=submit]').click()]);await page.getByText(/Инспекция запланирована на 15\.09\.2099/).waitFor();await page.goto(c.origin+'/pilot/calendar?date=2099-09-15');assert.equal(await page.locator('a[href="/pilot/objects/451201"]').count(),1,'calendar agrees after reschedule');await page.goto(c.origin+'/pilot/construction-control?ownership=all');await page.getByRole('button',{name:'Отменить'}).first().click();assert.equal(await page.locator('[data-inspection-dialog]').count(),1,'same dialog for cancel');await Promise.all([page.waitForNavigation(),page.locator('[data-inspection-dialog] button[type=submit]').click()]);await page.getByRole('button',{name:'Запланировать инспекцию'}).first().waitFor();await page.goto(c.origin+'/pilot/calendar?date=2099-09-15');assert.equal(await page.locator('a[href="/pilot/objects/451201"]').count(),0,'calendar agrees after cancel');await page.close();
  }
  fs.writeFileSync(c.result,JSON.stringify({passed:true}),{mode:0o600});
} finally {await browser.close();}
