import fs from 'node:fs';
import {createRequire} from 'node:module';
const c=JSON.parse(fs.readFileSync(process.argv[2],'utf8')),require=createRequire(import.meta.url);
const {chromium}=require(c.playwright),browser=await chromium.launch({headless:true});
const check=(value,message)=>{if(!value)throw new Error(message);};
try {
 const context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage(),errors=[];
 page.on('pageerror',error=>errors.push(error.message));page.on('response',response=>{if(new URL(response.url()).pathname.startsWith('/pilot/assets/')&&response.status()>=400)errors.push(response.url());});
 async function login(email){await page.goto(c.origin+'/pilot/login');await page.locator('[name=email]').fill(email);await page.locator('[name=email]').locator('xpath=ancestor::form').locator('button[type=submit]').click();await page.locator('[name=password]').fill(c.password);await Promise.all([page.waitForResponse(r=>r.url().endsWith('/pilot/login')&&r.status()===303),page.locator('[name=password]').locator('xpath=ancestor::form').locator('button[type=submit]').click()]);}
 await login(c.email);let response=await page.goto(c.origin+'/pilot/installers');check(response.status()===200,'INTENDED_RED directory '+response.status());
 check(await page.locator('nav[aria-label="Основная навигация"] a[href="/pilot/installers"][aria-current="page"]').count()===1,'current nav');check((await page.textContent('body')).includes('fkr.preopening@shlz.ru'),'identity');check(await page.getByRole('button',{name:'Выйти'}).count()===1,'logout');check((await page.textContent('body')).includes('10.09.2026 07:40'),'source date');check(await page.locator('tbody tr').count()===50,'page50');
 for(const name of ['q','status','availability'])check(await page.locator(`[name=${name}]`).evaluate(element=>element.labels.length>0),name+' label');check(await page.locator('[name=q]').getAttribute('maxlength')==='120','search bound');
 await page.locator('[name=q]').fill('Монтажник 125');await Promise.all([page.waitForNavigation(),page.locator('[name=q]').press('Enter')]);check((await page.textContent('body')).includes('Монтажник 125'),'keyboard search');check(await page.locator('a[href="/pilot/installers"]',{hasText:'Сбросить'}).count()===1,'reset visible');await page.locator('a[href="/pilot/installers"]',{hasText:'Сбросить'}).click();
 await page.locator('[name=status]').selectOption('dismissed');await page.locator('[name=availability]').selectOption('free');await Promise.all([page.waitForNavigation(),page.locator('form button[type=submit]').click()]);check((await page.textContent('body')).includes('40 сотрудников'),'filter40');await page.reload();check((await page.textContent('body')).includes('40 сотрудников'),'refresh preserves filters');
 for(const width of [1440,390]){await page.setViewportSize({width,height:900});check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'no overflow '+width);const row=page.locator('tbody tr').first();for(const text of ['Монтажник','таб.','Уволен','Нет действующих закреплений','1С ЗУП'])check((await row.textContent()).includes(text),'row content '+text+' '+width);await page.screenshot({path:c.artifacts+`/directory-${width}.png`,fullPage:true});}
 await page.goto(c.origin+'/pilot/installers?page=1');check(await page.locator('nav.fm2-pagination a[aria-current="page"]').count()===1,'one current pagination page');await page.locator('a[href*="page=2"]').focus();await page.keyboard.press('Enter');await page.waitForURL('**page=2');check(new URL(page.url()).searchParams.get('page')==='2','keyboard pagination');check(await page.locator('nav.fm2-pagination a[aria-current="page"]',{hasText:'2'}).count()===1,'second page current');
 await page.goto(c.origin+'/pilot/installers');await page.locator('a[href="/pilot/objects/5001"]').first().focus();await page.keyboard.press('Enter');await page.waitForURL('**/pilot/objects/5001');check(new URL(page.url()).pathname==='/pilot/objects/5001','keyboard object link');
 await page.goto(c.origin+'/pilot/installers');await page.getByRole('button',{name:'Выйти'}).click();await page.waitForURL('**/pilot/login');await login('reader.preopening@shlz.ru');response=await page.goto(c.origin+'/pilot/installers');check(response.status()===200,'reader directory');check(await page.locator('a[href="/pilot/admin/users"],a[href="/pilot/admin/roles"],a[href="/pilot/construction-control"]').count()===0,'forbidden navigation absent');check(await page.locator('a[href="/pilot/objects"],a[href="/pilot/installers"]').count()>=2,'permitted navigation present');
 check(errors.length===0,'browser errors '+errors.join(';'));fs.writeFileSync(c.result,JSON.stringify({passed:true}));
} finally {await browser.close();}
