import process from'node:process';import{readFile}from'node:fs/promises';const configPath=process.argv[2]||process.env.FMONITOR_BROWSER_CONFIG;if(!configPath)throw new Error('SETUP_FAILURE: fixture config required');const config=JSON.parse(await readFile(configPath,'utf8'));
const playwright=await import(config.playwright);const chromium=playwright.chromium??playwright.default?.chromium;
const browser=await chromium.launch({headless:true});
try {
  const context=await browser.newContext({viewport:{width:1280,height:900},hasTouch:true});const page=await context.newPage();
  await page.goto(config.origin+'/pilot/login');
  await page.fill('input[name=email]',config.email);await page.click('button[type=submit]');await page.fill('input[name=password]',config.password);
  await Promise.all([page.waitForURL('**/pilot/**'),page.click('button[type=submit]')]);
  await page.goto(config.origin+'/pilot/dashboard');
  const chart=page.locator('[data-dashboard-chart="utilization"]');if(await chart.count()!==1)throw new Error('utilization forecast absent');if(await chart.locator('.fm2-forecast-week').count()!==6||await chart.locator('.fm2-forecast-value').count()!==30)throw new Error('forecast matrix absent');if(await page.locator('[data-installer-utilization-history],[data-observation-date],[data-utilization-week-empty]').count())throw new Error('historical dashboard visualization remains');
  await page.goto(config.origin+'/pilot/dashboard/installers/observations/2026-09-25/without_current');if(await page.locator('[data-saved-member]').count()!==2)throw new Error('saved current detail count');if(!(await page.locator('[data-saved-reason]').count()))throw new Error('saved current reasons absent');await page.goto(config.origin+'/pilot/dashboard/installers/observations/2026-09-25/without_next');if(!(await page.locator('[data-saved-member]').count()))throw new Error('saved next detail absent');
  await page.goto(config.origin+'/pilot/installers/7001');for(const width of[1280,360]){await page.setViewportSize({width,height:800});const ok=await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth&&[...document.querySelectorAll('.installer-card .shlz-panel')].every(e=>parseFloat(getComputedStyle(e).paddingLeft)>=12)&&([...document.querySelectorAll('.installer-card .shlz-panel')].slice(1).every((e,i,a)=>i===0||e.getBoundingClientRect().top-a[i-1].getBoundingClientRect().bottom>=12)));if(!ok)throw new Error('narrow card gap/padding/overflow');}if(await page.getByText(/Источник интеграции|Последняя интеграция/).count())throw new Error('provenance visible');if(!(await page.locator('[data-installer-tab-id="7001"] .shlz-status').getByText('Трудоустроен',{exact:true}).count()))throw new Error('workforce status label absent');
} finally { await browser.close(); }
