import fs from 'node:fs';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),c=JSON.parse(fs.readFileSync(process.argv[2],'utf8'));
const {chromium}=require(c.playwright),browser=await chromium.launch({headless:true});
const check=(value,message)=>{if(!value)throw new Error(message);};
try {
 const context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage();
 const assetFailures=[];page.on('response',r=>{if(new URL(r.url()).pathname.startsWith('/pilot/assets/')&&r.status()>=400)assetFailures.push(r.status()+' '+r.url());});
 await page.goto(c.origin+'/pilot/login');await page.locator('[name=email]').fill(c.email);
 await page.locator('[name=email]').locator('xpath=ancestor::form').locator('button[type=submit]').click();
 await page.locator('[name=password]').fill(c.password);
 await Promise.all([page.waitForResponse(r=>r.url().endsWith('/pilot/login')&&r.status()===303),page.locator('[name=password]').locator('xpath=ancestor::form').locator('button[type=submit]').click()]);
 const response=await page.goto(c.origin+'/pilot/objects');check(response.status()===200,'INTENDED_RED Yii queue missing');
 await page.getByRole('heading',{name:'Объекты монтажа',exact:true}).waitFor();
 const button=page.locator('[data-inspection-schedule]').first();await button.focus();await page.keyboard.press('Enter');
 const dialog=page.locator('dialog[open]');await dialog.waitFor();
 const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Moscow',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
 check(await dialog.locator('[name=inspectionDate]').inputValue()===today,'default date Moscow today');check(await dialog.locator('[name=inspectionDate]').getAttribute('min')===today,'minimum date Moscow today');
 check(await dialog.locator('[name=_csrf]').count()===1,'native CSRF in dialog');
 await dialog.locator('[name=inspectionDate]').fill('2099-09-12');
 await Promise.all([page.waitForResponse(r=>r.url().endsWith('/inspection-schedule')&&r.status()===303),dialog.locator('button[type=submit]').click()]);
 await page.waitForURL(c.origin+'/pilot/objects?inspectionScheduled=2099-09-12');await page.getByText(/Инспекция запланирована на 12\.09\.2099/).waitFor();
 check(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1),'desktop has no page overflow');
 await page.screenshot({path:c.artifacts+'/queue-desktop.png',fullPage:true});
 await page.goto(c.origin+'/pilot/objects?page=2');check((await page.locator('[name=q]').count())===1,'search on actual second page');
 await page.locator('[name=q]').fill('REG-451201');
 const search=page.locator('[name=q]').locator('xpath=ancestor::form');await search.locator('button[type=submit]').click();await page.waitForURL(/q=REG-451201/);
 check(await page.locator('a[href="/pilot/objects/451201"]').count()>0,'filtered object link remains');check(!new URL(page.url()).searchParams.has('page'),'new browser search drops page2');
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:c.artifacts+'/queue-mobile.png',fullPage:true});
 check(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1),'mobile has no page overflow');
 await page.locator('[data-inspection-schedule]').first().click();await page.locator('dialog[open]').waitFor();await page.keyboard.press('Escape');
 check(await page.locator('dialog[open]').count()===0,'Escape closes dialog');
 await page.getByRole('link',{name:'Сбросить',exact:true}).click();await page.waitForURL(c.origin+'/pilot/objects');check(await page.locator('[name=q]').inputValue()==='','reset clears query');
 check(assetFailures.length===0,'assets loaded: '+assetFailures.join(','));
 fs.writeFileSync(c.result,JSON.stringify({scheduled:true,desktop:true,mobile:true,assetFailures}));
} finally {await browser.close();}
