import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';

const config=JSON.parse(fs.readFileSync(process.argv[2],'utf8'));
const {chromium}=createRequire(import.meta.url)(config.playwright);
const result={stage:'startup',pageErrors:[],badResponses:[]};let browser;
try{
  browser=await chromium.launch({headless:true});const context=await browser.newContext();const page=await context.newPage();page.setDefaultTimeout(7000);
  page.on('pageerror',error=>result.pageErrors.push(error.message));page.on('response',response=>{if(response.status()>=400)result.badResponses.push([new URL(response.url()).pathname,response.status()]);});
  result.stage='login';await page.goto(`${config.origin}/pilot/otiz/snapshots/821`);assert.equal(new URL(page.url()).pathname,'/pilot/otiz/login');await page.locator('input[name="email"]').fill(config.email);await Promise.all([page.waitForNavigation(),page.locator('button[type="submit"]').click()]);await page.locator('input[name="password"]').fill(config.password);await Promise.all([page.waitForNavigation(),page.locator('button[type="submit"]').click()]);assert.equal(new URL(page.url()).pathname,'/pilot/otiz/snapshots/821');
  result.stage='desktop details';await page.locator('[data-otiz-object="8821"] button').click();const drawer=page.locator('[data-otiz-drawer][data-object-id="8821"]');assert.equal(await drawer.count(),1);const details=drawer.locator('[data-installer-allocation-details]');assert.equal(await details.count(),3);const anna=details.filter({hasText:'Анна Монтажник'});await anna.locator('summary').click();for(const text of ['Т-01','31.08.2026','123,45 ₽','23,00 %','КТУ','1,17','Доля','31,00 %','Распоряжение № 7','Итог работника в расчёте','33,33 ₽'])assert.match(await anna.innerText(),new RegExp(text.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));assert.doesNotMatch(await anna.innerText(),/Просрочка по объекту/);assert.match(await drawer.innerText(),/Просрочка по объекту/);assert.doesNotMatch(await drawer.innerText(),/НОВЫЙ ТЕКУЩИЙ УЧАСТНИК/);assert.equal(await drawer.locator('script').count(),0);await page.screenshot({path:path.join(config.artifacts,'allocation-desktop.png'),fullPage:true});
  result.stage='narrow readable';await page.setViewportSize({width:390,height:844});const boris=details.filter({hasText:'<img src=x onerror=alert(1)> & Монтажник'});await boris.locator('summary').click();const basis=boris.getByText(/Длинное сохранённое основание участия/);assert.equal(await basis.count(),1);const bodyWidth=await page.locator('body').evaluate(element=>({client:element.clientWidth,scroll:element.scrollWidth}));assert.ok(bodyWidth.scroll<=bodyWidth.client+1,`page overflow ${JSON.stringify(bodyWidth)}`);const box=await basis.boundingBox();assert.ok(box&&box.width>0&&box.x>=0&&box.x+box.width<=390,'long basis remains in narrow viewport');for(const value of ['77,00 %','0,93','69,00 %','90,12 ₽'])assert.match(await boris.innerText(),new RegExp(value.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));await page.screenshot({path:path.join(config.artifacts,'allocation-narrow.png'),fullPage:true});
  result.stage='empty state';await page.locator('[data-shlz-drawer-close]').first().click();await page.locator('[data-otiz-object="8822"] button').click();assert.match(await page.locator('[data-otiz-drawer][data-object-id="8822"]').innerText(),/В этом расчёте распределение по работникам не сохранено/);
  assert.deepEqual(result.pageErrors,[]);assert.deepEqual(result.badResponses.filter(([url])=>url!=='/favicon.ico'),[]);result.stage='complete';
}catch(error){result.failure=error.stack||String(error);throw error;}finally{fs.writeFileSync(config.result,JSON.stringify(result,null,2),{mode:0o600});if(browser)await browser.close();}
