import fs from 'node:fs';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),c=JSON.parse(fs.readFileSync(process.argv[2],'utf8'));
const {chromium}=require(c.playwright),browser=await chromium.launch({headless:true});
const check=(value,message)=>{if(!value)throw new Error(message);};
try {
 const context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage(),uiFailures=[];const uiCheck=(value,message)=>{if(!value)uiFailures.push(message);};
 const pageErrors=[];page.on('pageerror',e=>pageErrors.push(e.message));const assetFailures=[];page.on('response',r=>{if(new URL(r.url()).pathname.startsWith('/pilot/assets/')&&r.status()>=400)assetFailures.push(r.status()+' '+r.url());});
 page.on('requestfailed',request=>{if(new URL(request.url()).pathname.startsWith('/pilot/assets/'))assetFailures.push('requestfailed '+request.url());});
 await page.goto(c.origin+'/pilot/login');await page.locator('[name=email]').fill(c.email);await page.locator('[name=email]').locator('xpath=ancestor::form').locator('button[type=submit]').click();await page.locator('[name=password]').fill(c.password);
 await Promise.all([page.waitForResponse(r=>r.url().endsWith('/pilot/login')&&r.status()===303),page.locator('[name=password]').locator('xpath=ancestor::form').locator('button[type=submit]').click()]);
 const card=await page.goto(c.origin+'/pilot/objects/4512');check(card.status()===200,'INTENDED_RED Yii preopening browser card');
 const stylesheets=await page.locator('link[rel=stylesheet]').evaluateAll(links=>links.filter(link=>new URL(link.href).origin===location.origin).map(link=>({url:link.href,loaded:link.sheet!==null})));
 check(stylesheets.length>0&&stylesheets.every(sheet=>sheet.loaded),'all declared stylesheets actually loaded: '+JSON.stringify(stylesheets));
 const policy=card.headers()['content-security-policy'];const directives=new Map(policy.split(';').map(x=>x.trim().split(/\s+/)).filter(x=>x[0]).map(([key,...values])=>[key,values]));for(const key of ['script-src','connect-src'])check(JSON.stringify(directives.get(key))===JSON.stringify(["'self'"]),'exact '+key+' policy');for(const forbidden of ['unsafe-inline','unsafe-eval','blob:','worker-src'])check(!policy.includes(forbidden),'no broadened CSP '+forbidden);
 await page.locator('a[href$="/assignment-order/prepare"],a[href$="/assignment-order/selection"]').first().click();await page.waitForURL(c.origin+'/pilot/objects/4512/assignment-order/selection');
 const selection=page.locator('[data-selection-picker]');await page.setViewportSize({width:320,height:568});const selectionTrigger=selection.locator('[data-dialog-open]');await selectionTrigger.focus();await page.keyboard.press('Enter');const installerDialog=page.locator('[data-installer-dialog][open]');await installerDialog.waitFor();const dialogGeometry=await installerDialog.evaluate(el=>{const r=el.getBoundingClientRect(),body=el.querySelector('.shlz-modal__body'),footer=el.querySelector('.shlz-modal__footer');return{left:r.left,right:r.right,top:r.top,bottom:r.bottom,viewportWidth:innerWidth,viewportHeight:innerHeight,bodyOverflow:getComputedStyle(body).overflowY,footerVisible:Boolean(footer&&footer.getBoundingClientRect().bottom<=innerHeight+1),focusInside:el.contains(document.activeElement)};});check(dialogGeometry.left>=0&&dialogGeometry.right<=dialogGeometry.viewportWidth&&dialogGeometry.top>=0&&dialogGeometry.bottom<=dialogGeometry.viewportHeight,'INTENDED_RED selection dialog uses actual mobile viewport geometry');check(dialogGeometry.bodyOverflow==='auto'||dialogGeometry.bodyOverflow==='scroll','INTENDED_RED selection dialog body owns scroll');check(dialogGeometry.footerVisible&&dialogGeometry.focusInside,'INTENDED_RED selection dialog footer and focus remain reachable');await page.keyboard.press('Escape');check(await installerDialog.count()===0,'INTENDED_RED Escape closes selection dialog');check(await selectionTrigger.evaluate(el=>el===document.activeElement),'INTENDED_RED selection dialog returns focus');await selectionTrigger.click();await page.locator('[data-installer-dialog][open]').waitFor();await page.locator('[data-installer-search]').fill('7001');await page.locator('[data-result-id="7001"] input[type=checkbox]').focus();await page.keyboard.press('Space');await page.locator('[data-dialog-apply]').focus();await page.keyboard.press('Enter');
 await Promise.all([page.waitForResponse(r=>r.url().endsWith('/assignment-order/selection')&&r.request().method()==='POST'&&r.status()===303),selection.getByRole('button',{name:'Сохранить состав',exact:true}).click()]);await page.waitForURL(c.origin+'/pilot/objects/4512/assignment-order/selection');
 const templateResponse=context.waitForEvent('response',r=>r.url().endsWith('/template')&&r.request().method()==='POST');await page.getByRole('button',{name:'Сформировать шаблон',exact:true}).click();const template=await templateResponse;check(template.status()===200,'real template POST200');for(const other of context.pages())if(other!==page)await other.close();
 await page.locator('a[href$="/originals/submit"]').first().click();await page.locator('[data-original-upload-form]').waitFor();const originalUrl=page.url();
 const deliveredReceipts=new Map();
 let lost=true,firstReceipt=null,resolveLost;const lostDone=new Promise(resolve=>{resolveLost=resolve;});
 await page.route('**/originals',async route=>{
  if(lost&&route.request().method()==='POST'){
   lost=false;const accepted=await route.fetch();check(accepted.status()===201,'server accepted before simulated response loss');firstReceipt=await accepted.json();await route.abort('failed');resolveLost();
  } else {
   // Capture the real server response before navigation disposes its browser body.
   const delivered=await route.fetch();const receipt=await delivered.json();deliveredReceipts.set(receipt.requestId,receipt);
   await route.fulfill({response:delivered});
  }
 });
 const fillDate=async(scope,name,iso)=>{const hidden=scope.locator(`.shlz-date-picker input[type="hidden"][name="${name}"]`),visible=hidden.locator('xpath=ancestor::*[contains(concat(" ",normalize-space(@class)," ")," shlz-date-picker ")]').locator('.shlz-date-field__input'),[year,month,day]=iso.split('-');await visible.fill(`${day}.${month}.${year}`);await visible.press('Tab');check(await hidden.inputValue()===iso,name+' public picker ISO');};let form=page.locator('[data-original-upload-form]');await form.locator('[name=original]').setInputFiles({name:'signed.pdf',mimeType:'application/pdf',buffer:Buffer.from(c.pdf,'base64')});await fillDate(form,'documentDate','2026-09-01');await form.locator('[name=compositionConfirmed]').check();const intent=await form.locator('[name=requestId]').inputValue();
 await form.locator('[data-original-submit]').click();await lostDone;await page.waitForFunction(()=>{const b=document.querySelector('[data-original-submit]'),s=document.querySelector('[data-original-status]');return b&&!b.disabled&&s&&s.textContent.length>0;});
 check(page.url()===originalUrl,'network failure is not false success');check(await form.locator('[name=requestId]').inputValue()===intent,'network retry retains intent');check(await form.locator('[name=original]').evaluate(e=>e.files.length)===1,'network retry retains file');
 await Promise.all([page.waitForResponse(r=>r.url().endsWith('/originals')&&r.request().method()==='POST'&&r.status()===200),form.locator('[data-original-submit]').click()]);await page.waitForURL(c.origin+'/pilot/objects/4512');await page.getByText('Готов к открытию',{exact:true}).first().waitFor();
 await page.setViewportSize({width:390,height:844});await page.goto(originalUrl);check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'mobile original form overflow');form=page.locator('[data-original-upload-form]');await form.locator('[name=original]').setInputFiles({name:'corrected.pdf',mimeType:'application/pdf',buffer:Buffer.from(c.pdf2,'base64')});await fillDate(form,'documentDate','2026-09-02');await form.locator('[name=correctionReason]').fill('Уточнена дата и файл');await form.locator('[name=compositionConfirmed]').check();
 const correctedResponse=page.waitForResponse(r=>r.url().endsWith('/originals')&&r.request().method()==='POST'&&r.status()===201);await form.locator('[data-original-submit]').click();const deliveredCorrection=await correctedResponse;const postedCorrection=JSON.parse(Buffer.from(deliveredCorrection.request().headers()['x-fmonitor-original'],'base64').toString('utf8'));const corrected=deliveredReceipts.get(postedCorrection.requestId);check(Boolean(corrected),'actual correction receipt retained before navigation');await page.waitForURL(c.origin+'/pilot/objects/4512');
 await page.goto(originalUrl);await page.locator('a[href$="/originals/history"]').first().click();await page.getByRole('heading',{name:'История оригинала',exact:true}).waitFor();
 for(const [revision,encoded] of [[firstReceipt.currentRevisionId,c.pdf],[corrected.currentRevisionId,c.pdf2]]){const [download]=await Promise.all([page.waitForEvent('download'),page.locator('a[href$="/'+revision+'/download"]').click()]);check(download.suggestedFilename()==='assignment-order-original.pdf','safe downloaded filename');const file=await download.path();check(fs.readFileSync(file).equals(Buffer.from(encoded,'base64')),'browser exact historical bytes');}
 await page.goto(c.origin+'/pilot/objects/4512');
 check(await page.getByRole('heading',{level:1}).isVisible(),'object identity heading visible');check((await page.getByRole('heading',{level:1}).innerText()).includes('Очень длинный адрес'),'long address rendered');check(await page.locator('.fm2-registration').getByText('Регистрационный номер',{exact:true}).isVisible(),'registration identity visible');check(await page.locator('.shlz-status').first().isVisible(),'business status visible');check(await page.locator('.fm2-next-action .shlz-button--primary:visible').count()===1,'exactly one permitted primary action');for(const name of ['Сроки и готовность','Команда','Документы','История'])check(await page.getByRole('tab',{name,exact:true}).count()===1,'semantic tab '+name);await page.getByRole('tab',{name:'Команда',exact:true}).click();check(await page.getByText('Инженер строительного контроля',{exact:true}).first().isVisible(),'engineer context visible');await page.getByRole('tab',{name:'Сроки и готовность',exact:true}).click();check((await page.getByRole('status').allTextContents()).some(x=>x.includes('повреждена')),'corrupt technical state visible');
 const opening=page.locator('form').filter({has:page.locator('[name=action][value=open_confirmed]')});await fillDate(opening,'actualStartDate','2026-09-03');
 await Promise.all([page.waitForResponse(r=>r.url().endsWith('/execution')&&r.request().method()==='POST'&&r.status()===303),opening.getByRole('button',{name:'Открыть работы',exact:true}).click()]);await page.waitForURL(c.origin+'/pilot/objects/4512');
 await page.waitForFunction(()=>!document.querySelector('[name=action][value=open_confirmed]'));
 check(await page.locator('[name=action][value=open_confirmed]').count()===0,'opened card no repeated opening form');await page.setViewportSize({width:1440,height:1000});check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'desktop overflow');await page.screenshot({path:c.artifacts+'/preopening-desktop.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'mobile overflow');await page.screenshot({path:c.artifacts+'/preopening-mobile.png',fullPage:true});
 c.email='engineer.preopening@shlz.ru';
 const noJs=await browser.newContext({javaScriptEnabled:false,viewport:{width:390,height:844}}),noJsPage=await noJs.newPage();await noJsPage.goto(c.origin+'/pilot/login');await noJsPage.locator('[name=email]').fill(c.email);await Promise.all([noJsPage.waitForNavigation(),noJsPage.locator('[name=email]').locator('xpath=ancestor::form').locator('button[type=submit]').click()]);await noJsPage.locator('[name=password]').fill(c.password);await Promise.all([noJsPage.waitForNavigation(),noJsPage.locator('[name=password]').locator('xpath=ancestor::form').locator('button[type=submit]').click()]);const noJsCard=await noJsPage.goto(c.origin+'/pilot/objects/4512');check(noJsCard.status()===200,'JavaScript-disabled card remains reachable');check(await noJsPage.getByRole('heading',{level:1}).isVisible(),'JavaScript-disabled SSR content visible');const noJsLink=noJsPage.locator('a[href="/pilot/objects/4512/checklist"]').first();check(await noJsLink.isVisible(),'JavaScript-disabled native workflow link visible');await Promise.all([noJsPage.waitForURL('**/pilot/objects/4512/checklist'),noJsLink.click()]);check(new URL(noJsPage.url()).pathname==='/pilot/objects/4512/checklist','JavaScript-disabled native workflow link operates');await noJs.close();
 const reader=await browser.newContext({viewport:{width:390,height:844}}),readerPage=await reader.newPage();await readerPage.goto(c.origin+'/pilot/login');await readerPage.locator('[name=email]').fill(c.readerEmail);await Promise.all([readerPage.waitForNavigation(),readerPage.locator('[name=email]').locator('xpath=ancestor::form').locator('button[type=submit]').click()]);await readerPage.locator('[name=password]').fill(c.password);await Promise.all([readerPage.waitForNavigation(),readerPage.locator('[name=password]').locator('xpath=ancestor::form').locator('button[type=submit]').click()]);await readerPage.goto(c.origin+'/pilot/objects/4512');check(await readerPage.locator('.fm2-next-action .shlz-button--primary').count()===0,'permission-limited actor has no forbidden primary action');check(await readerPage.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'permission-limited long degraded card has no overflow');await reader.close();
 for(const width of [1440,1024,768,320]){await page.setViewportSize({width,height:900});uiCheck(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'object card no page overflow '+width);}
 await page.setViewportSize({width:640,height:900});uiCheck(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'object card effective 200 percent reflow');await page.keyboard.press('Tab');uiCheck(await page.evaluate(()=>document.activeElement!==document.body&&getComputedStyle(document.activeElement).outlineStyle!=='none'),'object card visible keyboard focus');const firstFocus=await page.evaluateHandle(()=>document.activeElement);await page.keyboard.press('Tab');await page.keyboard.press('Shift+Tab');uiCheck(await page.evaluate(first=>document.activeElement===first,firstFocus),'object card reverse keyboard order');await firstFocus.dispose();await page.emulateMedia({reducedMotion:'reduce'});uiCheck(await page.evaluate(()=>[...document.querySelectorAll('main *')].every(e=>{const s=getComputedStyle(e);return s.animationDuration==='0s'&&(!s.transitionProperty.includes('transform')||s.transitionDuration==='0s');})),'reduced motion removes spatial transitions');
 const touch=await browser.newContext({storageState:await context.storageState(),hasTouch:true,isMobile:true,viewport:{width:390,height:844}}),touchPage=await touch.newPage();await touchPage.goto(c.origin+'/pilot/objects/4512');uiCheck(await touchPage.evaluate(()=>matchMedia('(pointer: coarse)').matches),'coarse pointer context');uiCheck(await touchPage.evaluate(()=>[...document.querySelectorAll('button,.shlz-button')].filter(e=>e.getClientRects().length>0).every(e=>{const r=e.getBoundingClientRect();return r.width>=44&&r.height>=44;})),'object card coarse targets 390');await touch.close();if(uiFailures.length)throw new Error('INTENDED_RED object card UI: '+uiFailures.join(' | '));
 check(pageErrors.length===0,'no uncaught browser errors: '+pageErrors.join(','));check(assetFailures.length===0,'assets all served: '+assetFailures.join(','));const logout=page.getByRole('button',{name:'Выйти',exact:true});check(await logout.isVisible(),'mobile logout');await logout.click();await page.waitForURL(c.origin+'/pilot/login');
 fs.writeFileSync(c.result,JSON.stringify({firstReceipt,corrected,intent,networkRetry:true,assetFailures}));
} finally {await browser.close();}
