import fs from 'node:fs';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const c=JSON.parse(fs.readFileSync(process.argv[2],'utf8'));
const {chromium}=require(c.playwright);
const browser=await chromium.launch({headless:true});
const assert=(condition,message)=>{if(!condition)throw new Error(message);};
try{
 const context=await browser.newContext({viewport:{width:1440,height:1000}});
 const page=await context.newPage();const assetFailures=[];page.on('response',r=>{if(new URL(r.url()).pathname.startsWith('/pilot/assets/')&&r.status()>=400)assetFailures.push(r.status()+' '+new URL(r.url()).pathname);});
 await page.goto(c.origin+'/pilot/login');
 await page.locator('[name=email]').fill(c.email);
 await page.locator('[name=email]').locator('xpath=ancestor::form').locator('button[type=submit]').click();
 await page.locator('[name=password]').fill(c.password);
 await Promise.all([page.waitForResponse(r=>r.url().endsWith('/pilot/login')&&r.request().method()==='POST'&&r.status()===303),page.locator('[name=password]').locator('xpath=ancestor::form').locator('button[type=submit]').click()]);
 const initial=await page.goto(c.origin+'/pilot/admin/users');
 assert(initial.status()===200,'INTENDED_RED YII2-USER-ACCESS-001 real browser users route missing');
 const invite=page.locator('form[action="/pilot/admin/users/invite"]');
 await invite.locator('[name=email]').fill('browser.person@shlz.ru');await invite.locator('[name=fullName]').fill('Browser Recipient');
 await Promise.all([page.waitForResponse(r=>r.url().endsWith('/pilot/admin/users/invite')&&r.status()===303),invite.locator('button[type=submit]').click()]);
 await page.waitForURL(c.origin+'/pilot/admin/users');
 const activationLink=page.locator('a[href*="/pilot/activate?token="]').first();await activationLink.waitFor();const first=await activationLink.getAttribute('href');
 await page.goto(c.origin+'/pilot/admin/roles');await page.goto(c.origin+'/pilot/admin/users');assert(await page.locator('a[href*="/pilot/activate?token="]').count()===0,'old invitation is not redisclosed');
 let row=page.locator('tr[data-user-id]').filter({hasText:'browser.person@shlz.ru'});await row.waitFor();const userId=Number(await row.getAttribute('data-user-id'));
 const reissue=row.locator('form[action$="/invitation"]');await Promise.all([page.waitForResponse(r=>r.url().endsWith('/invitation')&&r.status()===303),reissue.locator('button[type=submit]').click()]);
 await page.waitForURL(c.origin+'/pilot/admin/users');const nextLink=page.locator('a[href*="/pilot/activate?token="]').first();await nextLink.waitFor();const next=await nextLink.getAttribute('href');assert(first!==next,'reissue gives a new link');
 const recipientContext=await browser.newContext();const recipient=await recipientContext.newPage();await recipient.goto(new URL(first,c.origin).href);assert(await recipient.locator('[name=password]').count()===0,'old link revoked');
 await recipient.goto(new URL(next,c.origin).href);await recipient.locator('[name=password]').fill('Browser activation secret 2026');await recipient.locator('[name=passwordConfirmation]').fill('Browser activation secret 2026');
 await Promise.all([recipient.waitForResponse(r=>r.url().endsWith('/pilot/activate')&&r.request().method()==='POST'),recipient.locator('form[action="/pilot/activate"] button[type=submit]').click()]);
 await recipient.getByText('Учётная запись активирована',{exact:true}).waitFor();
 await recipient.locator('a[href="/pilot/login"]').click();await recipient.locator('[name=email]').fill('browser.person@shlz.ru');await recipient.locator('[name=email]').locator('xpath=ancestor::form').locator('button[type=submit]').click();await recipient.locator('[name=password]').fill('Browser activation secret 2026');
 await Promise.all([recipient.waitForResponse(r=>r.url().endsWith('/pilot/login')&&r.request().method()==='POST'&&r.status()===303),recipient.locator('[name=password]').locator('xpath=ancestor::form').locator('button[type=submit]').click()]);
 await page.goto(c.origin+'/pilot/admin/users');row=page.locator(`tr[data-user-id="${userId}"]`);const roleForm=row.locator('form[action$="/roles"]');await roleForm.locator('[name=roleId]').selectOption('9212');
 await Promise.all([page.waitForResponse(r=>r.url().endsWith('/roles')&&r.request().method()==='POST'&&r.status()===303),roleForm.locator('button[type=submit]').click()]);await page.waitForURL(c.origin+'/pilot/admin/users');
 row=page.locator(`tr[data-user-id="${userId}"]`);assert(await row.textContent().then(t=>t.includes('Инженер')),'assigned role visible');
 const block=row.locator('form[action$="/status"]');await Promise.all([page.waitForResponse(r=>r.url().endsWith('/status')&&r.status()===303),block.getByRole('button',{name:'Заблокировать',exact:true}).click()]);await page.waitForURL(c.origin+'/pilot/admin/users');
 const denied=await recipientContext.request.get(c.origin+'/pilot/admin/roles',{maxRedirects:0});assert(denied.status()===303,'blocked session is invalidated');
 row=page.locator(`tr[data-user-id="${userId}"]`);await Promise.all([page.waitForResponse(r=>r.url().endsWith('/status')&&r.status()===303),row.getByRole('button',{name:'Восстановить',exact:true}).click()]);await page.waitForURL(c.origin+'/pilot/admin/users');
 const search=page.locator('[data-user-search]');await search.fill('Browser Recipient');assert(await page.locator('tr[data-user-id]:visible').count()===1,'search filters rows');await search.fill('');
 await page.locator('label[for=uf-active]').click();assert(await page.locator(`tr[data-user-id="${userId}"]:visible`).count()===1,'active filter includes restored user');await page.locator('label[for=uf-all]').click();
 const filter=page.locator('[data-role-filter]').getByRole('combobox');
 if(await filter.evaluate(el=>el.tagName)==='SELECT')await filter.selectOption('9212');
 else {await filter.click();await page.locator('[data-role-filter]').getByRole('option',{name:/Инженер/}).click();}
 assert(await page.locator(`tr[data-user-id="${userId}"]:visible`).count()===1,'role filter includes assigned role');
 assert(await page.locator('tr[data-user-id="9401"]:visible').count()===0,'role filter hides unassigned row');
 assert(await page.locator('body.shlz-scope').count()===1,'corporate shlz scope retained');assert(assetFailures.length===0,'assets unavailable: '+assetFailures.join(', '));
 await page.screenshot({path:c.artifacts+'/admin-users.png',fullPage:true});
 const logout=page.locator('form[action="/pilot/logout"]');await Promise.all([page.waitForResponse(r=>r.url().endsWith('/pilot/logout')&&r.status()===303),logout.locator('button[type=submit]').click()]);await page.waitForURL(c.origin+'/pilot/login');
 fs.writeFileSync(c.result,JSON.stringify({userId}));await recipientContext.close();await context.close();
 console.log('PASS: YII2-USER-ACCESS-001 browser invite/reissue/activate/login/role/block/unblock/filter/logout');
}finally{await browser.close();}
