<?php
declare(strict_types=1);
require dirname(__DIR__).'/bootstrap.php';require __DIR__.'/PreopeningFixture.php';
$f=null;try{$f=new PreopeningFixture(dirname(__DIR__,2));$f->start();$p=$f->p;if(getenv('FMONITOR_FIXTURE_REACHABILITY')==='object-details-yii-fixture'){$probe=[];assertSameValue(303,$f->login($probe,18)['status'],'fixture login');assertSameValue(200,$f->request('GET','/pilot/objects/4512',[],$probe)['status'],'card fixture');assertSameValue(true,$f->token($probe)!=='','CSRF fixture');echo"FIXTURE_REACHABLE: object-details-yii-fixture\n";exit(0);}$guest=[];$beforeGuest=$f->facts();assertSameValue(303,$f->request('POST','/pilot/objects/4512/details',[], $guest)['status'],'INTENDED_RED guest details route authenticates before lookup');assertSameValue($beforeGuest,$f->facts(),'guest no facts');$actor=[];assertSameValue(303,$f->login($actor,18)['status'],'FKR login');$f->insert($p.'fm2_pilot_role_permissions',['role_id'=>1,'permission'=>'objects.details.edit']);
 $card=$f->request('GET','/pilot/objects/4512',[],$actor);assertSameValue(200,$card['status'],'card');assertSameValue(true,str_contains($card['body'],'data-object-details-edit'),'INTENDED_RED A13 compact edit trigger');assertSameValue(false,str_contains($card['body'],'name="shaftBp"'),'Kshah absent');foreach(['Идентификация и размещение','Классификация оборудования','shlz-modal','shlz-modal__close']as$text)assertSameValue(true,str_contains($card['body'],$text),'modal contract '.$text);
 $before=$f->facts();$csrf=$f->token($actor);$result=$f->form('/pilot/objects/4512/details',['_csrf'=>$csrf,'requestId'=>'22222222-2222-4222-8222-222222222451','expectedRevision'=>'0','zavnumber'=>'00123-А','floors'=>'12','pitmaterial'=>'9'],$actor);assertSameValue([303,'/pilot/objects/4512#history'],[$result['status'],$result['headers']['location'][0]??null],'INTENDED_RED canonical POST success');
 $reload=$f->request('GET','/pilot/objects/4512',[],$actor);foreach(['00123-А','Данные объекта изменены','Заводской номер','Не указано','ts.grishin']as$text)assertSameValue(true,str_contains($reload['body'],$text),'A8/A13 reload history '.$text);assertSameValue(1,count($f->facts()['fm2_object_detail_edit_events']??[]),'one event');
 foreach([['shaftBp'=>'11500'],['ptoactdate'=>'2026-09-21'],['floors'=>'bad']]as$i=>$patch){$beforeReject=$f->facts();$r=$f->form('/pilot/objects/4512/details',array_merge(['_csrf'=>$csrf,'requestId'=>sprintf('22222222-2222-4222-8222-%012d',500+$i),'expectedRevision'=>'1'],$patch),$actor);assertSameValue(422,$r['status'],'invalid payload');assertSameValue($beforeReject,$f->facts(),'invalid HTTP no facts');}
 foreach(['GET','HEAD','PUT','PATCH','DELETE']as$method){$beforeMethod=$f->facts();$r=$f->request($method,'/pilot/objects/4512/details',[],$actor);assertSameValue($method==='GET'||$method==='HEAD'?405:405,$r['status'],'method gate '.$method);assertSameValue($beforeMethod,$f->facts(),'method no facts');}
 $beforeCsrf=$f->facts();assertSameValue(400,$f->form('/pilot/objects/4512/details',['requestId'=>'22222222-2222-4222-8222-222222222599','expectedRevision'=>'1','floors'=>'13'],$actor)['status'],'CSRF rejection');assertSameValue($beforeCsrf,$f->facts(),'CSRF no facts');
 assertSameValue(false,$before===$f->facts(),'accepted POST changes facts');
 echo "PASS: OBJECT-DETAILS-EDITING-001 Yii HTTP card and history\n";
}finally{if($f instanceof PreopeningFixture)$f->close();}
