<?php
declare(strict_types=1);
require dirname(__DIR__).'/bootstrap.php';require __DIR__.'/InstallerDirectoryFixture.php';
// YII2-INSTALLER-DIRECTORY-001 A1-A7: real Yii HTTP; SQL only fixture/audit/fault setup.
$f=null;
try{
 $f=new InstallerDirectoryFixture(dirname(__DIR__,2));$f->open();$h=$f->http;$before=$h->facts();
 $first=$f->get();if($first['status']===404)echo "INTENDED_RED Yii installer directory route absent\n";assertSameValue(200,$first['status'],'directory GET');assertSameValue($before,$h->facts(),'GET read-only');
 $dom=new DOMDocument();@$dom->loadHTML('<?xml encoding="UTF-8">'.$first['body']);$xp=new DOMXPath($dom);$rows=$xp->query('//tbody/tr');assertSameValue(50,$rows->length,'page size50');assertSameValue(1,$xp->query('//*[@data-directory-summary="total" and normalize-space(.)="125"]')->length,'summary total');assertSameValue(1,$xp->query('//*[@data-directory-summary="working" and normalize-space(.)="84"]')->length,'summary working');assertSameValue(1,$xp->query('//*[@data-directory-summary="dismissed" and normalize-space(.)="41"]')->length,'summary dismissed');assertSameValue(1,$xp->query('//*[@data-directory-summary="assigned" and normalize-space(.)="5"]')->length,'summary assigned');assertSameValue(true,str_contains($rows->item(0)->textContent,'Монтажник 001')&&str_contains($rows->item(49)->textContent,'Монтажник 050'),'fio then tab order');foreach(['125 сотрудников','10.09.2026 07:40','ORDER-5001-1','Адрес 5001','ORDER-5010-1','Адрес 5010','Монтажник 001','таб. 000001']as$text)assertSameValue(true,str_contains($first['body'],$text),'literal projection '.$text);$links=$xp->query('//tbody/tr[1]//a[contains(@class,"fm2-assignment-link")]');assertSameValue(['/pilot/objects/5001','/pilot/objects/5010'],[$links->item(0)?->getAttribute('href'),$links->item(1)?->getAttribute('href')],'stable assignment order');foreach(['ORDER-5011','ORDER-5012','ORDER-5013','ORDER-5014']as$text)assertSameValue(false,str_contains($first['body'],$text),'excluded assignment '.$text);
 assertSameValue(1,$xp->query('//nav[contains(concat(" ",normalize-space(@class)," ")," fm2-pagination ")]//a[@aria-current="page"]')->length,'one current pagination page');assertSameValue(1,$xp->query('//nav[@aria-label="Основная навигация"]//a[@aria-current="page" and @href="/pilot/installers"]')->length,'directory sidebar current');
 $third=$f->get('?page=3');$dom=new DOMDocument();@$dom->loadHTML('<?xml encoding="UTF-8">'.$third['body']);$thirdXp=new DOMXPath($dom);assertSameValue(25,$thirdXp->query('//tbody/tr')->length,'third page25');assertSameValue(true,str_contains($third['body'],'Монтажник 101')&&str_contains($third['body'],'Монтажник 125'),'third ordered bounds');
 foreach([['?status=dismissed&availability=free&page=1','40 сотрудников'],['?availability=assigned','5 сотрудников'],['?status=employed','84 сотрудников']]as[$query,$literal]){$filtered=$f->get($query);assertSameValue(true,str_contains($filtered['body'],$literal),'filter '.$literal);}
 $filtered=$f->get('?status=dismissed&availability=free&page=1');assertSameValue(true,str_contains($filtered['body'],'status=dismissed')&&str_contains($filtered['body'],'availability=free'),'pagination preserves filters');
 foreach(['Монтажник 125','00-125']as$needle){$search=$f->get('?q='.rawurlencode($needle));assertSameValue(true,str_contains($search['body'],'Монтажник 125'),'search '.$needle);assertSameValue(false,str_contains($search['body'],'<script>Монтажник</script>'),'escaped source');assertSameValue(true,str_contains($search['body'],'&lt;script&gt;'),'escaped visible');}$none=$f->get('?q='.rawurlencode('НетТакогоМонтажника'));assertSameValue(true,str_contains($none['body'],'Ничего не найдено'),'filtered empty distinct');
 foreach(['?status=bad','?availability=bad','?page=0','?page=01','?page=4','?page=999999999999999999999','?q%5B%5D=x','?unknown=x','?status=employed&status=dismissed','?q=%ZZ','?q='.rawurlencode(str_repeat('Ж',121))]as$q){$before=$h->facts();assertSameValue(400,$f->get($q)['status'],'closed query '.$q);assertSameValue($before,$h->facts(),'invalid query no facts');}
 $head=$h->request('HEAD','/pilot/installers',[],$f->cookies);assertSameValue([200,''],[$head['status'],$head['body']],'HEAD empty');foreach(['content-type','content-security-policy','cache-control']as$name)assertSameValue($first['headers'][$name]??null,$head['headers'][$name]??null,'HEAD header '.$name);foreach(['POST','PUT','DELETE']as$method){$r=$h->request($method,'/pilot/installers',[],$f->cookies);assertSameValue([405,'GET, HEAD'],[$r['status'],$r['headers']['allow'][0]??null],'method '.$method);}
 $denied=[];$h->login($denied,96);assertSameValue(403,$h->request('GET','/pilot/installers',[],$denied)['status'],'exact grant denied');$guest=[];$r=$h->request('GET','/pilot/installers?status=dismissed',[],$guest);assertSameValue([303,'/pilot/login'],[$r['status'],$r['headers']['location'][0]??null],'guest redirect');$login=$h->login($guest);assertSameValue([303,'/pilot/installers?status=dismissed'],[$login['status'],$login['headers']['location'][0]??null],'safe return retained');
 $h->db->query("UPDATE {$h->p}fm2_workforce_catalog SET reconciliation_state='missing_from_delivery'");$empty=$f->get();assertSameValue(200,$empty['status'],'empty catalogue');assertSameValue(true,str_contains($empty['body'],'Каталог монтажников пока не загружен'),'empty message');
 $h->db->query("UPDATE {$h->p}fm2_workforce_catalog SET reconciliation_state='delivered' WHERE installer_tab_id=1");foreach([["employment_status='employed',fio='   '",'empty name'],["fio='Монтажник 001',workforce_source_updated_at='bad-time'",'invalid time'],["workforce_source_updated_at='2026-09-10T07:40:00+03:00',dismissal_effective_at='0000-00-00'",'invalid date']]as[$set,$label]){$h->db->query("UPDATE {$h->p}fm2_workforce_catalog SET $set WHERE installer_tab_id=1");$snapshot=$h->facts();$bad=$f->get();assertSameValue(['503','60'],[(string)$bad['status'],$bad['headers']['retry-after'][0]??null],$label);assertSameValue(false,str_contains($bad['body'],$h->p)||str_contains($bad['body'],'bad-time'),'sanitized503');assertSameValue($snapshot,$h->facts(),$label.' no writes');}
 $h->db->query("UPDATE {$h->p}fm2_workforce_catalog SET fio='Монтажник 001',employment_status='employed',workforce_source_updated_at='2026-09-10T07:40:00+03:00',dismissal_effective_at=NULL WHERE installer_tab_id=1");$table=$h->p.'fm2_workforce_catalog';$before=$h->facts();$h->db->query("RENAME TABLE $table TO {$table}_saved");try{$bad=$f->get();assertSameValue(['503','60'],[(string)$bad['status'],$bad['headers']['retry-after'][0]??null],'missing schema');assertSameValue(400,$f->get('?status=bad')['status'],'invalid shape rejected before DB read');}finally{$h->db->query("RENAME TABLE {$table}_saved TO $table");}assertSameValue($before,$h->facts(),'missing schema no repair');
 $f->restart(['FMONITOR_PROCESS_TABLE_PREFIX'=>'bad-prefix!']);$bad=$f->get();assertSameValue(['503','60'],[(string)$bad['status'],$bad['headers']['retry-after'][0]??null],'invalid prefix');$f->restart(['FMONITOR_DB_NAME'=>'missing_directory_database']);$bad=$f->get();assertSameValue(['503','60'],[(string)$bad['status'],$bad['headers']['retry-after'][0]??null],'unavailable configured DB');$f->restart();assertSameValue(200,$f->get()['status'],'configuration recovery');$f->routeNoLegacy();echo "PASS: YII2-INSTALLER-DIRECTORY-001 HTTP A1-A7\n";
}finally{if($f instanceof InstallerDirectoryFixture)$f->close();}
