<?php
declare(strict_types=1);
require dirname(__DIR__).'/bootstrap.php';
require __DIR__.'/ObjectQueueFixture.php';

// YII2-OPERATIONAL-DASHBOARD-REFINEMENT-001 R1-R8: agreed data/HTTP/browser seams.
$f=null;$browser=null;
try{
    $root=dirname(__DIR__,2);$f=new ObjectQueueFixture($root);$h=$f->http;$db=$f->db;$p=$f->p;$cutoff='2026-09-21';
    $db->query("UPDATE fm_maintable SET workdatestart='2026-09-12',workdateendadjusted='2026-10-20',plan_finish_date='2026-10-20' WHERE id=451201");
    $f->object(451202,6102,'needs_assignment_order','2026-09-21','Нужно распоряжение');$db->query("UPDATE fm_maintable SET workdateendadjusted='2026-09-27',plan_finish_date='2026-09-27' WHERE id=451202");
    $f->object(451203,6103,'assignment_order_prepared','2026-09-27','Готов к открытию');$f->order(6113,6103,1,7301);$db->query("UPDATE fm_maintable SET workdateendadjusted='2026-09-25',plan_finish_date='2026-09-25' WHERE id=451203");
    $f->object(451204,6104,'working','2026-09-28','Активность сегодня');$f->order(6114,6104,1,7301);$f->checklist(6104,1,1);$db->query("UPDATE {$p}fm2_checklist_operations SET device_time='2099-01-01T00:00:00+03:00',server_received_at='2026-09-21T10:00:00+03:00' WHERE installation_case_id=6104");
    $f->object(451205,6105,'working',null,'Закрытие документов');$db->query("UPDATE fm_maintable SET workdatestart='2026-09-31' WHERE id=451205");$f->order(6115,6105,1,7301);foreach(range(1,41)as$item)$f->checklist(6105,$item,$item);$db->query("UPDATE {$p}fm2_checklist_operations SET server_received_at='2026-09-14T10:00:00+03:00' WHERE installation_case_id=6105");
    $f->object(451206,6106,'working','2026-09-01','Работы завершены');$f->order(6116,6106,1,7301);$f->completion(6106,'pto_act');$f->completion(6106,'declaration');$db->query("UPDATE {$p}fm2_pilot_completion_facts SET recorded_at='2026-09-13T10:00:00+03:00' WHERE installation_case_id=6106");
    $f->object(451207,6107,'needs_assignment_change','2026-09-01','Требуется изменение');$f->order(6117,6107,1,7301);$f->completion(6107,'pto_act');$db->query("UPDATE {$p}fm2_pilot_completion_facts SET recorded_at='2026-09-06T10:00:00+03:00' WHERE installation_case_id=6107");
    $f->object(451208,6108,'working','2026-09-01','Старая фотография');$f->order(6118,6108,1,7301);$hash=str_repeat('a',64);$f->insert($p.'fm2_checklist_photos',['installation_case_id'=>6108,'section_id'=>1,'upload_operation_id'=>'99999999-9999-4999-8999-000000006108','sha256'=>$hash,'mime_type'=>'image/png','byte_size'=>4,'original_name'=>'evidence.png','storage_name'=>$hash.'.bin','actor_user_id'=>9101,'device_time'=>'2099-01-01T00:00:00+03:00','server_received_at'=>'2026-08-21T10:00:00+03:00','revoked_at'=>null]);
    foreach([[451209,6109,'2026-09-13'],[451210,6110,'2026-09-07'],[451211,6111,'2026-08-22']]as[$object,$case,$activity]){$f->object($object,$case,'working','2026-09-01','Граница активности '.$object);$f->order(10000+$case,$case,1,7301);$f->checklist($case,1,1);$db->query("UPDATE {$p}fm2_checklist_operations SET server_received_at='{$activity}T10:00:00+03:00' WHERE installation_case_id={$case}");}
    $f->object(451212,6112,'working','2026-09-01','Отозванное фото');$f->order(16112,6112,1,7301);$f->checklist(6112,1,1);$db->query("UPDATE {$p}fm2_checklist_operations SET server_received_at='2026-08-20T10:00:00+03:00' WHERE installation_case_id=6112");$hashRevoked=str_repeat('c',64);$f->insert($p.'fm2_checklist_photos',['installation_case_id'=>6112,'section_id'=>1,'upload_operation_id'=>'99999999-9999-4999-8999-000000006112','sha256'=>$hashRevoked,'mime_type'=>'image/png','byte_size'=>4,'original_name'=>'revoked.png','storage_name'=>$hashRevoked.'.bin','actor_user_id'=>9101,'device_time'=>'2026-09-20T10:00:00+03:00','server_received_at'=>'2026-09-20T10:00:00+03:00','revoked_at'=>'2026-09-20T11:00:00+03:00']);
    $f->object(451213,6113,'working','2026-09-01','Исправленный факт');$f->order(16113,6113,1,7301);$f->completion(6113,'pto_act');$rootFact=(int)$db->query("SELECT id FROM {$p}fm2_pilot_completion_facts WHERE installation_case_id=6113")->fetch_column();$db->query("UPDATE {$p}fm2_pilot_completion_facts SET recorded_at='2026-09-01T10:00:00+03:00' WHERE id={$rootFact}");$f->insert($p.'fm2_pilot_completion_fact_corrections',['root_fact_id'=>$rootFact,'version_no'=>1,'previous_correction_id'=>null,'previous_version_no'=>null,'fact_date'=>'2026-09-12','reason'=>'Исправлена дата','recorded_at'=>'2026-09-12T10:00:00+03:00','recorded_by_user_id'=>9101]);
    $f->object(451214,6114,'working','2026-09-01','Будущее свидетельство');$f->order(16114,6114,1,7301);$f->checklist(6114,1,1);$f->checklist(6114,2,2);$db->query("UPDATE {$p}fm2_checklist_operations SET server_received_at=CASE accepted_revision WHEN 1 THEN '2026-09-10T10:00:00+03:00' ELSE '2026-09-22T10:00:00+03:00' END WHERE installation_case_id=6114");
    $f->insert($p.'fm2_deadline_certificate_revisions',['id'=>701,'installation_case_id'=>6103,'revision_number'=>1,'previous_revision_id'=>null,'certificate_date'=>'2026-09-20','new_deadline'=>'2026-10-06','correction_reason'=>null,'actor_id'=>9101,'recorded_at'=>'2026-09-20T11:00:00+03:00','source_label'=>'Справка о переносе','source_locator'=>'fixture/701','pdf_sha256'=>str_repeat('b',64),'byte_size'=>4]);
    $f->insert($p.'fm2_deadline_certificate_roots',['installation_case_id'=>6103,'current_revision_id'=>701,'current_version'=>1]);
    foreach([[451220,6120,'2026-09-20'],[451221,6121,'2026-09-27'],[451222,6122,'2026-09-28'],[451223,6123,'2026-10-04'],[451224,6124,'2026-10-05'],[451229,6129,null],[451230,6130,'2026-09-31']]as[$object,$case,$start])$f->object($object,$case,'needs_assignment_order',$start,'Risk boundary '.$object);
    foreach([[451225,6125,'2026-10-04'],[451226,6126,'2026-10-05']]as[$object,$case,$start]){$f->object($object,$case,'assignment_order_prepared',$start,'Ready boundary '.$object);$f->order(16000+$case,$case,1,7301);}
    $f->object(451227,6127,'working','2026-10-04','Document closeout boundary');$f->order(16127,6127,1,7301);foreach(range(1,41)as$item)$f->checklist(6127,$item,$item);
    foreach(['construction_control.read','otiz.manage']as$permission)$db->query("INSERT IGNORE INTO {$p}fm2_pilot_role_permissions(role_id,permission) SELECT role_id,'{$permission}' FROM {$p}fm2_pilot_user_roles WHERE user_id=9101");

    $h->start(null,null,['FMONITOR_NOW'=>'2026-09-21T12:00:00+03:00']);$admin=[];assertSameValue(303,$h->login($admin)['status'],'chart actor login');
    $owner=FMonitor2\YiiRuntime\InstallationProcessFactory::dashboard($f->connection(),$p,'');$before=$f->facts();$dto=$owner->read(9101,$cutoff);assertSameValue($before,$f->facts(),'data seam is read-only');
    assertSameValue(true,isset($dto['charts']['stages'],$dto['charts']['weeks'],$dto['charts']['startRisk'])&&!isset($dto['charts']['activityAge']),'INTENDED_RED fixed refined chart DTO');
    $stageExpected=['needs_assignment_order'=>8,'ready_to_open'=>3,'installation'=>9,'document_closeout'=>2,'completed'=>1,'needs_assignment_change'=>1];assertSameValue($stageExpected,array_column($dto['charts']['stages'],'value','key'),'six canonical stage values');
    assertSameValue(24,array_sum(array_column($dto['charts']['stages'],'value')),'stage sum equals total');
    assertSameValue([['2026-09-21','2026-09-27',3,1],['2026-09-28','2026-10-04',5,0],['2026-10-05','2026-10-11',2,1],['2026-10-12','2026-10-18',0,0],['2026-10-19','2026-10-25',0,1],['2026-10-26','2026-11-01',0,0]],array_map(static fn(array$w)=>[$w['start'],$w['end'],$w['starts'],$w['finishes']],$dto['charts']['weeks']),'six independently calculated calendar weeks and transferred finish');
    $riskExpected=['overdue_start'=>1,'order_0_7'=>2,'order_8_14'=>2,'ready_0_14'=>2,'opened_0_14'=>2];assertSameValue($riskExpected,array_column($dto['charts']['startRisk'],'value','key'),'start risk past, 0/6/7/13/14, ready/opened, unknown and impossible-date boundaries');
    foreach(['shape','week_continuity','negative']as$defect){$broken=$dto;if($defect==='shape')unset($broken['charts']['startRisk'][0]['label']);elseif($defect==='week_continuity')$broken['charts']['weeks'][2]['start']='2026-10-06';else$broken['total']=-1;$malformedOwner=new FMonitor2\InstallationProcess\YiiOperationalDashboard(new class($broken)implements FMonitor2\InstallationProcess\YiiOperationalDashboardStore{public function __construct(private array$result){}public function authorized(int$actorId):bool{return true;}public function read(string$cutoff,string$windowEnd,array$weeks):array{return$this->result;}});try{$malformedOwner->read(9101,$cutoff);throw new TestFailure('malformed DTO accepted '.$defect);}catch(RuntimeException$error){assertSameValue('Malformed dashboard chart aggregate.',$error->getMessage(),'atomic DTO rejection '.$defect);}}
    $queueRows=$f->queue()->read(9101,'','',1)['objects'];$labelToKey=['Требуется распоряжение'=>'needs_assignment_order','Готов к открытию'=>'ready_to_open','Монтажные работы'=>'installation','Документарное закрытие'=>'document_closeout','Работы завершены'=>'completed','Требуется изменение'=>'needs_assignment_change'];$projected=array_fill_keys(array_values($labelToKey),0);foreach($queueRows as$row)$projected[$labelToKey[$row['status']]]++;assertSameValue($stageExpected,$projected,'all-six parity with ordinary queue displayed projection');

    $r=$h->request('GET','/pilot/dashboard',[],$admin);assertSameValue(200,$r['status'],'dashboard charts GET');foreach(['Объекты по этапам процесса','Плановая нагрузка на 6 недель','Риск срыва ближайших стартов','data-dashboard-chart="stages"','data-dashboard-chart="weeks"','data-dashboard-chart="start-risk"']as$m)assertSameValue(true,str_contains($r['body'],$m),'INTENDED_RED dashboard refinement marker '.$m);foreach(['Давность последней подтверждённой активности','data-dashboard-chart="activity-age"','style="--fm2-bar-size']as$m)assertSameValue(false,str_contains($r['body'],$m),'INTENDED_RED removed unsafe/obsolete marker '.$m);assertSameValue(23,substr_count($r['body'],'data-dashboard-bar'),'six plus twelve plus five bars');
    $drills=[];foreach($stageExpected as$key=>$value)$drills[]=['stage',$key,$value];$weekExpected=[[3,1],[5,0],[2,1],[0,0],[0,1],[0,0]];foreach($weekExpected as$index=>[$starts,$finishes]){$drills[]=['planned-start',(string)$index,$starts];$drills[]=['planned-finish',(string)$index,$finishes];}foreach($riskExpected as$key=>$value)$drills[]=['start-risk',$key,$value];
    $stageLabels=['needs_assignment_order'=>'Требуется распоряжение','ready_to_open'=>'Готов к открытию','installation'=>'Монтажные работы','document_closeout'=>'Документарное закрытие','completed'=>'Работы завершены','needs_assignment_change'=>'Требуется изменение'];$riskLabels=['overdue_start'=>'Плановый старт прошёл','order_0_7'=>'0–7 дней: нет распоряжения','order_8_14'=>'8–14 дней: нет распоряжения','ready_0_14'=>'Готовы к открытию','opened_0_14'=>'Уже открыты'];$weekLabels=['21.09–27.09','28.09–04.10','05.10–11.10','12.10–18.10','19.10–25.10','26.10–01.11'];$expectedNames=[];foreach($stageExpected as$key=>$value)$expectedNames['/pilot/objects?chart=stage&bucket='.$key]='Объекты по этапам процесса — '.$stageLabels[$key].': '.$value;foreach($weekExpected as$i=>[$starts,$finishes]){$expectedNames['/pilot/objects?chart=planned-start&bucket='.$i]='Плановая нагрузка на 6 недель — Плановые начала — '.$weekLabels[$i].': '.$starts;$expectedNames['/pilot/objects?chart=planned-finish&bucket='.$i]='Плановая нагрузка на 6 недель — Плановые окончания — '.$weekLabels[$i].': '.$finishes;}foreach($riskExpected as$key=>$value)$expectedNames['/pilot/objects?chart=start-risk&bucket='.rawurlencode($key)]='Риск срыва ближайших стартов — '.$riskLabels[$key].': '.$value;
    $dom=new DOMDocument();@$dom->loadHTML('<?xml encoding="UTF-8">'.$r['body']);$xp=new DOMXPath($dom);$observed=[];foreach($xp->query('//*[@data-dashboard-bar]')as$bar){$href=$bar->getAttribute('href');$name=$bar->getAttribute('aria-label');assertSameValue('a',strtolower($bar->nodeName),'bar is native link');assertSameValue(true,trim($bar->textContent)!==''&&preg_match('/\d/u',$bar->textContent)===1,'visible label and value '.$name);$observed[$href]=$name;}assertSameValue($expectedNames,$observed,'all 23 exact chart/series/category/value accessible names and hrefs');foreach($drills as[$chart,$bucket,$expected]){$url='/pilot/objects?chart='.$chart.'&bucket='.rawurlencode($bucket);$queue=$h->request('GET',$url,[],$admin);assertSameValue(200,$queue['status'],'drill-down '.$chart.' '.$bucket);$qdom=new DOMDocument();@$qdom->loadHTML('<?xml encoding="UTF-8">'.$queue['body']);$qxp=new DOMXPath($qdom);assertSameValue($expected,(int)trim($qxp->query('//*[@data-filtered-total]')->item(0)?->textContent??'-1'),'drill-down total '.$chart.' '.$bucket);assertSameValue(true,str_contains($queue['body'],'Срез на 21.09.2026'),'registry cutoff disclosure '.$chart.' '.$bucket);}
    $composed=$h->request('GET','/pilot/objects?chart=stage&bucket=installation&q=451214&page=1',[],$admin);assertSameValue(200,$composed['status'],'chart composes search/page');assertSameValue(true,str_contains($composed['body'],'REG-451214'),'composed chart result');$ordinary=$h->request('GET','/pilot/objects?status=installation',[],$admin);assertSameValue(200,$ordinary['status'],'ordinary predecessor status filter preserved');
    $head=$h->request('HEAD','/pilot/dashboard',[],$admin);$repeat=$owner->read(9101,$cutoff);assertSameValue([200,''],[$head['status'],$head['body']],'chart HEAD');assertSameValue($dto,$repeat,'repeat owner read deterministic');assertSameValue($before,$f->facts(),'GET HEAD repeat charts no facts');
    $invalid=['/pilot/objects?chart=unknown&bucket=0','/pilot/objects?chart=planned-start&bucket=9','/pilot/objects?chart=stage&bucket=installation&status=completed','/pilot/objects?chart=start-risk&bucket=order_0_7&from=2020-01-01','/pilot/objects?chart=start-risk&bucket=unknown','/pilot/objects?chart=stage','/pilot/objects?bucket=installation','/pilot/objects?chart=stage&bucket=bogus','/pilot/objects?chart=stage&bucket=installation&bucket=completed','/pilot/objects?chart=stage&bucket=installation&to=2030-01-01'];$rejectBefore=$f->facts();foreach($invalid as$url){$bad=$h->request('GET',$url,[],$admin);assertSameValue(400,$bad['status'],'fail-closed chart filter '.$url);assertSameValue(false,str_contains($bad['body'],'REG-'),'invalid filter no disclosure '.$url);}assertSameValue($rejectBefore,$f->facts(),'all invalid filters read-only');
    $guest=[];$guestBefore=$f->facts();$guestResponse=$h->request('GET','/pilot/dashboard',[],$guest);assertSameValue([303,'/pilot/login'],[$guestResponse['status'],$guestResponse['headers']['location'][0]??null],'guest chart safe login');$returned=$h->login($guest);assertSameValue([303,'/pilot/dashboard'],[$returned['status'],$returned['headers']['location'][0]??null],'guest chart safe return path');assertSameValue($guestBefore,$f->facts(),'guest flow no domain writes');
    $regular=[];assertSameValue(303,$h->login($regular,'ordinary.person@shlz.ru')['status'],'unprivileged login');$deniedBefore=$f->facts();foreach(['/pilot/dashboard','/pilot/objects?chart=start-risk&bucket=overdue_start']as$url){$denied=$h->request('GET',$url,[],$regular);assertSameValue(403,$denied['status'],'chart permission '.$url);foreach(['data-dashboard-bar','REG-451']as$private)assertSameValue(false,str_contains($denied['body'],$private),'denied no disclosure '.$private);}assertSameValue($deniedBefore,$f->facts(),'forbidden chart reads no facts');

    $runBrowser=static function(string$mode)use($h,$root,&$browser):array{$config=$h->artifacts.'/dashboard-bar-charts-'.$mode.'.json';$result=$h->artifacts.'/dashboard-bar-charts-'.$mode.'-result.json';file_put_contents($config,json_encode(['mode'=>$mode,'origin'=>'http://127.0.0.1:'.$h->server['port'],'email'=>$h->emails[18],'password'=>$h->password,'artifacts'=>$h->artifacts,'result'=>$result,'playwright'=>getenv('FMONITOR_TEST_PLAYWRIGHT_MODULE')?:dirname($root).'/shlz-ui/node_modules/playwright'],JSON_THROW_ON_ERROR));chmod($config,0600);$browser=proc_open([getenv('FMONITOR_TEST_NODE_BINARY')?:'node',$root.'/tests/Support/operational_dashboard_bar_charts_browser.cjs',$config],[0=>['file','/dev/null','r'],1=>['pipe','w'],2=>['pipe','w']],$pipes,$root);if(!is_resource($browser))throw new TestFailure('SETUP_FAILURE chart browser '.$mode);$stdout=stream_get_contents($pipes[1]);$stderr=stream_get_contents($pipes[2]);fclose($pipes[1]);fclose($pipes[2]);$exit=proc_close($browser);$browser=null;assertSameValue([0,''],[$exit,$stderr],'INTENDED_RED chart browser '.$mode.' 1440/390 '.$stdout.$stderr);$e=json_decode((string)file_get_contents($result),true,flags:JSON_THROW_ON_ERROR);foreach([1440,390]as$width){$shot=$e['screenshots'][$width]??[];assertSameValue(true,isset($shot['path'],$shot['sha256'],$shot['bytes'],$e['viewports'][$width])&&is_file($shot['path'])&&$shot['bytes']>0,'complete browser evidence '.$mode.' '.$width);assertSameValue($shot['sha256'],hash_file('sha256',$shot['path']),'browser digest '.$mode.' '.$width);}return$e;};$runBrowser('populated');

    $canonicalHtml=static fn(string$html):string=>(string)preg_replace('/(<input[^>]+name="_csrf"[^>]+value=")[^"]+("[^>]*>)/u','$1<MASKED>$2',$html);$cookie=implode('; ',array_map(static fn($k,$v)=>$k.'='.$v,array_keys($admin),$admin));$concurrentBefore=$f->facts();$processes=[];foreach(['GET','HEAD']as$i=>$method){$out=$h->artifacts.'/chart-concurrent-'.$i.'.out';$err=$h->artifacts.'/chart-concurrent-'.$i.'.err';$argv=$method==='HEAD'?['curl','-fsS','--head','-H','Cookie: '.$cookie,'http://127.0.0.1:'.$h->server['port'].'/pilot/dashboard']:['curl','-fsS','-H','Cookie: '.$cookie,'http://127.0.0.1:'.$h->server['port'].'/pilot/dashboard'];$processes[]=[$method,$out,proc_open($argv,[0=>['file','/dev/null','r'],1=>['file',$out,'w'],2=>['file',$err,'w']],$pipes,$root)];}foreach($processes as[$method,$out,$process]){assertSameValue(0,proc_close($process),'concurrent chart request '.$method);$bytes=(string)file_get_contents($out);if($method==='GET')assertSameValue($canonicalHtml($r['body']),$canonicalHtml($bytes),'concurrent GET exact stable response');else{assertSameValue(true,str_starts_with($bytes,'HTTP/1.1 200'),'concurrent HEAD status');assertSameValue(false,str_contains($bytes,'data-dashboard-bar'),'concurrent HEAD has no body');}}assertSameValue($concurrentBefore,$f->facts(),'concurrent GET HEAD read-only');

    $db->query("UPDATE {$p}fm2_installation_cases SET process_state='unsupported_fixture_state' WHERE id=6102");$malformedBefore=$f->facts();$malformed=$h->request('GET','/pilot/dashboard',[],$admin);assertSameValue(503,$malformed['status'],'stage sum/shape invariant fails closed at public seam');foreach(['data-dashboard-chart','data-dashboard-bar','REG-','unsupported_fixture_state']as$m)assertSameValue(false,str_contains($malformed['body'],$m),'malformed DTO hides '.$m);assertSameValue($malformedBefore,$f->facts(),'malformed DTO read-only');$db->query("UPDATE {$p}fm2_installation_cases SET process_state='needs_assignment_order' WHERE id=6102");

    $connection=$f->connection();$connection->enableLogging=true;$scaleOwner=FMonitor2\YiiRuntime\InstallationProcessFactory::dashboard($connection,$p,'');for($i=0;$i<30000;$i++)$f->object(500000+$i,700000+$i,'needs_assignment_order','2026-11-02','Scale '.$i);$logger=Yii::getLogger();$logger->flush(true);$logger->messages=[];$memory=memory_get_usage(true);$large=$scaleOwner->read(9101,$cutoff);$delta=memory_get_usage(true)-$memory;$queries=count(array_filter($logger->messages,static fn(array$m):bool=>str_starts_with((string)($m[2]??''),'yii\\db\\Command::query')&&($m[1]??null)===yii\log\Logger::LEVEL_INFO));assertSameValue(30024,$large['total'],'30k total');assertSameValue(30008,array_column($large['charts']['stages'],'value','key')['needs_assignment_order'],'30k exact stage aggregate');assertSameValue([6,6,5],[count($large['charts']['stages']),count($large['charts']['weeks']),count($large['charts']['startRisk'])],'30k fixed refined DTO shape');assertSameValue(true,$queries>0&&$queries<=12,'30k constant query count');assertSameValue(true,$delta<16*1024*1024,'30k bounded dashboard memory');$largeHttp=$h->request('GET','/pilot/dashboard',[],$admin);assertSameValue(23,substr_count($largeHttp['body'],'data-dashboard-bar'),'30k fixed DOM marks');assertSameValue(false,str_contains($largeHttp['body'],'Scale 29999'),'30k no serialized hidden corpus');

    $db->query("DELETE FROM {$p}fm2_pilot_object_details WHERE object_id>=500000");$db->query("DELETE FROM {$p}fm2_installation_cases WHERE id>=700000");$db->query('DELETE FROM fm_maintable WHERE id>=500000');unset($large,$largeHttp);gc_collect_cycles();
    $db->query('DELETE FROM fm_maintable');$emptyBefore=$f->facts();$empty=$h->request('GET','/pilot/dashboard',[],$admin);assertSameValue(200,$empty['status'],'empty charts success');assertSameValue(23,substr_count($empty['body'],'data-dashboard-bar'),'empty retains 23 honest bars');assertSameValue(23,substr_count($empty['body'],'data-dashboard-value="0"'),'empty all zero values');assertSameValue(true,str_contains($empty['body'],'Объектов пока нет'),'empty explanation');assertSameValue($emptyBefore,$f->facts(),'empty read-only');$runBrowser('empty');
    $failureBefore=$f->facts();$db->query('RENAME TABLE fm_maintable TO fm_maintable_unavailable');$failed=$h->request('GET','/pilot/dashboard',[],$admin);assertSameValue(503,$failed['status'],'risk source failure is atomic');foreach(['data-dashboard-chart','data-dashboard-bar','REG-','SQLSTATE','fm_maintable']as$m)assertSameValue(false,str_contains($failed['body'],$m),'atomic failure hides '.$m);assertSameValue(true,str_contains($failed['body'],'Данные временно недоступны'),'atomic safe error');$runBrowser('error');$db->query('RENAME TABLE fm_maintable_unavailable TO fm_maintable');assertSameValue($failureBefore,$f->facts(),'failed chart read-only');

    $source=(string)file_get_contents($root.'/app/YiiRuntime/Views/dashboard.php');$css=(string)file_get_contents($root.'/app/YiiRuntime/Assets/shlz.css');$localCss=(string)file_get_contents($root.'/app/YiiRuntime/Assets/pilot.css');foreach(['chart.js','highcharts','echarts','plotly','<canvas','shlz-design-source','node_modules','packages/']as$dependency)assertSameValue(false,str_contains(strtolower($source.$localCss),$dependency),'no private/chart runtime '.$dependency);foreach(['shlz-dashboard','shlz-chart-widget','shlz-status','shlz-link','shlz-button','shlz-empty-state']as$class)assertSameValue(true,str_contains($source,$class)&&str_contains($css,'.'.$class),'public shlz contract '.$class);$public=['reporting-dashboard.css'=>'00063551688aad728608da13c9f0ca47936421063eceb6d1ab862e2f7187c38f','status-badge.css'=>'cfeef75845e9547ab6b3aef393f4e3b1bd8f3dbed1f01b5016e33ca209b2f527','link.css'=>'8d09c935da2d5d3ffe7b432082712a1e2067a7d20d962e3bff93f8fadcc720cf','button.css'=>'4bf4615320224b8c3d5687600bfdff726d292ce3b9cfaea5646e86954dbb5e74','empty-state.css'=>'5ff1ffdbb245e338e7b5f610504323ce0a9b77ba0bc9d01da4a0b0dba27ab975'];foreach($public as$file=>$hash){$bytes=(string)file_get_contents(dirname($root).'/shlz-ui/packages/styles/components/'.$file);assertSameValue($hash,hash('sha256',$bytes),'public export '.$file);assertSameValue(true,str_contains($css,$bytes),'pinned public bytes '.$file);}
    foreach(['populated','empty','error']as$mode){$all=json_decode((string)file_get_contents($h->artifacts.'/dashboard-bar-charts-'.$mode.'-result.json'),true,flags:JSON_THROW_ON_ERROR);foreach([1440,1201,1200,1051,900,681,680,390]as$width){$shot=$all['screenshots'][$width]??[];assertSameValue(true,isset($shot['path'],$shot['sha256'],$shot['bytes'],$all['viewports'][$width])&&is_file($shot['path'])&&$shot['bytes']>0,'all-width browser evidence '.$mode.' '.$width);assertSameValue($shot['sha256'],hash_file('sha256',$shot['path']),'all-width browser digest '.$mode.' '.$width);}}
    echo "PASS: YII2-OPERATIONAL-DASHBOARD-BAR-CHARTS-001 complete A-L matrix\n";
}finally{if(is_resource($browser)){proc_terminate($browser,9);proc_close($browser);}if($f instanceof ObjectQueueFixture)$f->close();}
