<?php
declare(strict_types=1);
require dirname(__DIR__).'/bootstrap.php';require __DIR__.'/InspectionFixture.php';
// YII2-INSPECTION-JOURNEY-001 A7: real controls/offline queue, independent persisted audit.
$f=null;$process=null;
try {
 $f=new InspectionFixture(dirname(__DIR__,2));$f->open();$f->queueFixtures();$h=$f->http;$config=$h->artifacts.'/inspection-browser.json';$result=$h->artifacts.'/inspection-result.json';
 file_put_contents($config,json_encode(['origin'=>'http://127.0.0.1:'.$h->server['port'],'email'=>$h->emails[73],'otherEmail'=>$h->emails[96],'password'=>$h->password,'artifacts'=>$h->artifacts,'result'=>$result,'png'=>base64_encode(InspectionFixture::png()),'playwright'=>getenv('FMONITOR_TEST_PLAYWRIGHT_MODULE')?:dirname($h->root).'/shlz-ui/node_modules/playwright'],JSON_THROW_ON_ERROR));chmod($config,0600);
 $log=$h->artifacts.'/inspection-browser.log';$process=proc_open([getenv('FMONITOR_TEST_NODE_BINARY')?:'node',__DIR__.'/inspection_browser.mjs',$config],[0=>['file','/dev/null','r'],1=>['file',$log,'a'],2=>['file',$log,'a']],$pipes,$h->root);if(!is_resource($process))throw new TestFailure('SETUP_FAILURE browser');
 $deadline=microtime(true)+150;do{$state=proc_get_status($process);if(!$state['running'])break;usleep(20000);}while(microtime(true)<$deadline);if($state['running'])throw new TestFailure('browser timeout '.$h->artifacts);$exit=$state['exitcode'];proc_close($process);$process=null;assertSameValue(0,$exit,'browser '.file_get_contents($log));
 $r=json_decode(file_get_contents($result),true,flags:JSON_THROW_ON_ERROR);assertSameValue([true,true],[$r['lost'],$r['offline']],'observed response loss and offline');$ops=$h->rows('fm2_checklist_operations');assertSameValue(11,count($ops),'nine items photo section, no replay duplicate');assertSameValue(['28','29'],array_slice(array_column($ops,'item_id'),0,2),'literal first UI items');assertSameValue(array_fill(0,11,'73'),array_column($ops,'actor_user_id'),'server attribution');assertSameValue(['photo_uploaded','section_completed'],array_slice(array_column($ops,'operation_type'),-2),'photo then section persisted');assertSameValue($r['acceptedId'],$ops[0]['client_operation_id'],'lost receipt same identity');assertSameValue(array_map('strval',range(1,11)),array_column($ops,'accepted_revision'),'exact revision sequence');$h->noLegacy();echo 'PASS: YII2-INSPECTION-JOURNEY-001 browser '.$h->artifacts."\n";
}finally{if(is_resource($process)){proc_terminate($process,9);proc_close($process);}if(isset($config)&&is_file($config))unlink($config);if($f instanceof InspectionFixture)$f->close();}
