<?php
declare(strict_types=1);
require dirname(__DIR__).'/bootstrap.php';require __DIR__.'/ObjectQueueFixture.php';
$f=null;try{$f=new ObjectQueueFixture(dirname(__DIR__,2));$h=$f->http;$p=$f->p;
$f->db->query("UPDATE {$p}fm2_pilot_roles SET code='manager' WHERE role_id=9201");$f->db->query("INSERT IGNORE INTO {$p}fm2_pilot_role_permissions(role_id,permission) VALUES(9201,'construction_control.read'),(9201,'checklist.read'),(9211,'construction_control.read'),(9211,'checklist.read'),(9212,'objects.read'),(9212,'inspection.schedule'),(9212,'construction_control.read'),(9212,'checklist.read')");$f->db->query("INSERT IGNORE INTO {$p}fm2_pilot_user_roles(user_id,role_id,origin,assigned_at,assigned_by_user_id) VALUES(9101,9212,'fixture','2026-09-10',9101)");
$f->insert($p.'fm2_control_engineer_assignments',['installation_case_id'=>6101,'object_id'=>451201,'assignment_sequence'=>1,'engineer_user_id'=>9403,'engineer_fio_snapshot'=>'Инженер','engineer_position_snapshot'=>'Инженер','previous_assignment_id'=>null,'previous_engineer_user_id'=>null,'bootstrap_application_id'=>null,'assigned_by_user_id'=>9101,'assigned_at_utc'=>'2026-09-09 06:00:00','request_id'=>'12121212-1212-4212-8212-000000000001','request_fingerprint'=>hash('sha256','scope-one')]);$f->object(451202,6102,'working');$f->order(6121,6102,1,7301);$f->insert($p.'fm2_control_engineer_assignments',['installation_case_id'=>6102,'object_id'=>451202,'assignment_sequence'=>1,'engineer_user_id'=>9403,'engineer_fio_snapshot'=>'Инженер','engineer_position_snapshot'=>'Инженер','previous_assignment_id'=>null,'previous_engineer_user_id'=>null,'bootstrap_application_id'=>null,'assigned_by_user_id'=>9101,'assigned_at_utc'=>'2026-09-09 06:00:00','request_id'=>'12121212-1212-4212-8212-000000000002','request_fingerprint'=>hash('sha256','scope-two')]);$h->start();
$mixed=[];assertSameValue(303,$h->login($mixed)['status'],'mixed manager login');$queue=$h->request('GET','/pilot/construction-control?ownership=all',[],$mixed);assertSameValue([200,true],[$queue['status'],str_contains($queue['body'],'data-object-id="451202"')],'mixed manager-engineer global queue');$path='/pilot/construction-control/objects/451202/inspection-plan';assertSameValue(303,$h->request('POST',$path,['_csrf'=>$h->csrf($queue['body']),'action'=>'create','inspectionDate'=>'2099-09-18','requestId'=>'34343434-3434-4434-8434-000000000001','expectedVersion'=>'0'],$mixed)['status'],'mixed manager-engineer global command');$calendar=$h->request('GET','/pilot/calendar?date=2099-09-18',[],$mixed);assertSameValue([200,true],[$calendar['status'],str_contains($calendar['body'],'/pilot/objects/451202')],'mixed manager-engineer global calendar');
$ordinary=[];assertSameValue(303,$h->login($ordinary,'super.person@shlz.ru')['status'],'ordinary reader login');$before=$f->facts();assertSameValue(403,$h->request('GET','/pilot/construction-control?ownership=all',[],$ordinary)['status'],'non-manager without objects.read denied queue');assertSameValue(403,$h->request('GET','/pilot/calendar?date=2099-09-18',[],$ordinary)['status'],'non-manager without objects.read denied calendar');assertSameValue($before,$f->facts(),'denied reads no DML');echo "PASS: YII2-INSPECTION-PLANNING-UI-255 shared scope policy\n";
}finally{if($f instanceof ObjectQueueFixture)$f->close();}
