<?php
declare(strict_types=1);
require dirname(__DIR__).'/bootstrap.php';
require __DIR__.'/ObjectQueueFixture.php';
// YII2-INSPECTION-PLANNING-UI-255: real Yii HTTP and canonical command/read seam.
$f=null;try{$f=new ObjectQueueFixture(dirname(__DIR__,2));$h=$f->http;$p=$f->p;$f->db->query("UPDATE {$p}fm2_pilot_roles SET code='manager' WHERE role_id=9201");$f->db->query("INSERT IGNORE INTO {$p}fm2_pilot_role_permissions(role_id,permission) VALUES(9201,'construction_control.read'),(9201,'checklist.read')");$h->start();$cookies=[];assertSameValue(303,$h->login($cookies)['status'],'login');
$queue=$h->request('GET','/pilot/construction-control?ownership=all',[],$cookies);assertSameValue(200,$queue['status'],'construction control');$csrf=$h->csrf($queue['body']);$before=$f->facts();
foreach(['Запланировать инспекцию','data-inspection-dialog','Инспекция появится в календаре и списке стройконтроля']as$m)assertSameValue(true,str_contains($queue['body'],$m),'INTENDED_RED '.$m);
$path='/pilot/construction-control/objects/451201/inspection-plan';
foreach(['GET','HEAD']as$verb)assertSameValue(405,$h->request($verb,$path,[],$cookies)['status'],'GET/HEAD write route forbidden');assertSameValue($before,$f->facts(),'GET/HEAD write nothing');
foreach([[],['_csrf'=>'wrong']]as$fields)assertSameValue(400,$h->request('POST',$path,$fields+['action'=>'create','inspectionDate'=>'2099-09-12','requestId'=>'11111111-1111-4111-8111-111111111111','expectedVersion'=>'0'],$cookies)['status'],'CSRF');assertSameValue($before,$f->facts(),'CSRF writes nothing');
$created=$h->request('POST',$path,['_csrf'=>$csrf,'action'=>'create','inspectionDate'=>'2099-09-12','requestId'=>'11111111-1111-4111-8111-111111111111','expectedVersion'=>'0'],$cookies);assertSameValue(303,$created['status'],'create redirect');$afterCreate=$h->request('GET','/pilot/construction-control?ownership=all',[],$cookies);foreach(['Инспекция запланирована на 12.09.2099','Перенести','Отменить']as$m)assertSameValue(true,str_contains($afterCreate['body'],$m),'current plan '.$m);$calendar=$h->request('GET','/pilot/calendar?date=2099-09-12',[],$cookies);assertSameValue(true,str_contains($calendar['body'],'12.09.2099')&&str_contains($calendar['body'],'/pilot/objects/451201'),'calendar agrees and links object');
$plan=$f->planning()->currentPlan(9101,451201);$csrf=$h->csrf($afterCreate['body']);$moved=$h->request('POST',$path,['_csrf'=>$csrf,'action'=>'reschedule','inspectionDate'=>'2099-09-15','planId'=>(string)$plan['scheduleId'],'expectedVersion'=>(string)$plan['version'],'requestId'=>'22222222-2222-4222-8222-222222222222'],$cookies);assertSameValue(303,$moved['status'],'reschedule redirect');$afterMove=$h->request('GET','/pilot/construction-control?ownership=all',[],$cookies);assertSameValue(true,str_contains($afterMove['body'],'15.09.2099')&&!str_contains($afterMove['body'],'12.09.2099'),'only moved date current');
$staleBefore=$f->facts();assertSameValue(409,$h->request('POST',$path,['_csrf'=>$h->csrf($afterMove['body']),'action'=>'cancel','planId'=>(string)$plan['scheduleId'],'expectedVersion'=>'1','requestId'=>'33333333-3333-4333-8333-333333333333'],$cookies)['status'],'stale rejection');assertSameValue($staleBefore,$f->facts(),'stale writes nothing');
$current=$f->planning()->currentPlan(9101,451201);$cancel=$h->request('POST',$path,['_csrf'=>$h->csrf($afterMove['body']),'action'=>'cancel','planId'=>(string)$current['scheduleId'],'expectedVersion'=>(string)$current['version'],'requestId'=>'44444444-4444-4444-8444-444444444444'],$cookies);assertSameValue(303,$cancel['status'],'cancel redirect');$afterCancel=$h->request('GET','/pilot/construction-control?ownership=all',[],$cookies);assertSameValue(true,str_contains($afterCancel['body'],'Запланировать инспекцию')&&!str_contains($afterCancel['body'],'15.09.2099'),'cancel removes current date');
assertSameValue(['inspection_scheduled','inspection_rescheduled','inspection_cancelled'],array_column($f->rows('fm2_pilot_inspection_schedule_events'),'event_type'),'append-only exact command history');echo "PASS: YII2-INSPECTION-PLANNING-UI-255 HTTP journey\n";
}finally{if($f instanceof ObjectQueueFixture)$f->close();}
