<?php
declare(strict_types=1);
require dirname(__DIR__).'/bootstrap.php';require __DIR__.'/PreopeningFixture.php';
// INSTALLER-UTILIZATION-STAGE-ONE-001 D-H, J-M: native upcoming/current history, replacement and paging.
$boundary=getenv('FMONITOR_FIXTURE_REACHABILITY');$f=null;
try{
 $f=new PreopeningFixture(dirname(__DIR__,2));$f->countDirectoryQueries=true;$f->insert($f->p.'fm2_pilot_role_permissions',['role_id'=>1,'permission'=>'installers.read']);$f->start();$cookies=[];assertSameValue(303,$f->login($cookies,18)['status'],'history login');
 if(is_string($boundary)&&$boundary!==''){assertSameValue(200,$f->request('GET','/pilot/installers',[],$cookies)['status'],'history fixture baseline');echo 'FIXTURE_REACHABLE: '.$boundary."\n";exit(0);}
 assertSameValue(303,$f->selection($cookies)['status'],'native selection');$receipt=$f->upload($cookies,$f->metadata($cookies));$original=json_decode($receipt['body'],true,flags:JSON_THROW_ON_ERROR);assertSameValue(303,$f->form('/pilot/objects/4512/execution',['_csrf'=>$f->token($cookies),'action'=>'apply','requestId'=>'44444444-4444-4444-8444-000000000038','orderId'=>'81','revisionId'=>$original['currentRevisionId'],'sequence'=>'0'],$cookies)['status'],'first application');
 $f->db->query("UPDATE {$f->p}fm2_installation_cases SET actual_start_date=NULL,opened_at=NULL,opened_by_user_id=NULL WHERE id=6101");
 $upcoming=$f->request('GET','/pilot/installers/7001',[],$cookies);if($upcoming['status']===404)echo "INTENDED_RED installer card absent\n";assertSameValue(200,$upcoming['status'],'upcoming card');assertSameValue(true,str_contains($upcoming['body'],'Предстоящее назначение')&&str_contains($upcoming['body'],'TEST-4512'),'confirmed original before opening is upcoming');assertSameValue(false,str_contains($upcoming['body'],'Текущая работа'),'upcoming is not current before factual opening');
 $picker=$f->request('GET','/pilot/objects/4512/assignment-order/installers?q=7001&page=1',[],$cookies);assertSameValue(200,$picker['status'],'picker context');$pickerPayload=json_decode($picker['body'],true,flags:JSON_THROW_ON_ERROR);assertSameValue(0,$pickerPayload['items'][0]['utilization']['currentWorkCount']??null,'picker current count before opening');assertSameValue('TEST-4512',$pickerPayload['items'][0]['utilization']['upcomingAssignments'][0]['registrationNumber']??null,'picker same upcoming context');
 $f->db->query("UPDATE {$f->p}fm2_installation_cases SET actual_start_date='2026-09-01',opened_at='2026-09-01 06:00:00',opened_by_user_id=18 WHERE id=6101");
 $f->insert($f->p.'fm2_assignment_orders',['id'=>81,'installation_case_id'=>6101,'version_no'=>1,'kind'=>'initial','status'=>'prepared','order_date'=>'2026-09-01','control_engineer_user_id'=>73,'control_engineer_fio_snapshot'=>'Инженер','control_engineer_position_snapshot'=>'Инженер строительного контроля','organization_form'=>'brigade','object_address_snapshot'=>'Тестовая улица, 1','entrance_snapshot'=>'1','object_registration_number_snapshot'=>'TEST-4512','planned_start_date_snapshot'=>'2026-10-01','planned_finish_date_snapshot'=>'2026-10-31','prepared_at'=>'2026-09-01T09:00:00Z','prepared_by_user_id'=>18]);
 $first=$f->rows('fm2_assignment_order_applications')[0];$facts=$f->facts();$active=$f->request('GET','/pilot/installers/7001',[],$cookies);if($active['status']===404)echo "INTENDED_RED installer utilization history route absent\n";assertSameValue(200,$active['status'],'active history card');foreach(['TEST-4512','01.09.2026','продолжается']as$text)assertSameValue(true,str_contains($active['body'],$text),'active history '.$text);assertSameValue($facts,$f->facts(),'active history read-only');$traceRows=static function(PreopeningFixture$f,string$prefix):array{$records=file($f->artifacts.'/includes.jsonl',FILE_IGNORE_NEW_LINES|FILE_SKIP_EMPTY_LINES)?:[];return array_values(array_filter(array_map(static fn(string$line):array=>json_decode($line,true,flags:JSON_THROW_ON_ERROR),$records),static fn(array$row):bool=>str_starts_with((string)$row['uri'],$prefix)&&($row['status']??0)===200));};$shortTrace=$traceRows($f,'/pilot/installers/7001');$shortQueries=(int)end($shortTrace)['queries'];
 $selected=json_decode($first['selected_snapshot_json'],true,flags:JSON_THROW_ON_ERROR);
 $append=function(int$sequence,int$tabId,int$previousId,string$date)use($f,$first,$selected):int{$f->insert($f->p.'fm2_process_events',['installation_case_id'=>6101,'event_type'=>'assignment_order_composition_applied','occurred_at'=>$date.' 09:00:00','actor_user_id'=>18,'payload_json'=>'{}']);$snapshot=$selected;$snapshot['selectedInstallers'][0]['tabId']=$tabId;$row=$first;unset($row['application_id']);$row['application_sequence']=$sequence;$row['previous_application_id']=$previousId;$row['kind']='reapplication';$row['document_date']=$date;$row['applied_at_utc']=$date.' 06:00:00';$row['request_id']=sprintf('%08x-0000-4000-8000-%012x',$sequence,$sequence);$row['request_fingerprint']=hash('sha256','history-'.$sequence);$row['expected_application_sequence']=$sequence-1;$row['process_event_id']=(int)$f->db->insert_id;$row['selected_snapshot_json']=json_encode($snapshot,JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR);$composition=['caseId'=>(int)$row['installation_case_id'],'compositionIdentity'=>$row['composition_identity'],'engineerUserId'=>(int)$snapshot['selectedEngineer']['userId'],'installers'=>[$tabId],'orderId'=>(int)$row['assignment_order_id']];$row['composition_sha256']=hash('sha256',json_encode($composition,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR));$f->insert($f->p.'fm2_assignment_order_applications',$row);return(int)$f->db->insert_id;};
 $previous=$append(2,7002,(int)$first['application_id'],'2026-09-03');$replacementFacts=$f->facts();$old=$f->request('GET','/pilot/installers/7001',[],$cookies);$current=$f->request('GET','/pilot/installers/7002',[],$cookies);assertSameValue([200,200],[$old['status'],$current['status']],'replacement cards');foreach(['01.09.2026','03.09.2026']as$text)assertSameValue(true,str_contains($old['body'],$text),'closed period '.$text);assertSameValue(true,str_contains($old['body'],'Свободен'),'replaced installer free');assertSameValue(true,str_contains($current['body'],'1 активное закрепление')&&str_contains($current['body'],'продолжается'),'replacement current');assertSameValue($replacementFacts,$f->facts(),'replacement reads preserve facts');
 $previous=$append(3,7002,$previous,'2026-09-04');$adjacent=$f->request('GET','/pilot/installers/7002',[],$cookies);$adjacentDom=new DOMDocument();@$adjacentDom->loadHTML('<?xml encoding="UTF-8"'.$adjacent['body']);$adjacentXp=new DOMXPath($adjacentDom);assertSameValue(1,$adjacentXp->query('//*[@data-history-period and @data-object-id="4512"]')->length,'adjacent retained assignment has no false gap');
 $clock=new DateTimeImmutable('2026-09-05');for($sequence=4;$sequence<=104;$sequence++){$tabId=$sequence%2===0?7001:7002;$previous=$append($sequence,$tabId,$previous,$clock->modify('+'.($sequence-4).' days')->format('Y-m-d'));}
 foreach([[6300,4700,8300],[6301,4701,8301]]as[$caseId,$objectId,$orderId]){$f->insert($f->p.'fm2_installation_cases',['id'=>$caseId,'legacy_installation_object_id'=>$objectId,'process_state'=>'working','actual_start_date'=>'2026-01-01','opened_at'=>'2026-01-01T09:00:00+03:00','opened_by_user_id'=>18,'created_at'=>'2026-01-01T09:00:00+03:00','updated_at'=>'2026-01-01T09:00:00+03:00','lock_version'=>1]);$f->insert($f->p.'fm_maintable',['id'=>$objectId,'regnumber'=>'LEGACY-'.$objectId,'ordadr_address'=>'Legacy history '.$objectId]);$f->insert($f->p.'fm2_assignment_orders',['id'=>$orderId,'installation_case_id'=>$caseId,'version_no'=>1,'kind'=>'initial','status'=>'registered','order_date'=>'2026-01-01','registration_number'=>'ORDER-'.$objectId,'registered_at'=>'2026-01-01T10:00:00+03:00','registration_actor_type'=>'user','registration_actor_id'=>'18','registration_source'=>'fixture','control_engineer_user_id'=>73,'control_engineer_fio_snapshot'=>'Инженер','control_engineer_position_snapshot'=>'Инженер','organization_form'=>'individual','object_address_snapshot'=>'Legacy history '.$objectId,'entrance_snapshot'=>'1','object_registration_number_snapshot'=>'LEGACY-'.$objectId,'planned_start_date_snapshot'=>'2026-01-01','planned_finish_date_snapshot'=>'2026-12-31','prepared_at'=>'2026-01-01T09:00:00+03:00','prepared_by_user_id'=>18]);$f->insert($f->p.'fm2_order_installers',['assignment_order_id'=>$orderId,'installer_tab_id'=>7001,'fio_snapshot'=>'Монтажник 7001','position_snapshot'=>'Монтажник','employment_status_snapshot'=>'employed','employed_from_snapshot'=>'2020-01-01','workforce_source_snapshot'=>'fixture','workforce_source_updated_at_snapshot'=>'2026-01-01T06:00:00Z','valid_from'=>'2026-01-01','valid_to'=>'2026-12-31','change_action'=>'assign']);}
 $page1=$f->request('GET','/pilot/installers/7001?historyPage=1',[],$cookies);$page2=$f->request('GET','/pilot/installers/7001?historyPage=2',[],$cookies);foreach([$page1,$page2]as$page)assertSameValue(200,$page['status'],'long history page');$dom1=new DOMDocument();@$dom1->loadHTML('<?xml encoding="UTF-8"'.$page1['body']);$xp1=new DOMXPath($dom1);$dom2=new DOMDocument();@$dom2->loadHTML('<?xml encoding="UTF-8"'.$page2['body']);$xp2=new DOMXPath($dom2);assertSameValue(50,$xp1->query('//*[@data-history-period]')->length,'history page size50');assertSameValue(true,$xp2->query('//*[@data-history-period]')->length>=1,'history remainder page');$dates=[];foreach($xp1->query('//*[@data-history-period]')as$node)$dates[]=$node->getAttribute('data-start');$sorted=$dates;rsort($sorted,SORT_STRING);assertSameValue($sorted,$dates,'history newest-first stable order');assertSameValue(400,$f->request('GET','/pilot/installers/7001?historyPage=3',[],$cookies)['status'],'history out-of-range');$longTrace=$traceRows($f,'/pilot/installers/7001?historyPage=1');$longQueries=(int)end($longTrace)['queries'];assertSameValue($shortQueries,$longQueries,'card query count independent of 1/104 applications');assertSameValue(true,$longQueries<=6,'long history query cap '.$longQueries);
 $periodIds=[];foreach([$xp1,$xp2]as$historyXp)foreach($historyXp->query('//*[@data-history-period]')as$node)$periodIds[]=$node->getAttribute('data-object-id').'|'.$node->getAttribute('data-start');assertSameValue(count($periodIds),count(array_unique($periodIds)),'mixed native/legacy periods never repeat across pages');assertSameValue(true,str_contains($page1['body'].$page2['body'],'LEGACY-4700')&&str_contains($page1['body'].$page2['body'],'LEGACY-4701'),'mixed legacy periods included in combined pagination');$table=$f->p.'fm2_assignment_order_applications';$latest=$f->db->real_escape_string('{"bad":true}');$f->db->query("UPDATE $table SET selected_snapshot_json='$latest' WHERE installation_case_id=6101 AND application_sequence=104");$bad=$f->request('GET','/pilot/installers/7001',[],$cookies);assertSameValue([503,'60'],[$bad['status'],$bad['headers']['retry-after'][0]??null],'malformed current application fail closed');assertSameValue(false,str_contains($bad['body'],'TEST-4512')||str_contains($bad['body'],$f->p),'malformed current application sanitized');
 echo "PASS: INSTALLER-UTILIZATION-STAGE-ONE-001 native participation history\n";
}finally{if($f instanceof PreopeningFixture)$f->close();}
