<?php
declare(strict_types=1);
require dirname(__DIR__).'/bootstrap.php';require __DIR__.'/DocumentaryFixture.php';
// YII2-COMPLETION-FORM-RECOVERY-001 A3: independent real-browser executable.
$fixture=null;$browser=null;
try{$fixture=new DocumentaryFixture(dirname(__DIR__,2));$fixture->open();$fixture->progress();DocumentaryFixture::accepted($fixture->post('record_pto',['ptoActDate'=>'2026-09-05']));DocumentaryFixture::accepted($fixture->post('record_declaration',['declarationDate'=>'2026-09-04','declarationDetails'=>'Д-BROWSER-ROOT']));$http=$fixture->http;$roots=$http->rows('fm2_pilot_completion_facts');$before=count($http->rows('fm2_pilot_completion_fact_corrections'));
$config=$http->artifacts.'/completion-recovery-browser.json';$result=$http->artifacts.'/completion-recovery-result.json';$log=$http->artifacts.'/completion-recovery-browser.log';file_put_contents($config,json_encode(['origin'=>'http://127.0.0.1:'.$http->server['port'],'email'=>$http->emails[18],'password'=>$http->password,'result'=>$result,'playwright'=>getenv('FMONITOR_TEST_PLAYWRIGHT_MODULE')?:dirname($http->root).'/shlz-ui/node_modules/playwright'],JSON_THROW_ON_ERROR));chmod($config,0600);
$browser=proc_open([getenv('FMONITOR_TEST_NODE_BINARY')?:'node',__DIR__.'/completion_form_recovery_browser.mjs',$config],[0=>['file','/dev/null','r'],1=>['file',$log,'a'],2=>['file',$log,'a']],$pipes,$http->root);if(!is_resource($browser))throw new TestFailure('SETUP_FAILURE completion recovery browser');$deadline=microtime(true)+60;do{$state=proc_get_status($browser);if(!$state['running'])break;usleep(20000);}while(microtime(true)<$deadline);if($state['running']){proc_terminate($browser,9);throw new TestFailure('browser timeout '.$http->artifacts);}$exit=$state['exitcode'];proc_close($browser);$browser=null;assertSameValue(0,$exit,'INTENDED_RED completion recovery browser '.file_get_contents($log));assertSameValue(['passed'=>true,'posts'=>5],json_decode((string)file_get_contents($result),true,flags:JSON_THROW_ON_ERROR),'browser completed matrix');assertSameValue($before+1,count($http->rows('fm2_pilot_completion_fact_corrections')),'browser retry appends exactly one correction');assertSameValue($roots,$http->rows('fm2_pilot_completion_facts'),'browser preserves immutable roots');echo "PASS: YII2-COMPLETION-FORM-RECOVERY-001 browser contract\n";
}finally{if(is_resource($browser)){proc_terminate($browser,9);proc_close($browser);}if($fixture instanceof DocumentaryFixture)$fixture->close();}
