<?php
declare(strict_types=1);
require dirname(__DIR__).'/bootstrap.php';require __DIR__.'/Yii2AuthFixture.php';
use FMonitor2\Tests\Yii2\Yii2AuthFixture;

// YII2-OTIZ-WORKFLOW-001: browser enters the publication journey only through public/yii.php.
$root=dirname(__DIR__,2);$fixture=new Yii2AuthFixture($root);$fixture->setPermission('otiz.manage');$db=$fixture->db;$p=$fixture->prefix;$db->query("INSERT INTO `{$p}fm2_pilot_role_permissions`(role_id,permission)VALUES(9201,'objects.read')");
$db->query("INSERT INTO `{$p}fm_maintable`(id,ordadr_address,entrance,regnumber,workdatestart,plan_finish_date,floors,weight,pitmaterial)VALUES(4520,'Москва, ОТиЗ, 20','1','77-OTIZ-20','2026-08-01','2026-09-30','9','1000','Железобетон')");
$db->query("INSERT INTO `{$p}fm2_installation_cases`(id,legacy_installation_object_id,process_state,actual_start_date,opened_at,opened_by_user_id,created_at,updated_at,lock_version)VALUES(4520,4520,'working','2026-08-01','2026-08-01T09:00:00Z',9101,'2026-08-01T08:00:00Z','2026-08-01T09:00:00Z',1)");
$db->query("INSERT INTO `{$p}fm2_migration_classification_provenance`(legacy_object_id,output_kind,output_id,source_cutoff_at,classification_version,category,reason_codes_json,classification_sha256,created_at)VALUES(4520,'operational_case',4520,'2026-09-01 06:00:00','synthetic-v1','native_candidate','[]',REPEAT('b',64),'2026-09-01 06:00:00')");
$db->query("INSERT INTO `{$p}fm2_assignment_orders`(id,installation_case_id,version_no,kind,status,order_date,control_engineer_user_id,control_engineer_fio_snapshot,control_engineer_position_snapshot,organization_form,object_address_snapshot,entrance_snapshot,object_registration_number_snapshot,planned_start_date_snapshot,planned_finish_date_snapshot,prepared_at,prepared_by_user_id)VALUES(81,4520,1,'initial','registered','2026-08-01',9101,'Yii Auth Admin','Инженер','contract','Москва, ОТиЗ, 20','1','77-OTIZ-20','2026-08-01','2026-09-30','2026-08-01T09:00:00Z',9101)");
$db->query("INSERT INTO `{$p}fm2_order_installers`(assignment_order_id,installer_tab_id,fio_snapshot,position_snapshot,employment_status_snapshot,employed_from_snapshot,workforce_source_snapshot,workforce_source_updated_at_snapshot,valid_from,change_action)VALUES(81,7001,'Монтажник 7001','Монтажник','employed','2020-01-01','synthetic-hr','2026-09-01T06:00:00Z','2026-08-01','assigned')");
$payload=json_encode(['snapshotVersion'=>'yii-otiz-v1','definitions'=>[['id'=>1,'share'=>85]]],JSON_THROW_ON_ERROR|JSON_UNESCAPED_UNICODE);$templateHash=hash('sha256',$payload);$escaped=$db->real_escape_string($payload);
$db->query("INSERT INTO `{$p}fm2_checklist_template_snapshots`(id,snapshot_version,captured_at,valid_from,validity_scope,source_label,content_sha256,payload_json,created_at)VALUES(3,'yii-otiz-v1','2026-08-01','2026-08-01','synthetic','Yii OTIZ fixture','$templateHash','$escaped','2026-08-01')");
$db->query("INSERT INTO `{$p}fm2_checklist_operations`(installation_case_id,client_operation_id,device_installation_id,operation_type,section_id,item_id,actor_user_id,device_time,server_received_at,base_revision,accepted_revision,payload_json,template_snapshot_id,template_snapshot_version,template_content_sha256)VALUES(4520,'11111111-1111-4111-8111-111111111111','22222222-2222-4222-8222-222222222222','item_completed',1,1,9101,'2026-08-20T10:00:00+03:00','2026-08-20T10:00:01+03:00',0,1,'{}',3,'yii-otiz-v1','$templateHash')");
$db->query("INSERT INTO `{$p}fm2_checklist_operation_installers`(client_operation_id,installer_tab_id,fio_snapshot,position_snapshot,employment_status_snapshot,workforce_source_updated_at_snapshot,assignment_source)VALUES('11111111-1111-4111-8111-111111111111',7001,'Монтажник 7001','Монтажник','employed','2026-09-01T06:00:00Z','completion')");
$detail=json_encode(['schemaVersion'=>'technical-object-detail-v1','objectId'=>4520,'fields'=>['floors'=>['raw'=>9],'weight'=>['raw'=>1000],'pitmaterial'=>['display'=>'Железобетон'],'lift_type'=>['display'=>'Пассажирский']]],JSON_THROW_ON_ERROR|JSON_UNESCAPED_UNICODE);$detailHash=hash('sha256',$detail);$detailEscaped=$db->real_escape_string($detail);$db->query("INSERT INTO `{$p}fm2_pilot_object_details`(object_id,schema_version,content_sha256,payload_json,captured_at)VALUES(4520,'technical-object-detail-v1','$detailHash','$detailEscaped','2026-08-01T09:00:00Z')");
$server=null;$browser=null;$artifacts=sys_get_temp_dir().'/fmonitor-yii-otiz-publication-'.bin2hex(random_bytes(6));mkdir($artifacts,0700);
try{$listener=stream_socket_server('tcp://127.0.0.1:0',$errno,$error);if(!is_resource($listener))throw new TestFailure('SETUP_FAILURE: port');$address=stream_socket_get_name($listener,false);$port=(int)substr($address,strrpos($address,':')+1);fclose($listener);
 $env=getenv();foreach(array_keys($env)as$key)if(str_starts_with((string)$key,'FMONITOR_'))unset($env[$key]);$env=array_replace($env,$fixture->environment(),['FMONITOR_TRUSTED_REQUEST_HOST'=>'127.0.0.1:'.$port]);
 $server=proc_open([PHP_BINARY,'-d','display_errors=0','-S','127.0.0.1:'.$port,$root.'/public/yii.php'],[0=>['file','/dev/null','r'],1=>['file',$artifacts.'/server.log','a'],2=>['file',$artifacts.'/server.log','a']],$pipes,$root,$env);if(!is_resource($server))throw new TestFailure('SETUP_FAILURE: server');$ready=false;$deadline=microtime(true)+5;do{$socket=@fsockopen('127.0.0.1',$port,$errno,$error,.1);if(is_resource($socket)){fclose($socket);$ready=true;break;}usleep(20000);}while(microtime(true)<$deadline);assertSameValue(true,$ready,'Yii listener');
 $playwright=getenv('FMONITOR_TEST_PLAYWRIGHT_MODULE')?:dirname($root).'/shlz-ui/node_modules/playwright';$result=$artifacts.'/result.json';$browser=proc_open([getenv('FMONITOR_TEST_NODE_BINARY')?:'node',$root.'/tests/Otiz/snapshot_publication_browser_001_test.mjs',(string)$port,$playwright,$artifacts,$result,'2026-09-08',$fixture->email,$fixture->password],[0=>['file','/dev/null','r'],1=>['file',$artifacts.'/browser.log','a'],2=>['file',$artifacts.'/browser.log','a']],$pipes,$root);if(!is_resource($browser))throw new TestFailure('SETUP_FAILURE: browser');$deadline=microtime(true)+15;do{$status=proc_get_status($browser);if(!$status['running'])break;usleep(20000);}while(microtime(true)<$deadline);if($status['running']){proc_terminate($browser,9);proc_close($browser);$browser=null;throw new TestFailure('INTENDED_RED: Yii2 publication browser timed out on missing journey');}$exit=$status['exitcode'];proc_close($browser);$browser=null;assertSameValue(0,$exit,'INTENDED_RED: full publication browser journey through Yii2; '.file_get_contents($artifacts.'/browser.log'));
 $observed=json_decode((string)file_get_contents($result),true,flags:JSON_THROW_ON_ERROR);assertSameValue(['application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','attachment; filename="FMonitor-OTIZ-2026-09-08-v1.xlsx"','FMonitor-OTIZ-2026-09-08-v1.xlsx'],[$observed['xlsxContentType']??null,$observed['xlsxDisposition']??null,$observed['xlsxFilename']??null],'exact retained Yii2 XLSX HTTP headers and filename');$snapshot=$db->query("SELECT * FROM `{$p}fm2_pilot_otiz_snapshots`")->fetch_assoc();assertSameValue(['accepted',9101,60775000],[$snapshot['status'],(int)$snapshot['accepted_by_user_id'],(int)$snapshot['total_pool_cents']],'independent 71500000 * 85% accepted oracle');assertSameValue(1,(int)$db->query("SELECT COUNT(*) FROM `{$p}fm2_pilot_otiz_snapshots`")->fetch_column(),'response-loss replay retained one snapshot');assertSameValue(1,(int)$db->query("SELECT COUNT(*) FROM `{$p}fm2_otiz_publications`")->fetch_column(),'one publication receipt');assertSameValue(1,(int)$db->query("SELECT COUNT(*) FROM `{$p}fm2_pilot_otiz_events` WHERE event_type='draft_calculated'")->fetch_column(),'one draft event');assertSameValue(1,(int)$db->query("SELECT COUNT(*) FROM `{$p}fm2_pilot_otiz_events` WHERE event_type='snapshot_accepted'")->fetch_column(),'one accepted event');assertSameValue(true,$observed['generatedSettlementCompleted']??false,'generated snapshot continued through payment and reverse');assertSameValue(3,(int)$db->query("SELECT COUNT(*) FROM `{$p}fm2_pilot_otiz_payment_closures`")->fetch_column(),'generated journey appended discipline, payment and reversal');$xlsx=$artifacts.'/otiz.xlsx';assertSameValue('PK',substr((string)file_get_contents($xlsx),0,2),'downloaded XLSX signature');$archive=new PharData($xlsx);$xml='';foreach(new RecursiveIteratorIterator($archive)as$entry)if($entry->isFile()&&str_ends_with($entry->getFilename(),'.xml'))$xml.=$entry->getContent();foreach(['Объекты','Работники','Метаданные','77-OTIZ-20','Монтажник 7001','2026-09-08']as$needle)assertSameValue(true,str_contains($xml,$needle),'XLSX contains '.$needle);echo "PASS: Yii2 OTIZ publication browser\n";
}finally{if(is_resource($browser)){proc_terminate($browser,9);proc_close($browser);}if(is_resource($server)){proc_terminate($server);proc_close($server);}$fixture->close();}
