<?php
declare(strict_types=1);
require dirname(__DIR__).'/bootstrap.php';require __DIR__.'/ObjectQueueFixture.php';
// YII2-INSPECTION-PLANNING-UI-255: Moscow today priority is a server read projection before LIMIT.
$f=null;try{$f=new ObjectQueueFixture(dirname(__DIR__,2));$p=$f->p;$f->db->query("UPDATE {$p}fm2_pilot_roles SET code='manager' WHERE role_id=9201");$f->db->query("INSERT IGNORE INTO {$p}fm2_pilot_role_permissions(role_id,permission) VALUES(9201,'construction_control.read'),(9201,'checklist.read')");$f->insert($p.'fm2_control_engineer_assignments',['installation_case_id'=>6101,'object_id'=>451201,'assignment_sequence'=>1,'engineer_user_id'=>7301,'engineer_fio_snapshot'=>'Инженер','engineer_position_snapshot'=>'Инженер','previous_assignment_id'=>null,'previous_engineer_user_id'=>null,'bootstrap_application_id'=>null,'assigned_by_user_id'=>9101,'assigned_at_utc'=>'2026-09-09 06:00:00','request_id'=>'aaaaaaaa-aaaa-4aaa-8aaa-999999999999','request_fingerprint'=>hash('sha256','today-original')]);
for($i=0;$i<55;$i++){$object=452000+$i;$case=6200+$i;$f->object($object,$case,'working');$f->order(7200+$i,$case,1,7301);$f->insert($p.'fm2_control_engineer_assignments',['installation_case_id'=>$case,'object_id'=>$object,'assignment_sequence'=>1,'engineer_user_id'=>7301,'engineer_fio_snapshot'=>'Инженер','engineer_position_snapshot'=>'Инженер','previous_assignment_id'=>null,'previous_engineer_user_id'=>null,'bootstrap_application_id'=>null,'assigned_by_user_id'=>9101,'assigned_at_utc'=>'2026-09-09 06:00:00','request_id'=>sprintf('aaaaaaaa-aaaa-4aaa-8aaa-%012d',$i),'request_fingerprint'=>hash('sha256','today-'.$i)]);}
$planning=$f->planning();for($i=0;$i<51;$i++)assertSameValue('scheduled',$planning->createInspectionPlan(9101,452000+$i,0,'2026-09-10',sprintf('bbbbbbbb-bbbb-4bbb-8bbb-%012d',$i))['status'],'today plan '.$i);for($i=51;$i<55;$i++)assertSameValue('scheduled',$planning->createInspectionPlan(9101,452000+$i,0,'2026-09-11',sprintf('cccccccc-cccc-4ccc-8ccc-%012d',$i))['status'],'future plan '.$i);
$owner=static fn(string$now)=>new FMonitor2\InspectionEvidence\MariaDbYiiChecklist($f->db,$p,'',$f->http->artifacts,$now);$before=$f->facts();$first=$owner('2026-09-10T23:59:59+03:00')->queue(9101,1,50,'all','Синтетический',false);$second=$owner('2026-09-10T23:59:59+03:00')->queue(9101,2,50,'all','Синтетический',false);$ordered=array_merge($first,$second);assertSameValue(56,(int)$first[0]['_pagination']['total'],'filtered COUNT covers exact matching scope before LIMIT');$today=array_values(array_filter($ordered,static fn(array$r):bool=>(bool)($r['inspectionToday']??false)));assertSameValue(51,count($today),'all today rows survive filtered page boundary');assertSameValue(range(452000,452050),array_map('intval',array_column($today,'id')),'today group stable numeric identity order');assertSameValue(false,(bool)($ordered[51]['inspectionToday']??false),'future row starts after complete today group');assertSameValue($before,$f->facts(),'today reads perform no DML');
$tomorrow=$owner('2026-09-11T00:00:01+03:00')->queue(9101,1,50,'all','',false);assertSameValue([452051,452052,452053,452054],array_map('intval',array_column(array_values(array_filter($tomorrow,static fn(array$r):bool=>(bool)($r['inspectionToday']??false))),'id')),'Moscow midnight recomputes today without fact');assertSameValue($before,$f->facts(),'midnight recomputation performs no DML');
$f->db->query("INSERT INTO {$p}fm2_pilot_inspection_schedules(installation_case_id,legacy_object_id,control_engineer_user_id,inspection_date,scheduled_by_user_id,scheduled_at) VALUES(6200,452000,7301,'2026-09-12',9101,'2026-09-09T09:00:00+03:00')");$overflowId=(int)$f->db->insert_id;$f->insert($p.'fm2_pilot_inspection_schedule_events',['schedule_id'=>$overflowId,'installation_case_id'=>6200,'event_type'=>'inspection_scheduled','event_version'=>1,'request_identity'=>'dddddddd-dddd-4ddd-8ddd-000000000000','request_fingerprint'=>hash('sha256','overflow-current'),'payload_json'=>json_encode(['scheduleId'=>$overflowId,'inspectionDate'=>'2026-09-10'],JSON_THROW_ON_ERROR),'actor_user_id'=>9101,'occurred_at'=>'2026-09-09T09:00:00+03:00']);$overflowBefore=$f->facts();$failed=false;try{$owner('2026-09-10T12:00:00+03:00')->queue(9101,1,50,'all','',false);}catch(RuntimeException){$failed=true;}assertSameValue(true,$failed,'multiple-current overflow fails closed');assertSameValue($overflowBefore,$f->facts(),'overflow read does no repair/DML');echo "PASS: YII2-INSPECTION-PLANNING-UI-255 Moscow priority\n";
}finally{if($f instanceof ObjectQueueFixture)$f->close();}
