<?php
declare(strict_types=1);
require dirname(__DIR__).'/bootstrap.php';require __DIR__.'/DocumentaryFixture.php';
// YII2-DOCUMENTARY-CLOSURE-001 A1-A7: real Yii HTTP; SQL only independent audit/fault/denial setup.
$f=null;
try {
    $f=new DocumentaryFixture(dirname(__DIR__,2));$f->open();$h=$f->http;
    $noFormsWhenNotWorking=function()use($f,$h):void{
        $h->db->query("UPDATE {$h->p}fm2_installation_cases SET process_state='needs_assignment_change' WHERE id=6101");
        try{$before=$h->facts();$page=$f->page();assertSameValue(200,$page['status'],'nonworking card stays readable');assertSameValue($before,$h->facts(),'nonworking card read-only');foreach(['record_pto','record_declaration','correct_pto','correct_declaration'] as $action){$visible=str_contains($page['body'],'value="'.$action.'"');if($visible)echo "INTENDED_RED nonworking card exposes unavailable completion form\n";assertSameValue(false,$visible,'A4 no completion form outside working case '.$action);}}finally{$h->db->query("UPDATE {$h->p}fm2_installation_cases SET process_state='working' WHERE id=6101");}
    };
    $baseline=$h->facts();$page=$f->page();assertSameValue(200,$page['status'],'card ready before missing feature');
    assertSameValue(true,str_contains($page['body'],'/pilot/objects/4512/checklist'),'below85 checklist return');assertSameValue($baseline,$h->facts(),'read no facts');
    $r=$f->post('record_pto',['ptoActDate'=>'2026-09-05']);if($r['status']===404)echo "INTENDED_RED Yii completion route absent on existing opened object\n";DocumentaryFixture::rejected($r,409,'Сначала завершите монтажные работы до 85%.');
    assertSameValue($baseline,$h->facts(),'below85 no facts');
    $f->progress(false);$baseline=$h->facts();DocumentaryFixture::rejected($f->post('record_pto',['ptoActDate'=>'2026-09-05']),409,'Сначала завершите монтажные работы до 85%.');assertSameValue($baseline,$h->facts(),'84 no facts');
    $p=$f->inspection->page();$op=InspectionFixture::operation(532,40,32);$op['sectionId']=1;InspectionFixture::result($f->inspection->send($op,InspectionFixture::csrf($p)),200,'accepted');
    $baseline=$h->facts();InspectionFixture::result($f->inspection->send($op,InspectionFixture::csrf($p)),200,'duplicate');assertSameValue($baseline,$h->facts(),'duplicate does not add progress');
    $noFormsWhenNotWorking();
    $page=$f->page();assertSameValue(1,substr_count($page['body'],'id="completion"'),'one anchor');assertSameValue(true,str_contains($page['body'],'value="record_pto"'),'PTO form at85');assertSameValue(false,str_contains($page['body'],'value="record_declaration"'),'declaration locked');
    DocumentaryFixture::rejected($f->post('record_declaration',['declarationDate'=>'2026-09-06','declarationDetails'=>'Д-001']),409,'Сначала зафиксируйте дату акта ПТО.');
    $today=(new DateTimeImmutable('now',new DateTimeZone('Europe/Moscow')));$future=$today->modify('+2 days')->format('Y-m-d');
    foreach(['2026-02-30',$future,''] as $date)DocumentaryFixture::rejected($f->post('record_pto',['ptoActDate'=>$date]),422,'Укажите дату акта ПТО не позже сегодняшней.');
    foreach(['record_pto','record_declaration','correct_pto','correct_declaration'] as $action){
        foreach([73,94,95,96] as $actor){$jar=[];$h->login($jar,$actor);$token=$h->token($jar);$before=$h->facts();$r=$h->form('/pilot/objects/4512/completion',['_csrf'=>$token,'action'=>$action,'ptoActDate'=>'2026-09-05','declarationDate'=>'2026-09-06','declarationDetails'=>'Д-001','factId'=>'1','reason'=>'Поправка'],$jar);assertSameValue(403,$r['status'],'exact capability denied '.$action.' actor'.$actor);assertSameValue($before,$h->facts(),'denied no facts');}
    }
    // Root insert failure, before either document exists, must not leave a partial receipt.
    $trigger=$h->p.'documentary_root_fault';$h->db->query("CREATE TRIGGER $trigger BEFORE INSERT ON {$h->p}fm2_pilot_completion_facts FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='synthetic root failure'");
    try{$before=$h->facts();$r=$f->post('record_pto',['ptoActDate'=>'2026-09-05']);assertSameValue(503,$r['status'],'root insertion unavailable');assertSameValue($before,$h->facts(),'root insert rollback');}finally{$h->db->query("DROP TRIGGER $trigger");}
    // Current progress is reduced by a real retraction; correction later remains permitted.
    $cp=$f->inspection->page();$retract=InspectionFixture::operation(800,41,32);$retract['sectionId']=1;$retract['type']='completion_retracted';$retract['originalClientOperationId']=InspectionFixture::operation(532)['clientOperationId'];$retract['reason']='Ошибка отметки';
    InspectionFixture::result($f->inspection->send($retract,InspectionFixture::csrf($cp)),200,'accepted');$before=$h->facts();DocumentaryFixture::rejected($f->post('record_pto',['ptoActDate'=>'2026-09-05']),409,'Сначала завершите монтажные работы до 85%.');assertSameValue($before,$h->facts(),'retraction blocks PTO');
    $again=InspectionFixture::operation(801,42,32);$again['sectionId']=1;InspectionFixture::result($f->inspection->send($again,InspectionFixture::csrf($cp)),200,'accepted');
    $baseline=$h->facts();$beforeTime=new DateTimeImmutable('now',new DateTimeZone('Europe/Moscow'));DocumentaryFixture::accepted($f->post('record_pto',['ptoActDate'=>'2026-09-05','actorUserId'=>'94']));$afterTime=new DateTimeImmutable('now',new DateTimeZone('Europe/Moscow'));
    $facts=$h->rows('fm2_pilot_completion_facts');assertSameValue(1,count($facts),'one root');$pto=$facts[0];assertSameValue(['6101','pto_act','2026-09-05','','18'],array_map('strval',[$pto['installation_case_id'],$pto['fact_type'],$pto['fact_date'],$pto['details'],$pto['recorded_by_user_id']]),'PTO literal audit');
    $recorded=new DateTimeImmutable($pto['recorded_at']);assertSameValue('+03:00',$recorded->format('P'),'Moscow audit offset');assertSameValue(true,$recorded->getTimestamp()>=$beforeTime->getTimestamp()&&$recorded->getTimestamp()<=$afterTime->getTimestamp(),'bounded audit time');$f->unchangedExcept($baseline,['fm2_pilot_completion_facts']);
    $baseline=$h->facts();DocumentaryFixture::rejected($f->post('record_pto',['ptoActDate'=>$future]),422,'Укажите дату акта ПТО не позже сегодняшней.');foreach(['2026-09-05','2026-09-04'] as $date)DocumentaryFixture::rejected($f->post('record_pto',['ptoActDate'=>$date]),409,'Документ уже зафиксирован.');assertSameValue($baseline,$h->facts(),'PTO valid replay immutable');
    $page=$f->page();assertSameValue(true,str_contains($page['body'],'value="record_declaration"'),'declaration unlocked');assertSameValue(true,str_contains($page['body'],'85%'),'PTO remains85');
    foreach([['2026-02-30','Д-001'],[$future,'Д-001'],['2026-09-06','  '],['2026-09-06',str_repeat('Ж',501)]] as [$date,$details])DocumentaryFixture::rejected($f->post('record_declaration',['declarationDate'=>$date,'declarationDetails'=>$details]),422,'Укажите дату и реквизиты декларации.');
    $h->db->query("DELETE FROM {$h->p}fm2_pilot_role_permissions WHERE role_id=1 AND permission='installation.completion.declaration.record'");$before=$h->facts();assertSameValue(403,$f->post('record_declaration',['declarationDate'=>'2026-09-06','declarationDetails'=>'Д-001'])['status'],'PTO writer does not inherit declaration grant');assertSameValue($before,$h->facts(),'split grant no facts');$h->insert($h->p.'fm2_pilot_role_permissions',['role_id'=>1,'permission'=>'installation.completion.declaration.record']);
    $manager=[];$h->login($manager,97);$managerToken=$h->token($manager);$baseline=$h->facts();$declaration=['_csrf'=>$managerToken,'action'=>'record_declaration','declarationDate'=>'2026-09-04','declarationDetails'=>'  Д-001  '];DocumentaryFixture::accepted($h->form('/pilot/objects/4512/completion',$declaration,$manager));$f->unchangedExcept($baseline,['fm2_pilot_completion_facts']);
    $roots=$h->rows('fm2_pilot_completion_facts');assertSameValue($pto,$roots[0],'PTO original preserved');assertSameValue(['declaration','2026-09-04','Д-001','97'],array_map('strval',[$roots[1]['fact_type'],$roots[1]['fact_date'],$roots[1]['details'],$roots[1]['recorded_by_user_id']]),'manager declaration before PTO retained');$root=(int)$roots[1]['id'];
    $baseline=$h->facts();DocumentaryFixture::rejected($f->post('record_declaration',['declarationDate'=>'2026-09-06','declarationDetails'=>'Д-002']),409,'Документ уже зафиксирован.');assertSameValue($baseline,$h->facts(),'declaration replay');
    $correct=['factId'=>(string)$root,'declarationDate'=>'2026-09-03','declarationDetails'=>' Д-002 ','reason'=>' Сверено по оригиналу '];DocumentaryFixture::accepted($f->post('correct_declaration',$correct));$first=$h->rows('fm2_pilot_completion_fact_corrections')[0];
    assertSameValue(['1',null,null,'Д-002','Сверено по оригиналу','18'],[$first['version_no'],$first['previous_correction_id'],$first['previous_version_no'],$first['details'],$first['reason'],$first['recorded_by_user_id']],'first correction literal');
    DocumentaryFixture::accepted($f->post('correct_declaration',array_replace($correct,['declarationDate'=>'2026-09-02','declarationDetails'=>'','reason'=>'Исправлена только дата'])));
    $corr=$h->rows('fm2_pilot_completion_fact_corrections');assertSameValue($first,$corr[0],'first correction immutable');assertSameValue(['2',$first['id'],'1',null],[$corr[1]['version_no'],$corr[1]['previous_correction_id'],$corr[1]['previous_version_no'],$corr[1]['details']],'second inherits details');assertSameValue($roots,$h->rows('fm2_pilot_completion_facts'),'all roots preserved');
    $page=$f->page();foreach(['Д-001','Д-002','Сверено по оригиналу','Исправлена только дата','2026-09-02','2026-09-03','2026-09-04','Работы завершены','100%','/pilot/objects'] as $text)assertSameValue(true,str_contains($page['body'],$text),'full effective/history UI '.$text);
    $dom=new DOMDocument();@$dom->loadHTML('<?xml encoding="UTF-8">'.$page['body']);$xpath=new DOMXPath($dom);$history=$xpath->query('//*[@data-completion-history="declaration" and @data-completion-version]');assertSameValue(3,$history->length,'root plus two visible history revisions');
    foreach([['0','2026-09-04','Д-001','Руководитель Ирина','97',$roots[1]['recorded_at']],['1','2026-09-03','Д-002','ФКР Анна','18',$corr[0]['recorded_at']],['2','2026-09-02','Д-002','ФКР Анна','18',$corr[1]['recorded_at']]] as $i=>$expected){$row=$history->item($i);assertSameValue($expected[0],$row->getAttribute('data-completion-version'),'chronological history version');foreach(array_slice($expected,1) as $value)assertSameValue(true,str_contains($row->textContent,$value),'history row attribution/value '.$i.' '.$value);}
    $before=$h->facts();foreach([['reason'=>''],['reason'=>str_repeat('Ж',1001)],['declarationDate'=>$future],['declarationDetails'=>str_repeat('Ж',501)],['factId'=>'0']] as $delta){$r=$f->post('correct_declaration',array_replace($correct,$delta));assertSameValue(true,in_array($r['status'],[400,422],true),'invalid correction');}assertSameValue($before,$h->facts(),'invalid correction no facts');
    foreach([['factId'=>(string)$pto['id']],['factId'=>'999999']] as $delta)DocumentaryFixture::rejected($f->post('correct_declaration',array_replace($correct,$delta)),409,'Исправляемая запись не найдена.');
    // Existing correction repeat is a new revision, not an idempotent receipt.
    DocumentaryFixture::accepted($f->post('correct_declaration',$correct));assertSameValue(3,count($h->rows('fm2_pilot_completion_fact_corrections')),'repeat correction append');
    $baseline=$h->facts();DocumentaryFixture::accepted($f->post('correct_pto',['factId'=>(string)$pto['id'],'ptoActDate'=>'2026-09-04','reason'=>'Уточнение ПТО']));$f->unchangedExcept($baseline,['fm2_pilot_completion_fact_corrections']);
    $escaped='<script>alert(1)</script>';DocumentaryFixture::accepted($f->post('correct_declaration',array_replace($correct,['declarationDetails'=>$escaped,'reason'=>$escaped])));$page=$f->page();assertSameValue(false,str_contains($page['body'],$escaped),'history escapes user text');assertSameValue(true,str_contains($page['body'],'&lt;script&gt;'),'escaped details visible');
    // 500 Unicode details and 1000-character reason are allowed; whitespace-only details inherit.
    DocumentaryFixture::accepted($f->post('correct_declaration',array_replace($correct,['declarationDetails'=>str_repeat('Ж',500),'reason'=>str_repeat('Я',1000)])));
    $noFormsWhenNotWorking();
    $reader=[];$h->login($reader,95);$read=$f->page($reader);assertSameValue(200,$read['status'],'reader sees history');assertSameValue(false,str_contains($read['body'],'value="correct_declaration"')||str_contains($read['body'],'value="correct_pto"'),'reader cannot edit');
    $h->db->query("DELETE FROM {$h->p}fm2_pilot_role_permissions WHERE role_id=5 AND permission='objects.read'");$before=$h->facts();foreach(['GET','HEAD'] as $method){$r=$h->request($method,'/pilot/objects/4512',[],$reader);assertSameValue(403,$r['status'],'objects.read revoked '.$method);assertSameValue(false,str_contains($r['body'],'Д-001')||str_contains($r['body'],'Сверено по оригиналу'),'no protected history disclosure');}assertSameValue($before,$h->facts(),'read denial no facts');
    $head=$h->request('HEAD','/pilot/objects/4512',[],$f->cookies);assertSameValue([200,''],[$head['status'],$head['body']],'card HEAD');
    foreach(['GET','HEAD','PUT','DELETE'] as $method){$r=$h->request($method,'/pilot/objects/4512/completion',[],$f->cookies);assertSameValue([405,'POST'],[$r['status'],$r['headers']['allow'][0]??null],'method Allow '.$method);}
    foreach(['0','04512','-1','4512x','999999999999999999999999'] as $id)assertSameValue(404,$h->form('/pilot/objects/'.$id.'/completion',['_csrf'=>$f->csrf,'action'=>'record_pto','ptoActDate'=>'2026-09-05'],$f->cookies)['status'],'canonical id');
    $baseline=$h->facts();DocumentaryFixture::rejected($f->post('record_pto',['ptoActDate'=>'2026-09-05'],id:999999),404,'Объект не найден.');DocumentaryFixture::rejected($f->post('unknown'),422,'Неизвестное действие.');
    foreach([['_csrf'=>'wrong','action'=>'record_pto'],['action'=>'record_pto']] as $fields){$r=$h->form('/pilot/objects/4512/completion',$fields,$f->cookies);assertSameValue(true,in_array($r['status'],[400,403],true),'CSRF rejected');}
    foreach(['_csrf='.rawurlencode($f->csrf).'&action[]=record_pto','_csrf='.rawurlencode($f->csrf).'&action=record_pto&action=record_declaration','_csrf='.rawurlencode($f->csrf).'&action=record_pto&ptoActDate=%ZZ'] as $raw){$r=$h->request('POST','/pilot/objects/4512/completion',[],$f->cookies,['Content-Type: application/x-www-form-urlencoded'],$raw);assertSameValue(true,in_array($r['status'],[400,422],true),'malformed form rejected');}
    foreach([['record_pto','ptoActDate'],['record_declaration','declarationDate'],['record_declaration','declarationDetails'],['correct_pto','factId'],['correct_pto','ptoActDate'],['correct_pto','reason'],['correct_declaration','factId'],['correct_declaration','declarationDate'],['correct_declaration','declarationDetails'],['correct_declaration','reason']] as [$action,$field]){$fields=['_csrf'=>$f->csrf,'action'=>$action,'ptoActDate'=>'2026-09-05','declarationDate'=>'2026-09-04','declarationDetails'=>'Д-001','factId'=>(string)$root,'reason'=>'Проверка'];$fields[$field]=['bad'];$r=$h->form('/pilot/objects/4512/completion',$fields,$f->cookies);assertSameValue(true,in_array($r['status'],[400,422],true),'array field rejected '.$action.' '.$field);}
    $r=$h->request('POST','/pilot/objects/4512/completion',[],$f->cookies,['Content-Type: application/x-www-form-urlencoded','X-CSRF-Token: '.$f->csrf],str_repeat('a',16385));assertSameValue(413,$r['status'],'bounded body');
    $r=$h->request('POST','/pilot/objects/4512/completion',[],$f->cookies,['Content-Type: application/json','X-CSRF-Token: '.$f->csrf],'{"action":"record_pto"}');assertSameValue(true,in_array($r['status'],[400,415],true),'unsupported content type');
    assertSameValue($baseline,$h->facts(),'all transport failures no facts');
    $guest=[];$r=$h->form('/pilot/objects/4512/completion',['action'=>'record_pto','ptoActDate'=>'2026-09-05'],$guest);assertSameValue(true,in_array($r['status'],[303,400,401,403],true),'guest cannot mutate');assertSameValue($baseline,$h->facts(),'guest no facts');
    // Current identity/grants, not stale login or visible controls, govern POST.
    foreach(["DELETE FROM {$h->p}fm2_pilot_role_permissions WHERE role_id=1 AND permission='installation.completion.pto.correct'","UPDATE {$h->p}fm2_pilot_roles SET status=0 WHERE role_id=1","UPDATE {$h->p}fm2_pilot_users SET activation_state='invited' WHERE user_id=18","UPDATE {$h->p}fm2_pilot_users SET status=0 WHERE user_id=18"] as $i=>$sql){$h->db->query($sql);$before=$h->facts();$r=$f->post('correct_pto',['factId'=>(string)$pto['id'],'ptoActDate'=>'2026-09-04','reason'=>'Проверка допуска']);assertSameValue(true,in_array($r['status'],[303,401,403],true),'live authorization');assertSameValue($before,$h->facts(),'live denial no facts');if($i===0)$h->insert($h->p.'fm2_pilot_role_permissions',['role_id'=>1,'permission'=>'installation.completion.pto.correct']);elseif($i===1)$h->db->query("UPDATE {$h->p}fm2_pilot_roles SET status=1 WHERE role_id=1");else{$h->db->query("UPDATE {$h->p}fm2_pilot_users SET activation_state='active',status=1 WHERE user_id=18");$f->cookies=[];$h->login($f->cookies);$f->csrf=$h->token($f->cookies);}}
    $h->db->query("UPDATE {$h->p}fm2_installation_cases SET process_state='needs_assignment_change' WHERE id=6101");$before=$h->facts();DocumentaryFixture::rejected($f->post('correct_pto',['factId'=>(string)$pto['id'],'ptoActDate'=>'2026-09-04','reason'=>'Поправка']),409,'Работы по объекту не открыты.');assertSameValue($before,$h->facts(),'nonworking unchanged');$h->db->query("UPDATE {$h->p}fm2_installation_cases SET process_state='working' WHERE id=6101");
    // Failed correction INSERT leaves all prior facts intact; runtime account has no DDL.
    $trigger=$h->p.'documentary_fault';$h->db->query("CREATE TRIGGER $trigger BEFORE INSERT ON {$h->p}fm2_pilot_completion_fact_corrections FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='synthetic private documentary failure'");
    try{$before=$h->facts();$r=$f->post('correct_declaration',$correct);assertSameValue([503,'60'],[$r['status'],$r['headers']['retry-after'][0]??null],'sanitized unavailable');assertSameValue(false,str_contains($r['body'],'synthetic private'),'no SQL leak');assertSameValue($before,$h->facts(),'insert failure rollback');}finally{$h->db->query("DROP TRIGGER $trigger");}
    $table=$h->p.'fm2_pilot_completion_fact_corrections';$h->db->query("RENAME TABLE $table TO {$table}_saved");try{$before=$h->facts();assertSameValue(503,$f->page()['status'],'missing schema closed');assertSameValue(503,$f->post('correct_declaration',$correct)['status'],'missing schema mutation closed');assertSameValue($before,$h->facts(),'no runtime repair');}finally{$h->db->query("RENAME TABLE {$table}_saved TO $table");}
    $before=$h->facts();proc_terminate($h->server['process']);proc_close($h->server['process']);$h->server=null;$h->start();assertSameValue(200,$f->page()['status'],'session survives restart');assertSameValue($before,$h->facts(),'restart preserves history');
    $queue=$h->request('GET','/pilot/objects',[],$f->cookies);assertSameValue(true,str_contains($queue['body'],'Работы завершены'),'queue completed');$check=$f->inspection->page();assertSameValue(true,str_contains($check['body'],'data-progress-cap="100"'),'checklist documentary cap100');
    $bad=InspectionFixture::operation(900,41,42);InspectionFixture::result($f->inspection->send($bad,InspectionFixture::csrf($check)),409,'rejected');
    // Completion correction retains its existing admission even after checklist retraction.
    $check=$f->inspection->page();$retract=InspectionFixture::operation(802,43,32);$retract['sectionId']=1;$retract['type']='completion_retracted';$retract['originalClientOperationId']=InspectionFixture::operation(801)['clientOperationId'];$retract['reason']='Сверка выполненной работы';InspectionFixture::result($f->inspection->send($retract,InspectionFixture::csrf($check)),200,'accepted');
    $before=$h->facts();DocumentaryFixture::rejected($f->post('record_pto',['ptoActDate'=>'2026-09-05']),409,'Сначала завершите монтажные работы до 85%.');assertSameValue($before,$h->facts(),'current threshold precedes replay');DocumentaryFixture::accepted($f->post('correct_pto',['factId'=>(string)$pto['id'],'ptoActDate'=>'2026-09-03','reason'=>'Документ исправлен при сверке чек-листа']));$f->unchangedExcept($before,['fm2_pilot_completion_fact_corrections']);
    foreach($h->rows('fm2_pilot_completion_facts') as $row){$at=new DateTimeImmutable($row['recorded_at']);assertSameValue('+03:00',$at->format('P'),'all root timezone');assertSameValue(true,$at->getTimestamp()>=$beforeTime->getTimestamp()&&$at->getTimestamp()<=time(),'all root times bounded');}
    foreach($h->rows('fm2_pilot_completion_fact_corrections') as $row){$at=new DateTimeImmutable($row['recorded_at']);assertSameValue('+03:00',$at->format('P'),'all correction timezone');assertSameValue(true,$at->getTimestamp()>=$beforeTime->getTimestamp()&&$at->getTimestamp()<=time(),'all correction times bounded');}
    $h->noLegacy();echo "PASS: YII2-DOCUMENTARY-CLOSURE-001 HTTP A1-A7\n";
}finally{if($f instanceof DocumentaryFixture)$f->close();}
