<?php
declare(strict_types=1);
require dirname(__DIR__).'/bootstrap.php';require __DIR__.'/ObjectQueueFixture.php';
// INSPECTION-PLANNING-001 A2: independent public owners serialize by object/version.
function objectPlanRace(UserAccessFixture$f,array$operations):array{$dir=$f->artifacts.'/object-plan-race-'.bin2hex(random_bytes(4));mkdir($dir,0700);$e=$f->environment();$c=['connection'=>['dsn'=>'mysql:host='.$e['FMONITOR_DB_HOST'].';port='.$e['FMONITOR_DB_PORT'].';dbname='.$e['FMONITOR_DB_NAME'],'username'=>$f->dmlUser,'password'=>$f->dmlPassword,'charset'=>'utf8mb4'],'prefix'=>$f->p,'directory'=>$dir,'operations'=>$operations];$path=$dir.'/config.json';file_put_contents($path,json_encode($c,JSON_THROW_ON_ERROR));chmod($path,0600);$ps=[];try{foreach($operations as$i=>$op){$p=proc_open([PHP_BINARY,__DIR__.'/inspection_planning_object_worker.php',$path,(string)$i],[0=>['file','/dev/null','r'],1=>['file',$dir.'/worker-'.$i.'.log','a'],2=>['file',$dir.'/worker-'.$i.'.log','a']],$pipes,$f->root);if(!is_resource($p))throw new TestFailure('SETUP_FAILURE worker');$ps[$i]=$p;}$deadline=microtime(true)+15;while(count(glob($dir.'/ready-*'))!==count($operations)){if(microtime(true)>$deadline)throw new TestFailure('SETUP_FAILURE barrier');usleep(10000);}file_put_contents($dir.'/go','go');$out=[];foreach($ps as$i=>$p){$deadline=microtime(true)+20;do{$s=proc_get_status($p);if(!$s['running'])break;usleep(10000);}while(microtime(true)<$deadline);if($s['running'])throw new TestFailure('worker timeout');assertSameValue(0,$s['exitcode'],'worker '.file_get_contents($dir.'/worker-'.$i.'.log'));$out[]=json_decode(file_get_contents($dir.'/result-'.$i.'.json'),true,flags:JSON_THROW_ON_ERROR);proc_close($p);unset($ps[$i]);}return$out;}finally{foreach($ps as$p){proc_terminate($p,9);proc_close($p);}@unlink($path);}}
$f=null;try{$f=new ObjectQueueFixture(dirname(__DIR__,2));$f->db->query("UPDATE {$f->p}fm2_pilot_roles SET code='manager' WHERE role_id=9201");$f->planning();
$create=static fn(string$date,string$id):array=>['method'=>'createInspectionPlan','args'=>[9101,451201,0,$date,$id]];
$r=objectPlanRace($f->http,[$create('2099-09-12','11111111-1111-4111-8111-111111111111'),$create('2099-09-13','22222222-2222-4222-8222-222222222222')]);$statuses=array_column($r,'status');sort($statuses);assertSameValue(['conflict','scheduled'],$statuses,'INTENDED_RED concurrent creates have one winner');assertSameValue([1,1],[count($f->rows('fm2_pilot_inspection_schedules')),count($f->rows('fm2_pilot_inspection_schedule_events'))],'one root and event');$id=(int)$f->rows('fm2_pilot_inspection_schedules')[0]['id'];
$r=objectPlanRace($f->http,[['method'=>'rescheduleInspectionPlan','args'=>[9101,451201,$id,1,'2099-09-14','33333333-3333-4333-8333-333333333333']],['method'=>'cancelInspectionPlan','args'=>[9101,451201,$id,1,'44444444-4444-4444-8444-444444444444']]]);$statuses=array_column($r,'status');assertSameValue(1,count(array_filter($statuses,static fn(string$s):bool=>$s==='stale_plan')),'one stale loser');assertSameValue(1,count(array_filter($statuses,static fn(string$s):bool=>in_array($s,['scheduled','cancelled'],true))),'one valid reschedule/cancel winner');assertSameValue(2,count($f->rows('fm2_pilot_inspection_schedule_events')),'one second event');echo"PASS: INSPECTION-PLANNING-001 object concurrency\n";
}finally{if($f instanceof ObjectQueueFixture)$f->close();}
