<?php
declare(strict_types=1);
require dirname(__DIR__).'/bootstrap.php';require __DIR__.'/UserAccessFixture.php';
// YII2-USER-ACCESS-001: real clicks/forms + independent persisted-facts observation.
$f=null;$process=null;$configPath=null;
try{
$f=new UserAccessFixture(dirname(__DIR__,2));$f->start();$configPath=$f->artifacts.'/browser.json';file_put_contents($configPath,json_encode(['origin'=>'http://127.0.0.1:'.$f->server['port'],'email'=>$f->auth->email,'password'=>$f->auth->password,'artifacts'=>$f->artifacts,'result'=>$f->artifacts.'/result.json','playwright'=>getenv('FMONITOR_TEST_PLAYWRIGHT_MODULE')?:dirname($f->root).'/shlz-ui/node_modules/playwright'],JSON_THROW_ON_ERROR));chmod($configPath,0600);
$process=proc_open([getenv('FMONITOR_TEST_NODE_BINARY')?:'node',__DIR__.'/user_access_browser.mjs',$configPath],[0=>['file','/dev/null','r'],1=>['file',$f->artifacts.'/browser.log','a'],2=>['file',$f->artifacts.'/browser.log','a']],$pipes,$f->root);if(!is_resource($process))throw new TestFailure('SETUP_FAILURE: browser process');$deadline=microtime(true)+90;
do{$state=proc_get_status($process);if(!$state['running'])break;usleep(20000);}while(microtime(true)<$deadline);if($state['running'])throw new TestFailure('browser deadline; '.$f->artifacts);$exit=$state['exitcode'];proc_close($process);$process=null;assertSameValue(0,$exit,'browser flow; '.file_get_contents($f->artifacts.'/browser.log'));
$result=json_decode(file_get_contents($f->artifacts.'/result.json'),true,flags:JSON_THROW_ON_ERROR);$id=(int)$result['userId'];$u=$f->user($id);assertSameValue(['browser.person@shlz.ru','active',1,3],[$u['email'],$u['activation_state'],(int)$u['status'],(int)$u['session_version']],'real forms persisted normalized activated/restored identity');
$history=$f->db->query("SELECT * FROM {$f->p}fm2_pilot_invitations WHERE user_id=$id ORDER BY id")->fetch_all(MYSQLI_ASSOC);assertSameValue(2,count($history),'one issue + one reissue');assertSameValue(true,$history[0]['revoked_at']!==null&&$history[1]['used_at']!==null,'old revoked new used');
$roles=$f->db->query("SELECT role_id FROM {$f->p}fm2_pilot_user_roles WHERE user_id=$id ORDER BY role_id")->fetch_all(MYSQLI_ASSOC);assertSameValue([9210,9212],array_map('intval',array_column($roles,'role_id')),'exact role assignments');$events=$f->db->query("SELECT action,actor_user_id FROM {$f->p}fm2_pilot_user_role_events WHERE user_id=$id ORDER BY id")->fetch_all(MYSQLI_ASSOC);assertSameValue(['role_attached'],array_column($events,'action'),'one browser role event');assertSameValue([9101],array_map('intval',array_column($events,'actor_user_id')),'browser role actor');$status=$f->db->query("SELECT action,actor_user_id FROM {$f->p}fm2_pilot_user_status_events WHERE user_id=$id ORDER BY id")->fetch_all(MYSQLI_ASSOC);assertSameValue(['user_blocked','user_unblocked'],array_column($status,'action'),'browser status history');assertSameValue([9101,9101],array_map('intval',array_column($status,'actor_user_id')),'status actors');
$f->noLegacy();echo 'PASS: YII2-USER-ACCESS-001 real browser and independent facts; artifacts '.$f->artifacts."\n";
}finally{if(is_resource($process)){proc_terminate($process,9);proc_close($process);}if($configPath!==null&&is_file($configPath))unlink($configPath);if($f instanceof UserAccessFixture)$f->close();}
