<?php
declare(strict_types=1);
require dirname(__DIR__).'/bootstrap.php';require __DIR__.'/UserAccessFixture.php';
// YII2-USER-ACCESS-001: distinct processes/connections, literal single-winner oracles.
function yuaRace(UserAccessFixture $f,array $operations):array
{
 $dir=$f->artifacts.'/race-'.bin2hex(random_bytes(4));mkdir($dir,0700);$e=$f->environment();$config=['connection'=>['dsn'=>'mysql:host='.$e['FMONITOR_DB_HOST'].';port='.$e['FMONITOR_DB_PORT'].';dbname='.$e['FMONITOR_DB_NAME'],'username'=>$f->dmlUser,'password'=>$f->dmlPassword,'charset'=>'utf8mb4'],'prefix'=>$f->p,'directory'=>$dir,'operations'=>$operations];$path=$dir.'/config.json';file_put_contents($path,json_encode($config,JSON_THROW_ON_ERROR));chmod($path,0600);$processes=[];
 try{
 foreach($operations as$i=>$op){$process=proc_open([PHP_BINARY,__DIR__.'/user_access_worker.php',$path,(string)$i],[0=>['file','/dev/null','r'],1=>['file',$dir.'/worker-'.$i.'.log','a'],2=>['file',$dir.'/worker-'.$i.'.log','a']],$pipes,$f->root);if(!is_resource($process))throw new TestFailure('SETUP_FAILURE: worker');$processes[$i]=$process;}
 $deadline=microtime(true)+15;while(count(glob($dir.'/ready-*'))!==count($operations)){if(microtime(true)>$deadline)throw new TestFailure('SETUP_FAILURE: ready barrier '.$dir);usleep(10000);}file_put_contents($dir.'/go','go');
 $results=[];foreach($processes as$i=>$process){$deadline=microtime(true)+20;do{$state=proc_get_status($process);if(!$state['running'])break;usleep(10000);}while(microtime(true)<$deadline);if($state['running'])throw new TestFailure('worker timeout '.$dir);assertSameValue(0,$state['exitcode'],'worker result '.file_get_contents($dir.'/worker-'.$i.'.log'));$results[]=json_decode(file_get_contents($dir.'/result-'.$i.'.json'),true,flags:JSON_THROW_ON_ERROR);proc_close($process);unset($processes[$i]);}return$results;
 }finally{foreach($processes as$process){proc_terminate($process,9);proc_close($process);}unlink($path);}
}
$f=null;
try{
$f=new UserAccessFixture(dirname(__DIR__,2));$owner=$f->owner();
$op=['method'=>'invite','arguments'=>[9101,'concurrent.person@shlz.ru','Concurrent']];$r=yuaRace($f,[$op,$op]);$statuses=array_column($r,'status');sort($statuses);assertSameValue(['invalid','issued'],$statuses,'duplicate invite one winner');assertSameValue(1,(int)$f->db->query("SELECT COUNT(*) FROM {$f->p}fm2_pilot_users WHERE email='concurrent.person@shlz.ru'")->fetch_column(),'one user');$issued=$r[0]['status']==='issued'?$r[0]:$r[1];
$passwords=['First activation password 2026','Second activation password 2026'];$r=yuaRace($f,[['method'=>'activate','arguments'=>[$issued['token'],$passwords[0],$passwords[0]]],['method'=>'activate','arguments'=>[$issued['token'],$passwords[1],$passwords[1]]]]);$statuses=array_column($r,'status');sort($statuses);assertSameValue(['activated','invalid'],$statuses,'single-use activation winner');$winner=$r[0]['status']==='activated'?0:1;$id=$issued['userId'];$hash=(string)$f->db->query("SELECT password_hash FROM {$f->p}fm2_pilot_auth_credentials WHERE user_id=$id")->fetch_column();assertSameValue(true,password_verify($passwords[$winner],$hash),'winning hash retained');assertSameValue(false,password_verify($passwords[1-$winner],$hash),'loser cannot overwrite');
$issued=$owner->invite(9101,'activation.race@shlz.ru','Activation race');$id=$issued['userId'];$r=yuaRace($f,[['method'=>'activate','arguments'=>[$issued['token'],'Activation race password','Activation race password']],['method'=>'reissue','arguments'=>[9101,$id]]]);$active=$r[0]['status']==='activated';assertSameValue($active?['activated','invalid']:['invalid','issued'],array_column($r,'status'),'activate/reissue serialized');assertSameValue($active?'active':'invited',$f->user($id)['activation_state'],'state matches winner');assertSameValue($active?0:1,(int)$f->db->query("SELECT COUNT(*) FROM {$f->p}fm2_pilot_invitations WHERE user_id=$id AND used_at IS NULL AND revoked_at IS NULL AND expires_at>NOW(6)")->fetch_column(),'one usable invitation or activated');
$issued=$owner->invite(9101,'reissue.race@shlz.ru','Reissue race');$id=$issued['userId'];$before=$f->db->query("SELECT * FROM {$f->p}fm2_pilot_invitations WHERE user_id=$id ORDER BY id")->fetch_all(MYSQLI_ASSOC);$op=['method'=>'reissue','arguments'=>[9101,$id]];$r=yuaRace($f,[$op,$op]);assertSameValue(['issued','issued'],array_column($r,'status'),'two authorized reissue intents serialized');$rows=$f->db->query("SELECT * FROM {$f->p}fm2_pilot_invitations WHERE user_id=$id ORDER BY id")->fetch_all(MYSQLI_ASSOC);assertSameValue(3,count($rows),'initial plus both reissues retained');assertSameValue($before[0]['id'],$rows[0]['id'],'initial invitation identity retained');assertSameValue($before[0]['token_hash'],$rows[0]['token_hash'],'initial token hash retained');$current=array_values(array_filter($rows,static fn($row)=>$row['used_at']===null&&$row['revoked_at']===null));assertSameValue(1,count($current),'one usable invitation after reissue race');$valid=0;foreach($r as$result)if($owner->invitation($result['token'])!==null)$valid++;assertSameValue(1,$valid,'only final returned token usable');
$f->db->query("INSERT INTO {$f->p}fm2_pilot_role_permissions(role_id,permission) VALUES(9201,'access.superadminister')");assertSameValue('changed',$owner->changeRole(9101,9403,9211,'attach')['status'],'second superadministrator');
$r=yuaRace($f,[['method'=>'changeRole','arguments'=>[9101,9402,9211,'detach']],['method'=>'changeStatus','arguments'=>[9101,9403,'block']]]);$statuses=array_column($r,'status');sort($statuses);assertSameValue(['changed','invalid'],$statuses,'cross-command last-super serialization');assertSameValue(1,(int)$f->db->query("SELECT COUNT(DISTINCT u.user_id) FROM {$f->p}fm2_pilot_users u JOIN {$f->p}fm2_pilot_user_roles ur ON ur.user_id=u.user_id JOIN {$f->p}fm2_pilot_roles r ON r.role_id=ur.role_id WHERE u.status=1 AND BINARY u.activation_state=BINARY 'active' AND r.status=1 AND BINARY r.code=BINARY 'superadministrator'")->fetch_column(),'at least one last super survives');
echo "PASS: YII2-USER-ACCESS-001 concurrent invitation, activation and privileged access\n";
}finally{if($f instanceof UserAccessFixture)$f->close();}
