<?php
declare(strict_types=1);
require dirname(__DIR__).'/bootstrap.php';require __DIR__.'/PreopeningFixture.php';
// YII2-PREOPENING-JOURNEY-001: closed selection transport, paging and immutable pending replacement.
$f=null;
try {
 $f=new PreopeningFixture(dirname(__DIR__,2));$f->start();$p=$f->p;$cookies=[];assertSameValue(303,$f->login($cookies)['status'],'FKR login');$path='/pilot/objects/4512/assignment-order/selection';
 assertSameValue(200,$f->request('GET',$path,[],$cookies)['status'],'INTENDED_RED Yii selection input route');$token=$f->token($cookies);
 $valid=['_csrf'=>$token,'requestId'=>'11111111-1111-4111-8111-000000000001','mode'=>'new_order','expectedSelectionRevision'=>'0','controlEngineerUserId'=>'73','controlEngineerConfirmed'=>'yes','installerTabIds'=>[7001]];
 foreach([['requestId','bad'],['mode','INITIAL'],['expectedSelectionRevision','-1'],['expectedSelectionRevision','4294967296'],['controlEngineerUserId','0'],['controlEngineerUserId',['73']],['unexpected','x']]as[$key,$value]){$before=$f->facts();assertSameValue(400,$f->form($path,array_replace($valid,[$key=>$value]),$cookies)['status'],'malformed field '.$key);assertSameValue($before,$f->facts(),'shape no facts');}
 $scalar=$valid;unset($scalar['installerTabIds']);$raw=http_build_query($scalar).'&installerTabIds%5B%5D=7001';
 foreach([$raw.'&mode=new_order',$raw.'&bad=%GG',$raw.'&bad=%00',$raw.'&installerTabIds%5B0%5D=7001']as$body){$before=$f->facts();assertSameValue(400,$f->request('POST',$path,[],$cookies,['Content-Type: application/x-www-form-urlencoded'],$body)['status'],'closed duplicate/escape/index shape');assertSameValue($before,$f->facts(),'closed decoding no facts');}
 $before=$f->facts();assertSameValue(413,$f->request('POST',$path,[],$cookies,['Content-Type: application/x-www-form-urlencoded'],$raw.'&extra='.str_repeat('x',33000))['status'],'form byte cap');assertSameValue($before,$f->facts(),'oversized form no facts');
 $many=$valid;$many['installerTabIds']=array_fill(0,501,7001);assertSameValue(400,$f->form($path,$many,$cookies)['status'],'installer transport cap');assertSameValue($before,$f->facts(),'list cap no facts');
 $guest=[];assertSameValue(303,$f->request('POST',$path,[],$guest)['status'],'guest before form');
 for($id=8001;$id<=8025;$id++)$f->insert($p.'fm2_workforce_catalog',['installer_tab_id'=>$id,'fio'=>'Пакет '.$id,'position'=>'Монтажник','employment_status'=>'employed','employed_from'=>'2020-01-01','employed_to'=>null,'workforce_source'=>'fixture','workforce_source_updated_at'=>'2026-09-10T09:00:00Z','reconciliation_state'=>'delivered']);
 foreach([1=>[20,true],2=>[5,false]]as$page=>[$count,$more]){$before=$f->facts();$r=$f->request('GET','/pilot/objects/4512/assignment-order/installers?q='.rawurlencode('Пакет').'&page='.$page,[],$cookies);assertSameValue(200,$r['status'],'search page');$json=json_decode($r['body'],true,flags:JSON_THROW_ON_ERROR);assertSameValue(['items','page','hasMore'],array_keys($json),'search envelope');assertSameValue([$count,$page,$more],[count($json['items']),$json['page'],$json['hasMore']],'search paging');assertSameValue($page===1?range(8001,8020):range(8021,8025),array_column($json['items'],'tabId'),'stable entire-catalog search');assertSameValue($before,$f->facts(),'search no facts');}
 foreach(['q=x','q='.str_repeat('x',121),'q=70&page=0','q=70&extra=1']as$query)assertSameValue(400,$f->request('GET','/pilot/objects/4512/assignment-order/installers?'.$query,[],$cookies)['status'],'invalid search');
 assertSameValue(303,$f->selection($cookies)['status'],'initial selection');$old=$f->rows('fm2_assignment_order_selections');$members=$f->rows('fm2_assignment_order_selection_members');assertSameValue(['81','6101'],[$old[0]['assignment_order_id'],$old[0]['installation_case_id']],'identity distinct from version/object');
 assertSameValue(303,$f->selection($cookies,'11111111-1111-4111-8111-000000000002',[7002],'replace_pending',1)['status'],'pending replacement');$new=$f->rows('fm2_assignment_order_selections');assertSameValue(2,count($new),'second immutable selection');assertSameValue($old[0],$new[0],'first selection preserved');assertSameValue(['82','2'],[$new[1]['assignment_order_id'],$new[1]['selection_revision']],'new identity/revision');assertSameValue($members[0],$f->rows('fm2_assignment_order_selection_members')[0],'old member snapshot preserved');
 $before=$f->rows('fm2_assignment_order_selections');assertSameValue(409,$f->selection($cookies,'11111111-1111-4111-8111-000000000003',[7001],'replace_pending',1)['status'],'stale selection conflict');assertSameValue($before,$f->rows('fm2_assignment_order_selections'),'stale no new selected facts');assertSameValue(0,count($f->rows('fm2_assignment_order_applications')),'selection stays separate');assertSameValue([],$f->base->privateFiles(),'selection no artifacts');$f->noLegacy();
 echo "PASS: YII2-PREOPENING-JOURNEY-001 selection shape, paging and replacement\n";
}finally{if($f instanceof PreopeningFixture)$f->close();}
