<?php
declare(strict_types=1);
namespace FMonitor2\IdentityAccess;
final readonly class MariaDbLegacyIdentityLink
{
 public function __construct(private \mysqli$db,private string$p,private string$l,private LegacyIdentityLinkClock$clock){}
 public function link(LegacyIdentityLinkCommand$c):array{
  $reason=$c->correctionReason===null?null:trim($c->correctionReason);$fp=hash('sha256',json_encode([$c->requestId,$c->localUserId,$c->legacyUserId,$c->actorUserId,$reason],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR));$owned=false;
  try{$this->db->query('SET TRANSACTION ISOLATION LEVEL SERIALIZABLE');$this->db->begin_transaction();$owned=true;
   if($this->rows("SELECT u.user_id FROM `{$this->p}fm2_pilot_users`u JOIN `{$this->p}fm2_pilot_user_roles`ur ON ur.user_id=u.user_id JOIN `{$this->p}fm2_pilot_roles`r ON r.role_id=ur.role_id JOIN `{$this->p}fm2_pilot_role_permissions`rp ON rp.role_id=r.role_id WHERE u.user_id=? AND u.status=1 AND r.status=1 AND BINARY rp.permission='access.administer' FOR UPDATE",[$c->actorUserId])===[])return$this->rollback('rejected','authorization_denied');
   $request=$this->rows("SELECT * FROM `{$this->p}fm2_legacy_identity_links` WHERE request_id=? FOR UPDATE",[$c->requestId]);if($request!==[]){$this->db->rollback();return count($request)===1&&hash_equals((string)$request[0]['request_fingerprint'],$fp)?$this->out('replayed',null,$request[0]):$this->out('conflict','request_id_conflict');}
   $legacy=$this->rows("SELECT u.id,u.name,u.email,u.status,u.role_id,r.status role_status FROM `{$this->l}users`u LEFT JOIN `{$this->l}users_roles`r ON r.id=u.role_id WHERE u.id=?",[$c->legacyUserId]);if($legacy===[])return$this->rollback('rejected','legacy_user_not_found');if(count($legacy)!==1)return$this->rollback('conflict','identity_link_ambiguous');if((int)$legacy[0]['status']!==1||(int)$legacy[0]['role_status']!==1)return$this->rollback('rejected','legacy_user_inactive');
   $eligible=$this->rows("SELECT u.user_id FROM `{$this->p}fm2_pilot_users`u JOIN `{$this->p}fm2_pilot_user_roles`ur ON ur.user_id=u.user_id JOIN `{$this->p}fm2_pilot_roles`r ON r.role_id=ur.role_id WHERE u.user_id=? AND u.status=1 AND r.status=1 AND BINARY r.code='construction_control_engineer' FOR UPDATE",[$c->localUserId]);if(count($eligible)!==1)return$this->rollback('rejected','local_engineer_ineligible');
   $current=$this->rows("SELECT l.* FROM `{$this->p}fm2_legacy_identity_links`l WHERE(l.local_user_id=? OR l.legacy_user_id=?)AND NOT EXISTS(SELECT 1 FROM `{$this->p}fm2_legacy_identity_links`s WHERE s.supersedes_link_id=l.link_id)ORDER BY l.link_id FOR UPDATE",[$c->localUserId,$c->legacyUserId]);if(count($current)>1)return$this->rollback('conflict','identity_link_ambiguous');$old=$current[0]??null;
   if($old!==null&&$reason===null)return$this->rollback('conflict',(int)$old['legacy_user_id']===$c->legacyUserId?'legacy_user_already_linked':'local_user_already_linked');if($old===null&&$reason!==null)return$this->rollback('conflict','local_user_already_linked');if($old!==null&&$reason==='')return$this->rollback('rejected','correction_reason_required');
   $at=(new \DateTimeImmutable($this->clock->now()))->setTimezone(new \DateTimeZone('UTC'))->format('Y-m-d H:i:s');$s=$this->db->prepare("INSERT INTO `{$this->p}fm2_legacy_identity_links`(local_user_id,legacy_user_id,legacy_name_snapshot,legacy_email_snapshot,legacy_status_snapshot,legacy_role_id_snapshot,legacy_role_status_snapshot,linked_by_user_id,linked_at_utc,request_id,request_fingerprint,supersedes_link_id,correction_reason)VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)");$s->execute([$c->localUserId,$c->legacyUserId,$legacy[0]['name'],$legacy[0]['email'],$legacy[0]['status'],$legacy[0]['role_id'],$legacy[0]['role_status'],$c->actorUserId,$at,$c->requestId,$fp,$old['link_id']??null,$reason]);$id=(int)$this->db->insert_id;$e=$this->db->prepare("INSERT INTO `{$this->p}fm2_legacy_identity_link_events`(link_id,event_type,actor_user_id,occurred_at_utc,request_id)VALUES(?,?,?,?,?)");$e->execute([$id,$old===null?'linked':'corrected',$c->actorUserId,$at,$c->requestId]);$row=$this->rows("SELECT * FROM `{$this->p}fm2_legacy_identity_links` WHERE link_id=?",[$id])[0];$this->db->commit();$owned=false;return$this->out($old===null?'linked':'corrected',null,$row);
  }catch(\Throwable){if($owned)try{$this->db->rollback();}catch(\Throwable){}return$this->out('failed','persistence_failure');}
 }
 public function directory(int$actorUserId):array{
  if($actorUserId<1)throw new \DomainException('authorization_denied');
  $allowed=$this->rows("SELECT DISTINCT u.user_id FROM `{$this->p}fm2_pilot_users`u JOIN `{$this->p}fm2_pilot_user_roles`ur ON ur.user_id=u.user_id JOIN `{$this->p}fm2_pilot_roles`r ON r.role_id=ur.role_id JOIN `{$this->p}fm2_pilot_role_permissions`rp ON rp.role_id=r.role_id WHERE u.user_id=? AND u.status=1 AND r.status=1 AND BINARY rp.permission='access.administer'",[$actorUserId]);if(count($allowed)!==1)throw new \DomainException('authorization_denied');
  $links=$this->rows("SELECT l.local_user_id,l.legacy_user_id,l.legacy_name_snapshot FROM `{$this->p}fm2_legacy_identity_links`l WHERE NOT EXISTS(SELECT 1 FROM `{$this->p}fm2_legacy_identity_links`s WHERE s.supersedes_link_id=l.link_id)ORDER BY l.link_id",[]);$out=[];foreach($links as$row)$out[(int)$row['local_user_id']]=$row;return$out;
 }
 private function rollback(string$s,string$r):array{$this->db->rollback();return$this->out($s,$r);}
 private function rows(string$q,array$v):array{$s=$this->db->prepare($q);$s->execute($v);return$s->get_result()->fetch_all(MYSQLI_ASSOC);}
 private function out(string$s,?string$r,?array$row=null):array{return['status'=>$s,'reasonCode'=>$r,'link'=>$row===null?null:['linkId'=>(int)$row['link_id'],'localUserId'=>(int)$row['local_user_id'],'legacyUserId'=>(int)$row['legacy_user_id']]];}
}
