<?php
declare(strict_types=1);
namespace FMonitor\IdentityAccess;
require_once __DIR__.'/PilotSessionInspectionTypes.php';
final class PilotSessionStorageInspector implements PilotSessionStorageInspection
{
 public function inspect(PilotSessionStorageConfig$c,PilotSessionFilesystemPrimitives$f):PilotSessionInspectionResult{try{if($c->stateRoot===''||$c->stateRoot[0]!=='/'||!preg_match('/^[a-z0-9][a-z0-9_-]{0,31}$/D',$c->instance))return PilotSessionInspectionResult::inspectorUnavailable();$paths=[$c->stateRoot,$c->stateRoot.'/sessions',$c->stateRoot.'/sessions/'.$c->instance];$dirs=[];foreach($paths as$p){$r=$f->lstat($p);if(!$this->dir($r))return PilotSessionInspectionResult::inspectorUnavailable();$dirs[]=$this->metadata($r->value(),true);} $list=$f->list($paths[2]);if($list->outcome()!==PilotSessionPrimitiveOutcome::OK||!is_array($list->value())||count(array_unique($list->value(),SORT_STRING))!==count($list->value()))return PilotSessionInspectionResult::inspectorUnavailable();$entries=[];foreach($list->value()as$n){$type=$this->type($n);if($type===null)return PilotSessionInspectionResult::inspectorUnavailable();$p=$paths[2].'/'.$n;$s=$f->lstat($p);if(!$this->file($s))return PilotSessionInspectionResult::inspectorUnavailable();$h=$f->open($p,'rb',0600);if($h->outcome()!==PilotSessionPrimitiveOutcome::OK||!$h->value()instanceof PilotSessionFileHandle)return PilotSessionInspectionResult::inspectorUnavailable();$read=$f->read($h->value(),$s->value()->size()+1);$after=$f->fstat($h->value());$close=$f->close($h->value());if($read->outcome()!==PilotSessionPrimitiveOutcome::OK||!is_string($read->value())||strlen($read->value())!==$s->value()->size()||!$this->same($s,$after)||$close->outcome()!==PilotSessionPrimitiveOutcome::OK)return PilotSessionInspectionResult::inspectorUnavailable();$entries[]=array_merge(['entryKeySha256'=>hash('sha256',$n),'logicalType'=>$type],$this->metadata($s->value(),false),['contentSha256'=>hash('sha256',$read->value())]);}usort($entries,fn($a,$b)=>strcmp($a['entryKeySha256'],$b['entryKeySha256']));$json=json_encode(['schemaVersion'=>1,'root'=>$dirs[0],'sessions'=>$dirs[1],'instance'=>$dirs[2],'entries'=>$entries],JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR);return PilotSessionInspectionResult::inspectorOk($json);}catch(\Throwable){return PilotSessionInspectionResult::inspectorUnavailable();}}
 private function type(string$n):?string{if(preg_match('/^l-[0-9a-f]{64}\.lock$/D',$n))return'lock';if(preg_match('/^s-[A-Za-z0-9,-]{16,128}\.session$/D',$n))return'committed';if(preg_match('/^\.stage-[0-9a-f]{64}-[0-9a-f]{32}\.session$/D',$n))return'stage';if(preg_match('/^\.revoked-[0-9a-f]{64}-[0-9a-f]{32}\.session$/D',$n))return'revoked';return null;}private function dir(PilotSessionPrimitiveResult$r):bool{return$r->outcome()===PilotSessionPrimitiveOutcome::OK&&$r->value()instanceof PilotSessionFileStat&&$r->value()->type()===PilotSessionFileType::DIRECTORY&&$r->value()->uid()===posix_geteuid()&&in_array($r->value()->mode(),[0700,0750,0755],true);}private function file(PilotSessionPrimitiveResult$r):bool{return$r->outcome()===PilotSessionPrimitiveOutcome::OK&&$r->value()instanceof PilotSessionFileStat&&$r->value()->type()===PilotSessionFileType::REGULAR&&$r->value()->uid()===posix_geteuid()&&$r->value()->mode()===0600;}private function same(PilotSessionPrimitiveResult$a,PilotSessionPrimitiveResult$b):bool{return$b->outcome()===PilotSessionPrimitiveOutcome::OK&&$b->value()instanceof PilotSessionFileStat&&$a->value()->inode()===$b->value()->inode()&&$a->value()->device()===$b->value()->device()&&$a->value()->size()===$b->value()->size();}private function metadata(PilotSessionFileStat$s,bool$type):array{$m=['uid'=>$s->uid(),'mode'=>$s->mode(),'device'=>$s->device(),'inode'=>$s->inode(),'linkCount'=>$s->linkCount(),'size'=>$s->size(),'mtime'=>$s->mtime()];return$type?['type'=>$s->type()->value]+$m:$m;}
}
