<?php
declare(strict_types=1);

namespace FMonitor\IdentityAccess;

final readonly class PilotSessionStorageConfig { public function __construct(public string $stateRoot, public string $instance) {} }
interface PilotSessionStorage { public function start(?string $suppliedSessionId): PilotSessionOperationResult; public function writeCommit(string $sessionId,string $data): PilotSessionOperationResult; public function regenerate(string $oldSessionId,string $data): PilotSessionOperationResult; public function destroyCommit(string $sessionId): PilotSessionOperationResult; public function close(): PilotSessionOperationResult; }
interface PilotSessionClock { public function wallSeconds(): int; public function monotonicNanoseconds(): int; }
interface PilotSessionEntropy { public function bytes(int $length): PilotSessionEntropyResult; }
interface PilotSessionLifecycleObserver { public function observe(PilotSessionFilesystemEvent $event): void; }
interface PilotSessionFilesystemPrimitives { public function lstat(string $path): PilotSessionPrimitiveResult; public function fstat(PilotSessionFileHandle $handle): PilotSessionPrimitiveResult; public function mkdir(string $path,int $mode): PilotSessionPrimitiveResult; public function open(string $path,string $mode,int $permissions): PilotSessionPrimitiveResult; public function read(PilotSessionFileHandle $handle,int $length): PilotSessionPrimitiveResult; public function write(PilotSessionFileHandle $handle,string $bytes): PilotSessionPrimitiveResult; public function fflush(PilotSessionFileHandle $handle): PilotSessionPrimitiveResult; public function fsyncFile(PilotSessionFileHandle $handle): PilotSessionPrimitiveResult; public function fsyncDirectory(string $path): PilotSessionPrimitiveResult; public function link(string $existingPath,string $newPath): PilotSessionPrimitiveResult; public function rename(string $fromPath,string $toPath): PilotSessionPrimitiveResult; public function unlink(string $path): PilotSessionPrimitiveResult; public function flock(PilotSessionFileHandle $handle,int $operation): PilotSessionPrimitiveResult; public function close(PilotSessionFileHandle $handle): PilotSessionPrimitiveResult; public function list(string $directory): PilotSessionPrimitiveResult; public function mtime(string $path): PilotSessionPrimitiveResult; }
enum PilotSessionFilesystemOperation:string { case LSTAT='lstat';case FSTAT='fstat';case MKDIR='mkdir';case OPEN='open';case READ='read';case WRITE='write';case FFLUSH='fflush';case FSYNC_FILE='fsyncFile';case FSYNC_DIRECTORY='fsyncDirectory';case LINK='link';case RENAME='rename';case UNLINK='unlink';case FLOCK='flock';case CLOSE='close';case LIST='list';case MTIME='mtime'; }
enum PilotSessionLogicalArtifact:string { case ROOT='root';case SESSIONS='sessions';case INSTANCE='instance';case LOCK='lock';case COMMITTED='committed';case STAGE='stage';case REVOKED='revoked'; }
enum PilotSessionFilesystemPhase:string { case BEFORE='before';case AFTER='after'; }
enum PilotSessionPrimitiveOutcome:string { case OK='ok';case NATIVE_FALSE='false';case WARNING='warning';case EXCEPTION='exception';case SHORT_IO='short_io'; }
enum PilotSessionPrimitiveFailureCode:string { case NOT_FOUND='not_found';case ALREADY_EXISTS='already_exists';case PERMISSION_DENIED='permission_denied';case INTERRUPTED='interrupted';case INVALID_ARGUMENT='invalid_argument';case IO_ERROR='io_error';case UNSUPPORTED='unsupported';case UNKNOWN='unknown'; }
enum PilotSessionFileType:string { case REGULAR='regular';case DIRECTORY='directory';case SYMLINK='symlink';case OTHER='other'; }
enum PilotSessionEntropyStatus:string { case OK='ok';case FAILED='failed'; }
enum PilotSessionOperationStatus:string { case OK='ok';case NOT_FOUND='not_found';case INVALID='invalid';case UNAVAILABLE='unavailable'; }
enum PilotSessionUnavailableCategory:string { case CONFIGURATION_INVALID='configuration_invalid';case ROOT_INVALID='root_invalid';case PAYLOAD_INVALID='payload_invalid';case ENTROPY_FAILED='entropy_failed';case ID_COLLISION='id_collision';case LOCK_TIMEOUT='lock_timeout';case READ_FAILED='read_failed';case WRITE_FAILED='write_failed';case FSYNC_FAILED='fsync_failed';case PUBLISH_FAILED='publish_failed';case SESSION_STALE='session_stale';case REGENERATE_FAILED='regenerate_failed';case DESTROY_FAILED='destroy_failed';case GC_FAILED='gc_failed';case CLOSE_FAILED='close_failed'; }
final readonly class PilotSessionEntropyResult { private function __construct(private PilotSessionEntropyStatus $status,private ?string $bytes){} public static function ok(string $bytes):self{return new self(PilotSessionEntropyStatus::OK,$bytes);}public static function failed():self{return new self(PilotSessionEntropyStatus::FAILED,null);}public function status():PilotSessionEntropyStatus{return$this->status;}public function bytes():?string{return$this->bytes;} }
final readonly class PilotSessionFileHandle { private function __construct(private string $identity){}public static function mint():self{return new self(bin2hex(random_bytes(16)));} }
final readonly class PilotSessionFileStat { public function __construct(private PilotSessionFileType $type,private int $uid,private int $mode,private int $device,private int $inode,private int $linkCount,private int $size,private int $mtime){foreach([$uid,$mode,$device,$inode,$linkCount,$size,$mtime]as$v)if($v<0)throw new \InvalidArgumentException('negative metadata');}public function type():PilotSessionFileType{return$this->type;}public function uid():int{return$this->uid;}public function mode():int{return$this->mode;}public function device():int{return$this->device;}public function inode():int{return$this->inode;}public function linkCount():int{return$this->linkCount;}public function size():int{return$this->size;}public function mtime():int{return$this->mtime;} }
final readonly class PilotSessionPrimitiveResult { private function __construct(private PilotSessionPrimitiveOutcome$outcome,private mixed$value,private ?PilotSessionPrimitiveFailureCode$failureCode){}public static function ok(mixed$value):self{return new self(PilotSessionPrimitiveOutcome::OK,$value,null);}public static function nativeFalse():self{return new self(PilotSessionPrimitiveOutcome::NATIVE_FALSE,null,null);}public static function warning(PilotSessionPrimitiveFailureCode$c):self{return new self(PilotSessionPrimitiveOutcome::WARNING,null,$c);}public static function exception(PilotSessionPrimitiveFailureCode$c):self{return new self(PilotSessionPrimitiveOutcome::EXCEPTION,null,$c);}public static function shortIo(string|int$v):self{return new self(PilotSessionPrimitiveOutcome::SHORT_IO,$v,null);}public function outcome():PilotSessionPrimitiveOutcome{return$this->outcome;}public function value():mixed{return$this->value;}public function failureCode():?PilotSessionPrimitiveFailureCode{return$this->failureCode;} }
final readonly class PilotSessionFilesystemEvent { private function __construct(private int$sequence,private PilotSessionFilesystemOperation$operation,private PilotSessionFilesystemPhase$phase,private PilotSessionLogicalArtifact$artifact,private ?string$hash,private int$ordinal,private ?PilotSessionPrimitiveOutcome$outcome){}public static function ownerBefore(int$s,PilotSessionFilesystemOperation$o,PilotSessionLogicalArtifact$a,?string$h,int$n):self{return self::make($s,$o,PilotSessionFilesystemPhase::BEFORE,$a,$h,$n,null);}public static function ownerAfter(int$s,PilotSessionFilesystemOperation$o,PilotSessionLogicalArtifact$a,?string$h,int$n,PilotSessionPrimitiveOutcome$out):self{return self::make($s,$o,PilotSessionFilesystemPhase::AFTER,$a,$h,$n,$out);}private static function make(int$s,PilotSessionFilesystemOperation$o,PilotSessionFilesystemPhase$p,PilotSessionLogicalArtifact$a,?string$h,int$n,?PilotSessionPrimitiveOutcome$out):self{if($s<1||$n<1)throw new \InvalidArgumentException('positive event values required');$directory=in_array($a,[PilotSessionLogicalArtifact::ROOT,PilotSessionLogicalArtifact::SESSIONS,PilotSessionLogicalArtifact::INSTANCE],true);if(($directory&&$h!==null)||(!$directory&&!preg_match('/^[0-9a-f]{64}$/D',(string)$h)))throw new \InvalidArgumentException('invalid event hash');return new self($s,$o,$p,$a,$h,$n,$out);}public function sequence():int{return$this->sequence;}public function operation():PilotSessionFilesystemOperation{return$this->operation;}public function phase():PilotSessionFilesystemPhase{return$this->phase;}public function artifact():PilotSessionLogicalArtifact{return$this->artifact;}public function sessionIdSha256():?string{return$this->hash;}public function ordinal():int{return$this->ordinal;}public function outcome():?PilotSessionPrimitiveOutcome{return$this->outcome;} }
final readonly class PilotSessionOperationResult { private function __construct(private PilotSessionOperationStatus$status,private ?PilotSessionUnavailableCategory$category,private ?string$correlation,private ?string$id,private ?string$payload){}private static function success(?string$id):self{return new self(PilotSessionOperationStatus::OK,null,null,$id,null);}public static function ownerStarted(string$id,string$payload):self{if(!preg_match('/^[A-Za-z0-9,-]{16,128}$/D',$id))throw new \InvalidArgumentException('invalid session id');return new self(PilotSessionOperationStatus::OK,null,null,$id,$payload);}public static function ownerWriteCommitted(string$id):self{return self::success($id);}public static function ownerRegenerated(string$id):self{return self::success($id);}public static function ownerDestroyed():self{return self::success(null);}public static function ownerClosed():self{return self::success(null);}public static function ownerNotFound():self{return new self(PilotSessionOperationStatus::NOT_FOUND,null,null,null,null);}public static function ownerInvalid():self{return new self(PilotSessionOperationStatus::INVALID,null,null,null,null);}public static function ownerUnavailable(PilotSessionUnavailableCategory$c,string$correlation):self{if(!preg_match('/^[0-9a-f]{12}$/D',$correlation))throw new \InvalidArgumentException('invalid correlation');return new self(PilotSessionOperationStatus::UNAVAILABLE,$c,$correlation,null,null);}public function status():PilotSessionOperationStatus{return$this->status;}public function category():?PilotSessionUnavailableCategory{return$this->category;}public function correlationId():?string{return$this->correlation;}public function currentSessionId():?string{return$this->id;}public function sessionPayload():?string{return$this->payload;} }
