<?php
declare(strict_types=1);
namespace FMonitor2\RuntimeRestore;

use FMonitor2\Runtime\RuntimeConfiguration;
use FMonitor2\Runtime\RuntimeReadiness;

final class RuntimeRecovery
{
    public static function run(array $argv,array $environment):array
    {
        try{return match($argv[1]??''){ 'backup'=>self::backup(array_slice($argv,2),$environment),'restore'=>self::restore(array_slice($argv,2),$environment),default=>self::out(64,'CONFIGURATION_INVALID')};}
        catch(\mysqli_sql_exception){return self::out(69,'DATABASE_UNAVAILABLE');}
        catch(RecoveryFailure $failure){return self::out($failure->exit,$failure->reason);}
        catch(\Throwable){return self::out(70,'BACKUP_FAILED');}
    }
    private static function backup(array$args,array$env):array
    {
        $options=self::options($args,['destination','source-commit','image-reference','image-id'],['writers-stopped']);if(!isset($options['writers-stopped']))return self::out(65,'SOURCE_NOT_QUIESCED');$config=self::config($env);$destination=self::path($options['destination']);if(file_exists($destination)||is_link($destination))return self::out(66,'DESTINATION_NOT_EMPTY');if(!preg_match('/^[0-9a-f]{40}$/D',$options['source-commit'])||!preg_match('/^sha256:[0-9a-f]{64}$/D',$options['image-id'])||$options['image-reference']===''||preg_match('/[\x00-\x1f\x7f]/',$options['image-reference']))throw new RecoveryFailure(64,'CONFIGURATION_INVALID');
        $state=self::path($config->value('FMONITOR_SESSION_STATE_ROOT'),true);$inventory=self::inventory($state);$partial=self::partial($destination);$published=false;
        try{if(!mkdir($partial,0700))throw new RecoveryFailure(70,'BACKUP_FAILED');chmod($partial,0700);$dump=$partial.'/database.sql';$archive=$partial.'/state.tar';try{RuntimeReadiness::assertReady($config);}catch(\Throwable){throw new RecoveryFailure(70,'BACKUP_FAILED');}$db=self::db($config);try{$schemaVersion=max(array_keys(\FMonitor2\InstallationProcess\ProductionPilotMigrationCatalogue::migrations()));$tables=self::schemaTables($db,$config->value('FMONITOR_PROCESS_TABLE_PREFIX'));$autoIncrement=self::autoIncrement($db,$config->value('FMONITOR_PROCESS_TABLE_PREFIX'));}finally{$db->close();}self::dump($config,$dump);self::command(['tar','--format=ustar','-cf',$archive,'-C',$state,'.'],null,null,'BACKUP_FAILED');foreach([$dump,$archive]as$file)chmod($file,0600);$manifest=['formatVersion'=>'fmonitor-runtime-backup-v1','createdAtUtc'=>gmdate('Y-m-d\TH:i:s\Z'),'sourceCommit'=>$options['source-commit'],'imageReference'=>$options['image-reference'],'imageId'=>$options['image-id'],'database'=>['name'=>$config->value('FMONITOR_DB_NAME'),'schemaVersion'=>$schemaVersion,'tables'=>$tables,'byteSize'=>filesize($dump),'sha256'=>hash_file('sha256',$dump),'autoIncrement'=>$autoIncrement],'state'=>['byteSize'=>filesize($archive),'sha256'=>hash_file('sha256',$archive),'members'=>$inventory],'deferred'=>RuntimeRecoverySchemaV24::DEFERRED,'policyDecisions'=>['RETENTION_NEEDS_GRILL','RPO_NEEDS_GRILL','RTO_NEEDS_GRILL']];$manifestPath=$partial.'/manifest.json';file_put_contents($manifestPath,json_encode($manifest,JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR)."\n",LOCK_EX);chmod($manifestPath,0600);foreach([$dump,$archive,$manifestPath]as$file){$h=fopen($file,'rb');if(!is_resource($h)||!fsync($h))throw new RecoveryFailure(70,'BACKUP_FAILED');fclose($h);}self::fsyncDirectory($partial);if(file_exists($destination)||!rename($partial,$destination))throw new RecoveryFailure(66,'DESTINATION_NOT_EMPTY');self::fsyncDirectory(dirname($destination));$published=true;return['exitCode'=>0,'result'=>['ok'=>true,'reason'=>'BACKUP_CREATED','formatVersion'=>'fmonitor-runtime-backup-v1']];}
        finally{if(!$published&&is_dir($partial))self::remove($partial);}
    }
    private static function restore(array$args,array$env):array
    {
        $options=self::options($args,['bundle','target-state-root','source-commit','image-reference','image-id'],[]);$config=self::config($env);$bundle=self::path($options['bundle'],true);$target=self::path($options['target-state-root']);if($target!==$config->value('FMONITOR_SESSION_STATE_ROOT'))throw new RecoveryFailure(64,'CONFIGURATION_INVALID');$manifest=self::preflight($bundle,$config->value('FMONITOR_PROCESS_TABLE_PREFIX'));if($options['source-commit']!==$manifest['sourceCommit']||$options['image-reference']!==$manifest['imageReference']||$options['image-id']!==$manifest['imageId'])throw new RecoveryFailure(67,'BUNDLE_INVALID');$db=self::db($config);try{$count=(int)$db->query('SELECT COUNT(*) n FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE()')->fetch_assoc()['n'];}finally{$db->close();}if($count!==0||file_exists($target)||is_link($target))return self::out(66,'TARGET_NOT_EMPTY');$stage=$target.'.restore-'.bin2hex(random_bytes(16));
        try{$db=self::db($config);try{$migration=\FMonitor2\InstallationProcess\CanonicalMigrationApplication::run($db,$config->value('FMONITOR_PROCESS_TABLE_PREFIX'),\FMonitor2\InstallationProcess\ProductionPilotMigrationCatalogue::migrations());if($migration['exitCode']!==0||($migration['result']['schemaVersion']??null)!==$manifest['database']['schemaVersion']||self::schemaTables($db,$config->value('FMONITOR_PROCESS_TABLE_PREFIX'))!==$manifest['database']['tables'])throw new RecoveryFailure(70,'RESTORE_FAILED');}finally{$db->close();}self::import($config,$bundle.'/database.sql');$db=self::db($config);try{self::restoreAutoIncrement($db,$manifest['database']['autoIncrement'],$config->value('FMONITOR_PROCESS_TABLE_PREFIX'));}finally{$db->close();}if(!mkdir($stage,0700,true))throw new RecoveryFailure(70,'RESTORE_FAILED');self::command(['tar','-xf',$bundle.'/state.tar','-C',$stage],null,null,'RESTORE_FAILED');self::assertExtracted($stage,$manifest['state']['members']);if(!rename($stage,$target))throw new RecoveryFailure(70,'RESTORE_FAILED');try{RuntimeReadiness::assertReady($config);}catch(\Throwable){throw new RecoveryFailure(70,'READINESS_FAILED');}return self::out(0,'RESTORE_COMPLETED');}
        catch(RecoveryFailure $failure){throw$failure;}catch(\Throwable){throw new RecoveryFailure(70,'RESTORE_FAILED');}
    }
    private static function preflight(string$bundle,string$prefix):array
    {
        $invalid=static fn()=>throw new RecoveryFailure(67,'BUNDLE_INVALID');$stat=lstat($bundle);
        if(!is_array($stat)||is_link($bundle)||!is_dir($bundle)||($stat['mode']&0777)!==0700||$stat['uid']!==posix_geteuid()||$stat['gid']!==posix_getegid())$invalid();
        $names=array_values(array_diff(scandir($bundle)?:[],['.','..']));sort($names,SORT_STRING);if($names!==['database.sql','manifest.json','state.tar'])$invalid();
        foreach($names as$name){$p=$bundle.'/'.$name;$s=lstat($p);if(!is_array($s)||is_link($p)||!is_file($p)||($s['mode']&0777)!==0600||$s['uid']!==posix_geteuid()||$s['gid']!==posix_getegid())$invalid();}
        try{$manifest=json_decode((string)file_get_contents($bundle.'/manifest.json'),true,32,JSON_THROW_ON_ERROR);}catch(\Throwable){$invalid();}
        if(!is_array($manifest)||array_keys($manifest)!==['formatVersion','createdAtUtc','sourceCommit','imageReference','imageId','database','state','deferred','policyDecisions']||$manifest['formatVersion']!=='fmonitor-runtime-backup-v1'||!preg_match('/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z$/D',(string)$manifest['createdAtUtc'])||!preg_match('/^[0-9a-f]{40}$/D',(string)$manifest['sourceCommit'])||!preg_match('/^sha256:[0-9a-f]{64}$/D',(string)$manifest['imageId'])||$manifest['deferred']!==RuntimeRecoverySchemaV24::DEFERRED||$manifest['policyDecisions']!==['RETENTION_NEEDS_GRILL','RPO_NEEDS_GRILL','RTO_NEEDS_GRILL'])$invalid();
        if(array_keys($manifest['database']??[])!==['name','schemaVersion','tables','byteSize','sha256','autoIncrement']||$manifest['database']['schemaVersion']!==RuntimeRecoverySchemaV24::VERSION||$manifest['database']['tables']!==RuntimeRecoverySchemaV24::tables($prefix)||!is_array($manifest['database']['autoIncrement'])||array_keys($manifest['state']??[])!==['byteSize','sha256','members'])$invalid();
        foreach(['database.sql'=>'database','state.tar'=>'state']as$file=>$key)if(filesize($bundle.'/'.$file)!==$manifest[$key]['byteSize']||hash_file('sha256',$bundle.'/'.$file)!==$manifest[$key]['sha256'])$invalid();
        self::validateAutoIncrement($manifest['database']['autoIncrement'],$prefix,$manifest['database']['tables']);self::validateTarDirectoryModes($bundle.'/state.tar');$actual=self::tarInventory($bundle.'/state.tar');if($actual!==$manifest['state']['members'])$invalid();return$manifest;
    }
    private static function inventory(string$root):array
    {
        $out=[];$walk=new \RecursiveIteratorIterator(new \RecursiveDirectoryIterator($root,\FilesystemIterator::SKIP_DOTS),\RecursiveIteratorIterator::SELF_FIRST);foreach($walk as$item){$path=$item->getPathname();$relative=substr($path,strlen($root)+1);self::relative($relative);if($item->isLink()||(!$item->isDir()&&!$item->isFile()))throw new RecoveryFailure(70,'BACKUP_FAILED');$s=lstat($path);$mode=is_array($s)?$s['mode']&0777:0;if(!is_array($s)||$s['uid']!==posix_geteuid()||$s['gid']!==posix_getegid()||($item->isDir()&&$mode!==0700)||($item->isFile()&&$mode!==0600))throw new RecoveryFailure(70,'BACKUP_FAILED');if($item->isFile())$out[]=['path'=>$relative,'byteSize'=>$item->getSize(),'sha256'=>hash_file('sha256',$path),'mode'=>$mode];}usort($out,fn($a,$b)=>strcmp($a['path'],$b['path']));return$out;
    }
    private static function tarInventory(string$path):array
    {
        $h=fopen($path,'rb');if(!is_resource($h))throw new RecoveryFailure(67,'BUNDLE_INVALID');$out=[];$seen=[];try{while(true){$header=fread($h,512);if($header===false||strlen($header)!==512)throw new RecoveryFailure(67,'BUNDLE_INVALID');if($header===str_repeat("\0",512)){$rest=stream_get_contents($h);if(strlen($rest)<512||trim($rest,"\0")!=='')throw new RecoveryFailure(67,'BUNDLE_INVALID');break;}$stored=octdec(trim(substr($header,148,8)," \0"));$checksumHeader=substr_replace($header,'        ',148,8);if(array_sum(unpack('C*',$checksumHeader))!==$stored)throw new RecoveryFailure(67,'BUNDLE_INVALID');$name=rtrim(substr($header,0,100),"\0");$prefix=rtrim(substr($header,345,155),"\0");if($prefix!=='')$name=$prefix.'/'.$name;$name=preg_replace('#^\./#','',$name);$type=$header[156];$size=octdec(trim(substr($header,124,12)," \0"));$mode=octdec(trim(substr($header,100,8)," \0"))&0777;if($name===''&&$type==='5')continue;if($name===''||isset($seen[$name]))throw new RecoveryFailure(67,'BUNDLE_INVALID');$seen[$name]=true;self::relative(rtrim($name,'/'));if($type==='5'){if($mode!==0700&&$mode!==0750&&$mode!==0755)throw new RecoveryFailure(67,'BUNDLE_INVALID');continue;}if($type!=="\0"&&$type!=='0')throw new RecoveryFailure(67,'BUNDLE_INVALID');if($mode!==0600)throw new RecoveryFailure(67,'BUNDLE_INVALID');$context=hash_init('sha256');$left=$size;while($left>0){$chunk=fread($h,min($left,1048576));if($chunk===false||$chunk==='')throw new RecoveryFailure(67,'BUNDLE_INVALID');hash_update($context,$chunk);$left-=strlen($chunk);}if($padding=(512-($size%512))%512)if(strlen((string)fread($h,$padding))!==$padding)throw new RecoveryFailure(67,'BUNDLE_INVALID');$out[]=['path'=>$name,'byteSize'=>$size,'sha256'=>hash_final($context),'mode'=>$mode];}}finally{fclose($h);}usort($out,fn($a,$b)=>strcmp($a['path'],$b['path']));return$out;
    }
    private static function validateTarDirectoryModes(string$path):void{$h=fopen($path,'rb');if(!is_resource($h))throw new RecoveryFailure(67,'BUNDLE_INVALID');try{while(true){$header=fread($h,512);if(!is_string($header)||strlen($header)!==512)throw new RecoveryFailure(67,'BUNDLE_INVALID');if($header===str_repeat("\0",512))break;$size=octdec(trim(substr($header,124,12)," \0"));$mode=octdec(trim(substr($header,100,8)," \0"))&0777;if($header[156]==='5'&&$mode!==0700)throw new RecoveryFailure(67,'BUNDLE_INVALID');$skip=$size+((512-($size%512))%512);if($skip>0&&fseek($h,$skip,SEEK_CUR)!==0)throw new RecoveryFailure(67,'BUNDLE_INVALID');}}finally{fclose($h);}}
    private static function assertExtracted(string$root,array$expected):void{$actual=self::inventory($root);if($actual!==$expected)throw new RecoveryFailure(70,'READINESS_FAILED');}
    private static function dump(RuntimeConfiguration$c,string$file):void{$args=['mariadb-dump','--host='.$c->value('FMONITOR_DB_HOST'),'--port='.$c->value('FMONITOR_DB_PORT'),'--user='.$c->value('FMONITOR_DB_USER'),'--single-transaction','--no-create-info','--complete-insert','--replace','--skip-add-locks','--skip-triggers','--skip-routines','--skip-events','--hex-blob','--skip-comments',$c->value('FMONITOR_DB_NAME')];self::command($args,null,$file,'BACKUP_FAILED',['MYSQL_PWD'=>$c->value('FMONITOR_DB_PASSWORD')]);chmod($file,0600);if(!is_file($file)||filesize($file)<1)throw new RecoveryFailure(70,'BACKUP_FAILED');}
    private static function autoIncrement(\mysqli$db,string$prefix):array{$statement=$db->prepare('SELECT TABLE_NAME,AUTO_INCREMENT FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_TYPE=\'BASE TABLE\' AND AUTO_INCREMENT IS NOT NULL ORDER BY BINARY TABLE_NAME');$statement->execute();$out=[];foreach($statement->get_result()->fetch_all(MYSQLI_ASSOC)as$row)$out[]=['table'=>(string)$row['TABLE_NAME'],'nextValue'=>(int)$row['AUTO_INCREMENT']];if(array_column($out,'table')!==RuntimeRecoverySchemaV24::autoIncrement($prefix))throw new RecoveryFailure(70,'BACKUP_FAILED');return$out;}
    private static function schemaTables(\mysqli$db,string$prefix):array{$tables=array_column($db->query("SELECT TABLE_NAME FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_TYPE='BASE TABLE' ORDER BY BINARY TABLE_NAME")->fetch_all(MYSQLI_ASSOC),'TABLE_NAME');if($tables!==RuntimeRecoverySchemaV24::tables($prefix))throw new RecoveryFailure(70,'BACKUP_FAILED');return$tables;}
    private static function restoreAutoIncrement(\mysqli$db,array$values,string$prefix):void{self::validateAutoIncrement($values,$prefix,null);foreach($values as$row)try{$db->query('ALTER TABLE `'.$row['table'].'` AUTO_INCREMENT='.$row['nextValue']);}catch(\Throwable){throw new RecoveryFailure(70,'RESTORE_FAILED');}}
    private static function validateAutoIncrement(array$values,string$prefix,?array$tables):void{if(array_column($values,'table')!==RuntimeRecoverySchemaV24::autoIncrement($prefix))throw new RecoveryFailure(67,'BUNDLE_INVALID');$last='';foreach($values as$row){if(!is_array($row)||array_keys($row)!==['table','nextValue']||!is_string($row['table'])||!str_starts_with($row['table'],$prefix)||!preg_match('/^[A-Za-z0-9_]{1,64}$/D',$row['table'])||($tables!==null&&!in_array($row['table'],$tables,true))||!is_int($row['nextValue'])||$row['nextValue']<1||strcmp($last,$row['table'])>=0)throw new RecoveryFailure(67,'BUNDLE_INVALID');$last=$row['table'];}}
    private static function fsyncDirectory(string$path):void{$handle=fopen($path,'r');if(!is_resource($handle)||!fsync($handle))throw new RecoveryFailure(70,'BACKUP_FAILED');fclose($handle);}
    private static function import(RuntimeConfiguration$c,string$file):void{self::command(['mariadb','--host='.$c->value('FMONITOR_DB_HOST'),'--port='.$c->value('FMONITOR_DB_PORT'),'--user='.$c->value('FMONITOR_DB_USER'),$c->value('FMONITOR_DB_NAME')],$file,null,'RESTORE_FAILED',['MYSQL_PWD'=>$c->value('FMONITOR_DB_PASSWORD')]);}
    private static function command(array$command,?string$input,?string$output,string$reason,array$extra=[]):void{$descriptors=[0=>$input===null?['file','/dev/null','r']:['file',$input,'r'],1=>$output===null?['pipe','w']:['file',$output,'w'],2=>['pipe','w']];$env=array_replace(getenv(),$extra);$process=proc_open($command,$descriptors,$pipes,null,$env);if(!is_resource($process))throw new RecoveryFailure(70,$reason);if($output===null)stream_get_contents($pipes[1]);$stderr=stream_get_contents($pipes[2]);if($output===null)fclose($pipes[1]);fclose($pipes[2]);if(proc_close($process)!==0)throw new RecoveryFailure(70,$reason);}
    private static function config(array$env):RuntimeConfiguration{try{return RuntimeConfiguration::fromEnvironment($env);}catch(\Throwable){throw new RecoveryFailure(64,'CONFIGURATION_INVALID');}}
    private static function db(RuntimeConfiguration$c):\mysqli{$db=new \mysqli($c->value('FMONITOR_DB_HOST'),$c->value('FMONITOR_DB_USER'),$c->value('FMONITOR_DB_PASSWORD'),$c->value('FMONITOR_DB_NAME'),(int)$c->value('FMONITOR_DB_PORT'));$db->set_charset('utf8mb4');return$db;}
    private static function options(array$args,array$required,array$flags):array{$out=[];for($i=0;$i<count($args);$i++){if(in_array($args[$i],array_map(fn($x)=>'--'.$x,$flags),true)){$key=substr($args[$i],2);if(isset($out[$key]))throw new RecoveryFailure(64,'CONFIGURATION_INVALID');$out[$key]=true;continue;}if(!str_starts_with($args[$i],'--')||!isset($args[$i+1]))throw new RecoveryFailure(64,'CONFIGURATION_INVALID');$key=substr($args[$i],2);if(!in_array($key,$required,true)||isset($out[$key]))throw new RecoveryFailure(64,'CONFIGURATION_INVALID');$out[$key]=$args[++$i];}foreach($required as$key)if(!isset($out[$key])||!is_string($out[$key])||$out[$key]==='')throw new RecoveryFailure(64,'CONFIGURATION_INVALID');return$out;}
    private static function path(string$path,bool$existing=false):string{if($path===''||$path[0]!=='/'||str_contains($path,"\0")||preg_match('#(?:^|/)\.\.(?:/|$)#',$path)||is_link($path))throw new RecoveryFailure(64,'CONFIGURATION_INVALID');if($existing&&!file_exists($path))throw new RecoveryFailure(67,'BUNDLE_INVALID');$repo=realpath(dirname(__DIR__,2));$anchor=realpath($existing?$path:dirname($path));if(!is_string($repo)||!is_string($anchor)||($anchor===$repo||str_starts_with($anchor,$repo.DIRECTORY_SEPARATOR)))throw new RecoveryFailure(64,'CONFIGURATION_INVALID');return$path;}
    private static function relative(string$path):void{if($path===''||$path==='.'||$path[0]==='/'||str_contains($path,'\\')||preg_match('#(?:^|/)\.\.?(?:/|$)#',$path)||preg_match('/[\x00-\x1f\x7f]/',$path))throw new RecoveryFailure(67,'BUNDLE_INVALID');}
    private static function partial(string$destination):string{for($i=0;$i<8;$i++){$path=$destination.'.partial-'.bin2hex(random_bytes(16));if(!file_exists($path)&&!is_link($path))return$path;}throw new RecoveryFailure(70,'BACKUP_FAILED');}
    private static function remove(string$path):void{if(is_link($path)||is_file($path)){unlink($path);return;}foreach(scandir($path)?:[]as$e)if($e!=='.'&&$e!=='..')self::remove($path.'/'.$e);rmdir($path);}
    private static function out(int$exit,string$reason):array{return['exitCode'=>$exit,'result'=>['ok'=>$exit===0,'reason'=>$reason]];}
}
final class RecoveryFailure extends \RuntimeException{public function __construct(public readonly int$exit,public readonly string$reason){parent::__construct($reason);}}
/** Atomic no-clobber directory publication for backup and restored state roots. */
function rename(string$source,string$target):bool{$process=proc_open(['mv','--no-clobber','--no-target-directory',$source,$target],[0=>['file','/dev/null','r'],1=>['file','/dev/null','w'],2=>['file','/dev/null','w']],$pipes);if(!is_resource($process))return false;return proc_close($process)===0&&!file_exists($source)&&is_dir($target);}
