<?php
declare(strict_types=1);
namespace FMonitor2\RuntimeRestore;

/** Exact current-image recovery inventory. The historical v22 contract is separate. */
final class RuntimeRecoverySchemaV23
{
    public const VERSION = 23;
    public const DEFERRED = [];
    public const TABLES = [
        'fm2_assignment_application_attempts',
        'fm2_assignment_order_applications',
        'fm2_assignment_order_id_receipts',
        'fm2_assignment_order_identities',
        'fm2_assignment_order_original_audits',
        'fm2_assignment_order_original_events',
        'fm2_assignment_order_original_maintenance_audits',
        'fm2_assignment_order_original_maintenance_requests',
        'fm2_assignment_order_original_requests',
        'fm2_assignment_order_original_revisions',
        'fm2_assignment_order_original_roots',
        'fm2_assignment_order_selection_audits',
        'fm2_assignment_order_selection_events',
        'fm2_assignment_order_selection_members',
        'fm2_assignment_order_selection_requests',
        'fm2_assignment_order_selections',
        'fm2_assignment_orders',
        'fm2_checklist_operation_installers',
        'fm2_checklist_operations',
        'fm2_checklist_photos',
        'fm2_checklist_revisions',
        'fm2_checklist_template_associations',
        'fm2_checklist_template_snapshots',
        'fm2_installation_cases',
        'fm2_job_events',
        'fm2_jobs',
        'fm2_migrated_evidence_conflicts',
        'fm2_migrated_evidence_decision_state',
        'fm2_migrated_evidence_decisions',
        'fm2_migrated_evidence_projection',
        'fm2_migration_classification_provenance',
        'fm2_migration_quarantine_decisions',
        'fm2_order_artifacts',
        'fm2_order_installers',
        'fm2_otiz_publications',
        'fm2_outbox_attempt_events',
        'fm2_outbox_intents',
        'fm2_pilot_auth_attempts',
        'fm2_pilot_auth_credentials',
        'fm2_pilot_completion_fact_corrections',
        'fm2_pilot_completion_facts',
        'fm2_pilot_inspection_schedule_events',
        'fm2_pilot_inspection_schedules',
        'fm2_pilot_invitations',
        'fm2_pilot_object_detail_quarantine',
        'fm2_pilot_object_details',
        'fm2_pilot_otiz_events',
        'fm2_pilot_otiz_payment_closures',
        'fm2_pilot_otiz_snapshot_allocations',
        'fm2_pilot_otiz_snapshot_evidence',
        'fm2_pilot_otiz_snapshot_issues',
        'fm2_pilot_otiz_snapshot_objects',
        'fm2_pilot_otiz_snapshots',
        'fm2_pilot_role_permissions',
        'fm2_pilot_roles',
        'fm2_pilot_user_role_events',
        'fm2_pilot_user_roles',
        'fm2_pilot_user_status_events',
        'fm2_pilot_users',
        'fm2_process_events',
        'fm2_process_tasks',
        'fm2_process_user_capabilities',
        'fm2_scheduler_slots',
        'fm2_worker_heartbeats',
        'fm2_workforce_catalog',
        'fm2_workforce_observations',
        'fm2_workforce_sync_metadata',
        'fm2_workforce_sync_runs',
        'fm_maintable',
    ];
    public const AUTO_INCREMENT = [
        'fm2_assignment_application_attempts',
        'fm2_assignment_order_applications',
        'fm2_assignment_order_identities',
        'fm2_assignment_order_original_audits',
        'fm2_assignment_order_original_events',
        'fm2_assignment_order_original_maintenance_audits',
        'fm2_assignment_order_selection_audits',
        'fm2_assignment_order_selection_events',
        'fm2_assignment_orders',
        'fm2_checklist_operations',
        'fm2_checklist_photos',
        'fm2_checklist_template_associations',
        'fm2_checklist_template_snapshots',
        'fm2_installation_cases',
        'fm2_job_events',
        'fm2_jobs',
        'fm2_migrated_evidence_decisions',
        'fm2_migration_classification_provenance',
        'fm2_migration_quarantine_decisions',
        'fm2_outbox_attempt_events',
        'fm2_outbox_intents',
        'fm2_pilot_auth_attempts',
        'fm2_pilot_completion_fact_corrections',
        'fm2_pilot_completion_facts',
        'fm2_pilot_inspection_schedule_events',
        'fm2_pilot_inspection_schedules',
        'fm2_pilot_invitations',
        'fm2_pilot_otiz_events',
        'fm2_pilot_otiz_payment_closures',
        'fm2_pilot_otiz_snapshot_allocations',
        'fm2_pilot_otiz_snapshot_issues',
        'fm2_pilot_otiz_snapshots',
        'fm2_pilot_roles',
        'fm2_pilot_user_role_events',
        'fm2_pilot_user_status_events',
        'fm2_pilot_users',
        'fm2_process_events',
        'fm2_process_tasks',
        'fm2_workforce_observations',
    ];

    public static function tables(string $prefix): array
    {
        return array_map(static fn(string $suffix): string => $prefix.$suffix, self::TABLES);
    }

    public static function autoIncrement(string $prefix): array
    {
        return array_map(static fn(string $suffix): string => $prefix.$suffix, self::AUTO_INCREMENT);
    }
}
