pid /tmp/nginx.pid;
error_log /dev/stderr notice;
worker_processes auto;
worker_shutdown_timeout 55s;

events { worker_connections 1024; }

http {
    access_log /dev/stdout;
    client_body_temp_path /tmp/nginx-client-body;
    proxy_temp_path /tmp/nginx-proxy;
    fastcgi_temp_path /tmp/nginx-fastcgi;
    uwsgi_temp_path /tmp/nginx-uwsgi;
    scgi_temp_path /tmp/nginx-scgi;
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    server_tokens off;
    client_max_body_size 28m;

    server {
        listen 8080;
        server_name _;
        root /workspace/fmonitor-2/public;

        location / {
            include /etc/nginx/fastcgi_params;
            fastcgi_param SCRIPT_FILENAME /workspace/fmonitor-2/public/runtime.php;
            fastcgi_param SCRIPT_NAME /runtime.php;
            fastcgi_param DOCUMENT_ROOT /workspace/fmonitor-2/public;
            fastcgi_param HTTP_HOST $http_host;
            fastcgi_read_timeout 60s;
            fastcgi_pass php:9000;
        }

        location ~ \.php(?:/|$) { return 404; }
    }
}
