[global]
daemonize = no
process_control_timeout = 55s
error_log = /proc/self/fd/2
log_level = notice

[www]
user = fmonitor
group = fmonitor
listen = 0.0.0.0:9000
clear_env = no
catch_workers_output = yes
decorate_workers_output = no
pm = dynamic
pm.max_children = 16
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 4
pm.max_requests = 500
request_terminate_timeout = 55s
access.log = /proc/self/fd/2
access.format = "%R %m %r %s %{milli}dms"
php_admin_value[error_log] = /proc/self/fd/2
php_admin_flag[log_errors] = on
