<?php
declare(strict_types=1);

final class MigrationQuarantineRegistry
{
    private bool $schemaReady=false;
    public function __construct(private mysqli$db,private string$prefix){if(preg_match('/^[A-Za-z0-9_]+$/D',$prefix)!==1)throw new InvalidArgumentException('Invalid local prefix');}
    public function record(array$classification,string$locator,string$cutoff,string$sourceDigest,string$runId,string$observedAt):array
    {
        $cutoffDate=DateTimeImmutable::createFromFormat('!Y-m-d H:i:s',$cutoff,new DateTimeZone('UTC'));$observedDate=DateTimeImmutable::createFromFormat('!Y-m-d\TH:i:sP',$observedAt);if(($classification['quarantineCodes']??[])===[]||preg_match('/^hmac-sha256:[a-f0-9]{64}$/D',$locator)!==1||preg_match('/^[a-f0-9]{64}$/D',$sourceDigest)!==1||preg_match('/^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/D',$runId)!==1||!$cutoffDate||$cutoffDate->format('Y-m-d H:i:s')!==$cutoff||!$observedDate||$observedDate->format('Y-m-d\TH:i:sP')!==$observedAt)throw new DomainException('QUARANTINE_RECORD_NOT_ALLOWED');$p=$this->prefix;
        if(!$this->schemaReady){$this->db->query("CREATE TABLE IF NOT EXISTS `{$p}fm2_migration_quarantine_registry`(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,source_system VARCHAR(40) NOT NULL,source_locator VARCHAR(80) NOT NULL,source_cutoff_at DATETIME NOT NULL,source_digest CHAR(64) NOT NULL,classification_version VARCHAR(80) NOT NULL,category VARCHAR(40) NOT NULL,reason_codes_json TEXT NOT NULL,quarantine_codes_json TEXT NOT NULL,first_seen_at VARCHAR(40) NOT NULL,UNIQUE KEY uq_digest(source_digest),UNIQUE KEY uq_locator_cutoff(source_locator,source_cutoff_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");$this->db->query("CREATE TABLE IF NOT EXISTS `{$p}fm2_migration_quarantine_observations`(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,registry_id BIGINT UNSIGNED NOT NULL,run_id CHAR(36) NOT NULL,observed_at VARCHAR(40) NOT NULL,UNIQUE KEY uq_registry_run(registry_id,run_id),KEY run_id(run_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");$this->schemaReady=true;}
        $version=(string)$classification['classificationVersion'];$category=(string)$classification['category'];$reasons=json_encode($classification['reasonCodes'],JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR);$quarantine=json_encode($classification['quarantineCodes'],JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR);$system='legacy_fmonitor';$this->db->begin_transaction();try{$s=$this->db->prepare("INSERT IGNORE INTO `{$p}fm2_migration_quarantine_registry`(source_system,source_locator,source_cutoff_at,source_digest,classification_version,category,reason_codes_json,quarantine_codes_json,first_seen_at)VALUES(?,?,?,?,?,?,?,?,?)");$s->bind_param('sssssssss',$system,$locator,$cutoff,$sourceDigest,$version,$category,$reasons,$quarantine,$observedAt);$s->execute();$created=$s->affected_rows===1;$s=$this->db->prepare("SELECT id,source_digest,classification_version,category,reason_codes_json,quarantine_codes_json FROM `{$p}fm2_migration_quarantine_registry` WHERE source_locator=? AND source_cutoff_at=?");$s->bind_param('ss',$locator,$cutoff);$s->execute();$row=$s->get_result()->fetch_assoc();if(!is_array($row)||!hash_equals($sourceDigest,(string)$row['source_digest'])||$row['classification_version']!==$version||$row['category']!==$category||$row['reason_codes_json']!==$reasons||$row['quarantine_codes_json']!==$quarantine)throw new DomainException('QUARANTINE_REGISTRY_CONFLICT');$registryId=(int)$row['id'];$s=$this->db->prepare("INSERT IGNORE INTO `{$p}fm2_migration_quarantine_observations`(registry_id,run_id,observed_at)VALUES(?,?,?)");$s->bind_param('iss',$registryId,$runId,$observedAt);$s->execute();$observationCreated=$s->affected_rows===1;$s=$this->db->prepare("SELECT observed_at FROM `{$p}fm2_migration_quarantine_observations` WHERE registry_id=? AND run_id=?");$s->bind_param('is',$registryId,$runId);$s->execute();$observation=$s->get_result()->fetch_assoc();if(!is_array($observation)||$observation['observed_at']!==$observedAt)throw new DomainException('QUARANTINE_OBSERVATION_CONFLICT');$this->db->commit();return['registryCreated'=>$created,'observationCreated'=>$observationCreated];}catch(Throwable$e){$this->db->rollback();throw$e;}
    }
}
