<?php
declare(strict_types=1);
require_once __DIR__.'/MigratedEvidenceReconciliation.php';
final class MigratedEvidenceProjectionStore
{
 private ?array $workforce=null;
 public const VERSION='migrated-evidence-projection-v1';
 public function __construct(private mysqli$db,private string$p){if(preg_match('/^[A-Za-z0-9_]+$/D',$p)!==1)throw new InvalidArgumentException('Invalid local table prefix');}
 public function ensureSchema():void{$p=$this->p;$this->db->query("CREATE TABLE IF NOT EXISTS `{$p}fm2_migrated_evidence_projection`(snapshot_id BIGINT UNSIGNED NOT NULL,legacy_object_id BIGINT UNSIGNED NOT NULL,projection_version VARCHAR(80) NOT NULL,input_sha256 CHAR(64) NOT NULL,projection_sha256 CHAR(64) NOT NULL,classification VARCHAR(40) NOT NULL,evidence_grade CHAR(1) NOT NULL,confidence VARCHAR(20) NOT NULL,quarantine_count INT UNSIGNED NOT NULL,conflict_codes_json JSON NOT NULL,conflict_search VARCHAR(2000) NOT NULL,payload_json LONGTEXT NOT NULL,projected_at DATETIME NOT NULL,PRIMARY KEY(snapshot_id,legacy_object_id),KEY ix_filter(classification,evidence_grade,quarantine_count,legacy_object_id),KEY ix_object(legacy_object_id,snapshot_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");}
 public function persist(int$id,string$at):array{$s=$this->db->prepare("SELECT * FROM `{$this->p}fm2_history_source_snapshots` WHERE id=?");$s->bind_param('i',$id);$s->execute();$snapshot=$s->get_result()->fetch_assoc();if(!is_array($snapshot))throw new DomainException('Migrated snapshot unavailable');$q=$this->db->prepare("SELECT code,diagnostic_json FROM `{$this->p}fm2_history_import_quarantine` WHERE snapshot_id=? ORDER BY issue_no");$q->bind_param('i',$id);$q->execute();$issues=$q->get_result()->fetch_all(MYSQLI_ASSOC);$workforce=$this->workforce??[];$table=$this->db->real_escape_string($this->p.'fm2_workforce_catalog');if($this->workforce===null && (int)$this->db->query("SELECT COUNT(*) n FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='{$table}'")->fetch_assoc()['n']>0)foreach($this->db->query("SELECT installer_tab_id,fio,position,employment_status,workforce_source,workforce_source_updated_at,reconciliation_state,authority_system FROM `{$this->p}fm2_workforce_catalog`")->fetch_all(MYSQLI_ASSOC)as$w)$workforce[(string)$w['installer_tab_id']]=$w;$this->workforce=$workforce;$x=MigratedEvidenceReconciliation::project($snapshot,$issues,$workforce);$json=json_encode($x,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR);$codes=json_encode($x['conflictCodes'],JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR);$search='|'.implode('|',$x['conflictCodes']).'|';$s=$this->db->prepare("INSERT INTO `{$this->p}fm2_migrated_evidence_projection` VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE input_sha256=VALUES(input_sha256),projection_sha256=VALUES(projection_sha256),classification=VALUES(classification),evidence_grade=VALUES(evidence_grade),confidence=VALUES(confidence),quarantine_count=VALUES(quarantine_count),conflict_codes_json=VALUES(conflict_codes_json),conflict_search=VALUES(conflict_search),payload_json=VALUES(payload_json),projected_at=IF(projection_sha256=VALUES(projection_sha256),projected_at,VALUES(projected_at))");$v=self::VERSION;$object=(int)$x['legacyObjectId'];$hash=$x['contentSha256'];$ph=$x['projectionHash'];$class=$x['classification'];$grade=$x['evidenceGrade'];$confidence=$x['confidence'];$count=$x['quarantineCount'];$s->bind_param('iissssssissss',$id,$object,$v,$hash,$ph,$class,$grade,$confidence,$count,$codes,$search,$json,$at);$s->execute();return$x;}
 public function backfill(string$at):array{$this->ensureSchema();$ids=$this->db->query("SELECT s.id FROM `{$this->p}fm2_history_source_snapshots` s WHERE NOT EXISTS(SELECT 1 FROM `{$this->p}fm2_history_source_snapshots` n WHERE n.legacy_object_id=s.legacy_object_id AND n.id>s.id) ORDER BY s.id")->fetch_all(MYSQLI_ASSOC);$created=0;$present=0;foreach($ids as$r){$before=(int)$this->db->query("SELECT COUNT(*) n FROM `{$this->p}fm2_migrated_evidence_projection` WHERE snapshot_id=".(int)$r['id'])->fetch_assoc()['n'];$this->persist((int)$r['id'],$at);$before?$present++:$created++;}return['scanned'=>count($ids),'created'=>$created,'alreadyPresent'=>$present];}
 public function single(int$id):array{$s=$this->db->prepare("SELECT payload_json FROM `{$this->p}fm2_migrated_evidence_projection` WHERE snapshot_id=?");$s->bind_param('i',$id);$s->execute();$r=$s->get_result()->fetch_assoc();if(!is_array($r))throw new DomainException('Migrated evidence projection is stale or unavailable.');return json_decode($r['payload_json'],true,flags:JSON_THROW_ON_ERROR);}
 public function page(array$f,int$page,int$size=50):array{$where=['1=1'];foreach(['classification'=>'classification','grade'=>'evidence_grade']as$k=>$column)if(($f[$k]??'')!=='')$where[]=$column."='".$this->db->real_escape_string($f[$k])."'";if(($f['quarantine']??'')==='yes')$where[]='quarantine_count>0';elseif(($f['quarantine']??'')==='no')$where[]='quarantine_count=0';if(($f['conflict']??'')!=='')$where[]="conflict_search LIKE '%|".$this->db->real_escape_string($f['conflict'])."|%'";$sql=implode(' AND ',$where);$total=(int)$this->db->query("SELECT COUNT(*) n FROM `{$this->p}fm2_migrated_evidence_projection` WHERE {$sql}")->fetch_assoc()['n'];$offset=max(0,($page-1)*$size);$rows=$this->db->query("SELECT payload_json FROM `{$this->p}fm2_migrated_evidence_projection` WHERE {$sql} ORDER BY legacy_object_id LIMIT {$size} OFFSET {$offset}")->fetch_all(MYSQLI_ASSOC);return['total'=>$total,'rows'=>array_map(fn($r)=>json_decode($r['payload_json'],true,flags:JSON_THROW_ON_ERROR),$rows)];}
}
