<?php
declare(strict_types=1);

final class WorkforceCatalogReconciliationCandidate
{
    public static function evaluate(array$legacyMatches,array$bitrixMatches,array$localRows,string$targetLocatorHash,string$profileKey):array
    {
        if(strlen($profileKey)<32||preg_match('/^[a-f0-9]{64}$/D',$targetLocatorHash)!==1)throw new InvalidArgumentException('Invalid workforce reconciliation request');
        $safe=count($legacyMatches)===1&&count($bitrixMatches)===1&&count($localRows)===0;$legacy=$legacyMatches[0]??[];$bitrix=$bitrixMatches[0]??[];$tab=(int)($legacy['tab_id']??0);$legacyName=self::name($legacy['fio']??null);$bitrixName=self::name($bitrix['fio']??null);$hashMatches=$tab>0&&hash_equals($targetLocatorHash,hash_hmac('sha256','workforce_tab:'.$tab,$profileKey));$safe=$safe&&$hashMatches&&$legacyName!==null&&$legacyName===$bitrixName&&($legacy['status']??null)===($bitrix['status']??null)&&in_array($legacy['status']??null,['employed','dismissed'],true)&&filter_var($bitrix['personId']??null,FILTER_VALIDATE_INT,['options'=>['min_range'=>1]])!==false&&self::nonblank($bitrix['position']??null);
        $reason=$safe?'UNIQUE_LEGACY_AND_CURRENT_BITRIX_MATCH':(count($localRows)>0?'LOCAL_CATALOG_ALREADY_PRESENT':'CANDIDATE_NOT_INDEPENDENTLY_CONFIRMED');return['eligible'=>$safe,'reasonCode'=>$reason,'candidateHash'=>hash('sha256',json_encode(['target'=>$targetLocatorHash,'legacyUpdatedAt'=>$legacy['updatedAt']??null,'bitrixModifiedAt'=>$bitrix['modifiedAt']??null,'status'=>$legacy['status']??null],JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR)),'identifiersExposed'=>false,'candidate'=>$safe?['tab'=>$tab,'fio'=>(string)$legacy['fio'],'position'=>(string)$bitrix['position'],'status'=>(string)$legacy['status'],'personId'=>(int)$bitrix['personId'],'legacyUpdatedAt'=>(string)$legacy['updatedAt'],'bitrixModifiedAt'=>$bitrix['modifiedAt']]:null];
    }

    public static function apply(mysqli$db,string$prefix,array$evaluation,string$operationId,string$observedAt):array
    {
        if(preg_match('/^[A-Za-z0-9_]+$/D',$prefix)!==1||preg_match('/^[a-f0-9-]{36}$/D',$operationId)!==1||!($evaluation['eligible']??false)||!is_array($evaluation['candidate']??null))throw new DomainException('WORKFORCE_RECONCILIATION_APPLY_NOT_ALLOWED');$c=$evaluation['candidate'];$db->begin_transaction();try{$existing=$db->query("SELECT fio,position,employment_status,authority_system,reconciliation_state FROM `{$prefix}fm2_workforce_catalog` WHERE installer_tab_id=".(int)$c['tab']." FOR UPDATE")->fetch_assoc();if(is_array($existing)){if($existing['fio']!==$c['fio']||$existing['position']!==$c['position']||$existing['employment_status']!==$c['status']||$existing['authority_system']!=='one_c_zup'||$existing['reconciliation_state']!=='delivered')throw new DomainException('WORKFORCE_RECONCILIATION_CONFLICT');$db->commit();return['status'=>'duplicate','candidateHash'=>$evaluation['candidateHash']];}
            $checksum=$evaluation['candidateHash'];$started=$db->prepare("INSERT INTO `{$prefix}fm2_workforce_sync_runs`(run_id,status,started_at,observed_at,completed_at,page_count,delivered_count,material_change_count,missing_count,normalized_checksum)VALUES(?,'completed',?,?,?,1,1,1,0,?)");$started->bind_param('sssss',$operationId,$observedAt,$observedAt,$observedAt,$checksum);$started->execute();$modified=is_string($c['bitrixModifiedAt'])?$c['bitrixModifiedAt']:null;$reconciliation='delivered';$dismissal='observed_only';$ob=$db->prepare("INSERT INTO `{$prefix}fm2_workforce_observations`(sync_run_id,delivery_person_id,employee_number,full_name,position,employment_status,employed_from,dismissal_effective_at,authority_system,delivery_system,source_modified_at,reconciliation_state,observed_at,dismissal_time_quality)VALUES(?,?,?,?,?,?,NULL,NULL,'one_c_zup','bitrix24',?,?,?,?)");$ob->bind_param('siisssssss',$operationId,$c['personId'],$c['tab'],$c['fio'],$c['position'],$c['status'],$modified,$reconciliation,$observedAt,$dismissal);$ob->execute();$firstDismissed=$c['status']==='dismissed'?$observedAt:null;$catalog=$db->prepare("INSERT INTO `{$prefix}fm2_workforce_catalog`(installer_tab_id,fio,position,employment_status,employed_from,employed_to,workforce_source,workforce_source_updated_at,delivery_system,delivery_person_id,dismissal_effective_at,first_observed_dismissed_at,dismissal_time_quality,reconciliation_state,authority_system,last_successful_sync_run_id,last_successful_sync_at)VALUES(?,?,?,?,NULL,NULL,'one_c_zup_via_bitrix_reconciled',?,'bitrix24',?,NULL,?,'observed_only','delivered','one_c_zup',?,?)");$catalog->bind_param('issssisss',$c['tab'],$c['fio'],$c['position'],$c['status'],$observedAt,$c['personId'],$firstDismissed,$operationId,$observedAt);$catalog->execute();$db->commit();return['status'=>'applied','candidateHash'=>$evaluation['candidateHash']];}catch(Throwable$e){$db->rollback();throw$e;}
    }
    private static function name(mixed$v):?string{if(!is_string($v))return null;$n=preg_replace('/\s+/u',' ',mb_strtolower(trim($v)));return is_string($n)&&$n!==''?$n:null;}
    private static function nonblank(mixed$v):bool{return is_string($v)&&trim($v)!=='';}
}
