<?php
declare(strict_types=1);
namespace FMonitor2\Workforce;
use FMonitor2\InstallationProcess\YiiObjectCardApplicationIntegrity;
use yii\db\Connection;use yii\db\Expression;use yii\db\Query;
final class MariaDbYiiInstallerDirectory
{
 private const PAGE_SIZE=50;
 public function __construct(private readonly Connection$db,private readonly string$processPrefix,private readonly string$legacyPrefix){foreach([$processPrefix,$legacyPrefix]as$prefix)if(strlen($prefix)>32||preg_match('/^[A-Za-z0-9_]*$/D',$prefix)!==1)throw new \RuntimeException('Directory configuration unavailable.');}
 public function read(string$today,array$filters):array
 {
  if(!$this->validDate($today))throw new \RuntimeException('Directory clock unavailable.');$catalog=$this->processPrefix.'fm2_workforce_catalog';$orders=$this->processPrefix.'fm2_assignment_orders';$members=$this->processPrefix.'fm2_order_installers';$applications=$this->processPrefix.'fm2_assignment_order_applications';$cases=$this->processPrefix.'fm2_installation_cases';$objects=$this->legacyPrefix.'fm_maintable';
  $latest=(new Query())->addSelect(['installation_case_id','version_no'=>new Expression('MAX([[version_no]])')])->from($orders)->groupBy('installation_case_id');
  $latestApplications=(new Query())->addSelect(['installation_case_id','application_sequence'=>new Expression('MAX([[application_sequence]])')])->from($applications)->groupBy('installation_case_id');
  $native=(new Query())->addSelect(['source'=>new Expression("'native'"),'installer_tab_id'=>new Expression('NULL'),'selected_snapshot_json'=>'aa.selected_snapshot_json','application_sequence'=>'aa.application_sequence','application_object_id'=>'aa.object_id','installation_case_id'=>'aa.installation_case_id','assignment_order_id'=>'aa.assignment_order_id','order_version'=>'aa.order_version','composition_identity'=>'aa.composition_identity','composition_sha256'=>'aa.composition_sha256','control_engineer_user_id'=>'aa.control_engineer_user_id','object_id'=>'c.legacy_installation_object_id','registration_number'=>'o.regnumber','address'=>'o.ordadr_address','valid_from'=>'aa.document_date'])->from(['aa'=>$applications])->innerJoin(['current_application'=>$latestApplications],'current_application.installation_case_id=aa.installation_case_id AND current_application.application_sequence=aa.application_sequence')->innerJoin(['c'=>$cases],'c.id=aa.installation_case_id')->innerJoin(['o'=>$objects],'o.id=c.legacy_installation_object_id');
  $legacy=(new Query())->addSelect(['source'=>new Expression("'legacy'"),'installer_tab_id'=>'oi.installer_tab_id','selected_snapshot_json'=>new Expression('NULL'),'application_sequence'=>new Expression('NULL'),'application_object_id'=>new Expression('NULL'),'object_id'=>'c.legacy_installation_object_id','registration_number'=>new Expression("CONCAT([[ao.registration_number]], ' · ', [[o.regnumber]])"),'address'=>'o.ordadr_address','valid_from'=>'oi.valid_from'])->from(['oi'=>$members])->innerJoin(['ao'=>$orders],'ao.id=oi.assignment_order_id')->innerJoin(['latest'=>$latest],'latest.installation_case_id=ao.installation_case_id AND latest.version_no=ao.version_no')->innerJoin(['c'=>$cases],'c.id=ao.installation_case_id')->innerJoin(['o'=>$objects],'o.id=c.legacy_installation_object_id')->where(['ao.status'=>'registered'])->andWhere(['<>','oi.change_action','release'])->andWhere(['<=','oi.valid_from',$today])->andWhere(['or',['oi.valid_to'=>null],['>=','oi.valid_to',$today]])->andWhere(['not exists',(new Query())->from(['any_application'=>$applications])->where(new Expression('[[any_application.installation_case_id]]=[[ao.installation_case_id]]'))]);
  $projectionRows=array_merge($native->all($this->db),$legacy->all($this->db));$allAssignments=[];$activeIds=[];foreach($projectionRows as$projection){if($projection['source']==='native'){$this->validateNativeApplication($projection);$snapshot=json_decode((string)$projection['selected_snapshot_json'],true,512,JSON_THROW_ON_ERROR);foreach($snapshot['selectedInstallers']as$installer){$tabId=(int)$installer['tabId'];$assignment=['installer_tab_id'=>$tabId,'registration_number'=>$projection['registration_number'],'object_id'=>$projection['object_id'],'address'=>$projection['address'],'valid_from'=>$projection['valid_from']];$this->validateAssignment($assignment);$allAssignments[$tabId][(int)$projection['object_id']]=$assignment;$activeIds[$tabId]=true;}}else{$this->validateAssignment($projection);$tabId=(int)$projection['installer_tab_id'];$allAssignments[$tabId][(int)$projection['object_id']]=$projection;$activeIds[$tabId]=true;}}
  $activeTabIds=array_keys($activeIds);sort($activeTabIds,SORT_NUMERIC);$assignedExpression=$activeTabIds===[]?new Expression('0'):new Expression('SUM(CASE WHEN [[w.installer_tab_id]] IN ('.implode(',',$activeTabIds).') THEN 1 ELSE 0 END)');
  $summary=(new Query())->addSelect(['total'=>new Expression('COUNT(*)'),'working'=>new Expression("SUM([[w.employment_status]]='employed')"),'updated_at'=>new Expression('MAX([[w.workforce_source_updated_at]])'),'assigned'=>$assignedExpression])->from(['w'=>$catalog])->where(['w.reconciliation_state'=>'delivered'])->one($this->db);if(!is_array($summary))throw new \RuntimeException('Directory read unavailable.');
  $condition=['and',['w.reconciliation_state'=>'delivered']];if($filters['status']!=='')$condition[]=['w.employment_status'=>$filters['status']];if($filters['availability']!=='')$condition[]=$activeTabIds===[]?new Expression($filters['availability']==='assigned'?'0=1':'1=1'):[$filters['availability']==='assigned'?'in':'not in','w.installer_tab_id',$activeTabIds];if($filters['q']!==''){$search=['or',['like','w.fio',$filters['q']]];if($filters['tab']!=='')$search[]=['like',new Expression('CAST([[w.installer_tab_id]] AS CHAR)'),$filters['tab']];$condition[]=$search;}
  $total=(int)(new Query())->from(['w'=>$catalog])->where($condition)->count('*',$this->db);$pages=max(1,(int)ceil($total/self::PAGE_SIZE));if($filters['page']>$pages)throw new \OutOfRangeException('Directory page unavailable.');
  $rows=(new Query())->addSelect(['w.installer_tab_id','w.fio','w.position','w.employment_status','w.dismissal_effective_at','w.workforce_source','w.workforce_source_updated_at'])->from(['w'=>$catalog])->where($condition)->orderBy(['w.fio'=>SORT_ASC,'w.installer_tab_id'=>SORT_ASC])->limit(self::PAGE_SIZE)->offset(($filters['page']-1)*self::PAGE_SIZE)->all($this->db);
  foreach($rows as&$row){$this->validateInstaller($row);$assignments=array_values($allAssignments[(int)$row['installer_tab_id']]??[]);usort($assignments,static fn(array$a,array$b):int=>[(int)$a['object_id'],(string)$a['valid_from']]<=>[(int)$b['object_id'],(string)$b['valid_from']]);$row['assignments']=$assignments;}unset($row);$totalCatalog=(int)($summary['total']??0);$working=(int)($summary['working']??0);return['summary'=>['total'=>$totalCatalog,'working'=>$working,'dismissed'=>$totalCatalog-$working,'assigned'=>(int)($summary['assigned']??0),'updatedAt'=>$summary['updated_at']],'rows'=>$rows,'filters'=>$filters+['total'=>$total,'pages'=>$pages]];
 }
 private function validateInstaller(array$row):void{if((int)($row['installer_tab_id']??0)<1||trim((string)($row['fio']??''))===''||trim((string)($row['position']??''))===''||!in_array($row['employment_status']??null,['employed','dismissed'],true)||!$this->validTimestamp((string)($row['workforce_source_updated_at']??''))||(($row['dismissal_effective_at']??null)!==null&&!$this->validDate((string)$row['dismissal_effective_at'])))throw new \RuntimeException('Directory row unavailable.');}
 private function validateAssignment(array$row):void{if((int)($row['installer_tab_id']??0)<1||(int)($row['object_id']??0)<1||trim((string)($row['registration_number']??''))===''||trim((string)($row['address']??''))===''||!$this->validDate((string)($row['valid_from']??'')))throw new \RuntimeException('Directory assignment unavailable.');}
 private function validateNativeApplication(array$row):void{try{$snapshot=json_decode((string)($row['selected_snapshot_json']??''),true,512,JSON_THROW_ON_ERROR);}catch(\Throwable){throw new \RuntimeException('Directory assignment unavailable.');}if((int)($row['application_sequence']??0)<1||(int)($row['application_object_id']??0)!==(int)($row['object_id']??0)||!is_array($snapshot)||array_keys($snapshot)!==['selectedInstallers','selectedEngineer'])throw new \RuntimeException('Directory assignment unavailable.');try{YiiObjectCardApplicationIntegrity::validateComposition(array_replace($row,['object_id'=>$row['application_object_id']]),$snapshot);}catch(\Throwable){throw new \RuntimeException('Directory assignment unavailable.');}}
 private function validTimestamp(string$value):bool{try{new \DateTimeImmutable($value);return$value!=='';}catch(\Throwable){return false;}}
 private function validDate(string$value):bool{$date=\DateTimeImmutable::createFromFormat('!Y-m-d',$value,new \DateTimeZone('Europe/Moscow'));return$date!==false&&$date->format('Y-m-d')===$value;}
}
