<?php
declare(strict_types=1);
namespace FMonitor2\Workforce;
use yii\db\Connection;use yii\db\Expression;use yii\db\Query;
final class MariaDbYiiInstallerDirectory
{
 private const PAGE_SIZE=50;
 public function __construct(private readonly Connection$db,private readonly string$processPrefix,private readonly string$legacyPrefix){foreach([$processPrefix,$legacyPrefix]as$prefix)if(strlen($prefix)>32||preg_match('/^[A-Za-z0-9_]*$/D',$prefix)!==1)throw new \RuntimeException('Directory configuration unavailable.');}
 public function read(string$today,array$filters):array
 {
  if(!$this->validDate($today))throw new \RuntimeException('Directory clock unavailable.');$catalog=$this->processPrefix.'fm2_workforce_catalog';$orders=$this->processPrefix.'fm2_assignment_orders';$members=$this->processPrefix.'fm2_order_installers';$cases=$this->processPrefix.'fm2_installation_cases';$objects=$this->legacyPrefix.'fm_maintable';
  $latest=(new Query())->addSelect(['installation_case_id','version_no'=>new Expression('MAX([[version_no]])')])->from($orders)->groupBy('installation_case_id');
  $active=(new Query())->addSelect(['installer_tab_id'=>'oi.installer_tab_id'])->distinct()->from(['oi'=>$members])->innerJoin(['ao'=>$orders],'ao.id=oi.assignment_order_id')->innerJoin(['latest'=>$latest],'latest.installation_case_id=ao.installation_case_id AND latest.version_no=ao.version_no')->where(['ao.status'=>'registered'])->andWhere(['<>','oi.change_action','release'])->andWhere(['<=','oi.valid_from',$today])->andWhere(['or',['oi.valid_to'=>null],['>=','oi.valid_to',$today]]);
  $summary=(new Query())->addSelect(['total'=>new Expression('COUNT(*)'),'working'=>new Expression("SUM([[w.employment_status]]='employed')"),'updated_at'=>new Expression('MAX([[w.workforce_source_updated_at]])'),'assigned'=>new Expression('COUNT([[a.installer_tab_id]])')])->from(['w'=>$catalog])->leftJoin(['a'=>$active],'a.installer_tab_id=w.installer_tab_id')->where(['w.reconciliation_state'=>'delivered'])->one($this->db);if(!is_array($summary))throw new \RuntimeException('Directory read unavailable.');
  $condition=['and',['w.reconciliation_state'=>'delivered']];if($filters['status']!=='')$condition[]=['w.employment_status'=>$filters['status']];if($filters['availability']!==''){$correlated=(clone$active)->andWhere(new Expression('[[oi.installer_tab_id]]=[[w.installer_tab_id]]'));$condition[]=[$filters['availability']==='assigned'?'exists':'not exists',$correlated];}if($filters['q']!==''){$search=['or',['like','w.fio',$filters['q']]];if($filters['tab']!=='')$search[]=['like',new Expression('CAST([[w.installer_tab_id]] AS CHAR)'),$filters['tab']];$condition[]=$search;}
  $total=(int)(new Query())->from(['w'=>$catalog])->where($condition)->count('*',$this->db);$pages=max(1,(int)ceil($total/self::PAGE_SIZE));if($filters['page']>$pages)throw new \OutOfRangeException('Directory page unavailable.');
  $rows=(new Query())->addSelect(['w.installer_tab_id','w.fio','w.position','w.employment_status','w.dismissal_effective_at','w.workforce_source','w.workforce_source_updated_at'])->from(['w'=>$catalog])->where($condition)->orderBy(['w.fio'=>SORT_ASC,'w.installer_tab_id'=>SORT_ASC])->limit(self::PAGE_SIZE)->offset(($filters['page']-1)*self::PAGE_SIZE)->all($this->db);$ids=array_map(static fn(array$row):int=>(int)$row['installer_tab_id'],$rows);$assignments=[];
  if($ids!==[]){$assignmentRows=(new Query())->addSelect(['oi.installer_tab_id','ao.registration_number','object_id'=>'c.legacy_installation_object_id','address'=>'o.ordadr_address','oi.valid_from'])->from(['oi'=>$members])->innerJoin(['ao'=>$orders],'ao.id=oi.assignment_order_id')->innerJoin(['latest'=>$latest],'latest.installation_case_id=ao.installation_case_id AND latest.version_no=ao.version_no')->innerJoin(['c'=>$cases],'c.id=ao.installation_case_id')->innerJoin(['o'=>$objects],'o.id=c.legacy_installation_object_id')->where(['oi.installer_tab_id'=>$ids,'ao.status'=>'registered'])->andWhere(['<>','oi.change_action','release'])->andWhere(['<=','oi.valid_from',$today])->andWhere(['or',['oi.valid_to'=>null],['>=','oi.valid_to',$today]])->orderBy(['oi.installer_tab_id'=>SORT_ASC,'oi.valid_from'=>SORT_ASC,'c.legacy_installation_object_id'=>SORT_ASC])->all($this->db);foreach($assignmentRows as$assignment){$this->validateAssignment($assignment);$assignments[(int)$assignment['installer_tab_id']][]=$assignment;}}
  foreach($rows as&$row){$this->validateInstaller($row);$row['assignments']=$assignments[(int)$row['installer_tab_id']]??[];}unset($row);$totalCatalog=(int)($summary['total']??0);$working=(int)($summary['working']??0);return['summary'=>['total'=>$totalCatalog,'working'=>$working,'dismissed'=>$totalCatalog-$working,'assigned'=>(int)($summary['assigned']??0),'updatedAt'=>$summary['updated_at']],'rows'=>$rows,'filters'=>$filters+['total'=>$total,'pages'=>$pages]];
 }
 private function validateInstaller(array$row):void{if((int)($row['installer_tab_id']??0)<1||trim((string)($row['fio']??''))===''||trim((string)($row['position']??''))===''||!in_array($row['employment_status']??null,['employed','dismissed'],true)||!$this->validTimestamp((string)($row['workforce_source_updated_at']??''))||(($row['dismissal_effective_at']??null)!==null&&!$this->validDate((string)$row['dismissal_effective_at'])))throw new \RuntimeException('Directory row unavailable.');}
 private function validateAssignment(array$row):void{if((int)($row['installer_tab_id']??0)<1||(int)($row['object_id']??0)<1||trim((string)($row['registration_number']??''))===''||trim((string)($row['address']??''))===''||!$this->validDate((string)($row['valid_from']??'')))throw new \RuntimeException('Directory assignment unavailable.');}
 private function validTimestamp(string$value):bool{try{new \DateTimeImmutable($value);return$value!=='';}catch(\Throwable){return false;}}
 private function validDate(string$value):bool{$date=\DateTimeImmutable::createFromFormat('!Y-m-d',$value,new \DateTimeZone('Europe/Moscow'));return$date!==false&&$date->format('Y-m-d')===$value;}
}
