<?php
declare(strict_types=1);
namespace FMonitor2\YiiRuntime;
final class OtizEvidenceHtml
{
 public static function reconciliation(array$m,array$f,string$csrf):string
 {
  $e=self::e(...);$body=self::notice('/pilot/otiz/reconciliation').'<h1>Сверка перенесённых свидетельств</h1>'.self::nav();
  $body.='<form method="get" action="/pilot/otiz/reconciliation"><label>Классификация <input name="classification" value="'.$e($f['classification']).'"></label><label>Статус <input name="state" value="'.$e($f['state']).'"></label><label>Quarantine <input name="quarantine" value="'.$e($f['quarantine']).'"></label><label>Конфликт <input name="conflict" value="'.$e($f['conflict']).'"></label><button>Применить</button></form>';
  foreach($m['rows']as$row){$id=(int)($row['snapshotId']??0);$history=$m['decisions'][$id]??[];$body.='<article id="snapshot-'.$id.'"><h2>Объект '.(int)($row['legacyObjectId']??0).'</h2><p>Provenance: '.$e((string)($row['sourceLabel']??'')).' · '.$e((string)($row['sourceLocator']??'')).'</p><code>'.$e((string)($row['contentSha256']??'')).'</code>';
   foreach($row['conflictCodes']??[]as$code){$body.='<section><h3>'.$e((string)$code).'</h3><form method="post" action="/pilot/otiz/reconciliation/decisions"><input type="hidden" name="_csrf" value="'.$e($csrf).'"><input type="hidden" name="operationId" value="'.self::uuid().'"><input type="hidden" name="snapshotId" value="'.$id.'"><input type="hidden" name="snapshotSha256" value="'.$e((string)($row['contentSha256']??'')).'"><input type="hidden" name="projectionSha256" value="'.$e((string)($row['projectionHash']??'')).'"><input type="hidden" name="sourceLocator" value="'.$e((string)($row['sourceLocator']??'')).'"><input type="hidden" name="issueCode" value="'.$e((string)$code).'"><select name="outcome"><option value="acknowledge">Ознакомлены</option><option value="reject_evidence">Отклонить</option><option value="request_source_correction">Запросить исправление</option><option value="map_link">Сопоставить</option></select><input name="targetLocator" placeholder="operational_case:1"><textarea name="reason" required></textarea><button>Записать решение</button></form></section>';}
   if($history!==[]){$body.='<h3>История решений</h3><ul>';foreach($history as$d)$body.='<li>'.$e((string)$d['outcome']).' · '.$e((string)$d['reason']).' · '.$e((string)$d['occurred_at']).'</li>';$body.='</ul>';}$body.='</article>';
  }
  if($m['rows']===[])$body.='<p>По выбранным фильтрам ничего нет</p>';return self::page('Сверка свидетельств',$body.self::pager('/pilot/otiz/reconciliation',$m,$f));
 }
 public static function quarantine(array$m,array$history,string$csrf):string
 {
  $e=self::e(...);$f=$m['filters']??['category'=>'','code'=>''];$body=self::notice('/pilot/otiz/reconciliation/quarantine').'<h1>Pre-import quarantine</h1>'.self::nav().'<form method="get" action="/pilot/otiz/reconciliation/quarantine"><input name="category" value="'.$e($f['category']).'"><input name="code" value="'.$e($f['code']).'"><button>Применить</button></form>';
  foreach($m['rows']as$row){$body.='<article><h2>'.$e($row['reference']).'</h2><p>Provenance: '.$e($row['sourceLocator']).' · '.$e($row['sourceDigest']).'</p>';foreach($row['quarantineCodes']as$code){$key=$row['sourceLocator'].'|'.$row['sourceCutoffAt'].'|'.$row['sourceDigest'].'|'.$row['classificationVersion'].'|'.$code;$body.='<form method="post" action="/pilot/otiz/reconciliation/quarantine/decisions"><input type="hidden" name="_csrf" value="'.$e($csrf).'"><input type="hidden" name="operationId" value="'.self::uuid().'">';foreach(['sourceLocator','sourceCutoffAt','sourceDigest','classificationVersion']as$n)$body.='<input type="hidden" name="'.$n.'" value="'.$e($row[$n]).'">';$body.='<input type="hidden" name="quarantineCode" value="'.$e($code).'"><select name="outcome"><option value="acknowledge">Ознакомлены</option><option value="reject_source_evidence">Отклонить источник</option><option value="request_source_correction">Запросить исправление</option></select><textarea name="reason" required></textarea><button>Записать решение</button></form>';foreach($history[$key]??[]as$d)$body.='<p>'.$e($d['outcome']).' · '.$e($d['reason']).' · '.$e($d['occurred_at']).'</p>';}$body.='</article>';}
  if($m['rows']===[])$body.='<p>Нет записей quarantine</p>';return self::page('Pre-import quarantine',$body.self::pager('/pilot/otiz/reconciliation/quarantine',$m,$f));
 }
 private static function notice(string$path):string{$ok=$_GET['decision']??'';$error=$_GET['decisionError']??'';if($ok!=='')return'<p role="status">'.($ok==='duplicate'?'Повтор не создал новую запись.':'Решение добавлено в неизменяемую историю.').'</p>';return$error!==''?'<p role="alert">Решение не записано. Обновите данные и повторите.</p>':'';}
 private static function pager(string$path,array$m,array$f):string{$page=(int)($m['page']??1);$pages=(int)($m['pages']??max(1,ceil(($m['total']??0)/50)));if($pages<2)return'';$q=array_filter($f,fn($v)=>$v!=='');$h='<nav aria-label="Страницы">';for($i=1;$i<=$pages;$i++)$h.='<a'.($i===$page?' aria-current="page"':'').' href="'.$path.'?'.http_build_query($q+['page'=>$i]).'">'.$i.'</a> ';return$h.'</nav>';}
 private static function nav():string{return'<nav><a href="/pilot/otiz">Объекты</a> <a href="/pilot/otiz/reconciliation">Сверка свидетельств</a> <a href="/pilot/otiz/reconciliation/quarantine">Quarantine</a> <a href="/pilot/otiz/active-baselines">Active baselines</a> <a href="/pilot/otiz/historical-replay">Historical replay</a></nav>';}
 private static function page(string$t,string$b):string{return'<!doctype html><html lang="ru"><head><meta charset="utf-8"><title>'.self::e($t).'</title></head><body>'.$b.'</body></html>';}
 private static function e(string$v):string{return htmlspecialchars($v,ENT_QUOTES|ENT_HTML5,'UTF-8');}private static function uuid():string{$b=random_bytes(16);$b[6]=chr((ord($b[6])&15)|64);$b[8]=chr((ord($b[8])&63)|128);return vsprintf('%s%s-%s-%s-%s-%s%s%s',str_split(bin2hex($b),4));}
}
