<?php
declare(strict_types=1);
namespace FMonitor2\YiiRuntime;
final class OtizEvidenceHtml
{
 public static function reconciliation(array$m,array$f,string$csrf):string
 {
  $e=self::e(...);$body=self::notice('/pilot/otiz/reconciliation').'<h1>Сверка перенесённых свидетельств</h1>'.self::nav();
  $body.='<form method="get" action="/pilot/otiz/reconciliation"><label>Классификация <input name="classification" value="'.$e($f['classification']).'"></label><label>Статус <input name="state" value="'.$e($f['state']).'"></label><label>Quarantine <input name="quarantine" value="'.$e($f['quarantine']).'"></label><label>Конфликт <input name="conflict" value="'.$e($f['conflict']).'"></label><button>Применить</button></form>';
  foreach($m['rows']as$row){$id=(int)($row['snapshotId']??0);$history=$m['decisions'][$id]??[];$body.='<article id="snapshot-'.$id.'"><h2>Объект '.(int)($row['legacyObjectId']??0).'</h2><p>Provenance: '.$e((string)($row['sourceLabel']??'')).' · '.$e((string)($row['sourceLocator']??'')).'</p><code>'.$e((string)($row['contentSha256']??'')).'</code>';
   foreach($row['conflictCodes']??[]as$code){$body.='<section><h3>'.$e((string)$code).'</h3><form method="post" action="/pilot/otiz/reconciliation/decisions"><input type="hidden" name="_csrf" value="'.$e($csrf).'"><input type="hidden" name="operationId" value="'.self::uuid().'"><input type="hidden" name="snapshotId" value="'.$id.'"><input type="hidden" name="snapshotSha256" value="'.$e((string)($row['contentSha256']??'')).'"><input type="hidden" name="projectionSha256" value="'.$e((string)($row['projectionHash']??'')).'"><input type="hidden" name="sourceLocator" value="'.$e((string)($row['sourceLocator']??'')).'"><input type="hidden" name="issueCode" value="'.$e((string)$code).'"><select name="outcome"><option value="acknowledge">Ознакомлены</option><option value="reject_evidence">Отклонить</option><option value="request_source_correction">Запросить исправление</option><option value="map_link">Сопоставить</option></select><input name="targetLocator" placeholder="operational_case:1"><textarea name="reason" required></textarea><button>Записать решение</button></form></section>';}
   if($history!==[]){$body.='<h3>История решений</h3><ul>';foreach($history as$d)$body.='<li>'.$e((string)$d['outcome']).' · '.$e((string)$d['reason']).' · '.$e((string)$d['occurred_at']).'</li>';$body.='</ul>';}$body.='</article>';
  }
  if($m['rows']===[])$body.='<p>По выбранным фильтрам ничего нет</p>';return self::page('Сверка свидетельств',$body.self::pager('/pilot/otiz/reconciliation',$m,$f));
 }
 public static function quarantine(array$m,array$history,string$csrf):string
 {
  $e=self::e(...);$f=$m['filters']??['category'=>'','code'=>''];$body=self::notice('/pilot/otiz/reconciliation/quarantine').'<h1>Pre-import quarantine</h1>'.self::nav().'<form method="get" action="/pilot/otiz/reconciliation/quarantine"><input name="category" value="'.$e($f['category']).'"><input name="code" value="'.$e($f['code']).'"><button>Применить</button></form>';
  foreach($m['rows']as$row){$body.='<article><h2>'.$e($row['reference']).'</h2><p>Provenance: '.$e($row['sourceLocator']).' · '.$e($row['sourceDigest']).'</p>';foreach($row['quarantineCodes']as$code){$key=$row['sourceLocator'].'|'.$row['sourceCutoffAt'].'|'.$row['sourceDigest'].'|'.$row['classificationVersion'].'|'.$code;$body.='<form method="post" action="/pilot/otiz/reconciliation/quarantine/decisions"><input type="hidden" name="_csrf" value="'.$e($csrf).'"><input type="hidden" name="operationId" value="'.self::uuid().'">';foreach(['sourceLocator','sourceCutoffAt','sourceDigest','classificationVersion']as$n)$body.='<input type="hidden" name="'.$n.'" value="'.$e($row[$n]).'">';$body.='<input type="hidden" name="quarantineCode" value="'.$e($code).'"><select name="outcome"><option value="acknowledge">Ознакомлены</option><option value="reject_source_evidence">Отклонить источник</option><option value="request_source_correction">Запросить исправление</option></select><textarea name="reason" required></textarea><button>Записать решение</button></form>';foreach($history[$key]??[]as$d)$body.='<p>'.$e($d['outcome']).' · '.$e($d['reason']).' · '.$e($d['occurred_at']).'</p>';}$body.='</article>';}
  if($m['rows']===[])$body.='<p>Нет записей quarantine</p>';return self::page('Pre-import quarantine',$body.self::pager('/pilot/otiz/reconciliation/quarantine',$m,$f));
 }
 public static function activeBaselines(array$m,array$f):string
 {
  $e=self::e(...);$s=$m['summary'];$option=fn(string$v,string$l,string$c):string=>'<option value="'.$e($v).'"'.($v===$c?' selected':'').'>'.$e($l).'</option>';$body='<h1>Active baselines на cutover</h1>'.self::nav().'<section class="fm2-active-summary"><strong>'.(int)$s['total'].'</strong> immutable baselines · <strong>'.(int)$s['ready'].'</strong> готовы · <strong>'.(int)$s['blocked'].'</strong> имеют конфликт · <strong>'.(int)$s['quarantined'].'</strong> quarantine</section><form method="get" action="/pilot/otiz/active-baselines"><label>Native continuation <select name="state">'.$option('','Любое состояние',$f['state']).$option('ready','Можно начинать после cutover',$f['state']).$option('blocked','Требуется разбор',$f['state']).'</select></label><label>Покрытие evidence <select name="coverage">'.$option('','Любое покрытие',$f['coverage']).$option('both','Checklist и attribution',$f['coverage']).$option('partial','Только один источник',$f['coverage']).$option('none','Нет обоих источников',$f['coverage']).'</select></label><button>Применить</button></form>';
  foreach($m['rows']as$r){$template=$r['template'];$body.='<article class="fm2-active-item"><h2>'.$e($r['regnumber']!==''?$r['regnumber']:'Объект № '.$r['legacyObjectId']).'</h2><span>'.($r['nativeReady']?'Можно начинать native events':'Native events заблокированы').'</span><h3>Immutable baseline</h3><p>Cutover '.$e($r['cutoverAt']).' · контракт '.$e($r['contractVersion']).' · hash '.$e($r['baselineHash']).'</p><h3>Классификация</h3><p>'.$e($r['classification']).' · '.$e(implode(', ',$r['reasonCodes'])).' · '.$e($r['classificationVersion']).'</p><h3>Evidence coverage</h3><p>Checklist events '.(int)$r['coverage']['checklist'].' · Attribution facts '.(int)$r['coverage']['attribution'].'</p><h3>Template snapshot</h3>'.($template===null?'<p>Template snapshot не связан.</p>':'<p>Версия '.$e($template['version']).' · действует с '.$e($template['validFrom']).' · captured '.$e($template['capturedAt']).' · hash '.$e($template['contentHash']).' · '.$e($template['sourceLabel']).'</p>').'<h3>Конфликты и quarantine</h3><p>'.($r['conflictCodes']===[]?'Конфликтов не обнаружено':$e(implode(', ',$r['conflictCodes']))).'</p></article>';}
  foreach($m['rows']as$r)$body.='<p class="fm2-active-address">'.$e($r['address']).($r['entrance']===''?'':' · подъезд '.$e($r['entrance'])).'</p>';if($m['rows']===[])$body.='<section><h2>Active baselines не найдены</h2><p>Batch не применён либо фильтры не дают результатов.</p></section>';return self::page('Active baselines на cutover',$body.self::pager('/pilot/otiz/active-baselines',$m,$f));
 }
 public static function historicalReplay(array$m):string
 {
  $e=self::e(...);$body='<h1>Историческое воспроизведение премии</h1>'.self::nav().'<p>Расчёт появляется только из доказанных operands; отсутствующие факты не заменяются нулями.</p>';foreach($m['rows']as$r){$reasons='';foreach($r['exclusionReasons']as$x)$reasons.='<li><code>'.$e($x).'</code></li>';$candidate=$r['progressCandidate']['candidateProgressBp']===null?'—':number_format((int)$r['progressCandidate']['candidateProgressBp']/100,0,',',' ').'%';$body.='<article class="fm2-replay-item"><h2>'.$e($r['regnumber']!==''?$r['regnumber']:'Legacy № '.$r['legacyObjectId']).'</h2><span>'.($r['state']==='calculated'?'Расчёт воспроизведён':'Расчёт недоступен').'</span><h3>Почему исключено</h3><ul>'.$reasons.'</ul><h3>Progress candidate</h3><p>'.$candidate.' · '.$e((string)$r['progressCandidate']['mappingVersion']).' · В расчёте: '.($r['progressCandidate']['usedInCalculation']?'да':'нет').'</p><h3>Фактическая выплата</h3><p>'.$e((string)$r['payoutComparison']['state']).' · discrepancy '.($r['payoutComparison']['discrepancyCents']===null?'не вычисляется':(string)$r['payoutComparison']['discrepancyCents']).'</p><h3>Provenance</h3><p>'.$e($r['provenance']['sourceLabel']).' · '.$e($r['provenance']['sourceLocator']).' · '.$e($r['provenance']['snapshotHash']).'</p></article>';}
  foreach($m['rows']as$r)$body.='<p class="fm2-replay-address">'.$e($r['address']).'</p>';if($m['rows']===[])$body.='<section><h2>Исторические snapshots не импортированы</h2><p>Сначала требуется read-only snapshot и reconciliation.</p></section>';return self::page('Историческое воспроизведение премии',$body.self::pager('/pilot/otiz/historical-replay',$m,[]));
 }
 private static function notice(string$path):string{$ok=$_GET['decision']??'';$error=$_GET['decisionError']??'';if($ok!=='')return'<p role="status">'.($ok==='duplicate'?'Повтор не создал новую запись.':'Решение добавлено в неизменяемую историю.').'</p>';return$error!==''?'<p role="alert">Решение не записано. Обновите данные и повторите.</p>':'';}
 private static function pager(string$path,array$m,array$f):string{$page=(int)($m['page']??1);$pages=(int)($m['pages']??max(1,ceil(($m['total']??0)/50)));if($pages<2)return'';$q=array_filter($f,fn($v)=>$v!=='');$h='<nav aria-label="Страницы"><span>Страница '.$page.'</span> ';for($i=1;$i<=$pages;$i++)$h.='<a'.($i===$page?' aria-current="page"':'').' href="'.$path.'?'.http_build_query($q+['page'=>$i]).'">'.$i.'</a> ';return$h.'</nav>';}
 private static function nav():string{return'<nav><a href="/pilot/otiz">Объекты</a> <a href="/pilot/otiz/reconciliation">Сверка свидетельств</a> <a href="/pilot/otiz/reconciliation/quarantine">Quarantine</a> <a href="/pilot/otiz/active-baselines">Active baselines</a> <a href="/pilot/otiz/historical-replay">Historical replay</a></nav>';}
 private static function page(string$t,string$b):string{return'<!doctype html><html lang="ru"><head><meta charset="utf-8"><title>'.self::e($t).'</title></head><body>'.$b.'</body></html>';}
 private static function e(string$v):string{return htmlspecialchars($v,ENT_QUOTES|ENT_HTML5,'UTF-8');}private static function uuid():string{$b=random_bytes(16);$b[6]=chr((ord($b[6])&15)|64);$b[8]=chr((ord($b[8])&63)|128);return vsprintf('%s%s-%s-%s-%s-%s%s%s',str_split(bin2hex($b),4));}
}
