<?php
declare(strict_types=1);
namespace FMonitor2\AssignmentOrderComposition;

use FMonitor2\AssignmentOrderOriginal\{AssignmentOrderOriginalApplicationReferenceReader,AssignmentOrderOriginalApplicationReferenceStatus,AssignmentOrderOriginalApplicationGuardStatus};

final readonly class MariaDbAssignmentOrderApplication implements AssignmentOrderApplication
{
    public function __construct(private MariaDbAssignmentOrderApplicationSql $sql,private AssignmentOrderOriginalApplicationReferenceReader $originals,private SelectionClock $clock){}
    public function applyAssignmentOrderOriginal(ApplyAssignmentOrderOriginalCommand$c):AssignmentOrderApplicationResult
    {
        if(!$this->valid($c))return$this->out('rejected','invalid_command');$s=$this->sql;
        try{if(!$s->idle())return$this->out('failed','dependency_unavailable');$at=$this->instant();
            if(!$this->authorized($c->actorId))return$this->out('rejected','authorization_denied');
            $lookup=$this->originals->readCurrent($c->objectId,$c->orderId);
            if($lookup->status===AssignmentOrderOriginalApplicationReferenceStatus::NOT_FOUND)return$this->out('rejected','original_not_found');
            if($lookup->status!==AssignmentOrderOriginalApplicationReferenceStatus::FOUND)return$this->out('failed','dependency_unavailable');
            $reference=$lookup->reference;$m=$reference->metadata();if($m['revisionId']!==$c->originalRevisionId)return$this->out('conflict','original_changed');
            if(!$s->db->query('SET TRANSACTION ISOLATION LEVEL READ COMMITTED')||!$s->db->begin_transaction())throw new \RuntimeException();
            $case=$s->rows('SELECT * FROM '.$s->table('fm2_installation_cases').' WHERE legacy_installation_object_id=? FOR UPDATE',[$c->objectId]);
            if($case===[]){$s->db->rollback();return$this->out('rejected','object_not_found');}if(count($case)!==1||(int)$case[0]['id']!==$m['caseId'])throw new \RuntimeException();
            if(!$this->authorized($c->actorId,true))return$this->rejectTx($c,$at,'rejected','authorization_denied');
            $fingerprint=hash('sha256',json_encode([$c->requestId,$c->objectId,$c->orderId,$c->originalRevisionId,$c->expectedApplicationSequence,$c->actorId],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR));
            $accepted=$s->rows('SELECT * FROM '.$s->table('fm2_assignment_order_applications').' WHERE request_id=? FOR UPDATE',[$c->requestId]);
            if($accepted!==[])return $this->replay($c,$at,$fingerprint,$accepted);
            $previous=$s->rows('SELECT * FROM '.$s->table('fm2_assignment_order_applications').' WHERE installation_case_id=? ORDER BY application_sequence DESC LIMIT 1 FOR UPDATE',[$m['caseId']]);
            $sequence=$previous===[]?1:(int)$previous[0]['application_sequence']+1;if($sequence-1!==$c->expectedApplicationSequence)return$this->rejectTx($c,$at,'conflict','application_changed');
            $guard=$this->originals->confirmCurrent($reference);if($guard===AssignmentOrderOriginalApplicationGuardStatus::CHANGED)return$this->rejectTx($c,$at,'conflict','original_changed');
            if($guard!==AssignmentOrderOriginalApplicationGuardStatus::MATCHED)throw new \RuntimeException();
            $legacy=$s->rows('SELECT workdatefinish,ptoactdate FROM '.$s->table('fm_maintable').' WHERE id=? FOR UPDATE',[$c->objectId]);if(count($legacy)!==1)throw new \RuntimeException();
            $completion=$s->rows('SELECT fact_type FROM '.$s->table('fm2_pilot_completion_facts').' WHERE installation_case_id=? FOR UPDATE',[$m['caseId']]);
            $finished=$this->datePresent($legacy[0]['workdatefinish']);$pto=$this->datePresent($legacy[0]['ptoactdate']);foreach($completion as$f){if($f['fact_type']==='declaration')$finished=true;if($f['fact_type']==='pto_act')$pto=true;}
            if($finished)return$this->rejectTx($c,$at,'rejected','object_completed');if($pto)return$this->rejectTx($c,$at,'rejected','object_has_pto_act');
            $today=(new \DateTimeImmutable($at))->setTimezone(new \DateTimeZone('Europe/Moscow'))->format('Y-m-d');if($m['documentDate']>$today)return$this->rejectTx($c,$at,'rejected','document_date_in_future');
            $kind=$previous===[]?'initial':((int)$previous[0]['assignment_order_id']===$c->orderId?'reapplication':'new_order');
            if($kind==='reapplication'&&$previous[0]['original_revision_id']===$c->originalRevisionId)return$this->rejectTx($c,$at,'rejected','no_changes');
            if($kind==='reapplication'&&$case[0]['actual_start_date']!==null)return$this->rejectTx($c,$at,'rejected','reapplication_after_opening');
            if($previous!==[]&&$kind==='new_order'&&$m['orderVersion']<=(int)$previous[0]['order_version'])return$this->rejectTx($c,$at,'conflict','target_not_current');
            if($previous!==[]&&$kind==='new_order'&&$m['documentDate']<$previous[0]['document_date'])return$this->rejectTx($c,$at,'rejected','effective_date_before_current');
            if($case[0]['actual_start_date']!==null&&$kind==='new_order'&&$m['documentDate']<$case[0]['actual_start_date'])return$this->rejectTx($c,$at,'rejected','effective_date_before_opening');
            $crew=$m['composition']['installers'];$ids=array_column($crew,'tabId');$eligibility=AssignmentOrderCurrentEligibility::confirm($s->db,$s->prefix,$ids,$m['composition']['engineer']['userId'],$m['documentDate']);
            if($eligibility!=='eligible')return$this->rejectTx($c,$at,$eligibility==='dependency_unavailable'?'failed':'rejected',$eligibility==='control_engineer_required'?'control_engineer_not_eligible':$eligibility);
            $evidence=$this->eligibility($ids);$selected=['selectedInstallers'=>$crew,'selectedEngineer'=>$m['composition']['engineer']];
            $event=json_encode(['assignmentOrderId'=>$c->orderId,'originalRevisionId'=>$c->originalRevisionId,'applicationSequence'=>$sequence],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR);
            $s->execute('INSERT INTO '.$s->table('fm2_process_events').' (installation_case_id,event_type,occurred_at,actor_user_id,payload_json) VALUES (?,?,?,?,?)',[$m['caseId'],'assignment_order_composition_applied',$at,$c->actorId,$event]);$eventId=MariaDbAssignmentOrderApplicationSql::positive($s->db->insert_id);
            $row=[$m['caseId'],$c->objectId,$sequence,$c->orderId,$m['orderVersion'],$c->originalRevisionId,$m['revisionNumber'],$m['documentDate'],$m['compositionIdentity'],$m['compositionSha256'],$m['composition']['engineer']['userId'],$previous===[]?null:(int)$previous[0]['application_id'],$kind,$this->dbTime($at),$c->actorId,$c->requestId,$fingerprint,$c->expectedApplicationSequence,$eventId,json_encode($selected,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR),json_encode($evidence,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR)];
            $s->execute('INSERT INTO '.$s->table('fm2_assignment_order_applications').' (installation_case_id,object_id,application_sequence,assignment_order_id,order_version,original_revision_id,original_revision_number,document_date,composition_identity,composition_sha256,control_engineer_user_id,previous_application_id,kind,applied_at_utc,applied_by_user_id,request_id,request_fingerprint,expected_application_sequence,process_event_id,selected_snapshot_json,eligibility_snapshot_json) VALUES ('.implode(',',array_fill(0,21,'?')).')',$row);
            $id=MariaDbAssignmentOrderApplicationSql::positive($s->db->insert_id);$this->audit($c,$at,'applied',null,$id);if(!$s->db->commit())throw new \RuntimeException();
            return$this->out('applied',null,AssignmentOrderApplicationPayload::fromRow(array_combine(['installation_case_id','object_id','application_sequence','assignment_order_id','order_version','original_revision_id','original_revision_number','document_date','composition_identity','composition_sha256','control_engineer_user_id','previous_application_id','kind','applied_at_utc','applied_by_user_id','request_id','request_fingerprint','expected_application_sequence','process_event_id','selected_snapshot_json','eligibility_snapshot_json'],$row)+['application_id'=>$id]));
        }catch(\Throwable){try{if(!$s->idle())$s->db->rollback();}catch(\Throwable){}return$this->out('failed','persistence_failure');}
    }
    private function replay(ApplyAssignmentOrderOriginalCommand$c,string$at,string$f,array$rows):AssignmentOrderApplicationResult
    {if(count($rows)!==1)throw new \RuntimeException();$r=$rows[0];if(!hash_equals($r['request_fingerprint'],$f))return$this->rejectTx($c,$at,'conflict','request_id_conflict');$this->audit($c,$at,'replayed',null,(int)$r['application_id']);if(!$this->sql->db->commit())throw new \RuntimeException();return$this->out('replayed',null,AssignmentOrderApplicationPayload::fromRow($r));}
    private function authorized(int$id,bool$lock=false):bool
    {$s=$this->sql;$suffix=$lock?' FOR UPDATE':'';$local=(string)$s->rows('SELECT COUNT(*) n FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=?',[$s->prefix.'fm2_pilot_users'])[0]['n']==='1';if($local)$q='SELECT u.user_id FROM '.$s->table('fm2_pilot_users').' u JOIN '.$s->table('fm2_pilot_user_roles').' ur ON ur.user_id=u.user_id JOIN '.$s->table('fm2_pilot_roles').' r ON r.role_id=ur.role_id JOIN '.$s->table('fm2_pilot_role_permissions')." rp ON rp.role_id=r.role_id WHERE u.user_id=? AND u.status=1 AND BINARY u.activation_state='active' AND r.status=1 AND BINARY r.code IN ('fkr_operator','manager') AND BINARY rp.permission='assignment_order.composition.apply'".$suffix;else$q='SELECT u.id FROM '.$s->table('users').' u JOIN '.$s->table('users_roles').' r ON r.id=u.role_id JOIN '.$s->table('fm2_process_user_capabilities')." c ON c.user_id=u.id WHERE u.id=? AND u.status=1 AND r.status=1 AND BINARY c.capability='assignment_order.composition.apply'".$suffix;return$s->rows($q,[$id])!==[];}
    private function eligibility(array$ids):array{$s=$this->sql;$out=[];foreach($ids as$id){$r=$s->rows('SELECT * FROM '.$s->table('fm2_workforce_catalog').' WHERE installer_tab_id=?',[$id])[0]??null;if(!$r)throw new \RuntimeException();$full=null;if($r['employed_from']===null){$run=$s->rows('SELECT * FROM '.$s->table('fm2_workforce_sync_runs').' WHERE run_id=?',[$r['last_successful_sync_run_id']])[0]??null;if(!$run)throw new \RuntimeException();$full=['runId'=>$run['run_id'],'observedAt'=>$run['observed_at'],'normalizedChecksum'=>$run['normalized_checksum'],'deliveredCount'=>(int)$run['delivered_count'],'pageCount'=>(int)$run['page_count']];}$out[]=['tabId'=>(int)$id,'employmentStatus'=>'employed','employedFrom'=>$r['employed_from'],'employedTo'=>$r['employed_to'],'workforceSource'=>$r['workforce_source'],'sourceUpdatedAt'=>$r['workforce_source_updated_at'],'authoritySystem'=>$r['authority_system']??null,'deliverySystem'=>$r['delivery_system']??null,'deliveryPersonId'=>isset($r['delivery_person_id'])?(int)$r['delivery_person_id']:null,'reconciliationState'=>$r['reconciliation_state']??null,'proofKind'=>$r['employed_from']===null?'full_current':'known_period','fullSnapshot'=>$full];}return$out;}
    private function rejectTx(ApplyAssignmentOrderOriginalCommand$c,string$at,string$status,string$reason):AssignmentOrderApplicationResult{$this->audit($c,$at,$status,$reason,null);if(!$this->sql->db->commit())throw new \RuntimeException();return$this->out($status,$reason);}
    private function audit(ApplyAssignmentOrderOriginalCommand$c,string$at,string$status,?string$reason,?int$id):void{$this->sql->execute('INSERT INTO '.$this->sql->table('fm2_assignment_application_attempts').' (request_id,actor_user_id,object_id,assignment_order_id,status,reason_code,application_id,attempted_at_utc) VALUES (?,?,?,?,?,?,?,?)',[$c->requestId,$c->actorId,$c->objectId,$c->orderId,$status,$reason,$id,$this->dbTime($at)]);}
    private function instant():string{$x=$this->clock->now();$v=$x->payload?->utcRfc3339Seconds;if($x->status!==SelectionLookupStatus::FOUND||!is_string($v)||!preg_match('/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z$/D',$v))throw new \RuntimeException();return$v;}
    private function dbTime(string$s):string{return str_replace(['T','Z'],[' ','.000000'],$s);}private function out(string$s,?string$r,?array$a=null):AssignmentOrderApplicationResult{return new AssignmentOrderApplicationResult($s,$r,$a);}
    private function datePresent(mixed$v):bool{return is_string($v)&&trim($v)!==''&&!str_starts_with(trim($v),'0000-00-00')&&!preg_match('/^0+$/D',trim($v));}
    private function valid(ApplyAssignmentOrderOriginalCommand$c):bool{return preg_match('/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/D',$c->requestId)===1&&$c->objectId>0&&$c->orderId>0&&$c->actorId>0&&$c->expectedApplicationSequence>=0&&$c->expectedApplicationSequence<=2147483647&&preg_match('/^[A-Za-z0-9][A-Za-z0-9._:-]{0,79}$/D',$c->originalRevisionId)===1;}
}
