<?php
declare(strict_types=1);
require dirname(__DIR__).'/bootstrap.php';
$root=dirname(__DIR__,2);$jobs=$root.'/bin/fmonitor2-jobs.php';$handler=$root.'/bin/fmonitor2-job-handler.php';
assertSameValue(true,is_file($jobs)&&is_file($handler),'INTENTIONAL_RED: production Jobs CLI entrypoints exist');
$env=array_replace(getenv(),['FMONITOR_DB_NAME'=>'runtime_contract','FMONITOR_DB_USER'=>'runtime','FMONITOR_DB_PASSWORD'=>'private','FMONITOR_MIGRATION_DB_PASSWORD'=>'private-admin','FMONITOR_MIGRATION_DB_USER'=>'root','FMONITOR_PROCESS_TABLE_PREFIX'=>'fm_','FMONITOR_LEGACY_TABLE_PREFIX'=>'fm_','FMONITOR_SESSION_INSTANCE'=>'contract','FMONITOR_TRUSTED_REQUEST_HOST'=>'localhost','FMONITOR_TRUSTED_REQUEST_SCHEME'=>'http','FMONITOR_RUNTIME_IMAGE'=>'registry.invalid/fmonitor2@sha256:'.str_repeat('1',64),'FMONITOR_ERP_HOST'=>'erp.example.invalid','FMONITOR_ERP_SERVER_CERTIFICATE_FILE_HOST'=>dirname(__DIR__).'/fixtures/erp-server-certificate.pem','FMONITOR_ERP_DATABASE'=>'legacy-stage','FMONITOR_ERP_USER'=>'reader','FMONITOR_ERP_PASSWORD'=>'synthetic-password','FMONITOR_ERP_EQUIPMENT_FACTS_HMAC_KEY'=>str_repeat('h',40),'FMONITOR_ERP_EQUIPMENT_FACTS_MAX_ROWS'=>'500','FMONITOR_ERP_EQUIPMENT_FACTS_TIMEOUT_SECONDS'=>'5','FMONITOR_ERP_EQUIPMENT_FACTS_CHUNK_SIZE'=>'100']);
function jrcRun(array$args,array$env,string$cwd):array{$p=[];$r=proc_open($args,[0=>['file','/dev/null','r'],1=>['pipe','w'],2=>['pipe','w']],$p,$cwd,$env);if(!is_resource($r))throw new TestFailure('SETUP_FAILURE process');foreach($p as$q)stream_set_blocking($q,false);$o='';$e='';$deadline=microtime(true)+10;$exit=null;do{$o.=stream_get_contents($p[1]);$e.=stream_get_contents($p[2]);$s=proc_get_status($r);if(!$s['running']){$exit=$s['exitcode'];break;}if(microtime(true)>=$deadline){proc_terminate($r,9);throw new TestFailure('SETUP_FAILURE command timeout');}usleep(10000);}while(true);$o.=stream_get_contents($p[1]);$e.=stream_get_contents($p[2]);foreach($p as$q)fclose($q);$closed=proc_close($r);return[$exit!==null&&$exit>=0?$exit:$closed,$o,$e];}
$env['FMONITOR_YII_COOKIE_VALIDATION_KEY']='jobs-contract-test-cookie-validation-key';
$env['FMONITOR_YII_IDENTITY_KEY']='jobs-contract-test-identity-key';
[$exit,$default,$error]=jrcRun(['docker','compose','-f','deploy/runtime/compose.yaml','config','--services'],$env,$root);assertSameValue([0,''],[$exit,$error],'default compose resolves');$defaultServices=array_values(array_filter(explode("\n",trim($default))));sort($defaultServices);assertSameValue(['db','jobs-scheduler','jobs-worker','migrate','php','startup-check','web'],$defaultServices,'ordinary topology includes complete jobs contour');
[$exit,$json,$error]=jrcRun(['docker','compose','-f','deploy/runtime/compose.yaml','config','--format','json'],$env,$root);assertSameValue([0,''],[$exit,$error],'jobs compose resolves');$model=json_decode($json,true,512,JSON_THROW_ON_ERROR);foreach(['jobs-worker'=>'worker','jobs-scheduler'=>'scheduler']as$name=>$mode){$service=$model['services'][$name]??null;assertSameValue(true,is_array($service),'ordinary topology contains '.$name);assertSameValue(false,array_key_exists('profiles',$service),'jobs service is not opt-in');assertSameValue(false,array_key_exists('ports',$service),'jobs service has no ports');assertSameValue($model['services']['php']['image'],$service['image'],'jobs service uses exact php image');assertSameValue(['php','bin/yii','jobs/'.$mode,'--interactive=0'],$service['command'],'jobs service exact Yii2 CLI role');assertSameValue(['CMD','php','bin/yii','jobs/process-health','--interactive=0'],$service['healthcheck']['test']??null,'jobs service uses process readiness');assertSameValue('service_completed_successfully',$service['depends_on']['migrate']['condition']??null,'jobs wait for canonical migration');assertSameValue(['SIGTERM',true],[$service['stop_signal'],in_array($service['stop_grace_period'],['60s','1m0s'],true)],'jobs service exact 60-second graceful stop contract');assertSameValue(false,(bool)preg_match('/migrate|bootstrap|docker-bootstrap|php\s+-S|socat/i',implode(' ',$service['command'])),'jobs command has no startup migration/demo');$encoded=json_encode([$service['environment']??[],$service['volumes']??[]],JSON_THROW_ON_ERROR);if($mode==='worker'){assertSameValue('/run/fmonitor-secrets/bitrix-config.json',$service['environment']['FMONITOR_BITRIX_CONFIG']??null,'worker receives canonical private config');foreach(['FMONITOR_BITRIX_TOKEN_HOST_FILE','FMONITOR_BITRIX_RUNTIME_CONFIG_FILE','FMONITOR_BITRIX_TOKEN_FILE','FMONITOR_BITRIX_ORIGIN','FMONITOR_BITRIX_WEBHOOK_USER_ID','bitrix-token']as$forbidden)assertSameValue(false,str_contains($encoded,$forbidden),'disabled-capable worker has no duplicate runtime input '.$forbidden);}else{assertSameValue(false,str_contains($encoded,'BITRIX'),'scheduler receives no Bitrix configuration');assertSameValue(false,str_contains($encoded,'bitrix-'),'scheduler receives no transport secret mount');}}
$source=file_get_contents($jobs).file_get_contents($handler);assertSameValue(false,(bool)preg_match('/FMONITOR_DEMO_|PILOT_ACTIVE_MANIFEST|docker-bootstrap|fmonitor2-migrate|CREATE\s+TABLE|ALTER\s+TABLE|php\s+-S|socat/i',$source),'Jobs CLI has no demo/bootstrap/migration/DDL proxy');echo "PASS: JOBS-RUNTIME-WIRING-001 resolved Compose boundary\n";
