<?php
declare(strict_types=1);
require dirname(__DIR__).'/bootstrap.php';require dirname(__DIR__,2).'/app/autoload.php';
use FMonitor2\InstallationProcess\JobsSchemaMigration;use FMonitor2\Jobs\MariaDbJobQueue;
function jcliRun(string$file,array$args,array$env,string$cwd):array{$p=[];$r=proc_open([PHP_BINARY,$file,...$args],[0=>['file','/dev/null','r'],1=>['pipe','w'],2=>['pipe','w']],$p,$cwd,$env);if(!is_resource($r))throw new TestFailure('SETUP_FAILURE cli');foreach($p as$q)stream_set_blocking($q,false);$o='';$e='';$end=microtime(true)+10;$x=null;do{$o.=stream_get_contents($p[1]);$e.=stream_get_contents($p[2]);$s=proc_get_status($r);if(!$s['running']){$x=$s['exitcode'];break;}if(microtime(true)>=$end){proc_terminate($r,9);throw new TestFailure('SETUP_FAILURE cli timeout');}usleep(10000);}while(true);foreach($p as$q)fclose($q);$c=proc_close($r);return[$x!==null&&$x>=0?$x:$c,trim($o),$e];}
$root=dirname(__DIR__,2);$cli=$root.'/bin/fmonitor2-jobs.php';assertSameValue(true,is_file($cli),'INTENTIONAL_RED: public Jobs CLI exists');$host=getenv('FMONITOR_TEST_DB_HOST')?:'127.0.0.1';$port=(int)(getenv('FMONITOR_TEST_DB_PORT')?:23306);$user=getenv('FMONITOR_TEST_DB_ADMIN_USER')?:'root';$password=getenv('FMONITOR_TEST_DB_ADMIN_PASSWORD')?:'fmonitor2_test_root_local';$name='t_jobs_runtime_'.bin2hex(random_bytes(5));$runtime='runtime_'.bin2hex(random_bytes(4));$runtimePassword='Runtime-Cli-2026!';$p='runtime_';$admin=new mysqli($host,$user,$password,'',$port);$admin->query("CREATE DATABASE `{$name}` DEFAULT CHARSET=utf8mb4");$db=new mysqli($host,$user,$password,$name,$port);
try{JobsSchemaMigration::apply($db,$p);$escaped=$admin->real_escape_string($runtimePassword);$admin->query("CREATE USER `{$runtime}`@'%' IDENTIFIED BY '{$escaped}'");$admin->query("GRANT SELECT,INSERT,UPDATE,DELETE ON `{$name}`.* TO `{$runtime}`@'%'");$env=array_replace(getenv(),['FMONITOR_DB_HOST'=>$host,'FMONITOR_DB_PORT'=>(string)$port,'FMONITOR_DB_NAME'=>$name,'FMONITOR_DB_USER'=>$runtime,'FMONITOR_DB_PASSWORD'=>$runtimePassword,'FMONITOR_PROCESS_TABLE_PREFIX'=>$p,'FMONITOR_SESSION_INSTANCE'=>'runtime-test']);
[$x,$out,$err]=jcliRun($cli,['schedule-once','--now-utc','2026-09-09T07:07:00.000000Z'],$env,$root);$scheduled=json_decode($out,true,512,JSON_THROW_ON_ERROR);assertSameValue([0,'',['slot','dueAt','created','jobId','skippedSlots']],[$x,$err,array_keys($scheduled)],'schedule-once exact public JSON');
$scheduledLease=(new MariaDbJobQueue($db,$p,static fn():string=>'2026-09-09T07:07:00.000000Z',static fn():string=>str_repeat('c',64),['workforce.sync'=>[1]]))->claim(['workerId'=>'setup','batch'=>1])[0];(new MariaDbJobQueue($db,$p,static fn():string=>'2026-09-09T07:07:00.000000Z',static fn():string=>str_repeat('c',64),['workforce.sync'=>[1]]))->complete(['jobId'=>$scheduledLease['jobId'],'leaseToken'=>$scheduledLease['leaseToken'],'result'=>['fixture'=>true]]);$liveNow=(new DateTimeImmutable('now',new DateTimeZone('UTC')))->format('Y-m-d\TH:i:s.u\Z');$db->query("INSERT INTO `{$p}fm2_worker_heartbeats` VALUES('worker:runtime-test','{$liveNow}'),('scheduler:runtime-test','{$liveNow}')");[$x,$out,$err]=jcliRun($cli,['health'],$env,$root);assertSameValue([0,true,''],[$x,json_decode($out,true,512,JSON_THROW_ON_ERROR)['ok'],$err],'healthy CLI exit0');$db->query("UPDATE `{$p}fm2_worker_heartbeats` SET observed_at_utc='2026-09-09T06:00:00.000000Z'");[$x,$out]=jcliRun($cli,['health'],$env,$root);assertSameValue([70,false],[$x,json_decode($out,true,512,JSON_THROW_ON_ERROR)['ok']],'unhealthy CLI exit70');
$queue=new MariaDbJobQueue($db,$p,static fn():string=>'2026-09-09T08:00:00.000000Z',static fn():string=>str_repeat('a',64),['test.dead'=>[1]]);$job=$queue->enqueue(['jobType'=>'test.dead','payloadVersion'=>1,'payload'=>['private'=>'hidden'],'availableAtUtc'=>'2026-09-09T08:00:00.000000Z','idempotencyKey'=>'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','actor'=>['type'=>'system','id'=>'test']]);$lease=$queue->claim(['workerId'=>'fixture','batch'=>1])[0];$queue->fail(['jobId'=>$job['jobId'],'leaseToken'=>$lease['leaseToken'],'failureCode'=>'FIXTURE','retryable'=>false]);[$x,$out]=jcliRun($cli,['list-failed','--page','1','--limit','1'],$env,$root);assertSameValue([0,1],[$x,json_decode($out,true,512,JSON_THROW_ON_ERROR)['total']],'fixed-authority list CLI');[$x,$out]=jcliRun($cli,['retry','--job-id',(string)$job['jobId'],'--operation-id','bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb','--now-utc','2026-09-09T08:01:00.000000Z'],$env,$root);assertSameValue([0,'created'],[$x,json_decode($out,true,512,JSON_THROW_ON_ERROR)['status']],'fixed-authority retry CLI');
$before=$db->query("SELECT * FROM `{$p}fm2_jobs` ORDER BY job_id")->fetch_all(MYSQLI_ASSOC);foreach([['unknown'],['retry','--authority','admin'],['health','--extra','x']]as$args){[$x,$out]=jcliRun($cli,$args,$env,$root);assertSameValue([64,['ok'=>false,'error'=>'CONFIGURATION_INVALID']],[$x,json_decode($out,true,512,JSON_THROW_ON_ERROR)],'invalid invocation closed failure');} $missing=$env;unset($missing['FMONITOR_DB_PASSWORD']);putenv('FMONITOR_DB_PASSWORD=PARENT_POISON_MUST_NOT_BE_INHERITED');[$x,$out]=jcliRun($cli,['health'],$missing,$root);putenv('FMONITOR_DB_PASSWORD');assertSameValue([64,['ok'=>false,'error'=>'CONFIGURATION_INVALID']],[$x,json_decode($out,true,512,JSON_THROW_ON_ERROR)],'missing config closed failure despite parent poison');assertSameValue($before,$db->query("SELECT * FROM `{$p}fm2_jobs` ORDER BY job_id")->fetch_all(MYSQLI_ASSOC),'invalid invocations do not mutate jobs');echo "PASS: JOBS-RUNTIME-WIRING-001 public CLI matrix\n";
}finally{$db->close();try{$admin->query("DROP USER IF EXISTS `{$runtime}`@'%'");}catch(Throwable){}$admin->query("DROP DATABASE IF EXISTS `{$name}`");$admin->close();}
