<?php
declare(strict_types=1);
require dirname(__DIR__).'/bootstrap.php';require dirname(__DIR__,2).'/app/autoload.php';
use FMonitor2\Jobs\{SmtpConfiguration,SmtpTransport,WeeklyFkrReportJobHandler};
if(getenv('FMONITOR_FIXTURE_REACHABILITY')==='weekly-delivery-fixture'){assertSameValue(4,count(array_unique(['delivered','transient','permanent','unknown'])),'delivery outcome fixture complete');echo "FIXTURE_REACHABLE: weekly-delivery-fixture\n";exit(0);}
assertSameValue(true,class_exists(WeeklyFkrReportJobHandler::class)&&class_exists(SmtpTransport::class),'INTENTIONAL_RED: WEEKLY-FKR-ATTENTION-EMAIL-001 delivery seams exist');
$domainFacts=['objects'=>[['id'=>1,'progress'=>60]],'events'=>[['id'=>1,'type'=>'progress']]];$domainBefore=hash('sha256',serialize($domainFacts));$recipient=['active'=>true,'role'=>'fkr_manager','email'=>'new@example.test'];$network=[];$resolver=static function(string$id)use(&$recipient):?array{return$id==='leader-1'?$recipient:null;};
$assertDomain=static function(string$path)use(&$domainFacts,$domainBefore):void{assertSameValue($domainBefore,hash('sha256',serialize($domainFacts)),"A12 {$path} leaves connected domain facts byte-equivalent");};
$config=SmtpConfiguration::fromEnvironment(['FMONITOR_RUNTIME_ENV'=>'test','FMONITOR_SMTP_HOST'=>'smtp.test','FMONITOR_SMTP_PORT'=>'587','FMONITOR_SMTP_ENCRYPTION'=>'tls','FMONITOR_SMTP_USERNAME'=>'mailer@example.test','FMONITOR_SMTP_PASSWORD'=>'hidden-secret','FMONITOR_SMTP_FROM_ADDRESS'=>'mailer@example.test','FMONITOR_SMTP_FROM_NAME'=>'FMonitor','FMONITOR_SMTP_TIMEOUT_SECONDS'=>'10','FMONITOR_SMTP_VERIFY_PEER'=>'true','FMONITOR_PUBLIC_BASE_URL'=>'https://fmonitor.example.test','FMONITOR_SMTP_TEST_RECIPIENT'=>'sink@example.test']);
$transport=new SmtpTransport($config,$resolver,static function(array$wire)use(&$network,&$domainFacts):array{$witness=$domainFacts['objects'][0]['id'];$network[]=$wire;return['status'=>'delivered','providerReference'=>'smtp-'.$witness];});
$outcome=$transport->send(['recipientIdentity'=>'leader-1','subject'=>'Отчёт','html'=>'<p>ok</p>','text'=>'ok']);
assertSameValue(['delivered','smtp-1',true],[$outcome['status'],$outcome['providerReference'],$outcome['testRecipientOverride']],'A8/A10 typed delivered test outcome');
$assertDomain('delivered');
assertSameValue(['sink@example.test','mailer@example.test'],[$network[0]['to'],$network[0]['from']],'A9/A10 test override and authenticated sender');
assertSameValue(false,str_contains(json_encode($network,JSON_THROW_ON_ERROR),'new@example.test')||str_contains(json_encode($outcome,JSON_THROW_ON_ERROR),'hidden-secret'),'A9/A10 logical email and secret absent from wire body/safe outcome');
$base=['FMONITOR_RUNTIME_ENV'=>'test','FMONITOR_SMTP_HOST'=>'smtp.test','FMONITOR_SMTP_PORT'=>'587','FMONITOR_SMTP_ENCRYPTION'=>'tls','FMONITOR_SMTP_USERNAME'=>'mailer@example.test','FMONITOR_SMTP_PASSWORD'=>'hidden-secret','FMONITOR_SMTP_FROM_ADDRESS'=>'mailer@example.test','FMONITOR_SMTP_FROM_NAME'=>'FMonitor','FMONITOR_SMTP_TIMEOUT_SECONDS'=>'10','FMONITOR_SMTP_VERIFY_PEER'=>'true','FMONITOR_PUBLIC_BASE_URL'=>'https://fmonitor.example.test'];$directConfig=SmtpConfiguration::fromEnvironment($base);$direct=[];$responses=[['status'=>'transient','failureCode'=>'SMTP_TEMPORARY'],['status'=>'unknown','failureCode'=>'UNKNOWN_DELIVERY'],['status'=>'permanent','failureCode'=>'RECIPIENT_INVALID']];$directTransport=new SmtpTransport($directConfig,$resolver,static function(array$wire)use(&$direct,&$responses,&$domainFacts):array{$witness=$domainFacts['events'][0]['id'];$direct[]=$wire;return array_shift($responses);});
$recipientBefore=hash('sha256',serialize($recipient));assertSameValue(['status'=>'transient','failureCode'=>'SMTP_TEMPORARY'],$directTransport->send(['recipientIdentity'=>'leader-1','subject'=>'s','html'=>'h','text'=>'t']),'A8 transient outcome explicit');assertSameValue($recipientBefore,hash('sha256',serialize($recipient)),'A12 transient delivery cannot mutate recipient facts');$assertDomain('transient');$recipient['email']='changed@example.test';$recipientBefore=hash('sha256',serialize($recipient));assertSameValue(['status'=>'unknown','failureCode'=>'UNKNOWN_DELIVERY'],$directTransport->send(['recipientIdentity'=>'leader-1','subject'=>'s','html'=>'h','text'=>'t']),'A8 unknown ACK never becomes delivered');assertSameValue($recipientBefore,hash('sha256',serialize($recipient)),'A12 unknown delivery cannot mutate recipient facts');$assertDomain('unknown delivery');assertSameValue('changed@example.test',$direct[1]['to'],'A9 retry resolves changed current email');$recipientBefore=hash('sha256',serialize($recipient));assertSameValue(['status'=>'permanent','failureCode'=>'RECIPIENT_INVALID'],$directTransport->send(['recipientIdentity'=>'leader-1','subject'=>'s','html'=>'h','text'=>'t']),'A8 permanent outcome explicit');assertSameValue($recipientBefore,hash('sha256',serialize($recipient)),'A12 permanent delivery cannot mutate recipient facts');$assertDomain('permanent delivery');
$recipient=['active'=>false,'role'=>'fkr_manager','email'=>'new@example.test'];$recipientBefore=hash('sha256',serialize($recipient));$before=count($network);assertSameValue(['status'=>'permanent','failureCode'=>'RECIPIENT_INELIGIBLE'],$transport->send(['recipientIdentity'=>'leader-1','subject'=>'Отчёт','html'=>'<p>ok</p>','text'=>'ok']),'A9 revoked recipient rejected before network');assertSameValue([$before,$recipientBefore],[count($network),hash('sha256',serialize($recipient))],'A9/A12 zero network and no recipient mutation for revoked recipient');$assertDomain('revoked recipient');
$intents=[];$handler=new WeeklyFkrReportJobHandler(static function(string$week)use(&$domainFacts):array{return[['identity'=>'leader-1','report'=>['subject'=>'s','html'=>'<p>object '.$domainFacts['objects'][0]['id'].'</p>','text'=>'object '.$domainFacts['objects'][0]['id']]]];},static function(array$intent)use(&$intents,&$domainFacts):array{$witness=$domainFacts['events'][0]['type'];$key=$intent['idempotencyKey'];if(!isset($intents[$key]))$intents[$key]=['intentId'=>count($intents)+1,'created'=>true,'intent'=>$intent];else$intents[$key]['created']=false;return$intents[$key];});
$first=$handler->handle(['reportWeek'=>'2026-09-21','generatedAtUtc'=>'2026-09-21T06:00:00.000000Z']);$assertDomain('initial generation');$repeat=$handler->handle(['reportWeek'=>'2026-09-21','generatedAtUtc'=>'2026-09-21T06:00:00.000000Z']);$assertDomain('first replay');
assertSameValue([1,1,false,'weekly-fkr-report/v1/2026-09-21/leader-1'],[count($first['intents']),count($intents),$repeat['intents'][0]['created'],array_key_first($intents)],'A8 per-week recipient intent replay is idempotent');
$handler->handle(['reportWeek'=>'2026-09-21','generatedAtUtc'=>'2026-09-21T06:00:00.000000Z']);$assertDomain('second replay');
$large=str_repeat('x',SmtpConfiguration::MAX_MESSAGE_BYTES);assertSameValue(['status'=>'permanent','failureCode'=>'REPORT_TOO_LARGE','bytes'=>SmtpConfiguration::MAX_MESSAGE_BYTES+2,'limit'=>SmtpConfiguration::MAX_MESSAGE_BYTES],$transport->send(['recipientIdentity'=>'leader-1','subject'=>'s','html'=>$large,'text'=>'t']),'A11 complete overflow rejection');$assertDomain('overflow');
echo "PASS: WEEKLY-FKR-ATTENTION-EMAIL-001 delivery lifecycle\n";
