<?php

declare(strict_types=1);

namespace FMonitor2\AssignmentOrderOriginal;

require_once __DIR__ . '/AssignmentOrderOriginalApplication.php';

enum AssignmentOrderOriginalMaintenanceStatus:string { case COMPLETED='completed';case REPLAYED='replayed';case REJECTED='rejected';case PARTIAL='partial';case FAILED='failed'; }
enum AssignmentOrderOriginalMaintenanceReason:string { case INVALID_COMMAND='invalid_command';case AUTHORIZATION_DENIED='authorization_denied';case LOCKED='locked';case STORAGE_FAILURE='storage_failure';case PERSISTENCE_FAILURE='persistence_failure'; }
final readonly class ReconcileAssignmentOrderOriginalPrivateOrphansCommand { public function __construct(public string$requestId,public string$systemPrincipalId,public string$cutoffUtc,public int$batchLimit,public ?string$cursor){} }
interface AssignmentOrderOriginalMaintenanceResult { public function status():AssignmentOrderOriginalMaintenanceStatus;public function reason():?AssignmentOrderOriginalMaintenanceReason;public function retryable():bool;public function scanned():int;public function deleted():int;public function retained():int;public function failed():int;public function nextCursor():?string; }
interface AssignmentOrderOriginalMaintenanceApplication { public function reconcileAssignmentOrderOriginalPrivateOrphans(ReconcileAssignmentOrderOriginalPrivateOrphansCommand$command):AssignmentOrderOriginalMaintenanceResult; }
interface AssignmentOrderOriginalMaintenanceAuthorizer { public function authorize(string$systemPrincipalId,string$exactCapability):AssignmentOrderOriginalAuthorizationStatus; }
final readonly class AssignmentOrderOriginalMaintenanceCommit { public function __construct(public string$requestId,public string$systemPrincipalId,public AssignmentOrderOriginalMaintenanceStatus$status,public ?AssignmentOrderOriginalMaintenanceReason$reason,public bool$retryable,public int$scanned,public int$deleted,public int$retained,public int$failed,public ?string$nextCursor,public string$attemptedAtUtc){} }
interface AssignmentOrderOriginalMaintenanceResultLookup { public function status():AssignmentOrderOriginalLookupStatus;public function result():?AssignmentOrderOriginalMaintenanceResult; }
interface AssignmentOrderOriginalMaintenanceRepository { public function findTerminalRequest(string$requestId):AssignmentOrderOriginalMaintenanceResultLookup;public function commitResultAndAudit(AssignmentOrderOriginalMaintenanceCommit$commit):AssignmentOrderOriginalCommitStatus; }
final readonly class AssignmentOrderOriginalMaintenanceDependencies { public function __construct(public AssignmentOrderOriginalMaintenanceAuthorizer$authorizer,public AssignmentOrderOriginalClock$clock,public AssignmentOrderOriginalPrivateStorage$storage,public AssignmentOrderOriginalRepository$references,public AssignmentOrderOriginalMaintenanceRepository$requests,public AssignmentOrderOriginalStorageObserver$storageObserver,public AssignmentOrderOriginalFaultInjector$faults,public AssignmentOrderOriginalSafeLogObserver$safeLog){} }
final readonly class AssignmentOrderOriginalMaintenanceValueResult implements AssignmentOrderOriginalMaintenanceResult { public function __construct(private AssignmentOrderOriginalMaintenanceStatus$s,private ?AssignmentOrderOriginalMaintenanceReason$r,private bool$retry,private int$scan,private int$delete,private int$retain,private int$fail,private ?string$cursor){}public function status():AssignmentOrderOriginalMaintenanceStatus{return$this->s;}public function reason():?AssignmentOrderOriginalMaintenanceReason{return$this->r;}public function retryable():bool{return$this->retry;}public function scanned():int{return$this->scan;}public function deleted():int{return$this->delete;}public function retained():int{return$this->retain;}public function failed():int{return$this->fail;}public function nextCursor():?string{return$this->cursor;} }
final class AssignmentOrderOriginalMaintenanceVerificationFactory { public static function create(AssignmentOrderOriginalMaintenanceDependencies$d):AssignmentOrderOriginalMaintenanceApplication{return new AssignmentOrderOriginalMaintenanceService($d);} }

final class AssignmentOrderOriginalMaintenanceService implements AssignmentOrderOriginalMaintenanceApplication
{
    public function __construct(private AssignmentOrderOriginalMaintenanceDependencies$d){}
    public function reconcileAssignmentOrderOriginalPrivateOrphans(ReconcileAssignmentOrderOriginalPrivateOrphansCommand$c):AssignmentOrderOriginalMaintenanceResult
    {
        if(preg_match('/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/D',$c->requestId)!==1||$c->batchLimit<1||$c->batchLimit>1000||($c->cursor!==null&&preg_match('/^[A-Za-z0-9_-]+$/D',$c->cursor)!==1))return$this->value(AssignmentOrderOriginalMaintenanceStatus::REJECTED,AssignmentOrderOriginalMaintenanceReason::INVALID_COMMAND,false);
        try{$authorization=$this->d->authorizer->authorize($c->systemPrincipalId,'assignment_order.original.storage.reconcile');}catch(\Throwable){return$this->value(AssignmentOrderOriginalMaintenanceStatus::FAILED,AssignmentOrderOriginalMaintenanceReason::PERSISTENCE_FAILURE,true);}if($authorization!==AssignmentOrderOriginalAuthorizationStatus::ALLOWED)return$this->value(AssignmentOrderOriginalMaintenanceStatus::REJECTED,AssignmentOrderOriginalMaintenanceReason::AUTHORIZATION_DENIED,false);
        try{$stored=$this->d->requests->findTerminalRequest($c->requestId);}catch(\Throwable){return$this->value(AssignmentOrderOriginalMaintenanceStatus::FAILED,AssignmentOrderOriginalMaintenanceReason::PERSISTENCE_FAILURE,true);}if($stored->status()===AssignmentOrderOriginalLookupStatus::UNAVAILABLE)return$this->value(AssignmentOrderOriginalMaintenanceStatus::FAILED,AssignmentOrderOriginalMaintenanceReason::PERSISTENCE_FAILURE,true);if($stored->status()===AssignmentOrderOriginalLookupStatus::FOUND&&$stored->result()!==null){$r=$stored->result();return$this->value(AssignmentOrderOriginalMaintenanceStatus::REPLAYED,$r->reason(),false,$r->scanned(),$r->deleted(),$r->retained(),$r->failed(),$r->nextCursor());}
        try{$now=$this->d->clock->nowUtc();$cutoff=new \DateTimeImmutable($c->cutoffUtc);$instant=new \DateTimeImmutable($now);}catch(\Throwable){return$this->value(AssignmentOrderOriginalMaintenanceStatus::REJECTED,AssignmentOrderOriginalMaintenanceReason::INVALID_COMMAND,false);}if($cutoff>$instant->modify('-3600 seconds'))return$this->value(AssignmentOrderOriginalMaintenanceStatus::REJECTED,AssignmentOrderOriginalMaintenanceReason::INVALID_COMMAND,false);
        try{$page=$this->d->storage->listOrphans($c->cutoffUtc,$c->batchLimit,$c->cursor);}catch(\Throwable){return$this->value(AssignmentOrderOriginalMaintenanceStatus::FAILED,AssignmentOrderOriginalMaintenanceReason::PERSISTENCE_FAILURE,true);}if($page->status()!==AssignmentOrderOriginalStorageStatus::OK)return$this->value(AssignmentOrderOriginalMaintenanceStatus::FAILED,AssignmentOrderOriginalMaintenanceReason::PERSISTENCE_FAILURE,true);
        $scanned=$deleted=$retained=$failed=$locked=$storageFailures=0;foreach($page->candidates()as$candidate){$scanned++;try{$lock=$this->d->storage->acquireDigestLock($candidate->opaqueIdentity);}catch(\Throwable){$failed++;$storageFailures++;continue;}if($lock->status()===AssignmentOrderOriginalStorageStatus::LOCKED){$retained++;$locked++;continue;}if($lock->status()!==AssignmentOrderOriginalStorageStatus::OK){$failed++;$storageFailures++;continue;}try{if($candidate->kind===AssignmentOrderOriginalOrphanKind::FINALIZED_CONTENT){$reference=$this->d->references->hasCommittedContent($candidate->opaqueIdentity);if($reference->status()!==AssignmentOrderOriginalLookupStatus::FOUND){$failed++;$storageFailures++;continue;}if($reference->referenced()===true){$retained++;continue;}}$delete=$this->d->storage->deleteLocked($lock);if(in_array($delete,[AssignmentOrderOriginalStorageStatus::OK,AssignmentOrderOriginalStorageStatus::ALREADY_PRESENT_VERIFIED],true))$deleted++;else{$failed++;$storageFailures++;}}catch(\Throwable){$failed++;$storageFailures++;}finally{$lock->release();}}
        $status=($locked+$storageFailures)>0?AssignmentOrderOriginalMaintenanceStatus::PARTIAL:AssignmentOrderOriginalMaintenanceStatus::COMPLETED;$reason=$status===AssignmentOrderOriginalMaintenanceStatus::COMPLETED?null:($storageFailures>0?AssignmentOrderOriginalMaintenanceReason::STORAGE_FAILURE:AssignmentOrderOriginalMaintenanceReason::LOCKED);return$this->commit($c,$status,$reason,$status===AssignmentOrderOriginalMaintenanceStatus::PARTIAL,$scanned,$deleted,$retained,$failed,$page->nextCursor(),$now);
    }
    private function commit(ReconcileAssignmentOrderOriginalPrivateOrphansCommand$c,AssignmentOrderOriginalMaintenanceStatus$s,?AssignmentOrderOriginalMaintenanceReason$r,bool$retry,int$scan,int$delete,int$retain,int$fail,?string$cursor,string$now):AssignmentOrderOriginalMaintenanceResult{$commit=new AssignmentOrderOriginalMaintenanceCommit($c->requestId,$c->systemPrincipalId,$s,$r,$retry,$scan,$delete,$retain,$fail,$cursor,$now);try{$status=$this->d->requests->commitResultAndAudit($commit);}catch(\Throwable){$status=AssignmentOrderOriginalCommitStatus::ROLLED_BACK;}if($status!==AssignmentOrderOriginalCommitStatus::COMMITTED)return$this->value(AssignmentOrderOriginalMaintenanceStatus::FAILED,AssignmentOrderOriginalMaintenanceReason::PERSISTENCE_FAILURE,true);return$this->value($s,$r,$retry,$scan,$delete,$retain,$fail,$cursor);}
    private function value(AssignmentOrderOriginalMaintenanceStatus$s,?AssignmentOrderOriginalMaintenanceReason$r,bool$retry,int$scan=0,int$delete=0,int$retain=0,int$fail=0,?string$cursor=null):AssignmentOrderOriginalMaintenanceResult{return new AssignmentOrderOriginalMaintenanceValueResult($s,$r,$retry,$scan,$delete,$retain,$fail,$cursor);}
}
