<?php

declare(strict_types=1);

namespace FMonitor2\AssignmentOrderOriginal;

require_once __DIR__ . '/AssignmentOrderOriginalApplication.php';

final class AssignmentOrderOriginalPrivateStorageFactory
{
    public static function create(string $absolutePrivateRoot, AssignmentOrderOriginalStorageObserver $observer, AssignmentOrderOriginalFaultInjector $faults): AssignmentOrderOriginalPrivateStorage
    {
        if (!str_starts_with($absolutePrivateRoot, '/') || str_contains($absolutePrivateRoot, "\0")) throw new \InvalidArgumentException('Private root must be absolute.');
        return new FilesystemAssignmentOrderOriginalPrivateStorage($absolutePrivateRoot, $observer, $faults);
    }
}

final class FilesystemAssignmentOrderOriginalPrivateStorage implements AssignmentOrderOriginalPrivateStorage
{
    public function __construct(private string $root, private AssignmentOrderOriginalStorageObserver $observer, private AssignmentOrderOriginalFaultInjector $faults) {}
    public function beginStage(): AssignmentOrderOriginalPrivateStage
    {
        $this->faults->before(AssignmentOrderOriginalFaultPoint::STAGE);$this->ensure($this->root.'/stages');$id='stage-'.bin2hex(random_bytes(16));$path=$this->root.'/stages/'.$id;$handle=fopen($path,'x+b');if(!is_resource($handle))throw new \RuntimeException('stage unavailable');chmod($path,0600);$this->observer->observe(AssignmentOrderOriginalStorageEvent::STAGE_BEGIN,$id);return new FilesystemAssignmentOrderOriginalPrivateStage($this->root,$id,$path,$handle,$this->observer,$this->faults);
    }
    public function listOrphans(string $cutoffUtc,int $limit,?string $cursor):AssignmentOrderOriginalOrphanPage
    {
        try{$cutoff=(new \DateTimeImmutable($cutoffUtc))->getTimestamp();$after=null;if($cursor!==null){$padding=(4-strlen($cursor)%4)%4;$decoded=base64_decode(strtr($cursor,'-_','+/').str_repeat('=',$padding),true);if(!is_string($decoded)||rtrim(strtr(base64_encode($decoded),'+/','-_'),'=')!==$cursor||preg_match('/^([0-9]+)\|(.+)$/D',$decoded,$m)!==1)return new FilesystemAssignmentOrderOriginalOrphanPage(AssignmentOrderOriginalStorageStatus::FAILED,[],null);$after=[(int)$m[1],$m[2]];}$items=[];foreach(glob($this->root.'/stages/*')?:[]as$path)if(is_file($path))$items[]=new AssignmentOrderOriginalOrphanCandidate(AssignmentOrderOriginalOrphanKind::ABANDONED_STAGE,basename($path),null,filesize($path)?:0,gmdate('Y-m-d\TH:i:s\Z',filemtime($path)?:0));foreach(glob($this->root.'/sha256/*/*/*')?:[]as$path)if(is_file($path)){$id=substr($path,strlen($this->root)+1);$items[]=new AssignmentOrderOriginalOrphanCandidate(AssignmentOrderOriginalOrphanKind::FINALIZED_CONTENT,$id,basename($path),filesize($path)?:0,gmdate('Y-m-d\TH:i:s\Z',filemtime($path)?:0));}usort($items,static fn($a,$b)=>[$a->createdOrFinalizedAtUtc,$a->opaqueIdentity]<=>[$b->createdOrFinalizedAtUtc,$b->opaqueIdentity]);$eligible=array_values(array_filter($items,static function($x)use($cutoff,$after){$time=(new \DateTimeImmutable($x->createdOrFinalizedAtUtc))->getTimestamp();return$time<=$cutoff&&($after===null||[$time,$x->opaqueIdentity]>$after);}));$page=array_slice($eligible,0,$limit);$next=null;if(count($eligible)>count($page)&&$page!==[]){$last=$page[array_key_last($page)];$raw=(new \DateTimeImmutable($last->createdOrFinalizedAtUtc))->getTimestamp().'|'.$last->opaqueIdentity;$next=rtrim(strtr(base64_encode($raw),'+/','-_'),'=');}return new FilesystemAssignmentOrderOriginalOrphanPage(AssignmentOrderOriginalStorageStatus::OK,$page,$next);}catch(\Throwable){return new FilesystemAssignmentOrderOriginalOrphanPage(AssignmentOrderOriginalStorageStatus::FAILED,[],null);}
    }
    public function acquireDigestLock(string $opaqueIdentity):AssignmentOrderOriginalDigestLock{if(!$this->validIdentity($opaqueIdentity))return new FilesystemAssignmentOrderOriginalDigestLock($opaqueIdentity,null,AssignmentOrderOriginalStorageStatus::FAILED);$this->ensure($this->root.'/locks');$path=$this->root.'/locks/'.hash('sha256',$opaqueIdentity).'.lock';$h=fopen($path,'c+b');if(!is_resource($h))return new FilesystemAssignmentOrderOriginalDigestLock($opaqueIdentity,null,AssignmentOrderOriginalStorageStatus::FAILED);if(!flock($h,LOCK_EX|LOCK_NB)){fclose($h);return new FilesystemAssignmentOrderOriginalDigestLock($opaqueIdentity,null,AssignmentOrderOriginalStorageStatus::LOCKED);}$this->observer->observe(AssignmentOrderOriginalStorageEvent::DIGEST_LOCK_ACQUIRED,$opaqueIdentity);return new FilesystemAssignmentOrderOriginalDigestLock($opaqueIdentity,$h,AssignmentOrderOriginalStorageStatus::OK);}
    public function deleteLocked(AssignmentOrderOriginalDigestLock$lock):AssignmentOrderOriginalStorageStatus{if(!$this->validIdentity($lock->opaqueIdentity()))return AssignmentOrderOriginalStorageStatus::FAILED;$path=str_starts_with($lock->opaqueIdentity(),'stage-')?$this->root.'/stages/'.$lock->opaqueIdentity():$this->root.'/'.$lock->opaqueIdentity();if(!is_file($path))return AssignmentOrderOriginalStorageStatus::ALREADY_PRESENT_VERIFIED;$this->observer->observe(AssignmentOrderOriginalStorageEvent::DELETE_BEGIN,$lock->opaqueIdentity());if(!unlink($path))return AssignmentOrderOriginalStorageStatus::FAILED;$this->observer->observe(AssignmentOrderOriginalStorageEvent::DELETE_DONE,$lock->opaqueIdentity());return AssignmentOrderOriginalStorageStatus::OK;}
    public function inventoryCanonicalJson():string{$stages=[];$finalized=[];foreach(glob($this->root.'/stages/*')?:[]as$path)if(is_file($path))$stages[]=['opaqueIdentity'=>basename($path),'byteSize'=>filesize($path)?:0,'createdAtUtc'=>gmdate('Y-m-d\TH:i:s\Z',filemtime($path)?:0)];foreach(glob($this->root.'/sha256/*/*/*')?:[]as$path)if(is_file($path))$finalized[]=['opaqueIdentity'=>substr($path,strlen($this->root)+1),'sha256'=>basename($path),'byteSize'=>filesize($path)?:0,'finalizedAtUtc'=>gmdate('Y-m-d\TH:i:s\Z',filemtime($path)?:0)];usort($stages,static fn($a,$b)=>[$a['createdAtUtc'],$a['opaqueIdentity']]<=>[$b['createdAtUtc'],$b['opaqueIdentity']]);usort($finalized,static fn($a,$b)=>[$a['finalizedAtUtc'],$a['opaqueIdentity']]<=>[$b['finalizedAtUtc'],$b['opaqueIdentity']]);return json_encode(['schema'=>'aoou-blobs-v1','stages'=>$stages,'finalized'=>$finalized],JSON_THROW_ON_ERROR|JSON_UNESCAPED_SLASHES);}
    private function ensure(string$directory):void{if(!is_dir($directory)&&!mkdir($directory,0700,true)&&!is_dir($directory))throw new \RuntimeException('storage unavailable');}
    private function validIdentity(string$id):bool{return preg_match('/^stage-[0-9a-f]{32}$/D',$id)===1||preg_match('#^sha256/[0-9a-f]{2}/[0-9a-f]{2}/[0-9a-f]{64}$#D',$id)===1;}
}
final class FilesystemAssignmentOrderOriginalPrivateStage implements AssignmentOrderOriginalPrivateStage
{
    private bool$closed=false;public function __construct(private string$root,private string$id,private string$path,private $handle,private AssignmentOrderOriginalStorageObserver$observer,private AssignmentOrderOriginalFaultInjector$faults){}
    public function write(string$chunk):AssignmentOrderOriginalStorageStatus{try{$this->faults->before(AssignmentOrderOriginalFaultPoint::STAGE_WRITE);$this->observer->observe(AssignmentOrderOriginalStorageEvent::STAGE_WRITE,$this->id);return fwrite($this->handle,$chunk)===strlen($chunk)?AssignmentOrderOriginalStorageStatus::OK:AssignmentOrderOriginalStorageStatus::FAILED;}catch(\Throwable){return AssignmentOrderOriginalStorageStatus::FAILED;}}
    public function completedBytesForInspection():string{fflush($this->handle);rewind($this->handle);$bytes=stream_get_contents($this->handle);if(!is_string($bytes))throw new \RuntimeException('stage read');$this->observer->observe(AssignmentOrderOriginalStorageEvent::STAGE_DONE,$this->id);return$bytes;}
    public function finalize(string$sha256,int$byteSize):AssignmentOrderOriginalStorageOutcome{try{$this->faults->before(AssignmentOrderOriginalFaultPoint::PRIVATE_FINALIZE);$identity='sha256/'.substr($sha256,0,2).'/'.substr($sha256,2,2).'/'.$sha256;$target=$this->root.'/'.$identity;$directory=dirname($target);if(!is_dir($directory)&&!mkdir($directory,0700,true)&&!is_dir($directory))throw new \RuntimeException('finalize directory');if(!is_dir($this->root.'/locks')&&!mkdir($this->root.'/locks',0700,true)&&!is_dir($this->root.'/locks'))throw new \RuntimeException('lock directory');$this->observer->observe(AssignmentOrderOriginalStorageEvent::FINALIZE_BEGIN,$identity);$h=fopen($this->root.'/locks/'.hash('sha256',$identity).'.lock','c+b');if(!is_resource($h)||!flock($h,LOCK_EX|LOCK_NB))throw new \RuntimeException('lease');$status=AssignmentOrderOriginalStorageStatus::OK;if(is_file($target)){$existing=file_get_contents($target);if(!is_string($existing)||strlen($existing)!==$byteSize||hash('sha256',$existing)!==$sha256){flock($h,LOCK_UN);fclose($h);throw new \RuntimeException('digest collision');}if(is_file($this->path))unlink($this->path);$status=AssignmentOrderOriginalStorageStatus::ALREADY_PRESENT_VERIFIED;}elseif(!rename($this->path,$target)){flock($h,LOCK_UN);fclose($h);throw new \RuntimeException('finalize rename');}chmod($target,0600);$this->observer->observe(AssignmentOrderOriginalStorageEvent::FINALIZE_DONE,$identity);return new FilesystemAssignmentOrderOriginalStorageOutcome($status,new FilesystemAssignmentOrderOriginalLease(new FilesystemAssignmentOrderOriginalContent($identity,$sha256,$byteSize),$h));}catch(\Throwable){return new FilesystemAssignmentOrderOriginalStorageOutcome(AssignmentOrderOriginalStorageStatus::FAILED,null);}}
    public function abort():AssignmentOrderOriginalStorageStatus{$this->observer->observe(AssignmentOrderOriginalStorageEvent::ABORT_BEGIN,$this->id);if(is_file($this->path)&&!unlink($this->path))return AssignmentOrderOriginalStorageStatus::FAILED;$this->observer->observe(AssignmentOrderOriginalStorageEvent::ABORT_DONE,$this->id);return AssignmentOrderOriginalStorageStatus::OK;}
    public function close():void{if($this->closed)return;$this->closed=true;if(is_resource($this->handle))fclose($this->handle);$this->observer->observe(AssignmentOrderOriginalStorageEvent::STAGE_CLOSE,$this->id);}
}
final readonly class FilesystemAssignmentOrderOriginalContent implements AssignmentOrderOriginalPrivateContent{public function __construct(private string$id,private string$hash,private int$size){}public function opaqueIdentity():string{return$this->id;}public function sha256():string{return$this->hash;}public function byteSize():int{return$this->size;}}
final class FilesystemAssignmentOrderOriginalLease implements AssignmentOrderOriginalPrivateContentLease{private bool$released=false;public function __construct(private AssignmentOrderOriginalPrivateContent$contentValue,private$handle){}public function status():AssignmentOrderOriginalStorageStatus{return AssignmentOrderOriginalStorageStatus::OK;}public function content():?AssignmentOrderOriginalPrivateContent{return$this->contentValue;}public function release():AssignmentOrderOriginalStorageStatus{if($this->released)return AssignmentOrderOriginalStorageStatus::FAILED;$this->released=true;if(!flock($this->handle,LOCK_UN)){return AssignmentOrderOriginalStorageStatus::FAILED;}fclose($this->handle);return AssignmentOrderOriginalStorageStatus::OK;}}
final readonly class FilesystemAssignmentOrderOriginalStorageOutcome implements AssignmentOrderOriginalStorageOutcome{public function __construct(private AssignmentOrderOriginalStorageStatus$statusValue,private ?AssignmentOrderOriginalPrivateContentLease$leaseValue){}public function status():AssignmentOrderOriginalStorageStatus{return$this->statusValue;}public function lease():?AssignmentOrderOriginalPrivateContentLease{return$this->leaseValue;}}
final readonly class FilesystemAssignmentOrderOriginalOrphanPage implements AssignmentOrderOriginalOrphanPage{public function __construct(private AssignmentOrderOriginalStorageStatus$statusValue=AssignmentOrderOriginalStorageStatus::OK,private array$items=[],private ?string$cursor=null){}public function status():AssignmentOrderOriginalStorageStatus{return$this->statusValue;}public function candidates():array{return$this->items;}public function nextCursor():?string{return$this->cursor;}}
final class FilesystemAssignmentOrderOriginalDigestLock implements AssignmentOrderOriginalDigestLock{public function __construct(private string$id,private$handle,private AssignmentOrderOriginalStorageStatus$s){}public function status():AssignmentOrderOriginalStorageStatus{return$this->s;}public function opaqueIdentity():string{return$this->id;}public function release():void{if(is_resource($this->handle)){flock($this->handle,LOCK_UN);fclose($this->handle);$this->handle=null;}}}
