<?php
declare(strict_types=1);
namespace FMonitor2\AssignmentOrderOriginal;

enum AssignmentOrderOriginalMode:string{case INITIAL='initial';case CORRECTION='correction';}
enum AssignmentOrderOriginalStatus:string{case ACCEPTED='accepted';case REPLAYED='replayed';case REJECTED='rejected';case CONFLICT='conflict';case FAILED='failed';}
enum AssignmentOrderOriginalReason:string{case AUTHORIZATION_DENIED='authorization_denied';case INVALID_COMMAND='invalid_command';case ORDER_NOT_FOUND='order_not_found';case COMPOSITION_NOT_CONFIRMED='composition_not_confirmed';case INVALID_COMPOSITION='invalid_composition';case FILE_TOO_LARGE='file_too_large';case NOT_PDF='not_pdf';case INVALID_PDF='invalid_pdf';case UNSAFE_PDF='unsafe_pdf';case FUTURE_DOCUMENT_DATE='future_document_date';case NO_CHANGES='no_changes';case SEMANTIC_COLLISION='semantic_collision';case STALE_REVISION='stale_revision';case TARGET_NOT_FOUND='target_not_found';case TARGET_NOT_CURRENT='target_not_current';case INITIAL_ALREADY_EXISTS='initial_already_exists';case STREAM_FAILURE='stream_failure';case STORAGE_FAILURE='storage_failure';case PERSISTENCE_FAILURE='persistence_failure';case PERSISTENCE_OUTCOME_UNKNOWN='persistence_outcome_unknown';}
enum AssignmentOrderOriginalAuthorizationStatus:string{case ALLOWED='allowed';case DENIED='denied';case UNAVAILABLE='unavailable';}
enum AssignmentOrderCompositionLookupStatus:string{case FOUND='found';case NOT_FOUND='not_found';case UNAVAILABLE='unavailable';case NOT_CURRENT='not_current';}
enum AssignmentOrderOriginalStreamReadStatus:string{case BYTES='bytes';case EOF='eof';case FAILED='failed';}
enum AssignmentOrderOriginalPdfStatus:string{case PASSIVE_PDF='passive_pdf';case INVALID_PDF='invalid_pdf';case UNSAFE_PDF='unsafe_pdf';case INSPECTOR_FAILED='inspector_failed';}
enum AssignmentOrderOriginalStorageStatus:string{case OK='ok';case ALREADY_PRESENT_VERIFIED='already_present_verified';case FAILED='failed';case LOCKED='locked';}
enum AssignmentOrderOriginalCommitStatus:string{case COMMITTED='committed';case CONFLICT='conflict';case ROLLED_BACK='rolled_back';case OUTCOME_UNKNOWN='outcome_unknown';case COMPOSITION_NOT_CURRENT='composition_not_current';}
enum AssignmentOrderOriginalLookupStatus:string{case FOUND='found';case NOT_FOUND='not_found';case UNAVAILABLE='unavailable';}
enum AssignmentOrderOriginalIdStatus:string{case GENERATED='generated';case COLLISION='collision';case EXHAUSTED='exhausted';case UNAVAILABLE='unavailable';}
enum AssignmentOrderOriginalLifecycleEvent:string{case AFTER_REQUEST_MISS_BEFORE_STREAM='after_request_miss_before_stream';case AFTER_FINGERPRINT_MISS_BEFORE_CAS='after_fingerprint_miss_before_cas';case AFTER_PRIVATE_FINALIZE_BEFORE_COMMIT='after_private_finalize_before_commit';case AFTER_COMMIT_BEFORE_RETURN='after_commit_before_return';}
enum AssignmentOrderOriginalStorageEvent:string{case STAGE_BEGIN='stage_begin';case STAGE_WRITE='stage_write';case STAGE_DONE='stage_done';case FINALIZE_BEGIN='finalize_begin';case FINALIZE_DONE='finalize_done';case ABORT_BEGIN='abort_begin';case ABORT_DONE='abort_done';case STAGE_CLOSE='stage_close';case DIGEST_LOCK_ACQUIRED='digest_lock_acquired';case DELETE_BEGIN='delete_begin';case DELETE_DONE='delete_done';}
enum AssignmentOrderOriginalFaultPoint:string{case STREAM_READ='stream_read';case STAGE='stage';case STAGE_WRITE='stage_write';case PRIVATE_FINALIZE='private_finalize';case STAGE_ABORT='stage_abort';case STAGE_CLOSE='stage_close';case STREAM_CLOSE='stream_close';case CONTENT_LEASE_RELEASE='content_lease_release';case COMMIT_BEFORE='commit_before';case COMMIT_BEFORE_RELEASE_FAILURE='commit_before_release_failure';case COMMIT_UNKNOWN_FOUND='commit_unknown_found';case COMMIT_UNKNOWN_NOT_FOUND='commit_unknown_not_found';case COMMIT_UNKNOWN_UNAVAILABLE='commit_unknown_unavailable';case COMMIT_UNKNOWN_FOUND_RELEASE_FAILURE='commit_unknown_found_release_failure';case COMMIT_UNKNOWN_NOT_FOUND_RELEASE_FAILURE='commit_unknown_not_found_release_failure';case COMMIT_UNKNOWN_UNAVAILABLE_RELEASE_FAILURE='commit_unknown_unavailable_release_failure';case RESULT_SERIALIZATION_FAILURE='result_serialization_failure';case RESULT_OVERSIZE='result_oversize';case RESULT_WRITE_FALSE='result_write_false';case RESULT_WRITE_ZERO='result_write_zero';case RESULT_WRITE_SHORT_7='result_write_short_7';case ATTEMPT_AUDIT_COMMIT='attempt_audit_commit';case RESPONSE_DELIVERY='response_delivery';case DIGEST_LOCK='digest_lock';case REQUEST_LOOKUP='request_lookup';case FINGERPRINT_LOOKUP='fingerprint_lookup';case LINEAGE_LOOKUP='lineage_lookup';case ORPHAN_REFERENCE_LOOKUP='orphan_reference_lookup';case ORPHAN_DELETE='orphan_delete';}

final readonly class AssignmentOrderOriginalStreamRead{public function __construct(public AssignmentOrderOriginalStreamReadStatus$status,public string$bytes){} }
interface AssignmentOrderOriginalByteStream{public function read(int$maximumBytes):AssignmentOrderOriginalStreamRead;public function close():void;}
final readonly class AssignmentOrderOriginalUpload{public function __construct(public AssignmentOrderOriginalByteStream$stream,public string$originalFilename,public string$declaredMediaType){} }
final readonly class SubmitAssignmentOrderOriginalCommand{public function __construct(public string$requestId,public AssignmentOrderOriginalMode$mode,public int$installationCaseId,public int$assignmentOrderId,public int$actorUserId,public string$documentDate,public bool$compositionConfirmed,public ?string$rootOriginalId,public ?string$targetRevisionId,public ?string$expectedCurrentRevisionId,public ?string$correctionReason,public AssignmentOrderOriginalUpload$upload){} }
interface AssignmentOrderOriginalResult{public function status():AssignmentOrderOriginalStatus;public function reasonCode():?AssignmentOrderOriginalReason;public function retryable():bool;public function requestId():string;public function rootOriginalId():?string;public function currentRevisionId():?string;public function revisionNumber():?int;public function documentDate():?string;public function sha256():?string;public function byteSize():?int;public function uploadedAt():?string;}
final readonly class AssignmentOrderOriginalResultValue implements AssignmentOrderOriginalResult{public function __construct(private AssignmentOrderOriginalStatus$s,private ?AssignmentOrderOriginalReason$r,private bool$retry,private string$request,private ?string$root=null,private ?string$revision=null,private ?int$number=null,private ?string$date=null,private ?string$sha=null,private ?int$size=null,private ?string$at=null){}public function status():AssignmentOrderOriginalStatus{return$this->s;}public function reasonCode():?AssignmentOrderOriginalReason{return$this->r;}public function retryable():bool{return$this->retry;}public function requestId():string{return$this->request;}public function rootOriginalId():?string{return$this->root;}public function currentRevisionId():?string{return$this->revision;}public function revisionNumber():?int{return$this->number;}public function documentDate():?string{return$this->date;}public function sha256():?string{return$this->sha;}public function byteSize():?int{return$this->size;}public function uploadedAt():?string{return$this->at;}}
interface AssignmentOrderOriginalApplication{public function submitAssignmentOrderOriginal(SubmitAssignmentOrderOriginalCommand$command):AssignmentOrderOriginalResult;}
interface AssignmentOrderOriginalAuthorizer{public function authorize(int$actorUserId,string$exactCapability):AssignmentOrderOriginalAuthorizationStatus;}
final readonly class AssignmentOrderCompositionSnapshot{public function __construct(public AssignmentOrderCompositionLookupStatus$status,public int$installationCaseId,public int$assignmentOrderId,public ?string$identity,public ?string$sha256,public array$installerIds,public ?int$controlEngineerUserId){} }
interface AssignmentOrderCompositionReader{public function find(int$caseId,int$orderId):AssignmentOrderCompositionSnapshot;}
interface AssignmentOrderOriginalClock{public function nowUtc():string;}
final readonly class AssignmentOrderOriginalIdResult{public function __construct(public AssignmentOrderOriginalIdStatus$status,public ?string$id){} }
interface AssignmentOrderOriginalIdSource{public function nextRootId():AssignmentOrderOriginalIdResult;public function nextRevisionId():AssignmentOrderOriginalIdResult;}
final readonly class AssignmentOrderOriginalPdfInspection{private function __construct(public AssignmentOrderOriginalPdfStatus$status){}public static function failed():self{return new self(AssignmentOrderOriginalPdfStatus::INSPECTOR_FAILED);}public static function passive():self{return new self(AssignmentOrderOriginalPdfStatus::PASSIVE_PDF);}public static function invalid():self{return new self(AssignmentOrderOriginalPdfStatus::INVALID_PDF);}public static function unsafe():self{return new self(AssignmentOrderOriginalPdfStatus::UNSAFE_PDF);}}
interface AssignmentOrderOriginalPdfInspector{public function inspect(string$completedBytes):AssignmentOrderOriginalPdfInspection;public function algorithmId():string;}
interface AssignmentOrderOriginalPrivateContent{public function opaqueIdentity():string;public function sha256():string;public function byteSize():int;}
interface AssignmentOrderOriginalPrivateContentLease{public function status():AssignmentOrderOriginalStorageStatus;public function content():?AssignmentOrderOriginalPrivateContent;public function release():AssignmentOrderOriginalStorageStatus;}
interface AssignmentOrderOriginalStorageOutcome{public function status():AssignmentOrderOriginalStorageStatus;public function lease():?AssignmentOrderOriginalPrivateContentLease;}
interface AssignmentOrderOriginalPrivateStage{public function write(string$chunk):AssignmentOrderOriginalStorageStatus;public function completedBytesForInspection():string;public function finalize(string$sha256,int$byteSize):AssignmentOrderOriginalStorageOutcome;public function abort():AssignmentOrderOriginalStorageStatus;public function close():void;}


interface AssignmentOrderOriginalPrivateStorage{public function beginStage():AssignmentOrderOriginalPrivateStage;public function listOrphans(string$cutoffUtc,int$limit,?string$cursor):AssignmentOrderOriginalOrphanPage;public function acquireDigestLock(string$opaqueIdentity):AssignmentOrderOriginalDigestLock;public function deleteLocked(AssignmentOrderOriginalDigestLock$lock):AssignmentOrderOriginalStorageStatus;public function inventoryCanonicalJson():string;}
final readonly class AssignmentOrderOriginalResultLookupValue implements AssignmentOrderOriginalResultLookup{public function __construct(private AssignmentOrderOriginalLookupStatus$s,private ?AssignmentOrderOriginalResult$r=null){}public function status():AssignmentOrderOriginalLookupStatus{return$this->s;}public function result():?AssignmentOrderOriginalResult{return$this->r;}}
interface AssignmentOrderOriginalResultLookup{public function status():AssignmentOrderOriginalLookupStatus;public function result():?AssignmentOrderOriginalResult;}
interface AssignmentOrderOriginalLineageLookup{public function status():AssignmentOrderOriginalLookupStatus;public function rootOriginalId():?string;public function currentRevisionId():?string;public function currentRevisionNumber():?int;public function compositionIdentity():?string;public function compositionSha256():?string;public function containsRevision(string$revisionId):bool;}
interface AssignmentOrderOriginalCurrentEvidenceLookup{public function currentDocumentDate():?string;public function currentPdfSha256():?string;}
interface AssignmentOrderOriginalReferenceLookup{public function status():AssignmentOrderOriginalLookupStatus;public function referenced():?bool;}
final readonly class AssignmentOrderOriginalAcceptedCommit{public function __construct(public string$requestId,public string$fingerprint,public AssignmentOrderOriginalMode$mode,public int$installationCaseId,public int$assignmentOrderId,public int$actorUserId,public string$rootOriginalId,public string$newRevisionId,public int$newRevisionNumber,public ?string$previousRevisionId,public ?string$expectedCurrentRevisionId,public string$compositionIdentity,public string$compositionSha256,public string$documentDate,public string$uploadedAt,public string$pdfSha256,public int$byteSize,public string$privateContentIdentity,public ?string$correctionReason,public string$domainEventType){} }
final readonly class AssignmentOrderOriginalAttemptCommit{public function __construct(public string$requestId,public int$actorUserId,public AssignmentOrderOriginalMode$mode,public int$installationCaseId,public int$assignmentOrderId,public AssignmentOrderOriginalStatus$status,public AssignmentOrderOriginalReason$reason,public bool$retryable,public string$attemptedAt){} }
interface AssignmentOrderOriginalRepository{public function findTerminalRequest(string$requestId):AssignmentOrderOriginalResultLookup;public function findAcceptedFingerprint(string$fingerprint):AssignmentOrderOriginalResultLookup;public function findLineage(string$rootOriginalId):AssignmentOrderOriginalLineageLookup;public function commitAccepted(AssignmentOrderOriginalAcceptedCommit$commit):AssignmentOrderOriginalCommitStatus;public function commitAttempt(AssignmentOrderOriginalAttemptCommit$commit):AssignmentOrderOriginalCommitStatus;public function hasCommittedContent(string$opaqueIdentity):AssignmentOrderOriginalReferenceLookup;public function evidenceCanonicalJson(int$caseId,int$orderId):string;}
interface AssignmentOrderOriginalAssignmentLineageRepository{public function findLineageForAssignmentOrder(int$installationCaseId,int$assignmentOrderId):AssignmentOrderOriginalLineageLookup;}
interface AssignmentOrderOriginalLifecycleObserver{public function observe(AssignmentOrderOriginalLifecycleEvent$event):void;}
interface AssignmentOrderOriginalStorageObserver{public function observe(AssignmentOrderOriginalStorageEvent$event,?string$opaqueIdentity):void;}
interface AssignmentOrderOriginalFaultInjector{public function before(AssignmentOrderOriginalFaultPoint$point):void;}
interface AssignmentOrderOriginalSafeLogObserver{public function record(string$event,array$safeFields):void;}
interface AssignmentOrderOriginalRequestSafeLogObserver extends AssignmentOrderOriginalSafeLogObserver{public function useRequest(string$requestId):void;}
interface AssignmentOrderOriginalResultDeliveryObserver{public function afterCommitBeforeReturn(AssignmentOrderOriginalResult$result):void;}
require_once __DIR__.'/AssignmentOrderOriginalCommandShape.php';
require_once __DIR__.'/AssignmentOrderOriginalPortValues.php';
require_once __DIR__.'/AssignmentOrderOriginalBestEffortSafeLog.php';
require_once __DIR__.'/AssignmentOrderOriginalDataContracts.php';
require_once __DIR__.'/AssignmentOrderOriginalDependencies.php';

require_once __DIR__.'/AssignmentOrderOriginalService.php';
final class AssignmentOrderOriginalVerificationFactory{public static function create(AssignmentOrderOriginalDependencies$d):AssignmentOrderOriginalApplication{return new AssignmentOrderOriginalService($d);}}

final readonly class AssignmentOrderOriginalProductionConfig{public function __construct(public string$privateStorageRoot,public string$tablePrefix,public string$safeLogFile){} }
final class AssignmentOrderOriginalProductionConfigurationUnavailable extends \RuntimeException{public function __construct(){parent::__construct('AssignmentOrderOriginalProductionConfigurationUnavailable');}}
enum AssignmentOrderOriginalPrivateOrphanFixtureKind:string{case ABANDONED_STAGE='abandoned_stage';case FINALIZED_CONTENT='finalized_content';}
final readonly class AssignmentOrderOriginalPrivateOrphanFixtureCommand{public function __construct(public AssignmentOrderOriginalPrivateOrphanFixtureKind$kind,public string$opaqueIdentity,public string$bytes,public string$createdOrFinalizedAtUtc){} }
enum AssignmentOrderOriginalMaintenanceStatus:string{case COMPLETED='completed';case REPLAYED='replayed';case REJECTED='rejected';case PARTIAL='partial';case FAILED='failed';}
enum AssignmentOrderOriginalMaintenanceReason:string{case INVALID_COMMAND='invalid_command';case AUTHORIZATION_DENIED='authorization_denied';case LOCKED='locked';case STORAGE_FAILURE='storage_failure';case PERSISTENCE_FAILURE='persistence_failure';}
final readonly class ReconcileAssignmentOrderOriginalPrivateOrphansCommand{public function __construct(public string$requestId,public string$systemPrincipalId,public string$cutoffUtc,public int$batchLimit,public ?string$cursor){} }
final readonly class AssignmentOrderOriginalMaintenanceAuthorization{public function __construct(public string$systemPrincipalId,public string$capability){} }
require_once __DIR__.'/AssignmentOrderOriginalMaintenanceContracts.php';
final readonly class AssignmentOrderOriginalMaintenanceResultValue implements AssignmentOrderOriginalMaintenanceResult{public function __construct(private AssignmentOrderOriginalMaintenanceStatus$s,private ?AssignmentOrderOriginalMaintenanceReason$r,private bool$retry,private int$scan=0,private int$delete=0,private int$retain=0,private int$fail=0,private ?string$cursor=null){}public function status():AssignmentOrderOriginalMaintenanceStatus{return$this->s;}public function reason():?AssignmentOrderOriginalMaintenanceReason{return$this->r;}public function retryable():bool{return$this->retry;}public function scanned():int{return$this->scan;}public function deleted():int{return$this->delete;}public function retained():int{return$this->retain;}public function failed():int{return$this->fail;}public function nextCursor():?string{return$this->cursor;}}

final class AssignmentOrderOriginalMaintenanceVerificationFactory{public static function create(AssignmentOrderOriginalMaintenanceDependencies $dependencies):AssignmentOrderOriginalMaintenanceApplication{return new AssignmentOrderOriginalMaintenanceOwner($dependencies);}}

final class AssignmentOrderOriginalSequenceIds implements AssignmentOrderOriginalIdSource{private int$ri=0;private int$vi=0;public function __construct(private array$roots,private array$revisions){}public function nextRootId():AssignmentOrderOriginalIdResult{return isset($this->roots[$this->ri])?new AssignmentOrderOriginalIdResult(AssignmentOrderOriginalIdStatus::GENERATED,$this->roots[$this->ri++]):new AssignmentOrderOriginalIdResult(AssignmentOrderOriginalIdStatus::EXHAUSTED,null);}public function nextRevisionId():AssignmentOrderOriginalIdResult{return isset($this->revisions[$this->vi])?new AssignmentOrderOriginalIdResult(AssignmentOrderOriginalIdStatus::GENERATED,$this->revisions[$this->vi++]):new AssignmentOrderOriginalIdResult(AssignmentOrderOriginalIdStatus::EXHAUSTED,null);}}
final readonly class AssignmentOrderOriginalFixedClock implements AssignmentOrderOriginalClock{public function __construct(private string$at){}public function nowUtc():string{return$this->at;}}
final readonly class AssignmentOrderOriginalMariaDbLineage implements AssignmentOrderOriginalCompleteLineageLookup{public function __construct(private AssignmentOrderOriginalLookupStatus$s,private ?array$r=null,private array$ids=[]){}public function status():AssignmentOrderOriginalLookupStatus{return$this->s;}public function rootOriginalId():?string{return$this->r['root_original_id']??null;}public function currentRevisionId():?string{return$this->r['current_revision_id']??null;}public function currentRevisionNumber():?int{return isset($this->r['current_revision_number'])?(int)$this->r['current_revision_number']:null;}public function compositionIdentity():?string{return$this->r['composition_identity']??null;}public function compositionSha256():?string{return$this->r['composition_sha256']??null;}public function containsRevision(string$id):bool{return in_array($id,$this->ids,true);}public function currentDocumentDate():?string{return$this->r['current_document_date']??null;}public function currentPdfSha256():?string{return$this->r['current_pdf_sha256']??null;}public function installationCaseId():?int{return$this->r['installation_case_id']??null;}public function assignmentOrderId():?int{return$this->r['assignment_order_id']??null;}public function revisionIds():array{return$this->ids;}}
final readonly class AssignmentOrderOriginalReferenceValue implements AssignmentOrderOriginalReferenceLookup{public function __construct(private AssignmentOrderOriginalLookupStatus$s,private ?bool$r){}public function status():AssignmentOrderOriginalLookupStatus{return$this->s;}public function referenced():?bool{return$this->r;}}
final class AssignmentOrderOriginalWorkerFaults implements AssignmentOrderOriginalFaultInjector{public function __construct(public ?AssignmentOrderOriginalFaultPoint$target){}public function before(AssignmentOrderOriginalFaultPoint$p):void{$releaseFaults=[AssignmentOrderOriginalFaultPoint::COMMIT_BEFORE_RELEASE_FAILURE,AssignmentOrderOriginalFaultPoint::COMMIT_UNKNOWN_FOUND_RELEASE_FAILURE,AssignmentOrderOriginalFaultPoint::COMMIT_UNKNOWN_NOT_FOUND_RELEASE_FAILURE,AssignmentOrderOriginalFaultPoint::COMMIT_UNKNOWN_UNAVAILABLE_RELEASE_FAILURE];if($this->target===$p||($p===AssignmentOrderOriginalFaultPoint::CONTENT_LEASE_RELEASE&&in_array($this->target,$releaseFaults,true))||($this->target===AssignmentOrderOriginalFaultPoint::STAGE&&$p===AssignmentOrderOriginalFaultPoint::STAGE_WRITE))throw new \RuntimeException('fault');}public function beforeCommit():void{if(in_array($this->target,[AssignmentOrderOriginalFaultPoint::COMMIT_BEFORE,AssignmentOrderOriginalFaultPoint::COMMIT_BEFORE_RELEASE_FAILURE,AssignmentOrderOriginalFaultPoint::COMMIT_UNKNOWN_NOT_FOUND,AssignmentOrderOriginalFaultPoint::COMMIT_UNKNOWN_NOT_FOUND_RELEASE_FAILURE],true))throw new \RuntimeException('commit');}}
final class AssignmentOrderOriginalNoOpLifecycle implements AssignmentOrderOriginalLifecycleObserver{public function observe(AssignmentOrderOriginalLifecycleEvent$e):void{}}
final class AssignmentOrderOriginalNoOpStorageObserver implements AssignmentOrderOriginalStorageObserver{public function observe(AssignmentOrderOriginalStorageEvent$e,?string$i):void{}}
final class AssignmentOrderOriginalNoOpDelivery implements AssignmentOrderOriginalResultDeliveryObserver{public function afterCommitBeforeReturn(AssignmentOrderOriginalResult$r):void{}}
require_once __DIR__.'/AssignmentOrderOriginalFileSafeLog.php';
final class AssignmentOrderOriginalMemoryStream implements AssignmentOrderOriginalByteStream{private int$offset=0;private bool$closed=false;public function __construct(private string$bytes,private ?AssignmentOrderOriginalWorkerFaults$f=null){}public function read(int$max):AssignmentOrderOriginalStreamRead{try{$this->f?->before(AssignmentOrderOriginalFaultPoint::STREAM_READ);}catch(\Throwable){return new AssignmentOrderOriginalStreamRead(AssignmentOrderOriginalStreamReadStatus::FAILED,'');}if($this->offset>=strlen($this->bytes))return new AssignmentOrderOriginalStreamRead(AssignmentOrderOriginalStreamReadStatus::EOF,'');$x=substr($this->bytes,$this->offset,$max);$this->offset+=strlen($x);return new AssignmentOrderOriginalStreamRead(AssignmentOrderOriginalStreamReadStatus::BYTES,$x);}public function close():void{if(!$this->closed){$this->closed=true;$this->f?->before(AssignmentOrderOriginalFaultPoint::STREAM_CLOSE);}}}
final class AssignmentOrderOriginalInjectedInspector implements AssignmentOrderOriginalPdfInspector{public function algorithmId():string{return'fmonitor-passive-pdf-v1';}public function inspect(string$b):AssignmentOrderOriginalPdfInspection{return AssignmentOrderOriginalPdfInspection::passive();}}
require_once __DIR__.'/AssignmentOrderOriginalWorkerBoundary.php';
require_once __DIR__.'/AssignmentOrderOriginalWorkerResultEncoder.php';
final class AssignmentOrderOriginalBarrierLifecycle implements AssignmentOrderOriginalLifecycleObserver{
 public bool $failed=false;
 public function __construct(private $out,private $in,private string $request,private string $event){}
 public function observe(AssignmentOrderOriginalLifecycleEvent $event):void{
  if($event->value!==$this->event)return;
  try{$ready='READY '.$this->request."\n";if(@fwrite($this->out,$ready)!==strlen($ready)||!@fflush($this->out))throw new \RuntimeException();AssignmentOrderOriginalWorkerBoundary::releaseLine($this->in,'RELEASE '.$this->request."\n");}
  catch(\Throwable $error){$this->failed=true;throw $error;}
 }
}

require_once __DIR__.'/AssignmentOrderOriginalWorkerPorts.php';

final class AssignmentOrderOriginalVerificationWorkerBootstrap{
 public static function run(string$configJsonPath,int$commandReadFd,int$barrierReadFd,int$barrierWriteFd,int$resultWriteFd):int{
  ini_set('memory_limit','256M');$handles=[];$db=null;try{
   foreach([$commandReadFd,$barrierReadFd,$barrierWriteFd,$resultWriteFd]as$fd){if($fd<3||$fd>65535)throw new \RuntimeException();$h=@fopen('php://fd/'.$fd,'r+');if(!is_resource($h))throw new \RuntimeException();$st=fstat($h);if(!$st||(($st['mode']&0170000)!==0140000))throw new \RuntimeException();foreach($handles as$old){$os=fstat($old);if($os['dev']===$st['dev']&&$os['ino']===$st['ino'])throw new \RuntimeException();}$handles[]=$h;if(!stream_set_blocking($h,true))throw new \RuntimeException();}
   [$command,$release,$ready,$result]=$handles;$raw=@file_get_contents($configJsonPath);if(!is_string($raw))throw new \RuntimeException();$config=json_decode(trim($raw),true,512,JSON_THROW_ON_ERROR);$keys=['databaseDsn','databaseUser','databasePasswordFile','tablePrefix','privateStorageRoot','safeLogFile','clockUtc','rootIdSequenceCsv','revisionIdSequenceCsv','inspectorMode','faultPoint','barrierEvent'];if(!is_array($config)||array_keys($config)!==$keys)throw new \RuntimeException();$config=new AssignmentOrderOriginalWorkerConfig(...$config);if(!preg_match('/^host=([^;]+);port=([1-9][0-9]*);database=([A-Za-z0-9_]{1,64});charset=utf8mb4$/D',$config->databaseDsn,$m)||(int)$m[2]>65535||!preg_match('/^[A-Za-z0-9_.-]{1,32}$/D',$config->databaseUser)||!preg_match('/^[A-Za-z0-9_]*$/D',$config->tablePrefix))throw new \RuntimeException();foreach(['databasePasswordFile','privateStorageRoot','safeLogFile']as$k)if(!is_string($config->$k)||$config->$k===''||$config->$k[0]!=='/'||in_array('..',explode('/',$config->$k),true))throw new \RuntimeException();if(!in_array($config->inspectorMode,['real','injected_passive'],true)||!in_array($config->barrierEvent,['after_fingerprint_miss_before_cas','after_private_finalize_before_commit'],true))throw new \RuntimeException();$fault=$config->faultPoint===null?null:AssignmentOrderOriginalFaultPoint::tryFrom((string)$config->faultPoint);if($config->faultPoint!==null&&!$fault)throw new \RuntimeException();$roots=self::ids($config->rootIdSequenceCsv,'original');$revisions=self::ids($config->revisionIdSequenceCsv,'revision');
   $freshConfig=new AssignmentOrderOriginalFreshReaderConfig($m[1],(int)$m[2],$m[3],$config->databaseUser,$config->databasePasswordFile,$config->tablePrefix);
   $host=AssignmentOrderOriginalFreshConnection::host($freshConfig);
   if(!AssignmentOrderOriginalDataScalar::utc($config->clockUtc))throw new \RuntimeException();
   AssignmentOrderOriginalEvidenceConfiguration::validate(new AssignmentOrderOriginalEvidenceReaderConfig($m[1],(int)$m[2],$m[3],$config->databaseUser,$config->databasePasswordFile,$config->tablePrefix,$config->privateStorageRoot,$config->safeLogFile));
   AssignmentOrderOriginalSafeLogPath::observe($config->safeLogFile);
   AssignmentOrderOriginalFileStorage::validateRoot($config->privateStorageRoot);
   $line=AssignmentOrderOriginalWorkerBoundary::commandLine($command);$data=json_decode(substr($line,0,-1),true,512,JSON_THROW_ON_ERROR);$top=['requestId','mode','installationCaseId','assignmentOrderId','actorUserId','documentDate','compositionConfirmed','rootOriginalId','targetRevisionId','expectedCurrentRevisionId','correctionReason','upload'];if(!is_array($data)||array_keys($data)!==$top||!is_array($data['upload'])||array_keys($data['upload'])!==['bytesBase64','originalFilename','declaredMediaType'])throw new \RuntimeException();foreach(['requestId','mode','documentDate']as$k)if(!is_string($data[$k]))throw new \RuntimeException();foreach(['installationCaseId','assignmentOrderId','actorUserId']as$k)if(!is_int($data[$k]))throw new \RuntimeException();if(!is_bool($data['compositionConfirmed'])||!is_string($data['upload']['bytesBase64']))throw new \RuntimeException();$faults=new AssignmentOrderOriginalWorkerFaults($fault);$stream=(new AssignmentOrderOriginalBase64StreamFactory($faults))->fromBase64($data['upload']['bytesBase64']);
   $safe=new AssignmentOrderOriginalFileSafeLog($config->safeLogFile,$data['requestId']);$password=AssignmentOrderOriginalFreshConnection::password($freshConfig->databasePasswordFile);$db=new \mysqli($host,$config->databaseUser,$password,$m[3],(int)$m[2]);$db->set_charset('utf8mb4');$clock=new AssignmentOrderOriginalFixedClock($config->clockUtc);
   $repository=new AssignmentOrderOriginalMariaDbRepository($db,$config->tablePrefix,$faults);$storage=new AssignmentOrderOriginalFileStorage($config->privateStorageRoot,new AssignmentOrderOriginalFixedClock($config->clockUtc),$faults);$inspector=$config->inspectorMode==='real'?new FMonitorPassivePdfInspector():new AssignmentOrderOriginalInjectedInspector();$lifecycle=new AssignmentOrderOriginalBarrierLifecycle($ready,$release,$data['requestId'],$config->barrierEvent);$noopStorage=new AssignmentOrderOriginalNoOpStorageObserver();$noopDelivery=new AssignmentOrderOriginalNoOpDelivery();$fresh=new AssignmentOrderOriginalMariaDbFreshTerminalReaderFactory($freshConfig,new AssignmentOrderOriginalWorkerRecoveryObserver($fault));$app=new AssignmentOrderOriginalService(new AssignmentOrderOriginalDependencies(new AssignmentOrderOriginalMariaDbAuthorizer($db,$config->tablePrefix),new AssignmentOrderOriginalMariaDbCompositionReader($db,$config->tablePrefix),$clock,new AssignmentOrderOriginalSequenceIds($roots,$revisions),$inspector,$storage,$repository,$lifecycle,$noopStorage,$faults,$safe,$noopDelivery,$fresh,new AssignmentOrderOriginalMariaDbAttemptAuditWriter($db,$config->tablePrefix)));$mode=AssignmentOrderOriginalMode::tryFrom($data['mode']);if(!$mode)throw new \RuntimeException();$cmd=new SubmitAssignmentOrderOriginalCommand($data['requestId'],$mode,$data['installationCaseId'],$data['assignmentOrderId'],$data['actorUserId'],$data['documentDate'],$data['compositionConfirmed'],$data['rootOriginalId'],$data['targetRevisionId'],$data['expectedCurrentRevisionId'],$data['correctionReason'],new AssignmentOrderOriginalUpload($stream,$data['upload']['originalFilename'],$data['upload']['declaredMediaType']));$out=$app->submitAssignmentOrderOriginal($cmd);if($lifecycle->failed)throw new \RuntimeException();$json=AssignmentOrderOriginalWorkerResultEncoder::encode($out);
   if(in_array($fault,[AssignmentOrderOriginalFaultPoint::RESULT_SERIALIZATION_FAILURE,AssignmentOrderOriginalFaultPoint::RESULT_OVERSIZE,AssignmentOrderOriginalFaultPoint::RESULT_WRITE_FALSE,AssignmentOrderOriginalFaultPoint::RESULT_WRITE_ZERO],true))throw new \RuntimeException();if($fault===AssignmentOrderOriginalFaultPoint::RESULT_WRITE_SHORT_7){@fwrite($result,substr($json,0,7));throw new \RuntimeException();}$written=@fwrite($result,$json);if($written!==strlen($json))throw new \RuntimeException();foreach($handles as$h)fclose($h);$db->close();return 0;
  }catch(\Throwable){foreach($handles as$h)if(is_resource($h))@fclose($h);if($db instanceof \mysqli)try{$db->close();}catch(\Throwable){}fwrite(STDERR,"ASSIGNMENT_ORDER_ORIGINAL_WORKER_FAILED\n");return 70;}
 }
 private static function ids(string$csv,string$kind):array{$x=explode(',',$csv);if($csv===''||count($x)>1024||count($x)!==count(array_unique($x)))throw new \RuntimeException();foreach($x as$id)if(!preg_match('/^'.$kind.'-[0-9]{4}$/D',$id))throw new \RuntimeException();return$x;}

}
require_once __DIR__.'/AssignmentOrderOriginalFileStorage.php';
require_once __DIR__.'/MariaDbAssignmentOrderOriginalEvidence.php';
require_once __DIR__.'/MariaDbMaintenanceService.php';
require_once __DIR__.'/MariaDbOriginalFreshTerminalReaderFactory.php';
require_once __DIR__.'/AssignmentOrderOriginalWorkerRecoveryObserver.php';

require_once __DIR__.'/MariaDbOriginalAttemptAuditWriter.php';

require_once __DIR__.'/AssignmentOrderOriginalMaintenanceOwner.php';
require_once __DIR__.'/ProductionAssignmentOrderOriginalMaintenanceFactory.php';
