<?php
declare(strict_types=1);
namespace FMonitor2\AssignmentOrderOriginal;

final class AssignmentOrderOriginalMaintenanceService
{
    public function __construct(private \mysqli$db,private AssignmentOrderOriginalProductionConfig$config,private AssignmentOrderOriginalMaintenanceAuthorization$auth,private AssignmentOrderOriginalClock$clock,private AssignmentOrderOriginalFaultInjector$faults){}
    public function reconcileAssignmentOrderOriginalPrivateOrphans(ReconcileAssignmentOrderOriginalPrivateOrphansCommand$c):AssignmentOrderOriginalMaintenanceResultValue
    {
        $p=$this->config->tablePrefix;
        if(preg_match('/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/D',$c->requestId)!==1)return new AssignmentOrderOriginalMaintenanceResultValue(AssignmentOrderOriginalMaintenanceStatus::REJECTED,AssignmentOrderOriginalMaintenanceReason::INVALID_COMMAND,false);
        if($this->auth->systemPrincipalId!=='test-maintenance-01'||$this->auth->systemPrincipalId!==$c->systemPrincipalId||$this->auth->capability!=='assignment_order.original.storage.reconcile')return$this->persist($c,AssignmentOrderOriginalMaintenanceStatus::REJECTED,AssignmentOrderOriginalMaintenanceReason::AUTHORIZATION_DENIED,false,0,0,0,0,null);
        $id=$this->db->real_escape_string($c->requestId);$existing=$this->db->query("SELECT * FROM `{$p}fm2_assignment_order_original_maintenance_requests` WHERE request_id='{$id}'")->fetch_assoc();if($existing)return new AssignmentOrderOriginalMaintenanceResultValue(AssignmentOrderOriginalMaintenanceStatus::REPLAYED,$existing['reason_code']?AssignmentOrderOriginalMaintenanceReason::from($existing['reason_code']):null,(bool)$existing['retryable'],(int)$existing['scanned'],(int)$existing['deleted'],(int)$existing['retained'],(int)$existing['failed'],$existing['next_cursor']);
        $now=$this->clock->nowUtc();if($c->batchLimit<1||$c->batchLimit>1000||strtotime($c->cutoffUtc)>strtotime($now)-3600||($c->cursor!==null&&!$this->decodeCursor($c->cursor)))return$this->persist($c,AssignmentOrderOriginalMaintenanceStatus::REJECTED,AssignmentOrderOriginalMaintenanceReason::INVALID_COMMAND,false,0,0,0,0,null);
        $state=AssignmentOrderOriginalFileState::read($this->config->privateStorageRoot);$all=[];foreach($state['finalized']as$x)if($x['finalizedAtUtc']<=$c->cutoffUtc)$all[]=['kind'=>'finalized','at'=>$x['finalizedAtUtc'],'id'=>$x['opaqueIdentity']];foreach($state['stages']as$x)if($x['createdAtUtc']<=$c->cutoffUtc)$all[]=['kind'=>'stage','at'=>$x['createdAtUtc'],'id'=>$x['opaqueIdentity']];usort($all,fn($a,$b)=>[$a['at'],$a['id']]<=>[$b['at'],$b['id']]);if($c->cursor){$after=$this->decodeCursor($c->cursor);$all=array_values(array_filter($all,fn($x)=>[$x['at'],$x['id']]>[$after['at'],$after['id']]));}$more=count($all)>$c->batchLimit;$items=array_slice($all,0,$c->batchLimit);$deleted=$retained=$failed=$locked=0;
        foreach($items as$x){$lock=fopen($this->config->privateStorageRoot.'/.lock-'.hash('sha256',$x['id']),'c+');try{try{$this->faults->before(AssignmentOrderOriginalFaultPoint::DIGEST_LOCK);}catch(\Throwable){$retained++;$locked++;fclose($lock);continue;}if(!flock($lock,LOCK_EX|LOCK_NB)){$retained++;$locked++;fclose($lock);continue;}if($x['kind']==='finalized'){try{$this->faults->before(AssignmentOrderOriginalFaultPoint::ORPHAN_REFERENCE_LOOKUP);}catch(\Throwable){throw new \RuntimeException('reference');}$escaped=$this->db->real_escape_string($x['id']);$n=(int)$this->db->query("SELECT COUNT(*) n FROM `{$p}fm2_assignment_order_original_revisions` WHERE private_content_identity='{$escaped}'")->fetch_assoc()['n'];if($n>0){$retained++;flock($lock,LOCK_UN);fclose($lock);continue;}}$this->faults->before(AssignmentOrderOriginalFaultPoint::ORPHAN_DELETE);$paths=[$this->config->privateStorageRoot.'/fixture-'.hash('sha256',$x['id']).($x['kind']==='finalized'?'.pdf':'.stage')];if($x['kind']==='finalized'&&str_starts_with($x['id'],'content-sha256-'))$paths[]=$this->config->privateStorageRoot.'/content-'.substr($x['id'],15).'.pdf';if($x['kind']==='stage')$paths[]=$this->config->privateStorageRoot.'/.stage-'.$x['id'];foreach($paths as$file)if(is_file($file)&&!is_link($file)&&!@unlink($file))throw new \RuntimeException('delete');AssignmentOrderOriginalFileState::mutate($this->config->privateStorageRoot,function(&$s)use($x){$key=$x['kind']==='finalized'?'finalized':'stages';$s[$key]=array_values(array_filter($s[$key],fn($v)=>$v['opaqueIdentity']!==$x['id']));});$deleted++;flock($lock,LOCK_UN);fclose($lock);}catch(\Throwable){$failed++;if(is_resource($lock)){@flock($lock,LOCK_UN);@fclose($lock);}}}
        $scan=count($items);$cursor=$more&&$items?$this->encodeCursor($items[array_key_last($items)]):null;if($failed||$locked){$reason=$failed?AssignmentOrderOriginalMaintenanceReason::STORAGE_FAILURE:AssignmentOrderOriginalMaintenanceReason::LOCKED;return$this->persist($c,AssignmentOrderOriginalMaintenanceStatus::PARTIAL,$reason,true,$scan,$deleted,$retained,$failed,$cursor);}return$this->persist($c,AssignmentOrderOriginalMaintenanceStatus::COMPLETED,null,false,$scan,$deleted,$retained,$failed,$cursor);
    }
    private function persist($c,$status,$reason,$retry,$scan,$deleted,$retained,$failed,$cursor):AssignmentOrderOriginalMaintenanceResultValue{$p=$this->config->tablePrefix;$q=fn(?string$x)=>$x===null?'NULL':"'".$this->db->real_escape_string($x)."'";$at=str_replace(['T','Z'],[' ',''],$this->clock->nowUtc()).'.000000';try{$this->db->begin_transaction();$this->db->query("INSERT INTO `{$p}fm2_assignment_order_original_maintenance_requests` VALUES(".$q($c->requestId).','.$q($c->systemPrincipalId).','.$q($status->value).','.$q($reason?->value).','.($retry?1:0).",{$scan},{$deleted},{$retained},{$failed},".$q($cursor).','.$q($at).')');$this->db->query("INSERT INTO `{$p}fm2_assignment_order_original_maintenance_audits`(request_id,system_principal_id,status,reason_code,retryable,scanned,deleted,retained,failed,attempted_at_utc)VALUES(".$q($c->requestId).','.$q($c->systemPrincipalId).','.$q($status->value).','.$q($reason?->value).','.($retry?1:0).",{$scan},{$deleted},{$retained},{$failed},".$q($at).')');$this->db->commit();return new AssignmentOrderOriginalMaintenanceResultValue($status,$reason,$retry,$scan,$deleted,$retained,$failed,$cursor);}catch(\Throwable){try{$this->db->rollback();}catch(\Throwable){}return new AssignmentOrderOriginalMaintenanceResultValue(AssignmentOrderOriginalMaintenanceStatus::FAILED,AssignmentOrderOriginalMaintenanceReason::PERSISTENCE_FAILURE,true);}}
    private function encodeCursor(array$x):string{return rtrim(strtr(base64_encode(json_encode(['v'=>1,'at'=>$x['at'],'id'=>$x['id']],JSON_THROW_ON_ERROR|JSON_UNESCAPED_SLASHES)),'+/','-_'),'=');}
    private function decodeCursor(string$c):?array{if(str_contains($c,'=')||preg_match('/^[A-Za-z0-9_-]{59,484}$/D',$c)!==1)return null;$pad=str_repeat('=',(4-strlen($c)%4)%4);$raw=base64_decode(strtr($c,'-_','+/').$pad,true);if(!is_string($raw))return null;$x=json_decode($raw,true);if(!is_array($x)||array_keys($x)!==['v','at','id']||$x['v']!==1)return null;return rtrim(strtr(base64_encode(json_encode($x,JSON_THROW_ON_ERROR|JSON_UNESCAPED_SLASHES)),'+/','-_'),'=')===$c?$x:null;}
}
