<?php
declare(strict_types=1);
namespace FMonitor2\AssignmentOrderOriginal;

final readonly class AssignmentOrderOriginalEvidenceReaderConfig{public function __construct(public string$host,public int$port,public string$database,public string$user,public string$passwordFile,public string$tablePrefix,public string$privateStorageRoot,public string$safeLogFile){} }
final class AssignmentOrderOriginalEvidenceUnavailable extends \RuntimeException{public function __construct(){parent::__construct('AssignmentOrderOriginalEvidenceUnavailable');}}
final class AssignmentOrderOriginalEvidenceReader{
 private \mysqli$db;private bool$closed=false;
 public function __construct(private AssignmentOrderOriginalEvidenceReaderConfig$c){$pw=rtrim((string)file_get_contents($c->passwordFile),"\r\n");$this->db=new \mysqli($c->host,$c->user,$pw,$c->database,$c->port);$this->db->set_charset('utf8mb4');}
 private function rows(string$sql):array{return$this->db->query($sql)->fetch_all(MYSQLI_ASSOC);}
 private function j(array$x):string{return json_encode($x,JSON_THROW_ON_ERROR|JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);}
 public function domainCanonicalJson(int$case,int$order):string{$p=$this->c->tablePrefix;$roots=[];foreach($this->rows("SELECT * FROM `{$p}fm2_assignment_order_original_roots` WHERE installation_case_id={$case} AND assignment_order_id={$order} ORDER BY BINARY root_original_id")as$r){$revs=[];foreach($this->rows("SELECT * FROM `{$p}fm2_assignment_order_original_revisions` WHERE root_original_id='".$this->db->real_escape_string($r['root_original_id'])."' ORDER BY revision_number")as$v)$revs[]=['revisionId'=>$v['revision_id'],'revisionNumber'=>(int)$v['revision_number'],'previousRevisionId'=>$v['previous_revision_id'],'documentDate'=>$v['document_date'],'uploadedAt'=>self::utc($v['uploaded_at_utc']),'actorUserId'=>(int)$v['actor_user_id'],'pdfSha256'=>$v['pdf_sha256'],'byteSize'=>(int)$v['byte_size'],'privateContentIdentity'=>$v['private_content_identity'],'correctionReason'=>$v['correction_reason']];$roots[]=['rootOriginalId'=>$r['root_original_id'],'currentRevisionId'=>$r['current_revision_id'],'compositionIdentity'=>$r['composition_identity'],'compositionSha256'=>$r['composition_sha256'],'revisions'=>$revs];}return$this->j(['schema'=>'aoou-evidence-v1','caseId'=>$case,'orderId'=>$order,'roots'=>$roots]);}
 public function requestsCanonicalJson():string{$p=$this->c->tablePrefix;$items=[];foreach($this->rows("SELECT * FROM `{$p}fm2_assignment_order_original_requests` ORDER BY BINARY request_id")as$r)$items[]=['byteSize'=>$r['byte_size']===null?null:(int)$r['byte_size'],'currentRevisionId'=>$r['current_revision_id'],'documentDate'=>$r['document_date'],'reasonCode'=>$r['reason_code'],'requestId'=>$r['request_id'],'retryable'=>(bool)$r['retryable'],'revisionNumber'=>$r['revision_number']===null?null:(int)$r['revision_number'],'rootOriginalId'=>$r['root_original_id'],'sha256'=>$r['sha256'],'status'=>$r['status'],'uploadedAt'=>$r['uploaded_at_utc']===null?null:self::utc($r['uploaded_at_utc'])];return$this->j($items===[]?['schema'=>'aoou-requests-v1','items'=>[]]:['items'=>$items,'schema'=>'aoou-requests-v1']);}
 public function fingerprintsCanonicalJson():string{$p=$this->c->tablePrefix;$items=[];foreach($this->rows("SELECT operation_fingerprint,request_id,root_original_id,revision_id FROM `{$p}fm2_assignment_order_original_revisions` ORDER BY revision_number")as$r)$items[]=['currentRevisionId'=>$r['revision_id'],'fingerprint'=>$r['operation_fingerprint'],'requestId'=>$r['request_id'],'rootOriginalId'=>$r['root_original_id']];return$this->j($items===[]?['schema'=>'aoou-fingerprints-v1','items'=>[]]:['items'=>$items,'schema'=>'aoou-fingerprints-v1']);}
 public function eventsCanonicalJson():string{$p=$this->c->tablePrefix;$items=[];foreach($this->rows("SELECT * FROM `{$p}fm2_assignment_order_original_events` ORDER BY event_id")as$r)$items[]=['actorUserId'=>(int)$r['actor_user_id'],'caseId'=>(int)$r['installation_case_id'],'eventId'=>(int)$r['event_id'],'eventType'=>$r['event_type'],'occurredAt'=>self::utc($r['occurred_at_utc']),'orderId'=>(int)$r['assignment_order_id'],'revisionId'=>$r['revision_id'],'rootOriginalId'=>$r['root_original_id']];return$this->j($items===[]?['schema'=>'aoou-events-v1','items'=>[]]:['items'=>$items,'schema'=>'aoou-events-v1']);}
 public function safeAuditsCanonicalJson():string{$p=$this->c->tablePrefix;$items=[];foreach($this->rows("SELECT * FROM `{$p}fm2_assignment_order_original_audits` ORDER BY audit_id")as$r)$items[]=['actorIdentity'=>$r['actor_identity'],'attemptedAt'=>self::utc($r['attempted_at_utc']),'auditId'=>(int)$r['audit_id'],'caseId'=>(int)$r['installation_case_id'],'mode'=>$r['mode'],'orderId'=>(int)$r['assignment_order_id'],'reasonCode'=>$r['reason_code'],'requestId'=>$r['request_id'],'status'=>$r['status']];return$this->j($items===[]?['schema'=>'aoou-audits-v1','items'=>[]]:['items'=>$items,'schema'=>'aoou-audits-v1']);}
 public function maintenanceRequestsCanonicalJson():string{return$this->maintenance(false);}
 public function maintenanceAuditsCanonicalJson():string{return$this->maintenance(true);}
 private function maintenance(bool$audit):string{$p=$this->c->tablePrefix;$t=$p.'fm2_assignment_order_original_maintenance_'.($audit?'audits':'requests');$items=[];foreach($this->rows("SELECT * FROM `{$t}` ORDER BY ".($audit?'audit_id':'BINARY request_id'))as$r){$x=['attemptedAt'=>self::utc($r['attempted_at_utc'])];if($audit)$x['auditId']=(int)$r['audit_id'];$x+=['deleted'=>(int)$r['deleted'],'failed'=>(int)$r['failed']];if(!$audit)$x['nextCursor']=$r['next_cursor'];$x+=['reasonCode'=>$r['reason_code'],'requestId'=>$r['request_id'],'retained'=>(int)$r['retained'],'retryable'=>(bool)$r['retryable'],'scanned'=>(int)$r['scanned'],'status'=>$r['status'],'systemPrincipalId'=>$r['system_principal_id']];$items[]=$x;}return$this->j(['items'=>$items,'schema'=>'aoou-maintenance-'.($audit?'audits':'requests').'-v1']);}
 public function privateBlobsCanonicalJson():string{$f=$this->c->privateStorageRoot.'/.aoou-state.json';if(!is_file($f))return'{"schema":"aoou-blobs-v1","stages":[],"finalized":[]}';$x=json_decode((string)file_get_contents($f),true,512,JSON_THROW_ON_ERROR);usort($x['stages'],fn($a,$b)=>strcmp($a['opaqueIdentity'],$b['opaqueIdentity']));usort($x['finalized'],fn($a,$b)=>strcmp($a['opaqueIdentity'],$b['opaqueIdentity']));return$this->j(['finalized'=>$x['finalized'],'schema'=>'aoou-blobs-v1','stages'=>$x['stages']]);}
 public function safeLogsCanonicalJson():string{$items=[];foreach(file($this->c->safeLogFile,FILE_IGNORE_NEW_LINES)?:[]as$line)if($line!=='')$items[]=json_decode($line,true,512,JSON_THROW_ON_ERROR);$p=$this->c->tablePrefix;$used=is_file($this->c->privateStorageRoot.'/.aoou-state.json')||(int)($this->rows("SELECT COUNT(*) n FROM `{$p}fm2_assignment_order_original_requests`")[0]['n']??0)>0;return$this->j($items===[]&&!$used?['schema'=>'aoou-logs-v1','items'=>[]]:['items'=>$items,'schema'=>'aoou-logs-v1']);}
 public function unchangedProcessCanonicalJson(int$case,int$order):string{$p=$this->c->tablePrefix;$o=$this->rows("SELECT id,installation_case_id,version_no,control_engineer_user_id FROM `{$p}fm2_assignment_orders` WHERE id={$order} AND installation_case_id={$case}")[0]??null;if(!$o)throw new AssignmentOrderOriginalEvidenceUnavailable();$ids=array_map(fn($r)=>(int)$r['installer_tab_id'],$this->rows("SELECT installer_tab_id FROM `{$p}fm2_order_installers` WHERE assignment_order_id={$order} AND change_action IN('assign','retain') ORDER BY installer_tab_id"));$composition=$this->j(['caseId'=>$case,'compositionIdentity'=>'composition-'.$order.'-v'.$o['version_no'],'engineerUserId'=>(int)$o['control_engineer_user_id'],'installers'=>$ids,'orderId'=>$order]);$c=$this->rows("SELECT process_state,actual_start_date,opened_at,opened_by_user_id FROM `{$p}fm2_installation_cases` WHERE id={$case}")[0];$caseJ=$this->j(['actualStartDate'=>$c['actual_start_date'],'caseId'=>$case,'processState'=>$c['process_state']]);$openJ=$this->j(['actualStartDate'=>$c['actual_start_date'],'openedAt'=>$c['opened_at']===null?null:self::utc($c['opened_at']),'openedByUserId'=>$c['opened_by_user_id']===null?null:(int)$c['opened_by_user_id']]);$tasks=[];foreach($this->rows("SELECT id,task_type,assignee_role,status FROM `{$p}fm2_process_tasks` WHERE installation_case_id={$case} ORDER BY id")as$r)$tasks[]=['assigneeRole'=>$r['assignee_role'],'status'=>$r['status'],'taskId'=>(int)$r['id'],'taskType'=>$r['task_type']];$check=$this->j(['items'=>[['availability'=>($c['process_state']==='working'&&$c['actual_start_date']&&$c['opened_at']&&$c['opened_by_user_id'])?'available':'blocked_until_opening','checklistIdentity'=>'installation-case-'.$case]]]);$dec=[];foreach($this->rows("SELECT id,process_state FROM `{$p}fm2_installation_cases` WHERE id<>{$case} ORDER BY id")as$r)$dec[]=['caseId'=>(int)$r['id'],'marker'=>$r['process_state']];return$this->j(['schema'=>'aoou-process-v1','orderCompositionSha256'=>hash('sha256',$composition),'caseSha256'=>hash('sha256',$caseJ),'openingSha256'=>hash('sha256',$openJ),'tasksSha256'=>hash('sha256',$this->j(['items'=>$tasks])),'checklistSha256'=>hash('sha256',$check),'decoySha256'=>hash('sha256',$this->j(['items'=>$dec]))]);}
 public function close():void{if(!$this->closed){$this->db->close();$this->closed=true;$f=$this->c->privateStorageRoot.'/.aoou-state.json';if(is_file($f)){try{$s=json_decode((string)file_get_contents($f),true,512,JSON_THROW_ON_ERROR);if(($s['stages']??[])===[]&&($s['finalized']??[])===[]){@unlink($f);@unlink($this->c->privateStorageRoot.'/.aoou-state.lock');foreach(glob($this->c->privateStorageRoot.'/.lock-*')?:[]as$l)@unlink($l);}}catch(\Throwable){}}}}
 public static function utc(string$s):string{return str_replace(' ','T',substr($s,0,19)).'Z';}
}
final class AssignmentOrderOriginalEvidenceReaderFactory{public static function create(AssignmentOrderOriginalEvidenceReaderConfig$c):AssignmentOrderOriginalEvidenceReader{return new AssignmentOrderOriginalEvidenceReader($c);}}
final class AssignmentOrderOriginalMariaDbAuthorizer implements AssignmentOrderOriginalAuthorizer{public function __construct(private \mysqli$db,private string$p){}public function authorize(int$actor,string$cap):AssignmentOrderOriginalAuthorizationStatus{try{$q="SELECT COUNT(*) n FROM `{$this->p}fm2_pilot_users` u JOIN `{$this->p}fm2_pilot_user_roles` ur ON ur.user_id=u.user_id JOIN `{$this->p}fm2_pilot_roles` r ON r.role_id=ur.role_id JOIN `{$this->p}fm2_process_user_capabilities` c ON c.user_id=u.user_id WHERE u.user_id={$actor} AND u.status=1 AND u.activation_state='active' AND r.status=1 AND c.capability='".$this->db->real_escape_string($cap)."'";return(int)$this->db->query($q)->fetch_assoc()['n']>0?AssignmentOrderOriginalAuthorizationStatus::ALLOWED:AssignmentOrderOriginalAuthorizationStatus::DENIED;}catch(\Throwable){return AssignmentOrderOriginalAuthorizationStatus::UNAVAILABLE;}}}
final class AssignmentOrderOriginalMariaDbCompositionReader implements AssignmentOrderCompositionReader{public function __construct(private \mysqli$db,private string$p){}public function find(int$case,int$order):AssignmentOrderCompositionSnapshot{try{$r=$this->db->query("SELECT id,installation_case_id,version_no,control_engineer_user_id,order_date FROM `{$this->p}fm2_assignment_orders` WHERE id={$order}")->fetch_assoc();if(!$r||(int)$r['installation_case_id']!==$case)return new AssignmentOrderCompositionSnapshot(AssignmentOrderCompositionLookupStatus::NOT_FOUND,$case,$order,null,null,[],null);$ids=[];$seen=[];foreach($this->db->query("SELECT * FROM `{$this->p}fm2_order_installers` WHERE assignment_order_id={$order} ORDER BY installer_tab_id")->fetch_all(MYSQLI_ASSOC)as$x){$id=(int)$x['installer_tab_id'];$action=(string)$x['change_action'];$from=$x['valid_from'];$to=$x['valid_to'];if(!in_array($action,['assign','retain','release'],true)||$id<1||isset($seen[$id])||!is_string($from)||$from>$r['order_date']||($to!==null&&(!is_string($to)||$to<$from))||($action==='release'&&($to===null||$to>$r['order_date'])))return new AssignmentOrderCompositionSnapshot(AssignmentOrderCompositionLookupStatus::FOUND,$case,$order,null,null,[],null);$seen[$id]=true;if(in_array($action,['assign','retain'],true)&&($to===null||$to>=$r['order_date']))$ids[]=$id;}sort($ids,SORT_NUMERIC);if($ids===[])return new AssignmentOrderCompositionSnapshot(AssignmentOrderCompositionLookupStatus::FOUND,$case,$order,null,null,[],null);$identity='composition-'.$order.'-v'.$r['version_no'];$json=json_encode(['caseId'=>$case,'compositionIdentity'=>$identity,'engineerUserId'=>(int)$r['control_engineer_user_id'],'installers'=>$ids,'orderId'=>$order],JSON_THROW_ON_ERROR|JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);return new AssignmentOrderCompositionSnapshot(AssignmentOrderCompositionLookupStatus::FOUND,$case,$order,$identity,hash('sha256',$json),$ids,(int)$r['control_engineer_user_id']);}catch(\Throwable){return new AssignmentOrderCompositionSnapshot(AssignmentOrderCompositionLookupStatus::UNAVAILABLE,$case,$order,null,null,[],null);}}}
