<?php
// OTIZ-EXCEL-INPUTS-001 — root authored real Yii facts + public calculation reader.
declare(strict_types=1);
require dirname(__DIR__).'/bootstrap.php';require dirname(__DIR__).'/Yii2/InspectionFixture.php';
use FMonitor2\Otiz\{MariaDbNativePremiumInputs,PremiumCalculationV2};
use FMonitor2\DeadlineTransferCertificate\DeadlineTransferCertificates as Certificates;
use FMonitor2\Tests\Support\{DeadlineCertificateFixture,AssignmentOrderOriginalPdfCorpus as Pdf};
function inputStream(string $bytes):Closure{$done=false;return static function()use($bytes,&$done):?string{if($done)return null;$done=true;return$bytes;};}
function inputBlocked(array $row,string $code):void{assertSameValue(4512,$row['id'],'blocked native row remains visible');assertSameValue(true,in_array($code,array_column($row['issues'],'code'),true),'exact blocker '.$code);assertSameValue(null,$row['operands'],'blocked input cannot be calculated');}
$f=null;
try{
 $f=new InspectionFixture(dirname(__DIR__,2));$f->open();$h=$f->http;$db=$h->db;$p=$h->p;
 $payload=json_decode($db->query("SELECT payload_json FROM {$p}fm2_pilot_object_details WHERE object_id=4512")->fetch_column(),true,flags:JSON_THROW_ON_ERROR);$payload['fields']['pitmaterial']=['raw'=>'41','display'=>'41','provenance'=>['sourceTable'=>'fm_maintable','sourceColumn'=>'pitmaterial','legacyCode'=>'41','legacyName'=>'железобетон']];$payload['fields']['lift_type']=['raw'=>'1','display'=>'пассажирский'];$json=json_encode($payload,JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR);$db->prepare("UPDATE {$p}fm2_pilot_object_details SET payload_json=?,content_sha256=? WHERE object_id=4512")->execute([$json,hash('sha256',$json)]);
 $db->query("UPDATE {$p}fm_maintable SET plan_finish_date='2026-09-05',workdateendadjusted='2099-01-01' WHERE id=4512");
 $page=$f->page();$csrf=InspectionFixture::csrf($page);$op=InspectionFixture::operation();$op['deviceTime']='2026-09-14T10:00:00+03:00';$result=InspectionFixture::result($f->send($op,$csrf),200,'accepted');
 // Server time is a controlled report-date fixture: HTTP remains the sole command writer.
 $db->query("UPDATE {$p}fm2_checklist_operations SET server_received_at='2026-09-14T11:00:00+03:00'");
 assertSameValue(0,(int)$db->query("SELECT COUNT(*) FROM {$p}fm2_assignment_orders")->fetch_column(),'real native path has no registered legacy orders');
 $clock=static fn():string=>'2026-09-14T12:00:00Z';$reader=new MariaDbNativePremiumInputs($db,$p,null,$clock);$rows=$reader->forDate('2026-09-14');assertSameValue(1,count($rows),'RED_ASSERTION native Yii case participates without registered legacy order');$row=$rows[0];
 assertSameValue([4512,6101,200,65000000,10000,'2026-09-05',null,[]],[$row['id'],$row['caseId'],$row['progress'],$row['premium'],$row['shaft'],$row['deadline'],$row['pto'],$row['issues']],'real native operands');
 $code72=$payload;$code72['fields']['pitmaterial']=['raw'=>'72','display'=>'72','provenance'=>['sourceTable'=>'fm_maintable','sourceColumn'=>'pitmaterial','legacyCode'=>'72','legacyName'=>'Железобетон и металл']];$code72Json=json_encode($code72,JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR);$code72Hash=hash('sha256',$code72Json);$db->prepare("UPDATE {$p}fm2_pilot_object_details SET payload_json=?,content_sha256=? WHERE object_id=4512")->execute([$code72Json,$code72Hash]);$code72Before=$h->facts();$mapped72=$reader->forDate('2026-09-14')[0];assertSameValue([10000,10000],[$mapped72['shaft'],$mapped72['operands']['shaftBp']['value']??null],'INTENDED_RED: premium inputs resolve legacy material 72');assertSameValue(['fm2_pilot_object_details/4512',$code72Hash],[$mapped72['operands']['shaftBp']['source']['locator']??null,$mapped72['operands']['shaftBp']['source']['contentSha256']??null],'premium input retains exact card provenance 72');assertSameValue($code72Before,$h->facts(),'premium input read72 preserves immutable facts');$db->prepare("UPDATE {$p}fm2_pilot_object_details SET payload_json=?,content_sha256=? WHERE object_id=4512")->execute([$json,hash('sha256',$json)]);
 foreach([['86',11500],['112',11500],['123',12500]]as[$legacyCode,$expectedShaft]){$card=$payload;$card['fields']['pitmaterial']=['raw'=>$legacyCode,'display'=>$legacyCode,'provenance'=>['sourceTable'=>'fm_maintable','sourceColumn'=>'pitmaterial','legacyCode'=>$legacyCode]];$cardJson=json_encode($card,JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR);$cardHash=hash('sha256',$cardJson);$db->prepare("UPDATE {$p}fm2_pilot_object_details SET payload_json=?,content_sha256=? WHERE object_id=4512")->execute([$cardJson,$cardHash]);$codeBefore=$h->facts();$mapped=$reader->forDate('2026-09-14')[0];assertSameValue([$expectedShaft,$expectedShaft],[$mapped['shaft'],$mapped['operands']['shaftBp']['value']??null],'INTENDED_RED: premium inputs resolve legacy material '.$legacyCode);assertSameValue(['fm2_pilot_object_details/4512',$cardHash],[$mapped['operands']['shaftBp']['source']['locator']??null,$mapped['operands']['shaftBp']['source']['contentSha256']??null],'premium input retains exact card provenance '.$legacyCode);assertSameValue($codeBefore,$h->facts(),'premium input read '.$legacyCode.' preserves immutable facts');}
 $unknown=$payload;$unknown['fields']['pitmaterial']=['raw'=>'999','display'=>'999'];$unknownJson=json_encode($unknown,JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR);$db->prepare("UPDATE {$p}fm2_pilot_object_details SET payload_json=?,content_sha256=? WHERE object_id=4512")->execute([$unknownJson,hash('sha256',$unknownJson)]);$unknownBefore=$h->facts();inputBlocked($reader->forDate('2026-09-14')[0],'SHAFT_COEFFICIENT_UNRESOLVED');assertSameValue($unknownBefore,$h->facts(),'unknown premium material read preserves immutable facts');$db->prepare("UPDATE {$p}fm2_pilot_object_details SET payload_json=?,content_sha256=? WHERE object_id=4512")->execute([$json,hash('sha256',$json)]);$row=$reader->forDate('2026-09-14')[0];
 assertSameValue(['7001','7002'],array_column($row['team'],'tab'),'applied native crew');assertSameValue([100,100],array_column($row['team'],'contribution'),'exact contribution conservation');
 $proof=$row['sourceEvidence'];assertSameValue(['capturedAt','originalDeadline','certificate','completion','composition','progress'],array_keys($proof),'exact source evidence envelope');assertSameValue('2026-09-14T12:00:00Z',$proof['capturedAt'],'execution capture time');assertSameValue('fm_maintable/4512/plan_finish_date',$proof['originalDeadline']['source']['locator'],'raw plan provenance');$canonical=['objectId'=>4512,'planFinishDate'=>'2026-09-05','capturedAt'=>'2026-09-14T12:00:00Z'];assertSameValue(hash('sha256',json_encode($canonical,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR)),$proof['originalDeadline']['source']['contentSha256'],'raw plan exact digest');assertSameValue(['label'=>'Исходный плановый срок','locator'=>'fm_maintable/4512/plan_finish_date','contentSha256'=>hash('sha256',json_encode($canonical,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR))],$proof['originalDeadline']['source'],'exact original plan source envelope');
 $calc=PremiumCalculationV2::calculate($row['operands'],['closures'=>[],'actualPayouts'=>[]]);assertSameValue([9,9100,1183000],[$calc['daysLate'],$calc['kssBp'],$calc['amounts']['poolCents']],'worked 2 percent progress with9day penalty');
 require dirname(__DIR__).'/Support/ExcelInputsAdversarial.php';excelInputsAdversarial($h,$reader,$row);
 $beforeFacts=$h->facts();$reader->forDate('2026-09-14');assertSameValue($beforeFacts,$h->facts(),'input reader performs no mutation');
 foreach(['2026-02-30','bad','0000-00-00']as$date){try{$reader->forDate($date);throw new TestFailure('Expected invalid report date');}catch(DomainException $error){assertSameValue('INVALID_DATE',$error->getMessage(),'invalid reader report date');}}
 $applications=$h->rows('fm2_assignment_order_applications');$application=$applications[0];$applicationId=(int)$application['application_id'];assertSameValue($applicationId,$proof['composition']['applicationId'],'current applied identity provenance');
 foreach(['selected_snapshot_json'=> '{}','composition_sha256'=>str_repeat('0',64)]as$column=>$broken){$db->prepare("UPDATE {$p}fm2_assignment_order_applications SET $column=? WHERE application_id=?")->execute([$broken,$applicationId]);try{$bad=$reader->forDate('2026-09-14')[0];inputBlocked($bad,'COMPOSITION_EVIDENCE_INVALID');}finally{$db->prepare("UPDATE {$p}fm2_assignment_order_applications SET $column=? WHERE application_id=?")->execute([$application[$column],$applicationId]);}}
 $templates=$h->rows('fm2_checklist_template_snapshots');$db->query("UPDATE {$p}fm2_checklist_template_snapshots SET content_sha256=REPEAT('0',64)");try{$bad=$reader->forDate('2026-09-14')[0];inputBlocked($bad,'DEFINITION_VERSION_UNPROVEN');}finally{foreach($templates as$t)$db->prepare("UPDATE {$p}fm2_checklist_template_snapshots SET content_sha256=? WHERE id=?")->execute([$t['content_sha256'],$t['id']]);}
 $attribution=$h->rows('fm2_checklist_operation_installers');$db->query("DELETE FROM {$p}fm2_checklist_operation_installers");try{$bad=$reader->forDate('2026-09-14')[0];inputBlocked($bad,'CHECKLIST_ATTRIBUTION_ABSENT');}finally{foreach($attribution as$r)$h->insert($p.'fm2_checklist_operation_installers',$r);}
 $db->query("UPDATE {$p}fm_maintable SET plan_finish_date='2026-09-10' WHERE id=4512");$next=$reader->forDate('2026-09-14')[0];assertSameValue(['2026-09-05','2026-09-10'],[$row['deadline'],$next['deadline']],'new read captures changed raw plan, old result stays unchanged');
 DeadlineCertificateFixture::grants($db,$p);$cert=new Certificates($db,$p,$clock);$command=['requestId'=>'00000000-0000-4000-8000-000000001001','installationCaseId'=>6101,'actorId'=>18,'expectedVersion'=>0,'certificateDate'=>'2099-01-01','newDeadline'=>'2026-09-12','correctionReason'=>null,'sourceLabel'=>'Inputs fixture','sourceLocator'=>'fixture://inputs/certificate','mediaType'=>'application/pdf'];$r1=$cert->submit($command,inputStream(Pdf::passiveClassic()))['revision'];$with=$reader->forDate('2026-09-14')[0];assertSameValue($cert->currentEvidence(6101),$with['sourceEvidence']['certificate'],'full certificate proof passed without reinterpretation');assertSameValue(['2026-09-12',$r1['id']],[$with['deadline'],$with['sourceEvidence']['certificate']['id']],'future document uses current deadline');assertSameValue(2,PremiumCalculationV2::calculate($with['operands'],['closures'=>[],'actualPayouts'=>[]])['daysLate'],'future certificate participates');
 $r2=$cert->submit(array_replace($command,['requestId'=>'00000000-0000-4000-8000-000000001002','expectedVersion'=>1,'newDeadline'=>'2026-09-20','correctionReason'=>'Corrected']),inputStream(Pdf::passiveClassic()."\n"))['revision'];assertSameValue('2026-09-20',$reader->forDate('2026-09-14')[0]['deadline'],'current corrected leaf');
 $db->query("UPDATE {$p}fm_maintable SET plan_finish_date=NULL WHERE id=4512");$blocked=$reader->forDate('2026-09-14')[0];inputBlocked($blocked,'DEADLINE_EVIDENCE_ABSENT');assertSameValue(null,$blocked['operands'],'no invented original operand');$db->query("UPDATE {$p}fm_maintable SET plan_finish_date='2026-09-10' WHERE id=4512");
 $db->query("UPDATE {$p}fm2_deadline_certificate_revisions SET pdf_sha256=REPEAT('0',64) WHERE id=".$r2['id']);$blocked=$reader->forDate('2026-09-14')[0];inputBlocked($blocked,'CERTIFICATE_EVIDENCE_INVALID');$db->prepare("UPDATE {$p}fm2_deadline_certificate_revisions SET pdf_sha256=? WHERE id=?")->execute([$r2['pdfSha256'],$r2['id']]);
 $changed=InspectionFixture::operation(2,$result['revision']);$changed['type']='item_installers_changed';$changed['deviceTime']=$op['deviceTime'];$changed['installerTabIds']=[7002];$result=InspectionFixture::result($f->send($changed,$csrf),200,'accepted');$db->query("UPDATE {$p}fm2_checklist_operations SET server_received_at='2026-09-14T11:00:00+03:00'");$attributed=$reader->forDate('2026-09-14')[0];assertSameValue(200,$attributed['sourceEvidence']['progress']['contributions']['7002'],'latest attribution correction');inputBlocked($attributed,'INSTALLER_ATTRIBUTION_ABSENT');
 $changedRow=$db->query("SELECT * FROM {$p}fm2_checklist_operations WHERE client_operation_id='".$changed['clientOperationId']."'")->fetch_assoc();
 $db->query("UPDATE {$p}fm2_checklist_operations SET device_time='2026-09-13T11:00:00+03:00' WHERE id=".$changedRow['id']);assertSameValue(200,$reader->forDate('2026-09-14')[0]['sourceEvidence']['progress']['contributions']['7002'],'accepted ordering overrides reversed device chronology');
 foreach(['device_time','server_received_at']as$column){$db->query("UPDATE {$p}fm2_checklist_operations SET $column='2026-09-15T11:00:00+03:00' WHERE id=".$changedRow['id']);try{assertSameValue(['7001'=>100,'7002'=>100],$reader->forDate('2026-09-14')[0]['sourceEvidence']['progress']['contributions'],'future attribution cutoff '.$column);}finally{$db->prepare("UPDATE {$p}fm2_checklist_operations SET $column=? WHERE id=?")->execute([$changedRow[$column],$changedRow['id']]);}}
 $db->query("UPDATE {$p}fm2_checklist_operations SET accepted_revision=99 WHERE client_operation_id='".$op['clientOperationId']."'");try{assertSameValue(['7001'=>100,'7002'=>100],$reader->forDate('2026-09-14')[0]['sourceEvidence']['progress']['contributions'],'accepted revision takes precedence over row ID');}finally{$db->query("UPDATE {$p}fm2_checklist_operations SET accepted_revision=1 WHERE client_operation_id='".$op['clientOperationId']."'");}
 $retract=InspectionFixture::operation(3,$result['revision']);$retract['type']='completion_retracted';$retract['deviceTime']=$op['deviceTime'];$retract['originalClientOperationId']=$op['clientOperationId'];$retract['reason']='Fixture retraction';$result=InspectionFixture::result($f->send($retract,$csrf),200,'accepted');$db->query("UPDATE {$p}fm2_checklist_operations SET server_received_at='2026-09-14T11:00:00+03:00'");assertSameValue(0,$reader->forDate('2026-09-14')[0]['progress'],'retraction removes completed share');
 foreach(['device_time','server_received_at']as$column){$db->query("UPDATE {$p}fm2_checklist_operations SET $column='2026-09-15T11:00:00+03:00' WHERE client_operation_id='".$retract['clientOperationId']."'");assertSameValue(200,$reader->forDate('2026-09-14')[0]['progress'],'future '.$column.' cannot retract in-cut completion');$db->query("UPDATE {$p}fm2_checklist_operations SET $column='2026-09-14T11:00:00+03:00' WHERE client_operation_id='".$retract['clientOperationId']."'");}
 $revision=$result['revision'];$template=json_decode($db->query("SELECT payload_json FROM {$p}fm2_checklist_template_snapshots LIMIT 1")->fetch_column(),true,flags:JSON_THROW_ON_ERROR);$sequence=100;$active=[];
 foreach($template['sections']as$section)foreach($section['items']as$item){$mark=InspectionFixture::operation(++$sequence,$revision,$item['id']);$active[$item['id']]=$mark['clientOperationId'];$mark['sectionId']=$section['id'];$mark['deviceTime']=$op['deviceTime'];$r=InspectionFixture::result($f->send($mark,$csrf),200,'accepted');$revision=$r['revision'];}
 $db->query("UPDATE {$p}fm2_checklist_operations SET server_received_at='2026-09-14T11:00:00+03:00'");assertSameValue(8500,$reader->forDate('2026-09-14')[0]['progress'],'all current template shares85percent');ksort($active,SORT_NUMERIC);assertSameValue(array_values($active),$reader->forDate('2026-09-14')[0]['sourceEvidence']['progress']['clientOperationIds'],'only current completions, sorted by item identity');
 excelInputsLatestApplied($h,$reader);
 foreach(['installation.completion.pto.record','installation.completion.pto.correct','installation.completion.declaration.record']as$permission)$db->prepare("INSERT IGNORE INTO {$p}fm2_pilot_role_permissions(role_id,permission)VALUES(1,?)")->execute([$permission]);
 $completion=new FMonitor2\InstallationProcess\MariaDbInstallationCompletion($db,$p);$completion->record(4512,18,'pto_act','2026-09-10','','2026-09-14T12:00:00Z');$root=$completion->facts(6101)['pto_act'];$completion->correct(4512,18,(int)$root['id'],'pto_act','2026-09-20','','Corrected PTO','2026-09-21T12:00:00Z');
 $pto=$reader->forDate('2026-09-14')[0];assertSameValue(['2026-09-20',9500],[$pto['pto'],$pto['progress']],'future corrected PTO comparison with separately in-cut documentary progress');$e=$pto['sourceEvidence']['completion'];assertSameValue((string)$root['id'],$e['root']['id'],'PTO root provenance');assertSameValue(1,count($e['corrections']),'PTO correction provenance');assertSameValue(hash('sha256',json_encode(['root'=>$e['root'],'corrections'=>$e['corrections']],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR)),$e['source']['contentSha256'],'full PTO chain digest');assertSameValue(['label'=>'История акта ПТО','locator'=>'fm2_pilot_completion_facts/case/6101/pto_act','contentSha256'=>hash('sha256',json_encode(['root'=>$e['root'],'corrections'=>$e['corrections']],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR))],$e['source'],'exact completion source envelope');
 $completion->record(4512,18,'declaration','2026-09-12','Declaration fixture','2026-09-14T12:00:00Z');assertSameValue(10000,$reader->forDate('2026-09-14')[0]['progress'],'85plus10plus5 documentary progress');
 $id=(int)$e['corrections'][0]['id'];$db->query('SET SESSION check_constraint_checks=OFF');$db->query("UPDATE {$p}fm2_pilot_completion_fact_corrections SET previous_version_no=17 WHERE id=$id");$bad=$reader->forDate('2026-09-14')[0];inputBlocked($bad,'COMPLETION_EVIDENCE_INVALID');$db->query("UPDATE {$p}fm2_pilot_completion_fact_corrections SET previous_version_no=NULL WHERE id=$id");$db->query('SET SESSION check_constraint_checks=ON');
 excelInputsCompletionBoundaries($h,$reader,$completion,(int)$root['id']);
 excelInputsConsistentCut($h,$reader);
 $db->query("UPDATE {$p}fm2_pilot_object_details SET content_sha256=REPEAT('0',64) WHERE object_id=4512");$bad=$reader->forDate('2026-09-14')[0];inputBlocked($bad,'OBJECT_CARD_PROVENANCE_INVALID');
 echo "PASS OTIZ-EXCEL-INPUTS-001\n";
}finally{if($f!==null)$f->close();}
