<?php
// OTIZ-EXCEL-PUBLICATION-001 — bounded existing publication/payment integration.
declare(strict_types=1);
require dirname(__DIR__).'/bootstrap.php';require dirname(__DIR__).'/Support/ExcelPublicationFixture.php';
$f=null;
try{
 $f=new ExcelPublicationFixture();$h=$f->http;$db=$h->db;$p=$h->p;$pub=$f->publication([['id'=>4512]]);$pay=$f->settlement();$date='2026-09-14';$op=$f->operation();
 $a=$pub->buildAndPublish(96,$date,$op);$ra=$f->read($a);assertSameValue('premium-calculation-v2-excel',$ra['snapshot']['rules_version'],'RED_ASSERTION publication uses Excel v2');assertSameValue([9000,0,9000],[(int)$ra['snapshot']['total_pool_cents'],(int)$ra['snapshot']['total_closed_cents'],(int)$ra['snapshot']['total_available_cents']],'initial totals');$input=json_decode($ra['objects'][0]['inputs_json'],true,flags:JSON_THROW_ON_ERROR);assertSameValue(ExcelPublicationFixture::inputs($date,[['id'=>4512]])[0]['sourceEvidence'],$input['sourceEvidence'],'source proof retained');assertSameValue([10,1000,9000],[$input['premiumCalculation']['daysLate'],$input['premiumCalculation']['amounts']['deadlinePenaltyCents'],$input['premiumCalculation']['amounts']['poolCents']],'literal penalty trace');
 assertSameValue(ExcelPublicationFixture::inputs($date,[['id'=>4512]])[0]['operands'],$input['premiumCalculation']['operandEvidence'],'all exact operands persisted');assertSameValue('largest-remainder-tab-asc-v1',$input['premiumCalculation']['allocationVersion'],'exact allocation policy');assertSameValue([],$input['premiumCalculation']['exclusions'],'exact exclusions');assertSameValue([['step'=>'fund','resultCents'=>10000],['step'=>'progress','resultCents'=>10000],['step'=>'deadline','daysLate'=>10,'resultBp'=>9000],['step'=>'paid','resultCents'=>0],['step'=>'remaining','resultCents'=>10000],['step'=>'penalty','resultCents'=>1000],['step'=>'pool','resultCents'=>9000]],$input['premiumCalculation']['formulaTrace'],'complete ordered arithmetic audit');
 $b=$pub->buildAndPublish(96,$date,$f->operation());assertSameValue(9000,(int)$f->read($b)['objects'][0]['pool_cents'],'unlimited drafts not payments');$pub->accept(96,$a);$payment=$f->operation();$paid=$pay->completeSnapshotPayments(96,$a,$payment);assertSameValue(9000,$paid['paidCents'],'first confirmed payout');$before=$h->facts();assertSameValue($paid,$pay->completeSnapshotPayments(96,$a,$payment),'same operation replay');assertSameValue($before,$h->facts(),'replay no facts');$pub->accept(96,$b);assertSameValue('no_change',$pay->completeSnapshotPayments(96,$b,$f->operation())['status'],'another same-target draft cannot double pay');
 $immutable=ExcelPublicationFixture::immutable($f->read($a));$c=$pub->buildAndPublish(96,$date,$f->operation());$rc=$f->read($c);$calc=json_decode($rc['objects'][0]['inputs_json'],true,flags:JSON_THROW_ON_ERROR)['premiumCalculation'];assertSameValue([9000,1000,100,900],[$calc['amounts']['paidBeforeCents'],$calc['amounts']['remainingBeforePenaltyCents'],$calc['amounts']['deadlinePenaltyCents'],$calc['amounts']['poolCents']],'confirmed recurrence9000→900');assertSameValue(9900,(int)$rc['objects'][0]['accrued_cents'],'existing cumulative target');$pub->accept(96,$c);assertSameValue(900,$pay->completeSnapshotPayments(96,$c,$f->operation())['paidCents'],'next literal payout');$d=$pub->buildAndPublish(96,$date,$f->operation());assertSameValue(90,(int)$f->read($d)['objects'][0]['pool_cents'],'next recurrence90');assertSameValue($immutable,ExcelPublicationFixture::immutable($f->read($a)),'historical snapshot unchanged');
 $never=new FMonitor2\Otiz\SnapshotPublication(new FMonitor2\Otiz\MariaDbSnapshotStore($db,$p),static fn()=>throw new RuntimeException('unexpected source read'),$f->clock());assertSameValue($a,$never->buildAndPublish(96,$date,$op),'replay never recalculates');$before=$h->facts();excelRefusal('OPERATION_CONFLICT',fn()=>$pub->buildAndPublish(96,'2026-09-13',$op));excelRefusal('FORBIDDEN',fn()=>$pub->buildAndPublish(73,$date,$f->operation()));assertSameValue($before,$h->facts(),'existing refusals add no facts');
 $pennies=$f->publication([['id'=>4513,'premium'=>5,'deadline'=>'2026-10-01']]);$id=$pennies->buildAndPublish(96,$date,$f->operation());assertSameValue([['1',2],['10',2],['2',1]],array_map(static fn($r)=>[$r['tab_id'],(int)$r['amount_cents']],$f->read($id)['allocations']),'binary remainder conservation');
 $holds=$f->publication([['id'=>4514]]);$h1=$holds->buildAndPublish(96,$date,$f->operation());$holds->accept(96,$h1);$pay->recordDiscipline(96,$h1,4514,100,'Existing discipline','',$f->operation());$h2=$holds->buildAndPublish(96,$date,$f->operation());$row=$f->read($h2)['objects'][0];assertSameValue([0,9000,8900],[(int)$row['closed_before_cents'],(int)$row['pool_cents'],(int)$row['distributed_cents']],'discipline is not paid before penalty');
 foreach(['object','receipt']as$fault){$before=$h->facts();$sql=$fault==='object'?"CREATE TRIGGER excel_failure BEFORE INSERT ON {$p}fm2_pilot_otiz_snapshot_objects FOR EACH ROW BEGIN IF NEW.object_id=4513 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='controlled failure'; END IF; END":"CREATE TRIGGER excel_failure BEFORE INSERT ON {$p}fm2_otiz_publications FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='controlled failure'";$db->query($sql);try{try{$f->publication([['id'=>4512],['id'=>4513]])->buildAndPublish(96,$date,$f->operation());throw new TestFailure('Expected SQL failure');}catch(mysqli_sql_exception $e){assertSameValue(true,str_contains($e->getMessage(),'controlled failure'),'controlled fault');}}finally{$db->query('DROP TRIGGER excel_failure');}assertSameValue($before,$h->facts(),'atomic existing publication '.$fault);}
 $closureRows=$db->query("SELECT * FROM {$p}fm2_pilot_otiz_payment_closures WHERE object_id=4512 ORDER BY id")->fetch_all(MYSQLI_ASSOC);$latest=json_decode($f->read($d)['objects'][0]['inputs_json'],true,flags:JSON_THROW_ON_ERROR)['premiumCalculation'];$expected=[];foreach($closureRows as$r)$expected[]=['amountCents'=>(int)$r['paid_cents'],'closedOn'=>$r['closed_on'],'source'=>['label'=>'Принятое закрытие ОТиЗ','locator'=>'fm2_pilot_otiz_payment_closures/'.$r['id'],'contentSha256'=>hash('sha256',json_encode($r,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR))]];assertSameValue($expected,$latest['paymentEvidence']['closures'],'full signed paid row evidence');
 $pub->accept(96,$d);$f->now='2026-09-15T12:00:00Z';assertSameValue(90,$pay->completeSnapshotPayments(96,$d,$f->operation())['paidCents'],'payment after report');$e=$pub->buildAndPublish(96,$date,$f->operation());$row=$f->read($e)['objects'][0];assertSameValue([9900,90],[(int)$row['closed_before_cents'],(int)$row['pool_cents']],'future payment outside report cut');$pub->accept(96,$e);assertSameValue('no_change',$pay->completeSnapshotPayments(96,$e,$f->operation())['status'],'existing live ledger avoids duplicate future payout');$f->now='2026-09-14T12:00:00Z';
 $rows=ExcelPublicationFixture::inputs($date,[['id'=>4515]]);$make=static fn($rows)=>new FMonitor2\Otiz\SnapshotPublication(new FMonitor2\Otiz\MariaDbSnapshotStore($db,$p),static fn()=>$rows,$f->clock());$x=$make($rows)->buildAndPublish(96,$date,$f->operation());$rows[0]['sourceEvidence']['fixture']['contentSha256']=str_repeat('c',64);$y=$make($rows)->buildAndPublish(96,$date,$f->operation());assertSameValue(false,$f->read($x)['snapshot']['content_hash']===$f->read($y)['snapshot']['content_hash'],'source changes content identity without changing totals');
 $reversed=$f->publication([['id'=>4516]]);$r1=$reversed->buildAndPublish(96,$date,$f->operation());$reversed->accept(96,$r1);$pay->completeSnapshotPayments(96,$r1,$f->operation());$original=$db->query("SELECT * FROM {$p}fm2_pilot_otiz_payment_closures WHERE object_id=4516 ORDER BY id LIMIT 1")->fetch_assoc();$pay->reverse(96,(int)$original['id'],'Existing signed reversal',$f->operation());$r2=$reversed->buildAndPublish(96,$date,$f->operation());$recalc=json_decode($f->read($r2)['objects'][0]['inputs_json'],true,flags:JSON_THROW_ON_ERROR)['premiumCalculation'];assertSameValue([0,9000],[$recalc['amounts']['paidBeforeCents'],$recalc['amounts']['poolCents']],'signed reversal in next Excel recurrence');assertSameValue([9000,-9000],array_column($recalc['paymentEvidence']['closures'],'amountCents'),'both confirmed signed rows retained');assertSameValue($original,$db->query("SELECT * FROM {$p}fm2_pilot_otiz_payment_closures WHERE id=".$original['id'])->fetch_assoc(),'reversal never rewrites original');
 $blockers=[['code'=>'DEADLINE_EVIDENCE_ABSENT','message'=>'Missing original deadline','owner'=>'OTIZ']];$blockedPub=$f->publication([['id'=>4517,'issues'=>$blockers]]);$blocked=$blockedPub->buildAndPublish(96,$date,$f->operation());$br=$f->read($blocked);$bi=json_decode($br['objects'][0]['inputs_json'],true,flags:JSON_THROW_ON_ERROR);assertSameValue($blockers,$bi['blockers'],'complete blocker evidence');assertSameValue(null,$bi['premiumCalculation'],'blocked inputs never invent arithmetic');assertSameValue(ExcelPublicationFixture::inputs($date,[['id'=>4517,'issues'=>$blockers]])[0]['sourceEvidence'],$bi['sourceEvidence'],'blocked source remains visible');assertSameValue(0,array_sum(array_map(static fn($r)=>(int)$r['amount_cents'],$br['allocations'])),'blocked zero distribution');$before=$h->facts();excelRefusal('BLOCKERS',fn()=>$blockedPub->accept(96,$blocked));assertSameValue($before,$h->facts(),'blocked accept adds nothing');
 require dirname(__DIR__).'/Support/HistoricalCalculationFixture.php';$historical=excelHistoricalPublication($f);$cookies=[];$h->login($cookies,96);$csrf=$h->token($cookies);$before=$h->facts();$response=$h->request('POST','/pilot/otiz/snapshots/'.$historical.'/payments/complete',['_csrf'=>$csrf,'operationId'=>$f->operation()],$cookies);assertSameValue(409,$response['status'],'old formula HTTP409');assertSameValue(true,str_contains(mb_strtolower(strip_tags($response['body'])),'новый расчёт'),'old formula HTTP explains next action');assertSameValue($before,$h->facts(),'old formula HTTP refusal no facts');

 echo "PASS OTIZ-EXCEL-PUBLICATION-001\n";
}finally{if($f!==null)$f->close();}
