<?php declare(strict_types=1);
require dirname(__DIR__).'/bootstrap.php';require dirname(__DIR__,2).'/app/autoload.php';
use FMonitor2\Otiz\OtizSettlementV2Workbook;
function wfiles(string$b):array{$p=tempnam(sys_get_temp_dir(),'xlsx');file_put_contents($p,$b);$z=new ZipArchive();assertSameValue(true,$z->open($p)===true,'independent XLSX reader');$o=[];for($i=0;$i<$z->numFiles;$i++)$o[$z->getNameIndex($i)]=$z->getFromIndex($i);$z->close();unlink($p);return$o;}
function wpath(array$f,string$n):string{$w=simplexml_load_string($f['xl/workbook.xml']);$w->registerXPathNamespace('m','http://schemas.openxmlformats.org/spreadsheetml/2006/main');$id='';foreach($w->xpath('//m:sheet')as$s)if((string)$s['name']===$n)$id=(string)$s->attributes('http://schemas.openxmlformats.org/officeDocument/2006/relationships')['id'];$r=simplexml_load_string($f['xl/_rels/workbook.xml.rels']);$r->registerXPathNamespace('p','http://schemas.openxmlformats.org/package/2006/relationships');foreach($r->xpath('//p:Relationship')as$x)if((string)$x['Id']===$id)return'xl/'.(string)$x['Target'];throw new TestFailure('sheet '.$n);}
function wrows(string$x):array{preg_match_all('/<row\b[^>]*>(.*?)<\/row>/s',$x,$m);return$m[1]??[];}
function wcells(string$r):array{preg_match_all('/<c\b([^>]*)>(.*?)<\/c>/s',$r,$m);$o=[];foreach($m[2]??[]as$i=>$b){preg_match('/<t[^>]*>(.*?)<\/t>|<v>(.*?)<\/v>/s',$b,$v);$raw=($v[1]??'')!==''?$v[1]:($v[2]??'');$o[]=['a'=>$m[1][$i]??'','v'=>html_entity_decode(strip_tags($raw),ENT_QUOTES|ENT_XML1,'UTF-8')];}return$o;}
function wfmt(array$f,string$a):string{assertSameValue(1,preg_match('/\bs="(\d+)"/',$a,$m),'style id');$s=simplexml_load_string($f['xl/styles.xml']);$s->registerXPathNamespace('m','http://schemas.openxmlformats.org/spreadsheetml/2006/main');$xf=$s->xpath('//m:cellXfs/m:xf');$id=(int)$xf[(int)$m[1]]['numFmtId'];foreach($s->xpath('//m:numFmts/m:numFmt')as$n)if((int)$n['numFmtId']===$id)return(string)$n['formatCode'];return[14=>'yyyy-mm-dd',2=>'0.00',10=>'0.00%'][$id]??'builtin-'.$id;}
$source=['calculation'=>['id'=>42,'status'=>'accepted','reportDate'=>'2026-09-26','revision'=>3,'rulesVersion'=>'otiz-v2','acceptedAt'=>'2026-09-26T10:00:00+03:00','contentHash'=>str_repeat('a',64),'totalCents'=>1498766],'objects'=>[
 ['objectId'=>1,'regnumber'=>'014903','address'=>'=HYPERLINK("bad")','fundCents'=>10000000,'plannedPremiumCents'=>1234500,'grossCents'=>900000,'deadlineCents'=>50000,'disciplineCents'=>10000,'payableCents'=>898766,'shaftBp'=>11000,'confirmedBp'=>6000,'paidBeforeCents'=>100000,'daysLate'=>5,'kssBp'=>9500,'responsibleName'=>'Петров Пётр','objectStatus'=>'working','change'=>'revision-1','changeDate'=>'2026-09-25'],
 ['objectId'=>2,'regnumber'=>'000007','address'=>'Невский, 1','fundCents'=>20000000,'plannedPremiumCents'=>2345600,'grossCents'=>600000,'deadlineCents'=>0,'disciplineCents'=>0,'payableCents'=>600000,'shaftBp'=>10000,'confirmedBp'=>4000,'paidBeforeCents'=>0,'daysLate'=>0,'kssBp'=>10000,'responsibleName'=>'Сидоров Сидор','objectStatus'=>'completed','change'=>'revision-2','changeDate'=>'2026-09-26']],
'recipients'=>[['employeeId'=>'A','tabNumber'=>'00103','name'=>'Иванов','objectId'=>1,'originalWeight'=>60,'finalShareBp'=>10000,'preDeductionCents'=>900000,'deductionCents'=>1234,'employment'=>'employed','amountCents'=>898766],['employeeId'=>'A','tabNumber'=>'00103','name'=>'Иванов','objectId'=>2,'originalWeight'=>40,'finalShareBp'=>10000,'preDeductionCents'=>600000,'deductionCents'=>0,'employment'=>'employed','amountCents'=>600000],['employeeId'=>'B','tabNumber'=>'00104','name'=>'Исключённый','objectId'=>2,'originalWeight'=>10,'finalShareBp'=>0,'preDeductionCents'=>0,'deductionCents'=>0,'employment'=>'dismissed','excluded'=>true,'amountCents'=>0]],
'deductions'=>[['objectId'=>1,'employeeId'=>null,'amountCents'=>10000,'reason'=>'Общее удержание','document'=>'COMMON-1','createdAt'=>'2026-09-26T09:00:00+03:00'],['objectId'=>1,'employeeId'=>'A','amountCents'=>1234,'reason'=>'Личное удержание','document'=>'PERSONAL-1','createdAt'=>'2026-09-26T09:01:00+03:00']],
'decisions'=>[['employeeId'=>'B','decision'=>'do_not_pay','reason'=>'Приказ 7','actorId'=>501,'createdAt'=>'2026-09-26T09:02:00+03:00']],'issues'=>[['code'=>'EXCLUDED_ZERO','message'=>'Исключённый получатель']]];
$draft=OtizSettlementV2Workbook::build($source+['mode'=>'draft']);assertSameValue(true,str_contains($draft['filename'],'Черновик-Не-основание-выплаты'),'draft filename');
$f=wfiles(OtizSettlementV2Workbook::build($source+['mode'=>'payment','exportedAt'=>'2026-09-26T12:00:00+03:00'])['bytes']);assertSameValue([false,false,true],[isset($f['xl/vbaProject.bin']),str_contains(implode("\n",array_keys($f)),'externalLink'),isset($f['xl/styles.xml'])],'safe styled XLSX');
$mp=wpath($f,'Расчёт ОТиЗ');$ap=wpath($f,'Приложение к приказу');$dp=wpath($f,'Удержания');$rp=wpath($f,'Решения по выплате');$meta=wpath($f,'Метаданные');$rows=wrows($f[$mp]);$hi=null;foreach($rows as$i=>$r)if(str_contains($r,'Расчетный период'))$hi=$i;assertSameValue(true,$hi!==null,'21-field header on main sheet');$c=wcells($rows[$hi+1]??'');assertSameValue(21,count($c),'21 fields');assertSameValue(['014903','1.1','12345','Иванов','00103','0.6','1000','5','0.95','500','9000','60','9000','12.34','8987.66','Петров Пётр','employed','revision-1','2026-09-25','working'],array_map(fn($i)=>$c[$i]['v'],range(1,20)),'exact saved field map and scales');assertSameValue('yyyy-mm-dd',wfmt($f,$c[0]['a']),'date style');foreach([6,9]as$i)assertSameValue('0.00%',wfmt($f,$c[$i]['a']),'percent style '.$i);foreach([3,7,10,11,13,14,15]as$i)assertSameValue('0.00',wfmt($f,$c[$i]['a']),'money style '.$i);
$ar=wrows($f[$ap]);assertSameValue(2,count($ar),'one positive recipient');assertSameValue(true,str_contains($ar[1],'00103')&&str_contains($ar[1],'14987.66'),'stable recipient aggregate');assertSameValue(false,str_contains($f[$ap],'00104'),'zero excluded');assertSameValue(true,str_contains($f[$dp],'COMMON-1')&&str_contains($f[$dp],'PERSONAL-1'),'distinct deductions');assertSameValue(true,str_contains($f[$rp],'do_not_pay')&&str_contains($f[$rp],'Приказ 7'),'decision explanation');foreach(['otiz-v2',str_repeat('a',64),'2026-09-26T10:00:00+03:00']as$v)assertSameValue(true,str_contains($f[$meta],$v),'metadata '.$v);foreach(['<cols>','<pane','autoFilter','pageMargins','pageSetup']as$v)assertSameValue(true,str_contains($f[$mp],$v),'layout '.$v);assertSameValue(true,str_contains($f['xl/workbook.xml'],'_xlnm.Print_Area')&&str_contains($f['xl/workbook.xml'],'_xlnm.Print_Titles'),'print definitions');$all=implode("\n",array_filter($f,fn($k)=>str_starts_with($k,'xl/worksheets/'),ARRAY_FILTER_USE_KEY));assertSameValue([false,true],[str_contains($all,'<f>'),str_contains($all,'=HYPERLINK(&quot;bad&quot;)')],'formula injection stored as text');
$h=implode("\n",wfiles(OtizSettlementV2Workbook::build($source+['mode'=>'history','exportedAt'=>'2026-10-01T12:00:00+03:00'])['bytes']));assertSameValue(true,str_contains($h,'Историческая выгрузка')&&str_contains($h,'на момент выгрузки'),'history labeling');assertSameValue(false,OtizSettlementV2Workbook::paymentExportAllowed($source,'unknown'),'unknown blocks');assertSameValue(true,OtizSettlementV2Workbook::historicalExportAllowed($source),'history allowed');
echo "settlement_v2_workbook_001_test: OK\n";
