<?php
declare(strict_types=1);

require dirname(__DIR__).'/bootstrap.php';
require dirname(__DIR__,2).'/vendor/autoload.php';
require dirname(__DIR__,2).'/vendor/yiisoft/yii2/Yii.php';

use FMonitor2\InstallationProcess\CanonicalMigrationApplication;
use FMonitor2\InstallationProcess\OtizSettlementSchemaMigration;
use FMonitor2\InstallationProcess\ProductionPilotMigrationCatalogue;
use FMonitor2\Otiz\OtizSettlement;

mysqli_report(MYSQLI_REPORT_ERROR|MYSQLI_REPORT_STRICT);
$host=getenv('FMONITOR_TEST_DB_HOST')?:'127.0.0.1';$port=(int)(getenv('FMONITOR_TEST_DB_PORT')?:23306);$user=getenv('FMONITOR_TEST_DB_ADMIN_USER')?:'root';$password=getenv('FMONITOR_TEST_DB_ADMIN_PASSWORD')?:'fmonitor2_test_root_local';
$admin=new mysqli($host,$user,$password,'',$port);$database='t_otiz_settlement_concurrency_'.bin2hex(random_bytes(5));$db=null;$workers=[];$prefix='osc_';

function oscYii(string$host,int$port,string$user,string$password,string$database):yii\db\Connection{$connection=new yii\db\Connection(['dsn'=>"mysql:host={$host};port={$port};dbname={$database}",'username'=>$user,'password'=>$password,'charset'=>'utf8mb4']);$connection->open();return$connection;}
function oscWorker(string$root,string$database,string$prefix,string$action,int$actor,int$target,string$operation):array{$pipes=[];$process=proc_open([PHP_BINARY,$root.'/tests/Otiz/settlement_worker.php',$database,$prefix,$action,(string)$actor,(string)$target,$operation],[0=>['pipe','r'],1=>['pipe','w'],2=>['pipe','w']],$pipes,$root,getenv());if(!is_resource($process))throw new TestFailure('SETUP_FAILURE: settlement worker');$worker=['process'=>$process,'pipes'=>$pipes];$GLOBALS['oscWorkers'][]=$worker;return$worker;}
function oscRunPair(array$left,array$right,?Closure$started=null):array{$pair=[$left,$right];foreach($pair as$worker){stream_set_blocking($worker['pipes'][1],false);stream_set_blocking($worker['pipes'][2],false);fwrite($worker['pipes'][0],"GO\n");fclose($worker['pipes'][0]);}if($started!==null)$started();$outputs=[['stdout'=>'','stderr'=>''],['stdout'=>'','stderr'=>'']];$deadline=microtime(true)+15;do{$running=false;foreach($pair as$index=>$worker){$outputs[$index]['stdout'].=(string)stream_get_contents($worker['pipes'][1]);$outputs[$index]['stderr'].=(string)stream_get_contents($worker['pipes'][2]);if(proc_get_status($worker['process'])['running'])$running=true;}if(!$running)break;usleep(10000);}while(microtime(true)<$deadline);if($running){foreach($pair as$worker)if(proc_get_status($worker['process'])['running'])proc_terminate($worker['process'],9);throw new TestFailure('SETUP_FAILURE: concurrent worker deadline');}$results=[];foreach($pair as$index=>$worker){stream_set_blocking($worker['pipes'][1],true);stream_set_blocking($worker['pipes'][2],true);$outputs[$index]['stdout'].=(string)stream_get_contents($worker['pipes'][1]);$outputs[$index]['stderr'].=(string)stream_get_contents($worker['pipes'][2]);fclose($worker['pipes'][1]);fclose($worker['pipes'][2]);$exit=proc_close($worker['process']);assertSameValue([0,''],[$exit,$outputs[$index]['stderr']],'independent worker exit');$results[]=json_decode(trim($outputs[$index]['stdout']),true,16,JSON_THROW_ON_ERROR);}return$results;}
function oscCounts(mysqli$db,string$p):array{return[(int)$db->query("SELECT COUNT(*) n FROM {$p}fm2_pilot_otiz_payment_closures")->fetch_assoc()['n'],(int)$db->query("SELECT COUNT(*) n FROM {$p}fm2_pilot_otiz_events")->fetch_assoc()['n'],(int)$db->query("SELECT COUNT(*) n FROM {$p}fm2_otiz_settlement_operations")->fetch_assoc()['n']];}

try{
 $admin->query("CREATE DATABASE `{$database}` DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");$db=new mysqli($host,$user,$password,$database,$port);$migration=CanonicalMigrationApplication::run($db,$prefix,ProductionPilotMigrationCatalogue::migrations());assertSameValue([0,true,23],[$migration['exitCode'],$migration['result']['ok']??null,$migration['result']['schemaVersion']??null],'SETUP_FAILURE: canonical v23');$yii=oscYii($host,$port,$user,$password,$database);OtizSettlementSchemaMigration::apply($yii,$prefix);$yii->close();
 foreach([[601,61,'otiz.manage'],[602,62,'otiz.manage'],[603,63,'OTIZ.MANAGE']]as[$actor,$role,$permission]){$db->query("INSERT INTO {$prefix}fm2_pilot_users(user_id,full_name,email,status,activation_state,source_updated_at)VALUES({$actor},'Actor {$actor}','actor{$actor}@example.test',1,'active','2026-09-09T10:00:00+03:00')");$db->query("INSERT INTO {$prefix}fm2_pilot_roles(role_id,code,name,description,status,source_updated_at)VALUES({$role},'otiz_{$role}','OTIZ {$role}','concurrency',1,'2026-09-09T10:00:00+03:00')");$db->query("INSERT INTO {$prefix}fm2_pilot_role_permissions VALUES({$role},'{$permission}')");$db->query("INSERT INTO {$prefix}fm2_pilot_user_roles(user_id,role_id,origin,assigned_at)VALUES({$actor},{$role},'test','2026-09-09T10:00:00+03:00')");}
 $hash=str_repeat('b',64);$db->query("INSERT INTO {$prefix}fm2_pilot_otiz_snapshots(id,report_date,status,rules_version,calculated_at,calculated_by_user_id,accepted_at,accepted_by_user_id,total_pool_cents,total_closed_cents,total_available_cents,content_hash)VALUES(201,'2026-08-31','accepted','premium-calculation-v1','2026-09-01T09:00:00+03:00',601,'2026-09-01T10:00:00+03:00',601,100000,0,100000,'{$hash}'),(202,'2026-09-30','accepted','premium-calculation-v1','2026-10-01T09:00:00+03:00',602,'2026-10-01T10:00:00+03:00',602,150000,0,150000,'{$hash}'),(203,'2026-10-01','accepted','premium-calculation-v1','2026-10-02T09:00:00+03:00',601,'2026-10-02T10:00:00+03:00',601,100000,0,100000,'{$hash}')");
 $columns='(snapshot_id,object_id,regnumber,address,previous_progress_bp,current_progress_bp,progress_fact_date,premium_cents,shaft_bp,kss_bp,accrued_cents,fund_cents,closed_before_cents,remaining_cents,pool_cents,distributed_cents,undistributed_cents,calculation_state,inputs_json)';
 $db->query("INSERT INTO {$prefix}fm2_pilot_otiz_snapshot_objects {$columns} VALUES(201,7001,'C-S1','Concurrent',0,8500,'2026-08-31',100000,10000,10000,100000,100000,0,100000,100000,100000,0,'ready','{}'),(202,7001,'C-S2','Concurrent',8500,10000,'2026-09-30',150000,10000,10000,150000,150000,0,150000,150000,150000,0,'ready','{}'),(203,8001,'RB-1','Rollback one',0,10000,'2026-10-01',60000,10000,10000,60000,60000,0,60000,60000,60000,0,'ready','{}'),(203,8002,'RB-2','Rollback two',0,10000,'2026-10-01',40000,10000,10000,40000,40000,0,40000,40000,40000,0,'ready','{}')");
 $db->query("CREATE TRIGGER osc_delay_closure BEFORE INSERT ON {$prefix}fm2_pilot_otiz_payment_closures FOR EACH ROW BEGIN DO SLEEP(0.2); END");
 $root=dirname(__DIR__,2);$left=oscWorker($root,$database,$prefix,'complete',601,201,'00000000-0000-4000-8000-000000000201');$right=oscWorker($root,$database,$prefix,'complete',602,202,'00000000-0000-4000-8000-000000000202');$workers=[$left,$right];$complete=oscRunPair($left,$right);$workers=[];assertSameValue([true,true],array_column($complete,'ok'),'INTENDED_RED: concurrent complete commands both return valid public outcomes without deadlock');
 $outcomes=array_map(static fn(array$r):array=>$r['result'],$complete);usort($outcomes,static fn(array$a,array$b):int=>$a['paidCents']<=>$b['paidCents']);$observed=array_map(static fn(array$r):array=>[$r['objectCount'],$r['paidCents'],$r['status']],$outcomes);$allowed=[[[0,0,'no_change'],[1,150000,'completed']],[[1,50000,'completed'],[1,100000,'completed']]];assertSameValue(true,in_array($observed,$allowed,true),'INTENDED_RED: concurrent valid outcomes serialize at financial object');
 $signed=(int)$db->query("SELECT COALESCE(SUM(paid_cents+discipline_cents+deadline_cents),0)n FROM {$prefix}fm2_pilot_otiz_payment_closures WHERE object_id=7001")->fetch_assoc()['n'];assertSameValue(150000,$signed,'concurrent completion never exceeds literal150000');$db->query('DROP TRIGGER osc_delay_closure');
 $nearBefore=oscCounts($db,$prefix);$nearDb=oscYii($host,$port,$user,$password,$database);try{(new OtizSettlement($nearDb,$prefix,static fn():string=>'2026-10-03T12:00:00+03:00'))->completeSnapshotPayments(603,201,'00000000-0000-4000-8000-000000000203');throw new TestFailure('near-match OTIZ permission authorized');}catch(DomainException$e){assertSameValue('FORBIDDEN',$e->getMessage(),'permission comparison is byte-exact');}finally{$nearDb->close();}assertSameValue($nearBefore,oscCounts($db,$prefix),'near-match permission denial creates no facts');
 $outerDb=oscYii($host,$port,$user,$password,$database);$outer=$outerDb->beginTransaction();$outerBefore=oscCounts($db,$prefix);try{(new OtizSettlement($outerDb,$prefix,static fn():string=>'2026-10-03T12:00:00+03:00'))->completeSnapshotPayments(601,201,'00000000-0000-4000-8000-000000000204');throw new TestFailure('settlement claimed outcome inside caller transaction');}catch(LogicException){}finally{if($outer->isActive)$outer->rollBack();$outerDb->close();}assertSameValue($outerBefore,oscCounts($db,$prefix),'existing caller transaction rejected without facts');

 $db->query("INSERT INTO {$prefix}fm2_pilot_otiz_payment_closures(snapshot_id,object_id,closed_on,paid_cents,discipline_cents,deadline_cents,basis,artifact,created_by_user_id,created_at)VALUES(202,7101,'2026-10-02',70000,20000,10000,'Mixed original','artifact',601,'2026-10-02T11:00:00+03:00')");$original=(int)$db->insert_id;
 $reverse=oscRunPair(oscWorker($root,$database,$prefix,'reverse',601,$original,'00000000-0000-4000-8000-000000000211'),oscWorker($root,$database,$prefix,'reverse',602,$original,'00000000-0000-4000-8000-000000000212'));$success=array_values(array_filter($reverse,static fn(array$r):bool=>$r['ok']));$refused=array_values(array_filter($reverse,static fn(array$r):bool=>!$r['ok']));assertSameValue([1,1,'ALREADY_REVERSED'],[count($success),count($refused),$refused[0]['reason']??null],'concurrent reverse creates exactly one reversal');$reversal=$db->query("SELECT paid_cents,discipline_cents,deadline_cents,reverses_payment_closure_id FROM {$prefix}fm2_pilot_otiz_payment_closures WHERE reverses_payment_closure_id={$original}")->fetch_all(MYSQLI_ASSOC);assertSameValue([[-70000,-20000,-10000,$original]],array_map(static fn(array$r):array=>[(int)$r['paid_cents'],(int)$r['discipline_cents'],(int)$r['deadline_cents'],(int)$r['reverses_payment_closure_id']],$reversal),'exactly one linked negative reversal copies all components');$winner=$success[0]['result'];$winnerActor=$reverse[0]['ok']?601:602;$winnerOp=$reverse[0]['ok']?'00000000-0000-4000-8000-000000000211':'00000000-0000-4000-8000-000000000212';$replayDb=oscYii($host,$port,$user,$password,$database);$replay=(new OtizSettlement($replayDb,$prefix,static fn():string=>'2026-10-03T12:00:00+03:00'))->reverse($winnerActor,$original,'Concurrent reversal',$winnerOp);assertSameValue($winner,$replay,'winning reversal exact replay stable');$replayDb->close();

 $db->query("INSERT INTO {$prefix}fm2_pilot_otiz_payment_closures(snapshot_id,object_id,closed_on,paid_cents,discipline_cents,deadline_cents,basis,artifact,created_by_user_id,created_at)VALUES(202,7102,'2026-10-02',50000,0,0,'Same operation original','',601,'2026-10-02T11:00:00+03:00')");$sameOriginal=(int)$db->insert_id;$sameOperation='00000000-0000-4000-8000-000000000213';
 $gate=new mysqli($host,$user,$password,$database,$port);$gate->query("LOCK TABLES {$prefix}fm2_otiz_settlement_operations WRITE");$release=function()use($admin,$gate,$database):void{$escaped=$admin->real_escape_string($database);$deadline=microtime(true)+5;do{$waiting=(int)$admin->query("SELECT COUNT(*) n FROM information_schema.PROCESSLIST WHERE DB='{$escaped}' AND COMMAND='Query' AND INFO LIKE '%fm2_otiz_settlement_operations%'")->fetch_assoc()['n'];if($waiting>=2){$gate->query('UNLOCK TABLES');$gate->close();return;}usleep(10000);}while(microtime(true)<$deadline);$gate->query('UNLOCK TABLES');$gate->close();throw new TestFailure('SETUP_FAILURE: both reversal workers did not reach receipt lookup rendezvous');};$sameReverse=oscRunPair(oscWorker($root,$database,$prefix,'reverse',601,$sameOriginal,$sameOperation),oscWorker($root,$database,$prefix,'reverse',601,$sameOriginal,$sameOperation),$release);assertSameValue([true,true],array_column($sameReverse,'ok'),'INTENDED_RED: concurrent exact reversal replay returns the same successful outcome');assertSameValue($sameReverse[0]['result'],$sameReverse[1]['result'],'concurrent exact reversal replay result is stable');assertSameValue(1,(int)$db->query("SELECT COUNT(*) n FROM {$prefix}fm2_pilot_otiz_payment_closures WHERE reverses_payment_closure_id={$sameOriginal}")->fetch_assoc()['n'],'concurrent exact replay appends one reversal only');

 $before=oscCounts($db,$prefix);$db->query("CREATE TRIGGER osc_fail_second BEFORE INSERT ON {$prefix}fm2_pilot_otiz_payment_closures FOR EACH ROW BEGIN IF NEW.object_id=8002 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='fixture second object failure'; END IF; END");$faultDb=oscYii($host,$port,$user,$password,$database);$retryOp='00000000-0000-4000-8000-000000000221';$faultReached=false;try{(new OtizSettlement($faultDb,$prefix,static fn():string=>'2026-10-03T12:00:00+03:00'))->completeSnapshotPayments(601,203,$retryOp);throw new TestFailure('late second-object failure accepted');}catch(yii\db\Exception$e){$faultReached=str_contains($e->getMessage(),'fixture second object failure');}finally{$faultDb->close();}assertSameValue(true,$faultReached,'test-only trigger reached exact second object');assertSameValue($before,oscCounts($db,$prefix),'late second-object fault rolls back closures events and receipt');$db->query('DROP TRIGGER osc_fail_second');$retryDb=oscYii($host,$port,$user,$password,$database);$retried=(new OtizSettlement($retryDb,$prefix,static fn():string=>'2026-10-03T12:00:00+03:00'))->completeSnapshotPayments(601,203,$retryOp);assertSameValue(['completed',2,100000],[$retried['status'],$retried['objectCount'],$retried['paidCents']],'same operation retries after rollback and closes both objects');$retryDb->close();
 echo"PASS: OTIZ-SETTLEMENT-001 concurrent financial basis, reversal and rollback\n";
}finally{foreach($GLOBALS['oscWorkers']??[]as$worker)if(is_resource($worker['process']))proc_terminate($worker['process'],9);if($db instanceof mysqli)$db->close();$admin->query("DROP DATABASE IF EXISTS `{$database}`");$admin->close();}
