<?php
declare(strict_types=1);require dirname(__DIR__).'/bootstrap.php';require dirname(__DIR__,2).'/app/autoload.php';
use FMonitor2\Otiz\OtizSettlementV2Workbook;
$source=['calculation'=>['id'=>42,'status'=>'accepted','reportDate'=>'2026-09-26','revision'=>3,'rulesVersion'=>'otiz-v2','acceptedAt'=>'2026-09-26T10:00:00+03:00','totalCents'=>1500000],'objects'=>[['objectId'=>1,'regnumber'=>'014903','address'=>'=HYPERLINK("bad")','fundCents'=>10000000,'plannedPremiumCents'=>1234500,'grossCents'=>900000,'deadlineCents'=>0,'disciplineCents'=>0,'payableCents'=>900000],['objectId'=>2,'regnumber'=>'000007','address'=>'Невский, 1','fundCents'=>20000000,'plannedPremiumCents'=>2345600,'grossCents'=>600000,'deadlineCents'=>0,'disciplineCents'=>0,'payableCents'=>600000]],'recipients'=>[['employeeId'=>'A','tabNumber'=>'00103','name'=>'Иванов','objectId'=>1,'originalWeight'=>60,'finalShareBp'=>10000,'amountCents'=>900000],['employeeId'=>'A','tabNumber'=>'00103','name'=>'Иванов','objectId'=>2,'originalWeight'=>40,'finalShareBp'=>10000,'amountCents'=>600000]],'deductions'=>[],'decisions'=>[],'issues'=>[],'payment'=>['paidCents'=>0,'remainingCents'=>1500000]];
if(!class_exists(OtizSettlementV2Workbook::class)){fwrite(STDERR,"INTENDED_RED: saved-revision workbook builder is absent\n");exit(1);}
function v2xml(string$bytes):array{$f=tempnam(sys_get_temp_dir(),'v2xlsx');file_put_contents($f,$bytes);$z=new ZipArchive();assertSameValue(true,$z->open($f)===true,'independent ZIP reader opens XLSX');$out=[];for($i=0;$i<$z->numFiles;$i++){$n=$z->getNameIndex($i);$out[$n]=$z->getFromIndex($i);} $z->close();unlink($f);return$out;}
function v2cell(array$x,int$sheet,int$row,int$column):array{$xml=(string)($x['xl/worksheets/sheet'.$sheet.'.xml']??'');preg_match_all('/<row\b[^>]*>(.*?)<\/row>/s',$xml,$rows);preg_match_all('/<c\b([^>]*)>(.*?)<\/c>/s',$rows[1][$row-1]??'',$cells);return['attributes'=>$cells[1][$column-1]??'','body'=>$cells[2][$column-1]??''];}
$draft=OtizSettlementV2Workbook::build($source+['mode'=>'draft']);assertSameValue(true,str_contains($draft['filename'],'Черновик-Не-основание-выплаты'),'draft filename is explicit');$dx=v2xml($draft['bytes']);$joined=implode("\n",$dx);assertSameValue(true,str_contains($joined,'Черновик. Не основание выплаты'),'draft header/metadata explicit');
$book=OtizSettlementV2Workbook::build($source+['mode'=>'payment','exportedAt'=>'2026-09-26T12:00:00+03:00']);$x=v2xml($book['bytes']);assertSameValue(false,isset($x['xl/vbaProject.bin']),'no macros');assertSameValue(false,str_contains(implode("\n",array_keys($x)),'externalLink'),'no external links');$wb=$x['xl/workbook.xml']??'';foreach(['Расчёт ОТиЗ','Объекты','Работники','Контроль','Приложение к приказу','Метаданные','Удержания','Решения по выплате']as$name)assertSameValue(true,str_contains($wb,$name),'sheet '.$name);
$sheets=implode("\n",array_filter($x,static fn($k)=>str_starts_with($k,'xl/worksheets/'),ARRAY_FILTER_USE_KEY));foreach(['014903','000007','00103']as$id)assertSameValue(true,str_contains($sheets,$id),'leading-zero text '.$id);assertSameValue(false,str_contains($sheets,'<f>'),'no formulas including injection');assertSameValue(true,str_contains($sheets,'=HYPERLINK(&quot;bad&quot;)'),'formula-like user input is text');foreach(['<pane','autoFilter','printTitles','pageSetup']as$feature)assertSameValue(true,str_contains($sheets,$feature),'usable workbook feature '.$feature);$fund=v2cell($x,2,2,3);assertSameValue([true,true], [str_contains($fund['attributes'],'t="n"'),str_contains($fund['body'],'<v>100000</v>')],'Objects C2 is the saved fund as a numeric money cell');$planned=v2cell($x,9,2,4);assertSameValue([true,true],[str_contains($planned['attributes'],'t="n"'),str_contains($planned['body'],'<v>12345</v>')],'Legacy21 D2 uses saved planned premium rather than fund');assertSameValue(true,str_contains($sheets,'>15000<'),'one stable-recipient total 15000 rubles');
$legacyHeaders=['Расчетный период','Рег. номер','Коэффициент типа шахты','Плановая премия за монтаж, руб.','Фамилия, имя, отчество работника','Таб. №','Квып','Премия за монтаж, выплаченная ранее, руб.','Количество дней просрочки, дн.','Ксобл.срок.','Сумма удержания за несоблюдение сроков, руб.','Расчетная премия к распределению, руб.','КТУ работника','Премия с учетом КТУ, руб.','Дисциплинарная поправка, руб.','Премия за монтаж к выплате, руб.','Ответственный производитель работ','Статус работника','Изменение','Дата внесения изменения','Статус объекта'];foreach($legacyHeaders as$header)assertSameValue(true,str_contains($sheets,htmlspecialchars($header,ENT_XML1|ENT_QUOTES,'UTF-8')),'M21 verified legacy header mapped into workbook: '.$header);
$historical=OtizSettlementV2Workbook::build($source+['mode'=>'history','exportedAt'=>'2026-10-01T12:00:00+03:00']);$hx=implode("\n",v2xml($historical['bytes']));assertSameValue(true,str_contains($hx,'Историческая выгрузка'),'history is not payment instruction');assertSameValue(true,str_contains($hx,'на момент выгрузки'),'live payment context timestamp qualified');assertSameValue(false,OtizSettlementV2Workbook::paymentExportAllowed($source,'blocked'),'#257 blocks current payment export');assertSameValue(true,OtizSettlementV2Workbook::historicalExportAllowed($source),'#257 preserves historical read');
foreach([[$source+['mode'=>'bogus'],'EXPORT_MODE_INVALID'],[array_replace($source,['mode'=>'payment','calculation'=>array_replace($source['calculation'],['status'=>'draft'])]),'PAYMENT_EXPORT_STATE_INVALID']]as[$payload,$code]){try{OtizSettlementV2Workbook::build($payload);throw new TestFailure('Expected '.$code);}catch(DomainException|InvalidArgumentException$e){assertSameValue($code,$e->getMessage(),'strict workbook mode/state admission');}}assertSameValue(false,OtizSettlementV2Workbook::paymentExportAllowed($source,'unknown'),'UNKNOWN admission blocks current payment export');
echo"settlement_v2_workbook_001_test: OK\n";
