<?php

declare(strict_types=1);
// FMONITOR_TEST_DB: real synthetic MariaDB snapshot/projection contract.
require dirname(__DIR__).'/Support/AssignmentOrderOriginalIntegrityTestBootstrap.php';
require dirname(__DIR__).'/Support/AssignmentOrderOriginalIntegrityCommits.php';
require dirname(__DIR__).'/Support/AssignmentOrderOriginalIntegrityDatabase.php';
require dirname(__DIR__).'/Support/AssignmentOrderOriginalIntegrityPersistenceObserver.php';
use FMonitor2\AssignmentOrderOriginal as O;
use FMonitor2\Tests\Support as S;

$f=null;$other=null;
try{
    $f=new S\OriginalIntegrityDatabase();$other=$f->connect();$db=$f->db;
    // These test-owned loose projection columns permit malformed native string rows.
    // Production still reads the same public named columns; no production DDL changes.
    $db->query('CREATE TABLE loose_fm2_assignment_orders(id VARCHAR(30),installation_case_id VARCHAR(30),version_no VARCHAR(30),control_engineer_user_id VARCHAR(30),order_date VARCHAR(30)) ENGINE=InnoDB');
    $db->query('CREATE TABLE loose_fm2_order_installers(assignment_order_id VARCHAR(30),installer_tab_id VARCHAR(30),change_action VARCHAR(30),valid_from VARCHAR(30),valid_to VARCHAR(30) NULL) ENGINE=InnoDB');
    $reset=static function()use($db){$db->query('DELETE FROM loose_fm2_order_installers');$db->query('DELETE FROM loose_fm2_assignment_orders');$db->query("INSERT INTO loose_fm2_assignment_orders VALUES('81','4512','1','31','2026-09-01')");$db->query("INSERT INTO loose_fm2_order_installers VALUES('81','7001','assign','2026-09-01',NULL),('81','7002','retain','2026-09-01',NULL)");};
    $rows=static fn()=>json_encode([$db->query('SELECT * FROM loose_fm2_assignment_orders ORDER BY BINARY id')->fetch_all(MYSQLI_ASSOC),$db->query('SELECT * FROM loose_fm2_order_installers ORDER BY BINARY installer_tab_id')->fetch_all(MYSQLI_ASSOC)],JSON_THROW_ON_ERROR);
    $reader=new O\AssignmentOrderOriginalMariaDbCompositionReader($db,'loose_');
    integrityCase('projection-canonical-string-control',function()use($reset,$reader){$reset();$v=$reader->find(4512,81);assertSameValue([O\AssignmentOrderCompositionLookupStatus::FOUND,4512,81,'composition-81-v1','388c7d94b3cf91235dabddf26398ac05f754d3d12a0b41a7a91ac3d5370faba5',[7001,7002],31],[$v->status,$v->installationCaseId,$v->assignmentOrderId,$v->identity,$v->sha256,$v->installerIds,$v->controlEngineerUserId],'canonical native strings project losslessly');});
    foreach(['id'=>['081','+81','81.0','8.1e1'],'installation_case_id'=>['04512','+4512','4512.0','9223372036854775808']] as $field=>$values)foreach($values as $i=>$value)integrityCase('order-row-protocol-'.$field.'-'.$i,function()use($reset,$reader,$db,$f,$rows,$field,$value){$reset();$db->query('UPDATE loose_fm2_assignment_orders SET '.$field.'='.$f->q($value));$before=$rows();$v=$reader->find(4512,81);assertSameValue([O\AssignmentOrderCompositionLookupStatus::UNAVAILABLE,null,null,[],null],[$v->status,$v->identity,$v->sha256,$v->installerIds,$v->controlEngineerUserId],'malformed matched SQL identity is unavailable');assertSameValue($before,$rows(),'no protocol row repair');});
    $badOrder=['zero-version'=>['version_no','0'],'padded-version'=>['version_no','01'],'overflow-version'=>['version_no','9223372036854775808'],
        'zero-engineer'=>['control_engineer_user_id','0'],'padded-engineer'=>['control_engineer_user_id','031'],'overflow-engineer'=>['control_engineer_user_id','9223372036854775808'],
        'zero-date'=>['order_date','0000-00-00'],'normalized-date'=>['order_date','2026-02-31'],'short-date'=>['order_date','2026-9-01']];
    foreach($badOrder as $name=>[$field,$value])integrityCase('found-invalid-order-'.$name,function()use($reset,$reader,$db,$f,$rows,$field,$value){$reset();if($value==='2026-02-31')$db->query("UPDATE loose_fm2_order_installers SET valid_from='2026-01-01'");$db->query('UPDATE loose_fm2_assignment_orders SET '.$field.'='.$f->q($value));$before=$rows();$v=$reader->find(4512,81);assertSameValue([O\AssignmentOrderCompositionLookupStatus::FOUND,null,null,[],null],[$v->status,$v->identity,$v->sha256,$v->installerIds,$v->controlEngineerUserId],'found invalid business composition is not a plausible snapshot');assertSameValue($before,$rows(),'invalid composition not repaired');});
    $badMembers=[
        'zero-id'=>['installer_tab_id','0'],'padded-id'=>['installer_tab_id','07001'],'signed-id'=>['installer_tab_id','+7001'],
        'fraction-id'=>['installer_tab_id','7001.0'],'overflow-id'=>['installer_tab_id','9223372036854775808'],
        'invalid-action'=>['change_action','mystery'],'from-zero'=>['valid_from','0000-00-00'],'from-normalized'=>['valid_from','2026-02-31'],
        'from-future'=>['valid_from','2026-09-02'],'to-normalized'=>['valid_to','2026-02-31'],'to-before-from'=>['valid_to','2026-08-31'],
    ];
    foreach($badMembers as $name=>[$field,$value])integrityCase('found-invalid-member-'.$name,function()use($reset,$reader,$db,$f,$rows,$field,$value){$reset();if($field==='valid_to'&&$value==='2026-02-31')$db->query("UPDATE loose_fm2_order_installers SET valid_from='2026-01-01' WHERE installer_tab_id='7001'");$db->query('UPDATE loose_fm2_order_installers SET '.$field.'='.$f->q($value)." WHERE installer_tab_id='7001'");$before=$rows();$v=$reader->find(4512,81);assertSameValue([O\AssignmentOrderCompositionLookupStatus::FOUND,null,null,[],null],[$v->status,$v->identity,$v->sha256,$v->installerIds,$v->controlEngineerUserId],'invalid member yields no partial valid projection');assertSameValue($before,$rows(),'invalid member not repaired');});
    integrityCase('member-query-echo-protocol',function()use($reset,$reader,$db){$reset();$db->query("UPDATE loose_fm2_order_installers SET assignment_order_id='081' WHERE installer_tab_id='7001'");assertSameValue(O\AssignmentOrderCompositionLookupStatus::UNAVAILABLE,$reader->find(4512,81)->status,'matched member must echo exact numeric order identity losslessly');});
    integrityCase('duplicate-order-unavailable',function()use($reset,$reader,$db){$reset();$db->query('INSERT INTO loose_fm2_assignment_orders SELECT * FROM loose_fm2_assignment_orders');assertSameValue(O\AssignmentOrderCompositionLookupStatus::UNAVAILABLE,$reader->find(4512,81)->status,'duplicate physical order never LIMIT1 precedence');});
    integrityCase('duplicate-member-across-action-invalid',function()use($reset,$reader,$db){$reset();$db->query("INSERT INTO loose_fm2_order_installers VALUES('81','7001','release','2026-09-01','2026-09-01')");$v=$reader->find(4512,81);assertSameValue([O\AssignmentOrderCompositionLookupStatus::FOUND,null,[]],[$v->status,$v->identity,$v->installerIds],'all action rows enforce unique member ownership');});
    integrityCase('release-and-coverage-control',function()use($reset,$reader,$db){$reset();$db->query("INSERT INTO loose_fm2_order_installers VALUES('81','7003','release','2026-08-01','2026-08-31'),('81','7004','assign','2026-08-01','2026-08-31')");$v=$reader->find(4512,81);assertSameValue([O\AssignmentOrderCompositionLookupStatus::FOUND,[7001,7002]],[$v->status,$v->installerIds],'released/expired rows do not join active members but remain validated');});
    integrityCase('observer-public-contract',function(){assertSameValue(true,interface_exists(O\AssignmentOrderOriginalPersistenceObserver::class),'INTENDED_RED: deterministic persistence observer');assertSameValue(['after_composition_order_read','before_read_release','before_write_begin','before_native_commit','after_native_commit','before_write_rollback','before_fresh_reader_close'],array_map(fn($v)=>$v->value,O\AssignmentOrderOriginalPersistenceEvent::cases()),'exact observer events');});
    integrityCase('real-consistent-order-member-snapshot',function()use($reset,$db,$other){
        $reset();$changed=0;$observer=new S\OriginalIntegrityPersistenceObserver(function($event)use($other,&$changed){if($event->value!=='after_composition_order_read')return;++$changed;$other->begin_transaction();try{$other->query("UPDATE loose_fm2_assignment_orders SET version_no='2',control_engineer_user_id='32',order_date='2026-09-02'");$other->query('DELETE FROM loose_fm2_order_installers');$other->query("INSERT INTO loose_fm2_order_installers VALUES('81','8001','assign','2026-09-01',NULL)");$other->commit();}catch(Throwable $e){$other->rollback();throw $e;}});
        $reader=new O\AssignmentOrderOriginalMariaDbCompositionReader($db,'loose_',$observer);$v=$reader->find(4512,81);
        assertSameValue(1,$changed,'observer causally commits other writer after order read');assertSameValue([O\AssignmentOrderCompositionLookupStatus::FOUND,'composition-81-v1',[7001,7002],31,'388c7d94b3cf91235dabddf26398ac05f754d3d12a0b41a7a91ac3d5370faba5'],[$v->status,$v->identity,$v->installerIds,$v->controlEngineerUserId,$v->sha256],'one old snapshot, never old order plus new members');
        $new=(new O\AssignmentOrderOriginalMariaDbCompositionReader($db,'loose_'))->find(4512,81);assertSameValue(['composition-81-v2',[8001],32,hash('sha256','{"caseId":4512,"compositionIdentity":"composition-81-v2","engineerUserId":32,"installers":[8001],"orderId":81}')],[$new->identity,$new->installerIds,$new->controlEngineerUserId,$new->sha256],'next invocation observes complete new committed composition');assertSameValue('0',(string)$db->query('SELECT @@in_transaction active')->fetch_assoc()['active'],'read transaction released');
    });
    integrityCase('read-release-observer-failure-unavailable',function()use($reset,$db){$reset();$observer=new S\OriginalIntegrityPersistenceObserver(function($event){if($event->value==='before_read_release')throw new RuntimeException('synthetic read release observer');});$v=(new O\AssignmentOrderOriginalMariaDbCompositionReader($db,'loose_',$observer))->find(4512,81);assertSameValue(O\AssignmentOrderCompositionLookupStatus::UNAVAILABLE,$v->status,'unconfirmed read release cannot expose found snapshot');assertSameValue('0',(string)$db->query('SELECT @@in_transaction active')->fetch_assoc()['active'],'observer cannot strand read transaction');});
    integrityCase('composition-active-caller-transaction',function()use($reset,$db,$reader){$reset();$db->begin_transaction();try{$db->query("UPDATE loose_fm2_assignment_orders SET version_no='2'");assertSameValue(O\AssignmentOrderCompositionLookupStatus::UNAVAILABLE,$reader->find(4512,81)->status,'caller transaction not replaced');assertSameValue('1',(string)$db->query('SELECT @@in_transaction active')->fetch_assoc()['active'],'caller still owns transaction');}finally{$db->rollback();}assertSameValue('1',$db->query('SELECT version_no FROM loose_fm2_assignment_orders')->fetch_assoc()['version_no'],'caller rollback preserved');});
    integrityCase('not-found-never-probes-members',function()use($reset,$db,$reader){$reset();$db->query("UPDATE loose_fm2_assignment_orders SET installation_case_id='9999'");$db->query('DROP TABLE loose_fm2_order_installers');assertSameValue(O\AssignmentOrderCompositionLookupStatus::NOT_FOUND,$reader->find(4512,81)->status,'different canonical case no member probe');assertSameValue(O\AssignmentOrderCompositionLookupStatus::NOT_FOUND,$reader->find(4512,9999)->status,'absent order no member probe');});
}finally{if($other!==null)$other->close();if($f!==null)$f->close();}
integrityDone('ASSIGNMENT_ORDER_ORIGINAL_DATA_MARIADB_COMPOSITION_OK');
