<?php
declare(strict_types=1);
require dirname(__DIR__).'/bootstrap.php';

use FMonitor2\AssignmentOrderOriginal\AssignmentOrderOriginalAuthorizer;
use FMonitor2\AssignmentOrderOriginal\AssignmentOrderOriginalAuthorizationStatus;
use FMonitor2\AssignmentOrderOriginal\AssignmentOrderOriginalByteStream;
use FMonitor2\AssignmentOrderOriginal\AssignmentOrderOriginalDependencies;
use FMonitor2\AssignmentOrderOriginal\AssignmentOrderOriginalMode;
use FMonitor2\AssignmentOrderOriginal\AssignmentOrderOriginalReason;
use FMonitor2\AssignmentOrderOriginal\AssignmentOrderOriginalStatus;
use FMonitor2\AssignmentOrderOriginal\AssignmentOrderOriginalStreamRead;
use FMonitor2\AssignmentOrderOriginal\AssignmentOrderOriginalStreamReadStatus;
use FMonitor2\AssignmentOrderOriginal\AssignmentOrderOriginalUpload;
use FMonitor2\AssignmentOrderOriginal\AssignmentOrderOriginalVerificationFactory;
use FMonitor2\AssignmentOrderOriginal\SubmitAssignmentOrderOriginalCommand;
use FMonitor2\Tests\Support\InMemoryAssignmentOrderOriginalInitialEnvironment;

require_once dirname(__DIR__,2).'/app/AssignmentOrderOriginal/AssignmentOrderOriginalApplication.php';require dirname(__DIR__).'/Support/InMemoryAssignmentOrderOriginalInitialEnvironment.php';
$pdf=(string)base64_decode('JVBERi0xLjQKMSAwIG9iago8PCAvVHlwZSAvQ2F0YWxvZyAvUGFnZXMgMiAwIFIgPj4KZW5kb2JqCjIgMCBvYmoKPDwgL1R5cGUgL1BhZ2VzIC9LaWRzIFszIDAgUl0gL0NvdW50IDEgPj4KZW5kb2JqCjMgMCBvYmoKPDwgL1R5cGUgL1BhZ2UgL1BhcmVudCAyIDAgUiAvTWVkaWFCb3ggWzAgMCA3MiA3Ml0gPj4KZW5kb2JqCnhyZWYKMCA0CjAwMDAwMDAwMDAgNjU1MzUgZiAKMDAwMDAwMDAwOSAwMDAwMCBuIAowMDAwMDAwMDU4IDAwMDAwIG4gCjAwMDAwMDAxMTUgMDAwMDAgbiAKdHJhaWxlcgo8PCAvU2l6ZSA0IC9Sb290IDEgMCBSID4+CnN0YXJ0eHJlZgoxODQKJSVFT0YK',true);
$stream=static function(int&$reads)use($pdf):AssignmentOrderOriginalByteStream{return new class($pdf,$reads)implements AssignmentOrderOriginalByteStream{private int$o=0;public function __construct(private string$b,private int&$r){}public function read(int$m):AssignmentOrderOriginalStreamRead{$this->r++;if($this->o===strlen($this->b))return new AssignmentOrderOriginalStreamRead(AssignmentOrderOriginalStreamReadStatus::EOF,'');$x=substr($this->b,$this->o,$m);$this->o+=strlen($x);return new AssignmentOrderOriginalStreamRead(AssignmentOrderOriginalStreamReadStatus::BYTES,$x);}public function close():void{}};};
$command=static fn(string$id,AssignmentOrderOriginalMode$mode,AssignmentOrderOriginalByteStream$s,string$date='2026-09-01',?string$root=null,?string$target=null,?string$expected=null,?string$reason=null)=>new SubmitAssignmentOrderOriginalCommand($id,$mode,4512,81,18,$date,true,$root,$target,$expected,$reason,new AssignmentOrderOriginalUpload($s,'signed.pdf','application/pdf'));
$rejected=static fn($r)=>[$r->status(),$r->reasonCode(),$r->retryable(),$r->rootOriginalId(),$r->currentRevisionId()];
$publicResult=static fn($r)=>[$r->status()->value,$r->reasonCode()?->value,$r->retryable(),$r->requestId(),$r->rootOriginalId(),$r->currentRevisionId(),$r->revisionNumber(),$r->documentDate(),$r->sha256(),$r->byteSize(),$r->uploadedAt()];
$assertSafeLogs=static function(array$logs,array$expectedPhases,string$scenario):void{assertSameValue(count($expectedPhases),count($logs),$scenario.' exact safe-log count.');foreach($logs as$index=>$log){assertSameValue(['event','safeFields'],array_keys($log),$scenario.' log envelope allowlist.');assertSameValue('ASSIGNMENT_ORDER_ORIGINAL_CONTENT_LEASE_RELEASE_FAILED',$log['event'],$scenario.' exact event.');assertSameValue(['correlation_id','phase'],array_keys($log['safeFields']),$scenario.' safe fields allowlist.');assertSameValue(1,preg_match('/^[0-9a-f]{12}$/D',(string)$log['safeFields']['correlation_id']),$scenario.' correlation is opaque.');assertSameValue($expectedPhases[$index],$log['safeFields']['phase'],$scenario.' exact phase.');}};

foreach([
    ['NOT-A-UUID',AssignmentOrderOriginalMode::INITIAL,'2026-09-01',null,null,null,null],
    ['00000000-0000-4000-8000-000000000201',AssignmentOrderOriginalMode::INITIAL,'2026-02-30',null,null,null,null],
    ['00000000-0000-4000-8000-000000000202',AssignmentOrderOriginalMode::INITIAL,'2026-09-01','unexpected-root',null,null,null],
    ['00000000-0000-4000-8000-000000000203',AssignmentOrderOriginalMode::CORRECTION,'2026-09-01',null,null,null,'reason'],
    ['00000000-0000-4000-8000-000000000204',AssignmentOrderOriginalMode::CORRECTION,'2026-09-01','root','revision','revision','   '],
]as[$id,$mode,$date,$root,$target,$expected,$reason]){$env=new InMemoryAssignmentOrderOriginalInitialEnvironment();$reads=0;$result=AssignmentOrderOriginalVerificationFactory::create($env->dependencies())->submitAssignmentOrderOriginal($command($id,$mode,$stream($reads),$date,$root,$target,$expected,$reason));assertSameValue([AssignmentOrderOriginalStatus::REJECTED,AssignmentOrderOriginalReason::INVALID_COMMAND,false,null,null],$rejected($result),'Malformed shape/date/lineage/reason is typed INVALID_COMMAND.');assertSameValue([0,0,0,0],[$env->authorizationCalls,$reads,$env->requestLookupCalls,count($env->storageEvents)],'Malformed command fails before authorization, repository and stream/storage work.');}

$faults=[
    'authorizer'=>AssignmentOrderOriginalReason::PERSISTENCE_FAILURE,'request_lookup'=>AssignmentOrderOriginalReason::PERSISTENCE_FAILURE,
    'composition'=>AssignmentOrderOriginalReason::PERSISTENCE_FAILURE,'clock'=>AssignmentOrderOriginalReason::PERSISTENCE_FAILURE,
    'lifecycle'=>AssignmentOrderOriginalReason::PERSISTENCE_FAILURE,'stage_begin'=>AssignmentOrderOriginalReason::STORAGE_FAILURE,
    'fault_injector'=>AssignmentOrderOriginalReason::STORAGE_FAILURE,'storage_observer'=>AssignmentOrderOriginalReason::STORAGE_FAILURE,
    'stage_write'=>AssignmentOrderOriginalReason::STORAGE_FAILURE,'stage_completed'=>AssignmentOrderOriginalReason::STORAGE_FAILURE,
    'inspector'=>AssignmentOrderOriginalReason::STORAGE_FAILURE,'fingerprint_lookup'=>AssignmentOrderOriginalReason::PERSISTENCE_FAILURE,
    'stage_finalize'=>AssignmentOrderOriginalReason::STORAGE_FAILURE,'root_id'=>AssignmentOrderOriginalReason::PERSISTENCE_FAILURE,
    'revision_id'=>AssignmentOrderOriginalReason::PERSISTENCE_FAILURE,'commit_accepted'=>AssignmentOrderOriginalReason::PERSISTENCE_FAILURE,
    'lineage_lookup'=>AssignmentOrderOriginalReason::PERSISTENCE_FAILURE,
];
$faultIndex=250;foreach($faults as$phase=>$expectedReason){$faultIndex++;$fault=new InMemoryAssignmentOrderOriginalInitialEnvironment();$app=AssignmentOrderOriginalVerificationFactory::create($fault->dependencies());$mode=AssignmentOrderOriginalMode::INITIAL;$root=$target=null;if($phase==='lineage_lookup'){$reads=0;$accepted=$app->submitAssignmentOrderOriginal($command(sprintf('00000000-0000-4000-8000-%012d',900+$faultIndex),$mode,$stream($reads)));$fault->allowedCapability='assignment_order.original.correct';$mode=AssignmentOrderOriginalMode::CORRECTION;$root=$accepted->rootOriginalId();$target=$accepted->currentRevisionId();}$fault->throwAt=$phase;$reads=0;$caught=null;try{$result=$app->submitAssignmentOrderOriginal($command(sprintf('00000000-0000-4000-8000-%012d',$faultIndex),$mode,$stream($reads),'2026-09-01',$root,$target,$target,$mode===AssignmentOrderOriginalMode::CORRECTION?'reason':null));}catch(Throwable$e){$caught=$e;}assertSameValue(null,$caught,'Dependency Throwable is total at phase '.$phase);assertSameValue([AssignmentOrderOriginalStatus::FAILED,$expectedReason,true],[$result->status(),$result->reasonCode(),$result->retryable()],'Dependency Throwable has exact typed result at '.$phase);if(in_array($phase,['stage_write','stage_completed','inspector','fingerprint_lookup','stage_finalize'],true))assertSameValue(true,in_array('STAGE_CLOSE',$fault->storageEvents,true)&&in_array('ABORT_BEGIN',$fault->storageEvents,true),'Pre-finalize Throwable aborts and closes stage at '.$phase);if(in_array($phase,['root_id','revision_id','commit_accepted'],true))assertSameValue(1,$fault->leaseReleaseCalls,'Post-finalize Throwable releases lease exactly once at '.$phase);$public=json_encode([$publicResult($result),$fault->safeLogs],JSON_THROW_ON_ERROR);assertSameValue(false,str_contains($public,$fault->throwSecret),'Unique dependency secret never leaks at '.$phase);$assertSafeLogs($fault->safeLogs,[],'fault '.$phase);}
$fullPortTrace=['fault:stage','observer:stage_begin','fault:stage_write','observer:stage_write','observer:stage_done','fault:private_finalize','observer:finalize_begin','observer:finalize_done','fault:stage_close','observer:stage_close'];
foreach(['lifecycle'=>3,'fault_injector'=>4,'storage_observer'=>6]as$phase=>$calls)for($call=1;$call<=$calls;$call++){$multi=new InMemoryAssignmentOrderOriginalInitialEnvironment();$multi->throwOnCall[$phase]=$call;$reads=0;try{$multiResult=AssignmentOrderOriginalVerificationFactory::create($multi->dependencies())->submitAssignmentOrderOriginal($command(sprintf('00000000-0000-4000-8000-%012d',300+$call+($phase==='lifecycle'?0:($phase==='fault_injector'?10:20))),AssignmentOrderOriginalMode::INITIAL,$stream($reads)));$multiThrown=null;}catch(Throwable$e){$multiThrown=$e;}assertSameValue(null,$multiThrown,'Multi-call '.$phase.' #'.$call.' is total.');$afterCommit=($phase==='fault_injector'&&$call===4)||($phase==='storage_observer'&&$call===6);$expectedStatus=$afterCommit?AssignmentOrderOriginalStatus::ACCEPTED:AssignmentOrderOriginalStatus::FAILED;assertSameValue($expectedStatus,$multiResult->status(),'Multi-call '.$phase.' #'.$call.' exact committed boundary.');assertSameValue(false,str_contains(json_encode([$publicResult($multiResult),$multi->safeLogs],JSON_THROW_ON_ERROR),$multi->throwSecret),'Multi-call secret absent.');if($phase!=='lifecycle'){$prefix=$phase==='fault_injector'?'fault:':'observer:';$positions=array_keys(array_filter($fullPortTrace,static fn($event)=>str_starts_with($event,$prefix)));$stop=$positions[$call-1];assertSameValue(array_slice($fullPortTrace,0,$stop+1),$multi->portTrace,'Exact typed port event order at '.$phase.' #'.$call);}$assertSafeLogs($multi->safeLogs,[],'multi '.$phase.' '.$call);}

$auditFault=new InMemoryAssignmentOrderOriginalInitialEnvironment();$auditFault->allowedCapability='other';$auditFault->throwAt='commit_attempt';$reads=0;try{$auditResult=AssignmentOrderOriginalVerificationFactory::create($auditFault->dependencies())->submitAssignmentOrderOriginal($command('00000000-0000-4000-8000-000000000240',AssignmentOrderOriginalMode::INITIAL,$stream($reads)));$auditThrown=null;}catch(Throwable$e){$auditThrown=$e;}assertSameValue(null,$auditThrown,'Attempt-audit Throwable is total.');assertSameValue([AssignmentOrderOriginalStatus::FAILED,AssignmentOrderOriginalReason::PERSISTENCE_FAILURE],[$auditResult->status(),$auditResult->reasonCode()],'Attempt-audit Throwable has exact failure.');assertSameValue(false,str_contains(json_encode([$publicResult($auditResult),$auditFault->safeLogs],JSON_THROW_ON_ERROR),$auditFault->throwSecret),'Audit exception secret is absent.');$assertSafeLogs($auditFault->safeLogs,[],'audit fault');
$unknownFault=new InMemoryAssignmentOrderOriginalInitialEnvironment();$unknownFault->commitOutcome=\FMonitor2\AssignmentOrderOriginal\AssignmentOrderOriginalCommitStatus::OUTCOME_UNKNOWN;$unknownFault->throwOnCall['request_lookup']=2;$reads=0;try{$unknownResult=AssignmentOrderOriginalVerificationFactory::create($unknownFault->dependencies())->submitAssignmentOrderOriginal($command('00000000-0000-4000-8000-000000000241',AssignmentOrderOriginalMode::INITIAL,$stream($reads)));$unknownThrown=null;}catch(Throwable$e){$unknownThrown=$e;}assertSameValue(null,$unknownThrown,'Outcome-resolution lookup Throwable is total.');assertSameValue([AssignmentOrderOriginalStatus::FAILED,AssignmentOrderOriginalReason::PERSISTENCE_OUTCOME_UNKNOWN],[$unknownResult->status(),$unknownResult->reasonCode()],'Unknown commit plus unavailable fresh lookup stays outcome unknown.');assertSameValue(1,$unknownFault->leaseReleaseCalls,'Outcome lookup fault still releases lease exactly once.');$assertSafeLogs($unknownFault->safeLogs,[],'outcome lookup');

foreach(['fingerprint_lookup'=>'identical','lineage_lookup'=>'different']as$phase=>$raceMode){$cas=new InMemoryAssignmentOrderOriginalInitialEnvironment();$casApp=AssignmentOrderOriginalVerificationFactory::create($cas->dependencies());$reads=0;$baseRevision=$casApp->submitAssignmentOrderOriginal($command('00000000-0000-4000-8000-000000000242',AssignmentOrderOriginalMode::INITIAL,$stream($reads)));$cas->allowedCapability='assignment_order.original.correct';$cas->commitRace=$raceMode;$cas->throwOnCall[$phase]=($cas->phaseCalls[$phase]??0)+2;$cas->repositoryTrace=[];$cas->storageEvents=[];$reads=0;try{$casResult=$casApp->submitAssignmentOrderOriginal($command($phase==='fingerprint_lookup'?'00000000-0000-4000-8000-000000000243':'00000000-0000-4000-8000-000000000244',AssignmentOrderOriginalMode::CORRECTION,$stream($reads),'2026-09-02',$baseRevision->rootOriginalId(),$baseRevision->currentRevisionId(),$baseRevision->currentRevisionId(),'CAS'));$casThrown=null;}catch(Throwable$e){$casThrown=$e;}assertSameValue(null,$casThrown,'Post-CAS '.$phase.' reread Throwable is total while content lease is held.');assertSameValue([AssignmentOrderOriginalStatus::FAILED,AssignmentOrderOriginalReason::PERSISTENCE_FAILURE,true,1],[$casResult->status(),$casResult->reasonCode(),$casResult->retryable(),$cas->leaseReleaseCalls-1],'Post-CAS reread fault maps safely and releases correction lease once.');$held=array_values(array_filter($cas->repositoryTrace,static fn($event)=>str_ends_with($event,':held')));$expectedHeld=$phase==='fingerprint_lookup'?['commit:held','fingerprint_lookup:held']:['commit:held','fingerprint_lookup:held','lineage_lookup:held'];assertSameValue($expectedHeld,$held,'Post-CAS held-lease trace is exact at '.$phase);assertSameValue(['STAGE_BEGIN','STAGE_WRITE:327','STAGE_DONE','FINALIZE_BEGIN','FINALIZE_DONE','STAGE_CLOSE'],$cas->storageEvents,'Post-CAS fault finalizes then closes exactly at '.$phase);$assertSafeLogs($cas->safeLogs,[],'post-CAS '.$phase);}
$conflictAudit=new InMemoryAssignmentOrderOriginalInitialEnvironment();$conflictAuditApp=AssignmentOrderOriginalVerificationFactory::create($conflictAudit->dependencies());$reads=0;$conflictBase=$conflictAuditApp->submitAssignmentOrderOriginal($command('00000000-0000-4000-8000-000000000247',AssignmentOrderOriginalMode::INITIAL,$stream($reads)));$conflictAudit->allowedCapability='assignment_order.original.correct';$conflictAudit->commitRace='different';$conflictAudit->throwAt='commit_attempt';$reads=0;try{$conflictAuditResult=$conflictAuditApp->submitAssignmentOrderOriginal($command('00000000-0000-4000-8000-000000000248',AssignmentOrderOriginalMode::CORRECTION,$stream($reads),'2026-09-02',$conflictBase->rootOriginalId(),$conflictBase->currentRevisionId(),$conflictBase->currentRevisionId(),'CAS'));$conflictAuditThrown=null;}catch(Throwable$e){$conflictAuditThrown=$e;}assertSameValue(null,$conflictAuditThrown,'CAS conflict audit Throwable is total.');assertSameValue([AssignmentOrderOriginalStatus::FAILED,AssignmentOrderOriginalReason::PERSISTENCE_FAILURE,1],[$conflictAuditResult->status(),$conflictAuditResult->reasonCode(),$conflictAudit->leaseReleaseCalls-1],'CAS audit failure follows one lease release and becomes persistence failure.');$assertSafeLogs($conflictAudit->safeLogs,[],'CAS audit failure');

$releaseConflict=new InMemoryAssignmentOrderOriginalInitialEnvironment();$releaseApp=AssignmentOrderOriginalVerificationFactory::create($releaseConflict->dependencies());$reads=0;$releaseBase=$releaseApp->submitAssignmentOrderOriginal($command('00000000-0000-4000-8000-000000000245',AssignmentOrderOriginalMode::INITIAL,$stream($reads)));$releaseConflict->allowedCapability='assignment_order.original.correct';$releaseConflict->commitRace='different';$releaseConflict->leaseReleaseFault='throw';$reads=0;$selected=$releaseApp->submitAssignmentOrderOriginal($command('00000000-0000-4000-8000-000000000246',AssignmentOrderOriginalMode::CORRECTION,$stream($reads),'2026-09-02',$releaseBase->rootOriginalId(),$releaseBase->currentRevisionId(),$releaseBase->currentRevisionId(),'CAS'));assertSameValue([AssignmentOrderOriginalStatus::CONFLICT,AssignmentOrderOriginalReason::STALE_REVISION],[$selected->status(),$selected->reasonCode()],'Release failure cannot replace already selected CAS conflict.');assertSameValue(['correlation_id','phase'],array_keys($releaseConflict->safeLogs[0]['safeFields']??[]),'Release failure safe log has exact allowlist.');$assertSafeLogs($releaseConflict->safeLogs,['commit_conflict'],'CAS release failure');
foreach(['stage_abort','stage_close']as$index=>$phase){$cleanup=new InMemoryAssignmentOrderOriginalInitialEnvironment();$cleanup->storageFault='write';$cleanup->throwAt=$phase;$reads=0;try{$cleanupResult=AssignmentOrderOriginalVerificationFactory::create($cleanup->dependencies())->submitAssignmentOrderOriginal($command(sprintf('00000000-0000-4000-8000-%012d',270+$index),AssignmentOrderOriginalMode::INITIAL,$stream($reads)));$cleanupThrown=null;}catch(Throwable$e){$cleanupThrown=$e;}assertSameValue(null,$cleanupThrown,'Cleanup Throwable is total at '.$phase);assertSameValue([AssignmentOrderOriginalStatus::FAILED,AssignmentOrderOriginalReason::STORAGE_FAILURE],[$cleanupResult->status(),$cleanupResult->reasonCode()],'Cleanup Throwable preserves storage failure at '.$phase);assertSameValue(false,str_contains(json_encode([$publicResult($cleanupResult),$cleanup->safeLogs],JSON_THROW_ON_ERROR),$cleanup->throwSecret),'Cleanup secret absent at '.$phase);$assertSafeLogs($cleanup->safeLogs,[],'cleanup '.$phase);}

$streamFault=new InMemoryAssignmentOrderOriginalInitialEnvironment();$closed=0;$throwingStream=new class($closed)implements AssignmentOrderOriginalByteStream{public function __construct(private int&$closed){}public function read(int$m):AssignmentOrderOriginalStreamRead{throw new RuntimeException('SECRET-STREAM-DETAIL');}public function close():void{$this->closed++;}};try{$streamResult=AssignmentOrderOriginalVerificationFactory::create($streamFault->dependencies())->submitAssignmentOrderOriginal($command('00000000-0000-4000-8000-000000000275',AssignmentOrderOriginalMode::INITIAL,$throwingStream));$streamThrown=null;}catch(Throwable$e){$streamThrown=$e;}assertSameValue(null,$streamThrown,'Stream Throwable is total.');assertSameValue([AssignmentOrderOriginalStatus::FAILED,AssignmentOrderOriginalReason::STREAM_FAILURE,true,1],[$streamResult->status(),$streamResult->reasonCode(),$streamResult->retryable(),$closed],'Stream Throwable maps exactly and closes once.');assertSameValue(false,str_contains(json_encode([$publicResult($streamResult),$streamFault->safeLogs],JSON_THROW_ON_ERROR),'SECRET-STREAM-DETAIL'),'Stream secret does not leak.');$assertSafeLogs($streamFault->safeLogs,[],'stream fault');

$closeFault=new InMemoryAssignmentOrderOriginalInitialEnvironment();$offset=0;$closeCalls=0;$closeStream=new class($pdf,$offset,$closeCalls)implements AssignmentOrderOriginalByteStream{public function __construct(private string$bytes,private int&$offset,private int&$closes){}public function read(int$m):AssignmentOrderOriginalStreamRead{if($this->offset===strlen($this->bytes))return new AssignmentOrderOriginalStreamRead(AssignmentOrderOriginalStreamReadStatus::EOF,'');$chunk=substr($this->bytes,$this->offset,$m);$this->offset+=strlen($chunk);return new AssignmentOrderOriginalStreamRead(AssignmentOrderOriginalStreamReadStatus::BYTES,$chunk);}public function close():void{$this->closes++;throw new RuntimeException('SECRET-CLOSE-DETAIL');}};try{$closeResult=AssignmentOrderOriginalVerificationFactory::create($closeFault->dependencies())->submitAssignmentOrderOriginal($command('00000000-0000-4000-8000-000000000276',AssignmentOrderOriginalMode::INITIAL,$closeStream));$closeThrown=null;}catch(Throwable$e){$closeThrown=$e;}assertSameValue(null,$closeThrown,'Stream close Throwable after commit does not escape.');assertSameValue(AssignmentOrderOriginalStatus::ACCEPTED,$closeResult->status(),'Stream close fault cannot erase committed accepted fact.');assertSameValue(false,str_contains(json_encode([$publicResult($closeResult),$closeFault->safeLogs],JSON_THROW_ON_ERROR),'SECRET-CLOSE-DETAIL'),'Close secret does not leak.');$assertSafeLogs($closeFault->safeLogs,[],'stream close');

foreach(['lease_release','safe_log','delivery']as$index=>$phase){$post=new InMemoryAssignmentOrderOriginalInitialEnvironment();if($phase==='safe_log')$post->leaseReleaseFault='throw';$post->throwAt=$phase;$reads=0;try{$postResult=AssignmentOrderOriginalVerificationFactory::create($post->dependencies())->submitAssignmentOrderOriginal($command(sprintf('00000000-0000-4000-8000-%012d',280+$index),AssignmentOrderOriginalMode::INITIAL,$stream($reads)));$postThrown=null;}catch(Throwable$e){$postThrown=$e;}assertSameValue(null,$postThrown,'Post-commit observer Throwable does not escape at '.$phase);assertSameValue(AssignmentOrderOriginalStatus::ACCEPTED,$postResult->status(),'Committed fact remains accepted at '.$phase);assertSameValue(false,str_contains(json_encode([$publicResult($postResult),$post->safeLogs],JSON_THROW_ON_ERROR),$post->throwSecret),'Post-commit secret absent at '.$phase);$assertSafeLogs($post->safeLogs,$phase==='lease_release'?['committed']:[],'post-commit '.$phase);}

$env=new InMemoryAssignmentOrderOriginalInitialEnvironment();$firstDependencies=$env->dependencies();$reads=0;$initial=AssignmentOrderOriginalVerificationFactory::create($firstDependencies)->submitAssignmentOrderOriginal($command('00000000-0000-4000-8000-000000000205',AssignmentOrderOriginalMode::INITIAL,$stream($reads)));$env->allowedCapability='assignment_order.original.correct';$restart=unserialize(serialize($env),['allowed_classes'=>true]);assertSameValue(false,$restart===$env,'Restart crosses a serialization/reconstruction boundary.');$reads=0;$restartDependencies=$restart->dependencies();assertSameValue(false,$firstDependencies->repository===$restartDependencies->repository,'Restart uses a newly constructed repository adapter over durable evidence.');$fresh=AssignmentOrderOriginalVerificationFactory::create($restartDependencies);$noChange=$fresh->submitAssignmentOrderOriginal($command('00000000-0000-4000-8000-000000000206',AssignmentOrderOriginalMode::CORRECTION,$stream($reads),'2026-09-01',$initial->rootOriginalId(),$initial->currentRevisionId(),$initial->currentRevisionId(),'new reason'));assertSameValue([AssignmentOrderOriginalStatus::REJECTED,AssignmentOrderOriginalReason::NO_CHANGES],[$noChange->status(),$noChange->reasonCode()],'NO_CHANGES derives from committed lineage after fresh application construction.');

$race=new InMemoryAssignmentOrderOriginalInitialEnvironment();$app=AssignmentOrderOriginalVerificationFactory::create($race->dependencies());$reads=0;$one=$app->submitAssignmentOrderOriginal($command('00000000-0000-4000-8000-000000000207',AssignmentOrderOriginalMode::INITIAL,$stream($reads)));$race->allowedCapability='assignment_order.original.correct';$reads=0;$two=$app->submitAssignmentOrderOriginal($command('00000000-0000-4000-8000-000000000208',AssignmentOrderOriginalMode::CORRECTION,$stream($reads),'2026-09-02',$one->rootOriginalId(),$one->currentRevisionId(),$one->currentRevisionId(),'date'));$race->repositoryTrace=[];$reads=0;$replay=$app->submitAssignmentOrderOriginal($command('00000000-0000-4000-8000-000000000209',AssignmentOrderOriginalMode::CORRECTION,$stream($reads),'2026-09-02',$one->rootOriginalId(),$one->currentRevisionId(),$one->currentRevisionId(),'another reason'));assertSameValue([AssignmentOrderOriginalStatus::REPLAYED,$two->currentRevisionId()],[$replay->status(),$replay->currentRevisionId()],'Accepted fingerprint replay wins before stale/current checks after leaf moves.');$fingerprint=array_search('fingerprint_lookup:released',$race->repositoryTrace,true);$lineage=array_search('lineage_lookup:released',$race->repositoryTrace,true);assertSameValue(true,is_int($fingerprint)&&$lineage===false,'Replay trace performs fingerprint lookup and returns without any stale lineage lookup.');

fwrite(STDOUT,"ASSIGNMENT_ORDER_ORIGINAL_UPLOAD_TOTALITY_REPLAY_OK\n");
