<?php

declare(strict_types=1);
// FMONITOR_TEST_DB: real fresh reader, read-only principal, bounded pending-writer proof.
require dirname(__DIR__).'/Support/AssignmentOrderOriginalIntegrityTestBootstrap.php';
require dirname(__DIR__).'/Support/AssignmentOrderOriginalIntegrityCommits.php';
require dirname(__DIR__).'/Support/AssignmentOrderOriginalIntegrityDatabase.php';
require dirname(__DIR__).'/Support/AssignmentOrderOriginalIntegrityPersistenceObserver.php';
require dirname(__DIR__).'/Support/AssignmentOrderOriginalIntegrityFreshProcess.php';
require dirname(__DIR__).'/Support/AssignmentOrderOriginalIntegrityFactoryWiring.php';
use FMonitor2\AssignmentOrderOriginal as O;
use FMonitor2\Tests\Support as S;

function integrityRequireFreshApi():void
{if(!class_exists(O\AssignmentOrderOriginalMariaDbFreshTerminalReaderFactory::class))throw new TestFailure('INTENDED_RED: real fresh-reader factory declaration absent');}
function integrityFreshConfig(S\OriginalIntegrityDatabase $f,array $changes=[]):O\AssignmentOrderOriginalFreshReaderConfig
{return new O\AssignmentOrderOriginalFreshReaderConfig(...($changes+['databaseHost'=>$f->host,'databasePort'=>$f->port,'databaseName'=>$f->database,'databaseUser'=>$f->user,'databasePasswordFile'=>$f->passwordFile,'tablePrefix'=>$f->prefix]));}
function integrityChildFresh(S\OriginalIntegrityDatabase $f,array $configuration):array
{
    $r=S\OriginalIntegrityFreshProcess::run($f,'00000000-0000-4000-8000-000000000001',$configuration);
    if($r['exit']===42)throw new TestFailure('INTENDED_RED: real fresh-reader child API absent');
    assertSameValue(false,$r['timedOut'],'fresh proof child bounded to ten seconds');assertSameValue(0,$r['exit'],'fresh child protocol exits successfully');assertSameValue('',$r['error'],'no raw child exception/SQL/config output');
    $v=json_decode($r['out'],true,32,JSON_THROW_ON_ERROR);assertSameValue(true,$v['opened'],'read-only configured factory really opened, unavailable-all cannot pass');assertSameValue('closed',$v['close'],'child closes its owned reader');return $v;
}
$f=null;$readUser=null;$userCreated=false;
try{
    $f=new S\OriginalIntegrityDatabase();$token=substr($f->database,-12);$readUser='u_aoou_fresh_'.$token;$readPassword=bin2hex(random_bytes(16));$readPasswordFile=$f->control.'/reader-password';
    try{$f->db->query('CREATE USER '.$f->q($readUser)."@'%' IDENTIFIED BY ".$f->q($readPassword).' WITH MAX_STATEMENT_TIME 2');$userCreated=true;$f->db->query('GRANT SELECT ON `'.$f->database.'`.* TO '.$f->q($readUser)."@'%'");}
    catch(Throwable){throw new RuntimeException('SETUP_FAILURE: owned read-only principal unavailable');}
    file_put_contents($readPasswordFile,$readPassword."\n");chmod($readPasswordFile,0600);
    $limited=['databaseUser'=>$readUser,'databasePasswordFile'=>$readPasswordFile];
    integrityCase('read-only-principal-time-bound-control',function()use($f,$readUser,$readPassword){$db=new mysqli($f->host,$readUser,$readPassword,$f->database,$f->port);try{assertSameValue(2.0,(float)$db->query('SELECT @@max_statement_time n')->fetch_assoc()['n'],'account limits test SELECT wait without changing global/shared settings');$failed=false;try{$db->query('DELETE FROM `'.$f->prefix.'fm2_assignment_order_original_roots` WHERE 1=0');}catch(mysqli_sql_exception){$failed=true;}assertSameValue(true,$failed,'test recovery principal has SELECT only');}finally{$db->close();}});
    integrityCase('fresh-factory-lazy-config-control',function()use($f){integrityRequireFreshApi();$missing=$f->control.'/not-created-password';$factory=new O\AssignmentOrderOriginalMariaDbFreshTerminalReaderFactory(integrityFreshConfig($f,['databasePasswordFile'=>$missing]));assertSameValue(false,file_exists($missing),'constructor never creates or repairs credential file');$opened=$factory->open();assertSameValue([O\AssignmentOrderOriginalFreshReaderOpenStatus::UNAVAILABLE,null],[$opened->status,$opened->reader],'missing credential is typed unavailable');assertSameValue(false,file_exists($missing),'open never creates missing file');});
    $configInvalid=['databaseHost'=>['p:127.0.0.1','host;port=1234','/tmp/mysql.sock'],'databasePort'=>[0,65536],'databaseName'=>['bad`name',''],'databaseUser'=>['bad user',''],'tablePrefix'=>['bad`prefix',str_repeat('p',26)],'databasePasswordFile'=>['relative-password']];
    foreach($configInvalid as $field=>$values)foreach($values as $i=>$value)integrityCase('fresh-invalid-config-'.$field.'-'.$i,function()use($f,$field,$value){integrityRequireFreshApi();$before=$f->facts();$factory=new O\AssignmentOrderOriginalMariaDbFreshTerminalReaderFactory(integrityFreshConfig($f,[$field=>$value]));$out=$factory->open();assertSameValue([O\AssignmentOrderOriginalFreshReaderOpenStatus::UNAVAILABLE,null],[$out->status,$out->reader],'invalid config no raw connection/exception');assertSameValue($before,$f->facts(),'invalid config changes no facts');});
    $connectionIds=static function()use($f):array{$rows=$f->db->query('SELECT ID FROM information_schema.PROCESSLIST WHERE DB='.$f->q($f->database).' ORDER BY ID')->fetch_all(MYSQLI_ASSOC);return array_map(fn($r)=>(int)$r['ID'],$rows);};
    integrityCase('fresh-new-connection-one-shot-close',function()use($f,$limited,$connectionIds){
        integrityRequireFreshApi();$f->resetOriginals();$v=$f->seedAccepted();$beforeFacts=$f->facts();$before=$connectionIds();$writerId=(int)$f->db->query('SELECT CONNECTION_ID() n')->fetch_assoc()['n'];$reader=null;
        try{$factory=new O\AssignmentOrderOriginalMariaDbFreshTerminalReaderFactory(integrityFreshConfig($f,$limited));assertSameValue($before,$connectionIds(),'lazy constructor opens no native connection');$open=$factory->open();assertSameValue(O\AssignmentOrderOriginalFreshReaderOpenStatus::OPENED,$open->status,'real factory opens');$reader=$open->reader;$added=array_values(array_diff($connectionIds(),$before));assertSameValue(1,count($added),'one native connection to exact task-owned database');assertSameValue(false,in_array($writerId,$added,true),'fresh connection distinct from writer');assertSameValue(false,$reader instanceof O\AssignmentOrderOriginalRepository,'fresh reader is no write repository');
            $lookup=$reader->findTerminalRequest($v['requestId']);assertSameValue(O\AssignmentOrderOriginalLookupStatus::FOUND,$lookup->status(),'full coherent accepted backing found');assertSameValue('revision-0001',$lookup->result()->currentRevisionId(),'exact request evidence');assertSameValue(O\AssignmentOrderOriginalLookupStatus::UNAVAILABLE,$reader->findTerminalRequest($v['requestId'])->status(),'one-shot reader cannot query twice');assertSameValue(O\AssignmentOrderOriginalFreshReaderCloseStatus::CLOSED,$reader->close(),'owned close');assertSameValue(O\AssignmentOrderOriginalFreshReaderCloseStatus::CLOSED,$reader->close(),'idempotent cached close');assertSameValue(O\AssignmentOrderOriginalLookupStatus::UNAVAILABLE,$reader->findTerminalRequest($v['requestId'])->status(),'closed reader unavailable');$reader=null;assertSameValue($before,$connectionIds(),'only fresh connection closed, writer retained');assertSameValue($beforeFacts,$f->facts(),'read-only lookup no mutations');
        }finally{if($reader!==null)$reader->close();}
    });
    integrityCase('fresh-reads-credentials-at-open',function()use($f,$limited,$readPassword){integrityRequireFreshApi();$late=$f->control.'/late-reader-password';$factory=new O\AssignmentOrderOriginalMariaDbFreshTerminalReaderFactory(integrityFreshConfig($f,['databasePasswordFile'=>$late]+$limited));assertSameValue(false,file_exists($late),'passive construction does not create credential file');file_put_contents($late,$readPassword."\n");chmod($late,0600);$open=$factory->open();try{assertSameValue(O\AssignmentOrderOriginalFreshReaderOpenStatus::OPENED,$open->status,'open uses credentials supplied after passive construction');}finally{if($open->reader!==null)$open->reader->close();}});
    integrityCase('fresh-open-result-construction-closure',function()use($f,$limited){integrityRequireFreshApi();$open=(new O\AssignmentOrderOriginalMariaDbFreshTerminalReaderFactory(integrityFreshConfig($f,$limited)))->open();$reader=$open->reader;try{assertSameValue(true,(new ReflectionClass(O\AssignmentOrderOriginalFreshTerminalReaderOpenResult::class))->getConstructor()->isPrivate(),'no raw open-result construction');$caught=null;try{$copy=clone $open;}catch(Throwable $e){$caught=$e;}assertSameValue(true,$caught!==null,'open result cannot duplicate reader ownership');$caught=null;try{serialize($open);}catch(Throwable $e){$caught=$e;}assertSameValue([LogicException::class,'AssignmentOrderOriginalFreshReaderOpenResultNotSerializable',0,null],[$caught===null?null:get_class($caught),$caught?->getMessage(),$caught?->getCode(),$caught?->getPrevious()],'fixed serialization rejection');}finally{if($reader!==null)$reader->close();}});
    integrityCase('fresh-pending-insert-never-reliable-miss',function()use($f,$limited){$f->resetOriginals();$f->db->begin_transaction();try{$f->seedAccepted();$v=integrityChildFresh($f,$limited);assertSameValue('unavailable',$v['status'],'pending request key waits or fails unknown, never false NOT_FOUND');}finally{$f->db->rollback();}assertSameValue([], $f->rows('fm2_assignment_order_original_requests'),'owned pending seed rolled back');});
    integrityCase('fresh-committed-key-found-control',function()use($f,$limited){$f->resetOriginals();$f->seedAccepted();$before=$f->facts();$v=integrityChildFresh($f,$limited);assertSameValue(['found','accepted','revision-0001',1],[$v['status'],$v['result']['status'],$v['result']['revisionId'],$v['result']['revisionNumber']],'committed key plus backing is FOUND');assertSameValue($before,$f->facts(),'child has no DML');});
    integrityCase('fresh-rolled-back-key-reliable-miss-control',function()use($f,$limited){$f->resetOriginals();$f->db->begin_transaction();$f->seedAccepted();$f->db->rollback();$v=integrityChildFresh($f,$limited);assertSameValue('not_found',$v['status'],'settled rolled-back insertion gives reliable absence');assertSameValue(null,$v['result'],'no invented missing result');});
    integrityCase('fresh-orphan-revision-is-not-reliable-miss',function()use($f,$limited){$f->resetOriginals();$f->seedAccepted();$f->corrupt(fn(mysqli $db)=>$db->query('DELETE FROM `'.$f->prefix.'fm2_assignment_order_original_requests`'));$before=$f->facts();$v=integrityChildFresh($f,$limited);assertSameValue('unavailable',$v['status'],'request miss cannot hide its remaining atomic revision/audit');assertSameValue($before,$f->facts(),'orphan is not repaired');});
    foreach([false,true] as $ready)integrityCase('production-factory-real-ack-loss-'.(int)$ready,function()use($f,$limited,$connectionIds,$ready){
        integrityRequireFreshApi();assertSameValue(true,method_exists(O\ProductionAssignmentOrderOriginalFactory::class,'createRecoveryReady'),'INTENDED_RED: mandatory recovery-ready production constructor');
        $f->resetOriginals();$request=$ready?'00000000-0000-4000-8000-000000000601':'00000000-0000-4000-8000-000000000602';$write=$f->connect(S\OriginalIntegrityAckLossMysqli::class);$writerId=(int)$write->thread_id;$lost=false;
        $fresh=new S\OriginalIntegrityCountingRealFactory(new O\AssignmentOrderOriginalMariaDbFreshTerminalReaderFactory(integrityFreshConfig($f,$limited)),$connectionIds);
        try{
            $config=new O\AssignmentOrderOriginalProductionConfig($f->privateRoot,$f->prefix,$f->safeLog);
            $app=$ready?O\ProductionAssignmentOrderOriginalFactory::createRecoveryReady($write,$config,$fresh):O\ProductionAssignmentOrderOriginalFactory::create($write,$config);
            $write->afterNativeCommit=function(mysqli $native)use($f,$request,&$lost){if($lost)return;$row=$f->db->query('SELECT request_id FROM `'.$f->prefix.'fm2_assignment_order_original_requests` WHERE request_id='.$f->q($request))->fetch_assoc();if($row===null)return;$lost=true;$native->close();throw new RuntimeException('synthetic acknowledgement lost after independently visible native commit');};
            $command=new O\SubmitAssignmentOrderOriginalCommand($request,O\AssignmentOrderOriginalMode::INITIAL,4512,81,18,'2000-01-01',true,null,null,null,null,new O\AssignmentOrderOriginalUpload(new O\AssignmentOrderOriginalMemoryStream(S\OriginalIntegrityFixture::pdf()),'original.pdf','application/pdf'));
            $result=$app->submitAssignmentOrderOriginal($command);assertSameValue(true,$lost,'actual native write commit occurred before injected connection loss');
            $row=$f->db->query('SELECT * FROM `'.$f->prefix.'fm2_assignment_order_original_requests` WHERE request_id='.$f->q($request))->fetch_assoc();assertSameValue('accepted',$row['status'],'independent connection proves durable accepted terminal');assertSameValue(1,count($f->rows('fm2_assignment_order_original_revisions')),'exactly one revision, no blind retry');assertSameValue(1,count($f->rows('fm2_assignment_order_original_events')),'exactly one event');
            if($ready){assertSameValue(O\AssignmentOrderOriginalStatus::ACCEPTED,$result->status(),'ready factory resolves durable fact despite unusable writer');assertSameValue([$row['root_original_id'],$row['current_revision_id'],'2000-01-01','4028af3714fa07d2f20e758649532faef11b4818c99a2b8dc0c88170a0dc8784',327],[$result->rootOriginalId(),$result->currentRevisionId(),$result->documentDate(),$result->sha256(),$result->byteSize()],'result matches independent durable row and fixed input');assertSameValue([1,1,1],[$fresh->opens,$fresh->reads,$fresh->closes],'production composition uses exact fresh dependency once');assertSameValue(1,count($fresh->newConnectionIds),'actual second server connection observed at provider open');assertSameValue(false,in_array($writerId,$fresh->newConnectionIds,true),'recovery never reused the write identity');}
            else{assertSameValue([O\AssignmentOrderOriginalStatus::FAILED,O\AssignmentOrderOriginalReason::PERSISTENCE_OUTCOME_UNKNOWN,true],[$result->status(),$result->reasonCode(),$result->retryable()],'compatibility construction explicitly degraded');assertSameValue(0,$fresh->opens,'unprovided factory never silently adopted');}
            $before=$f->facts();$retry=O\ProductionAssignmentOrderOriginalFactory::createRecoveryReady($f->db,$config,$fresh)->submitAssignmentOrderOriginal(new O\SubmitAssignmentOrderOriginalCommand($request,O\AssignmentOrderOriginalMode::INITIAL,4512,81,18,'2099-01-01',true,null,null,null,null,new O\AssignmentOrderOriginalUpload(new O\AssignmentOrderOriginalMemoryStream('unread retry'),'retry.txt','text/plain')));
            assertSameValue(O\AssignmentOrderOriginalStatus::REPLAYED,$retry->status(),'later authorized same request replays without new payload');assertSameValue($row['current_revision_id'],$retry->currentRevisionId(),'retry resolves the same original fact');assertSameValue($before,$f->facts(),'replay leaves every fact/process row unchanged');assertSameValue($ready?1:0,$fresh->opens,'ordinary terminal replay does not open recovery');
        }finally{try{$write->close();}catch(Throwable){}}
    });
    integrityCase('production-invalid-safe-log-before-provider-or-DB',function()use($f){integrityRequireFreshApi();$db=new S\OriginalIntegrityNoSql();$trace=new S\OriginalIntegrityTrace();$repository=new S\OriginalIntegrityRepository([],$trace);$factory=new S\OriginalIntegrityFreshFactory([],$repository,$trace);$caught=null;try{O\ProductionAssignmentOrderOriginalFactory::createRecoveryReady($db,new O\AssignmentOrderOriginalProductionConfig($f->control.'/never-touch-private','data_',$f->control.'/missing-safe-log'),$factory);}catch(Throwable $e){$caught=$e;}assertSameValue(O\AssignmentOrderOriginalProductionConfigurationUnavailable::class,$caught===null?null:get_class($caught),'same approved safe-log-first configuration error');assertSameValue([],$db->calls,'invalid safe log no DB call');assertSameValue(0,$factory->opens,'invalid safe log no fresh connection');assertSameValue(false,file_exists($f->control.'/never-touch-private'),'invalid safe log no private directory touch');assertSameValue(false,file_exists($f->control.'/missing-safe-log'),'invalid safe log never created');});
    integrityCase('fresh-close-observer-failure-cached',function()use($f,$limited,$connectionIds){integrityRequireFreshApi();$f->resetOriginals();$f->seedAccepted();$before=$connectionIds();$observer=new S\OriginalIntegrityPersistenceObserver(function($event){if($event->value==='before_fresh_reader_close')throw new RuntimeException('synthetic close observer');});$open=(new O\AssignmentOrderOriginalMariaDbFreshTerminalReaderFactory(integrityFreshConfig($f,$limited),$observer))->open();$reader=$open->reader;try{assertSameValue(O\AssignmentOrderOriginalLookupStatus::FOUND,$reader->findTerminalRequest('00000000-0000-4000-8000-000000000001')->status(),'selected read remains independently confirmed');assertSameValue(O\AssignmentOrderOriginalFreshReaderCloseStatus::FAILED,$reader->close(),'close failure typed');assertSameValue(O\AssignmentOrderOriginalFreshReaderCloseStatus::FAILED,$reader->close(),'cached failed close');assertSameValue(1,count(array_filter($observer->events,fn($e)=>$e==='before_fresh_reader_close')),'one native close attempt despite callback failure');assertSameValue($before,$connectionIds(),'observer failure cannot leak native reader connection');}finally{if($reader!==null)$reader->close();}});
}finally{
    if($f!==null){try{if($userCreated){if(preg_match('/^u_aoou_fresh_[0-9a-f]{12}$/D',(string)$readUser)!==1)throw new RuntimeException('refuse unowned principal cleanup');$f->db->query('DROP USER '.$f->q($readUser)."@'%'");}}finally{$f->close();}}
}
integrityDone('ASSIGNMENT_ORDER_ORIGINAL_DATA_MARIADB_FRESH_OK');
