<?php

declare(strict_types=1);
// Specification: ASSIGNMENT-ORDER-ORIGINAL-MAINTENANCE-001 v0.1.
require dirname(__DIR__).'/Support/AssignmentOrderOriginalIntegrityTestBootstrap.php';
require dirname(__DIR__).'/Support/AssignmentOrderOriginalMaintenanceOwnerFixture.php';
use FMonitor2\AssignmentOrderOriginal as O;
use FMonitor2\Tests\Support\OriginalMaintenanceOwnerFixture as F;
function mntTuple(O\AssignmentOrderOriginalMaintenanceResult $r):array{return [$r->status()->value,$r->reason()?->value,$r->retryable(),$r->scanned(),$r->deleted(),$r->retained(),$r->failed(),$r->nextCursor()];}
function mntExpected(string $status='completed',?string $reason=null,int $scanned=0,int $deleted=0,int $retained=0,int $failed=0,?string $cursor=null):array{return [$status,$reason,in_array($status,['partial','failed'],true),$scanned,$deleted,$retained,$failed,$cursor];}
integrityCase('existing-command-control',function(){assertSameValue('ops-worker-02',F::command()->systemPrincipalId,'existing passive command input control');});
integrityCase('empty-page',function(){$f=new F();assertSameValue(mntExpected(),mntTuple($f->run()),'empty page completed');assertSameValue(['authorize:ops-worker-02:assignment_order.original.storage.reconcile','lookup','clock','page','commit'],$f->trace,'exact empty path');assertSameValue('2026-09-02T09:00:00Z',$f->commits[0]->attemptedAtUtc,'one captured instant');});
integrityCase('two-orphans',function(){
 $f=new F();$f->two();assertSameValue(mntExpected(scanned:2,deleted:2),mntTuple($f->run()),'two kinds deleted');assertSameValue(['status','items','cursor'],$f->pageGets,'page fields captured once');
 assertSameValue(['authorize:ops-worker-02:assignment_order.original.storage.reconcile','lookup','clock','page','lock:orphan-content-0001','fault:orphan_reference_lookup','reference:orphan-content-0001','delete:orphan-content-0001','release:orphan-content-0001','lock:orphan-stage-0001','delete:orphan-stage-0001','release:orphan-stage-0001','commit'],$f->trace,'ordered exclusion/reference/delete/release before commit');foreach($f->locks as $lock)assertSameValue(1,$lock->releases,'each lock released once');
});
foreach([['requestId'=>'bad'],['systemPrincipalId'=>'bad principal'],['cutoffUtc'=>'2026-02-30T09:00:00Z'],['batchLimit'=>0],['cursor'=>'=']] as $n=>$changes)integrityCase('invalid-shape-'.$n,function()use($changes){$f=new F();assertSameValue(mntExpected('rejected','invalid_command'),mntTuple($f->run($changes)),'invalid scalar outcome');assertSameValue([],$f->trace,'invalid shape no authorization/clock/audit/storage');});
integrityCase('denied',function(){$f=new F();$f->authorization='denied';assertSameValue(mntExpected('rejected','authorization_denied'),mntTuple($f->run()),'denial audited');assertSameValue(['authorize:ops-worker-02:assignment_order.original.storage.reconcile','clock','commit'],$f->trace,'denial no confidential lookup');});
foreach(['authorization','lookup','clock','candidate_page'] as $phase)integrityCase('unavailable-'.$phase,function()use($phase){$f=new F();match($phase){'authorization'=>$f->authorization='unavailable','lookup'=>$f->lookup='unavailable','clock'=>$f->time=new RuntimeException('clock'),default=>$f->page='failed'};assertSameValue(mntExpected('failed','persistence_failure'),mntTuple($f->run()),'unavailable has no invented counts');assertSameValue([],$f->commits,'no terminal on unavailable');assertSameValue([['ASSIGNMENT_ORDER_ORIGINAL_MAINTENANCE_PERSISTENCE_FAILED',['phase'=>$phase]]],$f->logs,'fixed diagnostic');});
integrityCase('future-cutoff',function(){$f=new F();assertSameValue(mntExpected('rejected','invalid_command'),mntTuple($f->run(['cutoffUtc'=>'2026-09-02T08:00:01Z'])),'cutoff must be at least one hour old');assertSameValue(['authorize:ops-worker-02:assignment_order.original.storage.reconcile','lookup','clock','commit'],$f->trace,'cutoff rejection before page');});
foreach([['completed',null,false,2,2,0,0,null],['partial','locked',true,2,1,1,0,null],['rejected','invalid_command',false,0,0,0,0,null]] as $n=>$tuple)integrityCase('replay-'.$n,function()use($tuple){$f=new F();$f->lookup='found';$f->stored=F::result($tuple);$expected=$tuple;$expected[0]='replayed';assertSameValue($expected,mntTuple($f->run()),'replay preserves retryability and counters');assertSameValue(['authorize:ops-worker-02:assignment_order.original.storage.reconcile','lookup'],$f->trace,'replay no clock/storage/audit');});
foreach(['referenced','locked','reference-unavailable','delete-failed','release-failed'] as $kind)integrityCase('item-'.$kind,function()use($kind){
 $f=new F();$f->two();$f->items=array_slice($f->items,0,1);match($kind){'referenced'=>$f->references['orphan-content-0001']=true,'locked'=>$f->lockStates['orphan-content-0001']='locked','reference-unavailable'=>$f->references['orphan-content-0001']=null,'delete-failed'=>$f->deleteStates['orphan-content-0001']='failed',default=>$f->releaseThrows=true};
 $expected=match($kind){'referenced'=>mntExpected(scanned:1,retained:1),'locked'=>mntExpected('partial','locked',1,0,1),'reference-unavailable','delete-failed'=>mntExpected('partial','storage_failure',1,0,0,1),default=>mntExpected(scanned:1,deleted:1)};
 assertSameValue($expected,mntTuple($f->run()),'per-item outcome and conservation');assertSameValue(1,$f->locks['orphan-content-0001']->releases,'lock released once including failure');if(in_array($kind,['referenced','locked','reference-unavailable'],true))assertSameValue([],$f->deleted,'protected/unknown content not deleted');
});
foreach(['duplicate','newer','bad-cursor'] as $kind)integrityCase('bad-page-'.$kind,function()use($kind){$f=new F();$f->two();if($kind==='duplicate')$f->items[]=$f->items[0];elseif($kind==='newer')$f->items[0]=new O\AssignmentOrderOriginalOrphanCandidate(O\AssignmentOrderOriginalOrphanKind::FINALIZED_CONTENT,'orphan-content-0001',hash('sha256','finalized-orphan-v1'),19,'2026-09-02T08:00:00Z');else $f->cursor='=';assertSameValue(mntExpected('failed','persistence_failure'),mntTuple($f->run()),'malformed page rejected before any item');assertSameValue([],$f->locks,'all page validated before lock');});
foreach(['rolled_back','conflict','outcome_unknown'] as $commit)integrityCase('commit-'.$commit,function()use($commit){$f=new F();$f->two();$f->commit=$commit;$f->logThrows=true;assertSameValue(mntExpected('failed','persistence_failure',2,2),mntTuple($f->run()),'failed acknowledgement preserves observed effects');assertSameValue(1,count($f->commits),'no blind commit retry');assertSameValue(2,count($f->deleted),'no repeated delete');assertSameValue([['ASSIGNMENT_ORDER_ORIGINAL_MAINTENANCE_PERSISTENCE_FAILED',['phase'=>'commit']]],$f->logs,'one best-effort diagnostic despite throw');});
foreach(['contradictory','counts','cursor'] as $kind)integrityCase('bad-stored-'.$kind,function()use($kind){
 $f=new F();$f->lookup=$kind==='contradictory'?'not_found':'found';$f->stored=F::result(['completed',null,false,$kind==='counts'?2:0,0,0,0,$kind==='cursor'?'=':null]);assertSameValue(mntExpected('failed','persistence_failure'),mntTuple($f->run()),'malformed stored result is not a replay');assertSameValue(['authorize:ops-worker-02:assignment_order.original.storage.reconcile','lookup','log:lookup'],$f->trace,'malformed lookup stops before clock/storage');
});
integrityCase('release-and-logger-fail',function(){$f=new F();$f->two();$f->releaseThrows=$f->logThrows=true;assertSameValue(mntExpected(scanned:2,deleted:2),mntTuple($f->run()),'release/log failure preserves selected counts');assertSameValue(2,count($f->logs),'one diagnostic per failed release, not repeated');assertSameValue(1,count($f->commits),'audit still attempted');});
integrityCase('page-getter-throws',function(){$f=new F();$f->page='throw';assertSameValue(mntExpected('failed','persistence_failure'),mntTuple($f->run()),'page getter failure total');assertSameValue([],$f->locks,'no item before full page snapshot');});
integrityCase('quote-space-cursor',function(){$f=new F();$f->items=[new O\AssignmentOrderOriginalOrphanCandidate(O\AssignmentOrderOriginalOrphanKind::ABANDONED_STAGE,'a "b"',null,0,'2026-09-02T07:00:00Z')];$f->cursor=rtrim(strtr(base64_encode('{"v":1,"at":"2026-09-02T07:00:00Z","id":"a \"b\""}'),'+/','-_'),'=');assertSameValue(mntExpected(scanned:1,deleted:1,cursor:$f->cursor),mntTuple($f->run()),'valid quoted/space opaque identity and literal codec');});
integrityDone('ASSIGNMENT_ORDER_ORIGINAL_MAINTENANCE_OWNER_OK');
