<?php
declare(strict_types=1);
require dirname(__DIR__).'/bootstrap.php';
require_once dirname(__DIR__,2).'/app/AssignmentOrderOriginal/AssignmentOrderOriginalRuntime.php';
require_once dirname(__DIR__,2).'/app/AssignmentOrderOriginal/AssignmentOrderOriginalFileStorage.php';
require_once dirname(__DIR__).'/Support/AssignmentOrderOriginalDatabaseSetupV1.php';
require_once dirname(__DIR__).'/Support/AssignmentOrderOriginalPdfCorpus.php';
use FMonitor2\AssignmentOrderOriginal\{AssignmentOrderOriginalApplication,AssignmentOrderOriginalClock,AssignmentOrderOriginalFaultInjector,AssignmentOrderOriginalFaultPoint,AssignmentOrderOriginalFileSafeLog,AssignmentOrderOriginalFileStorage,AssignmentOrderOriginalMemoryStream,AssignmentOrderOriginalMode,AssignmentOrderOriginalPrivateOrphanFixtureCommand,AssignmentOrderOriginalPrivateOrphanFixtureConflict,AssignmentOrderOriginalPrivateOrphanFixtureFactory,AssignmentOrderOriginalPrivateOrphanFixtureKind,AssignmentOrderOriginalPrivateOrphanFixtureUnavailable,AssignmentOrderOriginalProductionConfig,AssignmentOrderOriginalReason,AssignmentOrderOriginalService,AssignmentOrderOriginalStatus,AssignmentOrderOriginalUpload,ProductionAssignmentOrderOriginalFactory,SubmitAssignmentOrderOriginalCommand};
use FMonitor2\Tests\Support\AssignmentOrderOriginalPdfCorpus;
$token=bin2hex(random_bytes(16));$control=sys_get_temp_dir().'/aoou-production-boundary-'.$token;$remove=static function(string$path)use(&$remove):void{if(is_file($path)||is_link($path)){unlink($path);return;}if(!is_dir($path))return;foreach(scandir($path)?:[]as$entry)if($entry!=='.'&&$entry!=='..')$remove($path.'/'.$entry);rmdir($path);};$failures=[];$expectThrow=static function(string$label,callable$operation,string$expected='')use(&$failures):void{try{$operation();$failures[]=$label.': accepted';}catch(Throwable$e){if($expected!==''&&!$e instanceof $expected)$failures[]=$label.': '.get_class($e);}};
$clock=new class implements AssignmentOrderOriginalClock{public function nowUtc():string{return'2026-09-02T09:00:00Z';}};$noFaults=new class implements AssignmentOrderOriginalFaultInjector{public function before(AssignmentOrderOriginalFaultPoint$point):void{}};
mysqli_report(MYSQLI_REPORT_ERROR|MYSQLI_REPORT_STRICT);$host=getenv('FMONITOR_TEST_DB_HOST')?:'127.0.0.1';$port=(int)(getenv('FMONITOR_TEST_DB_PORT')?:23306);$user=getenv('FMONITOR_TEST_DB_ADMIN_USER')?:'root';$password=getenv('FMONITOR_TEST_DB_ADMIN_PASSWORD')?:'fmonitor2_test_root_local';$database='t_aoou_boundary_'.substr($token,0,12);$prefix='b_';$admin=new mysqli($host,$user,$password,'',$port);$db=null;
try{$admin->query("CREATE DATABASE `{$database}` CHARSET utf8mb4 COLLATE utf8mb4_unicode_ci");mkdir($control,0700);$production=$control.'/production';mkdir($production,0700);$valid=$control.'/valid';mkdir($valid,0700);file_put_contents($valid.'/.aoou-verifier-owner',"aoou-private-orphan-fixture-v1\n{$token}\n");chmod($valid.'/.aoou-verifier-owner',0600);$db=new mysqli($host,$user,$password,$database,$port);$db->set_charset('utf8mb4');$tablesBefore=$db->query('SHOW TABLES')->fetch_all(MYSQLI_NUM);
    $factoryAvailable=class_exists(ProductionAssignmentOrderOriginalFactory::class);if(!$factoryAvailable)$failures[]='production factory: absent';else{try{$application=ProductionAssignmentOrderOriginalFactory::create($db,new AssignmentOrderOriginalProductionConfig($production,$prefix));if(!$application instanceof AssignmentOrderOriginalApplication||get_class($application)!==AssignmentOrderOriginalService::class)$failures[]='production factory: did not return the real command application owner';else{$result=$application->submitAssignmentOrderOriginal(new SubmitAssignmentOrderOriginalCommand('invalid-request',AssignmentOrderOriginalMode::INITIAL,4512,81,18,'2026-09-01',true,null,null,null,null,new AssignmentOrderOriginalUpload(new AssignmentOrderOriginalMemoryStream(AssignmentOrderOriginalPdfCorpus::passiveClassic()),'production-boundary.pdf','application/pdf')));if([$result->status(),$result->reasonCode(),$result->retryable()]!==[AssignmentOrderOriginalStatus::REJECTED,AssignmentOrderOriginalReason::INVALID_COMMAND,false])$failures[]='production factory: returned real seam is unusable';if($db->query('SHOW TABLES')->fetch_all(MYSQLI_NUM)!==$tablesBefore)$failures[]='production factory: performed runtime DDL';}}catch(Throwable$e){$failures[]='production factory valid secure construction: '.get_class($e);}}
    $missing=$control.'/missing';$expectThrow('private root no-create',static fn()=>new AssignmentOrderOriginalFileStorage($missing,$clock,$noFaults));if(file_exists($missing))$failures[]='private root no-create: path created';
    $loose=$control.'/loose';mkdir($loose,0777);chmod($loose,0777);$expectThrow('private root mode',static fn()=>new AssignmentOrderOriginalFileStorage($loose,$clock,$noFaults));
    $link=$control.'/private-link';symlink($production,$link);$expectThrow('private root symlink',static fn()=>new AssignmentOrderOriginalFileStorage($link,$clock,$noFaults));
    $unsafeParent=$control.'/unsafe-parent';mkdir($unsafeParent,0777);chmod($unsafeParent,0777);mkdir($unsafeParent.'/private',0700);$expectThrow('private root protected chain',static fn()=>new AssignmentOrderOriginalFileStorage($unsafeParent.'/private',$clock,$noFaults));
    if($factoryAvailable){$expectThrow('production factory rejects loose root',static fn()=>ProductionAssignmentOrderOriginalFactory::create($db,new AssignmentOrderOriginalProductionConfig($loose,$prefix)));$expectThrow('production factory rejects symlink root',static fn()=>ProductionAssignmentOrderOriginalFactory::create($db,new AssignmentOrderOriginalProductionConfig($link,$prefix)));$expectThrow('production factory rejects protected chain',static fn()=>ProductionAssignmentOrderOriginalFactory::create($db,new AssignmentOrderOriginalProductionConfig($unsafeParent.'/private',$prefix)));}
    $validSafeLog=$control.'/valid-safe.log';file_put_contents($validSafeLog,'');chmod($validSafeLog,0600);try{$logger=new AssignmentOrderOriginalFileSafeLog($validSafeLog,'00000000-0000-4000-8000-000000000001');$logger->record('boundary_probe',['phase'=>'positive']);if(!str_ends_with((string)file_get_contents($validSafeLog),"\n"))$failures[]='safe log valid secure construction: unusable';}catch(Throwable$e){$failures[]='safe log valid secure construction: '.get_class($e);}$safeLog=$control.'/safe.log';file_put_contents($safeLog,'');chmod($safeLog,0644);$expectThrow('safe log exact 0600',static fn()=>new AssignmentOrderOriginalFileSafeLog($safeLog,'00000000-0000-4000-8000-000000000001'));
    $safeTarget=$control.'/safe-target.log';file_put_contents($safeTarget,'');chmod($safeTarget,0600);$safeLink=$control.'/safe-link.log';symlink($safeTarget,$safeLink);$expectThrow('safe log symlink',static fn()=>new AssignmentOrderOriginalFileSafeLog($safeLink,'00000000-0000-4000-8000-000000000001'));
    $inventory=static function(string$root):array{$items=[];foreach(scandir($root)?:[]as$item)if($item!=='.'&&$item!=='..')$items[$item]=is_file($root.'/'.$item)?hash_file('sha256',$root.'/'.$item):'dir';ksort($items,SORT_STRING);return$items;};$before=$inventory($valid);
    $wrongToken=str_repeat('0',32);$expectThrow('orphan marker token',static fn()=>AssignmentOrderOriginalPrivateOrphanFixtureFactory::create($valid,$wrongToken,$clock,new AssignmentOrderOriginalProductionConfig($production,'fm2_'),$noFaults),AssignmentOrderOriginalPrivateOrphanFixtureUnavailable::class);
    $expectThrow('orphan production-root disjointness',static fn()=>AssignmentOrderOriginalPrivateOrphanFixtureFactory::create($valid,$token,$clock,new AssignmentOrderOriginalProductionConfig($valid,'fm2_'),$noFaults),AssignmentOrderOriginalPrivateOrphanFixtureUnavailable::class);
    $fixture=AssignmentOrderOriginalPrivateOrphanFixtureFactory::create($valid,$token,$clock,new AssignmentOrderOriginalProductionConfig($production,'fm2_'),$noFaults);$future=new AssignmentOrderOriginalPrivateOrphanFixtureCommand(AssignmentOrderOriginalPrivateOrphanFixtureKind::ABANDONED_STAGE,'future-stage-0001','future','2026-09-02T09:00:01Z');$expectThrow('orphan injected clock future',static fn()=>$fixture->create($future),AssignmentOrderOriginalPrivateOrphanFixtureUnavailable::class);
    $faults=new class implements AssignmentOrderOriginalFaultInjector{public function before(AssignmentOrderOriginalFaultPoint$point):void{if($point===AssignmentOrderOriginalFaultPoint::STAGE_WRITE)throw new RuntimeException('injected');}};$faultFixture=AssignmentOrderOriginalPrivateOrphanFixtureFactory::create($valid,$token,$clock,new AssignmentOrderOriginalProductionConfig($production,'fm2_'),$faults);$faultCommand=new AssignmentOrderOriginalPrivateOrphanFixtureCommand(AssignmentOrderOriginalPrivateOrphanFixtureKind::ABANDONED_STAGE,'fault-stage-0001','fault','2026-09-02T07:00:00Z');$expectThrow('orphan injected primitive fault',static fn()=>$faultFixture->create($faultCommand),AssignmentOrderOriginalPrivateOrphanFixtureUnavailable::class);
    if($before!==$inventory($valid))$failures[]='invalid/fault fixture attempts changed task-owned inventory';
    $first=new AssignmentOrderOriginalPrivateOrphanFixtureCommand(AssignmentOrderOriginalPrivateOrphanFixtureKind::ABANDONED_STAGE,'collision-stage-0001','first','2026-09-02T07:00:00Z');$fixture->create($first);$collisionBefore=$inventory($valid);$collision=new AssignmentOrderOriginalPrivateOrphanFixtureCommand(AssignmentOrderOriginalPrivateOrphanFixtureKind::ABANDONED_STAGE,'collision-stage-0001','second','2026-09-02T07:00:00Z');$expectThrow('orphan collision',static fn()=>$fixture->create($collision),AssignmentOrderOriginalPrivateOrphanFixtureConflict::class);if($collisionBefore!==$inventory($valid))$failures[]='orphan collision changed task-owned inventory';
    if($failures!==[])throw new TestFailure("INTENDED_RED: approved production boundary is incomplete:\n".implode("\n",$failures));fwrite(STDOUT,"ASSIGNMENT_ORDER_ORIGINAL_PRODUCTION_BOUNDARY_OK\n");
}finally{if($db instanceof mysqli)$db->close();try{$admin->query("DROP DATABASE IF EXISTS `{$database}`");}catch(Throwable){}$admin->close();$remove($control);}
