<?php
declare(strict_types=1);
require dirname(__DIR__).'/bootstrap.php';
$host=getenv('FMONITOR_TEST_DB_HOST')?:'127.0.0.1';$port=(int)(getenv('FMONITOR_TEST_DB_PORT')?:23306);$user=getenv('FMONITOR_TEST_DB_ADMIN_USER')?:'root';$password=getenv('FMONITOR_TEST_DB_ADMIN_PASSWORD')?:'fmonitor2_test_root_local';$name='t_bootstrap_'.bin2hex(random_bytes(5));$home=sys_get_temp_dir().'/fm2-bootstrap-'.bin2hex(random_bytes(6));mkdir($home,0700,true);$admin=new mysqli($host,$user,$password,'',$port);$admin->query("CREATE DATABASE `$name` DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
$root=dirname(__DIR__,2);$env=array_replace(getenv(),['HOME'=>$home,'FMONITOR_DB_HOST'=>$host,'FMONITOR_DB_PORT'=>(string)$port,'FMONITOR_DB_NAME'=>$name,'FMONITOR_DB_USER'=>$user,'FMONITOR_DB_PASSWORD'=>$password,'FMONITOR_PROCESS_TABLE_PREFIX'=>'sb_','FMONITOR_BOOTSTRAP_PROCESS_PREFIX'=>'sb_','FMONITOR_BOOTSTRAP_LEGACY_PREFIX'=>'sb_','FMONITOR_BOOTSTRAP_SUPERADMIN_EMAILS'=>'owner-bootstrap@shlz.ru','FMONITOR_BOOTSTRAP_SUPERADMIN_PASSWORD'=>'owner-only-synthetic-secret','FMONITOR_DEMO_PORT'=>'18092']);
$run=static function(string$file,array$environment)use($root):array{$p=[];$r=proc_open([PHP_BINARY,$file],[0=>['pipe','r'],1=>['pipe','w'],2=>['pipe','w']],$p,$root,$environment);if(!is_resource($r))throw new RuntimeException();fclose($p[0]);$out=stream_get_contents($p[1]);$err=stream_get_contents($p[2]);fclose($p[1]);fclose($p[2]);return[proc_close($r),$out,$err];};
$remove=static function(string$path)use(&$remove):void{if(is_link($path)||is_file($path)){unlink($path);return;}if(!is_dir($path))return;foreach(scandir($path)?:[]as$n)if($n!=='.'&&$n!=='..')$remove($path.'/'.$n);rmdir($path);};
try{assertSameValue(0,$run($root.'/bin/fmonitor2-migrate.php',$env)[0],'canonical migrations');$first=$run($root.'/rapid-pilot/docker-bootstrap.php',$env);assertSameValue([0,'',''],$first,'clean bootstrap');$db=new mysqli($host,$user,$password,$name,$port);$users=$db->query('SELECT user_id,email,status,activation_state,session_version FROM sb_fm2_pilot_users')->fetch_all(MYSQLI_ASSOC);assertSameValue(1,count($users),'only configured owner account');assertSameValue('owner-bootstrap@shlz.ru',$users[0]['email'],'configured owner identity');assertSameValue(0,(int)$db->query('SELECT COUNT(*) n FROM sb_fm_maintable')->fetch_assoc()['n'],'empty object contour');$sentinel=$db->query('SELECT * FROM sb_fm2_pilot_generation_sentinel')->fetch_all(MYSQLI_ASSOC);$owner=(int)$users[0]['user_id'];$db->query("INSERT INTO sb_fm2_pilot_users(full_name,email,phone,status,activation_state,session_version,source_updated_at)VALUES('Приглашённый пользователь','invited-user@shlz.ru','',1,'invited',1,'2026-09-07T12:00:00+03:00')");$invited=(int)$db->insert_id;$role=(int)$db->query("SELECT role_id FROM sb_fm2_pilot_roles WHERE code='user'")->fetch_assoc()['role_id'];$db->query("INSERT INTO sb_fm2_pilot_user_roles(user_id,role_id,origin,assigned_at,assigned_by_user_id)VALUES($invited,$role,'manual','2026-09-07T12:00:00+03:00',$owner)");$users=$db->query('SELECT user_id,email,status,activation_state,session_version FROM sb_fm2_pilot_users ORDER BY user_id')->fetch_all(MYSQLI_ASSOC);assertSameValue(2,count($users),'owner-created invitation adds second account');$roles=$db->query('SELECT * FROM sb_fm2_pilot_user_roles ORDER BY user_id,role_id')->fetch_all(MYSQLI_ASSOC);$manifest=glob($home.'/.local/state/fmonitor2/pilot-demo/*/active.json')[0]??'';$before=file_get_contents($manifest);$second=$run($root.'/rapid-pilot/docker-bootstrap.php',$env);assertSameValue([0,'',''],$second,'restart bootstrap after invitation');assertSameValue([$users,$sentinel,$roles,$before],[$db->query('SELECT user_id,email,status,activation_state,session_version FROM sb_fm2_pilot_users ORDER BY user_id')->fetch_all(MYSQLI_ASSOC),$db->query('SELECT * FROM sb_fm2_pilot_generation_sentinel')->fetch_all(MYSQLI_ASSOC),$db->query('SELECT * FROM sb_fm2_pilot_user_roles ORDER BY user_id,role_id')->fetch_all(MYSQLI_ASSOC),file_get_contents($manifest)],'restart preserves owner, invited user, roles, sentinel and manifest');$generation=dirname($manifest).'/generations/1';foreach(['artifacts'=>0700,'database-password'=>0600,'original-safe.log'=>0600]as$path=>$mode){$s=lstat($generation.'/'.$path);assertSameValue($mode,$s['mode']&0777,"mode $path");}
 $pipes=[];$server=proc_open([PHP_BINARY,$root.'/rapid-pilot/start.php'],[0=>['pipe','r'],1=>['pipe','w'],2=>['pipe','w']],$pipes,$root,$env);if(!is_resource($server))throw new RuntimeException();fclose($pipes[0]);$ready=false;for($i=0;$i<100;$i++){$socket=@stream_socket_client('tcp://127.0.0.1:18092',$errno,$error,.05);if($socket){fclose($socket);$ready=true;break;}usleep(20000);}assertSameValue(true,$ready,'start binds synthetic stand');$context=stream_context_create(['http'=>['ignore_errors'=>true,'timeout'=>2]]);$body=file_get_contents('http://127.0.0.1:18092/pilot/login',false,$context);assertSameValue(true,is_string($body)&&str_contains($body,'Вход'),'owner login page available');proc_terminate($server);foreach([1,2]as$i){stream_get_contents($pipes[$i]);fclose($pipes[$i]);}proc_close($server);$db->close();echo"docker_bootstrap_manual_pilot_test: PASS\n";
}finally{$admin->query("DROP DATABASE IF EXISTS `$name`");$admin->close();$remove($home);}
