<?php
declare(strict_types=1);
require dirname(__DIR__).'/bootstrap.php';
require dirname(__DIR__,2).'/app/autoload.php';

use FMonitor2\InstallationProcess\InspectionEvidenceSchemaMigration;
use FMonitor2\InstallationProcess\InspectionPhotoContentIndexSchemaMigration;
use FMonitor2\InstallationProcess\ProductionPilotMigrationCatalogue;
use FMonitor2\InstallationProcess\CanonicalMigrationApplication;
use FMonitor2\InspectionEvidence\MariaDbInspectionAuthorization;
use FMonitor2\PilotHttp\ChecklistSync;

function ipcisDb(?string$name=null):mysqli{$db=new mysqli(getenv('FMONITOR_TEST_DB_HOST')?:'127.0.0.1',getenv('FMONITOR_TEST_DB_ADMIN_USER')?:'root',getenv('FMONITOR_TEST_DB_ADMIN_PASSWORD')?:'fmonitor2_test_root_local',$name??'',(int)(getenv('FMONITOR_TEST_DB_PORT')?:23306));$db->set_charset('utf8mb4');return$db;}
function ipcisIndexes(mysqli$db,string$table):array{$s=$db->prepare('SELECT INDEX_NAME,NON_UNIQUE,SEQ_IN_INDEX,COLUMN_NAME FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=? ORDER BY INDEX_NAME,SEQ_IN_INDEX');$s->execute([$table]);return$s->get_result()->fetch_all(MYSQLI_ASSOC);}
function ipcisState(mysqli$db,string$p):array{$table=$p.'fm2_checklist_photos';$auto=$db->query("SELECT AUTO_INCREMENT FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='{$table}'")->fetch_assoc();return['photos'=>$db->query("SELECT * FROM `{$table}` ORDER BY id")->fetch_all(MYSQLI_ASSOC),'operations'=>$db->query("SELECT * FROM `{$p}fm2_checklist_operations` ORDER BY id")->fetch_all(MYSQLI_ASSOC),'indexes'=>ipcisIndexes($db,$table),'autoIncrement'=>(string)$auto['AUTO_INCREMENT']];}

if(!class_exists(InspectionPhotoContentIndexSchemaMigration::class))throw new TestFailure('INTENDED_RED: canonical photo content-index migration v19 is absent');
$name='t_ipcis_'.bin2hex(random_bytes(5));$prefix='pi_';$decoyPrefix='decoy_';$badPrefix='bad_';$fullPrefix='full_';$admin=ipcisDb();$db=null;$failure=null;
try{
    $admin->query("CREATE DATABASE `{$name}` DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");$db=ipcisDb($name);assertSameValue(true,InspectionEvidenceSchemaMigration::apply($db,$prefix)['applied'],'predecessor canonical v8 fixture');assertSameValue(true,InspectionEvidenceSchemaMigration::apply($db,$decoyPrefix)['applied'],'opposite-prefix predecessor fixture');assertSameValue(true,InspectionEvidenceSchemaMigration::apply($db,$badPrefix)['applied'],'malformed-index predecessor fixture');
    $db->query("INSERT INTO `{$prefix}fm2_checklist_revisions` VALUES(71,2,'2026-09-01T10:01:00+03:00')");
    $db->query("INSERT INTO `{$prefix}fm2_checklist_operations`(id,installation_case_id,client_operation_id,device_installation_id,operation_type,section_id,item_id,actor_user_id,device_time,server_received_at,base_revision,accepted_revision,payload_json)VALUES(1,71,'11111111-1111-4111-8111-111111111111','22222222-2222-4222-8222-222222222222','photo_uploaded',3,NULL,901,'2026-09-01T10:00:00+03:00','2026-09-01T10:00:01+03:00',0,1,'{}'),(2,71,'33333333-3333-4333-8333-333333333333','22222222-2222-4222-8222-222222222222','photo_revoked',3,NULL,901,'2026-09-01T10:01:00+03:00','2026-09-01T10:01:01+03:00',1,2,'{\"photoId\":41}')");
    $hash=str_repeat('a',64);$db->query("INSERT INTO `{$prefix}fm2_checklist_photos`(id,installation_case_id,section_id,upload_operation_id,sha256,mime_type,byte_size,original_name,storage_name,actor_user_id,device_time,server_received_at,revoked_at)VALUES(41,71,3,'11111111-1111-4111-8111-111111111111','{$hash}','image/png',68,'retained.png','{$hash}.bin',901,'2026-09-01T10:00:00+03:00','2026-09-01T10:00:01+03:00','2026-09-01T10:01:01+03:00')");$db->query("ALTER TABLE `{$prefix}fm2_checklist_photos` AUTO_INCREMENT=90");
    (new ChecklistSync($db,$prefix,'','2026-09-07T12:00:00+03:00'))->ensureSchema();assertSameValue(true,(new MariaDbInspectionAuthorization($db,$prefix))->schemaAvailable(),'existing literal v8 remains an admitted historical runtime form');$before=ipcisState($db,$prefix);$decoyBefore=ipcisState($db,$decoyPrefix);assertSameValue(['applied'=>true,'schemaVersion'=>19,'indexesChanged'=>[$prefix.'fm2_checklist_photos.installation_case_id']],InspectionPhotoContentIndexSchemaMigration::apply($db,$prefix),'populated exact predecessor upgrades only content index');$after=ipcisState($db,$prefix);assertSameValue([$before['photos'],$before['operations'],$before['autoIncrement']],[$after['photos'],$after['operations'],$after['autoIncrement']],'populated revoked photo, operations and allocator remain byte/value-identical');assertSameValue($decoyBefore,ipcisState($db,$decoyPrefix),'configured prefix leaves opposite schema family byte-identical');
    $content=array_values(array_filter($after['indexes'],static fn(array$i):bool=>$i['INDEX_NAME']==='installation_case_id'));assertSameValue([['INDEX_NAME'=>'installation_case_id','NON_UNIQUE'=>1,'SEQ_IN_INDEX'=>1,'COLUMN_NAME'=>'installation_case_id'],['INDEX_NAME'=>'installation_case_id','NON_UNIQUE'=>1,'SEQ_IN_INDEX'=>2,'COLUMN_NAME'=>'section_id'],['INDEX_NAME'=>'installation_case_id','NON_UNIQUE'=>1,'SEQ_IN_INDEX'=>3,'COLUMN_NAME'=>'sha256']],$content,'final content lookup is exact non-unique ordered index');
    $upload=array_values(array_filter($after['indexes'],static fn(array$i):bool=>$i['INDEX_NAME']==='upload_operation_id'));assertSameValue(0,$upload[0]['NON_UNIQUE']??null,'upload operation identity remains unique');assertSameValue(['applied'=>false,'schemaVersion'=>19,'indexesChanged'=>[]],InspectionPhotoContentIndexSchemaMigration::apply($db,$prefix),'exact final repeat is no-op');assertSameValue($after,ipcisState($db,$prefix),'repeat preserves rows, indexes and allocator');
    assertSameValue(false,InspectionEvidenceSchemaMigration::isCompleteCompatible($db,$prefix),'literal v8 predecessor oracle remains historical and exact');assertSameValue(true,InspectionPhotoContentIndexSchemaMigration::isCompleteCompatible($db,$prefix),'successor recognizes exact final schema');(new ChecklistSync($db,$prefix,'','2026-09-07T12:00:00+03:00'))->ensureSchema();assertSameValue(true,(new MariaDbInspectionAuthorization($db,$prefix))->schemaAvailable(),'both runtime consumers admit migrated final schema without repair');
    $badTable=$badPrefix.'fm2_checklist_photos';$db->query("ALTER TABLE `{$badTable}` DROP INDEX installation_case_id,ADD UNIQUE INDEX installation_case_id(installation_case_id,sha256,section_id)");$badBefore=ipcisState($db,$badPrefix);assertSameValue(['applied'=>false,'schemaVersion'=>19,'reason'=>'SCHEMA_MIGRATION_CONFLICT','conflictingTables'=>[$badTable]],InspectionPhotoContentIndexSchemaMigration::apply($db,$badPrefix),'wrong ordered unique content index fails closed');assertSameValue($badBefore,ipcisState($db,$badPrefix),'malformed index refusal has zero mutation');
    $catalogue=ProductionPilotMigrationCatalogue::migrations();assertSameValue(InspectionPhotoContentIndexSchemaMigration::class,$catalogue[19]??null,'canonical catalogue assigns exact free successor version 19');$first=CanonicalMigrationApplication::run($db,$fullPrefix,$catalogue);assertSameValue([0,['ok'=>true,'schemaVersion'=>19,'appliedVersions'=>range(1,19)]],[$first['exitCode'],$first['result']],'clean canonical catalogue applies exact versions 1 through 19');$second=CanonicalMigrationApplication::run($db,$fullPrefix,$catalogue);assertSameValue([0,['ok'=>true,'schemaVersion'=>19,'appliedVersions'=>[]]],[$second['exitCode'],$second['result']],'full canonical repeat traverses historical v8 and final v19 without conflict');
    echo"PASS canonical photo content index v19 preserves populated evidence, runtime compatibility and full repeat\n";
}catch(Throwable$error){$failure=$error;}finally{if($db instanceof mysqli)$db->close();$admin->query("DROP DATABASE IF EXISTS `{$name}`");$admin->close();}if($failure)throw$failure;
