<?php
declare(strict_types=1);
require dirname(__DIR__).'/bootstrap.php';
use FMonitor2\InspectionEvidence\CompleteInspectionItem;
use FMonitor2\InspectionEvidence\InspectionEvidenceClock;
use FMonitor2\InspectionEvidence\ProductionInspectionEvidenceConfig;
use FMonitor2\InspectionEvidence\ProductionInspectionEvidenceFactory;
function iicsdQ(string $v):string{return'`'.str_replace('`','``',$v).'`';}
function iicsdDb(?string$d=null):mysqli{$c=new mysqli(getenv('FMONITOR_TEST_DB_HOST')?:'127.0.0.1',getenv('FMONITOR_TEST_DB_ADMIN_USER')?:'root',getenv('FMONITOR_TEST_DB_ADMIN_PASSWORD')?:'fmonitor2_test_root_local',$d,(int)(getenv('FMONITOR_TEST_DB_PORT')?:23306));$c->set_charset('utf8mb4');return$c;}
function iicsdMigrate(string$d,string$p):void{$e=['FMONITOR_DB_HOST'=>getenv('FMONITOR_TEST_DB_HOST')?:'127.0.0.1','FMONITOR_DB_PORT'=>getenv('FMONITOR_TEST_DB_PORT')?:'23306','FMONITOR_DB_NAME'=>$d,'FMONITOR_DB_USER'=>getenv('FMONITOR_TEST_DB_ADMIN_USER')?:'root','FMONITOR_DB_PASSWORD'=>getenv('FMONITOR_TEST_DB_ADMIN_PASSWORD')?:'fmonitor2_test_root_local','FMONITOR_PROCESS_TABLE_PREFIX'=>$p];$c=['env'];foreach($e as$k=>$v)$c[]="$k=$v";$c[]='php';$c[]=dirname(__DIR__,2).'/bin/fmonitor2-migrate.php';$pipes=[];$r=proc_open($c,[0=>['pipe','r'],1=>['pipe','w'],2=>['pipe','w']],$pipes,dirname(__DIR__,2));if(!is_resource($r))throw new TestFailure('SETUP_FAILURE: migration start.');fclose($pipes[0]);$o=stream_get_contents($pipes[1]);$x=stream_get_contents($pipes[2]);fclose($pipes[1]);fclose($pipes[2]);assertSameValue(0,proc_close($r),'SETUP_FAILURE: canonical migration '.$o.$x);}
function iicsdSnapshot(mysqli$db,string$p):array{$out=[];foreach(['fm2_checklist_revisions','fm2_checklist_operations','fm2_checklist_operation_installers','fm2_checklist_photos']as$b){$n=$p.$b;$create=$db->query('SHOW CREATE TABLE '.iicsdQ($n))->fetch_assoc();$out[$b]=['createTable'=>$create['Create Table']??null,'rows'=>$db->query('SELECT * FROM '.iicsdQ($n).' ORDER BY 1,2')->fetch_all(MYSQLI_ASSOC)];}return$out;}
mysqli_report(MYSQLI_REPORT_ERROR|MYSQLI_REPORT_STRICT);$t=substr(hash('sha256',__FILE__.hrtime(true)),0,10);$d='t_iicsd_'.$t;$p='sd'.substr($t,0,6).'_';$a=iicsdDb();$db=null;
try{$a->query('CREATE DATABASE '.iicsdQ($d).' DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci');iicsdMigrate($d,$p);$db=iicsdDb($d);$q=fn(string$n):string=>iicsdQ($p.$n);$db->query("INSERT INTO {$q('fm2_pilot_users')} VALUES(7301,'Fixture Engineer','drift@example.invalid','',1,'active',1,'2026-09-01T09:00:00+03:00')");$db->query("INSERT INTO {$q('fm2_pilot_roles')} VALUES(7001,'drift_fixture','Drift fixture','Test only',1,'2026-09-01T09:00:00+03:00')");$db->query("INSERT INTO {$q('fm2_pilot_role_permissions')} VALUES(7001,'inspection.item.complete')");$db->query("INSERT INTO {$q('fm2_pilot_user_roles')} VALUES(7301,7001,'fixture','2026-09-01T09:00:00+03:00',NULL)");$ops=$q('fm2_checklist_operations');$db->query("ALTER TABLE $ops ADD INDEX unexpected_v8_drift(actor_user_id)");$before=iicsdSnapshot($db,$p);$clock=new class implements InspectionEvidenceClock{public int$calls=0;public function now():DateTimeImmutable{$this->calls++;return new DateTimeImmutable('2026-09-01T09:05:00+03:00');}};$app=ProductionInspectionEvidenceFactory::create($db,new ProductionInspectionEvidenceConfig($p),$clock);$r=$app->completeItem(new CompleteInspectionItem(7301,4512,'11111111-1111-4111-8111-111111111111','22222222-2222-4222-8222-222222222222','2026-09-01T08:55:00+03:00',0,1,28,[1042]));assertSameValue(['status'=>'INSPECTION_SCHEMA_UNAVAILABLE','revision'=>0],['status'=>$r->status,'revision'=>$r->revision],'Partial/incompatible v8 index fails closed.');assertSameValue($before,iicsdSnapshot($db,$p),'Schema drift preserves exact v8 metadata, indexes, and all slice-owned rows without DDL repair or business mutation.');assertSameValue(0,$clock->calls,'Schema drift rejects before receipt clock.');echo"PASS: INSPECTION-ITEM-COMPLETE-001 partial v8 schema drift\n";}finally{if($db instanceof mysqli)$db->close();$a->query('DROP DATABASE IF EXISTS '.iicsdQ($d));$a->close();}
