<?php
declare(strict_types=1);
require dirname(__DIR__).'/bootstrap.php';
require dirname(__DIR__).'/Yii2/ObjectQueueFixture.php';
use FMonitor2\InstallationProcess\InspectionPlanningObjectBoundSchemaMigration as Schema;
// INSPECTION-PLANNING-001 A7: public canonical definition owns object-bound plans.
$definitions=Schema::definitions('','utf8mb4_unicode_ci');
$scheduleManifest=$definitions[Schema::SCHEDULES]['manifest'];$eventManifest=$definitions[Schema::EVENTS]['manifest'];
assertSameValue(['id','installation_case_id','legacy_object_id','control_engineer_user_id','inspection_date','scheduled_by_user_id','scheduled_at'],array_column($scheduleManifest['columns'],'name'),'legacy-compatible root columns exact');
$unique=[];foreach($scheduleManifest['indexes']as$index)if($index['nonUnique']===0&&$index['name']!=='PRIMARY')$unique[$index['name']][]=$index['column'];
assertSameValue(['unique_planned_inspection'=>['installation_case_id','inspection_date']],$unique,'INTENDED_RED exact object-date identity excludes engineer');
assertSameValue(['id','schedule_id','installation_case_id','event_type','event_version','request_identity','request_fingerprint','payload_json','actor_user_id','occurred_at'],array_column($eventManifest['columns'],'name'),'INTENDED_RED exact versioned receipt event columns');
$eventUnique=[];foreach($eventManifest['indexes']as$index)if($index['nonUnique']===0&&$index['name']!=='PRIMARY')$eventUnique[$index['name']][]=$index['column'];assertSameValue(['request_identity'=>['request_identity'],'schedule_version'=>['schedule_id','event_version']],$eventUnique,'exact replay/version uniqueness');
assertSameValue(true,class_exists(FMonitor2\InstallationProcess\InspectionPlanningObjectBoundSchemaMigration::class),'INTENDED_RED additive public migration exists');
$f=null;try{$f=new ObjectQueueFixture(dirname(__DIR__,2));$p=$f->p;
$f->insert($p.'fm2_pilot_inspection_schedules',['id'=>91,'installation_case_id'=>6101,'legacy_object_id'=>451201,'control_engineer_user_id'=>7301,'inspection_date'=>'2026-09-12','scheduled_by_user_id'=>9101,'scheduled_at'=>'2026-09-10T09:30:00+03:00']);
$before=$f->rows('fm2_pilot_inspection_schedules');$result=FMonitor2\InstallationProcess\InspectionPlanningObjectBoundSchemaMigration::apply($f->connection(),$p,'2026-09-10');
assertSameValue(true,$result['applied'],'compatible migration applies');assertSameValue($before,$f->rows('fm2_pilot_inspection_schedules'),'ids and rows preserved');
$state=$f->facts();assertSameValue(false,FMonitor2\InstallationProcess\InspectionPlanningObjectBoundSchemaMigration::apply($f->connection(),$p,'2026-09-10')['applied'],'repeat no-op');assertSameValue($state,$f->facts(),'repeat byte-equivalent');
}finally{if($f instanceof ObjectQueueFixture)$f->close();}
$conflict=null;try{$conflict=new ObjectQueueFixture(dirname(__DIR__,2));$p=$conflict->p;
foreach([[101,7301,'2099-09-12'],[102,7302,'2099-09-13']]as[$id,$engineer,$date])$conflict->insert($p.'fm2_pilot_inspection_schedules',['id'=>$id,'installation_case_id'=>6101,'legacy_object_id'=>451201,'control_engineer_user_id'=>$engineer,'inspection_date'=>$date,'scheduled_by_user_id'=>9101,'scheduled_at'=>'2026-09-10T09:30:00+03:00']);
$before=$conflict->facts();$result=FMonitor2\InstallationProcess\InspectionPlanningObjectBoundSchemaMigration::apply($conflict->connection(),$p,'2026-09-10');assertSameValue('SCHEMA_MIGRATION_CONFLICT',$result['reason'],'two current legacy rows fail closed');assertSameValue($before,$conflict->facts(),'conflict changes no schema or rows');
}finally{if($conflict instanceof ObjectQueueFixture)$conflict->close();}
$stages=null;try{$stages=new ObjectQueueFixture(dirname(__DIR__,2));$db=$stages->db;
foreach(['a_','b_']as$stage){assertSameValue(true,FMonitor2\InstallationProcess\InspectionPlanningSchemaMigration::apply($db,$stage)['applied'],'stage v9 setup');$db->query("ALTER TABLE `{$stage}fm2_pilot_inspection_schedules` DROP INDEX unique_planned_inspection, ADD UNIQUE INDEX unique_planned_inspection(installation_case_id,inspection_date)");if($stage==='b_')$db->query("ALTER TABLE `{$stage}fm2_pilot_inspection_schedule_events` ADD event_version INT UNSIGNED NULL AFTER event_type, ADD request_identity CHAR(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL AFTER event_version, ADD request_fingerprint CHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL AFTER request_identity");$result=FMonitor2\InstallationProcess\InspectionPlanningObjectBoundSchemaMigration::apply($db,$stage,'2026-09-10');assertSameValue(true,$result['applied'],'INTENDED_RED resumable durable DDL stage '.$stage);assertSameValue(false,FMonitor2\InstallationProcess\InspectionPlanningObjectBoundSchemaMigration::apply($db,$stage,'2026-09-10')['applied'],'stage repeat no-op');}
$bad='c_';assertSameValue(true,FMonitor2\InstallationProcess\InspectionPlanningSchemaMigration::apply($db,$bad)['applied'],'bad partial v9 setup');$db->query("INSERT INTO `{$bad}fm2_pilot_inspection_schedules` VALUES(301,9001,90001,7301,'2099-12-01',9101,'2026-09-10T09:30:00+03:00')");$db->query("INSERT INTO `{$bad}fm2_pilot_inspection_schedule_events` VALUES(301,301,9001,'inspection_scheduled','{\"scheduleId\":301,\"inspectionDate\":\"2099-12-01\"}',9101,'2026-09-10T09:30:00+03:00'),(302,301,9001,'inspection_rescheduled','{\"scheduleId\":301,\"newDate\":\"2099-12-02\"}',9101,'2026-09-10T09:31:00+03:00')");$db->query("ALTER TABLE `{$bad}fm2_pilot_inspection_schedule_events` ADD event_version INT UNSIGNED NULL AFTER event_type, ADD request_identity CHAR(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL AFTER event_version, ADD request_fingerprint CHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL AFTER request_identity");$db->query("UPDATE `{$bad}fm2_pilot_inspection_schedule_events` SET event_version=1,request_identity='30303030-3030-4030-8030-303030303030',request_fingerprint=REPEAT('3',64)");$before=$stages->facts();try{$result=FMonitor2\InstallationProcess\InspectionPlanningObjectBoundSchemaMigration::apply($db,$bad,'2026-09-10');}catch(Throwable){$result=['reason'=>'UNCLASSIFIED_EXCEPTION'];}assertSameValue('SCHEMA_MIGRATION_CONFLICT',$result['reason']??null,'INTENDED_RED incompatible partial receipts rejected before DDL');assertSameValue($before,$stages->facts(),'incompatible partial has zero durable schema/data mutation');
$semantic='d_';assertSameValue(true,FMonitor2\InstallationProcess\InspectionPlanningSchemaMigration::apply($db,$semantic)['applied'],'semantic partial v9 setup');$db->query("INSERT INTO `{$semantic}fm2_pilot_inspection_schedules` VALUES(401,9101,91001,7301,'2099-12-03',9101,'2026-09-10T09:30:00+03:00')");$db->query("INSERT INTO `{$semantic}fm2_pilot_inspection_schedule_events` VALUES(401,401,9101,'inspection_scheduled','{\"scheduleId\":401,\"inspectionDate\":\"2099-12-03\"}',9101,'2026-09-10T09:30:00+03:00')");$db->query("ALTER TABLE `{$semantic}fm2_pilot_inspection_schedule_events` ADD event_version INT UNSIGNED NULL AFTER event_type, ADD request_identity CHAR(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL AFTER event_version, ADD request_fingerprint CHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL AFTER request_identity");$db->query("UPDATE `{$semantic}fm2_pilot_inspection_schedule_events` SET event_version=7,request_identity='40404040-4040-4040-8040-404040404040',request_fingerprint=REPEAT('4',64)");$before=$stages->facts();$result=FMonitor2\InstallationProcess\InspectionPlanningObjectBoundSchemaMigration::apply($db,$semantic,'2026-09-10');assertSameValue('SCHEMA_MIGRATION_CONFLICT',$result['reason']??null,'INTENDED_RED semantically wrong partial receipt tuple rejected before DDL');assertSameValue($before,$stages->facts(),'semantic partial has zero durable mutation');
$indexes='e_';assertSameValue(true,FMonitor2\InstallationProcess\InspectionPlanningSchemaMigration::apply($db,$indexes)['applied'],'index partial v9 setup');$db->query("ALTER TABLE `{$indexes}fm2_pilot_inspection_schedule_events` ADD event_version INT UNSIGNED NULL AFTER event_type, ADD request_identity CHAR(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL AFTER event_version, ADD request_fingerprint CHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL AFTER request_identity, ADD KEY request_identity(request_identity), ADD KEY schedule_version(schedule_id,event_version)");$before=$stages->facts();$result=FMonitor2\InstallationProcess\InspectionPlanningObjectBoundSchemaMigration::apply($db,$indexes,'2026-09-10');assertSameValue('SCHEMA_MIGRATION_CONFLICT',$result['reason']??null,'INTENDED_RED named nonunique receipt indexes rejected before DDL');assertSameValue($before,$stages->facts(),'nonunique index partial has zero durable mutation');
$p=$stages->p;$stages->insert($p.'fm2_pilot_inspection_schedules',['id'=>191,'installation_case_id'=>6101,'legacy_object_id'=>451201,'control_engineer_user_id'=>7301,'inspection_date'=>'2099-10-01','scheduled_by_user_id'=>9101,'scheduled_at'=>'2026-09-10T09:30:00+03:00']);$stages->insert($p.'fm2_pilot_inspection_schedules',['id'=>192,'installation_case_id'=>6101,'legacy_object_id'=>451201,'control_engineer_user_id'=>7302,'inspection_date'=>'2099-10-02','scheduled_by_user_id'=>9101,'scheduled_at'=>'2026-09-10T09:31:00+03:00']);$stages->insert($p.'fm2_pilot_inspection_schedule_events',['schedule_id'=>191,'installation_case_id'=>6101,'event_type'=>'inspection_scheduled','event_version'=>1,'request_identity'=>'91919191-9191-4191-8191-919191919191','request_fingerprint'=>str_repeat('9',64),'payload_json'=>'{"scheduleId":191,"inspectionDate":"2099-10-01"}','actor_user_id'=>9101,'occurred_at'=>'2026-09-10T09:30:00+03:00']);$before=$stages->facts();$result=FMonitor2\InstallationProcess\InspectionPlanningObjectBoundSchemaMigration::apply($db,$p,'2026-09-10');assertSameValue('SCHEMA_MIGRATION_CONFLICT',$result['reason'],'INTENDED_RED mixed event-backed/eventless current roots conflict');assertSameValue($before,$stages->facts(),'mixed conflict changes nothing');
$atomic='z_';assertSameValue(true,FMonitor2\InstallationProcess\InspectionPlanningSchemaMigration::apply($db,$atomic)['applied'],'atomic v9 setup');assertSameValue(true,FMonitor2\InstallationProcess\InspectionPlanningObjectBoundSchemaMigration::apply($db,$atomic,'2026-09-10')['applied'],'atomic structural v34');foreach([[201,7001,8001],[202,7002,8002]]as[$id,$case,$object])$db->query("INSERT INTO `{$atomic}fm2_pilot_inspection_schedules` VALUES($id,$case,$object,7301,'2099-12-01',9101,'2026-09-10T09:30:00+03:00')");$db->query("CREATE TRIGGER `{$atomic}deny_second_adoption` BEFORE INSERT ON `{$atomic}fm2_pilot_inspection_schedule_events` FOR EACH ROW BEGIN IF NEW.schedule_id=202 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='second adoption fault'; END IF; END");$failed=false;try{FMonitor2\InstallationProcess\InspectionPlanningObjectBoundSchemaMigration::apply($db,$atomic,'2026-09-10');}catch(Throwable){$failed=true;}assertSameValue(true,$failed,'fault is observable');assertSameValue([],$db->query("SELECT * FROM `{$atomic}fm2_pilot_inspection_schedule_events`")->fetch_all(MYSQLI_ASSOC),'INTENDED_RED interrupted adoption leaves zero partial events');$db->query("DROP TRIGGER `{$atomic}deny_second_adoption`");assertSameValue(true,FMonitor2\InstallationProcess\InspectionPlanningObjectBoundSchemaMigration::apply($db,$atomic,'2026-09-10')['applied'],'adoption replay completes');assertSameValue(2,(int)$db->query("SELECT COUNT(*) FROM `{$atomic}fm2_pilot_inspection_schedule_events`")->fetch_column(),'both roots adopted once');
}finally{if($stages instanceof ObjectQueueFixture)$stages->close();}
echo "PASS: INSPECTION-PLANNING-001 canonical object-bound schema\n";
