<?php
declare(strict_types=1);
require dirname(__DIR__).'/bootstrap.php';require dirname(__DIR__).'/Yii2/PreopeningFixture.php';

function lcmRun(PreopeningFixture $f,array $args):array{
    $env=array_replace(getenv(),$f->environment());$cmd=array_merge([PHP_BINARY,$f->root.'/bin/fmonitor2-control-engineer-migration.php'],$args);
    $p=proc_open($cmd,[0=>['file','/dev/null','r'],1=>['pipe','w'],2=>['pipe','w']],$pipes,$f->root,$env);if(!is_resource($p))throw new TestFailure('SETUP_FAILURE process');$out=stream_get_contents($pipes[1]);$err=stream_get_contents($pipes[2]);fclose($pipes[1]);fclose($pipes[2]);return['exit'=>proc_close($p),'out'=>$out,'err'=>$err];
}
function lcmJson(array $r):array{assertSameValue('', $r['err'],'stderr empty');return json_decode($r['out'],true,flags:JSON_THROW_ON_ERROR);}
function lcmFacts(PreopeningFixture$f):string{$p=$f->p;$tables=['fm2_control_engineer_assignments','fm2_assignment_orders','fm2_assignment_order_applications','fm2_assignment_order_originals','fm2_installation_cases','fm2_pilot_users','fm2_legacy_identity_links'];$all=[];foreach($tables as$t)$all[$t]=$f->db->query("SELECT * FROM {$p}{$t} ORDER BY 1")->fetch_all(MYSQLI_ASSOC);return hash('sha256',json_encode($all,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR));}
$f=null;
try{
    $f=new PreopeningFixture(dirname(__DIR__,2));$p=$f->p;
    assertSameValue(true,is_file($f->root.'/bin/fmonitor2-control-engineer-migration.php'),'INTENDED_RED migration CLI absent');
    $f->db->query("INSERT IGNORE INTO {$p}users_roles(id,name,status) VALUES(42,'Строительный контроль',1)");
    $f->db->query("INSERT IGNORE INTO {$p}users(id,name,email,role_id,status) VALUES(73,'Legacy 73','legacy73@example.test',42,1),(74,'Legacy 74','legacy74@example.test',42,0),(75,'Name Collision','collision@example.test',42,1),(76,'Wrong Local Role','wrong@example.test',42,1)");
    $f->db->query("UPDATE {$p}fm_maintable SET responsstroicontrol=73 WHERE id=4512");
    $f->db->query("DELETE FROM {$p}fm2_control_engineer_assignments");
    $f->db->query("INSERT INTO {$p}fm2_legacy_identity_links(local_user_id,legacy_user_id,legacy_name_snapshot,legacy_email_snapshot,legacy_status_snapshot,legacy_role_id_snapshot,legacy_role_status_snapshot,linked_by_user_id,linked_at_utc,request_id,request_fingerprint) VALUES(73,73,'Legacy 73','legacy73@example.test',1,42,1,94,'2026-09-16 12:00:00','20202020-0003-4020-8020-000000000001','".str_repeat('a',64)."')");
    foreach([[4513,0],[4514,999],[4515,74],[4516,75],[4517,76],[4599,73]]as[$id,$engineer]){$f->db->query("INSERT INTO {$p}fm_maintable SELECT $id,ordadr_address,entrance,regnumber,workdatestart,workdatestartadjusted,workdateendadjusted,plan_finish_date,workdatefinish,ptoactdate,installator1,installator2,installator3,installator4,$engineer,ctime,cuser_id,last_ctime,last_cuser_id FROM {$p}fm_maintable WHERE id=4512");if($id!==4599)$f->db->query("INSERT INTO {$p}fm2_installation_cases(legacy_installation_object_id,process_state,created_at,updated_at,lock_version) VALUES($id,'needs_assignment_order','2026-09-16T00:00:00+00:00','2026-09-16T00:00:00+00:00',1)");}
    $f->insert($p.'fm2_pilot_users',['user_id'=>76,'full_name'=>'Wrong Local Role','email'=>'collision@example.test','status'=>1,'activation_state'=>'active','session_version'=>1,'source_updated_at'=>'2026-09-16T11:00:00+03:00']);$f->insert($p.'fm2_pilot_user_roles',['user_id'=>76,'role_id'=>5,'origin'=>'fixture','assigned_at'=>'2026-09-16T11:00:00+03:00']);
    $f->db->query("INSERT INTO {$p}fm2_legacy_identity_links(local_user_id,legacy_user_id,legacy_name_snapshot,legacy_email_snapshot,legacy_status_snapshot,legacy_role_id_snapshot,legacy_role_status_snapshot,linked_by_user_id,linked_at_utc,request_id,request_fingerprint) VALUES(76,76,'Wrong Local Role','wrong@example.test',1,42,1,94,'2026-09-16 12:00:00','20202020-0003-4020-8020-000000000002','".str_repeat('b',64)."')");
    $legacyBefore=json_encode($f->db->query("SELECT * FROM {$p}fm_maintable ORDER BY id")->fetch_all(MYSQLI_ASSOC),JSON_THROW_ON_ERROR);$factsBefore=lcmFacts($f);
    $operation='20202020-0004-4020-8020-000000000001';$preview=$f->artifacts.'/preview.json';
    $first=lcmRun($f,['preview','--all-imported','--operation-id='.$operation,'--output='.$preview]);assertSameValue(0,$first['exit'],'preview exit');$one=lcmJson($first);
    assertSameValue(['ready',4512,73,73],[$one['rows'][0]['status'],$one['rows'][0]['objectId'],$one['rows'][0]['legacyUserId'],$one['rows'][0]['localUserId']],'ready mapping');$byId=array_column($one['rows'],null,'objectId');assertSameValue(['LEGACY_ENGINEER_MISSING','LEGACY_USER_NOT_FOUND','LEGACY_USER_INACTIVE','IDENTITY_LINK_MISSING','LOCAL_ENGINEER_INELIGIBLE'],array_map(static fn($id)=>$byId[$id]['reasonCode'],[4513,4514,4515,4516,4517]),'complete skipped matrix');assertSameValue(false,isset($byId[4599]),'all-imported excludes legacy-only');
    $digestInput=$one;unset($digestInput['digest']);$canonical=json_encode($digestInput,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR);assertSameValue(hash('sha256',$canonical),$one['digest'],'independent canonical digest oracle');assertSameValue($canonical."\n",file_get_contents($preview.'.canonical'),'retained canonical bytes');
    assertSameValue($factsBefore,lcmFacts($f),'preview process read-only');assertSameValue($legacyBefore,json_encode($f->db->query("SELECT * FROM {$p}fm_maintable ORDER BY id")->fetch_all(MYSQLI_ASSOC),JSON_THROW_ON_ERROR),'preview legacy read-only');
    $explicit=lcmJson(lcmRun($f,['preview','--object-id=4599','--operation-id=20202020-0004-4020-8020-000000000002','--output='.$preview.'.explicit']));assertSameValue(['skipped','OBJECT_NOT_IMPORTED'],[$explicit['rows'][0]['status'],$explicit['rows'][0]['reasonCode']],'explicit ID cannot expand target cases');
    foreach([[],['preview','--object-id=01','--operation-id='.$operation,'--output='.$preview.'.bad'],array_merge(['preview','--operation-id='.$operation,'--output='.$preview.'.many'],array_map(static fn($i)=>'--object-id='.$i,range(1,101)))]as$args){$before=lcmFacts($f);$bad=lcmRun($f,$args);assertSameValue(64,$bad['exit'],'argv bounds');assertSameValue($before,lcmFacts($f),'argv rejection no facts');}
    $repeat=lcmJson(lcmRun($f,['preview','--all-imported','--operation-id='.$operation,'--output='.$preview.'.repeat']));assertSameValue($one,$repeat,'deterministic preview');
    $apply=lcmRun($f,['apply','--preview='.$preview,'--operation-id='.$operation,'--digest='.$one['digest']]);assertSameValue(0,$apply['exit'],'apply exit');$applied=lcmJson($apply);assertSameValue(true,$applied['ok'],'apply success');
    $rows=$f->rows('fm2_control_engineer_assignments');assertSameValue(1,count($rows),'one assignment');$row=$rows[0];$expectedFingerprint=hash('sha256',json_encode([$operation,4512,73,73,94],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR));assertSameValue([4512,73,'legacy_fmonitor',$operation,73,73,94,'2026-09-16 12:00:00',$expectedFingerprint],[(int)$row['object_id'],(int)$row['engineer_user_id'],$row['assignment_source'],$row['source_operation_id'],(int)$row['source_legacy_object_id'],(int)$row['source_legacy_user_id'],(int)$row['assigned_by_user_id'],$row['assigned_at_utc'],$row['request_fingerprint']],'complete migration provenance');
    $after=lcmFacts($f);$replay=lcmJson(lcmRun($f,['apply','--preview='.$preview,'--operation-id='.$operation,'--digest='.$one['digest']]));assertSameValue(true,$replay['ok'],'apply replay');assertSameValue($after,lcmFacts($f),'apply replay no facts');
    $reconcile=lcmJson(lcmRun($f,['reconcile','--operation-id='.$operation]));assertSameValue('applied',$reconcile['rows'][0]['status'],'reconcile terminal');
    assertSameValue($legacyBefore,json_encode($f->db->query("SELECT * FROM {$p}fm_maintable ORDER BY id")->fetch_all(MYSQLI_ASSOC),JSON_THROW_ON_ERROR),'apply legacy read-only');
    $f->db->query("UPDATE {$p}fm_maintable SET responsstroicontrol=74 WHERE id=4512");$beforeDrift=lcmFacts($f);$drift=lcmRun($f,['apply','--preview='.$preview,'--operation-id='.$operation,'--digest='.$one['digest']]);assertSameValue(2,$drift['exit'],'drift rejected');assertSameValue('PREVIEW_STALE',lcmJson($drift)['reason'],'drift reason');assertSameValue($beforeDrift,lcmFacts($f),'drift no process facts');
    $badDigest=lcmRun($f,['apply','--preview='.$preview,'--operation-id='.$operation,'--digest='.str_repeat('0',64)]);assertSameValue(2,$badDigest['exit'],'digest mismatch');assertSameValue($beforeDrift,lcmFacts($f),'digest mismatch no facts');
    foreach([$f->dmlPassword,'legacy-secret','SQLSTATE','SELECT ','DO-NOT-READ'] as $secret)foreach([$first,$apply,$drift,$badDigest]as$response)assertSameValue(false,str_contains($response['out'].$response['err'],$secret),'all paths redact '.$secret);
    echo "PASS: LEGACY-CONTROL-ENGINEER-MIGRATION-001 preview apply reconcile\n";
}finally{if($f instanceof PreopeningFixture)$f->close();}
