<?php
declare(strict_types=1);
require dirname(__DIR__).'/bootstrap.php';
use FMonitor2\Tests\Support\{FixedPilotSessionClock,FixedPilotSessionEntropy,NativePilotSessionFilesystem,RecordingPilotSessionObserver};
spl_autoload_register(static function(string$class):void{$p='FMonitor\\IdentityAccess\\';if(str_starts_with($class,$p)){$f=dirname(__DIR__,2).'/app/IdentityAccess/'.substr($class,strlen($p)).'.php';if(is_file($f))require$f;}});assertSameValue(true,class_exists(FMonitor\IdentityAccess\PilotSessionStorageFactory::class),'INTENTIONAL_RED: v7 crash-region owner exists');require dirname(__DIR__).'/Support/PilotSessionStoragePublicApiFixture.php';
$parent=sys_get_temp_dir().'/fmonitor2-session-storage-tests';if(!is_dir($parent)&&!mkdir($parent,0700))throw new RuntimeException('SETUP_FAILURE: parent');$roots=[];$process=null;$pipes=[];$remove=function(string$p)use(&$remove):void{if(is_link($p)||is_file($p)){unlink($p);return;}if(!is_dir($p))return;foreach(scandir($p)?:[]as$e)if($e!=='.'&&$e!=='..')$remove($p.'/'.$e);rmdir($p);};
try{foreach([['fsyncFile','stage',1,'old'],['link','revoked',1,'old'],['unlink','committed',1,'neither'],['link','committed',1,'new']]as[$op,$artifact,$ordinal,$valid]){$root=$parent.'/task-'.bin2hex(random_bytes(9));$roots[]=$root;mkdir($root,0700);$marker=$parent.'/marker-'.bin2hex(random_bytes(7));$owner=(new FMonitor\IdentityAccess\PilotSessionStorageFactory())->create(new FMonitor\IdentityAccess\PilotSessionStorageConfig($root,'crash_v7'),new NativePilotSessionFilesystem(),new FixedPilotSessionClock(1_788_200_000,1_000),new FixedPilotSessionEntropy([str_repeat("\x11",32),str_repeat("\x22",16),str_repeat("\x33",12)]),new RecordingPilotSessionObserver());$s=$owner->start(null);$old=(string)$s->currentSessionId();assertSameValue('OK',$owner->writeCommit($old,'old-crash-bytes')->status()->name,"$op seed");$owner->close();$process=proc_open([PHP_BINARY,dirname(__DIR__).'/Support/pilot_session_storage_crash_runner.php',$root,$old,$marker,$op,$artifact,(string)$ordinal],[1=>['pipe','w'],2=>['pipe','w']],$pipes,dirname(__DIR__,2));if(!is_resource($process))throw new RuntimeException('SETUP_FAILURE: child');$d=microtime(true)+3;while(!is_file($marker)&&microtime(true)<$d){if(!proc_get_status($process)['running'])throw new RuntimeException('SETUP_FAILURE: boundary absent '.stream_get_contents($pipes[2]));usleep(10000);}assertSameValue(true,is_file($marker),"$op/$artifact reached");proc_terminate($process,9);$d=microtime(true)+1;while(proc_get_status($process)['running']&&microtime(true)<$d)usleep(10000);if(proc_get_status($process)['running'])proc_terminate($process,9);foreach($pipes as$p){stream_get_contents($p);fclose($p);}proc_close($process);$process=null;unlink($marker);$files=glob("$root/sessions/crash_v7/s-*.session")?:[];$oldExists=is_file("$root/sessions/crash_v7/s-$old.session");assertSameValue($valid==='old',$oldExists,"$op old validity");assertSameValue($valid==='new',count($files)===1&&!$oldExists,"$op new-only validity");if($valid==='neither')assertSameValue([],$files,"$op neither ID valid");foreach(glob("$root/sessions/crash_v7/.{stage,revoked}-*",GLOB_BRACE)?:[]as$p)assertSameValue(false,str_starts_with(basename($p),'s-'),'intermediate never addressable');}
 echo"PASS: PILOT-SESSION-STORAGE-001 v7 crash regions\n";
}finally{if(is_resource($process)){proc_terminate($process,9);foreach($pipes as$p)if(is_resource($p))fclose($p);proc_close($process);}foreach($roots as$r)$remove($r);if(is_dir($parent)&&count(scandir($parent)?:[])===2)rmdir($parent);}
