<?php
declare(strict_types=1);
require dirname(__DIR__).'/bootstrap.php';
use FMonitor2\Tests\Support\{FixedPilotSessionClock,FixedPilotSessionEntropy,NativePilotSessionFilesystem,RecordingPilotSessionObserver};
spl_autoload_register(static function(string$class):void{$p='FMonitor\\IdentityAccess\\';if(str_starts_with($class,$p)){$f=dirname(__DIR__,2).'/app/IdentityAccess/'.substr($class,strlen($p)).'.php';if(is_file($f))require$f;}});
assertSameValue(true,class_exists(FMonitor\IdentityAccess\PilotSessionStorageFactory::class),'INTENTIONAL_RED: v7 concurrent owner exists');require dirname(__DIR__).'/Support/PilotSessionStoragePublicApiFixture.php';if(!function_exists('pcntl_fork'))throw new RuntimeException('SETUP_FAILURE: pcntl required');
$parent=sys_get_temp_dir().'/fmonitor2-session-storage-tests';$root=$parent.'/task-'.bin2hex(random_bytes(10));mkdir($root,0700,true);chmod($root,0700);$control=$parent.'/control-'.bin2hex(random_bytes(8));mkdir($control,0700);$children=[];$remove=function(string$p)use(&$remove):void{if(is_link($p)||is_file($p)){unlink($p);return;}if(!is_dir($p))return;foreach(scandir($p)?:[]as$e)if($e!=='.'&&$e!=='..')$remove($p.'/'.$e);rmdir($p);};
try{for($i=1;$i<=2;$i++){$pid=pcntl_fork();if($pid===-1)throw new RuntimeException('SETUP_FAILURE: fork');if($pid===0){file_put_contents("$control/ready-$i",'1');$d=microtime(true)+3;while(!is_file("$control/release")&&microtime(true)<$d)usleep(10000);if(!is_file("$control/release"))exit(80);$owner=(new FMonitor\IdentityAccess\PilotSessionStorageFactory())->create(new FMonitor\IdentityAccess\PilotSessionStorageConfig($root,'race_v7'),new NativePilotSessionFilesystem(),new FixedPilotSessionClock(1_788_200_000,1000),new FixedPilotSessionEntropy([str_repeat(chr(16+$i),32),str_repeat(chr(32+$i),16),str_repeat(chr(48+$i),12)]),new RecordingPilotSessionObserver());$s=$owner->start(null);$r=$s->status()->name==='OK'?$owner->writeCommit((string)$s->currentSessionId(),"worker-$i"):null;$owner->close();exit($r?->status()->name==='OK'?0:81);} $children[]=$pid;}
 $d=microtime(true)+3;while((!is_file("$control/ready-1")||!is_file("$control/ready-2"))&&microtime(true)<$d)usleep(10000);assertSameValue(true,is_file("$control/ready-1")&&is_file("$control/ready-2"),'both workers at barrier');file_put_contents("$control/release",'1');foreach($children as$pid){$d=microtime(true)+4;do{$done=pcntl_waitpid($pid,$status,WNOHANG);if($done===0)usleep(10000);}while($done===0&&microtime(true)<$d);if($done===0){posix_kill($pid,SIGKILL);pcntl_waitpid($pid,$status);}assertSameValue(0,pcntl_wexitstatus($status),'concurrent child owner succeeded');}$children=[];$files=glob("$root/sessions/race_v7/s-*.session")?:[];assertSameValue(2,count($files),'two material sessions after concurrent first mkdir');$bytes=array_map('file_get_contents',$files);sort($bytes,SORT_STRING);assertSameValue(['worker-1','worker-2'],$bytes,'both independent committed bytes');
 $overflow=$parent.'/task-'.bin2hex(random_bytes(10));mkdir("$overflow/sessions/gc_v7",0700,true);chmod($overflow,0700);chmod("$overflow/sessions",0700);for($i=0;$i<10001;$i++){file_put_contents("$overflow/sessions/gc_v7/foreign-$i",'x');chmod("$overflow/sessions/gc_v7/foreign-$i",0600);}$before=count(scandir("$overflow/sessions/gc_v7")?:[]);$owner=(new FMonitor\IdentityAccess\PilotSessionStorageFactory())->create(new FMonitor\IdentityAccess\PilotSessionStorageConfig($overflow,'gc_v7'),new NativePilotSessionFilesystem(),new FixedPilotSessionClock(1_788_200_000,1000),new FixedPilotSessionEntropy([str_repeat('g',12)]),new RecordingPilotSessionObserver());$r=$owner->start(null);assertSameValue('GC_FAILED',$r->category()?->name,'10001 entries fail GC without deletion');assertSameValue($before,count(scandir("$overflow/sessions/gc_v7")?:[]),'overflow deletes nothing');$owner->close();$remove($overflow);echo"PASS: PILOT-SESSION-STORAGE-001 v7 concurrency and GC overflow\n";
}finally{foreach($children as$pid){@posix_kill($pid,SIGKILL);pcntl_waitpid($pid,$s);}$remove($root);$remove($control);if(is_dir($parent)&&count(scandir($parent)?:[])===2)rmdir($parent);}
