<?php
declare(strict_types=1);
require dirname(__DIR__).'/bootstrap.php';
use FMonitor2\Tests\Support\{FixedPilotSessionClock,LengthQueuedPilotSessionEntropy,NativePilotSessionFilesystem,RecordingPilotSessionObserver};
spl_autoload_register(static function(string$class):void{$p='FMonitor\\IdentityAccess\\';if(str_starts_with($class,$p)){$f=dirname(__DIR__,2).'/app/IdentityAccess/'.substr($class,strlen($p)).'.php';if(is_file($f))require$f;}});
assertSameValue(true,class_exists(FMonitor\IdentityAccess\PilotSessionStorageFactory::class),'INTENTIONAL_RED: v7 lifecycle owner exists');require dirname(__DIR__).'/Support/PilotSessionStoragePublicApiFixture.php';
$parent=sys_get_temp_dir().'/fmonitor2-session-storage-tests';if(!is_dir($parent)&&!mkdir($parent,0700))throw new RuntimeException('SETUP_FAILURE: parent');$roots=[];$remove=function(string$p)use(&$remove):void{if(is_link($p)||is_file($p)){unlink($p);return;}if(!is_dir($p))return;foreach(scandir($p)?:[]as$e)if($e!=='.'&&$e!=='..')$remove($p.'/'.$e);rmdir($p);};
$ownerSequence=0;$newOwner=static function(string$root,NativePilotSessionFilesystem$fs)use(&$ownerSequence):FMonitor\IdentityAccess\PilotSessionStorage{$ownerSequence++;$q=[32=>[],16=>[],12=>[]];foreach(array_keys($q)as$length)for($i=0;$i<20;$i++)$q[$length][]=str_repeat(chr(32+(($ownerSequence+$i+$length)%80)),$length);return(new FMonitor\IdentityAccess\PilotSessionStorageFactory())->create(new FMonitor\IdentityAccess\PilotSessionStorageConfig($root,'life_v7'),$fs,new FixedPilotSessionClock(1_788_200_000,1_000),new LengthQueuedPilotSessionEntropy($q),new RecordingPilotSessionObserver());};
try{foreach([
 ['read','committed',1,'start','READ_FAILED','old','false'],['read','committed',1,'start','READ_FAILED','old','short-read'],['mtime','committed',1,'start','GC_FAILED','old','false'],
 ['rename','committed',1,'write','PUBLISH_FAILED','old','false'],['link','revoked',1,'regenerate','REGENERATE_FAILED','old','false'],
 ['unlink','committed',1,'regenerate','REGENERATE_FAILED','old','false'],['link','revoked',1,'destroy','DESTROY_FAILED','old','false'],
 ['unlink','committed',1,'destroy','DESTROY_FAILED','old','false'],
]as[$operation,$artifact,$ordinal,$action,$category,$valid]){$root=$parent.'/task-'.bin2hex(random_bytes(10));$roots[]=$root;mkdir($root,0700);$seed=$newOwner($root,new NativePilotSessionFilesystem());$start=$seed->start(null);$old=(string)$start->currentSessionId();assertSameValue('OK',$seed->writeCommit($old,'old-lifecycle')->status()->name,"$operation seed");$seed->close();$owner=$newOwner($root,new NativePilotSessionFilesystem($operation,$artifact,$ordinal,'false'));$result=match($action){'start'=>$owner->start($old),'write'=>(function()use($owner,$old){$s=$owner->start($old);assertSameValue('OK',$s->status()->name,'write predecessor read');return$owner->writeCommit($old,'replacement');})(),'regenerate'=>$owner->regenerate($old,'new-lifecycle'),'destroy'=>$owner->destroyCommit($old)};assertSameValue('UNAVAILABLE',$result->status()->name,"$action/$operation unavailable");assertSameValue($category,$result->category()?->name,"$action/$operation category");$committed="$root/sessions/life_v7/s-$old.session";if($valid==='old')assertSameValue(true,is_file($committed),"$action/$operation old material preserved before invalidation");$owner->close();}
 $root=$parent.'/task-'.bin2hex(random_bytes(10));$roots[]=$root;mkdir($root,0700);$owner=$newOwner($root,new NativePilotSessionFilesystem());$missing=str_repeat('M',16);$before=[];$destroy=$owner->destroyCommit($missing);assertSameValue('OK',$destroy->status()->name,'absent destroy idempotent');assertSameValue(null,$destroy->currentSessionId(),'absent destroy has no id');$stale=$owner->regenerate($missing,'none');assertSameValue('SESSION_STALE',$stale->category()?->name,'stale regeneration exact category');$start=$owner->start(null);$old=(string)$start->currentSessionId();assertSameValue('OK',$owner->writeCommit($old,'old-success')->status()->name,'success predecessor');$regen=$owner->regenerate($old,'new-success');$new=(string)$regen->currentSessionId();assertSameValue('OK',$regen->status()->name,'successful regeneration');assertSameValue(false,is_file("$root/sessions/life_v7/s-$old.session"),'old invalid after regeneration');assertSameValue('new-success',file_get_contents("$root/sessions/life_v7/s-$new.session"),'only new bytes addressable');assertSameValue(1,count(glob("$root/sessions/life_v7/s-*.session")?:[]),'dual-valid IDs forbidden');assertSameValue('OK',$owner->destroyCommit($new)->status()->name,'successful destroy');assertSameValue([],glob("$root/sessions/life_v7/s-*.session")?:[],'destroy leaves no valid ID');$owner->close();echo"PASS: PILOT-SESSION-STORAGE-001 v7 lifecycle primitive faults\n";
}finally{foreach($roots as$r)$remove($r);if(is_dir($parent)&&count(scandir($parent)?:[])===2)rmdir($parent);}
