<?php
declare(strict_types=1);

require dirname(__DIR__) . '/bootstrap.php';

// Specification: PILOT-SHLZ-ASSETS-001 v0.1.
// Confirmed public seam: raw HTTP GET|HEAD /pilot/assets/shlz.css and its
// fixed, browser-relative manifest routes. Expected bytes are task-owned.

function psaPort(): int { $s=stream_socket_server('tcp://127.0.0.1:0',$e,$m);if($s===false)throw new TestFailure('allocate port');$n=(string)stream_socket_get_name($s,false);fclose($s);return (int)substr($n,strrpos($n,':')+1); }
function psaStart(string $entry,array $extra=[]): array { $port=psaPort();$cmd=['/usr/bin/env','-i','FMONITOR_SHLZ_CSS_PATH='.$entry];foreach($extra as$k=>$v)$cmd[]=$k.'='.$v;$cmd=[...$cmd,PHP_BINARY,'-d','expose_php=0','-S','127.0.0.1:'.$port,dirname(__DIR__,2).'/public/router.php'];$p=proc_open($cmd,[0=>['pipe','r'],1=>['pipe','w'],2=>['pipe','w']],$pipes,dirname(__DIR__,2));if(!is_resource($p))throw new TestFailure('start server');fclose($pipes[0]);stream_set_blocking($pipes[1],false);stream_set_blocking($pipes[2],false);$until=microtime(true)+5;while(microtime(true)<$until){$s=@stream_socket_client("tcp://127.0.0.1:$port",$e,$m,.1);if($s!==false){fclose($s);return compact('p','pipes','port');}usleep(20000);}throw new TestFailure('server listen'); }
function psaStop(?array $s): void { if($s===null||!is_resource($s['p']))return;if(proc_get_status($s['p'])['running'])proc_terminate($s['p']);foreach([1,2]as$i)if(is_resource($s['pipes'][$i])){stream_get_contents($s['pipes'][$i]);fclose($s['pipes'][$i]);}proc_close($s['p']); }
function psaRequest(int $port,string $method,string $route): array { $s=stream_socket_client("tcp://127.0.0.1:$port",$e,$m,5);if($s===false)throw new TestFailure('connect');fwrite($s,"$method $route HTTP/1.1\r\nHost: assets.example\r\nConnection: close\r\nContent-Length: 0\r\n\r\n");stream_socket_shutdown($s,STREAM_SHUT_WR);$raw='';while(!feof($s))$raw.=(string)fread($s,65536);fclose($s);[$h,$body]=array_pad(explode("\r\n\r\n",$raw,2),2,'');$lines=explode("\r\n",$h);preg_match('/^HTTP\/\d\.\d (\d{3})/',(string)array_shift($lines),$m);$headers=[];foreach($lines as$l)if(str_contains($l,':')){[$k,$v]=explode(':',$l,2);$headers[strtolower(trim($k))][]=trim($v);}return ['status'=>(int)($m[1]??0),'headers'=>$headers,'body'=>$body]; }
function psaHeader(array $r,string $name): ?string { $v=$r['headers'][strtolower($name)]??[];return count($v)===1?$v[0]:null; }
function psaSecurity(array $r,string $why): void { $exact=['x-content-type-options'=>'nosniff','referrer-policy'=>'no-referrer','x-frame-options'=>'DENY','content-security-policy'=>"default-src 'none'; style-src 'self'; img-src 'self'; font-src 'self'; base-uri 'none'; form-action 'self'; frame-ancestors 'none'",'permissions-policy'=>'camera=(), microphone=(), geolocation=()','cross-origin-opener-policy'=>'same-origin','cache-control'=>'no-store','host'=>'assets.example'];foreach($exact as$n=>$v)assertSameValue($v,psaHeader($r,$n),$why.' '.$n);foreach(['set-cookie','access-control-allow-origin','server','x-powered-by','www-authenticate']as$n)assertSameValue(null,psaHeader($r,$n),$why.' forbids '.$n); }
function psaExact(array $r,int $status,string $type,string $body,string $why,array $extra=[]): void { assertSameValue([$status,$type,(string)strlen($body),$body],[$r['status'],psaHeader($r,'content-type'),psaHeader($r,'content-length'),$r['body']],$why);foreach($extra as$n=>$v)assertSameValue($v,psaHeader($r,$n),$why.' '.$n);psaSecurity($r,$why); }
function psaGetHead(int $port,string $route,string $bytes): void { $get=psaRequest($port,'GET',$route);psaExact($get,200,'text/css; charset=UTF-8',$bytes,'GET exact '.$route);$head=psaRequest($port,'HEAD',$route);assertSameValue([200,'text/css; charset=UTF-8',(string)strlen($bytes),''],[$head['status'],psaHeader($head,'content-type'),psaHeader($head,'content-length'),$head['body']],'HEAD exact '.$route);psaSecurity($head,'HEAD exact '.$route); }
function psaError(array $r,int $status,string $why,array $extra=[]): void { $body=$status===503?"Service unavailable.\n":($status===405?"Method not allowed.\n":"Not found.\n");psaExact($r,$status,'text/plain; charset=UTF-8',$body,$why,$extra);foreach(['PRIVATE-UNREFERENCED','SECRET-OUTSIDE','ATTACKER-REPLACEMENT','/home/','Exception','stack trace']as$secret)assertSameValue(false,str_contains($r['body'],$secret),$why.' redaction'); }
function psaWriteGraph(string $root,array $files): string { foreach($files as$relative=>$bytes){$path=$root.'/'.$relative;if(!is_dir(dirname($path)))mkdir(dirname($path),0700,true);file_put_contents($path,$bytes);}return $root.'/shlz.css'; }
function psaRemoveTree(string $root): void { if(!is_dir($root))return;$it=new RecursiveIteratorIterator(new RecursiveDirectoryIterator($root,FilesystemIterator::SKIP_DOTS),RecursiveIteratorIterator::CHILD_FIRST);foreach($it as$f){$p=$f->getPathname();if($f->isLink()||$f->isFile())unlink($p);else rmdir($p);}rmdir($root); }

$token=bin2hex(random_bytes(6));$base=dirname(__DIR__,2).'/.test-artifacts/psa-'.$token;$server=null;
try {
 mkdir($base,0700,true);$dist=$base.'/split-dist';mkdir($dist,0700);
 $members=[
  'shlz.css'=>"@charset \"UTF-8\";\n@import \"./foundation.css\";\n@import url(\"./components/button.css\") layer(components);\n@import url(components/card.css) screen;\n.shlz-scope{color:var(--shlz-color-text)}\n",
  'foundation.css'=>"@import \"./tokens/colors.css\";\n:root{--shlz-space:8px}\n",
  'components/button.css'=>".shlz-button{display:inline-flex}\n",
  'components/card.css'=>"@import \"../tokens/colors.css\";\n.shlz-card{display:block}\n",
  'tokens/colors.css'=>":root{--shlz-color-text:#202124}\n",
 ];
 $entry=psaWriteGraph($dist,$members);file_put_contents($dist.'/private.css',"PRIVATE-UNREFERENCED\n");
 $server=psaStart($entry);
 // Tracer bullet order is intentional: root already passes; first missing behavior is the first split import route.
 foreach(['/pilot/assets/shlz.css'=>'shlz.css','/pilot/assets/foundation.css'=>'foundation.css','/pilot/assets/components/button.css'=>'components/button.css','/pilot/assets/components/card.css'=>'components/card.css','/pilot/assets/tokens/colors.css'=>'tokens/colors.css']as$route=>$file)psaGetHead($server['port'],$route,$members[$file]);
 psaError(psaRequest($server['port'],'GET','/pilot/assets/private.css'),404,'unreferenced readable file is outside manifest');
 foreach(['/pilot/assets/unknown.css','/pilot/assets/components/unknown.css']as$route)psaError(psaRequest($server['port'],'GET',$route),404,'unknown manifest-shaped route '.$route);
 foreach(['/pilot/assets/','/pilot/assets//foundation.css','/pilot/assets/./foundation.css','/pilot/assets/../secret.css','/pilot/assets/%2e/foundation.css','/pilot/assets/%252e%252e/secret.css','/pilot/assets/components%2fbutton.css','/pilot/assets/components%252fbutton.css','/pilot/assets/components\\button.css','/pilot/assets/foundation.css/','/pilot/assets/foundation.CSS','/pilot/assets/foundation.css.map','/pilot/assets/%00.css']as$route)psaError(psaRequest($server['port'],'GET',$route),404,'malformed route '.$route);
 foreach(['POST','PUT','PATCH','DELETE','OPTIONS']as$method)psaError(psaRequest($server['port'],$method,'/pilot/assets/foundation.css'),405,$method.' valid candidate',['allow'=>'GET, HEAD']);
 psaStop($server);$server=null;

 $invalidImports=['../secret.css','/absolute.css','https://example.test/x.css','//example.test/x.css','data:text/css,x','@shlz/styles/x.css','foundation.css?x','foundation.css#x','FOUNDATION.CSS','image.png','components\\button.css','components/%62utton.css','components/../button.css',''];
 foreach($invalidImports as$i=>$target){$root=$base.'/invalid-'.$i;mkdir($root,0700);$bad="@import url(\"$target\");\n.safe{display:block}\n";psaWriteGraph($root,['shlz.css'=>$bad,'foundation.css'=>'SAFE-TARGET','button.css'=>'SAFE-TARGET']);$s=psaStart($root.'/shlz.css');psaError(psaRequest($s['port'],'GET','/pilot/assets/shlz.css'),503,'invalid graph import '.$i,['retry-after'=>'60']);psaStop($s);}
 $broken=$base.'/priority';mkdir($broken,0700);psaWriteGraph($broken,['shlz.css'=>"@import \"../secret.css\";\n"]);$s=psaStart($broken.'/shlz.css');psaError(psaRequest($s['port'],'GET','/pilot/assets/components/button.css'),503,'well-formed candidate exposes broken graph',['retry-after'=>'60']);psaError(psaRequest($s['port'],'GET','/pilot/assets/%2e%2e/secret.css'),404,'malformed route precedes broken graph');psaError(psaRequest($s['port'],'POST','/pilot/assets/components/button.css'),405,'method precedes broken graph',['allow'=>'GET, HEAD']);psaStop($s);
 foreach(["@import url(\"unterminated.css);\n", "\xFF\xFE", "@import \"pilot.css\";\n"]as$i=>$bad){$root=$base.'/malformed-'.$i;mkdir($root,0700);psaWriteGraph($root,['shlz.css'=>$bad,'pilot.css'=>'COLLISION']);$s=psaStart($root.'/shlz.css');psaError(psaRequest($s['port'],'GET','/pilot/assets/shlz.css'),503,'malformed/collision graph '.$i,['retry-after'=>'60']);psaStop($s);}
 $linkRoot=$base.'/symlink-file';mkdir($linkRoot,0700);psaWriteGraph($linkRoot,['shlz.css'=>"@import \"dependency.css\";\n",'real.css'=>'SECRET-OUTSIDE']);symlink($linkRoot.'/real.css',$linkRoot.'/dependency.css');$s=psaStart($linkRoot.'/shlz.css');psaError(psaRequest($s['port'],'GET','/pilot/assets/dependency.css'),503,'dependency symlink',['retry-after'=>'60']);psaStop($s);
 $dirLinkRoot=$base.'/symlink-dir';mkdir($dirLinkRoot,0700);mkdir($dirLinkRoot.'/real');file_put_contents($dirLinkRoot.'/real/dependency.css','SECRET-OUTSIDE');file_put_contents($dirLinkRoot.'/shlz.css',"@import \"linked/dependency.css\";\n");symlink($dirLinkRoot.'/real',$dirLinkRoot.'/linked');$s=psaStart($dirLinkRoot.'/shlz.css');psaError(psaRequest($s['port'],'GET','/pilot/assets/linked/dependency.css'),503,'dependency directory symlink',['retry-after'=>'60']);psaStop($s);
 $missing=$base.'/removed';mkdir($missing,0700);psaWriteGraph($missing,['shlz.css'=>"@import \"dependency.css\";\n",'dependency.css'=>'ORIGINAL']);$s=psaStart($missing.'/shlz.css');psaGetHead($s['port'],'/pilot/assets/shlz.css',"@import \"dependency.css\";\n");unlink($missing.'/dependency.css');psaError(psaRequest($s['port'],'GET','/pilot/assets/dependency.css'),503,'manifest member removal after manifest capture',['retry-after'=>'60']);psaStop($s);
 $swap=$base.'/regular-swap';mkdir($swap,0700);psaWriteGraph($swap,['shlz.css'=>"@import \"dependency.css\";\n",'dependency.css'=>'ORIGINAL-MEMBER']);$s=psaStart($swap.'/shlz.css');psaGetHead($s['port'],'/pilot/assets/shlz.css',"@import \"dependency.css\";\n");rename($swap.'/dependency.css',$swap.'/original.css');file_put_contents($swap.'/dependency.css','ATTACKER-REPLACEMENT');psaError(psaRequest($s['port'],'GET','/pilot/assets/dependency.css'),503,'regular-file identity swap after manifest capture',['retry-after'=>'60']);psaStop($s);
 echo "PASS: PILOT-SHLZ-ASSETS-001 public CSS manifest\n";
} finally { psaStop($server);psaRemoveTree($base); }
