<?php
declare(strict_types=1);
require dirname(__DIR__) . '/bootstrap.php';
// Specification: PILOT-CASE-IMPORT-001 v0.2.

function pciDb(?string $database=null):mysqli{$c=new mysqli(getenv('FMONITOR_TEST_DB_HOST')?:'127.0.0.1',getenv('FMONITOR_TEST_DB_ADMIN_USER')?:'root',getenv('FMONITOR_TEST_DB_ADMIN_PASSWORD')?:'fmonitor2_demo_local',$database,(int)(getenv('FMONITOR_TEST_DB_PORT')?:23306));$c->set_charset('utf8mb4');return $c;}
function pciRows(mysqli $c,string $sql):array{return $c->query($sql)->fetch_all(MYSQLI_ASSOC);}
function pciCommand(array $env,array $argv,string $script='bin/fmonitor2-import-cases.php'):array{$command=['/usr/bin/env','-i'];foreach($env as $name=>$value)$command[]=$name.'='.$value;return [...$command,PHP_BINARY,dirname(__DIR__,2).'/'.$script,...$argv];}
function pciRun(array $env,array $argv,string $stdin='',string $script='bin/fmonitor2-import-cases.php'):array{$pipes=[];$p=proc_open(pciCommand($env,$argv,$script),[0=>['pipe','r'],1=>['pipe','w'],2=>['pipe','w']],$pipes,dirname(__DIR__,2));if(!is_resource($p))throw new TestFailure('CLI process must start.');fwrite($pipes[0],$stdin);fclose($pipes[0]);$out=stream_get_contents($pipes[1]);$err=stream_get_contents($pipes[2]);fclose($pipes[1]);fclose($pipes[2]);return ['exitCode'=>proc_close($p),'stdout'=>$out,'stderr'=>$err];}
function pciResult(array $expected,array $actual,string $why,array $secrets=[]):void{assertSameValue($expected,$actual,$why);assertSameValue(1,substr_count($actual['stdout'],"\n"),$why.' one JSON line');assertSameValue("\n",substr($actual['stdout'],-1),$why.' newline');json_decode(rtrim($actual['stdout'],"\n"),true,512,JSON_THROW_ON_ERROR);foreach($secrets as $secret)if($secret!=='' )assertSameValue(false,str_contains($actual['stdout'].$actual['stderr'],$secret),$why.' redaction');}
function pciEnv(string $database,string $process='pr_',string $legacy='legacy_'):array{return ['FMONITOR_DB_HOST'=>getenv('FMONITOR_TEST_DB_HOST')?:'127.0.0.1','FMONITOR_DB_PORT'=>getenv('FMONITOR_TEST_DB_PORT')?:'23306','FMONITOR_DB_NAME'=>$database,'FMONITOR_DB_USER'=>getenv('FMONITOR_TEST_DB_ADMIN_USER')?:'root','FMONITOR_DB_PASSWORD'=>getenv('FMONITOR_TEST_DB_ADMIN_PASSWORD')?:'fmonitor2_demo_local','FMONITOR_PROCESS_TABLE_PREFIX'=>$process,'FMONITOR_LEGACY_TABLE_PREFIX'=>$legacy];}
function pciMigrate(array $env):void{$migration=array_diff_key($env,['FMONITOR_LEGACY_TABLE_PREFIX'=>true]);pciResult(['exitCode'=>0,'stdout'=>"{\"ok\":true,\"schemaVersion\":12,\"appliedVersions\":[1,2,3,4,5,6,7,8,9,10,11,12]}\n",'stderr'=>''],pciRun($migration,[],'','bin/fmonitor2-migrate.php'),'Canonical v12 migration precondition.');$db=pciDb($env['FMONITOR_DB_NAME']);$prefix=$env['FMONITOR_PROCESS_TABLE_PREFIX'];foreach(['fm2_assignment_order_original_maintenance_results','fm2_assignment_order_original_attempt_audits','fm2_assignment_order_original_events','fm2_assignment_order_original_fingerprints','fm2_assignment_order_original_requests','fm2_assignment_order_original_revisions','fm2_assignment_order_original_roots','fm2_pilot_completion_fact_corrections','fm2_pilot_completion_facts','fm2_migration_classification_provenance']as$table)$db->query("DROP TABLE `{$prefix}{$table}`");$db->close();}
function pciProcessState(mysqli $c,string $prefix):array{$state=[];foreach(['fm2_installation_cases','fm2_assignment_orders','fm2_order_installers','fm2_order_artifacts','fm2_process_tasks','fm2_process_events','fm2_workforce_catalog','fm2_process_user_capabilities'] as $table)$state[$table]=pciRows($c,"SELECT * FROM {$prefix}{$table} ORDER BY 1");return $state;}
function pciRace(array $environment,array $argv):array{$children=[];$results=[];try{for($index=0;$index<2;$index++){$pipes=[];$process=proc_open(pciCommand($environment,$argv),[0=>['pipe','r'],1=>['pipe','w'],2=>['pipe','w']],$pipes,dirname(__DIR__,2));if(!is_resource($process))throw new TestFailure('Both race processes must spawn.');fclose($pipes[0]);$children[]=['process'=>$process,'pipes'=>$pipes,'reaped'=>false];}foreach($children as $index=>&$child){$stdout=stream_get_contents($child['pipes'][1]);$stderr=stream_get_contents($child['pipes'][2]);fclose($child['pipes'][1]);fclose($child['pipes'][2]);$exitCode=proc_close($child['process']);$child['reaped']=true;$results[]=compact('exitCode','stdout','stderr');}unset($child);return $results;}finally{foreach($children as $child){foreach([1,2] as $fd)if(isset($child['pipes'][$fd])&&is_resource($child['pipes'][$fd]))fclose($child['pipes'][$fd]);if(!$child['reaped']&&is_resource($child['process'])){$status=proc_get_status($child['process']);if($status['running'])proc_terminate($child['process']);proc_close($child['process']);}}}}
function pciRunBeforeStdinEof(array $environment, array $argv, int $timeoutSeconds = 5, string $immediateBytes = '', ?string $delayedBytes = null, ?callable $afterDelayedBytes = null): array
{
    $pipes = [];
    $process = proc_open(
        pciCommand($environment, $argv),
        [0 => ['pipe', 'r'], 1 => ['pipe', 'w'], 2 => ['pipe', 'w']],
        $pipes,
        dirname(__DIR__, 2),
    );
    if (!is_resource($process)) {
        throw new TestFailure('Interactive tracer process must spawn.');
    }
    $reaped = false;
    $afterDelayedCalled = false;
    try {
        if ($immediateBytes !== '') {
            assertSameValue(strlen($immediateBytes), @fwrite($pipes[0], $immediateBytes), 'Immediate stdin fixture bytes must be delivered while writer remains open.');
            fflush($pipes[0]);
        }
        if ($delayedBytes !== null) {
            usleep(150000);
            assertSameValue(strlen($delayedBytes), @fwrite($pipes[0], $delayedBytes), 'Delayed stdin fixture bytes must be delivered while writer remains open.');
            fflush($pipes[0]);
            if ($afterDelayedBytes !== null) {
                $afterDelayedBytes();
                $afterDelayedCalled = true;
            }
        }
        stream_set_blocking($pipes[1], false);
        stream_set_blocking($pipes[2], false);
        $stdout = '';
        $stderr = '';
        $observedExitCode = null;
        $finishedBeforeEof = false;
        $deadline = microtime(true) + $timeoutSeconds;
        while (microtime(true) < $deadline) {
            $read = [$pipes[1], $pipes[2]];
            $write = $except = [];
            if (stream_select($read, $write, $except, 0, 100000) === false) {
                throw new TestFailure('Interactive tracer select failed.');
            }
            foreach ($read as $stream) {
                $chunk = stream_get_contents($stream);
                if ($stream === $pipes[1]) {
                    $stdout .= $chunk;
                } else {
                    $stderr .= $chunk;
                }
            }
            $status = proc_get_status($process);
            if (!$status['running']) {
                $stdout .= stream_get_contents($pipes[1]);
                $stderr .= stream_get_contents($pipes[2]);
                $observedExitCode = $status['exitcode'];
                $finishedBeforeEof = true;
                break;
            }
        }
        if (!$finishedBeforeEof || !str_contains($stdout, "\n")) {
            throw new TestFailure('Valid importer invocation must exit with its exact result while stdin remains open.');
        }

        // Only after observing process exit and a complete line do we close stdin and drain/reap.
        fclose($pipes[0]);
        $stdout .= stream_get_contents($pipes[1]);
        $stderr .= stream_get_contents($pipes[2]);
        fclose($pipes[1]);
        fclose($pipes[2]);
        $closedExitCode = proc_close($process);
        $reaped = true;
        $exitCode = $closedExitCode === -1 ? $observedExitCode : $closedExitCode;
        if (!is_int($exitCode) || $exitCode < 0) {
            throw new TestFailure('Interactive tracer must preserve the child exit code.');
        }
        return compact('exitCode', 'stdout', 'stderr');
    } finally {
        if ($afterDelayedBytes !== null && !$afterDelayedCalled) {
            $afterDelayedBytes();
        }
        foreach ($pipes as $pipe) {
            if (is_resource($pipe)) {
                fclose($pipe);
            }
        }
        if (!$reaped && is_resource($process)) {
            $status = proc_get_status($process);
            if ($status['running']) {
                proc_terminate($process);
            }
            proc_close($process);
        }
    }
}
function pciStartCommitProxy(string $token,bool $forwardCommit=false,?string $mutateTable=null):array{$root=dirname(__DIR__,2).'/.test-artifacts';$rootCreated=false;if(!file_exists($root)){$rootCreated=mkdir($root,0700);if(!$rootCreated)throw new TestFailure('artifact root create');}$stat=lstat($root);if($stat===false||is_link($root)||($stat['mode']&0170000)!==0040000||$stat['uid']!==posix_geteuid()||($stat['mode']&0022)!==0)throw new TestFailure('artifact root must be trusted');$dir=$root.'/pci-commit-'.$token;if(!mkdir($dir,0700))throw new TestFailure('commit proxy dir');$transcript=$dir.'/transcript';$pipes=[];$proxyEnv=['PMR_BACKEND_HOST'=>getenv('FMONITOR_TEST_DB_HOST')?:'127.0.0.1','PMR_BACKEND_PORT'=>getenv('FMONITOR_TEST_DB_PORT')?:'23306','PMR_TRANSCRIPT_PATH'=>$transcript,'PMR_FORWARD_COMMIT'=>$forwardCommit?'1':'0','PMR_MUTATE_TABLE'=>$mutateTable??'','PMR_MUTATE_USER'=>getenv('FMONITOR_TEST_DB_ADMIN_USER')?:'root','PMR_MUTATE_PASSWORD'=>getenv('FMONITOR_TEST_DB_ADMIN_PASSWORD')?:'fmonitor2_demo_local','PMR_MUTATE_DATABASE'=>getenv('PCI_DATABASE')?:''];$p=proc_open([PHP_BINARY,dirname(__DIR__).'/Support/mysql_wire_drop_commit_proxy.php'],[0=>['pipe','r'],1=>['pipe','w'],2=>['pipe','w']],$pipes,dirname(__DIR__,2),$proxyEnv);if(!is_resource($p)){rmdir($dir);if($rootCreated)rmdir($root);throw new TestFailure('commit proxy start');}fclose($pipes[0]);$port=trim((string)fgets($pipes[1]));return compact('p','pipes','port','transcript','dir','root','rootCreated','forwardCommit');}
function pciStopCommitProxy(array $proxy,bool $expectClean):void{try{if(is_resource($proxy['pipes'][1])){$out=stream_get_contents($proxy['pipes'][1]);fclose($proxy['pipes'][1]);}else $out='';if(is_resource($proxy['pipes'][2])){$err=stream_get_contents($proxy['pipes'][2]);fclose($proxy['pipes'][2]);}else $err='';if(is_resource($proxy['p'])){$status=proc_get_status($proxy['p']);if($status['running']&&!$expectClean)proc_terminate($proxy['p']);$exit=proc_close($proxy['p']);}else $exit=-1;if($expectClean){assertSameValue([0,'',''],[$exit,$out,$err],'commit proxy clean completion');$expected=$proxy['forwardCommit']?"COMMIT_FORWARDED_RESPONSE_DROPPED\n":"COMMIT_DROPPED\n";assertSameValue($expected,file_get_contents($proxy['transcript']),'commit proxy exact fault');}}finally{foreach([1,2] as $fd)if(isset($proxy['pipes'][$fd])&&is_resource($proxy['pipes'][$fd]))fclose($proxy['pipes'][$fd]);if(isset($proxy['p'])&&is_resource($proxy['p'])){if(proc_get_status($proxy['p'])['running'])proc_terminate($proxy['p']);proc_close($proxy['p']);}if(is_file($proxy['transcript']))unlink($proxy['transcript']);if(is_dir($proxy['dir']))rmdir($proxy['dir']);if($proxy['rootCreated']&&is_dir($proxy['root'])&&count(scandir($proxy['root']))===2)rmdir($proxy['root']);}}

$token=bin2hex(random_bytes(6));$database='t_pci001_'.$token;putenv('PCI_DATABASE='.$database);$databases=[$database];$users=[];$artifacts=[];$admin=pciDb();$admin->query("CREATE DATABASE `{$database}` DEFAULT CHARSET=utf8mb4");
try{
 $env=pciEnv($database);$base=$env;$base['FMONITOR_DB_HOST']='secret-host-'.$token;$base['FMONITOR_DB_NAME']='secret-db-'.$token;$base['FMONITOR_DB_USER']='secret-user-'.$token;$base['FMONITOR_DB_PASSWORD']='secret-password-'.$token;$base['FMONITOR_PROCESS_TABLE_PREFIX']='secret_process_'.$token.'_';$base['FMONITOR_LEGACY_TABLE_PREFIX']='secret_legacy_'.$token.'_';
 $invalidEnv=['missing host'=>array_diff_key($base,['FMONITOR_DB_HOST'=>1]),'missing port'=>array_diff_key($base,['FMONITOR_DB_PORT'=>1]),'missing db'=>array_diff_key($base,['FMONITOR_DB_NAME'=>1]),'missing user'=>array_diff_key($base,['FMONITOR_DB_USER'=>1]),'missing password'=>array_diff_key($base,['FMONITOR_DB_PASSWORD'=>1]),'missing process prefix'=>array_diff_key($base,['FMONITOR_PROCESS_TABLE_PREFIX'=>1]),'missing legacy prefix'=>array_diff_key($base,['FMONITOR_LEGACY_TABLE_PREFIX'=>1]),'three missing emptiable values'=>array_diff_key($base,['FMONITOR_DB_PASSWORD'=>1,'FMONITOR_PROCESS_TABLE_PREFIX'=>1,'FMONITOR_LEGACY_TABLE_PREFIX'=>1]),'empty host'=>array_replace($base,['FMONITOR_DB_HOST'=>'']),'empty port'=>array_replace($base,['FMONITOR_DB_PORT'=>'']),'empty db'=>array_replace($base,['FMONITOR_DB_NAME'=>'']),'empty user'=>array_replace($base,['FMONITOR_DB_USER'=>'']),'bad port'=>array_replace($base,['FMONITOR_DB_PORT'=>'01']),'high port'=>array_replace($base,['FMONITOR_DB_PORT'=>'65536']),'bad process prefix'=>array_replace($base,['FMONITOR_PROCESS_TABLE_PREFIX'=>'bad-prefix']),'long legacy prefix'=>array_replace($base,['FMONITOR_LEGACY_TABLE_PREFIX'=>str_repeat('a',33)])];
 foreach($invalidEnv as $label=>$case) pciResult(['exitCode'=>64,'stdout'=>"{\"ok\":false,\"reason\":\"CONFIGURATION_INVALID\"}\n",'stderr'=>''],pciRun($case,['--object-id=4512']),$label,array_values($base));
 $invalidArgv=['no IDs'=>[],'zero'=>['--object-id=0'],'negative'=>['--object-id=-1'],'positive sign'=>['--object-id=+1'],'leading whitespace'=>['--object-id= 1'],'trailing whitespace'=>['--object-id=1 '],'leading zero'=>['--object-id=04512'],'overflow'=>['--object-id=9223372036854775808'],'duplicate'=>['--object-id=4512','--object-id=4512'],'unknown'=>['--all'],'positional'=>['4512'],'101 IDs'=>array_map(fn(int $id):string=>'--object-id='.$id,range(1,101))];
 foreach($invalidArgv as $label=>$argv)pciResult(['exitCode'=>64,'stdout'=>"{\"ok\":false,\"reason\":\"CONFIGURATION_INVALID\"}\n",'stderr'=>''],pciRun($base,$argv),$label,array_values($base));
 $unavailable=array_replace($env,['FMONITOR_DB_HOST'=>'127.0.0.1','FMONITOR_DB_PORT'=>'1','FMONITOR_DB_PASSWORD'=>'unavailable-secret-'.$token]);pciResult(['exitCode'=>69,'stdout'=>"{\"ok\":false,\"reason\":\"DATABASE_UNAVAILABLE\"}\n",'stderr'=>''],pciRun($unavailable,['--object-id=4512']),'database unavailable',array_values($unavailable));

 pciMigrate($env);$c=pciDb($database);
 $c->query("CREATE TABLE legacy_fm_maintable (id BIGINT UNSIGNED NOT NULL PRIMARY KEY,ordadr_address VARCHAR(500),entrance VARCHAR(80),regnumber VARCHAR(120),workdatestart VARCHAR(40),workdateendadjusted VARCHAR(40),plan_finish_date VARCHAR(40),workdatefinish VARCHAR(40),ptoactdate VARCHAR(40),installator1 VARCHAR(80),installator2 VARCHAR(80),responsstroicontrol VARCHAR(80)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
 $c->query("INSERT INTO legacy_fm_maintable VALUES (4512,'  Москва, ул. Примерная, д. 10  ',' 2 ',' 77-000123 ','2026-10-05','2026-12-20','2026-12-25',NULL,NULL,'legacy-inst-4512','legacy-inst2-4512','legacy-engineer-4512'),(4513,'Москва, ул. Вторая, д. 7','1','77-000124','2026-10-01','2026-11-30','2026-12-01','0000-00-00','0','legacy-inst-4513',NULL,'legacy-engineer-4513'),(4514,'Москва, ул. Третья, д. 8','3','77-000125','2026-10-02',NULL,'2026-12-10',NULL,NULL,NULL,NULL,NULL),(4601,'Москва, ул. Плохая, д. 1','   ','77-000201','2026-09-30','2026-11-30',NULL,'2026-12-01','2026-08-01','raw-inst-secret',NULL,NULL),(4700,'Raw broken date address','4','77-000300','not-a-calendar-date','2026-12-20',NULL,NULL,NULL,NULL,NULL,NULL)");
 $stdinExpected=['exitCode'=>0,'stdout'=>"{\"ok\":true,\"selected\":[4514],\"imported\":[4514],\"alreadyPresent\":[]}\n",'stderr'=>''];
 $interactiveEnv=pciEnv($database,'i_','legacy_');pciMigrate($interactiveEnv);pciResult($stdinExpected,pciRunBeforeStdinEof($interactiveEnv,['--object-id=4514']),'valid invocation with empty open stdin');
 $immediateBytes="--object-id=4601\nDB_PASSWORD=stdin-secret-{$token}\n";$immediateEnv=pciEnv($database,'si_','legacy_');pciMigrate($immediateEnv);pciResult($stdinExpected,pciRunBeforeStdinEof($immediateEnv,['--object-id=4514'],5,$immediateBytes),'immediate stdin bytes are wholly ignored',[$immediateBytes,'4601','stdin-secret-'.$token]);
 $delayedBytes="delayed-id=4601 delayed-secret-{$token}\n";$delayedEnv=pciEnv($database,'sd_','legacy_');pciMigrate($delayedEnv);$c->query('LOCK TABLES sd_fm2_installation_cases WRITE');$unlockPending=true;$unlock=static function()use($c,&$unlockPending):void{if($unlockPending){$c->query('UNLOCK TABLES');$unlockPending=false;}};try{pciResult($stdinExpected,pciRunBeforeStdinEof($delayedEnv,['--object-id=4514'],5,'',$delayedBytes,$unlock),'delayed stdin bytes are wholly ignored',[$delayedBytes,'4601','delayed-secret-'.$token]);}finally{$unlock();}
 $stdinShapes=[];foreach(['i_','si_','sd_'] as $stdinPrefix){$rows=pciRows($c,"SELECT legacy_installation_object_id,process_state,actual_start_date,opened_at,opened_by_user_id,lock_version FROM {$stdinPrefix}fm2_installation_cases ORDER BY legacy_installation_object_id");$stdinShapes[]=$rows;}assertSameValue($stdinShapes[0],$stdinShapes[1],'Immediate bytes must not change DB effects.');assertSameValue($stdinShapes[0],$stdinShapes[2],'Delayed bytes must not change DB effects.');
 $legacyBefore=pciRows($c,'SELECT * FROM legacy_fm_maintable ORDER BY id');$before=time();$success=pciRun($env,['--object-id=4512','--object-id=4513']);$after=time();
 pciResult(['exitCode'=>0,'stdout'=>"{\"ok\":true,\"selected\":[4512,4513],\"imported\":[4512,4513],\"alreadyPresent\":[]}\n",'stderr'=>''],$success,'atomic success',[$database,'legacy_','pr_','legacy-inst-4512','legacy-engineer-4513']);
 $cases=pciRows($c,'SELECT legacy_installation_object_id,process_state,actual_start_date,opened_at,opened_by_user_id,created_at,updated_at,lock_version FROM pr_fm2_installation_cases ORDER BY legacy_installation_object_id');assertSameValue(2,count($cases),'two cases');$timestamp=$cases[0]['created_at'];foreach($cases as $index=>$case){assertSameValue((string)(4512+$index),(string)$case['legacy_installation_object_id'],'selected order rows');assertSameValue('needs_assignment_order',$case['process_state'],'empty state');assertSameValue([null,null,null],[$case['actual_start_date'],$case['opened_at'],$case['opened_by_user_id']],'opening nulls');assertSameValue('1',(string)$case['lock_version'],'revision');assertSameValue($timestamp,$case['created_at'],'single operation timestamp');assertSameValue($timestamp,$case['updated_at'],'timestamps equal');}assertSameValue(1,preg_match('/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\+00:00$/D',$timestamp),'RFC3339 UTC seconds');$instant=strtotime($timestamp);assertSameValue(true,$instant!==false&&$instant>=$before&&$instant<=$after,'timestamp within external interval');assertSameValue($legacyBefore,pciRows($c,'SELECT * FROM legacy_fm_maintable ORDER BY id'),'legacy byte preservation');foreach(array_diff(array_keys(pciProcessState($c,'pr_')),['fm2_installation_cases']) as $table)assertSameValue([],pciRows($c,"SELECT * FROM pr_{$table}"),$table.' remains empty');
 $stateBeforeRepeat=pciProcessState($c,'pr_');$autoIncrementBefore=pciRows($c,"SELECT AUTO_INCREMENT FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='pr_fm2_installation_cases'");pciResult(['exitCode'=>0,'stdout'=>"{\"ok\":true,\"selected\":[4512,4513],\"imported\":[],\"alreadyPresent\":[4512,4513]}\n",'stderr'=>''],pciRun($env,['--object-id=4512','--object-id=4513']),'safe repeat');assertSameValue($stateBeforeRepeat,pciProcessState($c,'pr_'),'repeat preserves all process rows');assertSameValue($autoIncrementBefore,pciRows($c,"SELECT AUTO_INCREMENT FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='pr_fm2_installation_cases'"),'repeat preserves auto-increment state');
 $c->query("UPDATE pr_fm2_installation_cases SET process_state='working',actual_start_date='2026-10-05',opened_at='2026-10-05T09:00:00+03:00',opened_by_user_id=18,lock_version=7 WHERE legacy_installation_object_id=4512");$c->query("UPDATE legacy_fm_maintable SET entrance='',workdatestart='broken-date',ptoactdate='2026-08-01' WHERE id=4512");$progressed=pciRows($c,'SELECT * FROM pr_fm2_installation_cases WHERE legacy_installation_object_id=4512');pciResult(['exitCode'=>0,'stdout'=>"{\"ok\":true,\"selected\":[4512],\"imported\":[],\"alreadyPresent\":[4512]}\n",'stderr'=>''],pciRun($env,['--object-id=4512']),'progressed case does not reread legacy');assertSameValue($progressed,pciRows($c,'SELECT * FROM pr_fm2_installation_cases WHERE legacy_installation_object_id=4512'),'progressed unchanged');
 pciResult(['exitCode'=>0,'stdout'=>"{\"ok\":true,\"selected\":[4512,4514],\"imported\":[4514],\"alreadyPresent\":[4512]}\n",'stderr'=>''],pciRun($env,['--object-id=4512','--object-id=4514']),'mixed progressed existing plus new');assertSameValue($progressed,pciRows($c,'SELECT * FROM pr_fm2_installation_cases WHERE legacy_installation_object_id=4512'),'mixed batch preserves progressed existing case');$mixedNew=pciRows($c,'SELECT process_state,actual_start_date,opened_at,opened_by_user_id,lock_version FROM pr_fm2_installation_cases WHERE legacy_installation_object_id=4514');assertSameValue([['process_state'=>'needs_assignment_order','actual_start_date'=>null,'opened_at'=>null,'opened_by_user_id'=>null,'lock_version'=>'1']],$mixedNew,'mixed batch inserts only exact empty new case');

 $rejectEnv=pciEnv($database,'rj_','legacy_');pciMigrate($rejectEnv);$rejectBefore=pciProcessState($c,'rj_');$rejected='{"ok":false,"reason":"PILOT_CASES_NOT_ELIGIBLE","rejected":[{"installationObjectId":4600,"reasonCodes":["LEGACY_OBJECT_NOT_FOUND"]},{"installationObjectId":4601,"reasonCodes":["LEGACY_OBJECT_REQUIRED_DATA_MISSING","ORDER_HAS_PTO_ACT","LEGACY_INSTALLATION_ALREADY_COMPLETED"]}]}'."\n";pciResult(['exitCode'=>2,'stdout'=>$rejected,'stderr'=>''],pciRun($rejectEnv,['--object-id=4513','--object-id=4600','--object-id=4601']),'all-or-nothing rejection',['raw-inst-secret','Москва, ул. Плохая, д. 1']);assertSameValue($rejectBefore,pciProcessState($c,'rj_'),'rejection mutates no process table');

 $schemaMissing=pciEnv($database,'mi_','legacy_');pciResult(['exitCode'=>78,'stdout'=>"{\"ok\":false,\"reason\":\"SCHEMA_UNAVAILABLE\"}\n",'stderr'=>''],pciRun($schemaMissing,['--object-id=4513']),'missing process schema');$c->query('CREATE TABLE ic_fm2_installation_cases (unexpected INT NOT NULL) ENGINE=InnoDB');$schemaBad=pciEnv($database,'ic_','legacy_');pciResult(['exitCode'=>78,'stdout'=>"{\"ok\":false,\"reason\":\"SCHEMA_UNAVAILABLE\"}\n",'stderr'=>''],pciRun($schemaBad,['--object-id=4513']),'incompatible process schema');$missingLegacy=pciEnv($database,'pr_','absent_');pciResult(['exitCode'=>78,'stdout'=>"{\"ok\":false,\"reason\":\"SCHEMA_UNAVAILABLE\"}\n",'stderr'=>''],pciRun($missingLegacy,['--object-id=4513']),'missing legacy schema');
 $c->query('CREATE TABLE badlegacy_fm_maintable (id BIGINT UNSIGNED PRIMARY KEY,ordadr_address VARCHAR(500),entrance VARCHAR(80),regnumber VARCHAR(120),workdatestart VARCHAR(40),workdateendadjusted VARCHAR(40),plan_finish_date VARCHAR(40),workdatefinish VARCHAR(40)) ENGINE=InnoDB');$badLegacy=pciEnv($database,'pr_','badlegacy_');pciResult(['exitCode'=>78,'stdout'=>"{\"ok\":false,\"reason\":\"SCHEMA_UNAVAILABLE\"}\n",'stderr'=>''],pciRun($badLegacy,['--object-id=4513']),'missing required legacy column');$dateEnv=pciEnv($database,'dt_','legacy_');pciMigrate($dateEnv);pciResult(['exitCode'=>78,'stdout'=>"{\"ok\":false,\"reason\":\"SCHEMA_UNAVAILABLE\"}\n",'stderr'=>''],pciRun($dateEnv,['--object-id=4700']),'unrecognized legacy date',['Raw broken date address','not-a-calendar-date']);assertSameValue([],pciRows($c,'SELECT * FROM dt_fm2_installation_cases'),'bad date creates no case');

 $raceEnv=pciEnv($database,'ra_','legacy_');pciMigrate($raceEnv);$raceResults=pciRace($raceEnv,['--object-id=4514']);usort($raceResults,static function(array $left,array $right):int{$leftImported=json_decode(trim($left['stdout']),true)['imported']??[];$rightImported=json_decode(trim($right['stdout']),true)['imported']??[];return count($rightImported)<=>count($leftImported);});pciResult(['exitCode'=>0,'stdout'=>"{\"ok\":true,\"selected\":[4514],\"imported\":[4514],\"alreadyPresent\":[]}\n",'stderr'=>''],$raceResults[0],'race winner exact output');pciResult(['exitCode'=>0,'stdout'=>"{\"ok\":true,\"selected\":[4514],\"imported\":[],\"alreadyPresent\":[4514]}\n",'stderr'=>''],$raceResults[1],'race observer exact output');assertSameValue(1,count(pciRows($c,'SELECT * FROM ra_fm2_installation_cases WHERE legacy_installation_object_id=4514')),'one race row');

 $leastEnv=pciEnv($database,'le_','legacy_');pciMigrate($leastEnv);$leastUser='pci_le_'.$token;$users[]=$leastUser;$leastPassword='least-secret-'.$token;$admin->query("CREATE USER `{$leastUser}`@'%' IDENTIFIED BY '{$leastPassword}'");$admin->query("GRANT SELECT ON `{$database}`.`legacy_fm_maintable` TO `{$leastUser}`@'%'");$admin->query("GRANT SELECT,INSERT ON `{$database}`.`le_fm2_installation_cases` TO `{$leastUser}`@'%'");$leastEnv['FMONITOR_DB_USER']=$leastUser;$leastEnv['FMONITOR_DB_PASSWORD']=$leastPassword;pciResult(['exitCode'=>0,'stdout'=>"{\"ok\":true,\"selected\":[4513],\"imported\":[4513],\"alreadyPresent\":[]}\n",'stderr'=>''],pciRun($leastEnv,['--object-id=4513']),'least privilege success',[$leastUser,$leastPassword]);$grants=pciRows($admin,"SHOW GRANTS FOR `{$leastUser}`@'%'");assertSameValue(false,str_contains(strtolower(implode(' ',array_column($grants,'Grants for '.$leastUser.'@%'))),'update'),'least privilege has no UPDATE');assertSameValue(false,str_contains(strtolower(json_encode($grants,JSON_THROW_ON_ERROR)),'delete'),'least privilege has no DELETE');assertSameValue(false,str_contains(strtolower(json_encode($grants,JSON_THROW_ON_ERROR)),"`{$database}`.*"),'least privilege has no database-wide grant');
 $failEnv=pciEnv($database,'fa_','legacy_');pciMigrate($failEnv);$readonly='pci_read_'.$token;$users[]=$readonly;$readonlyPassword='readonly-secret-'.$token;$admin->query("CREATE USER `{$readonly}`@'%' IDENTIFIED BY '{$readonlyPassword}'");$admin->query("GRANT SELECT ON `{$database}`.* TO `{$readonly}`@'%'");$failEnv['FMONITOR_DB_USER']=$readonly;$failEnv['FMONITOR_DB_PASSWORD']=$readonlyPassword;pciResult(['exitCode'=>70,'stdout'=>"{\"ok\":false,\"reason\":\"IMPORT_FAILED\"}\n",'stderr'=>''],pciRun($failEnv,['--object-id=4514']),'confirmed rollback',[$readonly,$readonlyPassword]);assertSameValue([],pciRows($c,'SELECT * FROM fa_fm2_installation_cases'),'rollback leaves no row');

 $emptyDatabase='t_pci_empty_'.$token;$databases[]=$emptyDatabase;$emptyUser='pci_empty_'.$token;$users[]=$emptyUser;$admin->query("CREATE DATABASE `{$emptyDatabase}` DEFAULT CHARSET=utf8mb4");$admin->query("CREATE USER `{$emptyUser}`@'%' IDENTIFIED BY ''");$admin->query("GRANT ALL PRIVILEGES ON `{$emptyDatabase}`.* TO `{$emptyUser}`@'%'");$emptyEnv=pciEnv($emptyDatabase,'','');$emptyEnv['FMONITOR_DB_USER']=$emptyUser;$emptyEnv['FMONITOR_DB_PASSWORD']='';pciMigrate($emptyEnv);$emptyConnection=pciDb($emptyDatabase);$emptyConnection->query("CREATE TABLE fm_maintable (id BIGINT UNSIGNED PRIMARY KEY,ordadr_address VARCHAR(500),entrance VARCHAR(80),regnumber VARCHAR(120),workdatestart VARCHAR(40),workdateendadjusted VARCHAR(40),plan_finish_date VARCHAR(40),workdatefinish VARCHAR(40),ptoactdate VARCHAR(40)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");$emptyConnection->query("INSERT INTO fm_maintable VALUES(9001,'Empty prefix address','1','77-009001','2026-10-01','2026-11-01',NULL,NULL,NULL)");pciResult(['exitCode'=>0,'stdout'=>"{\"ok\":true,\"selected\":[9001],\"imported\":[9001],\"alreadyPresent\":[]}\n",'stderr'=>''],pciRun($emptyEnv,['--object-id=9001']),'explicit empty password and both prefixes',[$emptyUser,'Empty prefix address']);$emptyConnection->close();

 $unknownEnv=pciEnv($database,'un_','legacy_');pciMigrate($unknownEnv);$proxy=pciStartCommitProxy($token);try{$proxied=$unknownEnv;$proxied['FMONITOR_DB_HOST']='127.0.0.1';$proxied['FMONITOR_DB_PORT']=$proxy['port'];pciResult(['exitCode'=>75,'stdout'=>"{\"ok\":false,\"reason\":\"IMPORT_OUTCOME_UNKNOWN\"}\n",'stderr'=>''],pciRun($proxied,['--object-id=4514']),'dropped commit reconciles absent row',[$proxy['port'],$database,'un_']);pciStopCommitProxy($proxy,true);$proxy=null;assertSameValue([],pciRows($c,'SELECT * FROM un_fm2_installation_cases'),'unknown commit cannot claim/import absent row');}finally{if($proxy!==null)pciStopCommitProxy($proxy,false);}
 $reconciledEnv=pciEnv($database,'rc_','legacy_');pciMigrate($reconciledEnv);$proxy=pciStartCommitProxy($token.'-forward',true);try{$proxied=$reconciledEnv;$proxied['FMONITOR_DB_HOST']='127.0.0.1';$proxied['FMONITOR_DB_PORT']=$proxy['port'];$reconcileBefore=time();pciResult(['exitCode'=>0,'stdout'=>"{\"ok\":true,\"selected\":[4514],\"imported\":[4514],\"alreadyPresent\":[]}\n",'stderr'=>''],pciRun($proxied,['--object-id=4514']),'lost commit response reconciles exact committed row',[$proxy['port'],$database,'rc_']);$reconcileAfter=time();pciStopCommitProxy($proxy,true);$proxy=null;$reconciled=pciRows($c,'SELECT process_state,actual_start_date,opened_at,opened_by_user_id,created_at,updated_at,lock_version FROM rc_fm2_installation_cases WHERE legacy_installation_object_id=4514');assertSameValue('needs_assignment_order',$reconciled[0]['process_state'],'reconciled empty state');assertSameValue([null,null,null],[$reconciled[0]['actual_start_date'],$reconciled[0]['opened_at'],$reconciled[0]['opened_by_user_id']],'reconciled opening nulls');assertSameValue('1',(string)$reconciled[0]['lock_version'],'reconciled revision');assertSameValue($reconciled[0]['created_at'],$reconciled[0]['updated_at'],'reconciled timestamps equal current operation timestamp');assertSameValue(1,preg_match('/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\+00:00$/D',$reconciled[0]['created_at']),'reconciled timestamp RFC3339 UTC');$reconciledInstant=strtotime($reconciled[0]['created_at']);assertSameValue(true,$reconciledInstant!==false&&$reconciledInstant>=$reconcileBefore&&$reconciledInstant<=$reconcileAfter,'reconciled timestamp belongs to current operation');}finally{if($proxy!==null)pciStopCommitProxy($proxy,false);}
 $staleEnv=pciEnv($database,'st_','legacy_');pciMigrate($staleEnv);$proxy=pciStartCommitProxy($token.'-stale',true,'st_fm2_installation_cases');try{$proxied=$staleEnv;$proxied['FMONITOR_DB_HOST']='127.0.0.1';$proxied['FMONITOR_DB_PORT']=$proxy['port'];pciResult(['exitCode'=>75,'stdout'=>"{\"ok\":false,\"reason\":\"IMPORT_OUTCOME_UNKNOWN\"}\n",'stderr'=>''],pciRun($proxied,['--object-id=4514']),'wrong-operation timestamp cannot reconcile as success',[$proxy['port'],$database,'st_','2000-01-01']);pciStopCommitProxy($proxy,true);$proxy=null;$stale=pciRows($c,'SELECT process_state,created_at,updated_at,lock_version FROM st_fm2_installation_cases WHERE legacy_installation_object_id=4514');assertSameValue([['process_state'=>'needs_assignment_order','created_at'=>'2000-01-01T00:00:00+00:00','updated_at'=>'2000-01-01T00:00:00+00:00','lock_version'=>'1']],$stale,'stale fixture proves shape alone is insufficient');}finally{if($proxy!==null)pciStopCommitProxy($proxy,false);}

 echo "PASS: PILOT-CASE-IMPORT-001 CLI contract\n";$c->close();
}finally{foreach($users as $user)$admin->query("DROP USER IF EXISTS `{$user}`@'%'");foreach($databases as $dropDatabase)$admin->query("DROP DATABASE IF EXISTS `{$dropDatabase}`");foreach($artifacts as $artifact)if(is_file($artifact))unlink($artifact);$admin->close();putenv('PCI_DATABASE');}
