<?php
declare(strict_types=1);

require dirname(__DIR__) . '/bootstrap.php';
spl_autoload_register(static function (string $class): void {
    foreach (['FMonitor\\IdentityAccess\\' => dirname(__DIR__, 2) . '/app/IdentityAccess/'] as $prefix => $base) {
        if (!str_starts_with($class, $prefix)) continue;
        $file = $base . str_replace('\\', '/', substr($class, strlen($prefix))) . '.php';
        if (is_file($file)) require_once $file;
    }
});
require dirname(__DIR__) . '/Support/PilotSessionStoragePublicApiFixture.php';

use FMonitor2\Tests\Support\FixedPilotSessionClock;
use FMonitor2\Tests\Support\LengthQueuedPilotSessionEntropy;
use FMonitor2\Tests\Support\NativePilotSessionFilesystem;
use FMonitor2\Tests\Support\RecordingPilotSessionObserver;

function puatPort(): int { $s=stream_socket_server('tcp://127.0.0.1:0',$e,$m);if(!is_resource($s))throw new RuntimeException("SETUP_FAILURE: $m");$n=(string)stream_socket_get_name($s,false);fclose($s);return(int)substr($n,strrpos($n,':')+1); }
function puatStart(string $router,array $environment): array { $port=puatPort();$process=proc_open([PHP_BINARY,'-S',"127.0.0.1:$port",$router],[1=>['pipe','w'],2=>['pipe','w']],$pipes,dirname(__DIR__,2),$environment);if(!is_resource($process))throw new RuntimeException('SETUP_FAILURE: server');foreach($pipes as$pipe)stream_set_blocking($pipe,false);$deadline=microtime(true)+3;do{usleep(20000);$socket=@stream_socket_client("tcp://127.0.0.1:$port",$e,$m,.1);if(is_resource($socket)){fclose($socket);return[$process,$pipes,$port];}}while(microtime(true)<$deadline);throw new RuntimeException('SETUP_FAILURE: readiness'); }
function puatStop(?array &$server): void { if($server===null)return;[$process,$pipes]=$server;if(proc_get_status($process)['running'])proc_terminate($process,15);$deadline=microtime(true)+.3;while(proc_get_status($process)['running']&&microtime(true)<$deadline)usleep(10000);if(proc_get_status($process)['running'])proc_terminate($process,9);foreach($pipes as$pipe){stream_get_contents($pipe);fclose($pipe);}proc_close($process);$server=null; }
function puatGet(int $port,string $cookie): array { $socket=stream_socket_client("tcp://127.0.0.1:$port",$e,$m,2);if(!is_resource($socket))throw new RuntimeException("SETUP_FAILURE: $m");fwrite($socket,"GET /pilot/admin/users HTTP/1.1\r\nHost: 127.0.0.1:$port\r\nCookie: $cookie\r\nConnection: close\r\nContent-Length: 0\r\n\r\n");$raw=(string)stream_get_contents($socket);fclose($socket);[$head,$body]=array_pad(explode("\r\n\r\n",$raw,2),2,'');preg_match('#^HTTP/1\.1 ([0-9]{3})#',$head,$match);$headers=[];foreach(array_slice(explode("\r\n",$head),1)as$line){$at=strpos($line,':');if($at!==false)$headers[strtolower(substr($line,0,$at))][]=ltrim(substr($line,$at+1));}return[(int)($match[1]??0),$headers,$body]; }
function puatOwner(string $root,array $entropy=[]): FMonitor\IdentityAccess\PilotSessionStorage { return(new FMonitor\IdentityAccess\PilotSessionStorageFactory())->create(new FMonitor\IdentityAccess\PilotSessionStorageConfig($root,'http_v7'),new NativePilotSessionFilesystem(),new FixedPilotSessionClock(1_788_200_000,1000),new LengthQueuedPilotSessionEntropy($entropy),new RecordingPilotSessionObserver()); }

$db=new mysqli(getenv('FMONITOR_TEST_DB_HOST')?:'127.0.0.1',getenv('FMONITOR_TEST_DB_ADMIN_USER')?:'root',getenv('FMONITOR_TEST_DB_ADMIN_PASSWORD')?:'fmonitor2_test_root_local',getenv('FMONITOR_TEST_DB_NAME')?:'fmonitor2_test',(int)(getenv('FMONITOR_TEST_DB_PORT')?:23306));
$db->set_charset('utf8mb4');$token=bin2hex(random_bytes(8));$email="token.actor.$token@shlz.ru";$root=sys_get_temp_dir().'/fmonitor2-session-storage-tests/task-'.$token;$actor=0;$role=0;$server=null;
$remove=function(string$path)use(&$remove):void{if(is_file($path)||is_link($path)){unlink($path);return;}if(!is_dir($path))return;foreach(scandir($path)?:[]as$entry)if($entry!=='.'&&$entry!=='..')$remove($path.'/'.$entry);rmdir($path);};
try{
    mkdir($root,0700,true);$now='2026-09-03T12:00:00+03:00';
    $q=$db->prepare("INSERT INTO fm2_pilot_users(full_name,email,status,activation_state,source_updated_at)VALUES('Token Actor',?,1,'active',?)");$q->bind_param('ss',$email,$now);$q->execute();$actor=(int)$db->insert_id;
    $hash=password_hash('unused-fixture-password',PASSWORD_BCRYPT);$q=$db->prepare('INSERT INTO fm2_pilot_auth_credentials(user_id,email_normalized,password_hash,password_set_at,updated_at)VALUES(?,?,?,?,?)');$q->bind_param('issss',$actor,$email,$hash,$now,$now);$q->execute();
    $code='token-role-'.$token;$q=$db->prepare("INSERT INTO fm2_pilot_roles(code,name,description,status,source_updated_at)VALUES(?,'Token role','test',1,?)");$q->bind_param('ss',$code,$now);$q->execute();$role=(int)$db->insert_id;$db->query("INSERT INTO fm2_pilot_role_permissions(role_id,permission)VALUES($role,'access.administer')");$db->query("INSERT INTO fm2_pilot_user_roles(user_id,role_id,origin,assigned_at)VALUES($actor,$role,'test','$now')");
    $csrf=str_repeat('d',64);$original=serialize(['auth_user_id'=>$actor,'auth_email'=>$email,'auth_csrf'=>$csrf]);$owner=puatOwner($root,[32=>[str_repeat("\x41",32)],16=>[str_repeat("\x42",16)],12=>[str_repeat("\x43",12)]]);$started=$owner->start(null);$id=(string)$started->currentSessionId();assertSameValue('OK',$owner->writeCommit($id,$original)->status()->name,'canonical no-flash state committed');$owner->close();
    $environment=array_replace($_ENV,['FMONITOR_DB_HOST'=>getenv('FMONITOR_TEST_DB_HOST')?:'127.0.0.1','FMONITOR_DB_PORT'=>getenv('FMONITOR_TEST_DB_PORT')?:'23306','FMONITOR_DB_NAME'=>getenv('FMONITOR_TEST_DB_NAME')?:'fmonitor2_test','FMONITOR_DB_USER'=>getenv('FMONITOR_TEST_DB_ADMIN_USER')?:'root','FMONITOR_DB_PASSWORD'=>getenv('FMONITOR_TEST_DB_ADMIN_PASSWORD')?:'fmonitor2_test_root_local','FMONITOR_SESSION_STATE_ROOT'=>$root,'FMONITOR_SESSION_INSTANCE'=>'http_v7','FMONITOR_TRUSTED_REQUEST_SCHEME'=>'http']);
    $server=puatStart(dirname(__DIR__).'/Support/pilot_session_storage_user_access_router.php',$environment);[$status,,$body]=puatGet($server[2],"fm2auth_{$server[2]}=$id");assertSameValue(200,$status,'no-flash UserAccess GET succeeds');assertSameValue(1,preg_match('/name="csrfToken" value="([0-9a-f]{32})"/D',$body,$match),'one action token rendered');
    $probe=puatOwner($root,[12=>[str_repeat("\x44",12)]]);$stored=$probe->start($id);$state=unserialize((string)$stored->sessionPayload(),['allowed_classes'=>false]);assertSameValue(true,isset($state['tokens'][$match[1]]),'INTENTIONAL_RED: rendered action token committed by owner');$probe->close();puatStop($server);
    $restore=puatOwner($root,[16=>[str_repeat("\x45",16)],12=>[str_repeat("\x46",12)]]);assertSameValue('OK',$restore->writeCommit($id,$original)->status()->name,'no-flash state restored for write fault');$restore->close();$server=puatStart(dirname(__DIR__).'/Support/pilot_session_storage_user_access_fault_router.php',$environment);[$faultStatus,$faultHeaders,$faultBody]=puatGet($server[2],"fm2auth_{$server[2]}=$id");assertSameValue(503,$faultStatus,'token commit fault maps unavailable');assertSameValue("Service unavailable.\n",$faultBody,'buffered token page discarded');assertSameValue([],array_intersect(array_keys($faultHeaders),['location','set-cookie']),'no success headers on token fault');$trace=(string)file_get_contents($root.'/user-access-fault-trace.jsonl');assertSameValue(1,preg_match_all('/"operation":"rename","artifact":"committed","ordinal":1,"outcome":"native_false"/',$trace),'exact token publication fault reached once');assertSameValue($original,file_get_contents($root.'/sessions/http_v7/s-'.$id.'.session'),'token fault preserves prior state');
    echo "PASS: PILOT-SESSION-STORAGE-001 v10 UserAccess action tokens\n";
}finally{puatStop($server);$q=$db->prepare('DELETE FROM fm2_pilot_users WHERE email=?');$q->bind_param('s',$email);$q->execute();if($role)$db->query("DELETE FROM fm2_pilot_roles WHERE role_id=$role");$db->close();$remove($root);$parent=dirname($root);if(is_dir($parent)&&count(scandir($parent)?:[])===2)rmdir($parent);}
