<?php
declare(strict_types=1);
require dirname(__DIR__).'/bootstrap.php';
use FMonitor2\Tests\Support\{FixedPilotSessionClock,LengthQueuedPilotSessionEntropy,NativePilotSessionFilesystem,RecordingPilotSessionObserver};
spl_autoload_register(static function(string$class):void{$p='FMonitor\\IdentityAccess\\';if(str_starts_with($class,$p)){$f=dirname(__DIR__,2).'/app/IdentityAccess/'.substr($class,strlen($p)).'.php';if(is_file($f))require$f;}});assertSameValue(true,class_exists(FMonitor\IdentityAccess\PilotSessionStorageFactory::class),'INTENTIONAL_RED: v7 collision owner exists');require dirname(__DIR__).'/Support/PilotSessionStoragePublicApiFixture.php';
$parent=sys_get_temp_dir().'/fmonitor2-session-storage-tests';if(!is_dir($parent)&&!mkdir($parent,0700))throw new RuntimeException('SETUP_FAILURE: parent');$roots=[];$remove=function(string$p)use(&$remove):void{if(is_link($p)||is_file($p)){unlink($p);return;}if(!is_dir($p))return;foreach(scandir($p)?:[]as$e)if($e!=='.'&&$e!=='..')$remove($p.'/'.$e);rmdir($p);};$mk=static function(string$r):string{mkdir("$r/sessions/collision_v7",0700,true);chmod($r,0700);chmod("$r/sessions",0700);return"$r/sessions/collision_v7";};$file=static function(string$p,string$b):void{file_put_contents($p,$b);chmod($p,0600);};$owner=static function(string$r,array$q){return(new FMonitor\IdentityAccess\PilotSessionStorageFactory())->create(new FMonitor\IdentityAccess\PilotSessionStorageConfig($r,'collision_v7'),new NativePilotSessionFilesystem(),new FixedPilotSessionClock(1_788_200_000,1000),new LengthQueuedPilotSessionEntropy($q),new RecordingPilotSessionObserver());};
try{
 // Eight generated-ID collisions: all independently seeded files survive.
 $r=$parent.'/task-'.bin2hex(random_bytes(8));$roots[]=$r;$d=$mk($r);$ids=[];$q32=[];$before=[];for($i=1;$i<=8;$i++){$bytes=str_repeat(chr($i),32);$id=bin2hex($bytes);$ids[]=$id;$q32[]=$bytes;$p="$d/s-$id.session";$file($p,"foreign-$i");$before[$p]=hash_file('sha256',$p);}$o=$owner($r,[32=>$q32,12=>[str_repeat('c',12)]]);$s=$o->start(null);$x=$o->writeCommit((string)$s->currentSessionId(),'must-not-publish');assertSameValue('ID_COLLISION',$x->category()?->name,'write exhausts exactly eight candidates');foreach($before as$p=>$h)assertSameValue($h,hash_file('sha256',$p),'candidate collision material preserved');assertSameValue(8,count(glob("$d/s-*.session")?:[]),'no ninth candidate published');$o->close();
 // Regeneration candidate collision preserves the old valid ID.
 $r=$parent.'/task-'.bin2hex(random_bytes(8));$roots[]=$r;$d=$mk($r);$old=str_repeat('O',16);$file("$d/s-$old.session",'old-valid');$q32=[];for($i=11;$i<=18;$i++){$b=str_repeat(chr($i),32);$q32[]=$b;$file("$d/s-".bin2hex($b).'.session',"candidate-$i");}$o=$owner($r,[32=>$q32,12=>[str_repeat('d',12)]]);$x=$o->regenerate($old,'new');assertSameValue('ID_COLLISION',$x->category()?->name,'regenerate exhausts eight candidate IDs');assertSameValue('old-valid',file_get_contents("$d/s-$old.session"),'candidate collisions preserve old');$o->close();
 // Eight revokedstone collisions occur only after a collision-free candidate/stage.
 $r=$parent.'/task-'.bin2hex(random_bytes(8));$roots[]=$r;$d=$mk($r);$old=str_repeat('T',16);$file("$d/s-$old.session",'old-before-tombstones');$candidate=str_repeat("\x71",32);$stage=str_repeat("\x72",16);$tokens=[];for($i=1;$i<=8;$i++){$t=str_repeat(chr(120+$i),16);$tokens[]=$t;$file("$d/.revoked-".hash('sha256',$old).'-'.bin2hex($t).'.session',"foreign-tombstone-$i");}$o=$owner($r,[32=>[$candidate],16=>array_merge([$stage],$tokens),12=>[str_repeat('e',12)]]);$x=$o->regenerate($old,'new');assertSameValue('ID_COLLISION',$x->category()?->name,'regenerate exhausts eight tombstones');assertSameValue('old-before-tombstones',file_get_contents("$d/s-$old.session"),'tombstone collisions preserve old');assertSameValue(false,is_file("$d/s-".bin2hex($candidate).'.session'),'candidate never published');$o->close();
 $r=$parent.'/task-'.bin2hex(random_bytes(8));$roots[]=$r;$d=$mk($r);$old=str_repeat('D',16);$file("$d/s-$old.session",'destroy-old');$tokens=[];for($i=1;$i<=8;$i++){$t=str_repeat(chr(80+$i),16);$tokens[]=$t;$file("$d/.revoked-".hash('sha256',$old).'-'.bin2hex($t).'.session',"destroy-collision-$i");}$o=$owner($r,[16=>$tokens,12=>[str_repeat('f',12)]]);$x=$o->destroyCommit($old);assertSameValue('ID_COLLISION',$x->category()?->name,'destroy exhausts eight tombstone candidates');assertSameValue('destroy-old',file_get_contents("$d/s-$old.session"),'destroy collisions preserve old valid ID');$o->close();echo"PASS: PILOT-SESSION-STORAGE-001 v7 collision families\n";
}finally{foreach($roots as$r)$remove($r);if(is_dir($parent)&&count(scandir($parent)?:[])===2)rmdir($parent);}
