<?php
// DEADLINE-TRANSFER-CERTIFICATE-001 — root-authored real dump/restore of immutable PDF chunks.
declare(strict_types=1);
require dirname(__DIR__).'/bootstrap.php';require dirname(__DIR__,2).'/app/autoload.php';
use FMonitor2\Tests\Support\{DeadlineSchemaFixture as Fixture,RecoveryContainerNetwork,AssignmentOrderOriginalPdfCorpus as Pdf};
use FMonitor2\InstallationProcess\{CanonicalMigrationApplication as Migration,ProductionPilotMigrationCatalogue as Catalogue};
use FMonitor2\RuntimeRestore\{RuntimeRecovery,RuntimeRecoverySchemaV29};
use FMonitor2\Runtime\{RuntimeConfiguration,RuntimeStorage,RuntimeReadiness};
use FMonitor2\DeadlineTransferCertificate\DeadlineTransferCertificates as Certificates;
assertSameValue(true,class_exists(RuntimeRecoverySchemaV29::class),'RED_ASSERTION certificate recovery v27 absent');
function certificateProcess(array $argv,array $env=[],?string $log=null):array{
 $spec=[0=>['file','/dev/null','r'],1=>$log===null?['pipe','w']:['file',$log,'a'],2=>$log===null?['pipe','w']:['file',$log,'a']];$proc=proc_open($argv,$spec,$pipes,dirname(__DIR__,2),array_replace(getenv(),$env));if(!is_resource($proc))throw new TestFailure('process setup');$out=$log===null?stream_get_contents($pipes[1]):'';$err=$log===null?stream_get_contents($pipes[2]):'';if($log===null){fclose($pipes[1]);fclose($pipes[2]);}return[proc_close($proc),$out,$err];
}
if(getenv('FMONITOR_CERT_RECOVERY_CONTAINER')!=='1'){
 $root=dirname(__DIR__,2);$control=(string)realpath(sys_get_temp_dir()).'/cert-recovery-build-'.bin2hex(random_bytes(6));mkdir($control,0700);$image='fmonitor2-certificate-recovery:'.bin2hex(random_bytes(6));
 try{mkdir($control.'/v24',0700);assertSameValue(0,certificateProcess(['git','archive','--format=tar','--output='.$control.'/v24.tar','79b3a4cecae558d74d781f353e967f03c036b921','app','bin'])[0],'retained v24 public tool source');assertSameValue(0,certificateProcess(['tar','-xf',$control.'/v24.tar','-C',$control.'/v24'])[0],'unpack retained tool outside checkout');chmod($control.'/v24',0755);assertSameValue(0,certificateProcess(['docker','build','-f','deploy/runtime/Dockerfile','-t',$image,'.'],[],$control.'/build.log')[0],'focused current runtime image build; log '.$control.'/build.log');
 $network=RecoveryContainerNetwork::forHost(getenv('FMONITOR_TEST_DB_HOST')?:'127.0.0.1');$cmd=['docker','run','--rm',...$network['arguments'],'-v',$root.'/tests:/workspace/fmonitor-2/tests:ro','-v',$control.'/v24:/old-v24:ro','-e','FMONITOR_CERT_RECOVERY_CONTAINER=1','-e','FMONITOR_TEST_DB_HOST='.$network['databaseHost'],'-e','FMONITOR_TEST_DB_PORT='.(getenv('FMONITOR_TEST_DB_PORT')?:'23306'),'-e','FMONITOR_TEST_DB_ADMIN_USER='.(getenv('FMONITOR_TEST_DB_ADMIN_USER')?:'root'),'-e','FMONITOR_TEST_DB_ADMIN_PASSWORD='.(getenv('FMONITOR_TEST_DB_ADMIN_PASSWORD')?:'fmonitor2_test_root_local'),'--entrypoint','php',$image,'tests/Runtime/deadline_transfer_certificate_recovery_001_test.php'];[$exit,$out,$err]=certificateProcess($cmd);echo$out;assertSameValue([0,''],[$exit,$err],'real runtime recovery container');
 }finally{certificateProcess(['docker','image','rm',$image],[],$control.'/cleanup.log');}exit(0);
}
require dirname(__DIR__,2).'/vendor/autoload.php';
$f=new Fixture();$p='cr_';$control=(string)realpath(sys_get_temp_dir()).'/cert-recovery-'.bin2hex(random_bytes(6));mkdir($control,0700);
try{
 $db=$f->database();$name=$db->query('SELECT DATABASE()')->fetch_column();assertSameValue(0,Migration::run($db,$p,Catalogue::migrations())['exitCode'],'canonical v28');
 FMonitor2\IdentityAccess\MariaDbInitialOwnerProvisioning::provision($db,$p,'certificate.recovery@shlz.ru','Certificate recovery fixture 2026');
 $actor=(int)$db->query("SELECT user_id FROM {$p}fm2_pilot_users")->fetch_column();$role=(int)$db->query("SELECT role_id FROM {$p}fm2_pilot_roles WHERE code='fkr_operator'")->fetch_column();$db->query("INSERT INTO {$p}fm2_pilot_user_roles(user_id,role_id,origin,assigned_at)VALUES($actor,$role,'fixture','2026-09-14T12:00:00Z')");
 $db->query("INSERT INTO {$p}fm2_installation_cases(id,legacy_installation_object_id,process_state,created_at,updated_at,lock_version)VALUES(6101,4512,'requires_assignment_order','2026-09-14T12:00:00Z','2026-09-14T12:00:00Z',0)");
 $service=new Certificates($db,$p,static fn():string=>'2026-09-14T12:00:00Z');$pdf=Pdf::passiveClassic().str_repeat(' ',80000);$offset=0;$stream=static function()use($pdf,&$offset):?string{if($offset>=strlen($pdf))return null;$chunk=substr($pdf,$offset,65536);$offset+=strlen($chunk);return$chunk;};
 $revision=$service->submit(['requestId'=>'00000000-0000-4000-8000-000000000901','installationCaseId'=>6101,'actorId'=>$actor,'expectedVersion'=>0,'certificateDate'=>'2026-09-01','newDeadline'=>'2026-09-20','correctionReason'=>null,'sourceLabel'=>'Recovery fixture','sourceLocator'=>'fixture://recovery/certificate','mediaType'=>'application/pdf'],$stream)['revision'];
 $db->query("ALTER TABLE {$p}fm2_deadline_certificate_revisions AUTO_INCREMENT=90001");$before=Fixture::rows($db,RuntimeRecoverySchemaV29::tables($p));$auto=Fixture::counters($db);
 $env=static function(string $database,string $state)use($f,$p,$control):array{return['FMONITOR_DB_HOST'=>$f->host,'FMONITOR_DB_PORT'=>(string)$f->port,'FMONITOR_DB_NAME'=>$database,'FMONITOR_DB_USER'=>$f->user,'FMONITOR_DB_PASSWORD'=>$f->password,'FMONITOR_PROCESS_TABLE_PREFIX'=>$p,'FMONITOR_LEGACY_TABLE_PREFIX'=>$p,'FMONITOR_SESSION_STATE_ROOT'=>$state,'FMONITOR_SESSION_INSTANCE'=>'certificate','FMONITOR_ARTIFACT_STORAGE_ROOT'=>$state.'/artifacts','FMONITOR_ORIGINAL_DB_PASSWORD_FILE'=>$control.'/secret/database-password','FMONITOR_ORIGINAL_SAFE_LOG_FILE'=>$state.'/log/original-safe.jsonl','FMONITOR_TRUSTED_REQUEST_HOST'=>'certificate.example.test','FMONITOR_TRUSTED_REQUEST_SCHEME'=>'https'];};
 $sourceEnv=$env($name,$control.'/source');RuntimeStorage::prepare(RuntimeConfiguration::fromEnvironment($sourceEnv));MariaDbRuntimeReadiness::assertDeepReady(RuntimeConfiguration::fromEnvironment($sourceEnv));
 $identity=['--source-commit',str_repeat('a',40),'--image-reference','certificate-focused-v27','--image-id','sha256:'.str_repeat('a',64)];$bundle=$control.'/bundle';
 $backup=RuntimeRecovery::run(['runtime-recovery','backup','--destination',$bundle,...$identity,'--writers-stopped'],$sourceEnv);assertSameValue([0,'BACKUP_CREATED'],[$backup['exitCode'],$backup['result']['reason']],'real mariadb-dump backup');
 $manifest=json_decode(file_get_contents($bundle.'/manifest.json'),true,32,JSON_THROW_ON_ERROR);assertSameValue([33,91,48],[$manifest['database']['schemaVersion'],count($manifest['database']['tables']),count($manifest['database']['autoIncrement'])],'backup carries exact v33 inventory');
 // The actual pre-v26 tool must refuse newer DB/bundle before modifying their state.
 $oldCli='/old-v24/bin/fmonitor2-runtime-recovery.php';$oldBackup=certificateProcess([PHP_BINARY,$oldCli,'backup','--destination',$control.'/old-backup',...$identity,'--writers-stopped'],$sourceEnv);assertSameValue([70,"{\"ok\":false,\"reason\":\"BACKUP_FAILED\"}\n",''],$oldBackup,'old v24 backup refuses current schema');assertSameValue(false,file_exists($control.'/old-backup'),'old tool publishes no incomplete bundle');assertSameValue([$before,$auto],[Fixture::rows($db,RuntimeRecoverySchemaV29::tables($p)),Fixture::counters($db)],'old backup cannot mutate v27 rows or counters');
 $oldTarget=$f->database();$oldName=$oldTarget->query('SELECT DATABASE()')->fetch_column();$oldState=$control.'/old-target';$oldRestore=certificateProcess([PHP_BINARY,$oldCli,'restore','--bundle',$bundle,'--target-state-root',$oldState,...$identity],$env($oldName,$oldState));assertSameValue([67,"{\"ok\":false,\"reason\":\"BUNDLE_INVALID\"}\n",''],$oldRestore,'old v24 restore rejects newer manifest');assertSameValue([],Fixture::tables($oldTarget),'old restore zero target DDL');assertSameValue(false,file_exists($oldState),'old restore zero private state');$oldTarget->close();
 $target=$f->database();$targetName=$target->query('SELECT DATABASE()')->fetch_column();$targetEnv=$env($targetName,$control.'/target');$restore=RuntimeRecovery::run(['runtime-recovery','restore','--bundle',$bundle,'--target-state-root',$control.'/target',...$identity],$targetEnv);assertSameValue([0,'RESTORE_COMPLETED'],[$restore['exitCode'],$restore['result']['reason']],'real mariadb restore');
 assertSameValue([$before,$auto],[Fixture::rows($target,RuntimeRecoverySchemaV29::tables($p)),Fixture::counters($target)],'every row, binary chunk and counter survives actual dump/restore');
 $restored=new Certificates($target,$p,static fn():string=>'2026-09-14T12:00:00Z');assertSameValue($pdf,$restored->download($actor,$revision['id'])['bytes'],'restored document downloaded through public seam');assertSameValue($service->read($actor,6101),$restored->read($actor,6101),'restored immutable history');
 // Readiness is read-only and must reject an incomplete current certificate schema.
 $target->query("RENAME TABLE {$p}fm2_deadline_certificate_pdf_chunks TO {$p}certificate_hidden_chunks");$tablesBefore=Fixture::tables($target);$refused=false;try{RuntimeReadiness::assertReady(RuntimeConfiguration::fromEnvironment($targetEnv));}catch(RuntimeException $e){$refused=$e->getMessage()==='SCHEMA_NOT_READY';}assertSameValue(true,$refused,'current readiness checks certificate schema');assertSameValue($tablesBefore,Fixture::tables($target),'readiness performs no DDL');
 $target->close();$db->close();echo "PASS DEADLINE-TRANSFER-CERTIFICATE-001 recovery\n";
}finally{$f->close();Fixture::closeTree($control);}
