<?php
declare(strict_types=1);
require dirname(__DIR__) . '/bootstrap.php';
require dirname(__DIR__, 2) . '/app/autoload.php';
use FMonitor2\InstallationProcess\CanonicalMigrationApplication;
use FMonitor2\InstallationProcess\ProductionPilotMigrationCatalogue;
use FMonitor2\Runtime\RuntimeConfiguration;
use FMonitor2\Runtime\RuntimeReadiness;
use FMonitor2\Runtime\RuntimeStorage;

mysqli_report(MYSQLI_REPORT_ERROR|MYSQLI_REPORT_STRICT);$repo=dirname(__DIR__,2);
$host=getenv('FMONITOR_TEST_DB_HOST')?:'127.0.0.1';$port=(int)(getenv('FMONITOR_TEST_DB_PORT')?:23306);$user=getenv('FMONITOR_TEST_DB_ADMIN_USER')?:'root';$password=getenv('FMONITOR_TEST_DB_ADMIN_PASSWORD')?:'fmonitor2_test_root_local';
$admin=new mysqli($host,$user,$password,'',$port);$token=bin2hex(random_bytes(5));$database='t_ready_load_'.$token;$otherDatabase='t_ready_other_'.$token;$prefix='load_';$temporaryRoot=realpath(sys_get_temp_dir());if(!is_string($temporaryRoot))throw new TestFailure('SETUP_FAILURE temporary root');$state=$temporaryRoot.'/fmonitor-ready-load-'.$token;
function rrlRemove(string$p):void{if(is_link($p)||is_file($p)){unlink($p);return;}if(!is_dir($p))return;foreach(scandir($p)?:[]as$e)if($e!=='.'&&$e!=='..')rrlRemove($p.'/'.$e);rmdir($p);}
function rrlEnv(string$host,int$port,string$db,string$user,string$password,string$prefix,string$root,string$buildFile):array{return['FMONITOR_DB_HOST'=>$host,'FMONITOR_DB_PORT'=>(string)$port,'FMONITOR_DB_NAME'=>$db,'FMONITOR_DB_USER'=>$user,'FMONITOR_DB_PASSWORD'=>$password,'FMONITOR_PROCESS_TABLE_PREFIX'=>$prefix,'FMONITOR_LEGACY_TABLE_PREFIX'=>$prefix,'FMONITOR_SESSION_STATE_ROOT'=>$root.'/state','FMONITOR_SESSION_INSTANCE'=>'readiness','FMONITOR_ARTIFACT_STORAGE_ROOT'=>$root.'/state/artifacts','FMONITOR_ORIGINAL_DB_PASSWORD_FILE'=>$root.'/secret/database-password','FMONITOR_ORIGINAL_SAFE_LOG_FILE'=>$root.'/state/log/original-safe.jsonl','FMONITOR_TRUSTED_REQUEST_HOST'=>'readiness.example.test','FMONITOR_TRUSTED_REQUEST_SCHEME'=>'https','FMONITOR_RUNTIME_BUILD_ID_FILE'=>$buildFile];}
function rrlCli(string$repo,array$environment):array{$pipes=[];$process=proc_open([PHP_BINARY,$repo.'/bin/fmonitor2-runtime-check.php'],[0=>['file','/dev/null','r'],1=>['pipe','w'],2=>['pipe','w']],$pipes,$repo,array_replace(getenv(),$environment));if(!is_resource($process))throw new TestFailure('SETUP_FAILURE runtime-check');$out=stream_get_contents($pipes[1]);$err=stream_get_contents($pipes[2]);fclose($pipes[1]);fclose($pipes[2]);return[proc_close($process),$out,$err];}
function rrlFails(RuntimeConfiguration$config,string$label):void{try{RuntimeReadiness::assertReady($config);throw new TestFailure($label.' accepted');}catch(RuntimeException$e){assertSameValue('STARTUP_NOT_READY',$e->getMessage(),$label);}}
try{
 foreach([$database,$otherDatabase]as$name)$admin->query("CREATE DATABASE `{$name}` DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
 $db=new mysqli($host,$user,$password,$database,$port);$migration=CanonicalMigrationApplication::run($db,$prefix,ProductionPilotMigrationCatalogue::migrations());assertSameValue([0,true],[$migration['exitCode'],$migration['result']['ok']??null],'fixture migration succeeds');
 $buildA=$state.'-build-a';$buildB=$state.'-build-b';file_put_contents($buildA,str_repeat('a',64)."\n");file_put_contents($buildB,str_repeat('b',64)."\n");chmod($buildA,0444);chmod($buildB,0444);$env=rrlEnv($host,$port,$database,$user,$password,$prefix,$state,$buildA);$config=RuntimeConfiguration::fromEnvironment($env);RuntimeStorage::prepare($config);$file=$state.'/state/runtime-startup-readiness.json';
 rrlFails($config,'SELECT 1 without startup result');assertSameValue([0,"{\"ok\":true}\n",''],rrlCli($repo,$env),'existing runtime-check performs full check and publishes');
 assertSameValue(true,is_file($file)&&!is_link($file),'attestation is a regular file');$stat=lstat($file);assertSameValue([0600,posix_geteuid(),posix_getegid(),1],[$stat['mode']&0777,$stat['uid'],$stat['gid'],$stat['nlink']],'attestation private ownership');
 RuntimeReadiness::assertReady($config);$before=[file_get_contents($file),filemtime($file),fileinode($file)];for($i=0;$i<8;$i++)RuntimeReadiness::assertReady($config);clearstatcache(true,$file);assertSameValue($before,[file_get_contents($file),filemtime($file),fileinode($file)],'steady probes are read-only');
 $children=[];for($i=0;$i<4;$i++){if(($pid=pcntl_fork())===0){try{RuntimeReadiness::assertReady($config);exit(0);}catch(Throwable){exit(1);}}$children[]=$pid;}foreach($children as$pid){pcntl_waitpid($pid,$status);assertSameValue(0,pcntl_wexitstatus($status),'parallel steady probe');}$db->close();$db=new mysqli($host,$user,$password,$database,$port);clearstatcache(true,$file);assertSameValue($before,[file_get_contents($file),filemtime($file),fileinode($file)],'parallel probes do not publish/deep-check');
 rrlFails(RuntimeConfiguration::fromEnvironment(rrlEnv($host,$port,$database,$user,$password,$prefix,$state,$buildB)),'build mismatch');rrlFails(RuntimeConfiguration::fromEnvironment(rrlEnv($host,$port,$database,$user,$password,'other_',$state,$buildA)),'prefix mismatch');
 $other=new mysqli($host,$user,$password,$otherDatabase,$port);CanonicalMigrationApplication::run($other,$prefix,ProductionPilotMigrationCatalogue::migrations());$other->close();rrlFails(RuntimeConfiguration::fromEnvironment(rrlEnv($host,$port,$otherDatabase,$user,$password,$prefix,$state,$buildA)),'database mismatch');
 $valid=file_get_contents($file);file_put_contents($file,'{}');rrlFails($config,'incomplete attestation');file_put_contents($file,$valid);chmod($file,0600);unlink($file);symlink('/dev/null',$file);rrlFails($config,'symlink attestation');unlink($file);file_put_contents($file,$valid);chmod($file,0600);
 $db->query("DROP TABLE `{$prefix}fm2_pilot_object_details`");$failed=rrlCli($repo,$env);assertSameValue([70,"{\"ok\":false,\"reason\":\"SCHEMA_NOT_READY\"}\n",''],$failed,'failed repeat deep check');rrlFails($config,'failed repeat invalidates prior success');
 assertSameValue(35,max(array_keys(ProductionPilotMigrationCatalogue::migrations())),'readiness reuses current canonical v35 frontier');
 echo "PASS: RUNTIME-READINESS-LOAD-001 startup-bound constant-work readiness\n";$db->close();
}finally{try{$admin->close();}catch(Throwable){}$cleanup=new mysqli($host,$user,$password,'',$port);foreach([$database,$otherDatabase]as$name)$cleanup->query("DROP DATABASE IF EXISTS `{$name}`");$cleanup->close();rrlRemove($state);foreach([$state.'-build-a',$state.'-build-b']as$buildFile)if(is_file($buildFile))unlink($buildFile);}
