<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/Support/RecoveryContainerNetwork.php';
use FMonitor2\Tests\Support\RecoveryContainerNetwork;
require dirname(__DIR__).'/bootstrap.php';require dirname(__DIR__,2).'/app/autoload.php';
use FMonitor2\InstallationProcess\{CanonicalMigrationApplication,ProductionPilotMigrationCatalogue};use FMonitor2\RuntimeRestore\{RuntimeRecoverySchemaV22,RuntimeRecoverySchemaV23};
const FORWARD_V22='f22d80a609d52a194c1fd68b1db7ab7273740f28';
const FORWARD_V23='a6bafb1d4b6c2c9de524dd6637df914034eee9a2';
function fruRun(array$command,string$cwd,array$env=[],$stdout=null):array{$pipes=[];$spec=[0=>['file','/dev/null','r'],1=>$stdout===null?['pipe','w']:['file',$stdout,'w'],2=>['pipe','w']];$p=proc_open($command,$spec,$pipes,$cwd,array_replace(getenv(),$env));if(!is_resource($p))throw new TestFailure('SETUP_FAILURE process');$out=$stdout===null?stream_get_contents($pipes[1]):'';$err=stream_get_contents($pipes[2]);if($stdout===null)fclose($pipes[1]);fclose($pipes[2]);return[proc_close($p),$out,$err];}
function fruRemove(string$path):void{if(is_link($path)||is_file($path)){unlink($path);return;}if(!is_dir($path))return;foreach(scandir($path)?:[]as$e)if($e!=='.'&&$e!=='..')fruRemove($path.'/'.$e);rmdir($path);}
function fruRows(mysqli$db,array$tables):array{$out=[];foreach($tables as$table){$r=$db->query("SELECT * FROM `{$table}`");$order=implode(',',range(1,$r->field_count));$out[$table]=$db->query("SELECT * FROM `{$table}` ORDER BY {$order}")->fetch_all(MYSQLI_ASSOC);}return$out;}
function fruAuto(mysqli$db):array{return$db->query("SELECT TABLE_NAME,CAST(AUTO_INCREMENT AS UNSIGNED) next_value FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND AUTO_INCREMENT IS NOT NULL ORDER BY BINARY TABLE_NAME")->fetch_all(MYSQLI_ASSOC);}
function fruTree(string$root):array{$out=[];foreach(new RecursiveIteratorIterator(new RecursiveDirectoryIterator($root,FilesystemIterator::SKIP_DOTS),RecursiveIteratorIterator::SELF_FIRST)as$i){$relative=substr($i->getPathname(),strlen($root)+1);$out[$relative]=[$i->isDir()?'dir':'file',fileperms($i->getPathname())&0777,$i->isFile()?hash_file('sha256',$i->getPathname()):null];}ksort($out);return$out;}
function fruEnv(string$host,int$port,string$name,string$password,string$state,string$secret,string$prefix='restore_',string$instance='restore'):array{return['FMONITOR_DB_HOST'=>$host,'FMONITOR_DB_PORT'=>(string)$port,'FMONITOR_DB_NAME'=>$name,'FMONITOR_DB_USER'=>'root','FMONITOR_DB_PASSWORD'=>$password,'FMONITOR_PROCESS_TABLE_PREFIX'=>$prefix,'FMONITOR_LEGACY_TABLE_PREFIX'=>$prefix,'FMONITOR_SESSION_STATE_ROOT'=>$state,'FMONITOR_SESSION_INSTANCE'=>$instance,'FMONITOR_ARTIFACT_STORAGE_ROOT'=>$state.'/artifacts','FMONITOR_ORIGINAL_DB_PASSWORD_FILE'=>$secret.'/database-password','FMONITOR_ORIGINAL_SAFE_LOG_FILE'=>$state.'/log/original-safe.jsonl','FMONITOR_TRUSTED_REQUEST_HOST'=>'restore.example.test','FMONITOR_TRUSTED_REQUEST_SCHEME'=>'https'];}
function fruDockerCli(string$image,string$repo,array$env,array$args,string$evidence):array{$network=RecoveryContainerNetwork::forHost($env['FMONITOR_DB_HOST']);$command=['docker','run','--rm','--user',posix_geteuid().':'.posix_getegid(),...$network['arguments'],'-v',$evidence.':/evidence'];foreach($env as$key=>$value){if($key==='FMONITOR_DB_HOST')$value=$network['databaseHost'];else$value=str_replace($evidence,'/evidence',$value);$command[]='-e';$command[]=$key.'='.$value;}$command=array_merge($command,['--entrypoint','php',$image,'bin/fmonitor2-runtime-recovery.php'],array_map(static fn(string$v):string=>str_replace($evidence,'/evidence',$v),$args));return fruRun($command,$repo);}
$selectedVersion=getenv('FMONITOR_RECOVERY_FORWARD_VERSION');
if ($selectedVersion===false) {
    foreach ([22,23] as $version) {
        [$exit,$out,$err]=fruRun([PHP_BINARY,__FILE__],dirname(__DIR__,2),['FMONITOR_RECOVERY_FORWARD_VERSION'=>(string)$version]);
        echo $out;
        assertSameValue([0,''],[$exit,$err],'exact historical version '.$version.' forward rehearsal');
    }
    exit(0);
}
if (!in_array($selectedVersion,['22','23'],true)) throw new TestFailure('SETUP_FAILURE: invalid forward version');
$version=(int)$selectedVersion;
$historicalSource=$version===22?FORWARD_V22:FORWARD_V23;
$prefix=$version===22?'restore_':'jr_';
$expectedTables=$version===22?63:69;
$expectedAuto=$version===22?35:39;
$repo=dirname(__DIR__,2);$host=getenv('FMONITOR_TEST_DB_HOST')?:'127.0.0.1';$network=RecoveryContainerNetwork::forHost($host);$port=(int)(getenv('FMONITOR_TEST_DB_PORT')?:23306);$password=getenv('FMONITOR_TEST_DB_ADMIN_PASSWORD')?:'fmonitor2_test_root_local';$admin=new mysqli($host,'root',$password,'',$port);$token=bin2hex(random_bytes(5));$control=(string)realpath(sys_get_temp_dir()).'/fm2-forward-'.$token;mkdir($control,0700);$archive=$control.'/historical.tar';$source=$control.'/historical-source';$oldImage='fmonitor2-recovery-v'.$version.':'.$token;$currentImage='fmonitor2-recovery-v24:'.$token;$databases=[];
try{
 [$x,,$e]=fruRun(['git','archive','--format=tar','--output',$archive,$historicalSource],$repo);assertSameValue([0,''],[$x,$e],'exact historical source archive');mkdir($source,0700);assertSameValue(0,fruRun(['tar','-xf',$archive,'-C',$source],$repo)[0],'extract historical source');if ($version===22) {
$historical=$source.'/tests/Runtime/runtime_recovery_001_test.php';$text=file_get_contents($historical);$raceStart=strpos($text,' $raceDestination=');$raceEnd=strpos($text,' $stalePartial=', $raceStart);if($raceStart===false||$raceEnd===false)throw new TestFailure('historical race fixture bounds');$text=substr($text,0,$raceStart).substr($text,$raceEnd);$needle='$backup=rrRun($cli,$sourceEnv,[';$at=strpos($text,$needle);assertSameValue(true,$at!==false,'historical fixture backup seam exists');$statement="assertSameValue(0,\$backup['exit'],'export backup '.json_encode(\$backup));rrCopy(\$bundle,'/evidence/historical-bundle');file_put_contents('/evidence/historical-exported','1');echo \"EXPORT_READY\\n\";exit(0);";$insert=strpos($text,'assertSameValue(0,$backup', $at);$text=substr($text,0,$insert).$statement.substr($text,$insert);} else {
    $historical=$source.'/tests/Runtime/runtime_jobs_recovery_001_test.php';
    $text=file_get_contents($historical);
    $insert=strpos($text,'$manifest=json_decode(file_get_contents($bundle');
    assertSameValue(true,$insert!==false,'historical v23 fixture has successful backup seam');
    $statement= <<<'EXPORT'
mkdir('/evidence/historical-bundle',0700);
foreach (['database.sql','state.tar','manifest.json'] as $file) { copy($bundle.'/'.$file,'/evidence/historical-bundle/'.$file); chmod('/evidence/historical-bundle/'.$file,0600); }
file_put_contents('/evidence/historical-exported','1');
$db->close();
$admin->query("DROP DATABASE IF EXISTS `$source`");
$admin->query("DROP DATABASE IF EXISTS `$target`");
$admin->close();
echo "EXPORT_READY\n";
exit(0);
EXPORT;
    $text=substr($text,0,$insert).$statement.substr($text,$insert);
}
file_put_contents($control.'/historical-export-test.php',$text);chmod($control.'/historical-export-test.php',0600);
 assertSameValue(0,fruRun(['docker','build','-f','deploy/runtime/Dockerfile','--label','org.opencontainers.image.revision='.$historicalSource,'-t',$oldImage,'.'],$source,[],$control.'/historical-build.log')[0],'build exact v22 image');assertSameValue(0,fruRun(['docker','build','-f','deploy/runtime/Dockerfile','--label','org.opencontainers.image.revision='.trim((string)shell_exec('git -C '.escapeshellarg($repo).' rev-parse HEAD')),'-t',$currentImage,'.'],$repo,[],$control.'/v24-build.log')[0],'build current image');$oldIdentity=fruRun(['docker','image','inspect',$oldImage,'--format','{{index .Config.Labels "org.opencontainers.image.revision"}}'],$repo);assertSameValue([0,$historicalSource,''],[$oldIdentity[0],trim($oldIdentity[1]),$oldIdentity[2]],'historical image OCI revision exact');
 $run=['docker','run','--rm','--user',posix_geteuid().':'.posix_getegid(),...$network['arguments'],'-v',$control.':/evidence','-v',$source.'/tests:/workspace/fmonitor-2/tests:ro','-v',$control.'/historical-export-test.php:/workspace/fmonitor-2/tests/Runtime/'.basename($historical).':ro','-e','FMONITOR_RECOVERY_CONTAINER_TEST=1','-e','FMONITOR_JOBS_RECOVERY_CONTAINER=1','-e','FMONITOR_TEST_DB_HOST='.$network['databaseHost'],'-e','FMONITOR_TEST_DB_PORT='.(string)$port,'-e','FMONITOR_TEST_DB_ADMIN_USER=root','-e','FMONITOR_TEST_DB_ADMIN_PASSWORD='.$password,'--entrypoint','php',$oldImage,'-d','display_errors=1','-d','log_errors=0','tests/Runtime/'.basename($historical)];[$x,$out,$err]=fruRun($run,$repo);assertSameValue([0,''],[$x,$err],'historical recovery fixture '.$out);assertSameValue(true,is_file($control.'/historical-exported')&&is_dir($control.'/historical-bundle'),'exact historical image exported reviewed bundle');$manifest=json_decode(file_get_contents($control.'/historical-bundle/manifest.json'),true,32,JSON_THROW_ON_ERROR);assertSameValue([$version,$expectedTables,$expectedAuto,$version===22?['jobs-outbox-issue-34']:[]],[$manifest['database']['schemaVersion'],count($manifest['database']['tables']),count($manifest['database']['autoIncrement']),$manifest['deferred']],'literal historical bundle contract for version '.$version);
 $target='t_forward_'.$token;$admin->query("CREATE DATABASE `{$target}` DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");$databases[]=$target;$state=$control.'/forward-state';$secret=$control.'/forward-secret';mkdir($secret,0700);file_put_contents($secret.'/database-password',$password);chmod($secret.'/database-password',0600);$env=fruEnv($host,$port,$target,$password,$state,$secret,$prefix,$version===23?'recovery':'restore');[$x,$out,$err]=fruDockerCli($oldImage,$repo,$env,['restore','--bundle',$control.'/historical-bundle','--target-state-root',$state,'--source-commit',$manifest['sourceCommit'],'--image-reference',$manifest['imageReference'],'--image-id',$manifest['imageId']],$control);assertSameValue([0,"{\"ok\":true,\"reason\":\"RESTORE_COMPLETED\"}\n",''],[$x,$out,$err],'exact historical image restores its own bundle');$db=new mysqli($host,'root',$password,$target,$port);$historicalProfile=$version===22?RuntimeRecoverySchemaV22::class:RuntimeRecoverySchemaV23::class;$oldTables=$historicalProfile::tables($prefix);$beforeRows=fruRows($db,$oldTables);$beforeAuto=fruAuto($db);$beforeState=fruTree($state);assertSameValue([$expectedTables,$expectedAuto],[count($beforeRows),count($beforeAuto)],'forward baseline has the exact historical table/AUTO counts');$rowCount=array_sum(array_map('count',$beforeRows));assertSameValue(true,$rowCount>=15&&count($beforeState)>=4,'historical bundle carries meaningful relational rows and private state');$processAuto=array_values(array_filter($beforeAuto,static fn(array$r):bool=>$r['TABLE_NAME']===$prefix.($version===22?'fm2_process_events':'fm2_jobs')));assertSameValue($version===22?1602:50001,(int)$processAuto[0]['next_value'],'historical deleted high id preserves AUTO frontier');$migration=CanonicalMigrationApplication::run($db,$prefix,ProductionPilotMigrationCatalogue::migrations());assertSameValue([0,24],[$migration['exitCode'],$migration['result']['schemaVersion']??null],'additive migrations23/24 succeeds');assertSameValue([$beforeRows,$beforeAuto,$beforeState],[fruRows($db,$oldTables),array_values(array_filter(fruAuto($db),static fn(array$r):bool=>in_array($r['TABLE_NAME'],array_column($beforeAuto,'TABLE_NAME'),true))),fruTree($state)],'migrations23/24 preserves every old table row, old AUTO value and state byte');$jobs=array_merge($version===22?['fm2_job_events','fm2_jobs','fm2_outbox_attempt_events','fm2_outbox_intents','fm2_scheduler_slots','fm2_worker_heartbeats']:[],['fm2_otiz_settlement_locks','fm2_otiz_settlement_operations']);$counts=[];foreach($jobs as$suffix)$counts[]=(int)$db->query("SELECT COUNT(*) FROM `{$prefix}{$suffix}`")->fetch_column();assertSameValue(array_fill(0,count($jobs),0),$counts,'only newly introduced Jobs/settlement tables start empty');$db->close();
 $v24=$control.'/v24-bundle';[$x,$out,$err]=fruDockerCli($currentImage,$repo,$env,['backup','--destination',$v24,'--source-commit',str_repeat('b',40),'--image-reference',$currentImage,'--image-id','sha256:'.str_repeat('b',64),'--writers-stopped'],$control);assertSameValue([0,"{\"ok\":true,\"reason\":\"BACKUP_CREATED\",\"formatVersion\":\"fmonitor-runtime-backup-v1\"}\n",''],[$x,$out,$err],'INTENTIONAL_RED: current image creates exact v24 bundle');$v24Manifest=json_decode(file_get_contents($v24.'/manifest.json'),true,32,JSON_THROW_ON_ERROR);assertSameValue([24,71,39,[]],[$v24Manifest['database']['schemaVersion'],count($v24Manifest['database']['tables']),count($v24Manifest['database']['autoIncrement']),$v24Manifest['deferred']],'v24 manifest exact expanded inventory');
 $reject='t_forward_reject_'.$token;$admin->query("CREATE DATABASE `{$reject}` DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");$databases[]=$reject;$rejectState=$control.'/reject-state';$rejectSecret=$control.'/reject-secret';mkdir($rejectSecret,0700);file_put_contents($rejectSecret.'/database-password',$password);chmod($rejectSecret.'/database-password',0600);$rejectEnv=fruEnv($host,$port,$reject,$password,$rejectState,$rejectSecret,$prefix,$version===23?'recovery':'restore');[$x,$out,$err]=fruDockerCli($oldImage,$repo,$rejectEnv,['restore','--bundle',$v24,'--target-state-root',$rejectState,'--source-commit',str_repeat('b',40),'--image-reference',$currentImage,'--image-id','sha256:'.str_repeat('b',64)],$control);assertSameValue([67,"{\"ok\":false,\"reason\":\"BUNDLE_INVALID\"}\n",''],[$x,$out,$err],'old image rejects v24 bundle');$rejectDb=new mysqli($host,'root',$password,$reject,$port);assertSameValue([0,false],[(int)$rejectDb->query('SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE()')->fetch_column(),file_exists($rejectState)],'historical rejection has zero DB/state mutation');$rejectDb->close();echo "PASS: PRODUCTION-JOBS-RECOVERY-001 exact historical forward update boundary\n";
}finally{foreach($databases as$db)try{$admin->query("DROP DATABASE IF EXISTS `{$db}`");}catch(Throwable){}$admin->close();fruRun(['docker','image','rm','-f',$oldImage],$repo);fruRun(['docker','image','rm','-f',$currentImage],$repo);fruRemove($control);}
