<?php
declare(strict_types=1);
require dirname(__DIR__).'/bootstrap.php';require dirname(__DIR__).'/Yii2/Yii2AuthFixture.php';
use FMonitor2\Tests\Yii2\Yii2AuthFixture;
const YWC_RED='INTENDED_RED: production web cutover';$GLOBALS['ywc_requests']=0;
function ywcRequest(int$p,string$m,string$path,?string$host=null,?string$case=null):array{$GLOBALS['ywc_requests']++;$headers=['Host: '.($host??'127.0.0.1:'.$p),'Connection: close'];if($case!==null)$headers[]='X-FMonitor-Test-Case: '.$case;$c=stream_context_create(['http'=>['ignore_errors'=>true,'follow_location'=>0,'timeout'=>10,'method'=>$m,'header'=>implode("\r\n",$headers)]]);$body=file_get_contents("http://127.0.0.1:$p$path",false,$c);$raw=$http_response_header??[];preg_match('#^HTTP/\S+ (\d+)#D',$raw[0]??'',$x);$h=[];foreach(array_slice($raw,1)as$l){$at=strpos($l,':');if($at!==false){$name=strtolower(substr($l,0,$at));if($name!=='host')$h[$name][]=trim(substr($l,$at+1));}}return['status'=>(int)($x[1]??0),'headers'=>$h,'body'=>(string)$body];}
function ywcCheck(mixed$e,mixed$a,string$l,array&$f):void{if($e!==$a)$f[]=$l.' expected='.var_export($e,true).' actual='.var_export($a,true);}
function ywcFacts(mysqli$db):array{$facts=[];foreach($db->query('SHOW TABLES')->fetch_all(MYSQLI_NUM)as[$t]){$safe=str_replace('`','``',$t);$facts[$t]=$db->query("SELECT * FROM `$safe`")->fetch_all(MYSQLI_ASSOC);}ksort($facts);return$facts;}
function ywcTree(string$root):array{if(!file_exists($root))return[];if(is_file($root))return['.'=>[filesize($root),hash_file('sha256',$root)]];$tree=[];foreach(new RecursiveIteratorIterator(new RecursiveDirectoryIterator($root,FilesystemIterator::SKIP_DOTS))as$file)if($file->isFile())$tree[substr($file->getPathname(),strlen($root))]=[$file->getSize(),hash_file('sha256',$file->getPathname())];ksort($tree);return$tree;}
function ywcPrivate(array$env):array{$paths=['FMONITOR_SESSION_STATE_ROOT','FMONITOR_YII_SESSION_PATH','FMONITOR_ARTIFACT_STORAGE_ROOT','FMONITOR_ORIGINAL_DB_PASSWORD_FILE','FMONITOR_ORIGINAL_SAFE_LOG_FILE'];$state=[];foreach($paths as$key)$state[$key]=ywcTree($env[$key]);if(!isset($GLOBALS['ywc_initial_stable'])){$GLOBALS['ywc_initial_stable']=$state;unset($GLOBALS['ywc_initial_stable']['FMONITOR_SESSION_STATE_ROOT'],$GLOBALS['ywc_initial_stable']['FMONITOR_YII_SESSION_PATH']);}return$state;}
function ywcStablePrivate(array$env):array{static$calls=0;$calls++;if($calls===1)return$GLOBALS['ywc_initial_stable'];$all=ywcPrivate($env);unset($all['FMONITOR_SESSION_STATE_ROOT'],$all['FMONITOR_YII_SESSION_PATH']);return$all;}
function ywcWithoutSessionPaths(array$state):array{unset($state['FMONITOR_SESSION_STATE_ROOT'],$state['FMONITOR_YII_SESSION_PATH']);return$state;}
function ywcWithoutEmptySessionPlaceholders(array$state):array{foreach(['FMONITOR_SESSION_STATE_ROOT','FMONITOR_YII_SESSION_PATH']as$key)foreach($state[$key]??[]as$path=>$meta)if(str_contains($path,'sess_')&&($meta[0]??-1)===0)unset($state[$key][$path]);return$state;}
function ywcRaw(int$port,string$request):array{$GLOBALS['ywc_requests']++;$socket=stream_socket_client("tcp://127.0.0.1:$port",$code,$message,5);if(!is_resource($socket))throw new TestFailure('SETUP_FAILURE raw request');fwrite($socket,$request);$raw=stream_get_contents($socket);fclose($socket);[$head,$body]=array_pad(explode("\r\n\r\n",(string)$raw,2),2,'');$lines=explode("\r\n",$head);preg_match('#^HTTP/\S+ (\d+)#D',$lines[0]??'',$match);$headers=[];foreach(array_slice($lines,1)as$line){$at=strpos($line,':');if($at!==false)$headers[strtolower(substr($line,0,$at))][]=trim(substr($line,$at+1));}return['status'=>(int)($match[1]??0),'headers'=>$headers,'body'=>$body];}
function ywcStart(string$root,array$env,?string$probe=null):array{$l=stream_socket_server('tcp://127.0.0.1:0',$e,$x);if(!is_resource($l))throw new TestFailure('SETUP_FAILURE port');preg_match('/:(\d+)$/D',(string)stream_socket_get_name($l,false),$m);$p=(int)$m[1];fclose($l);$env['FMONITOR_TRUSTED_REQUEST_HOST']='127.0.0.1:'.$p;$cmd=[PHP_BINARY,'-d','display_errors=0'];if($probe)$cmd=[...$cmd,'-d','auto_prepend_file='.$probe];$cmd=[...$cmd,'-S','127.0.0.1:'.$p,$root.'/public/runtime.php'];$proc=proc_open($cmd,[0=>['file','/dev/null','r'],1=>['file','/dev/null','a'],2=>['file','/dev/null','a']],$pipes,$root,$env);if(!is_resource($proc))throw new TestFailure('SETUP_FAILURE server');$d=microtime(true)+5;do{$s=@fsockopen('127.0.0.1',$p,$e,$x,.1);if(is_resource($s)){fclose($s);return['process'=>$proc,'port'=>$p];}usleep(20000);}while(microtime(true)<$d);throw new TestFailure('SETUP_FAILURE listen');}
function ywcStop(?array&$s):void{if(!$s)return;proc_terminate($s['process']);proc_close($s['process']);$s=null;}
function ywcSafeFailure(array$r,string$label,array$secrets,array&$fail):void{
 $security=['content-type'=>'application/json; charset=UTF-8','cache-control'=>'no-store','retry-after'=>'60','x-content-type-options'=>'nosniff','referrer-policy'=>'no-referrer','x-frame-options'=>'DENY','content-security-policy'=>"default-src 'none'; script-src 'self'; connect-src 'self'; style-src 'self'; img-src 'self'; font-src 'self'; form-action 'self'; base-uri 'none'; frame-ancestors 'none'",'permissions-policy'=>'camera=(), microphone=(), geolocation=()','cross-origin-opener-policy'=>'same-origin'];
 ywcCheck(503,$r['status'],$label.' status',$fail);ywcCheck("{\"ok\":false,\"reason\":\"SERVICE_UNAVAILABLE\"}\n",$r['body'],$label.' body',$fail);foreach($security as$header=>$value)ywcCheck($value,$r['headers'][$header][0]??null,$label.' '.$header,$fail);ywcCheck(false,isset($r['headers']['set-cookie']),$label.' no cookie',$fail);$encoded=json_encode($r,JSON_THROW_ON_ERROR);foreach([...$secrets,'RuntimeException','Warning','Fatal error','Stack trace','#0']as$secret)if($secret!=='')ywcCheck(false,str_contains($encoded,$secret),$label.' does not disclose '.$secret,$fail);
}
function ywcFailureCase(string$root,Yii2AuthFixture$fixture,array$env,array$override,string$path,string$label,array&$fail,?string$prepend=null):void{
 $caseEnv=array_replace($env,$override);$beforeFacts=ywcFacts($fixture->db);$beforePrivate=ywcPrivate($caseEnv);$server=null;try{$server=ywcStart($root,$caseEnv,$prepend);$r=ywcRequest($server['port'],'GET',$path);ywcSafeFailure($r,$label,array_values(array_filter([$caseEnv['FMONITOR_DB_PASSWORD']??'',...array_map(static fn($key)=>(string)($caseEnv[$key]??''),['FMONITOR_SESSION_STATE_ROOT','FMONITOR_YII_SESSION_PATH','FMONITOR_ARTIFACT_STORAGE_ROOT','FMONITOR_ORIGINAL_DB_PASSWORD_FILE','FMONITOR_ORIGINAL_SAFE_LOG_FILE'])])),$fail);}finally{ywcStop($server);}ywcCheck($beforeFacts,ywcFacts($fixture->db),$label.' whole DB unchanged',$fail);$afterPrivate=ywcPrivate($caseEnv);if($label==='durable session close failure'){$beforePrivate=ywcWithoutEmptySessionPlaceholders($beforePrivate);$afterPrivate=ywcWithoutEmptySessionPlaceholders($afterPrivate);}ywcCheck($beforePrivate,$afterPrivate,$label.' all committed private paths unchanged',$fail);
}
$root=dirname(__DIR__,2);$fixture=new Yii2AuthFixture($root);$log=tempnam(sys_get_temp_dir(),'ywc-');$server=null;$fail=[];
try{$tmp=realpath(sys_get_temp_dir())?:throw new TestFailure('SETUP_FAILURE temp');$token=bin2hex(random_bytes(4));$sandbox=$tmp.'/ywc-private-'.$token;$env=array_replace(getenv(),$fixture->environment(),['FMONITOR_TEST_INCLUDED_FILES_LOG'=>$log,'FMONITOR_LEGACY_TABLE_PREFIX'=>$fixture->prefix,'FMONITOR_SESSION_STATE_ROOT'=>$sandbox.'/state','FMONITOR_YII_SESSION_PATH'=>$sandbox.'/yii','FMONITOR_SESSION_INSTANCE'=>'cutover_'.$token,'FMONITOR_ARTIFACT_STORAGE_ROOT'=>$sandbox.'/artifacts','FMONITOR_ORIGINAL_DB_PASSWORD_FILE'=>$sandbox.'/secret/database-password','FMONITOR_ORIGINAL_SAFE_LOG_FILE'=>$sandbox.'/log/original-safe.jsonl']);FMonitor2\Runtime\RuntimeStorage::prepare(FMonitor2\Runtime\RuntimeConfiguration::fromEnvironment($env));$server=ywcStart($root,$env,$root.'/tests/Support/included_files_probe.php');$p=$server['port'];$facts=ywcFacts($fixture->db);$private=ywcPrivate($env);$contract=require $root.'/tests/Support/yii2_production_web_cutover_contract.php';
 $security=['x-content-type-options'=>'nosniff','referrer-policy'=>'no-referrer','x-frame-options'=>'DENY','content-security-policy'=>"default-src 'none'; script-src 'self'; connect-src 'self'; style-src 'self'; img-src 'self'; font-src 'self'; form-action 'self'; base-uri 'none'; frame-ancestors 'none'",'permissions-policy'=>'camera=(), microphone=(), geolocation=()','cross-origin-opener-policy'=>'same-origin'];$dynamic=[['GET','/health/live',200],['GET','/health/ready',200],['GET','/',302],['GET','/pilot/login',200],['GET','/pilot/objects',303],['GET','/pilot/admin/users',303],['GET','/pilot/does-not-exist',404]];foreach($dynamic as[$m,$path,$status]){$r=ywcRequest($p,$m,$path);ywcCheck($status,$r['status'],"$m $path status",$fail);ywcCheck('no-store',$r['headers']['cache-control'][0]??null,"$path cache",$fail);foreach($security as$h=>$value)ywcCheck($value,$r['headers'][$h][0]??null,"$path $h",$fail);}
 $live=ywcRequest($p,'GET','/health/live',null,'health-live');ywcCheck(['application/json; charset=UTF-8',"{\"ok\":true}\n"],[$live['headers']['content-type'][0]??null,$live['body']],'exact live',$fail);$ready=ywcRequest($p,'GET','/health/ready',null,'health-ready');ywcCheck([200,"{\"ok\":true}\n"],[$ready['status'],$ready['body']],'exact ready',$fail);$rr=ywcRequest($p,'GET','/',null,'root');ywcCheck([302,'/pilot/objects'],[$rr['status'],$rr['headers']['location'][0]??null],'root redirect',$fail);$unknown=ywcRequest($p,'GET','/pilot/does-not-exist',null,'unknown');ywcCheck([404,'{"ok":false,"reason":"NOT_FOUND"}'],[$unknown['status'],trim($unknown['body'])],'safe unknown',$fail);$method=ywcRequest($p,'GET','/pilot/logout',null,'method');ywcCheck([405,'POST','{"ok":false,"reason":"METHOD_NOT_ALLOWED"}'],[$method['status'],$method['headers']['allow'][0]??null,trim($method['body'])],'safe method',$fail);foreach(['/health/live','/pilot/login','/pilot/assets/pilot.css']as$path){$g=ywcRequest($p,'GET',$path,null,'head-get-'.sha1($path));$h=ywcRequest($p,'HEAD',$path,null,'head-head-'.sha1($path));$expectedHeaders=$g['headers'];unset($expectedHeaders['date'],$expectedHeaders['connection'],$expectedHeaders['set-cookie']);$actualHeaders=$h['headers'];unset($actualHeaders['date'],$actualHeaders['connection'],$actualHeaders['set-cookie']);ywcCheck([$g['status'],'',(string)strlen($g['body']),$expectedHeaders],[$h['status'],$h['body'],$h['headers']['content-length'][0]??null,$actualHeaders],'HEAD '.$path,$fail);} $hostFacts=ywcFacts($fixture->db);$hostFiles=ywcPrivate($env);foreach(['rejected.invalid','bad host']as$badHost){$bad=ywcRequest($p,'GET','/pilot/login',$badHost,'host-'.sha1($badHost));$encoded=json_encode($bad,JSON_THROW_ON_ERROR);ywcCheck([400,false,false,$hostFacts,$hostFiles],[$bad['status'],isset($bad['headers']['set-cookie']),str_contains($encoded,$badHost),ywcFacts($fixture->db),ywcPrivate($env)],'Host before all dependencies '.$badHost,$fail);}
 $missingHost=ywcRaw($p,"GET /pilot/login HTTP/1.0\r\nConnection: close\r\n\r\n");ywcCheck([400,false],[$missingHost['status'],isset($missingHost['headers']['set-cookie'])],'missing Host rejected',$fail);
 foreach($contract['routes']as$route){[$case,$method,$path,$status,$location]=$route;$allow=$route[5]??null;$r=ywcRequest($p,$method,$path,null,$case);ywcCheck([$status,$location,$allow],[$r['status'],$r['headers']['location'][0]??null,$r['headers']['allow'][0]??null],"route contract $case",$fail);}
 foreach($contract['assets']as$asset=>$expected){[$hash,$type,$cache]=$expected;$case='asset-'.sha1($asset);$r=ywcRequest($p,'GET','/pilot/assets/'.$asset,null,$case);ywcCheck([200,$hash,$cache,$type,'nosniff','same-origin'],[$r['status'],hash('sha256',$r['body']),$r['headers']['cache-control'][0]??null,$r['headers']['content-type'][0]??null,$r['headers']['x-content-type-options'][0]??null,$r['headers']['cross-origin-resource-policy'][0]??null],'asset contract '.$asset,$fail);if($asset==='checklist-sw.js')ywcCheck('/pilot/',$r['headers']['service-worker-allowed'][0]??null,'service worker scope',$fail);}usleep(50000);$rows=array_values(array_filter(explode("\n",trim((string)file_get_contents($log)))));ywcCheck($GLOBALS['ywc_requests'],count($rows),'include row per request',$fail);$legacy=[];$identified=[];foreach($rows as$row){$entry=json_decode($row,true,flags:JSON_THROW_ON_ERROR);$identity=[$entry['case'],$entry['method'],$entry['path']];if($entry['case']!==null)$identified[$entry['case']]=$identity;foreach($entry['files']as$file)if(str_contains($file,'/rapid-pilot/'))$legacy[]=['request'=>$identity,'file'=>$file];}$expectedIdentities=[];foreach($contract['routes']as$route)$expectedIdentities[$route[0]]=[$route[0],$route[1],$route[2]];foreach(array_keys($contract['assets'])as$asset){$case='asset-'.sha1($asset);$expectedIdentities[$case]=[$case,'GET','/pilot/assets/'.$asset];}foreach($expectedIdentities as$case=>$identity)ywcCheck($identity,$identified[$case]??null,'exact attributable include row '.$case,$fail);ywcCheck(count($expectedIdentities),count(array_intersect(array_keys($expectedIdentities),array_keys($identified))),'unique attributable inventory rows',$fail);ywcCheck([],$legacy,'no rapid include per identified request',$fail);ywcCheck($facts,ywcFacts($fixture->db),'whole DB unchanged after public matrix',$fail);ywcCheck(ywcWithoutSessionPaths($private),ywcWithoutSessionPaths(ywcPrivate($env)),'non-session private paths stable',$fail);ywcStop($server);
 $poison=array_replace($env,['FMONITOR_DB_PORT'=>'0','FMONITOR_YII_SESSION_PATH'=>$sandbox.'/absent-yii','FMONITOR_ARTIFACT_STORAGE_ROOT'=>$sandbox.'/absent-artifacts']);$server=ywcStart($root,$poison);$poisoned=ywcRequest($server['port'],'GET','/pilot/login','rejected.invalid','host-before-poison');ywcCheck([400,false],[$poisoned['status'],isset($poisoned['headers']['set-cookie'])],'Host rejection precedes unavailable DB/session/artifacts',$fail);ywcStop($server);
 $invalid=array_replace($env,['FMONITOR_DB_PORT'=>'0','FMONITOR_DB_PASSWORD'=>'CUTOVER_SECRET_76']);$server=ywcStart($root,$invalid);$live=ywcRequest($server['port'],'GET','/health/live');ywcCheck([200,"{\"ok\":true}\n",false],[$live['status'],$live['body'],isset($live['headers']['set-cookie'])],'live invalid DB',$fail);ywcStop($server);
 ywcFailureCase($root,$fixture,$env,['FMONITOR_DB_PORT'=>'0','FMONITOR_DB_PASSWORD'=>'CUTOVER_SECRET_76'],'/health/ready','database readiness failure',$fail);
 ywcFailureCase($root,$fixture,$env,['FMONITOR_DB_PORT'=>'0','FMONITOR_DB_PASSWORD'=>'CUTOVER_SECRET_76'],'/pilot/login','database page failure',$fail);
 ywcFailureCase($root,$fixture,$env,['FMONITOR_YII_COOKIE_VALIDATION_KEY'=>''],'/pilot/login','missing startup config',$fail);
 ywcFailureCase($root,$fixture,$env,['FMONITOR_YII_SESSION_PATH'=>$sandbox.'/missing-session'],'/pilot/login','session open failure',$fail);
 ywcFailureCase($root,$fixture,$env,['FMONITOR_ARTIFACT_STORAGE_ROOT'=>$sandbox.'/missing-artifacts'],'/health/ready','artifact readiness failure',$fail);
 ywcFailureCase($root,$fixture,$env,['FMONITOR_ARTIFACT_STORAGE_ROOT'=>$sandbox.'/missing-artifacts'],'/pilot/objects/4512','artifact page failure',$fail);
 $faultMarker=$tmp.'/ywc-session-close-'.$token.'.log';ywcFailureCase($root,$fixture,$env,['FMONITOR_TEST_SESSION_FAULT'=>'write','FMONITOR_TEST_SESSION_FAULT_MARKER'=>$faultMarker],'/pilot/login','durable session close failure',$fail,$root.'/tests/Support/Yii2SessionFaultPrepend.php');ywcCheck("write\n",is_file($faultMarker)?file_get_contents($faultMarker):'','durable close fault reached',$fail);if(is_file($faultMarker))unlink($faultMarker);
 assertSameValue([], $fail, YWC_RED.': complete public matrix');echo"PASS: YII2-PRODUCTION-WEB-CUTOVER-001 single runtime\n";
}finally{ywcStop($server);$fixture->close();if(is_file($log))unlink($log);}
