<?php
declare(strict_types=1);
use FMonitor2\RuntimeRestore\StandBackupFilesystem;
require dirname(__DIR__,2).'/vendor/autoload.php';
$args=array_slice($argv,1);$mode=$args[0]??'';$package=null;foreach($args as$arg)if(str_starts_with($arg,'--authorization='))$package=substr($arg,16);
if(!in_array($mode,['roundtrip','rollback'],true)||end($args)!=='--interactive=0'){echo"{\"ok\":false,\"reason\":\"CONFIGURATION_INVALID\"}\n";exit(64);}
$env=$mode==='rollback'?'FMONITOR_DISPOSABLE_ROLLBACK_AUTHORIZATION':'FMONITOR_DISPOSABLE_REHEARSAL_AUTHORIZATION';if($package===null||getenv($env)!==$package){echo"{\"ok\":false,\"reason\":\"ACTION_NOT_AUTHORIZED\"}\n";exit(77);}
try{$real=realpath($package);if($real===false||$real!==$package||is_link($package))throw new RuntimeException();$bytes=StandBackupFilesystem::regularBytes($real);$p=json_decode($bytes,true,512,JSON_THROW_ON_ERROR);if(StandBackupFilesystem::canonical($p)!==$bytes)throw new RuntimeException();$wanted=$mode==='rollback'?['candidate_failure','known_good_bundle_digest','manifest','rollback_authorization','rollback_operation_id','version']:['backup_authorization','backup_operation_id','expected_bundle_digest','manifest','restore_authorization','restore_operation_id','version'];$keys=array_keys($p);sort($keys);sort($wanted);if($keys!==$wanted||$p['version']!==1)throw new RuntimeException();foreach($p as$k=>$v)if(str_contains($k,'password')||str_contains($k,'secret'))throw new RuntimeException();$yii=dirname(__DIR__,2).'/bin/yii';$run=static function(array$a):array{$pipes=[];$x=proc_open($a,[0=>['file','/dev/null','r'],1=>['pipe','w'],2=>['pipe','w']],$pipes);if(!is_resource($x))throw new RuntimeException();$out=stream_get_contents($pipes[1]);fclose($pipes[1]);stream_get_contents($pipes[2]);fclose($pipes[2]);$code=proc_close($x);$json=json_decode($out,true,512,JSON_THROW_ON_ERROR);return[$code,$json];};
 if($mode==='roundtrip'){[$c,$created]=$run(['php',$yii,'stand-backup/create','--manifest='.$p['manifest'],'--operation-id='.$p['backup_operation_id'],'--authorization='.$p['backup_authorization'],'--interactive=0']);if($c!==0||$created['bundle_digest']!==$p['expected_bundle_digest'])throw new RuntimeException();[$c,$verified]=$run(['php',$yii,'stand-backup/verify','--manifest='.$p['manifest'],'--operation-id='.$p['backup_operation_id'],'--bundle-digest='.$p['expected_bundle_digest'],'--interactive=0']);if($c!==0||($verified['outcome']??null)!=='BACKUP_VERIFIED')throw new RuntimeException();[$c,$restored]=$run(['php',$yii,'stand-restore/run','--manifest='.$p['manifest'],'--bundle-digest='.$p['expected_bundle_digest'],'--operation-id='.$p['restore_operation_id'],'--authorization='.$p['restore_authorization'],'--interactive=0']);if($c!==0||($restored['outcome']??null)!=='RESTORE_VERIFIED')throw new RuntimeException();echo StandBackupFilesystem::canonical(['ok'=>true,'outcome'=>'ROUNDTRIP_VERIFIED','backup_operation_id'=>$p['backup_operation_id'],'restore_operation_id'=>$p['restore_operation_id'],'bundle_digest'=>$p['expected_bundle_digest']]);exit(0);}
 $failureBytes=StandBackupFilesystem::regularBytes(realpath($p['candidate_failure'])?:'');$failure=json_decode($failureBytes,true,512,JSON_THROW_ON_ERROR);if(StandBackupFilesystem::canonical($failure)!==$failureBytes||($failure['outcome']??null)!=='FAILED'||!isset($failure['operation_id']))throw new RuntimeException();[$c,$verified]=$run(['php',$yii,'stand-backup/verify','--manifest='.$p['manifest'],'--operation-id='.$p['rollback_operation_id'],'--bundle-digest='.$p['known_good_bundle_digest'],'--interactive=0']);if($c!==0)throw new RuntimeException();[$c,$restored]=$run(['php',$yii,'stand-restore/run','--manifest='.$p['manifest'],'--bundle-digest='.$p['known_good_bundle_digest'],'--operation-id='.$p['rollback_operation_id'],'--authorization='.$p['rollback_authorization'],'--interactive=0']);if($c!==0||($restored['outcome']??null)!=='RESTORE_VERIFIED'||$failure['operation_id']===$p['rollback_operation_id'])throw new RuntimeException();echo StandBackupFilesystem::canonical(['ok'=>true,'outcome'=>'ROLLBACK_VERIFIED','candidate_operation_id'=>$failure['operation_id'],'rollback_operation_id'=>$p['rollback_operation_id'],'candidate_outcome'=>'FAILED_RETAINED','bundle_digest'=>$p['known_good_bundle_digest']]);exit(0);
}catch(Throwable){echo"{\"ok\":false,\"outcome\":\"OUTCOME_UNKNOWN\"}\n";exit(70);}
