<?php
declare(strict_types=1);
require dirname(__DIR__).'/bootstrap.php';require dirname(__DIR__,2).'/app/autoload.php';
use FMonitor2\Jobs\{WeeklyFkrRecipientDirectory,WeeklyFkrReportSource,WeeklyFkrOpeningEligibility,WeeklyFkrReportBuilder,WeeklyFkrReportRenderer};

if(getenv('FMONITOR_FIXTURE_REACHABILITY')==='weekly-report-fixture'){assertSameValue([40,0,55,5],[40,0,55,5],'independent progress fixture');echo "FIXTURE_REACHABLE: weekly-report-fixture\n";exit(0);}
assertSameValue(true,interface_exists(WeeklyFkrRecipientDirectory::class)&&interface_exists(WeeklyFkrReportSource::class)&&interface_exists(WeeklyFkrOpeningEligibility::class)&&class_exists(WeeklyFkrReportBuilder::class)&&class_exists(WeeklyFkrReportRenderer::class),'INTENTIONAL_RED: WEEKLY-FKR-ATTENTION-EMAIL-001 typed public report seams exist');
$recipients=['leader-a'=>['active'=>true,'role'=>'fkr_manager','permissions'=>['objects.read'],'email'=>'a@example.test'],'leader-b'=>['active'=>true,'role'=>'fkr_manager','permissions'=>['objects.read'],'email'=>'b@example.test'],'disabled'=>['active'=>false,'role'=>'fkr_manager','permissions'=>['objects.read'],'email'=>'off@example.test'],'no-permission'=>['active'=>true,'role'=>'fkr_manager','permissions'=>[],'email'=>'none@example.test'],'missing-email'=>['active'=>true,'role'=>'fkr_manager','permissions'=>['objects.read'],'email'=>'']];
$objects=[
 ['id'=>'A-1','registrationNumber'=>'REG-002','address'=>'Ленина, 2 <секция>','openingPlanDate'=>'2026-09-21','openingCompleted'=>false,'openingStatus'=>'Основание не готово','openingReasons'=>['Нет подписанного оригинала'],'closingPlanDate'=>null,'closingCompleted'=>false,'work'=>null,'documents'=>null,'progressStart'=>null,'progressEnd'=>null,'violations'=>[]],
 ['id'=>'A-2','registrationNumber'=>'REG-001','address'=>'Ленина, 1','openingPlanDate'=>null,'openingCompleted'=>true,'openingStatus'=>'Открыт','openingReasons'=>[],'closingPlanDate'=>'2026-09-27','closingCompleted'=>false,'work'=>80,'documents'=>0,'progressStart'=>['work'=>40,'documents'=>0],'progressEnd'=>['work'=>55,'documents'=>5],'violations'=>[]],
 ['id'=>'A-3','registrationNumber'=>'REG-003','address'=>'Арбат, 3','openingPlanDate'=>null,'openingCompleted'=>true,'openingStatus'=>'Открыт','openingReasons'=>[],'closingPlanDate'=>'2026-09-14','closingCompleted'=>false,'work'=>85,'documents'=>10,'progressStart'=>['work'=>85,'documents'=>null],'progressEnd'=>['work'=>85,'documents'=>10],'violations'=>['Не закрыто нарушение Н-7']],
 ['id'=>'A-4','registrationNumber'=>'REG-004','address'=>'Арбат, 4','openingPlanDate'=>null,'openingCompleted'=>true,'openingStatus'=>'Открыт','openingReasons'=>[],'closingPlanDate'=>'2026-09-21','closingCompleted'=>false,'work'=>85,'documents'=>15,'progressStart'=>['work'=>85,'documents'=>15],'progressEnd'=>['work'=>85,'documents'=>15],'violations'=>[]],
 ['id'=>'A-5','registrationNumber'=>'REG-005','address'=>'Арбат, 5','openingPlanDate'=>null,'openingCompleted'=>true,'openingStatus'=>'Открыт','openingReasons'=>[],'closingPlanDate'=>'2026-09-25','closingCompleted'=>false,'work'=>null,'documents'=>null,'progressStart'=>null,'progressEnd'=>null,'violations'=>[]],
 ['id'=>'A-6','registrationNumber'=>'REG-006','address'=>'Арбат, 6','openingPlanDate'=>null,'openingCompleted'=>true,'openingStatus'=>'Открыт','openingReasons'=>[],'closingPlanDate'=>'2026-09-26','closingCompleted'=>false,'work'=>85,'documents'=>15,'progressStart'=>['work'=>85,'documents'=>15],'progressEnd'=>['work'=>85,'documents'=>15],'violations'=>['Нарушение Н-8']],
 ['id'=>'A-7','registrationNumber'=>'REG-007','address'=>'Арбат, 7','openingPlanDate'=>'2026-09-20','openingCompleted'=>false,'openingStatus'=>'Не открыт','openingReasons'=>['Нет основания'],'closingPlanDate'=>null,'closingCompleted'=>false,'work'=>null,'documents'=>null,'progressStart'=>null,'progressEnd'=>null,'violations'=>[]],
 ['id'=>'A-8','registrationNumber'=>'REG-008','address'=>'Арбат, 8','openingPlanDate'=>'2026-09-28','openingCompleted'=>false,'openingStatus'=>'Не открыт','openingReasons'=>['Нет основания'],'closingPlanDate'=>null,'closingCompleted'=>false,'work'=>null,'documents'=>null,'progressStart'=>null,'progressEnd'=>null,'violations'=>[]],
 ['id'=>'A-9','registrationNumber'=>'REG-009','address'=>'Арбат, 9','openingPlanDate'=>'2026-09-23','openingPlanDateOriginal'=>'2026-10-05','openingPlanCorrectedAt'=>'2026-09-20T12:00:00.000000Z','openingCompleted'=>false,'openingStatus'=>'Исправленный срок','openingReasons'=>[],'closingPlanDate'=>null,'closingCompleted'=>false,'work'=>null,'documents'=>null,'progressStart'=>null,'progressEnd'=>null,'violations'=>[]],
 ['id'=>'A-10','registrationNumber'=>'REG-010','address'=>'Арбат, 10','openingPlanDate'=>null,'openingCompleted'=>true,'openingStatus'=>'Открыт','openingReasons'=>[],'closingPlanDate'=>'2026-09-24','closingCompleted'=>false,'work'=>70,'documents'=>5,'progressStart'=>['work'=>30,'documents'=>0],'progressEnd'=>['work'=>70,'documents'=>5],'progressHistory'=>[['at'=>'2026-09-14','work'=>40,'documents'=>0],['at'=>'2026-09-15','correctsAt'=>'2026-09-14','work'=>30,'documents'=>0],['at'=>'2026-09-20','work'=>70,'documents'=>5]],'violations'=>[]],
 ['id'=>'A-11','registrationNumber'=>'REG-011','address'=>'Арбат, 11','openingPlanDate'=>'2026-09-10','openingCompleted'=>true,'openingStatus'=>'Открыт','openingReasons'=>[],'closingPlanDate'=>'2026-09-12','closingCompleted'=>true,'work'=>85,'documents'=>15,'progressStart'=>['work'=>85,'documents'=>15],'progressEnd'=>['work'=>85,'documents'=>15],'violations'=>['Историческое закрытое нарушение']],
];
$objectsBefore=hash('sha256',serialize($objects));
$directory=new class($recipients)implements WeeklyFkrRecipientDirectory{private array$rows;public function __construct(array&$rows){$this->rows=&$rows;}public function recipient(string$id):?array{return$this->rows[$id]??null;}public function fingerprint():string{return hash('sha256',serialize($this->rows));}};
$source=new class($objects)implements WeeklyFkrReportSource{public array$calls=[];public function __construct(private array$rows){}public function allObjectsAsOf(string$start,string$end,string$generatedAt):array{$this->calls[]=[$start,$end,$generatedAt];return$this->rows;}public function fingerprint():string{return hash('sha256',serialize($this->rows));}};
$eligibility=new class implements WeeklyFkrOpeningEligibility{public array$calls=[];public function reasons(string$objectId,string$at):array{$this->calls[]=[$objectId,$at];return$objectId==='A-1'?['Нет подписанного оригинала']:[];}public function fingerprint():string{return hash('sha256',serialize($this->calls));}};
$seamBefore=[$directory->fingerprint(),$source->fingerprint()];
$builder=new WeeklyFkrReportBuilder($directory,$source,$eligibility);
$report=$builder->build('leader-a','2026-09-21T06:00:00.000000Z','https://fmonitor.example.test');
assertSameValue(['2026-09-21','2026-09-27','2026-09-14','2026-09-20'],[$report['periods']['planStart'],$report['periods']['planEnd'],$report['periods']['progressStart'],$report['periods']['progressEnd']],'A1 exact report periods');
assertSameValue(['A-1','A-9'],array_column($report['sections']['plannedOpenings'],'objectId'),'A2/A4 current-week openings include corrected as-of date, exclude prior/next week');
assertSameValue(['A-4','A-10','A-5','A-6','A-2'],array_column($report['sections']['plannedClosings'],'objectId'),'A3/A4 stable date then registration sorting');
$progressA2=array_values(array_filter($report['sections']['progress'],static fn(array$row):bool=>$row['objectId']==='A-2'))[0];assertSameValue(['A-2',40,60,20],[$progressA2['objectId'],$progressA2['totalStart'],$progressA2['totalEnd'],$progressA2['delta']],'A5 independently fixed 85/15 delta');
assertSameValue([40,55,0,5],[$progressA2['workStart'],$progressA2['workEnd'],$progressA2['documentsStart'],$progressA2['documentsEnd']],'A5 separate 85/15 values remain observable');
$corrected=array_values(array_filter($report['sections']['progress'],static fn(array$row):bool=>$row['objectId']==='A-10'))[0];assertSameValue([30,70,0,5,45],[$corrected['workStart'],$corrected['workEnd'],$corrected['documentsStart'],$corrected['documentsEnd'],$corrected['delta']],'A5 correcting fact replaces prior boundary value without erasing history');
assertSameValue(['A-3',7],[$report['sections']['overdue'][0]['objectId'],$report['sections']['overdue'][0]['daysLate']],'A6 old deadline exact calendar days');
assertSameValue(true,in_array('A-7',array_column($report['sections']['overdue'],'objectId'),true)&&!in_array('A-4',array_column($report['sections']['overdue'],'objectId'),true),'A6 no lookback cutoff and today is not overdue');
assertSameValue(false,in_array('A-11',array_column($report['sections']['overdue'],'objectId'),true)||in_array('A-11',array_column($report['sections']['attention'],'objectId'),true),'A6/A7 completed opening and closing are excluded despite old dates/history');
assertSameValue(['A-1','A-10','A-5','A-6','A-2'],array_column($report['sections']['attention'],'objectId'),'A7 attention sorted by date and includes basis/readiness/UNKNOWN/violation; ready today and next week excluded');
assertSameValue(['Работы: 80 из 85','Документы: 0 из 15'],$report['sections']['attention'][4]['reasons'],'A7 exact closing readiness reasons/current values');
assertSameValue(['Недостаточно данных для оценки'],$report['sections']['attention'][2]['reasons'],'A5/A7 UNKNOWN is explicit, not zero');assertSameValue(['Нарушение Н-8'],$report['sections']['attention'][3]['reasons'],'A7 active blocking violation remains visible');
assertSameValue(null,$report['sections']['progress'][1]['delta'],'A5 UNKNOWN boundary never produces numeric delta');
$renderer=new WeeklyFkrReportRenderer();$message=$renderer->render($report);
foreach(['Плановые открытия','Плановые закрытия','Прогресс за прошедшую неделю','Просрочка','Обратить внимание','Данных за период нет']as$label)assertSameValue(true,str_contains($message['html'],$label)&&str_contains($message['text'],$label),"A3 both bodies contain {$label}");
assertSameValue(true,str_contains($message['html'],'data-report-summary="counts"'),'A3 compact summary is the first report block');
foreach(['plannedOpenings'=>2,'plannedClosings'=>5,'progress'=>3,'overdue'=>2,'attention'=>5]as$key=>$count)assertSameValue(true,str_contains($message['html'],'data-summary-key="'.$key.'" data-summary-count="'.$count.'"'),"A3 summary exposes exact {$key} count");
assertSameValue(true,str_contains($message['text'],"Сводка: Открытия — 2 · Закрытия — 5 · Прогресс — 3 · Просрочка — 2 · Внимание — 5"),'A3 text fallback starts with the same compact summary');
assertSameValue([['2026-09-14','2026-09-20','2026-09-21T06:00:00.000000Z']],$source->calls,'A2/A5 one typed native-source call receives exact as-of boundaries');
$leaderB=$builder->build('leader-b','2026-09-21T06:00:00.000000Z','https://fmonitor.example.test');foreach(array_keys($report['sections'])as$section)assertSameValue(array_column($report['sections'][$section],'objectId'),array_column($leaderB['sections'][$section],'objectId'),"A2 both leaders receive identical {$section} object identities");
assertSameValue(true,str_contains($message['html'],'Ленина, 2 &lt;секция&gt;')&&str_contains($message['html'],'https://fmonitor.example.test/pilot/object/A-1'),'A3 escaped value and trusted absolute link');
foreach(['<img','<picture','<svg','background-image','data:','<script','<link','@font-face','url(']as$forbidden)assertSameValue(false,str_contains(strtolower($message['html']),strtolower($forbidden)),"A3 image/external resource forbidden: {$forbidden}");
assertSameValue(true,substr_count($message['html'],'role="presentation"')>=2&&str_contains($message['html'],'max-width:680px')&&str_contains($message['html'],'Arial, Helvetica, sans-serif'),'A3 Outlook-safe tables, bounded canvas and system font');
$renderDir=sys_get_temp_dir().'/weekly-mail-'.bin2hex(random_bytes(5));mkdir($renderDir,0700);file_put_contents($renderDir.'/message.html',$message['html']);file_put_contents($renderDir.'/message.txt',$message['text']);$linkIds=['A-1'=>'REG-002','A-2'=>'REG-001','A-3'=>'REG-003','A-4'=>'REG-004','A-5'=>'REG-005','A-6'=>'REG-006','A-7'=>'REG-007','A-9'=>'REG-009','A-10'=>'REG-010'];$links=[];foreach($linkIds as$id=>$label)$links[$label]='https://fmonitor.example.test/pilot/object/'.$id;$parity=['playwright'=>getenv('FMONITOR_TEST_PLAYWRIGHT_MODULE')?:dirname(__DIR__,3).'/shlz-ui/node_modules/playwright','sections'=>['plannedOpenings'=>['A-1','A-9'],'plannedClosings'=>['A-4','A-10','A-5','A-6','A-2'],'progress'=>['A-2','A-3','A-10'],'overdue'=>['A-3','A-7'],'attention'=>['A-1','A-10','A-5','A-6','A-2']],'values'=>['Ленина, 2 <секция>','Ленина, 1','Арбат, 3','Арбат, 4','Арбат, 5','Арбат, 6','Арбат, 7','Арбат, 9','Арбат, 10','REG-001','REG-002','REG-003','REG-004','REG-005','REG-006','REG-007','REG-009','REG-010','Нет подписанного оригинала','Работы: 80 из 85','Документы: 0 из 15','Нарушение Н-8','Недостаточно данных для оценки','Работы 40→55 из 85','Документы 0→5 из 15','+20 п.п.','7 календарных дней','Сформировано: 21.09.2026 09:00 Europe/Moscow'],'links'=>$links];file_put_contents($renderDir.'/parity.json',json_encode($parity,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR));$pipes=[];$process=proc_open(['node',__DIR__.'/weekly_report_browser.mjs',$renderDir.'/message.html',$renderDir.'/message.txt',$renderDir.'/parity.json',$renderDir],[0=>['file','/dev/null','r'],1=>['pipe','w'],2=>['pipe','w']],$pipes,dirname(__DIR__,2));if(!is_resource($process))throw new TestFailure('SETUP_FAILURE browser verifier');$stdout=stream_get_contents($pipes[1]);$stderr=stream_get_contents($pipes[2]);fclose($pipes[1]);fclose($pipes[2]);assertSameValue([0,''],[proc_close($process),$stderr],'A3 680px/320px Outlook/web browser verifier');assertSameValue(true,is_file($renderDir.'/desktop.png')&&is_file($renderDir.'/narrow.png'),'A3 both render captures produced');foreach(glob($renderDir.'/*')?:[]as$file)unlink($file);rmdir($renderDir);
assertSameValue(false,str_contains(mb_strtolower(implode(' ',array_column($report['sections']['attention'],'label'))),'просроч'),'A7 attention never labelled overdue');
$dense=$report;foreach($dense['sections']as$name=>$rows){$dense['sections'][$name]=array_fill(0,1000,$rows[0]);}$denseMessage=$renderer->render($dense);$denseBytes=strlen($denseMessage['subject'].$denseMessage['html'].$denseMessage['text']);assertSameValue(true,$denseBytes*2<5242880,'A11 measured five-section 5x1000-row fixture stays below half 5 MiB limit');
try{$builder->build('disabled','2026-09-21T06:00:00.000000Z','https://fmonitor.example.test');throw new TestFailure('disabled recipient must reject');}catch(RuntimeException$e){assertSameValue('RECIPIENT_INELIGIBLE',$e->getMessage(),'A2 stable ineligible result');}
assertSameValue($seamBefore,[$directory->fingerprint(),$source->fingerprint()],'A12 recipient/source seam owners remain unchanged by build/render before test-owned negative-fixture additions');
foreach([['wrong-role',['active'=>true,'role'=>'employee','email'=>'wrong@example.test','scope'=>['A-1']]],['bad-email',['active'=>true,'role'=>'fkr_manager','email'=>'invalid','scope'=>['A-1']]]]as[$id,$value]){$recipients[$id]=$value;try{$builder->build($id,'2026-09-21T06:00:00.000000Z','https://fmonitor.example.test');throw new TestFailure("{$id} must reject");}catch(RuntimeException$e){assertSameValue('RECIPIENT_INELIGIBLE',$e->getMessage(),"A2 {$id} rejected");}}
foreach(['no-permission','missing-email']as$id){try{$builder->build($id,'2026-09-21T06:00:00.000000Z','https://fmonitor.example.test');throw new TestFailure("{$id} must reject");}catch(RuntimeException$e){assertSameValue('RECIPIENT_INELIGIBLE',$e->getMessage(),"A2 {$id} rejected");}}
assertSameValue($objectsBefore,hash('sha256',serialize($objects)),'A12 connected source fixtures remain byte-equivalent after two builds and rendering');
echo "PASS: WEEKLY-FKR-ATTENTION-EMAIL-001 scoped report and image-free Outlook/web render\n";
