<?php
declare(strict_types=1);
require dirname(__DIR__) . '/bootstrap.php';
/** HARNESS-OTIZ-ISOLATION-001 v0.1 */

function hoiConfig():array{$out=[];foreach(['HOST'=>'127.0.0.1','PORT'=>'23306','NAME'=>'fmonitor2_test','USER'=>'fmonitor2_test','PASSWORD'=>'fmonitor2_test_local'] as $s=>$default){$v=getenv("FMONITOR_VERIFY_DB_$s");$t=getenv("FMONITOR_TEST_DB_$s");$out[$s]=$v!==false&&$v!==''?$v:($t!==false&&$t!==''?$t:$default);}return$out;}
function hoiDb(array$c):mysqli{try{$d=new mysqli($c['HOST'],$c['USER'],$c['PASSWORD'],$c['NAME'],(int)$c['PORT']);$d->set_charset('utf8mb4');return$d;}catch(mysqli_sql_exception$e){fwrite(STDERR,"SETUP_FAILURE: disposable verification database is unavailable: {$e->getMessage()}\n");exit(2);}}
function hoiRun(string$root,array$c):array{$env=getenv();if(!is_array($env))$env=$_ENV;foreach($c as$s=>$v)$env["FMONITOR_VERIFY_DB_$s"]=(string)$v;$p=proc_open([PHP_BINARY,'rapid-pilot/verify-otiz-workflow.php'],[0=>['pipe','r'],1=>['pipe','w'],2=>['pipe','w']],$pipes,$root,$env);if(!is_resource($p))return['status'=>null,'stdout'=>'','stderr'=>'SETUP_FAILURE: verifier process did not start'];fclose($pipes[0]);$stdout=stream_get_contents($pipes[1]);$stderr=stream_get_contents($pipes[2]);fclose($pipes[1]);fclose($pipes[2]);return['status'=>proc_close($p),'stdout'=>$stdout,'stderr'=>$stderr];}
function hoiLeaks(mysqli$d):array{$r=$d->query("SELECT TABLE_NAME FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME LIKE 'otiz\\_verify\\_%' ESCAPE '\\\\' ORDER BY TABLE_NAME");return array_column($r->fetch_all(MYSQLI_ASSOC),'TABLE_NAME');}
function hoiDrop(mysqli$d,array$tables):void{foreach($tables as$t)$d->query('DROP TABLE IF EXISTS `'.str_replace('`','``',$t).'`');}
function hoiState(mysqli$d,array$tables):array{$out=[];foreach($tables as$t){$q='`'.str_replace('`','``',$t).'`';try{$definition=$d->query("SHOW CREATE TABLE $q")->fetch_row()[1];$rows=$d->query("SELECT * FROM $q")->fetch_all(MYSQLI_ASSOC);$out[$t]=['exists'=>true,'sha256'=>hash('sha256',serialize([$definition,$rows])),'error'=>null];}catch(mysqli_sql_exception$e){$out[$t]=['exists'=>false,'sha256'=>null,'error'=>$e->getMessage()];}}return$out;}
function hoiMilestonePositions(string$stdout,array$milestones):array{$positions=[];$offset=0;foreach($milestones as$milestone){$at=mb_strpos($stdout,$milestone,$offset);$positions[$milestone]=$at;$offset=$at===false?$offset:$at+mb_strlen($milestone);}return$positions;}
function hoiNativeDecoys(mysqli$d,array&$owned):array{
 $tables=['fm2_pilot_object_details','fm2_checklist_operation_installers','fm2_checklist_template_snapshots','fm2_checklist_operations','fm2_order_installers','fm2_assignment_orders','fm_maintable','fm2_migration_classification_provenance','fm2_installation_cases'];
 $definitions=[
  'fm2_installation_cases'=>'CREATE TABLE `fm2_installation_cases`(id BIGINT PRIMARY KEY,legacy_installation_object_id BIGINT,process_state VARCHAR(40),actual_start_date DATE)',
  'fm2_migration_classification_provenance'=>'CREATE TABLE `fm2_migration_classification_provenance`(output_kind VARCHAR(40),output_id BIGINT,legacy_object_id BIGINT,category VARCHAR(40))',
  'fm_maintable'=>'CREATE TABLE `fm_maintable`(id BIGINT PRIMARY KEY,regnumber VARCHAR(40),ordadr_address VARCHAR(100))',
  'fm2_assignment_orders'=>'CREATE TABLE `fm2_assignment_orders`(id BIGINT PRIMARY KEY,installation_case_id BIGINT,status VARCHAR(40),version_no INT,order_date DATE,planned_finish_date_snapshot DATE,pto_act_date_snapshot DATE NULL)',
  'fm2_order_installers'=>'CREATE TABLE `fm2_order_installers`(assignment_order_id BIGINT,installer_tab_id BIGINT,fio_snapshot VARCHAR(80),position_snapshot VARCHAR(80))',
  'fm2_checklist_template_snapshots'=>'CREATE TABLE `fm2_checklist_template_snapshots`(id BIGINT PRIMARY KEY,content_sha256 CHAR(64),payload_json LONGTEXT)',
  'fm2_checklist_operations'=>'CREATE TABLE `fm2_checklist_operations`(id BIGINT AUTO_INCREMENT PRIMARY KEY,installation_case_id BIGINT,client_operation_id CHAR(36),operation_type VARCHAR(40),item_id INT,device_time VARCHAR(40),server_received_at VARCHAR(40),template_snapshot_id BIGINT,template_content_sha256 CHAR(64))',
  'fm2_checklist_operation_installers'=>'CREATE TABLE `fm2_checklist_operation_installers`(client_operation_id CHAR(36),installer_tab_id BIGINT)',
  'fm2_pilot_object_details'=>'CREATE TABLE `fm2_pilot_object_details`(object_id BIGINT PRIMARY KEY,content_sha256 CHAR(64),payload_json LONGTEXT,captured_at VARCHAR(40))',
 ];
 $preexisting=[];foreach($definitions as$t=>$sql){$exists=(int)$d->query("SELECT COUNT(*) n FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='".$d->real_escape_string($t)."'")->fetch_assoc()['n']!==0;if($exists){$preexisting[]=$t;continue;}$d->query($sql);$owned[]=$t;}
 if($preexisting!==[])return['tables'=>$tables,'owned'=>$owned];
 $th=hash('sha256','ambient-native-decoy-template');$template=$d->real_escape_string(json_encode(['definitions'=>[['id'=>1,'share'=>100]]],JSON_THROW_ON_ERROR));$card=json_encode(['fields'=>['floors'=>['raw'=>'5'],'weight'=>['raw'=>'320'],'pitmaterial'=>['display'=>'металлокаркас+стекло'],'lift_type'=>['display'=>'пассажирский']]],JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR);$cs=$d->real_escape_string($card);$ch=hash('sha256',$card);
 $d->query("INSERT INTO `fm2_installation_cases` VALUES(99001,99001,'working','2026-08-01')");$d->query("INSERT INTO `fm2_migration_classification_provenance` VALUES('operational_case',99001,99001,'native_candidate')");$d->query("INSERT INTO `fm_maintable` VALUES(99001,'DECOY-99001','Ambient native-looking decoy')");$d->query("INSERT INTO `fm2_assignment_orders` VALUES(99001,99001,'registered',1,'2026-08-01','2026-12-31',NULL)");$d->query("INSERT INTO `fm2_order_installers` VALUES(99001,99001,'Ambient Decoy Installer','Installer')");$d->query("INSERT INTO `fm2_checklist_template_snapshots` VALUES(99001,'$th','$template')");$d->query("INSERT INTO `fm2_checklist_operations`(installation_case_id,client_operation_id,operation_type,item_id,device_time,server_received_at,template_snapshot_id,template_content_sha256)VALUES(99001,'99999999-9999-4999-8999-999999999999','item_completed',1,'2026-08-15T10:00:00+03:00','2026-08-15T10:01:00+03:00',99001,'$th')");$d->query("INSERT INTO `fm2_checklist_operation_installers` VALUES('99999999-9999-4999-8999-999999999999',99001)");$d->query("INSERT INTO `fm2_pilot_object_details` VALUES(99001,'$ch','$cs','2026-08-01T10:00:00+03:00')");
 return['tables'=>$tables,'owned'=>$owned];
}

$root=dirname(__DIR__,2);$config=hoiConfig();$db=hoiDb($config);$unrelated='harness_otiz_isolation_decoy_'.bin2hex(random_bytes(6));$native=[];$ownedNative=[];$ownedPrivate=[];$injectedFailure=false;$unrelatedOwned=false;$milestones=['authorization rejects a user outside OTIZ','calculation creates a deterministic draft','open blockers prevent acceptance','blocker-free draft can be accepted','snapshot persists shared premium calculation version','accepted snapshot is immutable on repeated acceptance','reversal is append-only and idempotent','accepted export is a structurally valid XLSX ZIP package'];
try{
 $initial=hoiLeaks($db);if($initial!==[])throw new TestFailure('SETUP_FAILURE: private namespace must be clean before first run: '.json_encode($initial));
 $nativeFixture=hoiNativeDecoys($db,$ownedNative);$native=$nativeFixture['tables'];$db->query("CREATE TABLE `$unrelated`(decoy_key VARCHAR(40) PRIMARY KEY,decoy_value VARBINARY(255) NOT NULL)");$unrelatedOwned=true;$s=$db->prepare("INSERT INTO `$unrelated` VALUES(?,?)");$key='ambient-state';$value="unchanged\0binary\xffstate";$s->bind_param('ss',$key,$value);$s->execute();$decoys=array_merge([$unrelated],$native);$before=hoiState($db,$decoys);
 if(getenv('FMONITOR_HARNESS_OTIZ_FAIL_AFTER_FIXTURES')==='1')throw new RuntimeException('HARNESS_OTIZ_INJECTED_FAILURE');
 $first=hoiRun($root,$config);$leaks1=hoiLeaks($db);$ownedPrivate=array_merge($ownedPrivate,$leaks1);$after1=hoiState($db,$decoys);hoiDrop($db,$leaks1);$cleanBeforeSecond=hoiLeaks($db);$second=hoiRun($root,$config);$leaks2=hoiLeaks($db);$ownedPrivate=array_merge($ownedPrivate,$leaks2);$after2=hoiState($db,$decoys);$hash1=hash('sha256',$first['stdout']);$hash2=hash('sha256',$second['stdout']);$normalizedDecoys=$after2;$normalizedDecoys['harness_otiz_isolation_decoy']=$normalizedDecoys[$unrelated];$normalizedDecoys['harness_otiz_isolation_decoy']['sha256']=hash('sha256',serialize(['stable-decoy-definition',$key,$value]));unset($normalizedDecoys[$unrelated]);ksort($normalizedDecoys);$decoyHash=hash('sha256',serialize($normalizedDecoys));$milestonePositions=['first'=>hoiMilestonePositions($first['stdout'],$milestones),'second'=>hoiMilestonePositions($second['stdout'],$milestones)];$evidence=json_encode(['first'=>['status'=>$first['status'],'stdoutSha256'=>$hash1,'stderr'=>$first['stderr']],'second'=>['status'=>$second['status'],'stdoutSha256'=>$hash2,'stderr'=>$second['stderr']],'milestonePositions'=>$milestonePositions,'cleanBeforeSecond'=>$cleanBeforeSecond,'leaksAfterFirst'=>$leaks1,'leaksAfterSecond'=>$leaks2,'decoySha256'=>$decoyHash],JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR);
 assertSameValue([],$cleanBeforeSecond,"SETUP_FAILURE: private namespace must be clean before second run; evidence=$evidence");assertSameValue($before,$after1,"First run preserves all ambient decoys; evidence=$evidence");assertSameValue($before,$after2,"Second run preserves all ambient decoys; evidence=$evidence");assertSameValue($first['stdout'],$second['stdout'],"Both runs emit the same transcript; evidence=$evidence");foreach($milestonePositions as$run=>$positions)foreach($positions as$milestone=>$position)assertSameValue(true,$position!==false,"RED_ASSERTION: $run verifier transcript contains ordered harness milestone `$milestone`; evidence=$evidence");assertSameValue(0,$first['status'],"RED_ASSERTION: first verifier behavior run must exit 0; evidence=$evidence");assertSameValue(0,$second['status'],"RED_ASSERTION: second verifier behavior run must exit 0; evidence=$evidence");assertSameValue([],$leaks1,"First run removes private tables; evidence=$evidence");assertSameValue([],$leaks2,"Second run removes private tables; evidence=$evidence");
 echo "ok - HARNESS-OTIZ-ISOLATION-001 verifier runs twice with transcript sha256=$hash1\n";echo "ok - no leaked private tables and ambient decoys sha256=$decoyHash\n";
}catch(RuntimeException$e){if($e->getMessage()!=='HARNESS_OTIZ_INJECTED_FAILURE')throw$e;$injectedFailure=true;}finally{hoiDrop($db,array_values(array_unique(array_merge($ownedPrivate,hoiLeaks($db)))));if($unrelatedOwned)$db->query("DROP TABLE IF EXISTS `$unrelated`");hoiDrop($db,$ownedNative);$db->close();}
if($injectedFailure){fwrite(STDERR,"REGRESSION_FAILURE: injected after fixtures\n");exit(1);}
