<?php
declare(strict_types=1);

require dirname(__DIR__) . '/bootstrap.php';

/** QUALITY-GRAPH-GOVERNANCE-001 v0.6, custom publisher RED. */

function qgpRemoveFixture(string $path): void
{
    if (!is_dir($path)) {
        return;
    }
    $items = new RecursiveIteratorIterator(new RecursiveDirectoryIterator($path, FilesystemIterator::SKIP_DOTS), RecursiveIteratorIterator::CHILD_FIRST);
    foreach ($items as $item) {
        $item->isDir() && !$item->isLink() ? rmdir($item->getPathname()) : unlink($item->getPathname());
    }
    rmdir($path);
}

$root = dirname(__DIR__, 2);
$publisherPath = $root . '/.github/workflows/quality-graph-publish.yml';
$baselinePath = $root . '/.quality-graph/generated-publisher-v0.1.7.yml';

assertSameValue(true, is_file($publisherPath), 'SETUP_FAILURE: qg generate must provide publisher input');
assertSameValue(true, is_file($baselinePath), 'RED_ASSERTION: pinned generated publisher baseline must be retained for allowlisted comparison');

$publisher = (string) file_get_contents($publisherPath);
assertSameValue('a5de72afaafb023a7f9fde24fc1be3872ea96dda1d16d23fb385e8fe58e2a8ee', hash_file('sha256', $baselinePath), 'Generated v0.1.7 comparison baseline must match the reviewed compiler output');
$expected = <<<'YAML'
# Generated by Quality Graph. DO NOT EDIT MANUALLY. Update quality-graph.yml and run qg generate.
---
name: Quality Graph Publisher
'on':
  workflow_run:
    workflows:
      - Quality Graph
    types:
      - requested
      - in_progress
      - completed
permissions: {}
concurrency:
  group: quality-graph-publish-${{ github.event.workflow_run.id || github.event.issue.number }}
  cancel-in-progress: false
jobs:
  publish:
    name: Publish Quality Graph
    if: github.event_name == 'workflow_run' && github.event.workflow_run.event == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      actions: read
      checks: write
      contents: read
    steps:
      - name: Publish trusted Quality Graph state
        uses: alchemmist/quality-graph@caf5366a04ca01b230f1df5585d0fbd9693d7bef
        with:
          operation: ${{ github.event.action == 'completed' && 'publish' || 'watch' }}
YAML;
assertSameValue($expected . "\n", $publisher, 'RED_ASSERTION: deployable publisher must equal the reviewed minimal workflow byte-for-byte');
assertSameValue(false, ($expected . "\nissue_comment: {}") === $publisher, 'Mutation: an extra trigger must not match');
assertSameValue(false, str_replace('actions: read', 'actions: write', $expected . "\n") === $publisher, 'Mutation: expanded permission must not match');
assertSameValue(false, ($expected . "\n- uses: actions/checkout@deadbeef") === $publisher, 'Mutation: extra execution step must not match');

$before = hash_file('sha256', $publisherPath);
$process = proc_open(
    ['make', '--no-print-directory', 'quality-graph-validate'],
    [0 => ['pipe', 'r'], 1 => ['pipe', 'w'], 2 => ['pipe', 'w']],
    $pipes,
    $root,
);
if (!is_resource($process)) {
    throw new TestFailure('SETUP_FAILURE: quality graph validation command did not start');
}
fclose($pipes[0]);
$stdout = stream_get_contents($pipes[1]);
$stderr = stream_get_contents($pipes[2]);
fclose($pipes[1]);
fclose($pipes[2]);
$status = proc_close($process);
$evidence = json_encode(compact('status', 'stdout', 'stderr'), JSON_UNESCAPED_SLASHES | JSON_THROW_ON_ERROR);
$manifest = json_decode((string) file_get_contents($root . '/.quality-graph/manifest.json'), true, 32, JSON_THROW_ON_ERROR);
$expectedDigest = $manifest['graphDigest'] ?? null;
assertSameValue(1, preg_match('/^[0-9a-f]{64}$/D', (string) $expectedDigest), 'SETUP_FAILURE: generated manifest must expose graphDigest');
assertSameValue(0, $status, "RED_ASSERTION: repository validation must accept only the reviewed publisher override; evidence=$evidence");
assertSameValue(1, preg_match_all('/^QUALITY_GRAPH_VALIDATION_OK digest=' . preg_quote((string) $expectedDigest, '/') . '$/m', $stdout), "Validation must emit the independently expected graph digest; evidence=$evidence");
assertSameValue($before, hash_file('sha256', $publisherPath), 'Validation must not rewrite the deployable publisher');

$fixture = sys_get_temp_dir() . '/fmonitor-qgp-' . bin2hex(random_bytes(8));
$fixtureFiles = [
    'quality-graph.yml',
    '.quality-graph/manifest.json',
    '.quality-graph/generated-publisher-v0.1.7.yml',
    '.github/workflows/quality-graph.yml',
    '.github/workflows/quality-graph-push.yml',
    '.github/workflows/quality-graph-publish.yml',
];
try {
    foreach ($fixtureFiles as $relative) {
        $target = $fixture . '/' . $relative;
        if (!is_dir(dirname($target)) && !mkdir(dirname($target), 0700, true) && !is_dir(dirname($target))) {
            throw new TestFailure("SETUP_FAILURE: cannot create fixture directory for $relative");
        }
        if (!copy($root . '/' . $relative, $target)) {
            throw new TestFailure("SETUP_FAILURE: cannot copy fixture $relative");
        }
    }
    file_put_contents($fixture . '/.github/workflows/quality-graph-publish.yml', "# arbitrary drift\n", FILE_APPEND);
    $result = qggRun(['php', $root . '/tools/delivery/check-quality-graph.php', '--repo', $fixture], $fixture);
    $combined = $result['stdout'] . "\n" . $result['stderr'];
    $evidence = json_encode($result, JSON_UNESCAPED_SLASHES | JSON_THROW_ON_ERROR);
    assertSameValue(true, $result['status'] !== 0, "Mutated publisher must fail repository validator; evidence=$evidence");
    assertSameValue(1, preg_match_all('/^QUALITY_GRAPH_VALIDATION_FAILURE category=publisher_override_drift detail=[^\r\n]+$/m', $combined), "RED_ASSERTION: validator must classify arbitrary publisher drift; evidence=$evidence");
    assertSameValue(0, preg_match_all('/^QUALITY_GRAPH_VALIDATION_OK /m', $combined), "Drift failure must not print success; evidence=$evidence");
} finally {
    qgpRemoveFixture($fixture);
}

echo "QUALITY-GRAPH-PUBLISHER-001 TESTS PASSED\n";
