<?php
declare(strict_types=1);

use FMonitor2\AssignmentOrderOriginal\{AssignmentOrderOriginalEvidenceReaderConfig,AssignmentOrderOriginalEvidenceReaderFactory,AssignmentOrderOriginalSchemaMigration,AssignmentOrderOriginalVerificationDatabaseFixture};
use FMonitor2\Tests\Support\AssignmentOrderOriginalDatabaseSetupV1 as RaceContract;

$snapshotRace=static function($r):array{return[
 'domain'=>$r->domainCanonicalJson(4512,81),'requests'=>$r->requestsCanonicalJson(),
 'fingerprints'=>$r->fingerprintsCanonicalJson(),'events'=>$r->eventsCanonicalJson(),
 'audits'=>$r->safeAuditsCanonicalJson(),'process'=>$r->unchangedProcessCanonicalJson(4512,81),
 'blobs'=>$r->privateBlobsCanonicalJson(),'logs'=>$r->safeLogsCanonicalJson(),
];};
$decodeRace=static fn(string$json):array=>json_decode($json,true,512,JSON_THROW_ON_ERROR);
$raceProcess=['schema'=>'aoou-process-v1'];foreach(RaceContract::PROJECTIONS as$key=>[$digest])$raceProcess[$key]=$digest;
$raceProcessJson=json_encode($raceProcess,JSON_THROW_ON_ERROR|JSON_UNESCAPED_SLASHES);
$pdfHash='4028af3714fa07d2f20e758649532faef11b4818c99a2b8dc0c88170a0dc8784';
$compositionHash='388c7d94b3cf91235dabddf26398ac05f754d3d12a0b41a7a91ac3d5370faba5';
$blobJson='{"finalized":[{"byteSize":327,"finalizedAtUtc":"2026-09-02T09:15:30Z","opaqueIdentity":"content-sha256-'.$pdfHash.'","sha256":"'.$pdfHash.'"}],"schema":"aoou-blobs-v1","stages":[]}';
$fingerprintRace=static function(array$members):string{$bytes='';foreach($members as$member){$member=(string)$member;$bytes.=pack('N',strlen($member)).$member;}return hash('sha256',$bytes);};

foreach(['identical','different']as$kind){
 $raceToken=bin2hex(random_bytes(6));$raceDatabase='t_aoou_race_'.$kind[0].'_'.$raceToken;$racePrefix='race_';$raceRoot=$control.'/isolated-'.$kind;$racePrivate=$raceRoot.'/private';$racePassword=$raceRoot.'/password';$raceLog=$raceRoot.'/safe.log';$raceDb=$raceReader=null;
 try{
  $admin->query("CREATE DATABASE `{$raceDatabase}` CHARSET utf8mb4 COLLATE utf8mb4_unicode_ci");mkdir($raceRoot,0700);mkdir($racePrivate,0700);file_put_contents($racePassword,$password."\n");chmod($racePassword,0600);file_put_contents($raceLog,'');chmod($raceLog,0600);$raceDb=new mysqli($host,$user,$password,$raceDatabase,$port);$raceDb->set_charset('utf8mb4');
  FMonitor2\InstallationProcess\ProductionProcessSchemaMigration::apply($raceDb,$racePrefix);FMonitor2\InstallationProcess\IdentityAccessSchemaMigration::apply($raceDb,$racePrefix);FMonitor2\InstallationProcess\ProcessUserCapabilitiesSchemaMigration::apply($raceDb,$racePrefix);FMonitor2\InstallationProcess\ProcessCommandCapabilitiesSchemaMigration::apply($raceDb,$racePrefix);AssignmentOrderOriginalSchemaMigration::apply($raceDb,$racePrefix);AssignmentOrderOriginalVerificationDatabaseFixture::seedExampleA($raceDb,$racePrefix);
  $cfg=['databaseDsn'=>"host={$host};port={$port};database={$raceDatabase};charset=utf8mb4",'databaseUser'=>$user,'databasePasswordFile'=>$racePassword,'tablePrefix'=>$racePrefix,'privateStorageRoot'=>$racePrivate,'safeLogFile'=>$raceLog,'clockUtc'=>'2026-09-02T09:15:30Z','rootIdSequenceCsv'=>'original-0001','revisionIdSequenceCsv'=>'revision-0001','inspectorMode'=>'injected_passive','faultPoint'=>null,'barrierEvent'=>'after_fingerprint_miss_before_cas'];
  $initial=$run($cfg,$command);$initialLine='{"status":"accepted","reasonCode":null,"retryable":false,"requestId":"00000000-0000-4000-8000-000000000001","rootOriginalId":"original-0001","currentRevisionId":"revision-0001","revisionNumber":1,"documentDate":"2026-09-01","sha256":"'.$pdfHash.'","byteSize":327,"uploadedAt":"2026-09-02T09:15:30Z"}' . "\n";assertSameValue([0,'',$initialLine],[$initial['exit'],$initial['stderr'],$initial['result']],"{$kind} exact isolated initial.");
  $raceReader=AssignmentOrderOriginalEvidenceReaderFactory::create(new AssignmentOrderOriginalEvidenceReaderConfig($host,$port,$raceDatabase,$user,$racePassword,$racePrefix,$racePrivate,$raceLog));$initialSnapshot=$snapshotRace($raceReader);$initialDomain=$decodeRace($initialSnapshot['domain']);$initialRequests=$decodeRace($initialSnapshot['requests']);$initialFingerprints=$decodeRace($initialSnapshot['fingerprints']);$initialEvents=$decodeRace($initialSnapshot['events']);$initialAudits=$decodeRace($initialSnapshot['audits']);
  $initialFingerprint=$fingerprintRace(['initial','4512','81','','','','2026-09-01','composition-81-v1',$compositionHash,$pdfHash]);assertSameValue('dd356db041181636ce1ecfc619f9055a625d81250e59ad3543c9f5cd5b582a7d',$initialFingerprint,'Initial fingerprint exact independent oracle.');assertSameValue([1,'original-0001','revision-0001',1,'revision-0001',$initialFingerprint,1,'revision-0001',1,'00000000-0000-4000-8000-000000000001',$raceProcessJson,$blobJson,'{"items":[],"schema":"aoou-logs-v1"}'],[count($initialDomain['roots']),$initialDomain['roots'][0]['rootOriginalId'],$initialDomain['roots'][0]['currentRevisionId'],count($initialDomain['roots'][0]['revisions']),$initialFingerprints['items'][0]['currentRevisionId'],$initialFingerprints['items'][0]['fingerprint'],count($initialEvents['items']),$initialEvents['items'][0]['revisionId'],count($initialAudits['items']),$initialRequests['items'][0]['requestId'],$initialSnapshot['process'],$initialSnapshot['blobs'],$initialSnapshot['logs']],"{$kind} complete exact initial inventory.");
  $current='revision-0001';$baseline=$initialSnapshot;
  if($kind==='different'){$prior=['requestId'=>'00000000-0000-4000-8000-000000000002','mode'=>'correction','installationCaseId'=>4512,'assignmentOrderId'=>81,'actorUserId'=>18,'documentDate'=>'2026-09-02','compositionConfirmed'=>true,'rootOriginalId'=>'original-0001','targetRevisionId'=>'revision-0001','expectedCurrentRevisionId'=>'revision-0001','correctionReason'=>'Baseline revision two','upload'=>['bytesBase64'=>$positive,'originalFilename'=>'baseline-v2.pdf','declaredMediaType'=>'application/pdf']];$priorCfg=$cfg;$priorCfg['clockUtc']='2026-09-02T09:16:00Z';$priorCfg['rootIdSequenceCsv']='original-0099';$priorCfg['revisionIdSequenceCsv']='revision-0002';$priorOut=$run($priorCfg,json_encode($prior,JSON_THROW_ON_ERROR|JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE)."\n");assertSameValue(true,str_contains($priorOut['result'],'"currentRevisionId":"revision-0002","revisionNumber":2'),'Different baseline exact revision two.');$baseline=$snapshotRace($raceReader);$domain=$decodeRace($baseline['domain']);$requests=$decodeRace($baseline['requests']);$fingerprints=$decodeRace($baseline['fingerprints']);$events=$decodeRace($baseline['events']);$audits=$decodeRace($baseline['audits']);$fp=$fingerprintRace(['correction','4512','81','original-0001','revision-0001','revision-0001','2026-09-02','composition-81-v1',$compositionHash,$pdfHash]);assertSameValue([2,'revision-0002',[1,2],['00000000-0000-4000-8000-000000000001','00000000-0000-4000-8000-000000000002'],['revision-0001','revision-0002'],['revision-0001','revision-0002'],[1,2],$fp,$raceProcessJson,$blobJson,'{"items":[],"schema":"aoou-logs-v1"}'],[count($domain['roots'][0]['revisions']),$domain['roots'][0]['currentRevisionId'],array_column($domain['roots'][0]['revisions'],'revisionNumber'),array_column($requests['items'],'requestId'),array_column($fingerprints['items'],'currentRevisionId'),array_column($events['items'],'revisionId'),array_column($audits['items'],'auditId'),$fingerprints['items'][1]['fingerprint'],$baseline['process'],$baseline['blobs'],$baseline['logs']],'Different complete exact initial+revision2 baseline.');$current='revision-0002';}
  $aId='00000000-0000-4000-8000-000000000101';$bId='00000000-0000-4000-8000-000000000102';$dateA=$kind==='identical'?'2026-09-02':'2026-08-31';$dateB=$kind==='identical'?$dateA:'2026-08-30';$a=['requestId'=>$aId,'mode'=>'correction','installationCaseId'=>4512,'assignmentOrderId'=>81,'actorUserId'=>18,'documentDate'=>$dateA,'compositionConfirmed'=>true,'rootOriginalId'=>'original-0001','targetRevisionId'=>$current,'expectedCurrentRevisionId'=>$current,'correctionReason'=>$kind==='identical'?'Concurrent identical correction':'Concurrent different A','upload'=>['bytesBase64'=>$positive,'originalFilename'=>'race-a.pdf','declaredMediaType'=>'application/pdf']];$b=$a;$b['requestId']=$bId;$b['documentDate']=$dateB;$b['correctionReason']=$kind==='identical'?$a['correctionReason']:'Concurrent different B';$aCfg=$cfg;$aCfg['clockUtc']='2026-09-02T09:17:00Z';$aCfg['rootIdSequenceCsv']='original-0098';$aCfg['revisionIdSequenceCsv']=$kind==='identical'?'revision-0002':'revision-0003';$bCfg=$aCfg;$bCfg['rootIdSequenceCsv']='original-0097';$bCfg['revisionIdSequenceCsv']=$kind==='identical'?'revision-0002':'revision-0004';if($kind==='different')$bCfg['faultPoint']='content_lease_release';$wa=$start($aCfg,json_encode($a,JSON_THROW_ON_ERROR|JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE)."\n",$kind.'-fresh-a');$wb=$start($bCfg,json_encode($b,JSON_THROW_ON_ERROR|JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE)."\n",$kind.'-fresh-b');assertSameValue($baseline,$snapshotRace($raceReader),"{$kind} both READY preserve byte-exact complete baseline.");$ra=$finish($wa);$winnerRev=$kind==='identical'?'revision-0002':'revision-0003';$winnerNo=$kind==='identical'?2:3;$winner='{"status":"accepted","reasonCode":null,"retryable":false,"requestId":"'.$aId.'","rootOriginalId":"original-0001","currentRevisionId":"'.$winnerRev.'","revisionNumber":'.$winnerNo.',"documentDate":"'.$dateA.'","sha256":"'.$pdfHash.'","byteSize":327,"uploadedAt":"2026-09-02T09:17:00Z"}' . "\n";assertSameValue([0,'',$winner],[$ra['exit'],$ra['stderr'],$ra['result']],"{$kind} exact winner.");$afterA=$snapshotRace($raceReader);assertSameValue(false,str_contains(json_encode($afterA,JSON_THROW_ON_ERROR),$bId),"{$kind} loser wholly absent before release.");$rb=$finish($wb);$loser=$kind==='identical'?str_replace(['"status":"accepted"',$aId],['"status":"replayed"',$bId],$winner):'{"status":"conflict","reasonCode":"stale_revision","retryable":false,"requestId":"'.$bId.'","rootOriginalId":null,"currentRevisionId":null,"revisionNumber":null,"documentDate":null,"sha256":null,"byteSize":null,"uploadedAt":null}' . "\n";assertSameValue([0,'',$loser],[$rb['exit'],$rb['stderr'],$rb['result']],"{$kind} exact loser.");
  $final=$snapshotRace($raceReader);$domain=$decodeRace($final['domain']);$requests=$decodeRace($final['requests']);$fps=$decodeRace($final['fingerprints']);$events=$decodeRace($final['events']);$audits=$decodeRace($final['audits']);$expectedIds=$kind==='identical'?['00000000-0000-4000-8000-000000000001',$aId]:['00000000-0000-4000-8000-000000000001','00000000-0000-4000-8000-000000000002',$aId,$bId];assertSameValue([$winnerNo,$winnerRev,range(1,$winnerNo),$expectedIds,$expectedIds,$winnerNo,$winnerNo,$raceProcessJson,$blobJson], [count($domain['roots'][0]['revisions']),$domain['roots'][0]['currentRevisionId'],array_column($domain['roots'][0]['revisions'],'revisionNumber'),array_column($requests['items'],'requestId'),array_column($audits['items'],'requestId'),count($fps['items']),count($events['items']),$final['process'],$final['blobs']],"{$kind} complete post-race inventories exact.");if($kind==='identical'){assertSameValue(false,str_contains(json_encode($final,JSON_THROW_ON_ERROR),$bId),'Identical loser absent from every inventory.');$beforeRetry=$final;$retry=$run($bCfg,json_encode($b,JSON_THROW_ON_ERROR|JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE)."\n");assertSameValue($loser,$retry['result'],'Identical loser retry exact.');assertSameValue($beforeRetry,$snapshotRace($raceReader),'Identical retry preserves all inventories byte-exact.');}else{$logs=$decodeRace($final['logs']);$corr=substr(hash('sha256',$bId),0,12);assertSameValue([['correlationId'=>$corr,'event'=>'ASSIGNMENT_ORDER_ORIGINAL_CONTENT_LEASE_RELEASE_FAILED','safeFields'=>['phase'=>'commit_conflict'],'sequence'=>1]],$logs['items'],'Different loser exact safe log.');assertSameValue(false,str_contains(json_encode([$domain,$fps,$events,$final['blobs']],JSON_THROW_ON_ERROR),$bId),'Different loser absent from domain/fingerprint/event/blob.');}
 }finally{if($raceReader!==null)try{$raceReader->close();}catch(Throwable){}if($raceDb instanceof mysqli){try{AssignmentOrderOriginalVerificationDatabaseFixture::cleanupExampleA($raceDb,$racePrefix);}catch(Throwable){}$raceDb->close();}try{$admin->query("DROP DATABASE IF EXISTS `{$raceDatabase}`");}catch(Throwable){}foreach([$raceLog,$racePassword]as$file)if(is_file($file))unlink($file);if(is_dir($racePrivate))rmdir($racePrivate);if(is_dir($raceRoot))rmdir($raceRoot);}
}
