<?php
declare(strict_types=1);
namespace { require dirname(__DIR__).'/bootstrap.php'; }
namespace FMonitor2\PilotHttp\Gate2DescriptorSpy {
use FMonitor2\PilotHttp\{CssDescriptor,CssDescriptorCloseFailed,CssDescriptorOpener,EnvironmentSource,HttpUser,PilotShellRenderer,TrustedServerIdentity,UnexpectedFailureReporter};
final class Source implements EnvironmentSource { public function __construct(private array $values){}public function read(string $name):string|false{return $this->values[$name]??false;}}
final class Descriptor implements CssDescriptor { public int $closeCalls=0;public function __construct(private string $mode){}public function readBytes():string{return "INDEPENDENT-CSS\n";}public function close():void{++$this->closeCalls;if($this->mode==='normal')return;if($this->mode==='throw')throw new \RuntimeException('DESCRIPTOR-THROW-SECRET');if($this->mode==='warning'){set_error_handler(static function():never{throw new \ErrorException('DESCRIPTOR-WARNING-SECRET');});try{trigger_error('DESCRIPTOR-WARNING-SECRET',E_USER_WARNING);}catch(\Throwable){throw new CssDescriptorCloseFailed();}finally{restore_error_handler();}}if($this->mode==='false'){$underlyingResult=false;if($underlyingResult===false)throw new CssDescriptorCloseFailed();}}
}
final class Opener implements CssDescriptorOpener { public int $openCalls=0;public function __construct(public Descriptor $descriptor){}public function open(string $absolutePath):CssDescriptor{++$this->openCalls;return $this->descriptor;}}
final class Identity implements TrustedServerIdentity { public function resolve(mixed $value):string{return 'unused@example.test';}}
final class Shell implements PilotShellRenderer { public function render(HttpUser $user):string{return 'unused';}}
final class Correlation implements \FMonitor2\PilotHttp\CorrelationIdSource { public function nextId():string{return 'descriptor-probe';}}
final class Reporter implements UnexpectedFailureReporter { public array $reports=[];public function report(string $category,string $correlationId):void{$this->reports[]=[$category,$correlationId];}}
}
namespace {
use FMonitor2\PilotHttp\{NativePhpFclosePrimitive,NativePhpStreamCloser,PhpCssDescriptor,PilotHttpApplication,PilotHttpEntrypoint,PilotHttpRequestFactory,ProductionPilotHttpDependencies};
use FMonitor2\PilotHttp\Gate2DescriptorSpy\{Correlation,Descriptor,Identity,Opener,Reporter,Shell,Source};
$config=json_decode((string)getenv('FMONITOR_TEST_RESOURCE_CONFIG'),true,512,JSON_THROW_ON_ERROR);
$cases=[];
foreach(['normal','false','warning','throw'] as $mode){$observer=new \mysqli($config['FMONITOR_DB_HOST'],$config['FMONITOR_DB_USER'],$config['FMONITOR_DB_PASSWORD'],$config['FMONITOR_DB_NAME'],(int)$config['FMONITOR_DB_PORT']);$query="SELECT ID FROM information_schema.PROCESSLIST WHERE DB='".$observer->real_escape_string($config['FMONITOR_DB_NAME'])."' AND ID<>CONNECTION_ID()";$baseline=array_column($observer->query($query)->fetch_all(MYSQLI_ASSOC),'ID');$descriptor=new Descriptor($mode);$opener=new Opener($descriptor);$source=new Source($config);$dependencies=new ProductionPilotHttpDependencies($source,$opener);$dependencies->css()->readBytes();$dependencies->users();$opened=array_values(array_diff(array_column($observer->query($query)->fetch_all(MYSQLI_ASSOC),'ID'),$baseline));$reporter=new Reporter();$application=new PilotHttpApplication(new Identity(),new Shell(),$dependencies);$entrypoint=new PilotHttpEntrypoint(new PilotHttpRequestFactory(),$application,$dependencies,new Correlation(),$reporter);$response=$entrypoint->handle(['REQUEST_METHOD'=>'GET','REQUEST_URI'=>'/pilot/unknown','FMONITOR_TRUSTED_REQUEST_HOST'=>'descriptor-probe.example','REMOTE_USER'=>null]);$repeatNoOp=true;try{$dependencies->close();}catch(\Throwable){$repeatNoOp=false;}$remaining=array_column($observer->query($query)->fetch_all(MYSQLI_ASSOC),'ID');$observer->close();$cases[$mode]=['response'=>['status'=>$response->status,'headers'=>$response->headers,'body'=>$response->body],'reports'=>$reporter->reports,'openCalls'=>$opener->openCalls,'closeCalls'=>$descriptor->closeCalls,'repeatNoOp'=>$repeatNoOp,'openedDbCount'=>count($opened),'dbAfter'=>array_values(array_intersect($opened,$remaining))];}
$baseline=count(get_resources('stream'));$resource=fopen($config['FMONITOR_SHLZ_CSS_PATH'],'rb');if($resource===false)throw new \RuntimeException('normal CSS open');$descriptor=new PhpCssDescriptor($resource,new NativePhpStreamCloser(new NativePhpFclosePrimitive()));$bytes=$descriptor->readBytes();$descriptor->close();$descriptor->close();$normal=['exactBytes'=>$bytes===file_get_contents($config['FMONITOR_SHLZ_CSS_PATH']),'resourceClosed'=>!is_resource($resource),'streamCountRestored'=>count(get_resources('stream'))===$baseline];
echo json_encode(['cases'=>$cases,'phpDescriptor'=>$normal],JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR),"\n";
}
