<?php
// OTIZ-EXCEL-INPUTS-001 — root-owned adversarial read fixtures, no production command bypass.
declare(strict_types=1);
function excelInputsCanonical(array $value):string{return hash('sha256',json_encode($value,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR));}
function excelInputsProof(PreopeningFixture $h,array $row):void
{
 $db=$h->db;$p=$h->p;$e=$row['sourceEvidence'];$application=$db->query("SELECT * FROM {$p}fm2_assignment_order_applications WHERE installation_case_id=6101 ORDER BY application_sequence DESC LIMIT 1")->fetch_assoc();
 assertSameValue(['label'=>'Применённый состав распоряжения','locator'=>'fm2_assignment_order_applications/'.$application['application_id'],'contentSha256'=>excelInputsCanonical($application)],$e['composition']['source'],'exact full applied source hash');
 $template=$db->query("SELECT t.* FROM {$p}fm2_checklist_template_snapshots t JOIN {$p}fm2_checklist_template_associations a ON a.template_snapshot_id=t.id WHERE a.subject_kind='operational_case' AND a.subject_id='6101'")->fetch_assoc();
 $operations=$db->query("SELECT * FROM {$p}fm2_checklist_operations WHERE installation_case_id=6101 AND operation_type IN('item_completed','item_installers_changed','completion_retracted') AND LEFT(device_time,10)<='2026-09-14' AND LEFT(server_received_at,10)<='2026-09-14' ORDER BY accepted_revision,id")->fetch_all(MYSQLI_ASSOC);
 $ids=array_column($operations,'client_operation_id');$all=$db->query("SELECT * FROM {$p}fm2_checklist_operation_installers ORDER BY BINARY client_operation_id,installer_tab_id")->fetch_all(MYSQLI_ASSOC);$attributions=array_values(array_filter($all,static fn($r)=>in_array($r['client_operation_id'],$ids,true)));
 $facts=$db->query("SELECT * FROM {$p}fm2_pilot_completion_facts WHERE installation_case_id=6101 ORDER BY id")->fetch_all(MYSQLI_ASSOC);$corrections=$db->query("SELECT c.* FROM {$p}fm2_pilot_completion_fact_corrections c JOIN {$p}fm2_pilot_completion_facts f ON f.id=c.root_fact_id WHERE f.installation_case_id=6101 ORDER BY c.root_fact_id,c.version_no,c.id")->fetch_all(MYSQLI_ASSOC);
 $canonical=['reportDate'=>'2026-09-14','template'=>$template,'operations'=>$operations,'attributions'=>$attributions,'completionFacts'=>$facts,'completionCorrections'=>$corrections];
 assertSameValue(['label'=>'Подтверждённый прогресс на отчётную дату','locator'=>'fm2_checklist_operations/case/6101','contentSha256'=>excelInputsCanonical($canonical)],$e['progress']['source'],'exact full progress source hash');
 assertSameValue([(int)$template['id'],$template['content_sha256']],[$e['progress']['templateId'],$e['progress']['templateHash']],'template identity proof');
}
function excelInputsAdversarial(PreopeningFixture $h,FMonitor2\Otiz\MariaDbNativePremiumInputs $reader,array $initial):void
{
 $db=$h->db;$p=$h->p;excelInputsProof($h,$initial);
 $operations=$h->rows('fm2_checklist_operations');$event=$operations[0];$eventId=(int)$event['id'];assertSameValue([$event['client_operation_id']],$initial['sourceEvidence']['progress']['clientOperationIds'],'active completion identity');
 foreach(['device_time','server_received_at']as$column){$db->query("UPDATE {$p}fm2_checklist_operations SET $column='2026-09-15T11:00:00+03:00' WHERE id=$eventId");try{assertSameValue(0,$reader->forDate('2026-09-14')[0]['progress'],'future completion cutoff '.$column);}finally{$db->prepare("UPDATE {$p}fm2_checklist_operations SET $column=? WHERE id=?")->execute([$event[$column],$eventId]);}}
 foreach(['item_id'=>999,'template_snapshot_id'=>999999,'template_content_sha256'=>str_repeat('0',64)]as$column=>$value){$db->prepare("UPDATE {$p}fm2_checklist_operations SET $column=? WHERE id=?")->execute([$value,$eventId]);try{inputBlocked($reader->forDate('2026-09-14')[0],$column==='item_id'?'CHECKLIST_ITEM_UNPROVEN':'DEFINITION_VERSION_UNPROVEN');}finally{$db->prepare("UPDATE {$p}fm2_checklist_operations SET $column=? WHERE id=?")->execute([$event[$column],$eventId]);}}
 $db->query("UPDATE {$p}fm_maintable SET plan_finish_date='2026-02-30' WHERE id=4512");try{inputBlocked($reader->forDate('2026-09-14')[0],'DEADLINE_EVIDENCE_ABSENT');}finally{$db->query("UPDATE {$p}fm_maintable SET plan_finish_date='2026-09-05' WHERE id=4512");}
 $app=$h->rows('fm2_assignment_order_applications')[0];$db->query('SET SESSION foreign_key_checks=OFF');$db->query("UPDATE {$p}fm2_assignment_order_applications SET installation_case_id=999999 WHERE application_id=".$app['application_id']);try{inputBlocked($reader->forDate('2026-09-14')[0],'CREW_EVIDENCE_ABSENT');}finally{$db->query("UPDATE {$p}fm2_assignment_order_applications SET installation_case_id=6101 WHERE application_id=".$app['application_id']);$db->query('SET SESSION foreign_key_checks=ON');}
 $card=$db->query("SELECT * FROM {$p}fm2_pilot_object_details WHERE object_id=4512")->fetch_assoc();foreach(['floors'=>['raw'=>'10000','display'=>'10000'],'pitmaterial'=>['raw'=>'X','display'=>'unknown']]as$key=>$value){$payload=json_decode($card['payload_json'],true,flags:JSON_THROW_ON_ERROR);$payload['fields'][$key]=$value;$json=json_encode($payload,JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR);$db->prepare("UPDATE {$p}fm2_pilot_object_details SET payload_json=?,content_sha256=? WHERE object_id=4512")->execute([$json,hash('sha256',$json)]);try{inputBlocked($reader->forDate('2026-09-14')[0],$key==='floors'?'PREMIUM_NORM_UNRESOLVED':'SHAFT_COEFFICIENT_UNRESOLVED');}finally{$db->prepare("UPDATE {$p}fm2_pilot_object_details SET payload_json=?,content_sha256=? WHERE object_id=4512")->execute([$card['payload_json'],$card['content_sha256']]);}}
 $attrs=$h->rows('fm2_checklist_operation_installers');$db->query("DELETE FROM {$p}fm2_checklist_operation_installers WHERE installer_tab_id=7001");try{inputBlocked($reader->forDate('2026-09-14')[0],'INSTALLER_ATTRIBUTION_ABSENT');}finally{foreach($attrs as$r)if((int)$r['installer_tab_id']===7001)$h->insert($p.'fm2_checklist_operation_installers',$r);}
 $associations=$h->rows('fm2_checklist_template_associations');$db->query("DELETE FROM {$p}fm2_checklist_template_associations WHERE subject_kind='operational_case' AND subject_id='6101'");try{inputBlocked($reader->forDate('2026-09-14')[0],'DEFINITION_VERSION_UNPROVEN');}finally{foreach($associations as$r)if($r['subject_kind']==='operational_case'&&$r['subject_id']==='6101')$h->insert($p.'fm2_checklist_template_associations',$r);}
 // Historical attribution may contain a former participant absent from current applied crew.
 $attrs=$h->rows('fm2_checklist_operation_installers');$third=$attrs[0];$third['installer_tab_id']='800';$h->insert($p.'fm2_checklist_operation_installers',$third);
 try{$split=$reader->forDate('2026-09-14')[0];assertSameValue(['7001'=>67,'7002'=>67,'800'=>66],$split['sourceEvidence']['progress']['contributions'],'binary tab remainder conservation200/3');assertSameValue(200,array_sum($split['sourceEvidence']['progress']['contributions']),'every basis point conserved');assertSameValue(['7001','7002'],array_column($split['team'],'tab'),'former attribution participant is not added to applied payable team');excelInputsProof($h,$split);assertSameValue(false,$initial['sourceEvidence']['progress']['source']['contentSha256']===$split['sourceEvidence']['progress']['source']['contentSha256'],'attribution changes proof');}finally{$db->query("DELETE FROM {$p}fm2_checklist_operation_installers WHERE installer_tab_id=800");}
 // Classification of another case sharing an object is not this case's source.
 foreach(['active_candidate','native_candidate']as$category){$foreign=['legacy_object_id'=>4512,'output_kind'=>'operational_case','output_id'=>999999,'source_cutoff_at'=>'2026-09-01 06:00:00','classification_version'=>'foreign-case-fixture','category'=>$category,'reason_codes_json'=>'[]','classification_sha256'=>str_repeat('d',64),'created_at'=>'2026-09-01 06:00:00'];$h->insert($p.'fm2_migration_classification_provenance',$foreign);try{assertSameValue([4512],array_column($reader->forDate('2026-09-14'),'id'),'RED_ASSERTION foreign-case classification cannot exclude or duplicate native case');}finally{$db->query("DELETE FROM {$p}fm2_migration_classification_provenance WHERE output_kind='operational_case' AND output_id=999999");}}
 // Both immutable template formats; even a harmless template label must affect proof.
 $template=$h->rows('fm2_checklist_template_snapshots')[0];$associations=$h->rows('fm2_checklist_template_associations');$decoded=json_decode($template['payload_json'],true,flags:JSON_THROW_ON_ERROR);$definitions=[];foreach($decoded['sections']as$section)foreach($section['items']as$item)$definitions[]=['id'=>$item['id'],'share'=>$item['weight']];
 foreach([$decoded+['fixtureNote'=>'changed'],['definitions'=>$definitions]]as$payload){$json=json_encode($payload,JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR);$hash=hash('sha256',$json);$db->prepare("UPDATE {$p}fm2_checklist_template_snapshots SET payload_json=?,content_sha256=? WHERE id=?")->execute([$json,$hash,$template['id']]);$db->prepare("UPDATE {$p}fm2_checklist_template_associations SET template_content_sha256=? WHERE template_snapshot_id=?")->execute([$hash,$template['id']]);$db->prepare("UPDATE {$p}fm2_checklist_operations SET template_content_sha256=? WHERE template_snapshot_id=?")->execute([$hash,$template['id']]);try{$row=$reader->forDate('2026-09-14')[0];assertSameValue(200,$row['progress'],'supported immutable template form');excelInputsProof($h,$row);assertSameValue(false,$initial['sourceEvidence']['progress']['source']['contentSha256']===$row['sourceEvidence']['progress']['source']['contentSha256'],'template bytes change proof');}finally{$db->prepare("UPDATE {$p}fm2_checklist_template_snapshots SET payload_json=?,content_sha256=? WHERE id=?")->execute([$template['payload_json'],$template['content_sha256'],$template['id']]);foreach($associations as$r)$db->prepare("UPDATE {$p}fm2_checklist_template_associations SET template_content_sha256=? WHERE id=?")->execute([$r['template_content_sha256'],$r['id']]);foreach($operations as$r)$db->prepare("UPDATE {$p}fm2_checklist_operations SET template_content_sha256=? WHERE id=?")->execute([$r['template_content_sha256'],$r['id']]);}}
 // Selection matrix uses copies solely as read fixtures; case IDs deliberately oppose object order.
 $case=$h->rows('fm2_installation_cases')[0];$object=$db->query("SELECT * FROM {$p}fm_maintable WHERE id=4512")->fetch_assoc();$provenance=['output_kind'=>'operational_case','source_cutoff_at'=>'2026-09-01 06:00:00','classification_version'=>'synthetic-native-v1','reason_codes_json'=>'[]','classification_sha256'=>str_repeat('b',64),'created_at'=>'2026-09-01 06:00:00'];$created=[];
 try{foreach([[4511,7009,'working','2026-09-02','native_candidate',true],[4510,7008,'working','2026-09-02','native_candidate',true],[4513,7007,'requires_assignment_order','2026-09-02','native_candidate',true],[4514,7006,'working','2026-09-15','native_candidate',true],[4515,7005,'working','2026-09-02','active_candidate',true],[4516,7004,'working','2026-09-02','native_candidate',false]]as[$id,$caseId,$state,$start,$category,$hasObject]){$c=$case;$c['id']=$caseId;$c['legacy_installation_object_id']=$id;$c['process_state']=$state;$c['actual_start_date']=$start;$h->insert($p.'fm2_installation_cases',$c);$created[]=$caseId;if($hasObject){$o=$object;$o['id']=$id;$h->insert($p.'fm_maintable',$o);}$mp=$provenance;unset($mp['id']);$mp['legacy_object_id']=$id;$mp['output_id']=$caseId;$mp['category']=$category;$h->insert($p.'fm2_migration_classification_provenance',$mp);}assertSameValue([4510,4511,4512],array_column($reader->forDate('2026-09-14'),'id'),'exact sorted eligible native cases only');}finally{if($created!==[]){$db->query("DELETE FROM {$p}fm2_migration_classification_provenance WHERE output_id IN(".implode(',',$created).")");$db->query("DELETE FROM {$p}fm2_installation_cases WHERE id IN(".implode(',',$created).")");}$db->query("DELETE FROM {$p}fm_maintable WHERE id IN(4510,4511,4513,4514,4515,4516)");}
}
function excelInputsLatestApplied(PreopeningFixture $h,FMonitor2\Otiz\MariaDbNativePremiumInputs $reader):void
{
 $db=$h->db;$p=$h->p;$cookies=[];$h->login($cookies);assertSameValue(303,$h->selection($cookies,'11111111-1111-4111-8111-000000001101',[7001,7002],'new_order',1)['status'],'second real selection');$order=(int)$db->query("SELECT MAX(assignment_order_id) FROM {$p}fm2_assignment_order_selections")->fetch_column();$metadata=$h->metadata($cookies,'22222222-2222-4222-8222-000000001102');$metadata['documentDate']='2026-09-14';$upload=$h->upload($cookies,$metadata,order:$order);assertSameValue(201,$upload['status'],'second real original');$original=json_decode($upload['body'],true,flags:JSON_THROW_ON_ERROR);
 assertSameValue(303,$h->form('/pilot/objects/4512/execution',['_csrf'=>$h->token($cookies),'action'=>'apply','requestId'=>'33333333-3333-4333-8333-000000001103','orderId'=>(string)$order,'revisionId'=>$original['currentRevisionId'],'sequence'=>'1'],$cookies)['status'],'second real application');$application=(int)$db->query("SELECT MAX(application_id) FROM {$p}fm2_assignment_order_applications")->fetch_column();assertSameValue($application,$reader->forDate('2026-09-14')[0]['sourceEvidence']['composition']['applicationId'],'latest applied application');
 assertSameValue(303,$h->selection($cookies,'11111111-1111-4111-8111-000000001104',[7001,7002],'new_order',2)['status'],'later pending selection');$pending=(int)$db->query("SELECT MAX(assignment_order_id) FROM {$p}fm2_assignment_order_selections")->fetch_column();$metadata=$h->metadata($cookies,'22222222-2222-4222-8222-000000001105');$metadata['documentDate']='2026-09-14';assertSameValue(201,$h->upload($cookies,$metadata,order:$pending)['status'],'later unapplied original');$row=$reader->forDate('2026-09-14')[0];assertSameValue($application,$row['sourceEvidence']['composition']['applicationId'],'pending original does not supersede applied crew');excelInputsProof($h,$row);
}
function excelInputsConsistentCut(PreopeningFixture $h,FMonitor2\Otiz\MariaDbNativePremiumInputs $reader):void
{
 $db=$h->db;$p=$h->p;$other=new mysqli(getenv('FMONITOR_TEST_DB_HOST')?:'127.0.0.1',getenv('FMONITOR_TEST_DB_ADMIN_USER')?:'root',getenv('FMONITOR_TEST_DB_ADMIN_PASSWORD')?:'fmonitor2_test_root_local',$h->database,(int)(getenv('FMONITOR_TEST_DB_PORT')?:23306));$db->query("CREATE TABLE {$p}input_transaction_witness(id INT PRIMARY KEY,value INT) ENGINE=InnoDB");$db->query("INSERT INTO {$p}input_transaction_witness VALUES(1,0)");
 $legacy=$db->query("SELECT plan_finish_date FROM {$p}fm_maintable WHERE id=4512")->fetch_column();$fact=$db->query("SELECT * FROM {$p}fm2_pilot_completion_facts WHERE installation_case_id=6101 AND fact_type='pto_act'")->fetch_assoc();$application=$db->query("SELECT * FROM {$p}fm2_assignment_order_applications WHERE installation_case_id=6101 ORDER BY application_sequence DESC LIMIT 1")->fetch_assoc();$operation=$db->query("SELECT * FROM {$p}fm2_checklist_operations WHERE installation_case_id=6101 ORDER BY id DESC LIMIT 1")->fetch_assoc();
 $db->query('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');$db->begin_transaction(MYSQLI_TRANS_START_WITH_CONSISTENT_SNAPSHOT);try{$db->query("UPDATE {$p}input_transaction_witness SET value=7 WHERE id=1");$before=$reader->forDate('2026-09-14');$other->query("UPDATE {$p}fm_maintable SET plan_finish_date='2030-01-01' WHERE id=4512");$other->query("UPDATE {$p}fm2_pilot_completion_facts SET details='concurrent' WHERE id=".$fact['id']);$other->query("UPDATE {$p}fm2_assignment_order_applications SET composition_sha256=REPEAT('0',64) WHERE application_id=".$application['application_id']);$other->query("UPDATE {$p}fm2_checklist_operations SET device_time='2099-01-01T00:00:00Z' WHERE id=".$operation['id']);assertSameValue($before,$reader->forDate('2026-09-14'),'one consistent old deadline/composition/PTO/progress source cut');assertSameValue(0,(int)$other->query("SELECT value FROM {$p}input_transaction_witness WHERE id=1")->fetch_column(),'caller transaction was never committed and restarted');assertSameValue(7,(int)$db->query("SELECT value FROM {$p}input_transaction_witness WHERE id=1")->fetch_column(),'caller uncommitted witness retained');}finally{$db->rollback();$other->prepare("UPDATE {$p}fm_maintable SET plan_finish_date=? WHERE id=4512")->execute([$legacy]);$other->prepare("UPDATE {$p}fm2_pilot_completion_facts SET details=? WHERE id=?")->execute([$fact['details'],$fact['id']]);$other->prepare("UPDATE {$p}fm2_assignment_order_applications SET composition_sha256=? WHERE application_id=?")->execute([$application['composition_sha256'],$application['application_id']]);$other->prepare("UPDATE {$p}fm2_checklist_operations SET device_time=? WHERE id=?")->execute([$operation['device_time'],$operation['id']]);$db->query("DROP TABLE {$p}input_transaction_witness");$other->close();}
}
function excelInputsCompletionBoundaries(PreopeningFixture $h,FMonitor2\Otiz\MariaDbNativePremiumInputs $reader,FMonitor2\InstallationProcess\MariaDbInstallationCompletion $owner,int $rootId):void
{
 $db=$h->db;$p=$h->p;$db->prepare("INSERT IGNORE INTO {$p}fm2_pilot_role_permissions(role_id,permission)VALUES(1,?)")->execute(['installation.completion.declaration.correct']);
 $owner->correct(4512,18,$rootId,'pto_act','2026-09-25','','Second correction','2026-09-26T12:00:00Z');$owner->correct(4512,18,$rootId,'pto_act','2026-09-28','','Third correction','2026-09-29T12:00:00Z');
 $declaration=$owner->facts(6101)['declaration'];$owner->correct(4512,18,(int)$declaration['id'],'declaration','2026-09-30','Corrected declaration','Later declaration correction','2026-09-30T12:00:00Z');
 $row=$reader->forDate('2026-09-14')[0];assertSameValue(['2026-09-28',10000],[$row['pto'],$row['progress']],'current final PTO leaf with independently historical PTO/declaration progress');assertSameValue([1,2,3],array_map(static fn($r)=>(int)$r['version_no'],$row['sourceEvidence']['completion']['corrections']),'full mixed cutoff chain');excelInputsProof($h,$row);
 $current=$row['sourceEvidence']['completion']['corrections'][2];$root=$row['sourceEvidence']['completion']['root'];$oldMode=$db->query('SELECT @@SESSION.sql_mode')->fetch_column();$db->query("SET SESSION sql_mode=''");$db->query('SET SESSION check_constraint_checks=OFF');$db->query('SET SESSION foreign_key_checks=OFF');
 try{foreach([['fm2_pilot_completion_facts',$root,'fact_date','0000-00-00'],['fm2_pilot_completion_facts',$root,'recorded_at','invalid'],['fm2_pilot_completion_fact_corrections',$current,'fact_date','0000-00-00'],['fm2_pilot_completion_fact_corrections',$current,'recorded_at','invalid'],['fm2_pilot_completion_fact_corrections',$current,'version_no',5],['fm2_pilot_completion_fact_corrections',$current,'previous_correction_id',999999],['fm2_pilot_completion_fact_corrections',$current,'previous_version_no',1]]as[$table,$saved,$column,$bad]){$db->prepare("UPDATE {$p}{$table} SET {$column}=? WHERE id=?")->execute([$bad,$saved['id']]);try{inputBlocked($reader->forDate('2026-09-14')[0],'COMPLETION_EVIDENCE_INVALID');}finally{$db->prepare("UPDATE {$p}{$table} SET {$column}=? WHERE id=?")->execute([$saved[$column],$saved['id']]);}}}finally{$db->query('SET SESSION foreign_key_checks=ON');$db->query('SET SESSION check_constraint_checks=ON');$db->prepare('SET SESSION sql_mode=?')->execute([$oldMode]);}
 // A not-yet-known declaration must not add the last five percent.
 $original=$db->query("SELECT * FROM {$p}fm2_pilot_completion_facts WHERE id=".$declaration['id'])->fetch_assoc();$db->query("UPDATE {$p}fm2_pilot_completion_facts SET recorded_at='2026-09-15T12:00:00Z' WHERE id=".$declaration['id']);try{assertSameValue(9500,$reader->forDate('2026-09-14')[0]['progress'],'future declaration receipt excluded');}finally{$db->prepare("UPDATE {$p}fm2_pilot_completion_facts SET recorded_at=? WHERE id=?")->execute([$original['recorded_at'],$original['id']]);}
}
