<?php
declare(strict_types=1);
// Explicit PILOT-SESSION-STORAGE-001 v7 Compose verifier; intentionally not an
// auto-discovered test because it stop/starts the operator-owned pilot service.
$root=dirname(__DIR__,2);$inspector="$root/bin/pilot-session-storage-inspect.php";
if(!is_file($inspector)){fwrite(STDERR,"INTENTIONAL_RED: exact inspector CLI is missing\n");exit(65);}
$email=getenv('FMONITOR_COMPOSE_TEST_EMAIL');$password=getenv('FMONITOR_COMPOSE_TEST_PASSWORD');if(!is_string($email)||$email===''||!is_string($password)||$password===''){fwrite(STDERR,"SETUP_FAILURE: FMONITOR_COMPOSE_TEST_EMAIL/PASSWORD required\n");exit(78);}
function pcsCmd(array$args,int$timeoutMs=30000):array{$p=[];$r=proc_open($args,[1=>['pipe','w'],2=>['pipe','w']],$p,dirname(__DIR__,2));if(!is_resource($r))throw new RuntimeException('SETUP_FAILURE: process');foreach($p as$q)stream_set_blocking($q,false);$o='';$e='';$deadline=hrtime(true)+$timeoutMs*1_000_000;$timed=false;while(true){$o.=stream_get_contents($p[1]);$e.=stream_get_contents($p[2]);$s=proc_get_status($r);if(!$s['running'])break;if(hrtime(true)>=$deadline){$timed=true;proc_terminate($r,15);$term=hrtime(true)+500_000_000;do{usleep(10000);$s=proc_get_status($r);}while($s['running']&&hrtime(true)<$term);if($s['running'])proc_terminate($r,9);break;}usleep(10000);}$o.=stream_get_contents($p[1]);$e.=stream_get_contents($p[2]);foreach($p as$q)fclose($q);$exit=proc_close($r);if($timed)throw new RuntimeException('SETUP_FAILURE: bounded command timeout');return[$exit,$o,$e];}
function pcsHttp(string$method,string$path,string$body='',string$cookie=''):array{$h=['Content-Type: application/x-www-form-urlencoded'];if($cookie!=='')$h[]='Cookie: '.$cookie;$c=stream_context_create(['http'=>['method'=>$method,'header'=>implode("\r\n",$h),'content'=>$body,'ignore_errors'=>true,'follow_location'=>0,'timeout'=>5]]);$bytes=file_get_contents('http://127.0.0.1:8092'.$path,false,$c);$headers=$http_response_header??[];$status=preg_match('#^HTTP/\S+ (\d+)#',$headers[0]??'',$m)?(int)$m[1]:0;return[$status,$headers,(string)$bytes];}
function pcsCookie(array$headers,string$current=''):string{foreach($headers as$h)if(preg_match('/^Set-Cookie:\s*([^;]+)/i',$h,$m))$current=$m[1];return$current;}
function pcsHeader(array$headers,string$name):?string{foreach($headers as$h)if(str_starts_with(strtolower($h),strtolower($name).':'))return trim(substr($h,strlen($name)+1));return null;}
function pcsCsrf(string$html):string{if(!preg_match('/name="csrfToken" value="([A-Za-z0-9_-]+)"/',$html,$m))throw new RuntimeException('SETUP_FAILURE: csrf absent');return$m[1];}
$initiallyRunning=false;$cookie='';$csrf='';
try{[$rc,$id]=pcsCmd(['docker','compose','ps','-q','pilot']);if($rc!==0||trim($id)==='')throw new RuntimeException('SETUP_FAILURE: pilot service must already be running');$initiallyRunning=true;
 [$s,$h]=pcsHttp('GET','/pilot/admin/users');if($s!==303||pcsHeader($h,'Location')!=='/pilot/login')throw new RuntimeException('REGRESSION: safe return-to admission');$set=pcsHeader($h,'Set-Cookie')??'';if(!preg_match('/^fm2auth_8092=[A-Za-z0-9,-]{16,128};.*path=\/pilot.*HttpOnly.*SameSite=Strict/i',$set)||stripos($set,'Secure')!==false)throw new RuntimeException('REGRESSION: exact http cookie name/attributes');$cookie=pcsCookie($h);[$s,$h,$b]=pcsHttp('GET','/pilot/login','',$cookie);$csrf=pcsCsrf($b);[$s,$h,$b]=pcsHttp('POST','/pilot/login',http_build_query(['csrfToken'=>$csrf,'email'=>$email]),$cookie);$cookie=pcsCookie($h,$cookie);$csrf=pcsCsrf($b);[$s,$h]=pcsHttp('POST','/pilot/login',http_build_query(['csrfToken'=>$csrf,'email'=>$email,'password'=>$password]),$cookie);$cookie=pcsCookie($h,$cookie);if($s!==303||pcsHeader($h,'Location')!=='/pilot/admin/users')throw new RuntimeException('SETUP_FAILURE: authenticated login/regeneration/return-to failed');
 [$s]=pcsHttp('GET','/pilot/admin/users','',$cookie);if($s!==200)throw new RuntimeException('REGRESSION: authenticated UserAccessView unavailable before restart');[$rc,$before,$err]=pcsCmd(['docker','compose','exec','-T','pilot','php','bin/pilot-session-storage-inspect.php','--state-root','/home/fmonitor/.local/state/fmonitor2','--instance','pilot']);if($rc!==0||$err!=='')throw new RuntimeException('REGRESSION: pre-restart inspector failed');
 [$rc]=pcsCmd(['docker','compose','stop','pilot']);if($rc!==0)throw new RuntimeException('SETUP_FAILURE: stop failed');[$rc]=pcsCmd(['docker','compose','start','pilot']);if($rc!==0)throw new RuntimeException('SETUP_FAILURE: start failed');$deadline=microtime(true)+30;do{usleep(250000);[$s]=pcsHttp('GET','/pilot/assets/favicon.svg');}while($s!==200&&microtime(true)<$deadline);if($s!==200)throw new RuntimeException('SETUP_FAILURE: pilot not ready after restart');
 [$rc,$after,$err]=pcsCmd(['docker','compose','exec','-T','pilot','php','bin/pilot-session-storage-inspect.php','--state-root','/home/fmonitor/.local/state/fmonitor2','--instance','pilot']);if($rc!==0||$err!==''||$before!==$after)throw new RuntimeException('REGRESSION: canonical material changed across restart');[$s]=pcsHttp('GET','/pilot/admin/users','',$cookie);if($s!==200)throw new RuntimeException('REGRESSION: original authenticated cookie failed after restart');echo"PASS: PILOT-SESSION-STORAGE-001 v7 actual Compose restart\n";
}finally{if($initiallyRunning){[$s,$h,$b]=pcsHttp('GET','/pilot/admin/users','',$cookie);if($s===200&&preg_match('/name="csrfToken" value="([A-Za-z0-9_-]+)"/',$b,$m))pcsHttp('POST','/pilot/logout',http_build_query(['csrfToken'=>$m[1]]),$cookie);}}
