<?php

declare(strict_types=1);

require_once __DIR__.'/legacy-migration/LegacyMigrationRouter.php';
require_once __DIR__.'/legacy-migration/ChecklistTemplateAssociation.php';
function activeBatchEnv(string$n):string{$v=getenv($n);if(!is_string($v)||$v==='')throw new RuntimeException('CONFIGURATION_INVALID');return$v;}
set_exception_handler(static function(Throwable$e):never{echo json_encode(['ok'=>false,'reason'=>'ACTIVE_BATCH_UNAVAILABLE'],JSON_THROW_ON_ERROR),"\n";exit(2);});
$o=getopt('',['cutover:','after-id:','batch-size:','template-snapshot-id:','apply','dry-run-all']);$cutover=(string)($o['cutover']??'');$after=filter_var($o['after-id']??'0',FILTER_VALIDATE_INT,['options'=>['min_range'=>0]]);$size=filter_var($o['batch-size']??'25',FILTER_VALIDATE_INT,['options'=>['min_range'=>1,'max_range'=>100]]);$snapshotId=filter_var($o['template-snapshot-id']??null,FILTER_VALIDATE_INT,['options'=>['min_range'=>1]]);$apply=isset($o['apply']);$all=isset($o['dry-run-all']);if($cutover===''||$after===false||$size===false||$snapshotId===false||($apply&&$all))throw new InvalidArgumentException('CONFIGURATION_INVALID');
$source=new mysqli(getenv('FMONITOR_SOURCE_HOST')?:'127.0.0.1',activeBatchEnv('FMONITOR_SOURCE_USER'),activeBatchEnv('FMONITOR_SOURCE_PASSWORD'),getenv('FMONITOR_SOURCE_NAME')?:'c1_fmonitor',(int)(getenv('FMONITOR_SOURCE_PORT')?:13306));$source->set_charset('utf8mb4');
$manifest=json_decode((string)file_get_contents(activeBatchEnv('FMONITOR_PILOT_ACTIVE_MANIFEST')),true,flags:JSON_THROW_ON_ERROR);$prefix=(string)($manifest['processPrefix']??'');$target=new mysqli(activeBatchEnv('FMONITOR_DB_HOST'),activeBatchEnv('FMONITOR_DB_USER'),activeBatchEnv('FMONITOR_DB_PASSWORD'),activeBatchEnv('FMONITOR_DB_NAME'),(int)activeBatchEnv('FMONITOR_DB_PORT'));$target->set_charset('utf8mb4');
$template=$target->query("SELECT snapshot_version,valid_from,content_sha256 FROM `{$prefix}fm2_checklist_template_snapshots` WHERE id=".(int)$snapshotId)->fetch_assoc();if(!is_array($template))throw new OutOfBoundsException('CHECKLIST_TEMPLATE_NOT_FOUND');$policy=ChecklistTemplateAssociationPolicy::validate('legacy_active_baseline',$cutover,(string)$template['valid_from'],(string)$template['snapshot_version'],(string)$template['content_sha256']);if(!$policy['allowed'])throw new DomainException((string)$policy['conflictCode']);
$baselineTarget=new LegacyActiveBaselineTarget($target,$prefix);$provenanceTarget=new MigrationClassificationProvenanceTarget($target,$prefix);$associationTarget=new ChecklistTemplateAssociationTarget($target,$prefix);
$stats=['scanned'=>0,'activeBaselines'=>0,'classifierQuarantined'=>0,'created'=>0,'alreadyPresent'=>0,'provenanceCreated'=>0,'provenancePresent'=>0,'associationCreated'=>0,'associationPresent'=>0];$checkpoint=(int)$after;$complete=false;
do{$source->query('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');$source->query('START TRANSACTION WITH CONSISTENT SNAPSHOT, READ ONLY');
 try{$q=$source->prepare('SELECT id,ordadr_address,entrance,regnumber,CASE WHEN factworkstartdate<=? THEN factworkstartdate ELSE NULL END factworkstartdate,CASE WHEN ptoactdate<=? THEN ptoactdate ELSE NULL END ptoactdate,object_status,fact_percent,workstarted FROM fm_maintable WHERE id>? ORDER BY id LIMIT ?');$q->bind_param('ssii',$cutover,$cutover,$checkpoint,$size);$q->execute();$rows=$q->get_result()->fetch_all(MYSQLI_ASSOC);$events=[];$attrs=[];
  if($rows!==[]){$first=(int)$rows[0]['id'];$last=(int)$rows[array_key_last($rows)]['id'];$x=$source->prepare('SELECT value_id,COUNT(*)n FROM fm_install_checklists_values_log WHERE value_id BETWEEN ? AND ? AND ctime<=? GROUP BY value_id');$x->bind_param('iis',$first,$last,$cutover);$x->execute();foreach($x->get_result()->fetch_all(MYSQLI_ASSOC)as$r)$events[(int)$r['value_id']]=(int)$r['n'];$x=$source->prepare('SELECT v.value_id,COUNT(*)n FROM fm_install_checklists_values_installators_log a JOIN fm_install_checklists_values v ON v.id=a.checklist_value_id WHERE v.value_id BETWEEN ? AND ? AND a.ctime<=? GROUP BY v.value_id');$x->bind_param('iis',$first,$last,$cutover);$x->execute();foreach($x->get_result()->fetch_all(MYSQLI_ASSOC)as$r)$attrs[(int)$r['value_id']]=(int)$r['n'];}
  foreach($rows as$row){$id=(int)$row['id'];$row['checklist_event_count']=$events[$id]??0;$row['attribution_count']=$attrs[$id]??0;$checkpoint=$id;$stats['scanned']++;$classification=LegacyObjectClassification::classify($row);$route=LegacyMigrationRoute::decide($classification);if($route['route']!=='cutover_baseline')continue;if($route['applyBlocked']){$stats['classifierQuarantined']++;continue;}$stats['activeBaselines']++;if(!$apply)continue;$now=gmdate('Y-m-d H:i:s');$saved=$baselineTarget->apply($row,$classification,$cutover,$now);$saved['created']?$stats['created']++:$stats['alreadyPresent']++;$proof=$provenanceTarget->reconcile('active_baseline',$id,(int)$saved['baselineId'],$cutover,$classification,$now);$proof['provenanceCreated']?$stats['provenanceCreated']++:$stats['provenancePresent']++;$link=$associationTarget->associateActiveBaseline($id,(int)$snapshotId,$now);$link['created']?$stats['associationCreated']++:$stats['associationPresent']++;}
  $source->commit();}catch(Throwable$e){$source->rollback();throw$e;}$complete=count($rows)<$size;
}while($all&&!$complete);
echo json_encode(['ok'=>true,'mode'=>$apply?'apply':($all?'dry-run-all':'dry-run'),'batchSize'=>(int)$size,'startedAfterId'=>(int)$after,'nextAfterId'=>$checkpoint,'complete'=>$complete,'classificationVersion'=>LegacyObjectClassification::VERSION,'route'=>'cutover_baseline','template'=>['snapshotId'=>(int)$snapshotId,'snapshotVersion'=>$template['snapshot_version'],'contentSha256'=>$template['content_sha256'],'validFrom'=>$template['valid_from']],'stats'=>$stats],JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR),"\n";
