<?php
declare(strict_types=1);
function userImportEnv(string $name):string{$value=getenv($name);if($value===false||$value==='')throw new RuntimeException("Missing {$name}");return$value;}
mysqli_report(MYSQLI_REPORT_ERROR|MYSQLI_REPORT_STRICT);$manifest=json_decode((string)file_get_contents(userImportEnv('FMONITOR_PILOT_ACTIVE_MANIFEST')),true,flags:JSON_THROW_ON_ERROR);$prefix=(string)($manifest['processPrefix']??'');if(preg_match('/^[A-Za-z0-9_]+$/D',$prefix)!==1)throw new RuntimeException('Invalid pilot generation prefix');
$source=new mysqli(getenv('FMONITOR_SOURCE_HOST')?:'127.0.0.1',userImportEnv('FMONITOR_SOURCE_USER'),userImportEnv('FMONITOR_SOURCE_PASSWORD'),getenv('FMONITOR_SOURCE_NAME')?:'c1_fmonitor',(int)(getenv('FMONITOR_SOURCE_PORT')?:'13306'));$source->set_charset('utf8');$target=new mysqli('127.0.0.1','fmonitor2_demo','fmonitor2_demo_local','fmonitor2_demo',23306);$target->set_charset('utf8mb4');$sourcePrefix=getenv('FMONITOR_SOURCE_TABLE_PREFIX')?:'';if(preg_match('/^[A-Za-z0-9_]*$/D',$sourcePrefix)!==1)throw new RuntimeException('Invalid source table prefix');
$userColumns=array_column($source->query("SHOW COLUMNS FROM `{$sourcePrefix}users`")->fetch_all(MYSQLI_ASSOC),'Field');$phoneExpression=in_array('phone',$userColumns,true)?'phone':"'' AS phone";$users=$source->query("SELECT id,name,email,{$phoneExpression},role_id,status FROM `{$sourcePrefix}users` ORDER BY id")->fetch_all(MYSQLI_ASSOC);$roles=$source->query("SELECT id,name,status FROM `{$sourcePrefix}users_roles` ORDER BY id")->fetch_all(MYSQLI_ASSOC);if($users===[]||$roles===[])throw new RuntimeException('Production user directory is empty');$now=(new DateTimeImmutable('now',new DateTimeZone('Europe/Moscow')))->format('Y-m-d\TH:i:sP');
$target->begin_transaction();try{
 $target->query("CREATE TABLE IF NOT EXISTS `{$prefix}fm2_pilot_users`(user_id BIGINT UNSIGNED NOT NULL PRIMARY KEY,full_name VARCHAR(300) NOT NULL,email VARCHAR(254) NOT NULL,phone VARCHAR(100) NOT NULL,status TINYINT(1) NOT NULL,source_updated_at VARCHAR(40) NOT NULL,KEY(status,full_name)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");$target->query("CREATE TABLE IF NOT EXISTS `{$prefix}fm2_pilot_roles`(role_id BIGINT UNSIGNED NOT NULL PRIMARY KEY,name VARCHAR(300) NOT NULL,status TINYINT(1) NOT NULL,source_updated_at VARCHAR(40) NOT NULL,KEY(status,name)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");$target->query("CREATE TABLE IF NOT EXISTS `{$prefix}fm2_pilot_user_roles`(user_id BIGINT UNSIGNED NOT NULL,role_id BIGINT UNSIGNED NOT NULL,origin VARCHAR(40) NOT NULL,assigned_at VARCHAR(40) NOT NULL,assigned_by_user_id BIGINT UNSIGNED NULL,PRIMARY KEY(user_id,role_id),KEY(role_id,user_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");$target->query("CREATE TABLE IF NOT EXISTS `{$prefix}fm2_pilot_user_role_events`(id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,user_id BIGINT UNSIGNED NOT NULL,role_id BIGINT UNSIGNED NOT NULL,action VARCHAR(40) NOT NULL,occurred_at VARCHAR(40) NOT NULL,actor_user_id BIGINT UNSIGNED NOT NULL,KEY(user_id,id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
 $roleUpsert=$target->prepare("INSERT INTO `{$prefix}fm2_pilot_roles`(role_id,name,status,source_updated_at) VALUES(?,?,?,?) ON DUPLICATE KEY UPDATE name=VALUES(name),status=VALUES(status),source_updated_at=VALUES(source_updated_at)");$roleIds=[];foreach($roles as$row){$id=(int)$row['id'];$name=trim((string)$row['name']);$status=(int)$row['status']===1?1:0;if($id<1||$name==='')throw new RuntimeException('Invalid production role');$roleIds[$id]=true;$roleUpsert->bind_param('isis',$id,$name,$status,$now);$roleUpsert->execute();}
 $userUpsert=$target->prepare("INSERT INTO `{$prefix}fm2_pilot_users`(user_id,full_name,email,phone,status,source_updated_at) VALUES(?,?,?,?,?,?) ON DUPLICATE KEY UPDATE full_name=VALUES(full_name),email=VALUES(email),phone=VALUES(phone),status=VALUES(status),source_updated_at=VALUES(source_updated_at)");foreach($users as$row){$id=(int)$row['id'];$name=trim((string)$row['name']);$email=trim((string)$row['email']);$phone=trim((string)$row['phone']);$status=(int)$row['status']===1?1:0;if($id<1||$name==='')throw new RuntimeException('Invalid production user');$userUpsert->bind_param('isssis',$id,$name,$email,$phone,$status,$now);$userUpsert->execute();}
 $target->query("DELETE FROM `{$prefix}fm2_pilot_user_roles` WHERE origin='legacy_primary'");$seed=$target->prepare("INSERT INTO `{$prefix}fm2_pilot_user_roles`(user_id,role_id,origin,assigned_at,assigned_by_user_id) VALUES(?,?,'legacy_primary',?,NULL) ON DUPLICATE KEY UPDATE origin=IF(origin='legacy_primary',VALUES(origin),origin)");$seeded=0;foreach($users as$row){$userId=(int)$row['id'];$roleId=(int)$row['role_id'];if(!isset($roleIds[$roleId]))continue;$seed->bind_param('iis',$userId,$roleId,$now);$seed->execute();$seeded++;}$target->commit();
}catch(Throwable $error){$target->rollback();throw$error;}
echo json_encode(['ok'=>true,'users'=>count($users),'activeUsers'=>count(array_filter($users,fn($x)=>(int)$x['status']===1)),'roles'=>count($roles),'activeRoles'=>count(array_filter($roles,fn($x)=>(int)$x['status']===1)),'legacyAssignments'=>$seeded,'sourceUpdatedAt'=>$now],JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR),PHP_EOL;
