<?php
declare(strict_types=1);
require_once __DIR__.'/legacy-migration/MigratedEvidenceDecisionLedger.php';
function ledgerCheck(bool $ok,string $message):void{if(!$ok)throw new RuntimeException($message);}
$host=getenv('FMONITOR_DB_HOST')?:'127.0.0.1';$port=(int)(getenv('FMONITOR_DB_PORT')?:23306);$db=new mysqli($host,getenv('FMONITOR_DB_USER')?:'fmonitor2_demo',getenv('FMONITOR_DB_PASSWORD')?:'fmonitor2_demo_local',getenv('FMONITOR_DB_NAME')?:'fmonitor2_demo',$port);$db->set_charset('utf8mb4');$p='decision_verify_'.bin2hex(random_bytes(4)).'_';
$tables=['fm2_migrated_evidence_decisions','fm2_history_import_quarantine','fm2_history_source_snapshots','fm2_pilot_user_roles','fm2_pilot_roles','fm2_pilot_users'];
try{
 $db->query("CREATE TABLE `{$p}fm2_pilot_users`(user_id BIGINT UNSIGNED PRIMARY KEY,full_name VARCHAR(100),email VARCHAR(100),status TINYINT)");$db->query("CREATE TABLE `{$p}fm2_pilot_roles`(role_id BIGINT UNSIGNED PRIMARY KEY,name VARCHAR(100),status TINYINT)");$db->query("CREATE TABLE `{$p}fm2_pilot_user_roles`(user_id BIGINT UNSIGNED,role_id BIGINT UNSIGNED,PRIMARY KEY(user_id,role_id))");
 $db->query("INSERT INTO `{$p}fm2_pilot_users` VALUES(10,'OTIZ','otiz@example.test',1),(11,'Viewer','viewer@example.test',1)");$db->query("INSERT INTO `{$p}fm2_pilot_roles` VALUES(20,'ОТиЗ',1),(21,'Наблюдатель',1)");$db->query("INSERT INTO `{$p}fm2_pilot_user_roles` VALUES(10,20),(11,21)");
 $db->query("CREATE TABLE `{$p}fm2_history_source_snapshots`(id BIGINT UNSIGNED PRIMARY KEY,legacy_object_id BIGINT UNSIGNED,source_system VARCHAR(80),source_locator VARCHAR(500),cutoff_at VARCHAR(40),extractor_version VARCHAR(100),content_sha256 CHAR(64),payload_json LONGTEXT)");$db->query("CREATE TABLE `{$p}fm2_history_import_quarantine`(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,snapshot_id BIGINT UNSIGNED,issue_no INT UNSIGNED,code VARCHAR(80),diagnostic_json LONGTEXT)");
 $payload=json_encode(['object'=>['id'=>973,'regnumber'=>'77-00973','ordadr_address'=>'Test','entrance'=>'1','ptoactdate'=>'2026-08-01'],'checklistEvents'=>[['id'=>1]],'attributions'=>[['id'=>2]]],JSON_THROW_ON_ERROR);$snapshotHash=hash('sha256',$payload);$s=$db->prepare("INSERT INTO `{$p}fm2_history_source_snapshots` VALUES(5,973,'legacy_fmonitor','fm_maintable/973','2026-08-30 23:59:59','history-v1',?,?)");$s->bind_param('ss',$snapshotHash,$payload);$s->execute();$db->query("INSERT INTO `{$p}fm2_history_import_quarantine`(snapshot_id,issue_no,code,diagnostic_json)VALUES(5,1,'ORPHAN_ATTRIBUTION','{}')");
 $ledger=new MigratedEvidenceDecisionLedger($db,$p);$ledger->ensureSchema();$projection=MigratedEvidenceReconciliation::load($db,$p)[0];$command=['operationId'=>'11111111-1111-4111-8111-111111111111','snapshotId'=>5,'snapshotSha256'=>$snapshotHash,'projectionSha256'=>$projection['projectionHash'],'sourceLocator'=>'fm_maintable/973','issueCode'=>'ORPHAN_ATTRIBUTION','outcome'=>'request_source_correction','targetLocator'=>null,'reason'=>'Проверить первичный журнал атрибуции','actorUserId'=>10,'occurredAt'=>'2026-08-30T15:30:00+03:00'];
 $accepted=$ledger->decide($command);ledgerCheck($accepted['status']==='accepted','authorized decision accepted');ledgerCheck($ledger->decide($command)===['status'=>'duplicate','decisionId'=>$accepted['decisionId']],'same operation is idempotent');
 foreach([['unauthorized',array_replace($command,['operationId'=>'22222222-2222-4222-8222-222222222222','actorUserId'=>11])],['stale hash',array_replace($command,['operationId'=>'33333333-3333-4333-8333-333333333333','projectionSha256'=>str_repeat('0',64)])],['unknown issue',array_replace($command,['operationId'=>'44444444-4444-4444-8444-444444444444','issueCode'=>'NOT_PRESENT'])]]as[$case,$invalid]){try{$ledger->decide($invalid);throw new RuntimeException("{$case} unexpectedly accepted");}catch(DomainException){}}
 try{$ledger->decide(array_replace($command,['outcome'=>'map_link']));throw new RuntimeException('map without target accepted');}catch(InvalidArgumentException){}
 try{$ledger->decide(array_replace($command,['reason'=>'different']));throw new RuntimeException('operation reuse accepted');}catch(DomainException){}
 $map=array_replace($command,['operationId'=>'55555555-5555-4555-8555-555555555555','outcome'=>'map_link','targetLocator'=>'workforce_tab:1042','reason'=>'Unique personnel number confirmed']);ledgerCheck($ledger->decide($map)['status']==='accepted','safe typed link decision recorded');
 foreach([['66666666-6666-4666-8666-666666666666','acknowledge','Conflict reviewed; evidence remains quarantined'],['77777777-7777-4777-8777-777777777777','reject_evidence','Source row cannot support operational use']]as[$operation,$outcome,$reason])ledgerCheck($ledger->decide(array_replace($command,['operationId'=>$operation,'outcome'=>$outcome,'reason'=>$reason]))['status']==='accepted',"{$outcome} decision recorded");
 $rows=$ledger->decisionsForSnapshot(5);ledgerCheck(count($rows)===4&&array_column($rows,'outcome')===['request_source_correction','map_link','acknowledge','reject_evidence']&&$rows[1]['target_locator']==='workforce_tab:1042','all four outcomes are append-only and ordered');ledgerCheck((int)$db->query("SELECT COUNT(*) n FROM `{$p}fm2_history_import_quarantine`")->fetch_assoc()['n']===1,'source quarantine remains unchanged');ledgerCheck((int)$db->query("SELECT COUNT(*) n FROM `{$p}fm2_history_source_snapshots`")->fetch_assoc()['n']===1,'immutable source snapshot remains unchanged');
 echo "PASS migrated evidence append-only decision ledger\n";
}finally{foreach($tables as$table)$db->query("DROP TABLE IF EXISTS `{$p}{$table}`");$db->close();}
