<?php
declare(strict_types=1);
require_once __DIR__.'/NativeOperationalPremiumInputs.php';
require_once __DIR__.'/legacy-migration/PremiumCalculation.php';
mysqli_report(MYSQLI_REPORT_ERROR|MYSQLI_REPORT_STRICT);
$db=new mysqli(getenv('FMONITOR_VERIFY_DB_HOST')?:'127.0.0.1',getenv('FMONITOR_VERIFY_DB_USER')?:'fmonitor2_demo',getenv('FMONITOR_VERIFY_DB_PASSWORD')?:'fmonitor2_demo_local',getenv('FMONITOR_VERIFY_DB_NAME')?:'fmonitor2_demo',(int)(getenv('FMONITOR_VERIFY_DB_PORT')?:23306));$db->set_charset('utf8mb4');$p='native_e2e_'.bin2hex(random_bytes(5)).'_';
$tables=['fm2_pilot_otiz_payment_closures','fm2_pilot_otiz_snapshot_objects','fm2_pilot_otiz_snapshots','fm2_operational_ktu_facts','fm2_operational_premium_facts','fm2_checklist_operation_installers','fm2_checklist_template_snapshots','fm2_checklist_operations','fm2_order_installers','fm2_assignment_orders','fm_maintable','fm2_migration_classification_provenance','fm2_installation_cases'];
$ok=static function(bool$c,string$m):void{if(!$c)throw new RuntimeException($m);echo"ok - $m\n";};
$source=static fn(string$l,string$x,array$r):array=>['label'=>$l,'locator'=>$x,'contentSha256'=>hash('sha256',json_encode($r,JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR))];
try{
 $schema=[
 'fm2_installation_cases'=>"id BIGINT PRIMARY KEY,legacy_installation_object_id BIGINT UNIQUE,process_state VARCHAR(80),actual_start_date DATE,opened_at VARCHAR(40),opened_by_user_id BIGINT",
 'fm2_migration_classification_provenance'=>"output_kind VARCHAR(40),output_id BIGINT,legacy_object_id BIGINT,category VARCHAR(40),classification_version VARCHAR(80),reason_codes_json JSON,quarantine_codes_json JSON",
 'fm_maintable'=>"id BIGINT PRIMARY KEY,regnumber VARCHAR(120),ordadr_address VARCHAR(500)",
 'fm2_assignment_orders'=>"id BIGINT PRIMARY KEY,installation_case_id BIGINT,status VARCHAR(40),version_no INT,order_date DATE,planned_finish_date_snapshot DATE,pto_act_date_snapshot DATE NULL,registration_number VARCHAR(120),registered_at VARCHAR(40)",
 'fm2_order_installers'=>"assignment_order_id BIGINT,installer_tab_id BIGINT,fio_snapshot VARCHAR(300),position_snapshot VARCHAR(300)",
 'fm2_checklist_template_snapshots'=>"id BIGINT PRIMARY KEY,content_sha256 CHAR(64),payload_json LONGTEXT",
 'fm2_checklist_operations'=>"id BIGINT AUTO_INCREMENT PRIMARY KEY,installation_case_id BIGINT,client_operation_id CHAR(36),operation_type VARCHAR(40),item_id INT,actor_user_id BIGINT,device_time VARCHAR(40),server_received_at VARCHAR(40),accepted_revision BIGINT,template_snapshot_id BIGINT,template_content_sha256 CHAR(64),UNIQUE KEY(client_operation_id)",
 'fm2_checklist_operation_installers'=>"client_operation_id CHAR(36),installer_tab_id BIGINT,fio_snapshot VARCHAR(300),position_snapshot VARCHAR(300),assignment_source VARCHAR(40),PRIMARY KEY(client_operation_id,installer_tab_id)",
 'fm2_operational_premium_facts'=>"id BIGINT PRIMARY KEY,installation_case_id BIGINT,effective_date DATE,premium_cents BIGINT,shaft_bp INT,source_label VARCHAR(160),source_locator VARCHAR(300),source_sha256 CHAR(64)",
 'fm2_operational_ktu_facts'=>"id BIGINT PRIMARY KEY,installation_case_id BIGINT,installer_tab_id BIGINT,effective_date DATE,ktu_bp INT,source_label VARCHAR(160),source_locator VARCHAR(300),source_sha256 CHAR(64)",
 'fm2_pilot_otiz_snapshots'=>"id BIGINT AUTO_INCREMENT PRIMARY KEY,report_date DATE,status VARCHAR(20),previous_snapshot_id BIGINT NULL,rules_version VARCHAR(80),calculated_at VARCHAR(40),calculated_by_user_id BIGINT,accepted_at VARCHAR(40) NULL,accepted_by_user_id BIGINT NULL,total_pool_cents BIGINT,total_closed_cents BIGINT,total_available_cents BIGINT,content_hash CHAR(64)",
 'fm2_pilot_otiz_snapshot_objects'=>"snapshot_id BIGINT,object_id BIGINT,regnumber VARCHAR(120),address VARCHAR(500),previous_progress_bp INT,current_progress_bp INT,progress_fact_date DATE,premium_cents BIGINT,shaft_bp INT,kss_bp INT,accrued_cents BIGINT,fund_cents BIGINT,closed_before_cents BIGINT,remaining_cents BIGINT,pool_cents BIGINT,distributed_cents BIGINT,undistributed_cents BIGINT,calculation_state VARCHAR(40),inputs_json JSON,PRIMARY KEY(snapshot_id,object_id)",
 'fm2_pilot_otiz_payment_closures'=>"id BIGINT AUTO_INCREMENT PRIMARY KEY,snapshot_id BIGINT,object_id BIGINT,closed_on DATE,paid_cents BIGINT,discipline_cents BIGINT,deadline_cents BIGINT,basis VARCHAR(500),artifact VARCHAR(300),created_by_user_id BIGINT,created_at VARCHAR(40),reverses_payment_closure_id BIGINT NULL"];
 foreach($schema as$n=>$columns)$db->query("CREATE TABLE `{$p}{$n}`($columns)");
 $hash=hash('sha256','native-template-v1');$payload=$db->real_escape_string(json_encode(['definitions'=>[['id'=>1,'share'=>15],['id'=>2,'share'=>20],['id'=>3,'share'=>25]]],JSON_THROW_ON_ERROR));
 $db->query("INSERT INTO `{$p}fm2_installation_cases` VALUES(7,88421,'working','2026-09-02','2026-09-02T08:00:00+03:00',18)");$db->query("INSERT INTO `{$p}fm2_migration_classification_provenance` VALUES('operational_case',7,88421,'native_candidate','legacy-object-classification-v1',JSON_ARRAY('NO_ACTUAL_START_OR_PROGRESS_EVIDENCE'),JSON_ARRAY())");$db->query("INSERT INTO `{$p}fm_maintable` VALUES(88421,'77-088421','Москва, ул. Производственная, д. 8')");$db->query("INSERT INTO `{$p}fm2_assignment_orders` VALUES(10,7,'registered',1,'2026-09-01','2026-09-30',NULL,'12-Р','2026-09-01T10:00:00+03:00')");$db->query("INSERT INTO `{$p}fm2_order_installers` VALUES(10,1482,'Морозов Илья Павлович','Монтажник')");$db->query("INSERT INTO `{$p}fm2_checklist_template_snapshots` VALUES(3,'$hash','$payload')");$db->query("INSERT INTO `{$p}fm2_operational_premium_facts` VALUES(1,7,'2026-09-01',24000000,10000,'Утверждённая премиальная база','native-premium/88421','".hash('sha256','premium')."')");$db->query("INSERT INTO `{$p}fm2_operational_ktu_facts` VALUES(1,7,1482,'2026-09-01',10000,'Распоряжение и состав','assignment-order/10','".hash('sha256','ktu')."')");
 $add=static function(int$i,string$d)use($db,$p,$hash):void{$u=sprintf('%08d-1111-4111-8111-%012d',$i,$i);$db->query("INSERT INTO `{$p}fm2_checklist_operations` VALUES(NULL,7,'$u','item_completed',$i,73,'{$d}T14:00:00+03:00','{$d}T14:01:00+03:00',$i,3,'$hash')");$db->query("INSERT INTO `{$p}fm2_checklist_operation_installers` VALUES('$u',1482,'Морозов Илья Павлович','Монтажник','completion')");};$add(1,'2026-09-05');$add(2,'2026-09-08');
 $reader=new NativeOperationalPremiumInputs($db,$p);
 $calculate=static function(string$d)use($db,$p,$reader,$source):int{$o=$reader->forDate($d);if(count($o)!==1||$o[0]['issues']!==[])throw new RuntimeException('native inputs blocked');$o=$o[0];$prev=$db->query("SELECT s.id,so.current_progress_bp FROM `{$p}fm2_pilot_otiz_snapshots` s JOIN `{$p}fm2_pilot_otiz_snapshot_objects` so ON so.snapshot_id=s.id AND so.object_id=".(int)$o['id']." WHERE s.status='accepted' AND s.report_date<'$d' ORDER BY s.report_date DESC,s.id DESC LIMIT 1")->fetch_assoc();$closures=[];foreach($db->query("SELECT * FROM `{$p}fm2_pilot_otiz_payment_closures` WHERE object_id=".(int)$o['id']." AND closed_on<='$d' ORDER BY id")->fetch_all(MYSQLI_ASSOC)as$r)$closures[]=['amountCents'=>(int)$r['paid_cents']+(int)$r['discipline_cents']+(int)$r['deadline_cents'],'closedOn'=>$r['closed_on'],'source'=>$source('Принятое закрытие ОТиЗ',$p.'fm2_pilot_otiz_payment_closures/'.$r['id'],$r)];$calc=PremiumCalculation::calculate($o['operands'],['closures'=>$closures,'actualPayouts'=>[]]);$previousId=$prev['id']??null;$previous=(int)($prev['current_progress_bp']??0);$db->query("INSERT INTO `{$p}fm2_pilot_otiz_snapshots` VALUES(NULL,'$d','draft',".($previousId??'NULL').",'".PremiumCalculation::VERSION."','{$d}T18:00:00+03:00',101,NULL,NULL,0,0,0,'pending')");$id=(int)$db->insert_id;$a=$calc['amounts'];$json=$db->real_escape_string(json_encode(['calculationOperandsSource'=>'native_operational_facts','premiumCalculation'=>$calc],JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR));$db->query("INSERT INTO `{$p}fm2_pilot_otiz_snapshot_objects` VALUES($id,".(int)$o['id'].",'{$o['reg']}','".$db->real_escape_string($o['address'])."',$previous,".(int)$o['progress'].",'$d',".(int)$o['premium'].",".(int)$o['shaft'].",".(int)$calc['kssBp'].",{$a['accruedCents']},{$a['fundCents']},{$a['closedBeforeCents']},{$a['remainingFundCents']},{$a['poolCents']},{$a['distributableCents']},0,'ready','$json')");$h=hash('sha256',$json);$db->query("UPDATE `{$p}fm2_pilot_otiz_snapshots` SET total_pool_cents={$a['poolCents']},total_closed_cents={$a['closedBeforeCents']},total_available_cents={$a['poolCents']},content_hash='$h' WHERE id=$id");return$id;};
 $one=$calculate('2026-09-10');$db->query("UPDATE `{$p}fm2_pilot_otiz_snapshots` SET status='accepted',accepted_at='2026-09-11T10:00:00+03:00',accepted_by_user_id=101 WHERE id=$one");$before=$db->query("SELECT s.*,o.* FROM `{$p}fm2_pilot_otiz_snapshots` s JOIN `{$p}fm2_pilot_otiz_snapshot_objects` o ON o.snapshot_id=s.id WHERE s.id=$one")->fetch_assoc();$add(3,'2026-09-12');$twoId=$calculate('2026-09-15');$two=$db->query("SELECT * FROM `{$p}fm2_pilot_otiz_snapshot_objects` WHERE snapshot_id=$twoId")->fetch_assoc();$ok((int)$before['current_progress_bp']===3500&&(int)$two['current_progress_bp']===6000&&(int)$two['previous_progress_bp']===3500,'dated checklist history produces cumulative progress and accepted delta');
 $db->query("INSERT INTO `{$p}fm2_pilot_otiz_payment_closures` VALUES(NULL,$one,88421,'2026-09-16',100000,0,0,'Платёжное поручение 44','44',101,'2026-09-16T12:00:00+03:00',NULL)");$threeId=$calculate('2026-09-20');$three=$db->query("SELECT * FROM `{$p}fm2_pilot_otiz_snapshot_objects` WHERE snapshot_id=$threeId")->fetch_assoc();$ok((int)$three['closed_before_cents']===100000,'append-only closure participates in following slice');$after=$db->query("SELECT s.*,o.* FROM `{$p}fm2_pilot_otiz_snapshots` s JOIN `{$p}fm2_pilot_otiz_snapshot_objects` o ON o.snapshot_id=s.id WHERE s.id=$one")->fetch_assoc();$ok($before===$after,'accepted snapshot remains immutable');
 $browser=$db->query("SELECT o.* FROM `{$p}fm2_pilot_otiz_snapshot_objects` o WHERE snapshot_id=$twoId")->fetch_assoc();$mode=json_decode($browser['inputs_json'],true)['calculationOperandsSource'];$html='<article><h2>'.htmlspecialchars($browser['regnumber']).'</h2><span>'.((int)$browser['current_progress_bp']/100).'%</span><span>Δ '.(((int)$browser['current_progress_bp']-(int)$browser['previous_progress_bp'])/100).'%</span><small>'.$mode.'</small></article>';$ok(str_contains($html,'77-088421')&&str_contains($html,'60%')&&str_contains($html,'Δ 25%')&&str_contains($html,'native_operational_facts'),'browser projection renders persisted native snapshot');$count=(int)$db->query("SELECT COUNT(*)n FROM `{$p}fm2_checklist_operation_installers` i JOIN `{$p}fm2_checklist_operations` o ON o.client_operation_id=i.client_operation_id")->fetch_assoc()['n'];$ok($count===3,'all server completions retain installer attribution');$ok(!str_contains(json_encode($db->query("SELECT inputs_json FROM `{$p}fm2_pilot_otiz_snapshot_objects`")->fetch_all(MYSQLI_ASSOC)),'synthetic'),'no synthetic fallback enters snapshots');
}finally{foreach($tables as$t)$db->query("DROP TABLE IF EXISTS `{$p}{$t}`");$db->close();}
