<?php declare(strict_types=1);
namespace FMonitor2\AssignmentOrderOriginal;
enum AssignmentOrderOriginalSchemaMigrationStatus:string{case APPLIED='applied';case UNCHANGED='unchanged';case CONFLICT='conflict';}
final readonly class AssignmentOrderOriginalSchemaMigrationResult{public function __construct(private AssignmentOrderOriginalSchemaMigrationStatus$s,private array$t){}public function status():AssignmentOrderOriginalSchemaMigrationStatus{return$this->s;}public function schemaVersion():int{return 2;}public function affectedTables():array{return$this->t;}}
final class AssignmentOrderOriginalVerificationFixtureConflict extends \RuntimeException{public function __construct(){parent::__construct('AssignmentOrderOriginalVerificationFixtureConflict');}}
final class AssignmentOrderOriginalVerificationFixtureUnavailable extends \RuntimeException{public function __construct(){parent::__construct('AssignmentOrderOriginalVerificationFixtureUnavailable');}}
final class AssignmentOrderOriginalSchemaMigration{
private static function legacyApply(\mysqli$d,string$p=''):AssignmentOrderOriginalSchemaMigrationResult{return new AssignmentOrderOriginalSchemaMigrationResult(AssignmentOrderOriginalSchemaMigrationStatus::CONFLICT,[]);}
public static function apply(\mysqli$d,string$p=''):AssignmentOrderOriginalSchemaMigrationResult{return (new AssignmentOrderOriginalSchemaMigrationEngine(new NoOpAssignmentOrderOriginalSchemaMigrationObserver()))->apply($d,$p);}
public static function same(\mysqli$d,string$p,string$t):bool{$a=self::snap($d,$p.$t,$p);$e=self::expected($t);if(($a[0][1]??null)==='utf8mb4_uca1400_ai_ci')$a[0][1]='utf8mb4_unicode_ci';return$a===$e;}
public static function prefix(string$p):void{if(strlen($p)>25||preg_match('/^[A-Za-z0-9_]*$/D',$p)!==1)throw new \InvalidArgumentException('Invalid table prefix.');}
public static function exists(\mysqli$d,string$t):bool{$s=$d->prepare('SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE()AND TABLE_NAME=?');$s->bind_param('s',$t);$s->execute();return$s->get_result()->fetch_row()!==null;}
private static function caps(\mysqli$d,string$p):void{$t=$p.'fm2_process_user_capabilities';if(!self::exists($d,$t))return;$s=$d->prepare('SELECT CONSTRAINT_NAME,CHECK_CLAUSE FROM information_schema.CHECK_CONSTRAINTS WHERE CONSTRAINT_SCHEMA=DATABASE()AND TABLE_NAME=?');$s->bind_param('s',$t);$s->execute();foreach($s->get_result()->fetch_all(MYSQLI_ASSOC)as$r){$clause=strtolower(str_replace(['`',' '],'',(string)$r['CHECK_CLAUSE']));if(!str_contains($clause,'capabilityin('))continue;if(str_contains($clause,'assignment_order.original.upload'))return;$n=$r['CONSTRAINT_NAME'];if(preg_match('/^[A-Za-z0-9_$]{1,64}$/D',$n)!==1)throw new \RuntimeException('Capability schema conflict.');$d->query("ALTER TABLE `{$t}` DROP CONSTRAINT `{$n}`,ADD CONSTRAINT `ck_fm2_process_user_capability_v5` CHECK(capability IN ('assignment_order.prepare','assignment_order.confirm_registration','installation.open','construction_control_engineer','assignment_order.original.upload','assignment_order.original.correct'))");return;}throw new \RuntimeException('Capability schema conflict.');}
private static function norm(string$v):string{$v=strtolower(str_replace(['`',' ',"\n","\r","\t"],'',$v));$v=str_replace("'[[:cntrl:]/\\\\\\\\]'","'[[:cntrl:]/\\\\]'",$v);$v=(string)preg_replace("/!\\(([^()]+)regexp('[^']*')\\)/","$1notregexp$2",$v);while(str_starts_with($v,'(')&&str_ends_with($v,')')){$n=0;$w=true;for($i=0;$i<strlen($v);$i++){if($v[$i]==='(')$n++;elseif($v[$i]===')')$n--;if($n===0&&$i<strlen($v)-1){$w=false;break;}}if(!$w)break;$v=substr($v,1,-1);}$l="revision_number=1andprevious_revision_idisnullandcorrection_reasonisnullandevent_type='assignment_order_original_accepted'";$r="revision_number>1andprevious_revision_idisnotnullandchar_length(trim(correction_reason))between1and500andevent_type='assignment_order_original_corrected'";if($v===$l.'or'.$r||$v==='('.$l.')or('.$r.')')$v='(('.$l.')or('.$r.'))';return$v;}
public static function snap(\mysqli$d,string$t,string$p):array{$s=$d->prepare('SELECT ENGINE,TABLE_COLLATION FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE()AND TABLE_NAME=?');$s->bind_param('s',$t);$s->execute();$pr=array_values($s->get_result()->fetch_assoc()?:[]);$s=$d->prepare('SELECT COLUMN_NAME,LOWER(COLUMN_TYPE)COLUMN_TYPE,IS_NULLABLE,CHARACTER_SET_NAME,COLLATION_NAME,COLUMN_DEFAULT,EXTRA FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE()AND TABLE_NAME=? ORDER BY ORDINAL_POSITION');$s->bind_param('s',$t);$s->execute();$cols=array_map(static function($r){if($r['IS_NULLABLE']==='YES'&&$r['COLUMN_DEFAULT']==='NULL')$r['COLUMN_DEFAULT']=null;return array_values($r);},$s->get_result()->fetch_all(MYSQLI_ASSOC));$s=$d->prepare("SELECT INDEX_NAME,NON_UNIQUE,GROUP_CONCAT(COLUMN_NAME ORDER BY SEQ_IN_INDEX SEPARATOR ',')COLUMNS FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=DATABASE()AND TABLE_NAME=? GROUP BY INDEX_NAME,NON_UNIQUE");$s->bind_param('s',$t);$s->execute();$keys=array_map(static fn($r)=>[$r['INDEX_NAME']==='PRIMARY'?'PRIMARY':((int)$r['NON_UNIQUE']===0?'UNIQUE':'INDEX'),$r['COLUMNS']],$s->get_result()->fetch_all(MYSQLI_ASSOC));sort($keys);$s=$d->prepare('SELECT k.COLUMN_NAME,k.REFERENCED_TABLE_NAME,k.REFERENCED_COLUMN_NAME,r.UPDATE_RULE,r.DELETE_RULE FROM information_schema.KEY_COLUMN_USAGE k JOIN information_schema.REFERENTIAL_CONSTRAINTS r ON r.CONSTRAINT_SCHEMA=k.CONSTRAINT_SCHEMA AND r.CONSTRAINT_NAME=k.CONSTRAINT_NAME WHERE k.TABLE_SCHEMA=DATABASE()AND k.TABLE_NAME=? AND k.REFERENCED_TABLE_NAME IS NOT NULL');$s->bind_param('s',$t);$s->execute();$fk=array_map(static fn($r)=>[$r['COLUMN_NAME'],substr($r['REFERENCED_TABLE_NAME'],strlen($p)),$r['REFERENCED_COLUMN_NAME'],$r['UPDATE_RULE'].'/'.$r['DELETE_RULE']],$s->get_result()->fetch_all(MYSQLI_ASSOC));sort($fk);$s=$d->prepare('SELECT CHECK_CLAUSE FROM information_schema.CHECK_CONSTRAINTS WHERE CONSTRAINT_SCHEMA=DATABASE()AND TABLE_NAME=?');$s->bind_param('s',$t);$s->execute();$ck=array_map(static fn($r)=>MariaDbCheckCanonicalizer::normalize($r['CHECK_CLAUSE']),$s->get_result()->fetch_all(MYSQLI_ASSOC));sort($ck);return[$pr,$cols,$keys,$fk,$ck];}
public static function expected(string$t):array{$k=AssignmentOrderOriginalDatabaseSetupV1::keys()[$t];$f=AssignmentOrderOriginalDatabaseSetupV1::foreignKeys()[$t];$c=AssignmentOrderOriginalDatabaseSetupV1::checks()[$t];sort($k);sort($f);sort($c);return[['InnoDB','utf8mb4_unicode_ci'],AssignmentOrderOriginalDatabaseSetupV1::columnManifest()[$t],$k,$f,$c];}
public static function ddl(string$p,string$t):string{$q=static fn($n)=>'`'.$p.$n.'`';$a=[];foreach(AssignmentOrderOriginalDatabaseSetupV1::columnManifest()[$t]as[$n,$ty,$nu,$cs,$co,$de,$ex]){$x="`{$n}` ".strtoupper($ty);if($cs)$x.=" CHARACTER SET {$cs} COLLATE {$co}";$x.=$nu==='NO'?' NOT NULL':' NULL';if($de!==null)$x.=" DEFAULT '".str_replace("'","''",$de)."'";if($ex)$x.=' '.strtoupper($ex);$a[]=$x;}foreach(AssignmentOrderOriginalDatabaseSetupV1::keys()[$t]as[$kind,$cols]){$list=implode(',',array_map(static fn($x)=>"`{$x}`",explode(',',$cols)));$a[]=($kind==='PRIMARY'?'PRIMARY KEY':($kind==='UNIQUE'?'UNIQUE KEY':'KEY'))."({$list})";}foreach(AssignmentOrderOriginalDatabaseSetupV1::foreignKeys()[$t]as[$col,$rt,$rc,$act])$a[]="FOREIGN KEY(`{$col}`)REFERENCES {$q($rt)}(`{$rc}`)ON UPDATE RESTRICT ON DELETE RESTRICT";foreach(AssignmentOrderOriginalDatabaseSetupV1::sqlChecks()[$t]as$ck)$a[]="CHECK({$ck})";return"CREATE TABLE {$q($t)}(".implode(',',$a).')ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci';}}
