<?php
declare(strict_types=1);
namespace FMonitor2\InstallationProcess;
final class DeadlineTransferCertificateSchemaMigration
{
 private const TABLES=['roots','revisions','operations','pdf_chunks'];
 public static function apply(\mysqli$db,string$p):array{
  if(preg_match('/^[A-Za-z0-9_]{0,25}$/D',$p)!==1)throw new \InvalidArgumentException('INVALID_TABLE_PREFIX');$missing=[];
  foreach(self::TABLES as$s){$n=$p.'fm2_deadline_certificate_'.$s;if(!self::exists($db,$n))$missing[]=$s;elseif(!self::compatible($db,$p,$s))return['applied'=>false,'schemaVersion'=>26,'reason'=>'SCHEMA_MIGRATION_CONFLICT'];}
  foreach($missing as$s)$db->query(self::ddl($p,$s));self::grants($db,$p);return['applied'=>$missing!==[],'schemaVersion'=>26,'tablesCreated'=>array_map(fn($s)=>$p.'fm2_deadline_certificate_'.$s,$missing)];}
 public static function isCompleteCompatible(\mysqli$db,string$p):bool{foreach(self::TABLES as$s)if(!self::exists($db,$p.'fm2_deadline_certificate_'.$s)||!self::compatible($db,$p,$s))return false;return true;}
 private static function exists(\mysqli$db,string$n):bool{$q=$db->prepare('SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=?');$q->execute([$n]);return(bool)$q->get_result()->fetch_column();}
 private static function compatible(\mysqli$db,string$p,string$s):bool{
  $n=$p.'fm2_deadline_certificate_'.$s;$columns=$db->query("SHOW FULL COLUMNS FROM `$n`")->fetch_all(MYSQLI_ASSOC);$a=array_map(fn($r)=>[$r['Field'],$r['Type'],$r['Null'],$r['Extra']],$columns);
  $definitions=['roots'=>[['installation_case_id','bigint(20) unsigned','NO',''],['current_revision_id','bigint(20) unsigned','YES',''],['current_version','int(10) unsigned','NO','']],'revisions'=>[['id','bigint(20) unsigned','NO','auto_increment'],['installation_case_id','bigint(20) unsigned','NO',''],['revision_number','int(10) unsigned','NO',''],['previous_revision_id','bigint(20) unsigned','YES',''],['certificate_date','date','NO',''],['new_deadline','date','NO',''],['correction_reason','varchar(1000)','YES',''],['actor_id','bigint(20) unsigned','NO',''],['recorded_at','varchar(40)','NO',''],['source_label','varchar(500)','NO',''],['source_locator','varchar(500)','NO',''],['pdf_sha256','char(64)','NO',''],['byte_size','int(10) unsigned','NO','']],'operations'=>[['actor_id','bigint(20) unsigned','NO',''],['request_id','char(36)','NO',''],['request_sha256','char(64)','NO',''],['revision_id','bigint(20) unsigned','NO','']],'pdf_chunks'=>[['revision_id','bigint(20) unsigned','NO',''],['chunk_no','smallint(5) unsigned','NO',''],['bytes','mediumblob','NO','']]];
  if($a!==$definitions[$s])return false;foreach($columns as$column)if($column['Default']!==null||(str_contains($column['Type'],'char')&&$column['Collation']!=='utf8mb4_unicode_ci'))return false;
  $expectedUnique=['roots'=>[['installation_case_id']],'revisions'=>[['id'],['installation_case_id','revision_number']],'operations'=>[['actor_id','request_id']],'pdf_chunks'=>[['revision_id','chunk_no']]];$indexes=[];foreach($db->query("SHOW INDEX FROM `$n`")->fetch_all(MYSQLI_ASSOC)as$row)if((int)$row['Non_unique']===0)$indexes[$row['Key_name']][]=$row['Column_name'];$actual=array_values($indexes);sort($actual);$wanted=$expectedUnique[$s];sort($wanted);if($actual!==$wanted||($indexes['PRIMARY']??null)!==$expectedUnique[$s][0])return false;
  $expectedForeign=['roots'=>[],'revisions'=>[['installation_case_id',$p.'fm2_installation_cases','id'],['previous_revision_id',$p.'fm2_deadline_certificate_revisions','id']],'operations'=>[['revision_id',$p.'fm2_deadline_certificate_revisions','id']],'pdf_chunks'=>[['revision_id',$p.'fm2_deadline_certificate_revisions','id']]];$foreign=$db->query("SELECT COLUMN_NAME,REFERENCED_TABLE_NAME,REFERENCED_COLUMN_NAME FROM information_schema.KEY_COLUMN_USAGE WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='".$db->real_escape_string($n)."' AND REFERENCED_TABLE_NAME IS NOT NULL ORDER BY COLUMN_NAME")->fetch_all(MYSQLI_NUM);if($foreign!==$expectedForeign[$s])return false;
  $q=$db->prepare('SELECT ENGINE,TABLE_COLLATION FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=?');$q->execute([$n]);$table=$q->get_result()->fetch_assoc();return$table&&$table['ENGINE']==='InnoDB'&&$table['TABLE_COLLATION']==='utf8mb4_unicode_ci';
 }
 private static function ddl(string$p,string$s):string{$case="`{$p}fm2_installation_cases`";$rev="`{$p}fm2_deadline_certificate_revisions`";$t="`{$p}fm2_deadline_certificate_{$s}`";return match($s){'roots'=>"CREATE TABLE $t(installation_case_id BIGINT UNSIGNED NOT NULL,current_revision_id BIGINT UNSIGNED NULL,current_version INT UNSIGNED NOT NULL,PRIMARY KEY(installation_case_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",'revisions'=>"CREATE TABLE $t(id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,installation_case_id BIGINT UNSIGNED NOT NULL,revision_number INT UNSIGNED NOT NULL,previous_revision_id BIGINT UNSIGNED NULL,certificate_date DATE NOT NULL,new_deadline DATE NOT NULL,correction_reason VARCHAR(1000) NULL,actor_id BIGINT UNSIGNED NOT NULL,recorded_at VARCHAR(40) NOT NULL,source_label VARCHAR(500) NOT NULL,source_locator VARCHAR(500) NOT NULL,pdf_sha256 CHAR(64) NOT NULL,byte_size INT UNSIGNED NOT NULL,PRIMARY KEY(id),UNIQUE KEY installation_revision(installation_case_id,revision_number),CONSTRAINT `{$p}dtc_rev_case_fk` FOREIGN KEY(installation_case_id) REFERENCES $case(id),CONSTRAINT `{$p}dtc_rev_prev_fk` FOREIGN KEY(previous_revision_id) REFERENCES $rev(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",'operations'=>"CREATE TABLE $t(actor_id BIGINT UNSIGNED NOT NULL,request_id CHAR(36) NOT NULL,request_sha256 CHAR(64) NOT NULL,revision_id BIGINT UNSIGNED NOT NULL,PRIMARY KEY(actor_id,request_id),CONSTRAINT `{$p}dtc_op_rev_fk` FOREIGN KEY(revision_id) REFERENCES $rev(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",default=>"CREATE TABLE $t(revision_id BIGINT UNSIGNED NOT NULL,chunk_no SMALLINT UNSIGNED NOT NULL,bytes MEDIUMBLOB NOT NULL,PRIMARY KEY(revision_id,chunk_no),CONSTRAINT `{$p}dtc_chunk_rev_fk` FOREIGN KEY(revision_id) REFERENCES $rev(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci"};}
 private static function grants(\mysqli$db,string$p):void{foreach(['fkr_operator'=>['deadline_certificate.read','deadline_certificate.write'],'manager'=>['deadline_certificate.read','deadline_certificate.write'],'otiz_specialist'=>['deadline_certificate.read']]as$r=>$ps)foreach($ps as$x){$q=$db->prepare("INSERT IGNORE INTO `{$p}fm2_pilot_role_permissions`(role_id,permission) SELECT role_id,? FROM `{$p}fm2_pilot_roles` WHERE BINARY code=?");$q->execute([$x,$r]);}}
}
