<?php
declare(strict_types=1);
namespace FMonitor2\InstallationProcess;

/** Additive v34 transition from engineer-keyed schedules to object-keyed plans. */
final class InspectionPlanningObjectBoundSchemaMigration
{
    public const SCHEDULES='fm2_pilot_inspection_schedules';
    public const EVENTS='fm2_pilot_inspection_schedule_events';
    public static function definitions(string$prefix,string$collation):array
    {
        $column=static fn(string$name,string$type,string$extra='',?string$columnCollation=null,bool$nullable=false):array=>compact('name','type','extra','columnCollation','nullable');
        $index=static fn(string$name,bool$unique,array$columns):array=>compact('name','unique','columns');
        $schemas=[self::SCHEDULES=>['columns'=>[$column('id','BIGINT UNSIGNED','auto_increment'),$column('installation_case_id','BIGINT UNSIGNED'),$column('legacy_object_id','BIGINT UNSIGNED'),$column('control_engineer_user_id','BIGINT UNSIGNED'),$column('inspection_date','DATE'),$column('scheduled_by_user_id','BIGINT UNSIGNED'),$column('scheduled_at','VARCHAR(40)')],'indexes'=>[$index('PRIMARY',true,['id']),$index('unique_planned_inspection',true,['installation_case_id','inspection_date']),$index('calendar_date',false,['inspection_date','id']),$index('engineer_day',false,['control_engineer_user_id','inspection_date','id'])],'checks'=>[]],self::EVENTS=>['columns'=>[$column('id','BIGINT UNSIGNED','auto_increment'),$column('schedule_id','BIGINT UNSIGNED'),$column('installation_case_id','BIGINT UNSIGNED'),$column('event_type','VARCHAR(80)'),$column('event_version','INT UNSIGNED',nullable:true),$column('request_identity','CHAR(36)',columnCollation:'utf8mb4_bin',nullable:true),$column('request_fingerprint','CHAR(64)',columnCollation:'utf8mb4_bin',nullable:true),$column('payload_json','LONGTEXT','', 'utf8mb4_bin'),$column('actor_user_id','BIGINT UNSIGNED'),$column('occurred_at','VARCHAR(40)')],'indexes'=>[$index('PRIMARY',true,['id']),$index('request_identity',true,['request_identity']),$index('schedule_version',true,['schedule_id','event_version']),$index('schedule_id',false,['schedule_id','id']),$index('installation_case_id',false,['installation_case_id','id'])],'checks'=>['json_valid(payload_json)']]];
        $out=[];foreach($schemas as$name=>$schema)$out[$name]=['ddl'=>self::render($prefix.$name,$schema,$collation),'manifest'=>MariaDbInspectionPlanningSchemaFingerprint::manifest($schema,$collation)];return$out;
    }
    public static function apply(\mysqli|\yii\db\Connection $connection,string $prefix='',?string $today=null):array
    {
        $owned=false;$db=$connection;
        if($connection instanceof \yii\db\Connection){$parts=[];foreach(explode(';',substr($connection->dsn,6))as$part){[$key,$value]=array_pad(explode('=',$part,2),2,'');$parts[$key]=$value;}$db=new \mysqli($parts['host']??'127.0.0.1',$connection->username,$connection->password,$parts['dbname']??'',(int)($parts['port']??3306));$owned=true;}
        try{return self::applyMysqli($db,$prefix,$today);}finally{if($owned)$db->close();}
    }
    private static function applyMysqli(\mysqli $db,string $prefix,?string $today):array
    {
        IdentityAccessDefinitionSchemaMigration::assertPrefix($prefix);
        $today ??= (new \DateTimeImmutable('now',new \DateTimeZone('Europe/Moscow')))->format('Y-m-d');
        $s=$prefix.self::SCHEDULES;$e=$prefix.self::EVENTS;$changed=[];
        if(!self::table($db,$s)||!self::table($db,$e))return self::conflict([$s,$e]);
        if(self::ready($db,$prefix))return self::adoptReadyLegacyRows($db,$s,$e,$today);
        $scheduleIndex=self::index($db,$s,'unique_planned_inspection');
        if(!in_array($scheduleIndex,['installation_case_id,control_engineer_user_id,inspection_date','installation_case_id,inspection_date'],true))return self::conflict([$s]);
        if(!self::indexIsUnique($db,$s,'unique_planned_inspection'))return self::conflict([$s]);
        if(!self::eventColumnsSupported($db,$e))return self::conflict([$e]);
        if(!self::partialReceiptsCompatible($db,$e))return self::conflict([$e]);
        foreach(['request_identity'=>'request_identity','schedule_version'=>'schedule_id,event_version']as$name=>$expected)if(self::index($db,$e,$name)!==null&&(!self::indexIsUnique($db,$e,$name)||self::index($db,$e,$name)!==$expected))return self::conflict([$e]);
        if($scheduleIndex==='installation_case_id,control_engineer_user_id,inspection_date'){$q=$db->prepare("SELECT installation_case_id FROM `{$s}` WHERE inspection_date>=? GROUP BY installation_case_id HAVING COUNT(*)>1 LIMIT 1");$q->execute([$today]);if($q->get_result()->fetch_row())return self::conflict([$s]);$db->query("ALTER TABLE `{$s}` DROP INDEX unique_planned_inspection, ADD UNIQUE INDEX unique_planned_inspection(installation_case_id,inspection_date)");$changed[]=$s;}
        $columns=self::columns($db,$e);
        if(!in_array('event_version',$columns,true)){$db->query("ALTER TABLE `{$e}` ADD event_version INT UNSIGNED NULL AFTER event_type");$changed[]=$e;$columns=self::columns($db,$e);}
        if(!in_array('request_identity',$columns,true)){$db->query("ALTER TABLE `{$e}` ADD request_identity CHAR(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL AFTER event_version");$changed[]=$e;$columns=self::columns($db,$e);}
        if(!in_array('request_fingerprint',$columns,true)){$db->query("ALTER TABLE `{$e}` ADD request_fingerprint CHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL AFTER request_identity");$changed[]=$e;}
        self::backfillEvents($db,$e);
        if(self::index($db,$e,'request_identity')===null){$db->query("ALTER TABLE `{$e}` ADD UNIQUE INDEX request_identity(request_identity)");$changed[]=$e;}elseif(self::index($db,$e,'request_identity')!=='request_identity')return self::conflict([$e]);
        if(self::index($db,$e,'schedule_version')===null){$db->query("ALTER TABLE `{$e}` ADD UNIQUE INDEX schedule_version(schedule_id,event_version)");$changed[]=$e;}elseif(self::index($db,$e,'schedule_version')!=='schedule_id,event_version')return self::conflict([$e]);
        if(!self::ready($db,$prefix))return self::conflict([$s,$e]);
        $adoption=self::adoptReadyLegacyRows($db,$s,$e,$today);if(($adoption['reason']??null)==='SCHEMA_MIGRATION_CONFLICT')return$adoption;
        return['applied'=>$changed!==[]||$adoption['applied'],'schemaVersion'=>34,'tablesUpgraded'=>array_values(array_unique([...$changed,...$adoption['tablesUpgraded']]))];
    }
    private static function table(\mysqli$db,string$t):bool{$q=$db->prepare('SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=?');$q->execute([$t]);return(int)$q->get_result()->fetch_column()===1;}
    private static function columns(\mysqli$db,string$t):array{$q=$db->prepare('SELECT COLUMN_NAME FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=? ORDER BY ORDINAL_POSITION');$q->execute([$t]);return array_column($q->get_result()->fetch_all(MYSQLI_ASSOC),'COLUMN_NAME');}
    private static function index(\mysqli$db,string$t,string$i):?string{$q=$db->prepare('SELECT GROUP_CONCAT(COLUMN_NAME ORDER BY SEQ_IN_INDEX) c FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=? AND INDEX_NAME=? GROUP BY INDEX_NAME,NON_UNIQUE');$q->execute([$t,$i]);$v=$q->get_result()->fetch_column();return$v===false?null:(string)$v;}
    private static function indexIsUnique(\mysqli$db,string$t,string$i):bool{$q=$db->prepare('SELECT DISTINCT NON_UNIQUE FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=? AND INDEX_NAME=?');$q->execute([$t,$i]);$rows=$q->get_result()->fetch_all(MYSQLI_NUM);return count($rows)===1&&(int)$rows[0][0]===0;}
    private static function ready(\mysqli$db,string$prefix):bool{$collation=IdentityAccessDefinitionSchemaMigration::databaseCollation($db);foreach(self::definitions($prefix,$collation)as$name=>$definition)if(!MariaDbInspectionPlanningSchemaFingerprint::matches($db,$prefix.$name,$definition['manifest'],$collation))return false;return true;}
    private static function adoptReadyLegacyRows(\mysqli$db,string$s,string$e,string$today):array
    {
        $db->begin_transaction();try{$roots=$db->query("SELECT s.*,e.id event_id,e.event_type,e.payload_json FROM `{$s}`s LEFT JOIN `{$e}`e ON e.schedule_id=s.id AND e.event_version=(SELECT MAX(x.event_version)FROM `{$e}`x WHERE x.schedule_id=s.id) ORDER BY s.id FOR UPDATE")->fetch_all(MYSQLI_ASSOC);$missing=[];$current=[];foreach($roots as$r){$date=$r['inspection_date'];$type=$r['event_type'];if($r['event_id']===null)$missing[]=$r;else{$payload=json_decode($r['payload_json'],true,flags:JSON_THROW_ON_ERROR);$date=$payload['newDate']??$payload['inspectionDate']??$date;}if($type!=='inspection_cancelled'&&$date>=$today){$case=(string)$r['installation_case_id'];if(isset($current[$case])){$db->rollBack();return self::conflict([$s]);}$current[$case]=true;}}if($missing===[]){$db->commit();return['applied'=>false,'schemaVersion'=>34,'tablesUpgraded'=>[]];}$insert=$db->prepare("INSERT INTO `{$e}`(schedule_id,installation_case_id,event_type,event_version,request_identity,request_fingerprint,payload_json,actor_user_id,occurred_at)VALUES(?,?,'inspection_scheduled',1,?,?,?,?,?)");foreach($missing as$r){$request=sprintf('00000000-0000-4000-8000-%012d',(int)$r['id']);$payload=json_encode(['scheduleId'=>(int)$r['id'],'inspectionDate'=>$r['inspection_date']],JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR);$finger=hash('sha256',json_encode(['legacy-root',(int)$r['id'],$r['inspection_date']],JSON_THROW_ON_ERROR));$insert->execute([(int)$r['id'],(int)$r['installation_case_id'],$request,$finger,$payload,(int)$r['scheduled_by_user_id'],$r['scheduled_at']]);}$db->commit();return['applied'=>true,'schemaVersion'=>34,'tablesUpgraded'=>[$e]];}catch(\Throwable$x){$db->rollback();throw$x;}
    }
    private static function eventColumnsSupported(\mysqli$db,string$e):bool{$columns=self::columns($db,$e);$base=['id','schedule_id','installation_case_id','event_type','payload_json','actor_user_id','occurred_at'];foreach($base as$c)if(!in_array($c,$columns,true))return false;return count(array_diff($columns,[...$base,'event_version','request_identity','request_fingerprint']))===0;}
    private static function partialReceiptsCompatible(\mysqli$db,string$e):bool{$columns=self::columns($db,$e);$optional=array_values(array_intersect(['event_version','request_identity','request_fingerprint'],$columns));if($optional===[])return true;$select=implode(',',array_map(static fn(string$c):string=>"`{$c}`",$optional));$rows=$db->query("SELECT id,schedule_id,event_type,payload_json,actor_user_id,occurred_at,{$select} FROM `{$e}` ORDER BY schedule_id,id")->fetch_all(MYSQLI_ASSOC);$versions=[];$requests=[];$sequence=[];$migrationFrontier=self::index($db,$e,'request_identity')===null||self::index($db,$e,'schedule_version')===null;foreach($rows as$r){$sid=(int)$r['schedule_id'];$expectedVersion=($sequence[$sid]??0)+1;$sequence[$sid]=$expectedVersion;$expectedRequest=sprintf('00000000-0000-4000-8000-%012d',(int)$r['id']);$expectedFingerprint=hash('sha256',json_encode(['legacy-event',(int)$r['id'],$sid,$r['event_type'],$r['payload_json'],$r['actor_user_id'],$r['occurred_at']],JSON_THROW_ON_ERROR));if(in_array('event_version',$optional,true)&&$r['event_version']!==null){$key=$sid.':'.$r['event_version'];if(isset($versions[$key])||($migrationFrontier&&(int)$r['event_version']!==$expectedVersion))return false;$versions[$key]=true;}if(in_array('request_identity',$optional,true)&&$r['request_identity']!==null){$request=(string)$r['request_identity'];if(isset($requests[$request])||($migrationFrontier&&!hash_equals($request,$expectedRequest)))return false;$requests[$request]=true;}if(in_array('request_fingerprint',$optional,true)&&$r['request_fingerprint']!==null){$finger=(string)$r['request_fingerprint'];if(!preg_match('/^[0-9a-f]{64}$/D',$finger)||($migrationFrontier&&!hash_equals($finger,$expectedFingerprint)))return false;}}return true;}
    private static function backfillEvents(\mysqli$db,string$e):void{$rows=$db->query("SELECT id,schedule_id,event_type,payload_json,actor_user_id,occurred_at,event_version,request_identity,request_fingerprint FROM `{$e}` ORDER BY schedule_id,id")->fetch_all(MYSQLI_ASSOC);$versions=[];$u=$db->prepare("UPDATE `{$e}` SET event_version=?,request_identity=?,request_fingerprint=? WHERE id=?");foreach($rows as$r){$sid=(int)$r['schedule_id'];$v=($versions[$sid]??0)+1;$versions[$sid]=$v;$request=sprintf('00000000-0000-4000-8000-%012d',(int)$r['id']);$finger=hash('sha256',json_encode(['legacy-event',(int)$r['id'],$sid,$r['event_type'],$r['payload_json'],$r['actor_user_id'],$r['occurred_at']],JSON_THROW_ON_ERROR));$partial=$r['event_version']===null||$r['request_identity']===null||$r['request_fingerprint']===null;if(!$partial)continue;if(($r['event_version']!==null&&(int)$r['event_version']!==$v)||($r['request_identity']!==null&&!hash_equals((string)$r['request_identity'],$request))||($r['request_fingerprint']!==null&&!hash_equals((string)$r['request_fingerprint'],$finger)))throw new \RuntimeException('Inconsistent migration backfill.');$u->execute([$v,$request,$finger,(int)$r['id']]);}}
    private static function conflict(array$t):array{return['applied'=>false,'schemaVersion'=>34,'reason'=>'SCHEMA_MIGRATION_CONFLICT','conflictingTables'=>array_values(array_unique($t))];}
    private static function render(string$table,array$schema,string$collation):string{$parts=[];foreach($schema['columns']as$column){$sql=$column['name'].' '.$column['type'];if($column['columnCollation']!==null)$sql.=' CHARACTER SET utf8mb4 COLLATE '.$column['columnCollation'];$sql.=($column['nullable']??false)?' NULL':' NOT NULL';if($column['extra']==='auto_increment')$sql.=' AUTO_INCREMENT';$parts[]=$sql;}foreach($schema['indexes']as$index){$head=$index['name']==='PRIMARY'?'PRIMARY KEY':($index['unique']?'UNIQUE KEY ':'KEY ').$index['name'];$parts[]=$head.'('.implode(',',$index['columns']).')';}foreach($schema['checks']as$check){$name='json_valid_'.substr(hash('sha256',$table),0,16);$parts[]="CONSTRAINT `{$name}` CHECK({$check})";}return'CREATE TABLE `'.$table.'`('.implode(',',$parts).") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE `{$collation}`";}
}
