<?php
declare(strict_types=1);
namespace FMonitor2\InstallationProcess;
final class LegacyControlEngineerMigrationSchema
{
 public static function apply(\mysqli$db,string$p):array{
  if(preg_match('/^[A-Za-z0-9_]{0,25}$/D',$p)!==1)throw new \InvalidArgumentException('INVALID_TABLE_PREFIX');
  $links=$p.'fm2_legacy_identity_links';$events=$p.'fm2_legacy_identity_link_events';$ops=$p.'fm2_engineer_migration_operations';$assignment=$p.'fm2_control_engineer_assignments';
  $states=[self::tableState($db,$links,self::linkColumns(),[['PRIMARY',['link_id'],true],['uq_lil_request',['request_id'],true],['ix_lil_local',['local_user_id'],false],['ix_lil_legacy',['legacy_user_id'],false]]),self::tableState($db,$events,self::eventColumns(),[['PRIMARY',['event_id'],true],['uq_lile_request',['request_id'],true]]),self::tableState($db,$ops,self::operationColumns(),[['PRIMARY',['operation_id'],true]])];
  $assignmentState=self::assignmentState($db,$p,$assignment);$allAbsent=$states===['absent','absent','absent'];$allCompatible=$states===['compatible','compatible','compatible'];
  if($allCompatible&&$assignmentState==='complete')return['applied'=>false,'schemaVersion'=>29,'tablesCreated'=>[]];
  if(!$allAbsent||!in_array($assignmentState,['predecessor','complete'],true))throw new \DomainException('SCHEMA_MIGRATION_CONFLICT');
  if($assignmentState==='predecessor')foreach(['assignment_source'=>"VARCHAR(30) NOT NULL DEFAULT 'manual'",'source_operation_id'=>'CHAR(36) NULL','source_legacy_object_id'=>'BIGINT UNSIGNED NULL','source_legacy_user_id'=>'BIGINT UNSIGNED NULL']as$column=>$definition)$db->query("ALTER TABLE `$assignment` ADD COLUMN `$column` $definition");
  $db->query("CREATE TABLE `$links`(link_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,local_user_id BIGINT UNSIGNED NOT NULL,legacy_user_id BIGINT UNSIGNED NOT NULL,legacy_name_snapshot VARCHAR(300) NOT NULL,legacy_email_snapshot VARCHAR(300) NOT NULL,legacy_status_snapshot TINYINT NOT NULL,legacy_role_id_snapshot BIGINT UNSIGNED NOT NULL,legacy_role_status_snapshot TINYINT NOT NULL,linked_by_user_id BIGINT UNSIGNED NOT NULL,linked_at_utc DATETIME NOT NULL,request_id CHAR(36) NOT NULL,request_fingerprint CHAR(64) NOT NULL,supersedes_link_id BIGINT UNSIGNED NULL,superseded_by_link_id BIGINT UNSIGNED NULL,correction_reason VARCHAR(500) NULL,UNIQUE KEY uq_lil_request(request_id),KEY ix_lil_local(local_user_id),KEY ix_lil_legacy(legacy_user_id))ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
  $db->query("CREATE TABLE `$events`(event_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,link_id BIGINT UNSIGNED NOT NULL,event_type VARCHAR(30) NOT NULL,actor_user_id BIGINT UNSIGNED NOT NULL,occurred_at_utc DATETIME NOT NULL,request_id CHAR(36) NOT NULL,UNIQUE KEY uq_lile_request(request_id))ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
  $db->query("CREATE TABLE `$ops`(operation_id CHAR(36) PRIMARY KEY,preview_digest CHAR(64) NOT NULL,source_fingerprint CHAR(64) NOT NULL,report_json LONGTEXT NOT NULL,actor_user_id BIGINT UNSIGNED NOT NULL,applied_at_utc DATETIME NOT NULL)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
  return['applied'=>true,'schemaVersion'=>29,'tablesCreated'=>[$links,$events,$ops]];
 }
 private static function tableState(\mysqli$db,string$table,array$expectedColumns,array$expectedIndexes):string{
  $s=$db->prepare('SELECT ENGINE,TABLE_COLLATION FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=?');$s->execute([$table]);$meta=$s->get_result()->fetch_assoc();if($meta===null)return'absent';if($meta['ENGINE']!=='InnoDB'||$meta['TABLE_COLLATION']!=='utf8mb4_unicode_ci')return'malformed';
  $columns=$db->query("SHOW FULL COLUMNS FROM `$table`")->fetch_all(MYSQLI_ASSOC);$actual=array_map(static fn($r)=>[$r['Field'],$r['Type'],$r['Null'],$r['Default'],$r['Extra'],$r['Collation']],$columns);if($actual!==$expectedColumns)return'malformed';
  $indexes=[];foreach($db->query("SHOW INDEX FROM `$table`")->fetch_all(MYSQLI_ASSOC)as$row){$name=$row['Key_name'];$indexes[$name]??=[[],(int)$row['Non_unique']===0];$indexes[$name][0][(int)$row['Seq_in_index']]=(string)$row['Column_name'];}$normalized=[];foreach($indexes as$name=>[$cols,$unique]){ksort($cols);$normalized[]=[$name,array_values($cols),$unique];}usort($normalized,static fn($a,$b)=>strcmp($a[0],$b[0]));usort($expectedIndexes,static fn($a,$b)=>strcmp($a[0],$b[0]));return$normalized===$expectedIndexes?'compatible':'malformed';
 }
 private static function assignmentState(\mysqli$db,string$p,string$table):string{
  $s=$db->prepare('SELECT ENGINE,TABLE_COLLATION FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=?');$s->execute([$table]);$meta=$s->get_result()->fetch_assoc();if($meta===null||$meta['ENGINE']!=='InnoDB'||$meta['TABLE_COLLATION']!=='utf8mb4_unicode_ci')return'malformed';
  $columns=$db->query("SHOW FULL COLUMNS FROM `$table`")->fetch_all(MYSQLI_ASSOC);$actual=array_map(static fn($r)=>[$r['Field'],$r['Type'],$r['Null'],$r['Default'],$r['Extra']],$columns);$expected=self::assignmentColumns();$kind=$actual===$expected?'complete':($actual===array_slice($expected,0,14)?'predecessor':'malformed');if($kind==='malformed')return$kind;foreach($columns as$row)if(str_contains($row['Type'],'char')&&$row['Collation']!=='utf8mb4_unicode_ci')return'malformed';
  $indexes=[];foreach($db->query("SHOW INDEX FROM `$table`")->fetch_all(MYSQLI_ASSOC)as$row)$indexes[$row['Key_name']][(int)$row['Seq_in_index']]=[(string)$row['Column_name'],(int)$row['Non_unique']===0];foreach($indexes as&$parts)ksort($parts);unset($parts);$expectedIndexes=['PRIMARY'=>[1=>['assignment_id',true]],'uq_control_case_sequence'=>[1=>['installation_case_id',true],2=>['assignment_sequence',true]],'uq_control_request'=>[1=>['request_id',true]],'ix_control_object'=>[1=>['object_id',false],2=>['assignment_sequence',false]],$p.'control_assignment_previous_fk'=>[1=>['previous_assignment_id',false]],$p.'control_assignment_bootstrap_fk'=>[1=>['bootstrap_application_id',false]]];ksort($indexes);ksort($expectedIndexes);if($indexes!==$expectedIndexes)return'malformed';
  $s=$db->prepare('SELECT COLUMN_NAME,REFERENCED_TABLE_NAME,REFERENCED_COLUMN_NAME FROM information_schema.KEY_COLUMN_USAGE WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=? AND REFERENCED_TABLE_NAME IS NOT NULL ORDER BY COLUMN_NAME');$s->execute([$table]);$foreign=$s->get_result()->fetch_all(MYSQLI_NUM);$expectedForeign=[['bootstrap_application_id',$p.'fm2_assignment_order_applications','application_id'],['installation_case_id',$p.'fm2_installation_cases','id'],['previous_assignment_id',$table,'assignment_id']];if($foreign!==$expectedForeign)return'malformed';$s=$db->prepare('SELECT CHECK_CLAUSE FROM information_schema.CHECK_CONSTRAINTS WHERE CONSTRAINT_SCHEMA=DATABASE() AND TABLE_NAME=?');$s->execute([$table]);$checks=array_map(static fn($r)=>strtolower(str_replace(['`',' ','(',')'],'',$r['CHECK_CLAUSE'])),$s->get_result()->fetch_all(MYSQLI_ASSOC));sort($checks);if($checks!==['assignment_sequence>0'])return'malformed';return$kind;
 }
 private static function linkColumns():array{return[['link_id','bigint(20) unsigned','NO',null,'auto_increment',null],['local_user_id','bigint(20) unsigned','NO',null,'',null],['legacy_user_id','bigint(20) unsigned','NO',null,'',null],['legacy_name_snapshot','varchar(300)','NO',null,'','utf8mb4_unicode_ci'],['legacy_email_snapshot','varchar(300)','NO',null,'','utf8mb4_unicode_ci'],['legacy_status_snapshot','tinyint(4)','NO',null,'',null],['legacy_role_id_snapshot','bigint(20) unsigned','NO',null,'',null],['legacy_role_status_snapshot','tinyint(4)','NO',null,'',null],['linked_by_user_id','bigint(20) unsigned','NO',null,'',null],['linked_at_utc','datetime','NO',null,'',null],['request_id','char(36)','NO',null,'','utf8mb4_unicode_ci'],['request_fingerprint','char(64)','NO',null,'','utf8mb4_unicode_ci'],['supersedes_link_id','bigint(20) unsigned','YES',null,'',null],['superseded_by_link_id','bigint(20) unsigned','YES',null,'',null],['correction_reason','varchar(500)','YES',null,'','utf8mb4_unicode_ci']];}
 private static function eventColumns():array{return[['event_id','bigint(20) unsigned','NO',null,'auto_increment',null],['link_id','bigint(20) unsigned','NO',null,'',null],['event_type','varchar(30)','NO',null,'','utf8mb4_unicode_ci'],['actor_user_id','bigint(20) unsigned','NO',null,'',null],['occurred_at_utc','datetime','NO',null,'',null],['request_id','char(36)','NO',null,'','utf8mb4_unicode_ci']];}
 private static function operationColumns():array{return[['operation_id','char(36)','NO',null,'','utf8mb4_unicode_ci'],['preview_digest','char(64)','NO',null,'','utf8mb4_unicode_ci'],['source_fingerprint','char(64)','NO',null,'','utf8mb4_unicode_ci'],['report_json','longtext','NO',null,'','utf8mb4_unicode_ci'],['actor_user_id','bigint(20) unsigned','NO',null,'',null],['applied_at_utc','datetime','NO',null,'',null]];}
 private static function assignmentColumns():array{return[['assignment_id','bigint(20) unsigned','NO',null,'auto_increment'],['installation_case_id','bigint(20) unsigned','NO',null,''],['object_id','bigint(20) unsigned','NO',null,''],['assignment_sequence','int(10) unsigned','NO',null,''],['engineer_user_id','bigint(20) unsigned','NO',null,''],['engineer_fio_snapshot','varchar(300)','NO',null,''],['engineer_position_snapshot','varchar(300)','NO',null,''],['previous_assignment_id','bigint(20) unsigned','YES',null,''],['previous_engineer_user_id','bigint(20) unsigned','YES',null,''],['bootstrap_application_id','bigint(20) unsigned','YES',null,''],['assigned_by_user_id','bigint(20) unsigned','NO',null,''],['assigned_at_utc','datetime','NO',null,''],['request_id','char(36)','NO',null,''],['request_fingerprint','char(64)','NO',null,''],['assignment_source','varchar(30)','NO','manual',''],['source_operation_id','char(36)','YES',null,''],['source_legacy_object_id','bigint(20) unsigned','YES',null,''],['source_legacy_user_id','bigint(20) unsigned','YES',null,'']];}
}
