<?php
declare(strict_types=1);
namespace FMonitor2\InstallationProcess;

final readonly class LegacyControlEngineerMigration
{
 public function __construct(private \mysqli$db,private string$p,private string$l){}
 public function preview(array$ids,string$operation,bool$insideTransaction=false):array{
  if(!$insideTransaction){$this->db->query('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');$this->db->query('START TRANSACTION READ ONLY, WITH CONSISTENT SNAPSHOT');}
  $all=$ids===[];$targets=$all?$this->rows("SELECT legacy_installation_object_id object_id FROM `{$this->p}fm2_installation_cases` ORDER BY legacy_installation_object_id"):array_map(static fn($id)=>['object_id'=>$id],$ids);$rows=[];$authority=[];
  foreach($targets as$t){$id=(int)$t['object_id'];$case=$this->rows("SELECT id FROM `{$this->p}fm2_installation_cases` WHERE legacy_installation_object_id=?",[$id]);if($case===[]){$rows[]=$this->row($id,'skipped','OBJECT_NOT_IMPORTED');$authority[]=[$id,null,null,null,null,null,null,null,null,null,null,null];continue;}$caseId=(int)$case[0]['id'];$m=$this->rows("SELECT responsstroicontrol FROM `{$this->l}fm_maintable` WHERE id=?",[$id]);if(count($m)!==1){$rows[]=$this->row($id,'conflict','SOURCE_CORRUPT');$authority[]=[$id,$caseId,null,null,null,null,null,null,null,null,null,null];continue;}$legacyId=(int)$m[0]['responsstroicontrol'];$u=$legacyId>0?$this->rows("SELECT u.id,u.status,r.status role_status FROM `{$this->l}users`u LEFT JOIN `{$this->l}users_roles`r ON r.id=u.role_id WHERE u.id=?",[$legacyId]):[];$links=$legacyId>0?$this->rows("SELECT link_id,local_user_id FROM `{$this->p}fm2_legacy_identity_links` WHERE legacy_user_id=? AND superseded_by_link_id IS NULL ORDER BY link_id",[$legacyId]):[];$link=count($links)===1?$links[0]:null;$a=$this->rows("SELECT assignment_id,engineer_user_id,assignment_source,source_operation_id,source_legacy_object_id,source_legacy_user_id FROM `{$this->p}fm2_control_engineer_assignments` WHERE installation_case_id=? ORDER BY assignment_sequence DESC",[$caseId]);$current=$a[0]??null;
   $local=$link===null?[]:$this->rows("SELECT u.status,r.status role_status,r.code FROM `{$this->p}fm2_pilot_users`u LEFT JOIN `{$this->p}fm2_pilot_user_roles`ur ON ur.user_id=u.user_id LEFT JOIN `{$this->p}fm2_pilot_roles`r ON r.role_id=ur.role_id WHERE u.user_id=? ORDER BY r.role_id",[(int)$link['local_user_id']]);$eligibleLocal=array_values(array_filter($local,static fn($r)=>($r['code']??null)==='construction_control_engineer'&&(int)($r['role_status']??0)===1));$ls=$u[0]['status']??null;$lrs=$u[0]['role_status']??null;$localStatus=$local[0]['status']??null;$localRole=$local[0]['role_status']??null;$authority[]=[$id,$caseId,$legacyId,$ls===null?null:(int)$ls,$lrs===null?null:(int)$lrs,$link===null?null:(int)$link['link_id'],$link===null?null:(int)$link['local_user_id'],$localStatus===null?null:(int)$localStatus,$localRole===null?null:(int)$localRole,$current===null?null:(int)$current['assignment_id'],$current===null?null:(int)$current['engineer_user_id'],$current['assignment_source']??null];if($eligibleLocal===[]&&$local!==[])$local[0]['role_status']=0;
   if($current!==null){$valid=($current['assignment_source']??'manual')!=='legacy_fmonitor'||(preg_match('/^[0-9a-f-]{36}$/D',(string)$current['source_operation_id'])===1&&(int)$current['source_legacy_object_id']===$id&&(int)$current['source_legacy_user_id']===$legacyId);if(!$valid)$rows[]=$this->row($id,'conflict','SOURCE_CORRUPT',$legacyId,$link===null?null:(int)$link['local_user_id']);elseif(($current['assignment_source']??'manual')==='legacy_fmonitor'&&(int)$current['engineer_user_id']===($link===null?0:(int)$link['local_user_id']))$rows[]=$this->row($id,'already_applied',null,$legacyId,(int)$link['local_user_id']);else$rows[]=$this->row($id,'conflict','CURRENT_ASSIGNMENT_DIFFERS',$legacyId,$link===null?null:(int)$link['local_user_id']);continue;}
   if($legacyId<1)$rows[]=$this->row($id,'skipped','LEGACY_ENGINEER_MISSING');elseif($u===[])$rows[]=$this->row($id,'skipped','LEGACY_USER_NOT_FOUND',$legacyId);elseif((int)$u[0]['status']!==1||(int)$u[0]['role_status']!==1)$rows[]=$this->row($id,'skipped','LEGACY_USER_INACTIVE',$legacyId);elseif(count($links)>1)$rows[]=$this->row($id,'conflict','IDENTITY_LINK_AMBIGUOUS',$legacyId);elseif($link===null)$rows[]=$this->row($id,'skipped','IDENTITY_LINK_MISSING',$legacyId);elseif(count($eligibleLocal)!==1||(int)$localStatus!==1)$rows[]=$this->row($id,'skipped','LOCAL_ENGINEER_INELIGIBLE',$legacyId,(int)$link['local_user_id']);else$rows[]=$this->row($id,'ready',null,$legacyId,(int)$link['local_user_id']);
  }
  usort($rows,static fn($a,$b)=>$a['objectId']<=>$b['objectId']);usort($authority,static fn($a,$b)=>$a[0]<=>$b[0]);$counts=['selected'=>count($rows),'ready'=>0,'alreadyApplied'=>0,'skipped'=>0,'conflict'=>0];foreach($rows as$r){$k=$r['status']==='already_applied'?'alreadyApplied':$r['status'];$counts[$k]++;}$doc=['version'=>1,'operationId'=>$operation,'sourceFingerprint'=>hash('sha256',json_encode($authority,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR)),'counts'=>$counts,'rows'=>$rows];$doc['digest']=hash('sha256',json_encode($doc,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR));if(!$insideTransaction)$this->db->commit();return$doc;
 }
 public function apply(array$doc,int$actorUserId,string$assignedAtUtc):array{
  $operation=$doc['operationId'];$ids=array_map(static fn($r)=>(int)$r['objectId'],$doc['rows']);$fresh=$this->preview($ids,$operation);$existing=$this->rows("SELECT preview_digest,source_fingerprint,report_json FROM `{$this->p}fm2_engineer_migration_operations` WHERE operation_id=?",[$operation]);if($existing!==[]){$reportRows=array_map(static fn($r)=>['objectId'=>$r['objectId'],'status'=>$r['status']==='ready'?'applied':$r['status'],'reasonCode'=>$r['reasonCode']],$doc['rows']);$expectedReport=json_encode($this->report($operation,$reportRows),JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR);if(count($existing)!==1||!hash_equals($existing[0]['preview_digest'],$doc['digest'])||!hash_equals($existing[0]['source_fingerprint'],$doc['sourceFingerprint'])||!hash_equals($existing[0]['report_json'],$expectedReport))throw new \DomainException('OPERATION_REPLAY_CONFLICT');$expected=array_column($doc['rows'],null,'objectId');foreach($fresh['rows']as$row){$old=$expected[$row['objectId']]??null;if($old===null||$old['legacyUserId']!==$row['legacyUserId']||$old['localUserId']!==$row['localUserId'])throw new \DomainException('PREVIEW_STALE');}return['ok'=>true];}if(!hash_equals($doc['sourceFingerprint'],$fresh['sourceFingerprint']))throw new \DomainException('PREVIEW_STALE');
  $this->db->query('SET TRANSACTION ISOLATION LEVEL SERIALIZABLE');$this->db->begin_transaction();$committing=false;try{$this->lockAuthority($ids,$doc['rows'],$operation);$again=$this->preview($ids,$operation,true);if(!hash_equals($doc['sourceFingerprint'],$again['sourceFingerprint']))throw new \DomainException('PREVIEW_STALE');$ready=[];$report=[];foreach($again['rows']as$r){$status=$r['status'];if($status==='ready'){$ready[]=['objectId'=>$r['objectId'],'legacyUserId'=>$r['legacyUserId'],'localUserId'=>$r['localUserId']];$status='applied';}$report[]=['objectId'=>$r['objectId'],'status'=>$status,'reasonCode'=>$r['reasonCode']];}if($ready!==[])ProductionControlEngineerAssignmentFactory::create($this->db,$this->p)->migrateLegacyBatch($operation,$ready,$actorUserId,$assignedAtUtc);$reportDoc=$this->report($operation,$report);$s=$this->db->prepare("INSERT INTO `{$this->p}fm2_engineer_migration_operations` VALUES(?,?,?,?,?,?)");$s->execute([$operation,$doc['digest'],$doc['sourceFingerprint'],json_encode($reportDoc,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR),$actorUserId,$assignedAtUtc]);file_put_contents($this->marker($operation),json_encode($this->report($operation,array_map(static fn($r)=>['objectId'=>$r['objectId'],'status'=>'unknown','reasonCode'=>null],$doc['rows']))));$committing=true;$this->db->commit();@unlink($this->marker($operation));return['ok'=>true];}catch(\Throwable$e){try{$this->db->rollback();}catch(\Throwable){}if(!$committing)@unlink($this->marker($operation));throw$e;}
 }
 public function reconcile(string$operation):?array{$r=$this->rows("SELECT report_json FROM `{$this->p}fm2_engineer_migration_operations` WHERE operation_id=?",[$operation]);if($r!==[])return json_decode($r[0]['report_json'],true,flags:JSON_THROW_ON_ERROR);$m=$this->marker($operation);return is_file($m)?json_decode((string)file_get_contents($m),true,flags:JSON_THROW_ON_ERROR):null;}
 private function lockAuthority(array$ids,array$previewRows,string$operation):void{
  sort($ids,SORT_NUMERIC);$marks=implode(',',array_fill(0,count($ids),'?'));
  foreach($ids as$id)$this->rows("SELECT id,responsstroicontrol FROM `{$this->l}fm_maintable` WHERE id=? FOR UPDATE",[$id]);
  $this->rows("SELECT id,legacy_installation_object_id FROM `{$this->p}fm2_installation_cases` WHERE legacy_installation_object_id IN($marks) ORDER BY legacy_installation_object_id FOR UPDATE",$ids);
  $legacy=array_values(array_unique(array_filter(array_map(static fn($r)=>$r['legacyUserId']??null,$previewRows),static fn($v)=>is_int($v)&&$v>0)));sort($legacy,SORT_NUMERIC);if($legacy!==[]){$m=implode(',',array_fill(0,count($legacy),'?'));$this->rows("SELECT u.id,u.status,u.role_id,r.status role_status FROM `{$this->l}users`u LEFT JOIN `{$this->l}users_roles`r ON r.id=u.role_id WHERE u.id IN($m) ORDER BY u.id FOR UPDATE",$legacy);$this->rows("SELECT link_id,legacy_user_id,local_user_id FROM `{$this->p}fm2_legacy_identity_links` WHERE legacy_user_id IN($m) ORDER BY legacy_user_id,link_id FOR UPDATE",$legacy);}
  $local=array_values(array_unique(array_filter(array_map(static fn($r)=>$r['localUserId']??null,$previewRows),static fn($v)=>is_int($v)&&$v>0)));sort($local,SORT_NUMERIC);if($local!==[]){$m=implode(',',array_fill(0,count($local),'?'));foreach($local as$id)$this->rows("SELECT user_id,status FROM `{$this->p}fm2_pilot_users` WHERE user_id=? FOR UPDATE",[$id]);$this->rows("SELECT ur.user_id,ur.role_id,r.status,r.code FROM `{$this->p}fm2_pilot_user_roles`ur JOIN `{$this->p}fm2_pilot_roles`r ON r.role_id=ur.role_id WHERE ur.user_id IN($m) ORDER BY ur.user_id,ur.role_id FOR UPDATE",$local);}
  $this->rows("SELECT assignment_id,object_id FROM `{$this->p}fm2_control_engineer_assignments` WHERE object_id IN($marks) ORDER BY object_id,assignment_sequence FOR UPDATE",$ids);$this->rows("SELECT operation_id FROM `{$this->p}fm2_engineer_migration_operations` WHERE operation_id=? FOR UPDATE",[$operation]);
 }
 private function report(string$o,array$rows):array{$c=['selected'=>count($rows),'applied'=>0,'alreadyApplied'=>0,'skipped'=>0,'conflict'=>0,'unknown'=>0];foreach($rows as$r){$k=$r['status']==='already_applied'?'alreadyApplied':$r['status'];$c[$k]++;}return['version'=>1,'operationId'=>$o,'counts'=>$c,'rows'=>$rows];}
 private function marker(string$o):string{return sys_get_temp_dir().'/fmonitor-lcm-'.hash('sha256',(string)getenv('FMONITOR_DB_NAME').$o).'.json';}
 private function row(int$id,string$s,?string$r,?int$l=null,?int$u=null):array{return['objectId'=>$id,'status'=>$s,'reasonCode'=>$r,'legacyUserId'=>$l,'localUserId'=>$u];}
 private function rows(string$q,array$v=[]):array{$s=$this->db->prepare($q);$s->execute($v);return$s->get_result()->fetch_all(MYSQLI_ASSOC);}
}
