<?php
declare(strict_types=1);
namespace FMonitor2\InstallationProcess;

final readonly class MariaDbControlEngineerAssignment
{
 public function __construct(private \mysqli$db,private string$p,private ControlEngineerAssignmentClock$clock){}
 public function assign(ControlEngineerAssignmentCommand$c):array{
  $fingerprint=hash('sha256',json_encode([$c->requestId,$c->objectId,$c->engineerUserId,$c->expectedRevision,$c->actorUserId],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR));$owned=false;
  try{
   if(!ControlEngineerAssignmentDefinitionSchemaMigration::isCompleteCompatible($this->db,$this->p))return$this->out('failed','dependency_unavailable');
   $this->db->query('SET TRANSACTION ISOLATION LEVEL READ COMMITTED');$this->db->begin_transaction();$owned=true;
   $auth=$this->rows("SELECT u.user_id FROM `{$this->p}fm2_pilot_users` u JOIN `{$this->p}fm2_pilot_user_roles` ur ON ur.user_id=u.user_id JOIN `{$this->p}fm2_pilot_roles` r ON r.role_id=ur.role_id JOIN `{$this->p}fm2_pilot_role_permissions` rp ON rp.role_id=r.role_id WHERE u.user_id=? AND u.status=1 AND BINARY u.activation_state='active' AND r.status=1 AND BINARY rp.permission='control_engineer.assign' FOR UPDATE",[$c->actorUserId]);if($auth===[]){$this->db->rollback();return$this->out('rejected','authorization_denied');}
   $existing=$this->rows("SELECT * FROM `{$this->p}fm2_control_engineer_assignments` WHERE request_id=? FOR UPDATE",[$c->requestId]);if($existing!==[]){$this->db->rollback();if(count($existing)!==1||!hash_equals($existing[0]['request_fingerprint'],$fingerprint))return$this->out('conflict','request_id_conflict');return$this->out('replayed',null,$this->payload($existing[0]));}
   $cases=$this->rows("SELECT id FROM `{$this->p}fm2_installation_cases` WHERE legacy_installation_object_id=? FOR UPDATE",[$c->objectId]);if($cases===[]){$this->db->rollback();return$this->out('rejected','object_not_found');}if(count($cases)!==1)throw new \RuntimeException();$case=(int)$cases[0]['id'];
   $eligible=$this->rows("SELECT u.user_id,u.full_name FROM `{$this->p}fm2_pilot_users` u JOIN `{$this->p}fm2_pilot_user_roles` ur ON ur.user_id=u.user_id JOIN `{$this->p}fm2_pilot_roles` r ON r.role_id=ur.role_id WHERE u.user_id=? AND u.status=1 AND BINARY u.activation_state='active' AND r.status=1 AND BINARY r.code='construction_control_engineer' FOR UPDATE",[$c->engineerUserId]);if(count($eligible)!==1){$this->db->rollback();return$this->out('rejected','engineer_not_eligible');}
   $current=(new MariaDbControlEngineerAssignmentReader($this->db,$this->p))->read($c->objectId);if($current['status']==='unavailable')throw new \RuntimeException();if(!in_array($current['status'],['found','missing'],true))throw new \RuntimeException();if($current['revision']!==$c->expectedRevision){$this->db->rollback();return$this->out('conflict','assignment_changed');}if(($current['engineer']['userId']??null)===$c->engineerUserId){$this->db->rollback();return$this->out('rejected','no_changes');}
   $at=$this->clock->now();$mysql=(new \DateTimeImmutable($at))->setTimezone(new \DateTimeZone('UTC'))->format('Y-m-d H:i:s');$seq=$c->expectedRevision+1;$previousId=$current['assignmentId']??null;$previousEngineer=$current['engineer']['userId']??null;$bootstrap=$current['provenance']==='native_application_bootstrap'?$current['bootstrapApplicationId']:null;
   $sql="INSERT INTO `{$this->p}fm2_control_engineer_assignments`(installation_case_id,object_id,assignment_sequence,engineer_user_id,engineer_fio_snapshot,engineer_position_snapshot,previous_assignment_id,previous_engineer_user_id,bootstrap_application_id,assigned_by_user_id,assigned_at_utc,request_id,request_fingerprint)VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)";$s=$this->db->prepare($sql);$s->execute([$case,$c->objectId,$seq,$c->engineerUserId,$eligible[0]['full_name'],'Инженер строительного контроля',$previousId,$previousEngineer,$bootstrap,$c->actorUserId,$mysql,$c->requestId,$fingerprint]);$id=(int)$this->db->insert_id;$row=$this->rows("SELECT * FROM `{$this->p}fm2_control_engineer_assignments` WHERE assignment_id=?",[$id])[0];$this->db->commit();$owned=false;return$this->out('assigned',null,$this->payload($row));
  }catch(\mysqli_sql_exception){if($owned)try{$this->db->rollback();}catch(\Throwable){}return$this->out('failed','persistence_failure');}catch(\Throwable){if($owned)try{$this->db->rollback();}catch(\Throwable){}return$this->out('failed','dependency_unavailable');}
 }
 public function migrateLegacyBatch(string$operationId,array$rows,int$actorUserId,string$assignedAtUtc):void{
  if(!preg_match('/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/D',$operationId)||$actorUserId<1||$rows===[]||count($rows)>100)throw new \InvalidArgumentException();
  foreach($rows as$row){if(!is_array($row)||array_keys($row)!==['objectId','legacyUserId','localUserId'])throw new \InvalidArgumentException();$object=(int)$row['objectId'];$legacy=(int)$row['legacyUserId'];$local=(int)$row['localUserId'];if($object<1||$legacy<1||$local<1)throw new \InvalidArgumentException();$cases=$this->rows("SELECT id FROM `{$this->p}fm2_installation_cases` WHERE legacy_installation_object_id=? FOR UPDATE",[$object]);if(count($cases)!==1)throw new \DomainException('PREVIEW_STALE');$case=(int)$cases[0]['id'];$current=$this->rows("SELECT assignment_id FROM `{$this->p}fm2_control_engineer_assignments` WHERE installation_case_id=? FOR UPDATE",[$case]);if($current!==[])throw new \DomainException('PREVIEW_STALE');$eligible=$this->rows("SELECT u.full_name FROM `{$this->p}fm2_pilot_users`u JOIN `{$this->p}fm2_pilot_user_roles`ur ON ur.user_id=u.user_id JOIN `{$this->p}fm2_pilot_roles`r ON r.role_id=ur.role_id WHERE u.user_id=? AND u.status=1 AND r.status=1 AND BINARY r.code='construction_control_engineer' FOR UPDATE",[$local]);if(count($eligible)!==1)throw new \DomainException('PREVIEW_STALE');$fingerprint=hash('sha256',json_encode([$operationId,$object,$legacy,$local,$actorUserId],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR));$request=substr($operationId,0,24).sprintf('%012d',$object);$s=$this->db->prepare("INSERT INTO `{$this->p}fm2_control_engineer_assignments`(installation_case_id,object_id,assignment_sequence,engineer_user_id,engineer_fio_snapshot,engineer_position_snapshot,assigned_by_user_id,assigned_at_utc,request_id,request_fingerprint,assignment_source,source_operation_id,source_legacy_object_id,source_legacy_user_id)VALUES(?,?,?,?,?,'Инженер строительного контроля',?,?,?,?,'legacy_fmonitor',?,?,?)");$s->execute([$case,$object,1,$local,$eligible[0]['full_name'],$actorUserId,$assignedAtUtc,$request,$fingerprint,$operationId,$object,$legacy]);}
 }
 private function rows(string$q,array$v):array{$s=$this->db->prepare($q);$s->execute($v);return$s->get_result()->fetch_all(MYSQLI_ASSOC);}
 private function payload(array$r):array{return['assignmentId'=>(int)$r['assignment_id'],'caseId'=>(int)$r['installation_case_id'],'objectId'=>(int)$r['object_id'],'revision'=>(int)$r['assignment_sequence'],'engineer'=>['userId'=>(int)$r['engineer_user_id'],'fullName'=>$r['engineer_fio_snapshot'],'position'=>$r['engineer_position_snapshot']],'assignedByUserId'=>(int)$r['assigned_by_user_id'],'assignedAt'=>str_replace(' ','T',$r['assigned_at_utc']).'Z'];}
 private function out(string$s,?string$r,?array$a=null):array{return['status'=>$s,'reasonCode'=>$r,'assignment'=>$a];}
}
