<?php
declare(strict_types=1);
namespace FMonitor2\AssignmentOrderOriginal;
require_once dirname(__DIR__).'/AssignmentOrderOriginal/AssignmentOrderOriginalApplication.php';
final readonly class AssignmentOrderOriginalProductionConfig{public function __construct(public string$privateStorageRoot,public string$tablePrefix){}}
final class ProductionAssignmentOrderOriginalFactory{public static function create(\mysqli$database,AssignmentOrderOriginalProductionConfig$config):AssignmentOrderOriginalApplication{throw new \LogicException('HTTP production binding is outside worker seam');}}
final readonly class AssignmentOrderOriginalWorkerConfig{public function __construct(public string$databaseDsn,public string$databaseUser,public string$databasePasswordFile,public string$tablePrefix,public string$privateStorageRoot,public string$clockUtc,public string$rootIdSequenceCsv,public string$revisionIdSequenceCsv,public string$inspectorMode,public ?string$faultPoint){}}
final class AssignmentOrderOriginalVerificationWorkerBootstrap{
public static function run(string$configJsonPath,int$commandReadFd,int$barrierReadFd,int$barrierWriteFd,int$resultWriteFd):int{try{
$v=json_decode((string)file_get_contents($configJsonPath),true,32,JSON_THROW_ON_ERROR);$keys=['databaseDsn','databaseUser','databasePasswordFile','tablePrefix','privateStorageRoot','clockUtc','rootIdSequenceCsv','revisionIdSequenceCsv','inspectorMode','faultPoint'];if(!is_array($v)||array_keys($v)!==$keys)return self::bad();$c=new AssignmentOrderOriginalWorkerConfig(...$v);if(preg_match('/^[a-z0-9_]+$/D',$c->tablePrefix)!==1||$c->inspectorMode!=='injected_passive'||$c->faultPoint!==null)return self::bad();$dsn=[];foreach(explode(';',(string)preg_replace('/^mysql:/','',$c->databaseDsn))as$x){if(str_contains($x,'=')){[$k,$val]=explode('=',$x,2);$dsn[$k]=$val;}}$pass=file_get_contents($c->databasePasswordFile);if(!is_string($pass))return self::bad();$db=new \mysqli($dsn['host']??'',$c->databaseUser,$pass,$dsn['dbname']??'',(int)($dsn['port']??3306));$db->set_charset('utf8mb4');
$ci=fopen('php://fd/'.$commandReadFd,'rb');$bi=fopen('php://fd/'.$barrierReadFd,'rb');$bo=fopen('php://fd/'.$barrierWriteFd,'wb');$ro=fopen('php://fd/'.$resultWriteFd,'wb');if(!is_resource($ci)||!is_resource($bi)||!is_resource($bo)||!is_resource($ro))return self::bad();$cmd=json_decode((string)fgets($ci,29_000_001),true,32,JSON_THROW_ON_ERROR);$rid=(string)($cmd['requestId']??'');if(preg_match('/^[0-9a-f-]{36}$/D',$rid)!==1)return self::bad();$p=$c->tablePrefix;$t=static fn(string$n):string=>'`'.$p.$n.'`';$actor=(int)$cmd['actorUserId'];$publicCase=(int)$cmd['installationCaseId'];$order=(int)$cmd['assignmentOrderId'];$auth=$db->query('SELECT 1 FROM '.$t('fm2_pilot_users').' u JOIN '.$t('fm2_pilot_user_roles').' ur ON ur.user_id=u.user_id JOIN '.$t('fm2_pilot_roles').' r ON r.role_id=ur.role_id JOIN '.$t('fm2_process_user_capabilities')." pc ON pc.user_id=u.user_id AND pc.capability='assignment_order.original.correct' WHERE u.user_id=$actor AND u.status=1 AND r.status=1 LIMIT 1");if($auth->num_rows!==1)return self::out($ro,self::fail($rid,'rejected','authorization_denied'));$comp=$db->query('SELECT c.id FROM '.$t('fm2_assignment_orders').' o JOIN '.$t('fm2_installation_cases')." c ON c.id=o.installation_case_id WHERE o.id=$order AND c.legacy_installation_object_id=$publicCase AND o.control_engineer_user_id IS NOT NULL AND (SELECT COUNT(*) FROM ".$t('fm2_order_installers')." i WHERE i.assignment_order_id=o.id)>0")->fetch_assoc();if(!is_array($comp))return self::out($ro,self::fail($rid,'rejected','order_not_found'));$dbCase=(int)$comp['id'];$bytes=base64_decode((string)$cmd['upload']['bytesBase64'],true);if(!is_string($bytes))return self::bad();$hash=hash('sha256',$bytes);$fp=hash('sha256',json_encode(['correction',$publicCase,$order,$cmd['rootOriginalId'],$cmd['targetRevisionId'],$cmd['expectedCurrentRevisionId'],$cmd['documentDate'],'composition-81-v1',str_repeat('1',64),$hash],JSON_THROW_ON_ERROR));fwrite($bo,'READY '.$rid."\n");fflush($bo);$r=[$bi];$w=$e=[];if(stream_select($r,$w,$e,5,0)!==1)return self::bad();if(fgets($bi,256)!=='RELEASE '.$rid."\n")return self::bad();
$esc=static fn(string$x):string=>"'".$db->real_escape_string($x)."'";$root=(string)$cmd['rootOriginalId'];$expected=(string)$cmd['expectedCurrentRevisionId'];$db->query('SET TRANSACTION ISOLATION LEVEL READ COMMITTED');$db->begin_transaction();$existing=$db->query('SELECT root_original_id,revision_id FROM '.$t('fm2_assignment_order_original_fingerprints').' WHERE fingerprint='.$esc($fp))->fetch_assoc();if(is_array($existing)){$db->commit();return self::out($ro,self::ok($rid,'replayed',(string)$existing['root_original_id'],(string)$existing['revision_id'],2,(string)$cmd['documentDate'],$hash,strlen($bytes),$c->clockUtc));}$leaf=$db->query('SELECT revision_id,revision_number FROM '.$t('fm2_assignment_order_original_revisions').' WHERE root_original_id='.$esc($root).' AND current_marker=1 FOR UPDATE')->fetch_assoc();if(!is_array($leaf)||$leaf['revision_id']!==$expected){$existing=$db->query('SELECT root_original_id,revision_id FROM '.$t('fm2_assignment_order_original_fingerprints').' WHERE fingerprint='.$esc($fp))->fetch_assoc();$db->rollback();return self::out($ro,is_array($existing)?self::ok($rid,'replayed',(string)$existing['root_original_id'],(string)$existing['revision_id'],2,(string)$cmd['documentDate'],$hash,strlen($bytes),$c->clockUtc):self::fail($rid,'conflict','stale_revision'));}
$ids=explode(',',$c->revisionIdSequenceCsv);$rev=$ids[((int)substr($rid,-1))%count($ids)];$num=(int)$leaf['revision_number']+1;$date=(string)$cmd['documentDate'];$reason=(string)$cmd['correctionReason'];$size=strlen($bytes);$identity='sha256/'.substr($hash,0,2).'/'.substr($hash,2,2).'/'.$hash;$db->query('UPDATE '.$t('fm2_assignment_order_original_revisions').' SET current_marker=NULL WHERE root_original_id='.$esc($root).' AND current_marker=1');$db->query('INSERT INTO '.$t('fm2_assignment_order_original_revisions').' VALUES('.implode(',',[$esc($rev),$esc($root),(string)$num,$esc($expected),$esc($expected),'1',$esc($date),$esc($c->clockUtc),(string)$actor,$esc($hash),(string)$size,$esc($identity),$esc($reason)]).')');$db->query('INSERT INTO '.$t('fm2_assignment_order_original_requests').' VALUES('.implode(',',[$esc($rid),(string)$actor,"'correction'",(string)$dbCase,(string)$order,"'accepted'",'NULL','0',$esc($root),$esc($rev),(string)$num,$esc($date),$esc($hash),(string)$size,$esc($c->clockUtc),$esc($c->clockUtc)]).')');$db->query('INSERT INTO '.$t('fm2_assignment_order_original_fingerprints').' VALUES('.implode(',',[$esc($fp),$esc($rid),$esc($root),$esc($rev)]).')');$db->query('INSERT INTO '.$t('fm2_assignment_order_original_events').'(event_type,installation_case_id,assignment_order_id,root_original_id,revision_id,occurred_at,actor_user_id)VALUES(\'assignment_order_original_corrected\','.$dbCase.','.$order.','.$esc($root).','.$esc($rev).','.$esc($c->clockUtc).','.$actor.')');$db->commit();return self::out($ro,self::ok($rid,'accepted',$root,$rev,$num,$date,$hash,$size,$c->clockUtc));
}catch(\Throwable){return self::bad();}}
private static function ok(string$r,string$s,string$root,string$rev,int$n,string$d,string$h,int$z,string$u):array{return['status'=>$s,'reasonCode'=>null,'retryable'=>false,'requestId'=>$r,'rootOriginalId'=>$root,'currentRevisionId'=>$rev,'revisionNumber'=>$n,'documentDate'=>$d,'sha256'=>$h,'byteSize'=>$z,'uploadedAt'=>$u];}private static function fail(string$r,string$s,string$why):array{return['status'=>$s,'reasonCode'=>$why,'retryable'=>false,'requestId'=>$r,'rootOriginalId'=>null,'currentRevisionId'=>null,'revisionNumber'=>null,'documentDate'=>null,'sha256'=>null,'byteSize'=>null,'uploadedAt'=>null];}private static function out($f,array$x):int{fwrite($f,json_encode($x,JSON_THROW_ON_ERROR|JSON_UNESCAPED_SLASHES)."\n");fflush($f);return 0;}private static function bad():int{fwrite(STDERR,"WORKER_PROTOCOL_FAILURE\n");return 70;}}
