<?php
declare(strict_types=1);
namespace FMonitor2\InstallationProcess;

final readonly class MariaDbControlEngineerAssignmentReader
{
 public function __construct(private \mysqli $db,private string $p){if(preg_match('/^[A-Za-z0-9_]{0,25}$/D',$p)!==1)throw new \InvalidArgumentException();}
 public function read(int $objectId):array { if($objectId<1)throw new \InvalidArgumentException();try{if(!ControlEngineerAssignmentDefinitionSchemaMigration::isCompleteCompatible($this->db,$this->p))throw new \RuntimeException();return $this->inside($objectId);}catch(\Throwable){return['status'=>'unavailable','revision'=>null,'engineer'=>null,'provenance'=>null];} }
 private function inside(int$id):array{
  $q=$this->db->prepare("SELECT id,legacy_installation_object_id FROM `{$this->p}fm2_installation_cases` WHERE legacy_installation_object_id=?");$q->execute([$id]);$cases=$q->get_result()->fetch_all(MYSQLI_ASSOC);if($cases===[])return['status'=>'not_found','revision'=>0,'engineer'=>null,'provenance'=>null];if(count($cases)!==1)throw new \RuntimeException();$case=(int)$cases[0]['id'];
  $q=$this->db->prepare("SELECT * FROM `{$this->p}fm2_control_engineer_assignments` WHERE installation_case_id=? ORDER BY assignment_sequence");$q->execute([$case]);$rows=$q->get_result()->fetch_all(MYSQLI_ASSOC);
  if($rows!==[]){$prev=null;$prevEngineer=null;$seq=0;foreach($rows as$r){$seq++;$rowPrev=$r['previous_engineer_user_id']===null?null:(int)$r['previous_engineer_user_id'];$bootstrap=$r['bootstrap_application_id']===null?null:(int)$r['bootstrap_application_id'];if((int)$r['object_id']!==$id||(int)$r['assignment_sequence']!==$seq||($r['previous_assignment_id']===null?null:(int)$r['previous_assignment_id'])!==$prev||($seq>1&&$rowPrev!==$prevEngineer)||($seq===1&&$bootstrap===null&&$rowPrev!==null)||($seq===1&&$bootstrap!==null&&($rowPrev===null||$rowPrev<1))||($seq>1&&$bootstrap!==null)||trim($r['engineer_fio_snapshot'])===''||trim($r['engineer_position_snapshot'])==='')throw new \RuntimeException();if($seq===1&&$bootstrap!==null)$this->validateBootstrap($bootstrap,$case,$id,$rowPrev);$prev=(int)$r['assignment_id'];$prevEngineer=(int)$r['engineer_user_id'];}$r=end($rows);return $this->found($case,$id,$seq,(int)$r['engineer_user_id'],$r['engineer_fio_snapshot'],$r['engineer_position_snapshot'],'standalone',$r['bootstrap_application_id']===null?null:(int)$r['bootstrap_application_id'],$r);}
  $q=$this->db->prepare("SELECT * FROM `{$this->p}fm2_assignment_order_applications` WHERE installation_case_id=? ORDER BY application_sequence DESC LIMIT 2");$q->execute([$case]);$apps=$q->get_result()->fetch_all(MYSQLI_ASSOC);if($apps===[])return['status'=>'missing','caseId'=>$case,'objectId'=>$id,'revision'=>0,'engineer'=>null,'provenance'=>null,'bootstrapApplicationId'=>null];$a=$apps[0];$selected=json_decode($a['selected_snapshot_json'],true,512,JSON_THROW_ON_ERROR);YiiObjectCardApplicationIntegrity::validateComposition($a,$selected);$e=$selected['selectedEngineer'];if((int)$a['object_id']!==$id||(int)$e['userId']!==(int)$a['control_engineer_user_id'])throw new \RuntimeException();return $this->found($case,$id,0,(int)$e['userId'],$e['fullName'],$e['position'],'native_application_bootstrap',(int)$a['application_id'],$a);
 }
 private function found(int$c,int$o,int$r,int$u,string$n,string$p,string$source,?int$app,array$row):array{return['status'=>'found','caseId'=>$c,'objectId'=>$o,'revision'=>$r,'engineer'=>['userId'=>$u,'fullName'=>$n,'position'=>$p],'provenance'=>$source,'bootstrapApplicationId'=>$app,'assignmentId'=>$source==='standalone'?(int)$row['assignment_id']:null];}
 private function validateBootstrap(int$app,int$case,int$object,?int$previous):void{$q=$this->db->prepare("SELECT * FROM `{$this->p}fm2_assignment_order_applications` WHERE application_id=?");$q->execute([$app]);$rows=$q->get_result()->fetch_all(MYSQLI_ASSOC);if(count($rows)!==1||(int)$rows[0]['installation_case_id']!==$case||(int)$rows[0]['object_id']!==$object||(int)$rows[0]['control_engineer_user_id']!==$previous)throw new \RuntimeException();$selected=json_decode($rows[0]['selected_snapshot_json'],true,512,JSON_THROW_ON_ERROR);YiiObjectCardApplicationIntegrity::validateComposition($rows[0],$selected);if((int)$selected['selectedEngineer']['userId']!==$previous)throw new \RuntimeException();}
}
