<?php
declare(strict_types=1);
namespace FMonitor2\InstallationProcess;

use FMonitor2\Workforce\{BitrixWorkforceDeliveryClient,BitrixWorkforceDeliveryStatus};

final class MariaDbWorkforceSynchronization
{
 public function __construct(private readonly \mysqli$db,private readonly string$p){if(preg_match('/^[A-Za-z0-9_]*$/D',$p)!==1)throw new \InvalidArgumentException();}
 public function run(BitrixWorkforceDeliveryClient$delivery,string$run,?string$observedAt=null):array
 {
  $lock=$this->p.'bitrix_workforce_sync';$s=$this->db->prepare('SELECT GET_LOCK(?,0)');$s->bind_param('s',$lock);$s->execute();if((int)($s->get_result()->fetch_row()[0]??0)!==1)return['status'=>'failed','runId'=>$run,'reason'=>'SYNC_ALREADY_RUNNING','pages'=>0];
  try{return$this->execute($delivery,$run,$observedAt);}catch(\Throwable$e){$allowed=['INVALID_RUN_ID','INVALID_OBSERVED_AT','DATABASE_PUBLICATION_FAILED'];$code=in_array($e->getMessage(),$allowed,true)?$e->getMessage():'WORKFORCE_SYNC_FAILED';throw new \RuntimeException($code);}finally{$s=$this->db->prepare('SELECT RELEASE_LOCK(?)');$s->bind_param('s',$lock);$s->execute();}
 }
 private function execute(BitrixWorkforceDeliveryClient$delivery,string$run,?string$at):array
 {
  if(preg_match('/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/D',$run)!==1)throw new \InvalidArgumentException('INVALID_RUN_ID');
  if($at!==null&&!$this->timestamp($at))throw new \InvalidArgumentException('INVALID_OBSERVED_AT');$startedAt=$at??gmdate(DATE_ATOM);$started=$this->db->prepare('INSERT INTO '.$this->t('fm2_workforce_sync_runs')."(run_id,status,started_at)VALUES(?,'started',?)");$started->bind_param('ss',$run,$startedAt);$started->execute();$result=$delivery->fetch();
  if($result->status===BitrixWorkforceDeliveryStatus::Failed){$completedAt=$at??gmdate(DATE_ATOM);$code='DELIVERY_'.strtoupper((string)$result->reason?->value);$this->fail($run,$completedAt,$code);return['status'=>'failed','runId'=>$run,'reason'=>$code,'pages'=>$result->pages];}
  try{$rows=$this->normalize($result->batch?->records()??[]);if($rows===[]||count($rows)!==$result->batch?->total)throw new \DomainException('DELIVERY_SCHEMA_INVALID');}
  catch(\Throwable$e){$at??=gmdate(DATE_ATOM);$code=in_array($e->getMessage(),['IDENTITY_INVALID','IDENTITY_CONFLICT'],true)?$e->getMessage():'DELIVERY_SCHEMA_INVALID';$this->fail($run,$at,$code);return['status'=>'failed','runId'=>$run,'reason'=>$code,'pages'=>$result->pages];}$at??=gmdate(DATE_ATOM);
  $checksum=hash('sha256',json_encode($rows,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR));
  try{if((int)$this->db->query('SELECT @@in_transaction active')->fetch_assoc()['active']!==0)throw new \RuntimeException('AMBIENT_TRANSACTION');$this->db->begin_transaction();$meta=$this->db->query('SELECT singleton_id FROM '.$this->t('fm2_workforce_sync_metadata').' WHERE singleton_id=1 FOR UPDATE')->fetch_row();if($meta===null)throw new \RuntimeException();$existing=[];$existingPeople=[];foreach($this->db->query('SELECT * FROM '.$this->t('fm2_workforce_catalog').' FOR UPDATE')->fetch_all(MYSQLI_ASSOC)as$x){$tab=(int)$x['installer_tab_id'];$existing[$tab]=$x;if($x['delivery_person_id']!==null)$existingPeople[(int)$x['delivery_person_id']]=$tab;}foreach($rows as$x)if(isset($existingPeople[$x['delivery_person_id']])&&$existingPeople[$x['delivery_person_id']]!==$x['employee_number'])throw new \DomainException('IDENTITY_CONFLICT');$changed=0;
   foreach($rows as$x){$old=$existing[$x['employee_number']]??null;if($this->material($old,$x,'delivered')){$this->observe($run,$x,'delivered',$at);$changed++;}$this->upsert($run,$x,$at);unset($existing[$x['employee_number']]);}
   foreach($existing as$tab=>$old){if(($old['reconciliation_state']??null)!=='missing_from_delivery'&&$old['delivery_person_id']!==null){$x=$this->fromCurrent($old);$this->observe($run,$x,'missing_from_delivery',$at);$changed++;}$s=$this->db->prepare('UPDATE '.$this->t('fm2_workforce_catalog')." SET reconciliation_state='missing_from_delivery',last_successful_sync_run_id=?,last_successful_sync_at=? WHERE installer_tab_id=?");$s->bind_param('ssi',$run,$at,$tab);$s->execute();}
   $pages=$result->pages;$delivered=count($rows);$missing=count($existing);$s=$this->db->prepare('UPDATE '.$this->t('fm2_workforce_sync_runs')." SET status='completed',observed_at=?,completed_at=?,page_count=?,delivered_count=?,material_change_count=?,missing_count=?,normalized_checksum=? WHERE run_id=?");$s->bind_param('ssiiiiss',$at,$at,$pages,$delivered,$changed,$missing,$checksum,$run);$s->execute();$s=$this->db->prepare('UPDATE '.$this->t('fm2_workforce_sync_metadata').' SET last_successful_run_id=?,last_successful_at=? WHERE singleton_id=1');$s->bind_param('ss',$run,$at);$s->execute();$this->db->commit();return['status'=>'completed','runId'=>$run,'pages'=>$pages,'delivered'=>$delivered,'materialChanges'=>$changed,'missing'=>$missing,'observedAt'=>$at,'normalizedChecksum'=>$checksum];
  }catch(\Throwable$e){$this->db->rollback();$code=$e->getMessage()==='IDENTITY_CONFLICT'?'IDENTITY_CONFLICT':'DATABASE_PUBLICATION_FAILED';$this->fail($run,$at,$code);if($code==='IDENTITY_CONFLICT')return['status'=>'failed','runId'=>$run,'reason'=>$code,'pages'=>$result->pages];throw new \RuntimeException($code);}
 }
 private function normalize(array$raw):array
 {
  $rows=[];$people=[];$tabs=[];foreach($raw as$r){$person=$this->positive($r['ID']??null);$email=trim((string)($r['EMAIL']??''));$emailTab=preg_match('/^tab([0-9]+)@/Di',$email,$m)===1?$this->positive(ltrim($m[1],'0')):null;$xing=trim((string)($r['UF_XING']??''));$xingTab=$xing===''?null:$this->positive(ltrim($xing,'0'));if($emailTab!==null&&$xingTab!==null&&$emailTab!==$xingTab)throw new \DomainException('IDENTITY_CONFLICT');$tab=$emailTab??$xingTab??throw new \DomainException('IDENTITY_INVALID');$parts=[];foreach(['LAST_NAME','NAME','SECOND_NAME']as$key){$v=trim((string)($r[$key]??''));if($v!=='')$parts[]=$v;}$fio=implode(' ',$parts);$position=trim((string)($r['WORK_POSITION']??''));if($fio===''||$position===''||!is_bool($r['ACTIVE']??null))throw new \DomainException('IDENTITY_INVALID');$from=$this->date($r['UF_EMPLOYMENT_DATE']??null);if(isset($people[$person])||isset($tabs[$tab]))throw new \DomainException('IDENTITY_CONFLICT');$people[$person]=$tabs[$tab]=true;$rows[]=['delivery_person_id'=>$person,'employee_number'=>$tab,'full_name'=>$fio,'position'=>$position,'employment_status'=>$r['ACTIVE']?'employed':'dismissed','employed_from'=>$from,'dismissal_effective_at'=>null,'authority_system'=>'1c_zup','delivery_system'=>'bitrix24','source_modified_at'=>null];}usort($rows,fn($a,$b)=>$a['delivery_person_id']<=>$b['delivery_person_id']);return$rows;
 }
 private function observe(string$run,array$x,string$state,string$at):void{$quality='observed_only';$s=$this->db->prepare('INSERT INTO '.$this->t('fm2_workforce_observations').'(sync_run_id,delivery_person_id,employee_number,full_name,position,employment_status,employed_from,dismissal_effective_at,authority_system,delivery_system,source_modified_at,reconciliation_state,observed_at,dismissal_time_quality)VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)');$s->bind_param('siisssssssssss',$run,$x['delivery_person_id'],$x['employee_number'],$x['full_name'],$x['position'],$x['employment_status'],$x['employed_from'],$x['dismissal_effective_at'],$x['authority_system'],$x['delivery_system'],$x['source_modified_at'],$state,$at,$quality);$s->execute();}
 private function upsert(string$run,array$x,string$at):void{$first=$x['employment_status']==='dismissed'?$at:null;$source='one_c_zup_via_bitrix';$quality='observed_only';$state='delivered';$s=$this->db->prepare('INSERT INTO '.$this->t('fm2_workforce_catalog').'(installer_tab_id,fio,position,employment_status,employed_from,employed_to,workforce_source,workforce_source_updated_at,delivery_system,delivery_person_id,dismissal_effective_at,first_observed_dismissed_at,dismissal_time_quality,reconciliation_state,authority_system,last_successful_sync_run_id,last_successful_sync_at)VALUES(?,?,?,?,?,NULL,?,?,?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE fio=VALUES(fio),position=VALUES(position),employment_status=VALUES(employment_status),employed_from=VALUES(employed_from),employed_to=NULL,workforce_source=VALUES(workforce_source),workforce_source_updated_at=VALUES(workforce_source_updated_at),delivery_system=VALUES(delivery_system),delivery_person_id=VALUES(delivery_person_id),dismissal_effective_at=NULL,first_observed_dismissed_at=COALESCE(first_observed_dismissed_at,VALUES(first_observed_dismissed_at)),dismissal_time_quality=VALUES(dismissal_time_quality),reconciliation_state=VALUES(reconciliation_state),authority_system=VALUES(authority_system),last_successful_sync_run_id=VALUES(last_successful_sync_run_id),last_successful_sync_at=VALUES(last_successful_sync_at)');$s->bind_param('isssssssisssssss',$x['employee_number'],$x['full_name'],$x['position'],$x['employment_status'],$x['employed_from'],$source,$at,$x['delivery_system'],$x['delivery_person_id'],$x['dismissal_effective_at'],$first,$quality,$state,$x['authority_system'],$run,$at);$s->execute();}
 private function material(?array$o,array$x,string$state):bool{if($o===null)return true;$map=['installer_tab_id'=>'employee_number','fio'=>'full_name','position'=>'position','employment_status'=>'employment_status','employed_from'=>'employed_from','dismissal_effective_at'=>'dismissal_effective_at','authority_system'=>'authority_system','delivery_system'=>'delivery_system','delivery_person_id'=>'delivery_person_id'];foreach($map as$a=>$b)if((string)($o[$a]??'')!==(string)($x[$b]??''))return true;return($o['reconciliation_state']??null)!==$state;}
 private function fromCurrent(array$o):array{return['delivery_person_id'=>(int)$o['delivery_person_id'],'employee_number'=>(int)$o['installer_tab_id'],'full_name'=>$o['fio'],'position'=>$o['position'],'employment_status'=>$o['employment_status'],'employed_from'=>$o['employed_from'],'dismissal_effective_at'=>$o['dismissal_effective_at'],'authority_system'=>$o['authority_system'],'delivery_system'=>$o['delivery_system'],'source_modified_at'=>null];}
 private function fail(string$run,string$at,string$code):void{$s=$this->db->prepare('UPDATE '.$this->t('fm2_workforce_sync_runs')." SET status='failed',completed_at=?,failure_code=? WHERE run_id=?");$s->bind_param('sss',$at,$code,$run);$s->execute();}
 private function positive(mixed$v):int{if(is_int($v)&&$v>0)return$v;if(is_string($v)&&preg_match('/^[1-9][0-9]*$/D',$v)===1&&(strlen($v)<strlen((string)PHP_INT_MAX)||(strlen($v)===strlen((string)PHP_INT_MAX)&&strcmp($v,(string)PHP_INT_MAX)<=0)))return(int)$v;throw new \DomainException('IDENTITY_INVALID');}
 private function date(mixed$v):?string{if($v===null||$v==='')return null;if(!is_string($v)||preg_match('/^(\d{4})-(\d{2})-(\d{2})$/D',$v,$m)!==1||!checkdate((int)$m[2],(int)$m[3],(int)$m[1]))throw new \DomainException('IDENTITY_INVALID');return$v;}
 private function timestamp(string$v):bool{if(strlen($v)>40||preg_match('/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?(?:Z|[+-]\d{2}:\d{2})$/D',$v)!==1)return false;try{new \DateTimeImmutable($v);return true;}catch(\Throwable){return false;}}
 private function t(string$n):string{return'`'.$this->p.$n.'`';}
}
