<?php
declare(strict_types=1);
namespace FMonitor2\InstallationProcess;
final readonly class ObjectDetailsEditApplication
{
 public function __construct(private \mysqli$db,private string$p,private ObjectDetailsFieldRegistry$registry,private mixed$clock){}
 public function edit(ObjectDetailsEditCommand$c):array
 {
  try{$patch=$this->registry->normalizePatch($c->patch);}catch(\InvalidArgumentException){return['status'=>'invalid','reasonCode'=>'invalid_patch'];}
  $fingerprint=hash('sha256',json_encode(['object_details.edit',$c->actorId,$c->objectId,$c->expectedRevision,$patch],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR));
  try{$this->db->begin_transaction();$actor=$this->authorization($c->actorId,$c->objectId);if($actor===null){$this->db->rollback();return['status'=>'rejected','reasonCode'=>'authorization_denied'];}
   $s=$this->db->prepare("SELECT id FROM `{$this->p}fm2_installation_cases` WHERE legacy_installation_object_id=? FOR UPDATE");$s->execute([$c->objectId]);$cases=$s->get_result()->fetch_all(MYSQLI_ASSOC);if(count($cases)!==1){$this->db->rollback();return['status'=>'rejected','reasonCode'=>'authorization_denied'];}$caseId=(int)$cases[0]['id'];
   $s=$this->db->prepare("SELECT request_fingerprint,outcome_json FROM `{$this->p}fm2_object_detail_edit_requests` WHERE request_id=? FOR UPDATE");$s->execute([$c->requestId]);$previous=$s->get_result()->fetch_assoc();if($previous){$this->db->rollback();if(!hash_equals($previous['request_fingerprint'],$fingerprint))return['status'=>'conflict','reasonCode'=>'request_id_conflict'];$out=json_decode($previous['outcome_json'],true,flags:JSON_THROW_ON_ERROR);$out['status']='replayed';return$out;}
   $s=$this->db->prepare("SELECT revision,values_json FROM `{$this->p}fm2_object_detail_edits` WHERE object_id=? FOR UPDATE");$s->execute([$c->objectId]);$current=$s->get_result()->fetch_assoc();$revision=(int)($current['revision']??0);if($revision!==$c->expectedRevision){$this->db->rollback();return['status'=>'conflict','reasonCode'=>'object_details_changed','revision'=>$revision];}
   $values=$current?json_decode($current['values_json'],true,flags:JSON_THROW_ON_ERROR):[];$effective=(new MariaDbEffectiveObjectDetails($this->db,$this->p,$this->p))->read($c->objectId);$changes=[];foreach($patch as$field=>$value){$old=$effective[$field]['value']??null;if($this->same($old,$value))continue;$definition=$this->registry->definitions()[$field];$oldSnapshot=$this->registry->snapshot($field,$old,false);if(($effective[$field]['display']??null)!==null)$oldSnapshot['display']=$effective[$field]['display'];$changes[]=['field'=>$field,'label'=>$definition['label'],'old'=>$oldSnapshot,'new'=>$this->registry->snapshot($field,$value)];$values[$field]=$value;}
   if($changes===[]){$this->db->rollback();return['status'=>'noop','revision'=>$revision];}$next=$revision+1;$at=($this->clock)();$mysql=(new \DateTimeImmutable($at))->setTimezone(new \DateTimeZone('UTC'))->format('Y-m-d H:i:s.u');$json=json_encode($values,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR);
   if($current){$s=$this->db->prepare("UPDATE `{$this->p}fm2_object_detail_edits` SET revision=?,values_json=?,updated_at_utc=?,updated_by_user_id=? WHERE object_id=? AND revision=?");$s->execute([$next,$json,$mysql,$c->actorId,$c->objectId,$revision]);if($s->affected_rows!==1)throw new \RuntimeException();}else{$s=$this->db->prepare("INSERT INTO `{$this->p}fm2_object_detail_edits`(object_id,revision,values_json,updated_at_utc,updated_by_user_id)VALUES(?,?,?,?,?)");$s->execute([$c->objectId,$next,$json,$mysql,$c->actorId]);}
   $changesJson=json_encode($changes,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR);$s=$this->db->prepare("INSERT INTO `{$this->p}fm2_object_detail_edit_events`(installation_case_id,object_id,revision,event_type,changes_json,actor_user_id,actor_display_snapshot,occurred_at_utc,request_id)VALUES(?,?,?,'object_details_changed',?,?,?,?,?)");$s->execute([$caseId,$c->objectId,$next,$changesJson,$c->actorId,$actor['full_name'],$mysql,$c->requestId]);$eventId=$this->db->insert_id;$out=['status'=>'applied','revision'=>$next,'eventId'=>$eventId];$s=$this->db->prepare("INSERT INTO `{$this->p}fm2_object_detail_edit_requests`(request_id,request_fingerprint,object_id,outcome_json,created_at_utc)VALUES(?,?,?,?,?)");$s->execute([$c->requestId,$fingerprint,$c->objectId,json_encode($out,JSON_THROW_ON_ERROR),$mysql]);$this->db->commit();return$out;
  }catch(\Throwable){try{$this->db->rollback();}catch(\Throwable){}return['status'=>'failed','reasonCode'=>'persistence_unavailable'];}
 }
 private function authorization(int$actor,int$objectId):?array{$s=$this->db->prepare("SELECT u.full_name,MAX(BINARY r.code IN('fkr_operator','manager') AND BINARY rp.permission='objects.details.edit') can_edit,MAX(BINARY rp.permission='objects.read') can_read_object FROM `{$this->p}fm2_pilot_users` u JOIN `{$this->p}fm2_pilot_user_roles` ur ON ur.user_id=u.user_id JOIN `{$this->p}fm2_pilot_roles` r ON r.role_id=ur.role_id AND r.status=1 JOIN `{$this->p}fm2_pilot_role_permissions` rp ON rp.role_id=r.role_id JOIN `{$this->p}fm2_installation_cases` scope_case ON scope_case.legacy_installation_object_id=? WHERE u.user_id=? AND u.status=1 AND BINARY u.activation_state='active' GROUP BY u.user_id,u.full_name,scope_case.id");$s->execute([$objectId,$actor]);$row=$s->get_result()->fetch_assoc();return$row&&(int)$row['can_edit']===1&&(int)$row['can_read_object']===1?$row:null;}
 private function same(mixed$a,mixed$b):bool{return get_debug_type($a)===get_debug_type($b)?$a===$b:(is_scalar($a)&&is_scalar($b)&&(string)$a===(string)$b);}
}
