<?php
declare(strict_types=1);
namespace FMonitor2\InstallationProcess;

final class PilotOtizSchemaMigration
{
    public static function apply(\mysqli$db,string$p=''):array
    {
        MariaDbSchemaInspector::validateTablePrefix($p);$names=['fm2_pilot_otiz_snapshots','fm2_pilot_otiz_snapshot_objects','fm2_pilot_otiz_snapshot_allocations','fm2_pilot_otiz_snapshot_issues','fm2_pilot_otiz_snapshot_evidence','fm2_pilot_otiz_payment_closures','fm2_pilot_otiz_events'];$present=array_filter($names,fn($n)=>MariaDbSchemaInspector::tableExists($db,$p.$n));
        if($present!==[]){if(count($present)!==count($names))return['applied'=>false,'reason'=>'SCHEMA_MIGRATION_CONFLICT'];try{MariaDbPilotLegacyObjectSchemaReadiness::assertOtizReady($db,$p);return['applied'=>false];}catch(\Throwable){return['applied'=>false,'reason'=>'SCHEMA_MIGRATION_CONFLICT'];}}
        $q=fn(string$n)=>'`'.$p.$n.'`';$ddl=[
            "CREATE TABLE {$q($names[0])}(id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,report_date DATE NOT NULL,status ENUM('draft','accepted') NOT NULL,previous_snapshot_id BIGINT UNSIGNED NULL,rules_version VARCHAR(80) NOT NULL,calculated_at VARCHAR(40) NOT NULL,calculated_by_user_id BIGINT UNSIGNED NOT NULL,accepted_at VARCHAR(40) NULL,accepted_by_user_id BIGINT UNSIGNED NULL,total_pool_cents BIGINT NOT NULL,total_closed_cents BIGINT NOT NULL,total_available_cents BIGINT NOT NULL,content_hash CHAR(64) NOT NULL,KEY(report_date,status)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
            "CREATE TABLE {$q($names[1])}(snapshot_id BIGINT UNSIGNED NOT NULL,object_id BIGINT UNSIGNED NOT NULL,regnumber VARCHAR(120) NOT NULL,address VARCHAR(500) NOT NULL,previous_progress_bp INT NOT NULL,current_progress_bp INT NOT NULL,progress_fact_date DATE NOT NULL,premium_cents BIGINT NOT NULL,shaft_bp INT NOT NULL,kss_bp INT NOT NULL,accrued_cents BIGINT NOT NULL,fund_cents BIGINT NOT NULL,closed_before_cents BIGINT NOT NULL,remaining_cents BIGINT NOT NULL,pool_cents BIGINT NOT NULL,distributed_cents BIGINT NOT NULL,undistributed_cents BIGINT NOT NULL,calculation_state VARCHAR(40) NOT NULL,inputs_json JSON NOT NULL,PRIMARY KEY(snapshot_id,object_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
            "CREATE TABLE {$q($names[2])}(id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,snapshot_id BIGINT UNSIGNED NOT NULL,object_id BIGINT UNSIGNED NOT NULL,tab_id VARCHAR(40) NOT NULL,full_name VARCHAR(300) NOT NULL,position_name VARCHAR(200) NOT NULL,contribution_bp INT NOT NULL,base_ktu_bp INT NOT NULL,adjustment_ktu_bp INT NOT NULL,effective_ktu_bp INT NOT NULL,share_bp INT NOT NULL,amount_cents BIGINT NOT NULL,employment_status VARCHAR(40) NOT NULL,participation_basis VARCHAR(300) NOT NULL,KEY(snapshot_id,object_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
            "CREATE TABLE {$q($names[3])}(id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,snapshot_id BIGINT UNSIGNED NOT NULL,object_id BIGINT UNSIGNED NOT NULL,severity ENUM('blocker','warning') NOT NULL,issue_code VARCHAR(80) NOT NULL,message VARCHAR(600) NOT NULL,owner_role VARCHAR(120) NOT NULL,state ENUM('open','resolved') NOT NULL DEFAULT 'open',resolution VARCHAR(600) NULL,resolved_by_user_id BIGINT UNSIGNED NULL,resolved_at VARCHAR(40) NULL,KEY(snapshot_id,object_id,severity)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
            "CREATE TABLE {$q($names[4])}(snapshot_id BIGINT UNSIGNED NOT NULL,legacy_object_id BIGINT UNSIGNED NOT NULL,admission_state ENUM('confirmed_not_mapped','excluded') NOT NULL,source_label VARCHAR(160) NOT NULL,source_locator VARCHAR(160) NOT NULL,snapshot_hash CHAR(64) NOT NULL,projection_hash CHAR(64) NOT NULL,evidence_grade CHAR(1) NOT NULL,payload_json JSON NOT NULL,PRIMARY KEY(snapshot_id,legacy_object_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
            "CREATE TABLE {$q($names[5])}(id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,snapshot_id BIGINT UNSIGNED NOT NULL,object_id BIGINT UNSIGNED NOT NULL,closed_on DATE NOT NULL,paid_cents BIGINT NOT NULL,discipline_cents BIGINT NOT NULL,deadline_cents BIGINT NOT NULL,basis VARCHAR(500) NOT NULL,artifact VARCHAR(300) NOT NULL,created_by_user_id BIGINT UNSIGNED NOT NULL,created_at VARCHAR(40) NOT NULL,reverses_payment_closure_id BIGINT UNSIGNED NULL,KEY(object_id,closed_on),KEY(snapshot_id),UNIQUE KEY unique_reversal(reverses_payment_closure_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
            "CREATE TABLE {$q($names[6])}(id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,snapshot_id BIGINT UNSIGNED NULL,object_id BIGINT UNSIGNED NULL,event_type VARCHAR(80) NOT NULL,payload_json JSON NOT NULL,actor_user_id BIGINT UNSIGNED NOT NULL,occurred_at VARCHAR(40) NOT NULL,KEY(snapshot_id,id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4"];
        foreach($ddl as$sql)$db->query($sql);MariaDbPilotLegacyObjectSchemaReadiness::assertOtizReady($db,$p);return['applied'=>true];
    }
}
