<?php
declare(strict_types=1);
require dirname(__DIR__).'/bootstrap.php';
use FMonitor2\AssignmentOrderComposition as C;
use FMonitor2\Tests\Support\SelectionCommandFixture as F;

// ASSIGNMENT-ORDER-COMPOSITION-SELECT-001 v0.11 §§2–6/9–10, fresh contour only.
function outcomeCommand(array $change=[]):C\SelectAssignmentOrderCompositionCommand
{
    $v=$change+['request'=>'00000000-0000-4000-8000-000000000001','actor'=>18,'object'=>4512,'engineer'=>73,'ids'=>[7001],'revision'=>0,'mode'=>'new_order'];
    return new C\SelectAssignmentOrderCompositionCommand(new C\SelectionRequestId($v['request']),C\AssignmentOrderCompositionMode::from($v['mode']),new C\InstallationObjectId($v['object']),new C\UserId($v['actor']),new C\InstallerTabIdList(array_map(static fn($id)=>new C\InstallerTabId($id),$v['ids'])),$v['engineer']===null?null:new C\UserId($v['engineer']),new C\SelectionRevision($v['revision']));
}
function outcomeCheck(C\AssignmentOrderCompositionResult $r,string $status,?string $reason,bool $retry=false):void
{assertSameValue([$status,$reason,$retry],[$r->status()->value,$r->reasonCode()?->value,$r->retryable()],'closed result');if(!in_array($status,['selected','replayed'],true))assertSameValue(null,$r->success(),'failure contains no success disclosure');}
function noFacts(F $f):void{assertSameValue([[],[],[],[]],[$f->selections,$f->events,$f->audits,$f->requests],'no committed facts');}
function outcomeInstaller(array $values=[]):C\InstallerSnapshot
{ $v=$values+['id'=>7001,'fio'=>'Worker','position'=>'Installer','status'=>'employed','from'=>'2020-01-01','to'=>null,'source'=>'synthetic','updated'=>'2026-09-01T06:00:00Z'];return new C\InstallerSnapshot($v['id'],$v['fio'],$v['position'],$v['status'],$v['from'],$v['to'],$v['source'],$v['updated']); }
$cases=[];
foreach(['uuid'=>['request'=>'bad'],'actor'=>['actor'=>0],'object'=>['object'=>0],'engineer'=>['engineer'=>0],'installer'=>['ids'=>[0]],'duplicate'=>['ids'=>[7001,7001]],'too-many'=>['ids'=>range(1,501)],'revision'=>['revision'=>-1]] as $name=>$change){
    $cases['shape '.$name]=static function()use($change):void{$f=new F();outcomeCheck($f->app()->selectAssignmentOrderComposition(outcomeCommand($change)),'rejected','invalid_command');assertSameValue([],$f->trace,'shape rejected before any I/O');noFacts($f);};
}
$cases['authorization unavailable']=static function():void{$f=new F();$f->authorization=C\SelectionAuthorizationStatus::UNAVAILABLE;outcomeCheck($f->app()->selectAssignmentOrderComposition(outcomeCommand()),'failed','dependency_unavailable',true);assertSameValue(['authorize'],$f->trace,'no clock/lookup after unavailable authorization');noFacts($f);};
$cases['revoked replay denial per invocation']=static function():void{
    $f=new F();$app=$f->app();$command=outcomeCommand();$original=$app->selectAssignmentOrderComposition($command);$f->authorization=C\SelectionAuthorizationStatus::DENIED;
    for($i=0;$i<2;$i++){$f->trace=[];outcomeCheck($app->selectAssignmentOrderComposition($command),'rejected','authorization_denied');assertSameValue(['authorize','clock','independent-audit'],$f->trace,'denial before stored result');}
    assertSameValue([1,1,3],[count($f->requests),count($f->events),count($f->audits)],'one audit per denied invocation');$f->authorization=C\SelectionAuthorizationStatus::ALLOWED;$f->trace=[];$restored=$app->selectAssignmentOrderComposition($command);outcomeCheck($restored,'replayed',null);assertSameValue(get_object_vars($original->success()),get_object_vars($restored->success()),'restored frozen success values');assertSameValue(['authorize','request'],$f->trace,'restore silent replay');
};
$cases['changed request conflict']=static function():void{$f=new F();$app=$f->app();$app->selectAssignmentOrderComposition(outcomeCommand());$before=serialize([$f->requests,$f->selections,$f->events]);$f->trace=[];outcomeCheck($app->selectAssignmentOrderComposition(outcomeCommand(['ids'=>[7002]])),'conflict','request_id_conflict');assertSameValue(['authorize','request','clock','independent-audit'],$f->trace,'changed request no confidential work');assertSameValue($before,serialize([$f->requests,$f->selections,$f->events]),'terminal preserved');assertSameValue(2,count($f->audits),'one conflict audit');};
foreach(['unavailable','notFound','malformed'] as $kind){$cases['clock '.$kind]=static function()use($kind):void{$f=new F();$f->clockResponse=$kind==='malformed'?C\SelectionInstantLookup::found(new C\SelectionInstant('2026-02-31T00:00:00Z')):C\SelectionInstantLookup::$kind();outcomeCheck($f->app()->selectAssignmentOrderComposition(outcomeCommand()),'failed','dependency_unavailable',true);assertSameValue(['authorize','request','clock'],$f->trace,'clock failure before facts');noFacts($f);};}
$cases['terminal lookup unavailable']=static function():void{$f=new F();$f->requestResponse=C\SelectionTerminalRequestLookup::unavailable();outcomeCheck($f->app()->selectAssignmentOrderComposition(outcomeCommand()),'failed','dependency_unavailable',true);assertSameValue(['authorize','request'],$f->trace,'terminal failure no clock');noFacts($f);};
foreach(['completed'=>'object_completed','pto'=>'object_has_pto_act','empty'=>'installer_required','engineer'=>'control_engineer_required'] as $kind=>$reason){$cases['business '.$kind]=static function()use($kind,$reason):void{
    $f=new F();$command=outcomeCommand($kind==='empty'?['ids'=>[],'engineer'=>null]:($kind==='engineer'?['engineer'=>null]:[]));
    if(in_array($kind,['completed','pto'],true)){$f->caseResponse=$f->lockedCaseResponse=C\SelectionCaseLookup::found(new C\SelectionCasePayload(4512,4512,$kind==='completed','2026-09-01'));}
    outcomeCheck($f->app()->selectAssignmentOrderComposition($command),'rejected',$reason);assertSameValue([0,0,1,1],[$f->allocations,count($f->events),count($f->requests),count($f->audits)],'business rejection stores terminal/audit only');
};}
foreach(['missing','dismissed','future','malformed'] as $kind){$cases['workforce '.$kind]=static function()use($kind):void{$f=new F();$rows=$kind==='missing'?[]:[outcomeInstaller(match($kind){'dismissed'=>['status'=>'dismissed'],'future'=>['from'=>'2026-10-01'],'malformed'=>['fio'=>''],default=>[]})];$f->installerResponse=C\SelectionInstallerBatchLookup::found(new C\InstallerBatchPayload($rows,$kind==='missing'?[7001]:[]));$reason=match($kind){'missing'=>'installer_not_in_catalog','malformed'=>'dependency_unavailable',default=>'installer_not_employed'};outcomeCheck($f->app()->selectAssignmentOrderComposition(outcomeCommand()),$kind==='malformed'?'failed':'rejected',$reason,$kind==='malformed');assertSameValue(0,$f->allocations,'eligibility before allocation');if($kind==='malformed')noFacts($f);else assertSameValue([1,1],[count($f->requests),count($f->audits)],'eligibility rejection persisted');};}
foreach(['notFound','unavailable','malformed'] as $kind){$cases['engineer '.$kind]=static function()use($kind):void{$f=new F();$f->engineerResponse=$kind==='malformed'?C\SelectionEngineerLookup::found(new C\EngineerSnapshot(74,'Engineer','Engineer')):C\SelectionEngineerLookup::$kind();outcomeCheck($f->app()->selectAssignmentOrderComposition(outcomeCommand()),$kind==='notFound'?'rejected':'failed',$kind==='notFound'?'control_engineer_not_eligible':'dependency_unavailable',$kind!=='notFound');assertSameValue(0,$f->allocations,'engineer before allocation');};}
foreach(['case','locked-case','state'] as $kind){$cases['malformed dependency '.$kind]=static function()use($kind):void{$f=new F();if($kind==='case')$f->caseResponse=C\SelectionCaseLookup::found(new C\SelectionCasePayload(4512,9999,false,null));elseif($kind==='locked-case')$f->lockedCaseResponse=C\SelectionCaseLookup::notFound();else $f->stateResponse=C\SelectionStateLookup::unavailable();outcomeCheck($f->app()->selectAssignmentOrderComposition(outcomeCommand()),'failed','dependency_unavailable',true);assertSameValue(0,$f->allocations,'dependency failure before allocation');noFacts($f);};}
foreach(['stale','pending','no-selection','accepted-replace','accepted-new'] as $kind){$cases['state '.$kind]=static function()use($kind):void{
    $f=new F();$app=$f->app();if($kind!=='no-selection')$app->selectAssignmentOrderComposition(outcomeCommand());
    if(str_starts_with($kind,'accepted')){$s=$f->state->latestSelection;$accepted=new C\SelectionIdentitySummary($s->assignmentOrderId,$s->orderVersion,$s->selectionRevision,$s->compositionIdentity,$s->compositionSha256,true);$f->state=new C\SelectionStateSnapshot($accepted,null,$accepted,null,new C\EffectiveOrderIdentity(81,1));}
    $effective=$f->state->effectiveOrder;$command=outcomeCommand(['request'=>'00000000-0000-4000-8000-000000000002','revision'=>in_array($kind,['stale','no-selection'],true)?0:1,'mode'=>in_array($kind,['no-selection','accepted-replace'],true)?'replace_pending':'new_order']);
    $r=$app->selectAssignmentOrderComposition($command);$reason=match($kind){'stale'=>'stale_selection','pending'=>'pending_selection_exists','no-selection'=>'selection_not_found','accepted-replace'=>'original_already_accepted',default=>null};outcomeCheck($r,$kind==='accepted-new'?'selected':'conflict',$reason);assertSameValue((array)$effective,(array)$f->state->effectiveOrder,'new pending selection does not apply itself');assertSameValue($kind==='accepted-new'?2:($kind==='no-selection'?0:1),$f->allocations,'state gate allocation count');
};}
foreach(['allocation','stage'] as $kind){foreach(['capacity','persistence'] as $fault){$cases[$kind.' '.$fault]=static function()use($kind,$fault):void{$f=new F();if($kind==='allocation')$f->allocationResponse=$fault==='capacity'?C\SelectionIdentityAllocationResult::capacityExhausted():C\SelectionIdentityAllocationResult::persistenceError();else $f->stageResponse=$fault==='capacity'?C\SelectionStageResult::capacityExhausted():C\SelectionStageResult::persistenceError();outcomeCheck($f->app()->selectAssignmentOrderComposition(outcomeCommand()),'failed',$fault==='capacity'?'allocation_capacity_exhausted':'persistence_failure',$fault!=='capacity');noFacts($f);};}}
$cases['revision and version exhausted before allocation']=static function():void{$f=new F();$identity='composition-81-v65535';$hash=hash('sha256','{"caseId":4512,"compositionIdentity":"composition-81-v65535","engineerUserId":73,"installers":[7001],"orderId":81}');$s=new C\SelectionIdentitySummary(81,65535,4294967295,$identity,$hash,true);$f->state=new C\SelectionStateSnapshot($s,null,$s,null,null);outcomeCheck($f->app()->selectAssignmentOrderComposition(outcomeCommand(['revision'=>4294967295])),'failed','allocation_capacity_exhausted');assertSameValue(0,$f->allocations,'prove exhaustion before reservation');noFacts($f);};
foreach(['rolledBack','outcomeUnknown','capacityExhausted'] as $fault){$cases['denial audit '.$fault]=static function()use($fault):void{$f=new F();$f->authorization=C\SelectionAuthorizationStatus::DENIED;$f->auditResponse=C\SelectionAuditWriteResult::$fault();outcomeCheck($f->app()->selectAssignmentOrderComposition(outcomeCommand()),'failed',match($fault){'rolledBack'=>'persistence_failure','outcomeUnknown'=>'persistence_outcome_unknown',default=>'allocation_capacity_exhausted'},$fault!=='capacityExhausted');noFacts($f);};}
foreach(['rollback','unknown-committed','unknown-absent','unknown-unavailable'] as $fault){$cases['transaction '.$fault]=static function()use($fault):void{$f=new F();$f->outcome=$fault==='unknown-unavailable'?'unknown-absent':$fault;if($fault==='unknown-unavailable')$f->freshResponse=C\SelectionTerminalRequestLookup::unavailable();$r=$f->app()->selectAssignmentOrderComposition(outcomeCommand());outcomeCheck($r,$fault==='unknown-committed'?'replayed':'failed',$fault==='unknown-committed'?null:($fault==='unknown-unavailable'?'persistence_outcome_unknown':'persistence_failure'),$fault!=='unknown-committed');assertSameValue(1,$f->allocations,'no second allocation');assertSameValue(1,$f->clockCalls,'no second clock');if($fault!=='rollback')assertSameValue(1,count(array_filter($f->trace,static fn($x)=>$x==='fresh-close')),'fresh reader closes once');if($fault!=='unknown-committed')noFacts($f);};}
foreach(['matching','absent','unavailable'] as $kind){$cases['request race '.$kind]=static function()use($kind):void{
    $f=new F();$f->stageResponse=C\SelectionStageResult::requestRace();
    if($kind==='matching'){
        $request=new C\SelectionRequestId('00000000-0000-4000-8000-000000000001');
        $intent=new C\SelectionNormalizedIntent(18,73,0,4512,new C\InstallerTabIdSet([new C\InstallerTabId(7001)]),C\AssignmentOrderCompositionMode::NEW_ORDER,
            '{"actorUserId":18,"controlEngineerUserId":73,"expectedSelectionRevision":0,"installationObjectId":4512,"installerTabIds":[7001],"mode":"new_order"}',
            '62ee3be1c62ff977fc0e508a4743d85b8f5bc83386b3b8b0c26f542d321aff6c');
        $result=C\SelectionResult::selected($request,new C\SelectionSuccessPayload(4512,81,1,1,'composition-81-v1','5c405e5761854b6de09ff2f06f1d72e38203081052b8409cf23fa8d4447fe93a','2026-09-05','2026-09-05T09:00:00Z'));
        $f->freshResponse=C\SelectionTerminalRequestLookup::found(new C\SelectionTerminalRequestRecord($request,$intent,$result));
    }else{$f->freshResponse=$kind==='absent'?C\SelectionTerminalRequestLookup::notFound():C\SelectionTerminalRequestLookup::unavailable();}
    $r=$f->app()->selectAssignmentOrderComposition(outcomeCommand());outcomeCheck($r,$kind==='matching'?'replayed':'failed',$kind==='matching'?null:($kind==='absent'?'persistence_failure':'persistence_outcome_unknown'),$kind!=='matching');
    assertSameValue(1,$f->allocations,'race never re-allocates');assertSameValue(1,$f->clockCalls,'race keeps attempt instant');assertSameValue(1,count(array_filter($f->trace,static fn($x)=>$x==='fresh-close')),'race fresh reader closed');noFacts($f);
};}
$cases['reauthorize unknown result before disclosure']=static function():void{
    $f=new F();$f->outcome='unknown-committed';$f->authorizationSequence=[C\SelectionAuthorizationStatus::ALLOWED,C\SelectionAuthorizationStatus::DENIED];
    outcomeCheck($f->app()->selectAssignmentOrderComposition(outcomeCommand()),'rejected','authorization_denied');assertSameValue(false,in_array('fresh-open',$f->trace,true),'revoked recovery cannot open confidential reader');
    assertSameValue([1,1,2],[$f->clockCalls,count($f->requests),count($f->audits)],'denial uses original attempt instant and retains committed terminal');
};
$failed=0;foreach($cases as $name=>$test){try{assertSameValue(true,is_callable([C\AssignmentOrderCompositionFactory::class,'create']),'RED_ASSERTION: public selection application factory is missing');$test();echo "PASS $name\n";}catch(Throwable $e){$failed++;echo "FAIL $name: ".$e->getMessage()."\n";}}
echo 'SELECTION_COMMAND_OUTCOMES passed='.(count($cases)-$failed).' failed='.$failed."\n";exit($failed===0?0:1);
