<?php
declare(strict_types=1);
require dirname(__DIR__).'/bootstrap.php';
require_once dirname(__DIR__,2).'/app/AssignmentOrderOriginal/AssignmentOrderOriginalRuntime.php';
use FMonitor2\Tests\Support\SelectedOriginalFixture as F;use FMonitor2\Tests\Support\SelectionNativeFixture as SF;
use FMonitor2\AssignmentOrderComposition as C;use FMonitor2\AssignmentOrderOriginal as O;use FMonitor2\InstallationProcess as I;
$f=new F('ue_');
try{$db=$f->selection->db;$p='ue_';I\BitrixWorkforceHistorySchemaMigration::apply($db,$p);assertSameValue(['applied'=>true],I\AssignmentOrderSelectionUnknownEmploymentSchemaMigration::apply($db,$p),'nullable proof successor');
 $db->query("UPDATE `{$p}fm2_workforce_catalog` SET employed_from=NULL WHERE installer_tab_id=7002");$denied=$f->selection->app()->selectAssignmentOrderComposition(SF::command(9,0,7002));assertSameValue(['failed','dependency_unavailable'],[$denied->status()->value,$denied->reasonCode()?->value],'unknown without full proof refused');
 $run='44444444-4444-4444-8444-444444444444';$observed='2026-09-01T06:00:00+00:00';$hash=str_repeat('a',64);$db->query("INSERT INTO `{$p}fm2_workforce_sync_runs`(run_id,status,started_at,observed_at,completed_at,failure_code,page_count,delivered_count,material_change_count,missing_count,normalized_checksum)VALUES('$run','completed','2026-09-01T05:59:00+00:00','$observed','$observed',NULL,1,1,1,0,'$hash')");$db->query("UPDATE `{$p}fm2_workforce_sync_metadata` SET last_successful_run_id='$run',last_successful_at='$observed' WHERE singleton_id=1");$db->query("UPDATE `{$p}fm2_workforce_catalog` SET employed_from=NULL,authority_system='1c_zup',delivery_system='bitrix24',delivery_person_id=9001,reconciliation_state='delivered',last_successful_sync_run_id='$run',last_successful_sync_at='$observed' WHERE installer_tab_id=7001");
 $selected=$f->selection->app()->selectAssignmentOrderComposition(SF::command());assertSameValue('selected',$selected->status()->value,'unknown with full proof selected');$member=$db->query("SELECT employed_from_snapshot,employment_proof_kind,authority_system_snapshot,delivery_system_snapshot FROM `{$p}fm2_assignment_order_selection_members`")->fetch_assoc();assertSameValue([null,'full_current','1c_zup','bitrix24'],array_values($member),'unknown preserved with proof');
 $original=$f->app()->submitAssignmentOrderOriginal(F::command(new O\AssignmentOrderOriginalMemoryStream(F::pdf())));assertSameValue('accepted',$original->status()->value,'original accepted');I\AssignmentOrderApplicationSchemaMigration::apply($db,$p);$f->selection->schema->insert($p.'fm2_pilot_role_permissions',['role_id'=>1,'permission'=>'assignment_order.composition.apply']);$clock=new class implements C\SelectionClock{public function now():C\SelectionInstantLookup{return C\SelectionInstantLookup::found(new C\SelectionInstant('2026-09-05T10:00:00Z'));}};$applied=C\ProductionAssignmentOrderApplicationFactory::create($db,$p,$clock)->applyAssignmentOrderOriginal(new C\ApplyAssignmentOrderOriginalCommand('55555555-5555-4555-8555-555555555555',4512,81,(string)$original->currentRevisionId(),0,18));assertSameValue('applied',$applied->status,'applied');assertSameValue(null,C\AssignmentOrderApplicationReaderFactory::create($db,$p)->readCurrent(4512)->value['eligibility'][0]['employedFrom'],'unknown retained');
 echo"selection_unknown_employment_manual_pilot_test: PASS\n";
}finally{$f->close();}
