<?php
declare(strict_types=1);
namespace FMonitor2\Otiz;
use yii\db\Connection;
use yii\db\Transaction;
/** Read-only settlement projection; all monetary writes remain in OtizSettlement. */
final class MariaDbOtizSettlementView
{
 public function __construct(private Connection$db,private string$prefix){if(preg_match('/^[A-Za-z0-9_]{0,25}$/D',$prefix)!==1)throw new \InvalidArgumentException();}
 public function snapshot(int$id):array|false
 {
  $snapshot=$this->db->createCommand("SELECT * FROM `{$this->prefix}fm2_pilot_otiz_snapshots` WHERE id=:id",[':id'=>$id])->queryOne();if($snapshot===false)return false;
  $objects=$this->db->createCommand("SELECT * FROM `{$this->prefix}fm2_pilot_otiz_snapshot_objects` WHERE snapshot_id=:id ORDER BY object_id",[':id'=>$id])->queryAll();
  foreach($objects as&$object){$oid=(int)$object['object_id'];$object['global_closed_cents']=(int)$this->db->createCommand("SELECT COALESCE(SUM(paid_cents+discipline_cents+deadline_cents),0) FROM `{$this->prefix}fm2_pilot_otiz_payment_closures` WHERE object_id=:o",[':o'=>$oid])->queryScalar();$object['issues']=$this->db->createCommand("SELECT * FROM `{$this->prefix}fm2_pilot_otiz_snapshot_issues` WHERE snapshot_id=:s AND object_id=:o ORDER BY severity",[':s'=>$id,':o'=>$oid])->queryAll();$object['allocations']=$this->db->createCommand("SELECT * FROM `{$this->prefix}fm2_pilot_otiz_snapshot_allocations` WHERE snapshot_id=:s AND object_id=:o ORDER BY amount_cents DESC,full_name",[':s'=>$id,':o'=>$oid])->queryAll();}unset($object);
  $closures=$this->db->createCommand("SELECT c.*,o.regnumber FROM `{$this->prefix}fm2_pilot_otiz_payment_closures` c JOIN `{$this->prefix}fm2_pilot_otiz_snapshot_objects` o ON o.snapshot_id=c.snapshot_id AND o.object_id=c.object_id WHERE c.snapshot_id=:id ORDER BY c.id DESC",[':id'=>$id])->queryAll();
  return['snapshot'=>$snapshot,'objects'=>$objects,'closures'=>$closures];
 }
 public function snapshotForClosure(int$id):int|false{$v=$this->db->createCommand("SELECT snapshot_id FROM `{$this->prefix}fm2_pilot_otiz_payment_closures` WHERE id=:id",[':id'=>$id])->queryScalar();return$v===false?false:(int)$v;}
 public function objectLedgerHistory(int$snapshotId,int$objectId,int$page):array|false
 {
  if($snapshotId<1||$objectId<1||$page<1)return false;
  $transaction=$this->db->beginTransaction(Transaction::REPEATABLE_READ);
  try{
   $object=$this->db->createCommand("SELECT o.*,s.report_date FROM `{$this->prefix}fm2_pilot_otiz_snapshot_objects` o JOIN `{$this->prefix}fm2_pilot_otiz_snapshots` s ON s.id=o.snapshot_id WHERE o.snapshot_id=:s AND o.object_id=:o",[':s'=>$snapshotId,':o'=>$objectId])->queryOne();
   if($object===false){$transaction->rollBack();return false;}
   $aggregate=$this->db->createCommand("SELECT COUNT(*) total,COALESCE(SUM(paid_cents),0) paid_cents,COALESCE(SUM(discipline_cents),0) discipline_cents,COALESCE(SUM(deadline_cents),0) deadline_cents,COALESCE(SUM(paid_cents+discipline_cents+deadline_cents),0) global_closed_cents FROM `{$this->prefix}fm2_pilot_otiz_payment_closures` WHERE object_id=:o",[':o'=>$objectId])->queryOne();
   $rows=[];
   if($page-1<=intdiv(PHP_INT_MAX,10)){$offset=($page-1)*10;$rows=$this->db->createCommand("SELECT c.*,s.report_date source_report_date,CASE WHEN c.reverses_payment_closure_id IS NOT NULL THEN 'reversal' WHEN c.paid_cents>0 THEN 'payment' ELSE 'deduction' END presentation_kind,original.id local_reversal_id,CASE WHEN original.id IS NULL THEN NULL ELSE 1+((SELECT COUNT(*) FROM `{$this->prefix}fm2_pilot_otiz_payment_closures` preceding WHERE preceding.object_id=c.object_id AND (preceding.closed_on>original.closed_on OR (preceding.closed_on=original.closed_on AND preceding.id>original.id))) DIV 10) END local_reversal_page FROM `{$this->prefix}fm2_pilot_otiz_payment_closures` c JOIN `{$this->prefix}fm2_pilot_otiz_snapshots` s ON s.id=c.snapshot_id LEFT JOIN `{$this->prefix}fm2_pilot_otiz_payment_closures` original ON original.id=c.reverses_payment_closure_id AND original.object_id=c.object_id WHERE c.object_id=:o ORDER BY c.closed_on DESC,c.id DESC LIMIT 10 OFFSET {$offset}",[':o'=>$objectId])->queryAll();}
   $transaction->commit();
   return['object'=>$object,'rows'=>$rows,'total'=>(int)$aggregate['total'],'totals'=>['paid_cents'=>(int)$aggregate['paid_cents'],'discipline_cents'=>(int)$aggregate['discipline_cents'],'deadline_cents'=>(int)$aggregate['deadline_cents'],'global_closed_cents'=>(int)$aggregate['global_closed_cents']],'page'=>$page,'page_size'=>10];
  }catch(\Throwable$e){if($transaction->isActive)$transaction->rollBack();throw$e;}
 }
 public function snapshots():array
 {
  return$this->db->createCommand("SELECT s.*,(SELECT u.full_name FROM `{$this->prefix}fm2_pilot_users` u WHERE u.user_id=s.calculated_by_user_id LIMIT 1) calculated_by_name,COUNT(DISTINCT o.object_id) object_count,COUNT(DISTINCT CASE WHEN i.severity='blocker' THEN i.id END) blocker_count,COUNT(DISTINCT CASE WHEN i.severity='warning' THEN i.id END) warning_count FROM `{$this->prefix}fm2_pilot_otiz_snapshots` s LEFT JOIN `{$this->prefix}fm2_pilot_otiz_snapshot_objects` o ON o.snapshot_id=s.id LEFT JOIN `{$this->prefix}fm2_pilot_otiz_snapshot_issues` i ON i.snapshot_id=s.id GROUP BY s.id ORDER BY s.report_date DESC,s.id DESC")->queryAll();
 }
 public function workbook(int$id):array|false
 {
  $p=$this->snapshot($id);if($p===false||$p['snapshot']['status']!=='accepted')return false;$s=$p['snapshot'];$allocations=$this->db->createCommand("SELECT a.*,o.regnumber FROM `{$this->prefix}fm2_pilot_otiz_snapshot_allocations` a JOIN `{$this->prefix}fm2_pilot_otiz_snapshot_objects` o ON o.snapshot_id=a.snapshot_id AND o.object_id=a.object_id WHERE a.snapshot_id=:id ORDER BY a.object_id,a.full_name",[':id'=>$id])->queryAll();$issues=$this->db->createCommand("SELECT i.*,o.regnumber FROM `{$this->prefix}fm2_pilot_otiz_snapshot_issues` i JOIN `{$this->prefix}fm2_pilot_otiz_snapshot_objects` o ON o.snapshot_id=i.snapshot_id AND o.object_id=i.object_id WHERE i.snapshot_id=:id ORDER BY i.object_id,i.severity",[':id'=>$id])->queryAll();
  $sheets=['Объекты'=>[['Регномер','Адрес','Квып','Ксс','Закрыто ранее','Новый пул','Статус']],'Работники'=>[['Регномер объекта','Табельный номер','ФИО','Должность','КТУ','Доля','Сумма']],'Контроль'=>[['Объект','Уровень','Код','Проблема','Владелец']],'Приложение к приказу'=>[['Табельный номер','ФИО','Сумма','Основание']],'Метаданные'=>[['Поле','Значение']]];
  foreach($p['objects']as$o)$sheets['Объекты'][]=[$o['regnumber'],$o['address'],(int)$o['current_progress_bp']/100,(int)$o['kss_bp']/10000,(int)$o['closed_before_cents']/100,(int)$o['pool_cents']/100,$o['calculation_state']];foreach($allocations as$a){$ktu=(int)$a['effective_ktu_bp'];if((int)$a['base_ktu_bp']===(int)$a['contribution_bp']&&$ktu===(int)$a['contribution_bp']&&str_contains((string)$a['participation_basis'],'коэффициент 1,00'))$ktu=10000;$sheets['Работники'][]=[$a['regnumber'],$a['tab_id'],$a['full_name'],$a['position_name'],$ktu/10000,(int)$a['share_bp']/100,(int)$a['amount_cents']/100];$sheets['Приложение к приказу'][]=[$a['tab_id'],$a['full_name'],(int)$a['amount_cents']/100,$a['participation_basis']];}foreach($issues as$i)$sheets['Контроль'][]=[$i['regnumber'],$i['severity'],$i['issue_code'],$i['message'],$i['owner_role']];foreach(OtizV2WorkbookEvidence::rows($p['objects'])as$row)$sheets['Метаданные'][]=$row;foreach([['Отчётная дата',$s['report_date']],['Версия правил',$s['rules_version']],['Hash',$s['content_hash']],['Принят',$s['accepted_at']]]as$row)$sheets['Метаданные'][]=$row;
  $files=['[Content_Types].xml'=>$this->types(count($sheets)),'_rels/.rels'=>'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>'];$workbook='<?xml version="1.0" encoding="UTF-8" standalone="yes"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets>';$rels='<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">';$n=1;foreach($sheets as$name=>$rows){$workbook.='<sheet name="'.$this->xml($name).'" sheetId="'.$n.'" r:id="rId'.$n.'"/>';$rels.='<Relationship Id="rId'.$n.'" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet'.$n.'.xml"/>';$files['xl/worksheets/sheet'.$n.'.xml']=$this->sheet($rows);$n++;}$files['xl/workbook.xml']=$workbook.'</sheets></workbook>';$files['xl/_rels/workbook.xml.rels']=$rels.'</Relationships>';return['filename'=>'FMonitor-OTIZ-'.$s['report_date'].'-v'.$id.'.xlsx','bytes'=>$this->zip($files)];
 }
 private function xml(mixed$v):string{return htmlspecialchars((string)$v,ENT_XML1|ENT_QUOTES,'UTF-8');}private function sheet(array$rows):string{$x='<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData>';foreach($rows as$row){$x.='<row>';foreach($row as$v)$x.=is_int($v)||is_float($v)?'<c><v>'.$v.'</v></c>':'<c t="inlineStr"><is><t>'.$this->xml($v).'</t></is></c>';$x.='</row>';}return$x.'</sheetData></worksheet>';}private function types(int$n):string{$x='<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>';for($i=1;$i<=$n;$i++)$x.='<Override PartName="/xl/worksheets/sheet'.$i.'.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>';return$x.'</Types>';}private function zip(array$files):string{$body='';$central='';$offset=0;foreach($files as$name=>$data){$crc=(int)sprintf('%u',crc32($data));$l=strlen($data);$nl=strlen($name);$local=pack('VvvvvvVVVvv',0x04034b50,20,0,0,0,0,$crc,$l,$l,$nl,0).$name.$data;$body.=$local;$central.=pack('VvvvvvvVVVvvvvvVV',0x02014b50,20,20,0,0,0,0,$crc,$l,$l,$nl,0,0,0,0,0,$offset).$name;$offset+=strlen($local);}return$body.$central.pack('VvvvvVVv',0x06054b50,0,0,count($files),count($files),strlen($central),strlen($body),0);}
}
