<?php
declare(strict_types=1);
namespace FMonitor2\Otiz;
use yii\db\Connection;
/** Read-only settlement projection; all monetary writes remain in OtizSettlement. */
final class MariaDbOtizSettlementView
{
 public function __construct(private Connection$db,private string$prefix){if(preg_match('/^[A-Za-z0-9_]{0,25}$/D',$prefix)!==1)throw new \InvalidArgumentException();}
 public function snapshot(int$id):array|false
 {
  $snapshot=$this->db->createCommand("SELECT * FROM `{$this->prefix}fm2_pilot_otiz_snapshots` WHERE id=:id",[':id'=>$id])->queryOne();if($snapshot===false)return false;
  $objects=$this->db->createCommand("SELECT * FROM `{$this->prefix}fm2_pilot_otiz_snapshot_objects` WHERE snapshot_id=:id ORDER BY object_id",[':id'=>$id])->queryAll();
  foreach($objects as&$object){$oid=(int)$object['object_id'];$object['global_closed_cents']=(int)$this->db->createCommand("SELECT COALESCE(SUM(paid_cents+discipline_cents+deadline_cents),0) FROM `{$this->prefix}fm2_pilot_otiz_payment_closures` WHERE object_id=:o",[':o'=>$oid])->queryScalar();$object['issues']=$this->db->createCommand("SELECT * FROM `{$this->prefix}fm2_pilot_otiz_snapshot_issues` WHERE snapshot_id=:s AND object_id=:o ORDER BY severity",[':s'=>$id,':o'=>$oid])->queryAll();$object['allocations']=$this->db->createCommand("SELECT * FROM `{$this->prefix}fm2_pilot_otiz_snapshot_allocations` WHERE snapshot_id=:s AND object_id=:o ORDER BY amount_cents DESC,full_name",[':s'=>$id,':o'=>$oid])->queryAll();}unset($object);
  $closures=$this->db->createCommand("SELECT c.*,o.regnumber FROM `{$this->prefix}fm2_pilot_otiz_payment_closures` c JOIN `{$this->prefix}fm2_pilot_otiz_snapshot_objects` o ON o.snapshot_id=c.snapshot_id AND o.object_id=c.object_id WHERE c.snapshot_id=:id ORDER BY c.id DESC",[':id'=>$id])->queryAll();
  return['snapshot'=>$snapshot,'objects'=>$objects,'closures'=>$closures];
 }
 public function snapshotForClosure(int$id):int|false{$v=$this->db->createCommand("SELECT snapshot_id FROM `{$this->prefix}fm2_pilot_otiz_payment_closures` WHERE id=:id",[':id'=>$id])->queryScalar();return$v===false?false:(int)$v;}
 public function snapshots():array{return$this->db->createCommand("SELECT id,report_date,status,total_pool_cents FROM `{$this->prefix}fm2_pilot_otiz_snapshots` ORDER BY report_date DESC,id DESC")->queryAll();}
 public function workbook(int$id):array|false
 {
  $p=$this->snapshot($id);if($p===false||$p['snapshot']['status']!=='accepted')return false;$s=$p['snapshot'];$allocations=$this->db->createCommand("SELECT a.*,o.regnumber FROM `{$this->prefix}fm2_pilot_otiz_snapshot_allocations` a JOIN `{$this->prefix}fm2_pilot_otiz_snapshot_objects` o ON o.snapshot_id=a.snapshot_id AND o.object_id=a.object_id WHERE a.snapshot_id=:id ORDER BY a.object_id,a.full_name",[':id'=>$id])->queryAll();$issues=$this->db->createCommand("SELECT i.*,o.regnumber FROM `{$this->prefix}fm2_pilot_otiz_snapshot_issues` i JOIN `{$this->prefix}fm2_pilot_otiz_snapshot_objects` o ON o.snapshot_id=i.snapshot_id AND o.object_id=i.object_id WHERE i.snapshot_id=:id ORDER BY i.object_id,i.severity",[':id'=>$id])->queryAll();
  $sheets=['Объекты'=>[['Регномер','Адрес','Квып','Ксс','Закрыто ранее','Новый пул','Статус']],'Работники'=>[['Регномер объекта','Табельный номер','ФИО','Должность','КТУ','Доля','Сумма']],'Контроль'=>[['Объект','Уровень','Код','Проблема','Владелец']],'Приложение к приказу'=>[['Табельный номер','ФИО','Сумма','Основание']],'Метаданные'=>[['Поле','Значение']]];
  foreach($p['objects']as$o)$sheets['Объекты'][]=[$o['regnumber'],$o['address'],(int)$o['current_progress_bp']/100,(int)$o['kss_bp']/10000,(int)$o['closed_before_cents']/100,(int)$o['pool_cents']/100,$o['calculation_state']];foreach($allocations as$a){$ktu=(int)$a['effective_ktu_bp'];if((int)$a['base_ktu_bp']===(int)$a['contribution_bp']&&$ktu===(int)$a['contribution_bp']&&str_contains((string)$a['participation_basis'],'коэффициент 1,00'))$ktu=10000;$sheets['Работники'][]=[$a['regnumber'],$a['tab_id'],$a['full_name'],$a['position_name'],$ktu/10000,(int)$a['share_bp']/100,(int)$a['amount_cents']/100];$sheets['Приложение к приказу'][]=[$a['tab_id'],$a['full_name'],(int)$a['amount_cents']/100,$a['participation_basis']];}foreach($issues as$i)$sheets['Контроль'][]=[$i['regnumber'],$i['severity'],$i['issue_code'],$i['message'],$i['owner_role']];foreach([['Отчётная дата',$s['report_date']],['Версия правил',$s['rules_version']],['Hash',$s['content_hash']],['Принят',$s['accepted_at']]]as$row)$sheets['Метаданные'][]=$row;
  $files=['[Content_Types].xml'=>$this->types(count($sheets)),'_rels/.rels'=>'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>'];$workbook='<?xml version="1.0" encoding="UTF-8" standalone="yes"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets>';$rels='<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">';$n=1;foreach($sheets as$name=>$rows){$workbook.='<sheet name="'.$this->xml($name).'" sheetId="'.$n.'" r:id="rId'.$n.'"/>';$rels.='<Relationship Id="rId'.$n.'" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet'.$n.'.xml"/>';$files['xl/worksheets/sheet'.$n.'.xml']=$this->sheet($rows);$n++;}$files['xl/workbook.xml']=$workbook.'</sheets></workbook>';$files['xl/_rels/workbook.xml.rels']=$rels.'</Relationships>';return['filename'=>'FMonitor-OTIZ-'.$s['report_date'].'-v'.$id.'.xlsx','bytes'=>$this->zip($files)];
 }
 private function xml(mixed$v):string{return htmlspecialchars((string)$v,ENT_XML1|ENT_QUOTES,'UTF-8');}private function sheet(array$rows):string{$x='<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData>';foreach($rows as$row){$x.='<row>';foreach($row as$v)$x.=is_int($v)||is_float($v)?'<c><v>'.$v.'</v></c>':'<c t="inlineStr"><is><t>'.$this->xml($v).'</t></is></c>';$x.='</row>';}return$x.'</sheetData></worksheet>';}private function types(int$n):string{$x='<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>';for($i=1;$i<=$n;$i++)$x.='<Override PartName="/xl/worksheets/sheet'.$i.'.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>';return$x.'</Types>';}private function zip(array$files):string{$body='';$central='';$offset=0;foreach($files as$name=>$data){$crc=(int)sprintf('%u',crc32($data));$l=strlen($data);$nl=strlen($name);$local=pack('VvvvvvVVVvv',0x04034b50,20,0,0,0,0,$crc,$l,$l,$nl,0).$name.$data;$body.=$local;$central.=pack('VvvvvvvVVVvvvvvVV',0x02014b50,20,20,0,0,0,0,$crc,$l,$l,$nl,0,0,0,0,0,$offset).$name;$offset+=strlen($local);}return$body.$central.pack('VvvvvVVv',0x06054b50,0,0,count($files),count($files),strlen($central),strlen($body),0);}
}
