<?php declare(strict_types=1);
namespace FMonitor2\Otiz;
if(!class_exists(\yii\db\Connection::class,false))require_once dirname(__DIR__,2).'/vendor/yiisoft/yii2/Yii.php';
use yii\db\Connection;

class MariaDbOtizPortfolioEconomy
{
 public function __construct(private Connection$db,private string$prefix,private string$legacyPrefix){}
 public function read(int$actor,array$q):array
 {
  if(!(int)$this->db->createCommand("SELECT COUNT(*) FROM `{$this->prefix}fm2_pilot_user_roles` ur JOIN `{$this->prefix}fm2_pilot_role_permissions` rp ON rp.role_id=ur.role_id WHERE ur.user_id=:u AND BINARY rp.permission='otiz.manage'",[':u'=>$actor])->queryScalar())throw new \DomainException('REGISTER_FORBIDDEN');
  $year=(string)($q['year']??'all');$needle=mb_strtolower(trim((string)($q['q']??'')),'UTF-8');$page=max(1,(int)($q['page']??1));$size=min(100,max(1,(int)($q['pageSize']??25)));$params=[];$conditions=[];
  if($year!=='all'){$conditions[]=$year==='Без года'?'plan_finish_date IS NULL':'YEAR(plan_finish_date)=:year';if($year!=='Без года')$params[':year']=(int)$year;}
  if($needle!==''){$conditions[]="LOCATE(:needle,LOWER(CONCAT(COALESCE(regnumber,''),' ',COALESCE(address,''))))>0";$params[':needle']=$needle;}
  $where=$conditions?' WHERE '.implode(' AND ',$conditions):'';$cte=$this->effectiveCte();$total=(int)$this->db->createCommand("{$cte} SELECT COUNT(*) FROM effective{$where}",$params)->queryScalar();$pages=max(1,(int)ceil($total/$size));if($page>$pages)throw new \DomainException('REGISTER_PAGE_NOT_FOUND');$direction=($q['sort']??'')==='regnumber_desc'?'DESC':'ASC';$offset=($page-1)*$size;
  $pageIds=array_map('intval',$this->db->createCommand("{$cte} SELECT object_id FROM effective{$where} ORDER BY regnumber {$direction},object_id {$direction} LIMIT {$size} OFFSET {$offset}",$params)->queryColumn());$allIds=array_map('intval',$this->db->createCommand("{$cte} SELECT object_id FROM effective{$where} ORDER BY object_id",$params)->queryColumn());$rows=$this->hydrate($pageIds);$payables=$this->payables($pageIds);$out=[];
  foreach($rows as$r){$id=(int)$r['object_id'];$details=$this->overlay($this->decode((string)($r['payload_json']??'')),$this->decode((string)($r['values_json']??'')));$fund=$this->fund($details);$objectPayables=$payables[$id]??[];$payable=array_sum(array_column($objectPayables,'remainingCents'));$approved=array_sum(array_column($objectPayables,'approvedContributionCents'));$paid=array_sum(array_column($objectPayables,'paidContributionCents'));$legacy=(int)$r['legacy_cents'];$out[]=['objectId'=>$id,'regnumber'=>(string)$r['regnumber'],'address'=>(string)$r['address'],'year'=>$r['plan_finish_date']?substr((string)$r['plan_finish_date'],0,4):'Без года','fundCents'=>$fund,'approvedCents'=>$approved,'paidCents'=>$paid,'payableCents'=>$payable,'payableCalculations'=>array_values(array_filter($objectPayables,static fn($x)=>$x['remainingCents']>0)),'unlinkedLegacyCents'=>$legacy,'diagnostic'=>$legacy>0&&$payable===0?'Не найдено основание задолженности':null];}
  $years=$this->db->createCommand("{$cte} SELECT DISTINCT COALESCE(CAST(YEAR(plan_finish_date) AS CHAR),'Без года') FROM effective ORDER BY 1")->queryColumn();return['rows'=>$out,'total'=>$total,'page'=>$page,'pageSize'=>$size,'facets'=>['years'=>$years],'summary'=>$this->summary($allIds),'globalPayableCents'=>$this->globalPayable()];
 }
 public function payableForObject(int$actor,int$objectId):array{return$this->payables([$objectId])[$objectId]??[];}
 public function fingerprint(int$actor):string{$ids=array_map('intval',$this->db->createCommand($this->effectiveCte().' SELECT object_id FROM effective ORDER BY object_id')->queryColumn());return hash('sha256',json_encode($this->summary($ids),JSON_THROW_ON_ERROR));}
 private function effectiveCte():string{return"WITH latest_edits AS (SELECT e.*,ROW_NUMBER() OVER(PARTITION BY object_id ORDER BY revision DESC) position_no FROM `{$this->prefix}fm2_object_detail_edits` e),effective AS (SELECT m.id object_id,COALESCE(NULLIF(JSON_UNQUOTE(JSON_EXTRACT(e.values_json,'$.regnumber')),'null'),m.regnumber) regnumber,COALESCE(NULLIF(JSON_UNQUOTE(JSON_EXTRACT(e.values_json,'$.address')),'null'),m.ordadr_address) address,m.plan_finish_date,e.values_json FROM `{$this->legacyPrefix}fm_maintable` m LEFT JOIN latest_edits e ON e.object_id=m.id AND e.position_no=1)";}
 private function hydrate(array$ids):array{if($ids===[])return[];$in=implode(',',array_map('intval',$ids));return$this->db->createCommand($this->effectiveCte()." SELECT e.*,d.payload_json,COALESCE(u.amount_cents,0) legacy_cents FROM effective e LEFT JOIN `{$this->prefix}fm2_pilot_object_details` d ON d.object_id=e.object_id LEFT JOIN (SELECT object_id,SUM(amount_cents) amount_cents FROM `{$this->prefix}fm2_otiz_unlinked_legacy_totals` GROUP BY object_id)u ON u.object_id=e.object_id WHERE e.object_id IN({$in}) ORDER BY FIELD(e.object_id,{$in})")->queryAll();}
 private function payables(array$ids):array{if($ids===[])return[];$in=implode(',',array_map('intval',$ids));$rows=$this->db->createCommand("SELECT o.object_id,c.id calculation_id,c.report_date,SUM(o.amount_cents) object_amount,(SELECT COALESCE(SUM(p.amount_cents),0) FROM `{$this->prefix}fm2_otiz_payment_facts` p WHERE p.calculation_id=c.id AND NOT EXISTS(SELECT 1 FROM `{$this->prefix}fm2_otiz_payment_reversals` r WHERE r.payment_id=p.id)) paid,(SELECT SUM(x.amount_cents) FROM `{$this->prefix}fm2_otiz_recipient_obligations` x WHERE x.calculation_id=c.id) calculation_total,(SELECT COUNT(DISTINCT x.object_id) FROM `{$this->prefix}fm2_otiz_recipient_obligations` x WHERE x.calculation_id=c.id) object_count FROM `{$this->prefix}fm2_otiz_calculation_revisions` c JOIN `{$this->prefix}fm2_otiz_recipient_obligations` o ON o.calculation_id=c.id WHERE c.status='accepted' AND o.object_id IN({$in}) GROUP BY o.object_id,c.id,c.report_date ORDER BY c.id")->queryAll();$out=[];foreach($rows as$r){$remaining=max(0,(int)$r['calculation_total']-(int)$r['paid']);$objectRemaining=$remaining>0?(int)$r['object_amount']:0;$out[(int)$r['object_id']][]=['calculationId'=>(int)$r['calculation_id'],'remainingCents'=>$objectRemaining,'objectContributionCents'=>$objectRemaining,'approvedContributionCents'=>(int)$r['object_amount'],'paidContributionCents'=>$remaining>0?0:(int)$r['object_amount'],'calculationRemainingCents'=>$remaining,'calculationObjectCount'=>(int)$r['object_count'],'reportDate'=>$r['report_date']];}foreach($out as&$items)usort($items,static fn($a,$b)=>(int)($b['remainingCents']>0)<=>(int)($a['remainingCents']>0));return$out;}
 private function summary(array$ids):array{if($ids===[])return['fundCents'=>0,'fundIncomplete'=>false,'approvedCents'=>0,'paidCents'=>0,'payableCents'=>0];$in=implode(',',array_map('intval',$ids));$rows=$this->db->createCommand("SELECT d.payload_json,e.values_json FROM `{$this->prefix}fm2_pilot_object_details` d LEFT JOIN (SELECT x.object_id,x.values_json FROM `{$this->prefix}fm2_object_detail_edits` x JOIN (SELECT object_id,MAX(revision) revision FROM `{$this->prefix}fm2_object_detail_edits` GROUP BY object_id)m ON m.object_id=x.object_id AND m.revision=x.revision)e ON e.object_id=d.object_id WHERE d.object_id IN({$in}) ORDER BY d.object_id")->queryAll();$fund=0;$incomplete=count($rows)!==count($ids);foreach($rows as$r){$value=$this->fund($this->overlay($this->decode((string)$r['payload_json']),$this->decode((string)($r['values_json']??''))));if($value===null)$incomplete=true;else$fund+=$value;}$approved=(int)$this->db->createCommand("SELECT COALESCE(SUM(o.amount_cents),0) FROM `{$this->prefix}fm2_otiz_recipient_obligations` o JOIN `{$this->prefix}fm2_otiz_calculation_revisions` c ON c.id=o.calculation_id WHERE c.status='accepted' AND o.object_id IN({$in})")->queryScalar();$paid=(int)$this->db->createCommand("SELECT COALESCE(SUM(o.amount_cents),0) FROM `{$this->prefix}fm2_otiz_recipient_obligations` o WHERE o.object_id IN({$in}) AND EXISTS(SELECT 1 FROM `{$this->prefix}fm2_otiz_payment_facts` p WHERE p.calculation_id=o.calculation_id AND NOT EXISTS(SELECT 1 FROM `{$this->prefix}fm2_otiz_payment_reversals` r WHERE r.payment_id=p.id))")->queryScalar();return['fundCents'=>$fund,'fundIncomplete'=>$incomplete,'approvedCents'=>$approved,'paidCents'=>$paid,'payableCents'=>max(0,$approved-$paid)];}
 private function globalPayable():int{$approved=(int)$this->db->createCommand("SELECT COALESCE(SUM(o.amount_cents),0) FROM `{$this->prefix}fm2_otiz_recipient_obligations` o JOIN `{$this->prefix}fm2_otiz_calculation_revisions` c ON c.id=o.calculation_id WHERE c.status='accepted'")->queryScalar();$paid=(int)$this->db->createCommand("SELECT COALESCE(SUM(p.amount_cents),0) FROM `{$this->prefix}fm2_otiz_payment_facts` p WHERE NOT EXISTS(SELECT 1 FROM `{$this->prefix}fm2_otiz_payment_reversals` r WHERE r.payment_id=p.id)")->queryScalar();return max(0,$approved-$paid);}
 private function overlay(array$d,array$values):array{foreach(['floors','weight','lift_type','pitmaterial']as$key)if(array_key_exists($key,$values)){$value=$values[$key];$display=$value;if(in_array($key,['lift_type','pitmaterial'],true)&&$value!==null){try{$display=\FMonitor2\InstallationProcess\ObjectDetailsReferenceCatalogue::display($key,(string)$value);}catch(\InvalidArgumentException){$display=$value;}}$d['fields'][$key]=['raw'=>$value,'display'=>$display];}return$d;}
 private function fund(array$details):?int{$fields=$details['fields']??[];$floors=filter_var($fields['floors']['raw']??null,FILTER_VALIDATE_INT);$capacity=filter_var($fields['weight']['raw']??null,FILTER_VALIDATE_INT);$typeText=mb_strtolower((string)($fields['lift_type']['display']??''),'UTF-8');$material=(string)($fields['pitmaterial']['display']??'');if($floors===false||$capacity===false)return null;$type=str_contains($typeText,'груз')||$typeText==='cargo'?'cargo':(str_contains($typeText,'пассаж')||$typeText==='passenger'?'passenger':null);if($type===null&&trim($typeText)!=='')return null;$norms=new NativePremiumNorms();$premium=$norms->premiumCents($type,(int)$floors,(int)$capacity);$shaft=$norms->shaftBasisPoints($material);return$premium===null||$shaft===null?null:intdiv($premium*$shaft,10000);}
 private function decode(string$json):array{if($json===''||!json_validate($json))return[];return json_decode($json,true,flags:JSON_THROW_ON_ERROR);}
}
