<?php declare(strict_types=1);
namespace FMonitor2\Otiz;
if(!class_exists(\yii\db\Connection::class,false))require_once dirname(__DIR__,2).'/vendor/yiisoft/yii2/Yii.php';
use yii\db\Connection;

class MariaDbOtizSettlementV2DraftBuilder
{
 private \Closure$clock;
 public function __construct(private Connection$db,private string$prefix,private string$legacyPrefix,?\Closure$clock=null){$this->clock=$clock??static fn():string=>(new \DateTimeImmutable('now',new \DateTimeZone('Europe/Moscow')))->format(\DateTimeImmutable::ATOM);}
 public function build(int$actor,string$date):array
 {
  if(!(int)$this->db->createCommand("SELECT COUNT(*) FROM `{$this->prefix}fm2_pilot_user_roles` ur JOIN `{$this->prefix}fm2_pilot_role_permissions` rp ON rp.role_id=ur.role_id WHERE ur.user_id=:u AND BINARY rp.permission='otiz.manage'",[':u'=>$actor])->queryScalar())throw new \DomainException('FORBIDDEN');
  preg_match('/host=([^;]+).*port=(\d+).*dbname=([^;]+)/D',(string)$this->db->dsn,$dsn);$mysqli=new \mysqli($dsn[1]??'127.0.0.1',(string)$this->db->username,(string)$this->db->password,$dsn[3]??'',(int)($dsn[2]??3306));$mysqli->set_charset('utf8mb4');try{$facts=(new MariaDbNativePremiumInputs($mysqli,$this->prefix,$this->legacyPrefix,$this->clock))->forDate($date);}finally{$mysqli->close();}
  $claimed=$this->claimState();$objects=[];
  foreach($facts as$f){$oid=(int)$f['id'];$case=(int)$f['caseId'];$fund=intdiv((int)$f['premium']*(int)$f['shaft'],10000);$e=$f['sourceEvidence'];$meta=$this->meta($case,$oid);$calculated=is_array($f['operands']??null)?PremiumCalculationV2::calculate($f['operands'],['closures'=>[],'actualPayouts'=>[]]):null;$rights=[];$checkBp=array_sum(array_map('intval',$e['progress']['contributions']??[]));if($checkBp===0)$checkBp=min(8500,(int)$f['progress']);$progressKey=implode('|',[$oid,'checklist','case-'.$case.'-checklist','progress']);$this->right($rights,$claimed,$oid,'checklist','case-'.$case.'-checklist',(string)($e['progress']['source']['contentSha256']??''),'progress',$date,intdiv($fund*$checkBp,10000));foreach(['pto_act'=>['pto',1000],'declaration'=>['declaration',500]]as$type=>[$kind,$bp])if($doc=$this->document($case,$type,$date))$this->right($rights,$claimed,$oid,$type,'completion-'.$doc['root_id'],hash('sha256',json_encode($doc,JSON_THROW_ON_ERROR)),$kind,$doc['fact_date'],intdiv($fund*$bp,10000));
   $progressDelta=[];$priorContributions=$claimed[$progressKey]['contributions']??[];foreach($e['progress']['contributions']??[]as$tab=>$bp){$delta=max(0,(int)$bp-(int)($priorContributions[(string)$tab]??0));if($delta>0)$progressDelta[(string)$tab]=$delta;}$progressRevision=(string)($e['progress']['source']['contentSha256']??'');$correctedTabs=(int)($claimed[$progressKey]['gross']??0)>=intdiv($fund*$checkBp,10000)&&($claimed[$progressKey]['sourceRevision']??$progressRevision)!==$progressRevision?$this->latestProgressRecipients($case,$date):[];
   $hasAttributionDelta=$progressDelta!==[]||$correctedTabs!==[];$hasDocumentary=false;foreach($rights as$right)if(in_array($right['kind'],['pto','declaration'],true))$hasDocumentary=true;
   $recipients=[];foreach($f['team']??[]as$m){$tab=(string)$m['tab'];$weight=$correctedTabs!==[]?(in_array($tab,$correctedTabs,true)?1:0):($progressDelta!==[]?($progressDelta[$tab]??0):($hasDocumentary?1:(int)$m['weight']));if($weight<=0)continue;$recipients[]=['employeeId'=>$tab,'tabNumber'=>$tab,'name'=>(string)$m['name'],'weight'=>$weight,'employment'=>(string)($m['employment']??'unknown'),'employmentSource'=>(string)($m['employmentSource']??''),'employmentAsOf'=>$m['employmentAsOf']??null,'position'=>(string)($m['position']??''),'attributionBasis'=>$hasAttributionDelta?'Вклад только впервые признаваемых/corrected checklist-работ':($hasDocumentary?'Равная доля действующего состава для документарного права':(string)($m['basis']??''))];}
   $effectiveKss=$hasDocumentary?$this->documentaryKss($oid,$calculated['kssBp']??null):($calculated['kssBp']??null);$gross=array_sum(array_column($rights,'grossCents'));$objects[]=['objectId'=>$oid,'regnumber'=>(string)$f['reg'],'address'=>(string)$f['address'],'fundCents'=>$fund,'plannedPremiumCents'=>(int)$f['premium'],'shaftBp'=>(int)$f['shaft'],'kssBp'=>$effectiveKss,'daysLate'=>$calculated['daysLate']??null,'paidBeforeCents'=>$this->paidBefore($oid),'responsibleName'=>$meta['responsibleName'],'objectStatus'=>$meta['objectStatus'],'change'=>$meta['change'],'changeDate'=>$meta['changeDate'],'confirmedBp'=>(int)$f['progress'],'acceptedBp'=>0,'calculationState'=>($f['issues']!==[]||($gross>0&&$recipients===[]))?'blocked':'ready','entitlements'=>$rights,'recipients'=>$recipients,'sourceEvidence'=>$e,'issues'=>$f['issues']];
  }
  foreach($objects as&$object)$object['deadlineBp']=$object['kssBp'];unset($object);return['reportDate'=>$date,'sourceMode'=>'canonical','objects'=>$objects];
 }
 public function buildReplacement(int$actor,string$date,int$calculationId):array
 {
  $current=$this->build($actor,$date);$row=$this->db->createCommand("SELECT input_json FROM `{$this->prefix}fm2_otiz_calculation_revisions` WHERE id=:id AND status='accepted'",[':id'=>$calculationId])->queryOne();if($row===false)throw new \DomainException('CALCULATION_IMMUTABLE');$old=json_decode((string)$row['input_json'],true,flags:JSON_THROW_ON_ERROR);$byObject=[];foreach($current['objects']??[]as$object)$byObject[(int)$object['objectId']]=$object;$objects=[];
  foreach($old['objects']??[]as$object){$oid=(int)$object['objectId'];$canonical=$byObject[$oid]??null;if($canonical===null)throw new \DomainException('INCOMPLETE_REPLACEMENT');$claims=$this->db->createCommand("SELECT source_kind,source_id,source_revision,entitlement_kind,recognition_date,gross_cents FROM `{$this->prefix}fm2_otiz_entitlement_claims` WHERE calculation_id=:id AND object_id=:object AND active=1 ORDER BY id",[':id'=>$calculationId,':object'=>$oid])->queryAll();$rights=[];$ownedKeys=[];foreach($claims as$claim){$gross=(int)$claim['gross_cents'];$ownedKeys[implode('|',[$oid,$claim['source_kind'],$claim['source_id'],$claim['entitlement_kind']])]=true;$rights[]=['rightKey'=>implode('|',[$oid,$claim['source_kind'],$claim['source_id'],$claim['entitlement_kind']]),'sourceKind'=>$claim['source_kind'],'sourceId'=>$claim['source_id'],'sourceRevision'=>$claim['source_revision'],'kind'=>$claim['entitlement_kind'],'recognitionDate'=>$claim['recognition_date'],'baselineClaimedCents'=>$this->frontier(implode('|',[$oid,$claim['source_kind'],$claim['source_id'],$claim['entitlement_kind']])),'cumulativeGrossCents'=>$gross,'grossCents'=>$gross];}foreach($canonical['entitlements']??[]as$newRight){$key=implode('|',[$oid,$newRight['sourceKind'],$newRight['sourceId'],$newRight['kind']]);if((int)($newRight['grossCents']??0)>0)$rights[]=$newRight;}foreach(['fundCents','plannedPremiumCents','shaftBp','kssBp','deadlineBp','daysLate']as$key)if(array_key_exists($key,$object))$canonical[$key]=$object[$key];$canonical['entitlements']=$rights;$canonical['recipients']=$this->replacementRecipients($canonical,$object);$canonical['calculationState']=$canonical['recipients']===[]?'blocked':'ready';$objects[]=$canonical;}
  return['reportDate'=>$date,'sourceMode'=>'canonical-replacement','objects'=>$objects];
 }
 private function frontier(string$key):int{return(int)$this->db->createCommand("SELECT claimed_cents FROM `{$this->prefix}fm2_otiz_entitlement_frontiers` WHERE right_key=:key",[':key'=>$key])->queryScalar();}
 private function replacementRecipients(array$current,array$old):array{if(($current['recipients']??[])!==[])return$current['recipients'];return$old['recipients']??[];}
 private function claimState():array{$rows=$this->db->createCommand("SELECT c.object_id,c.source_kind,c.source_id,c.source_revision,c.entitlement_kind,c.gross_cents,r.input_json FROM `{$this->prefix}fm2_otiz_entitlement_claims` c JOIN `{$this->prefix}fm2_otiz_calculation_revisions` r ON r.id=c.calculation_id WHERE c.active=1 ORDER BY c.id")->queryAll();$out=[];foreach($rows as$row){$key=implode('|',[(int)$row['object_id'],$row['source_kind'],$row['source_id'],$row['entitlement_kind']]);$out[$key]['gross']=($out[$key]['gross']??0)+(int)$row['gross_cents'];$out[$key]['sourceRevision']=(string)$row['source_revision'];$input=json_decode((string)$row['input_json'],true);foreach($input['objects']??[]as$object)if((int)$object['objectId']===(int)$row['object_id']){$contributions=$object['sourceEvidence']['progress']['contributions']??null;if(is_array($contributions))$out[$key]['contributions']=array_map('intval',$contributions);break;}}return$out;}
 private function right(array&$out,array$claimed,int$o,string$sourceKind,string$sourceId,string$revision,string$kind,string$date,int$cumulative):void{$rightKey=implode('|',[$o,$sourceKind,$sourceId,$kind]);$prior=(int)($claimed[$rightKey]['gross']??0);$delta=max(0,$cumulative-$prior);if($delta>0)$out[]=['rightKey'=>$rightKey,'sourceKind'=>$sourceKind,'sourceId'=>$sourceId,'sourceRevision'=>$revision,'kind'=>$kind,'recognitionDate'=>$date,'baselineClaimedCents'=>$prior,'cumulativeGrossCents'=>$cumulative,'grossCents'=>$delta];}
 private function latestProgressRecipients(int$case,string$date):array{$received=substr(($this->clock)(),0,10);$operation=$this->db->createCommand("SELECT client_operation_id FROM `{$this->prefix}fm2_checklist_operations` WHERE installation_case_id=:case AND operation_type='item_completed' AND LEFT(device_time,10)<=:date AND LEFT(server_received_at,10)<=:received ORDER BY accepted_revision DESC,id DESC LIMIT 1",[':case'=>$case,':date'=>$date,':received'=>$received])->queryScalar();if(!is_string($operation))return[];return array_map('strval',$this->db->createCommand("SELECT installer_tab_id FROM `{$this->prefix}fm2_checklist_operation_installers` WHERE client_operation_id=:id ORDER BY installer_tab_id",[':id'=>$operation])->queryColumn());}
 private function documentaryKss(int$objectId,mixed$current):?int{$rows=$this->db->createCommand("SELECT projection_json FROM `{$this->prefix}fm2_otiz_calculation_revisions` WHERE status='accepted' ORDER BY id")->queryColumn();$values=[];foreach($rows as$json)foreach((json_decode((string)$json,true)['objects']??[])as$object)if((int)($object['objectId']??0)===$objectId&&isset($object['kssBp']))$values[]=(int)$object['kssBp'];if($current!==null)$values[]=(int)$current;return$values===[]?null:min($values);}
 private function document(int$case,string$type,string$cut):?array{$prepared=substr(($this->clock)(),0,10);$row=$this->db->createCommand("SELECT id root_id,fact_date,recorded_at FROM `{$this->prefix}fm2_pilot_completion_facts` WHERE installation_case_id=:c AND fact_type=:t AND fact_date<=:d AND LEFT(recorded_at,10)<=:prepared ORDER BY id DESC LIMIT 1",[':c'=>$case,':t'=>$type,':d'=>$cut,':prepared'=>$prepared])->queryOne();if($row===false)return null;$correction=$this->db->createCommand("SELECT fact_date,recorded_at,version_no,id FROM `{$this->prefix}fm2_pilot_completion_fact_corrections` WHERE root_fact_id=:id AND fact_date<=:d AND LEFT(recorded_at,10)<=:prepared ORDER BY version_no DESC,id DESC LIMIT 1",[':id'=>$row['root_id'],':d'=>$cut,':prepared'=>$prepared])->queryOne();return$correction===false?$row:array_replace($row,$correction);}
 private function paidBefore(int$object):int{return(int)$this->db->createCommand("SELECT COALESCE(SUM(o.amount_cents),0) FROM `{$this->prefix}fm2_otiz_recipient_obligations` o WHERE o.object_id=:o AND EXISTS(SELECT 1 FROM `{$this->prefix}fm2_otiz_payment_facts` p WHERE p.calculation_id=o.calculation_id AND NOT EXISTS(SELECT 1 FROM `{$this->prefix}fm2_otiz_payment_reversals` r WHERE r.payment_id=p.id))",[':o'=>$object])->queryScalar();}
 private function meta(int$case,int$object):array{$application=$this->db->createCommand("SELECT selected_snapshot_json FROM `{$this->prefix}fm2_assignment_order_applications` WHERE installation_case_id=:c AND object_id=:o ORDER BY application_sequence DESC LIMIT 1",[':c'=>$case,':o'=>$object])->queryScalar();$snapshot=is_string($application)?json_decode($application,true):[];$status=$this->db->createCommand("SELECT process_state FROM `{$this->prefix}fm2_installation_cases` WHERE id=:c",[':c'=>$case])->queryScalar();$edit=$this->db->createCommand("SELECT revision,updated_at_utc FROM `{$this->prefix}fm2_object_detail_edits` WHERE object_id=:o ORDER BY revision DESC LIMIT 1",[':o'=>$object])->queryOne();return['responsibleName'=>$snapshot['selectedEngineer']['fullName']??null,'objectStatus'=>$status===false?null:(string)$status,'change'=>$edit===false?null:'object_details_revision_'.$edit['revision'],'changeDate'=>$edit===false?null:(string)$edit['updated_at_utc']];}
}
