<?php declare(strict_types=1);
namespace FMonitor2\Otiz;
if(!class_exists(\yii\db\Connection::class,false))require_once dirname(__DIR__,2).'/vendor/yiisoft/yii2/Yii.php';
use yii\db\Connection;

final class OtizSettlementV2DraftBuilder
{
 public function __construct(private Connection$db,private string$prefix,private string$legacyPrefix){}
 public function build(int$actor,string$date):array
 {
  if(!(int)$this->db->createCommand("SELECT COUNT(*) FROM `{$this->prefix}fm2_pilot_user_roles` ur JOIN `{$this->prefix}fm2_pilot_role_permissions` rp ON rp.role_id=ur.role_id WHERE ur.user_id=:u AND BINARY rp.permission='otiz.manage'",[':u'=>$actor])->queryScalar())throw new \DomainException('FORBIDDEN');preg_match('/host=([^;]+).*port=(\d+).*dbname=([^;]+)/D',(string)$this->db->dsn,$dsn);$mysqli=new \mysqli($dsn[1]??'127.0.0.1',(string)$this->db->username,(string)$this->db->password,$dsn[3]??'',(int)($dsn[2]??3306));$mysqli->set_charset('utf8mb4');try{$facts=(new MariaDbNativePremiumInputs($mysqli,$this->prefix,$this->legacyPrefix))->forDate($date);}finally{$mysqli->close();}$claimed=$this->claims();$objects=[];
  foreach($facts as$f){$oid=(int)$f['id'];$case=(int)$f['caseId'];$fund=intdiv((int)$f['premium']*(int)$f['shaft'],10000);$e=$f['sourceEvidence'];$meta=$this->meta($case,$oid);$calculated=is_array($f['operands']??null)?PremiumCalculationV2::calculate($f['operands'],['closures'=>[],'actualPayouts'=>[]]):null;$rights=[];$checkBp=array_sum(array_map('intval',$e['progress']['contributions']??[]));if($checkBp===0)$checkBp=min(8500,(int)$f['progress']);$this->right($rights,$claimed,$oid,'checklist','case-'.$case.'-checklist',(string)($e['progress']['source']['contentSha256']??''),'progress',$date,intdiv($fund*$checkBp,10000));foreach(['pto_act'=>['pto',1000],'declaration'=>['declaration',500]]as$type=>[$kind,$bp])if($doc=$this->document($case,$type,$date))$this->right($rights,$claimed,$oid,$type,'completion-'.$doc['root_id'],hash('sha256',json_encode($doc,JSON_THROW_ON_ERROR)),$kind,$doc['fact_date'],intdiv($fund*$bp,10000));$recipients=[];foreach($f['team']??[]as$m)$recipients[]=['employeeId'=>(string)$m['tab'],'tabNumber'=>(string)$m['tab'],'name'=>(string)$m['name'],'weight'=>max(1,(int)$m['weight']),'employment'=>(string)($m['employment']??'unknown'),'employmentSource'=>(string)($m['employmentSource']??''),'employmentAsOf'=>$m['employmentAsOf']??null,'position'=>(string)($m['position']??''),'attributionBasis'=>(string)($m['basis']??'')];$gross=array_sum(array_column($rights,'grossCents'));$objects[]=['objectId'=>$oid,'regnumber'=>(string)$f['reg'],'address'=>(string)$f['address'],'fundCents'=>$fund,'plannedPremiumCents'=>(int)$f['premium'],'shaftBp'=>(int)$f['shaft'],'kssBp'=>$calculated['kssBp']??null,'daysLate'=>$calculated['daysLate']??null,'paidBeforeCents'=>$this->paidBefore($oid),'responsibleName'=>$meta['responsibleName'],'objectStatus'=>$meta['objectStatus'],'change'=>$meta['change'],'changeDate'=>$meta['changeDate'],'confirmedBp'=>(int)$f['progress'],'acceptedBp'=>0,'calculationState'=>($f['issues']!==[]||($gross>0&&$recipients===[]))?'blocked':'ready','entitlements'=>$rights,'recipients'=>$recipients,'sourceEvidence'=>$e,'issues'=>$f['issues']];}
  return['reportDate'=>$date,'sourceMode'=>'canonical','objects'=>$objects];
 }
 private function claims():array{$rows=$this->db->createCommand("SELECT object_id,source_kind,source_id,entitlement_kind,SUM(gross_cents) gross FROM `{$this->prefix}fm2_otiz_entitlement_claims` WHERE active=1 GROUP BY object_id,source_kind,source_id,entitlement_kind")->queryAll();$out=[];foreach($rows as$r)$out[implode('|',[$r['object_id'],$r['source_kind'],$r['source_id'],$r['entitlement_kind']])]=(int)$r['gross'];return$out;}
 private function right(array&$out,array$claimed,int$o,string$sourceKind,string$sourceId,string$revision,string$kind,string$date,int$cumulative):void{$prior=$claimed[implode('|',[$o,$sourceKind,$sourceId,$kind])]??0;$delta=max(0,$cumulative-$prior);if($delta>0)$out[]=['sourceKind'=>$sourceKind,'sourceId'=>$sourceId,'sourceRevision'=>$revision,'kind'=>$kind,'recognitionDate'=>$date,'grossCents'=>$delta];}
 private function document(int$case,string$type,string$cut):?array{$row=$this->db->createCommand("SELECT id root_id,fact_date,recorded_at FROM `{$this->prefix}fm2_pilot_completion_facts` WHERE installation_case_id=:c AND fact_type=:t AND fact_date<=:d AND LEFT(recorded_at,10)<=:d ORDER BY id DESC LIMIT 1",[':c'=>$case,':t'=>$type,':d'=>$cut])->queryOne();if($row===false)return null;$correction=$this->db->createCommand("SELECT fact_date,recorded_at,version_no,id FROM `{$this->prefix}fm2_pilot_completion_fact_corrections` WHERE root_fact_id=:id AND LEFT(recorded_at,10)<=:d ORDER BY version_no DESC,id DESC LIMIT 1",[':id'=>$row['root_id'],':d'=>$cut])->queryOne();return$correction===false?$row:array_replace($row,$correction);}
 private function paidBefore(int$object):int{return(int)$this->db->createCommand("SELECT COALESCE(SUM(o.amount_cents),0) FROM `{$this->prefix}fm2_otiz_recipient_obligations` o WHERE o.object_id=:o AND EXISTS(SELECT 1 FROM `{$this->prefix}fm2_otiz_payment_facts` p WHERE p.calculation_id=o.calculation_id AND NOT EXISTS(SELECT 1 FROM `{$this->prefix}fm2_otiz_payment_reversals` r WHERE r.payment_id=p.id))",[':o'=>$object])->queryScalar();}
 private function meta(int$case,int$object):array{$application=$this->db->createCommand("SELECT selected_snapshot_json FROM `{$this->prefix}fm2_assignment_order_applications` WHERE installation_case_id=:c AND object_id=:o ORDER BY application_sequence DESC LIMIT 1",[':c'=>$case,':o'=>$object])->queryScalar();$snapshot=is_string($application)?json_decode($application,true):[];$status=$this->db->createCommand("SELECT process_state FROM `{$this->prefix}fm2_installation_cases` WHERE id=:c",[':c'=>$case])->queryScalar();$edit=$this->db->createCommand("SELECT revision,updated_at_utc FROM `{$this->prefix}fm2_object_detail_edits` WHERE object_id=:o ORDER BY revision DESC LIMIT 1",[':o'=>$object])->queryOne();return['responsibleName'=>$snapshot['selectedEngineer']['fullName']??null,'objectStatus'=>$status===false?null:(string)$status,'change'=>$edit===false?null:'object_details_revision_'.$edit['revision'],'changeDate'=>$edit===false?null:(string)$edit['updated_at_utc']];}
}
