<?php declare(strict_types=1);
namespace FMonitor2\Otiz;
final class OtizSettlementV2Workbook{
 public static function paymentExportAllowed(array$s,string$a):bool{return$a==='allow';}public static function historicalExportAllowed(array$s):bool{return true;}
 public static function build(array$s):array{
  $m=(string)($s['mode']??'draft');if(!in_array($m,['draft','history','payment'],true))throw new \InvalidArgumentException('EXPORT_MODE_INVALID');$c=$s['calculation'];if($m==='payment'&&($c['status']??null)!=='accepted')throw new \DomainException('PAYMENT_EXPORT_STATE_INVALID');$label=$m==='draft'?'Черновик. Не основание выплаты':($m==='history'?'Историческая выгрузка':'Реестр к выплате');
  $h=['Расчетный период','Рег. номер','Коэффициент типа шахты','Плановая премия за монтаж, руб.','Фамилия, имя, отчество работника','Таб. №','Квып','Премия за монтаж, выплаченная ранее, руб.','Количество дней просрочки, дн.','Ксобл.срок.','Сумма удержания за несоблюдение сроков, руб.','Расчетная премия к распределению, руб.','КТУ работника','Премия с учетом КТУ, руб.','Дисциплинарная поправка, руб.','Премия за монтаж к выплате, руб.','Ответственный производитель работ','Статус работника','Изменение','Дата внесения изменения','Статус объекта'];
  $sh=['Расчёт ОТиЗ'=>[[$label],$h],'Объекты'=>[['Регномер','Адрес','Фонд, руб.','Начислено, руб.','Сроки, руб.','Дисциплина, руб.','К выплате, руб.']],'Работники'=>[['Регномер','Табельный номер','ФИО','Вес','Доля, б.п.','Сумма, руб.']],'Контроль'=>[['Код','Сообщение']],'Приложение к приказу'=>[['Табельный номер','ФИО','Сумма, руб.','Основание']],'Основания'=>[['Объект','Вид','Источник','Версия/хеш','Дата признания','Сумма, руб.']],'Метаданные'=>[['Поле','Значение'],['Режим',$label],['Расчёт',(int)$c['id']],['Дата расчёта',$c['reportDate']],['Версия правил',$c['rulesVersion']??'otiz-v2'],['Редакция',(int)$c['revision']],['Хеш содержимого',$c['contentHash']??''],['Принят',$c['acceptedAt']??''],['Принял',$c['acceptedBy']??'']],'Удержания'=>[['Объект','Работник','Сумма, руб.','Причина','Документ']],'Решения по выплате'=>[['Работник','Решение','Причина','Автор','Дата']]];
  $objects=[];$diagnostics=[];foreach($s['objects']??[]as$o){$objects[(string)$o['objectId']]=$o;$sh['Объекты'][]=[$o['regnumber'],$o['address']??'',self::rub($o['fundCents']??null),self::rub($o['grossCents']??null),self::rub($o['deadlineCents']??null),self::rub($o['disciplineCents']??null),self::rub($o['payableCents']??null)];foreach($o['entitlements']??[]as$e)$sh['Основания'][]=[$o['regnumber']??$o['objectId'],self::kind($e['kind']??null),$e['sourceId']??'Нет данных',$e['sourceRevision']??'Нет данных',self::date($e['recognitionDate']??null),self::rub($e['grossCents']??null)];foreach($o['issues']??[]as$i){$key=(string)$o['objectId'].'|'.(string)($i['code']??'');if(isset($diagnostics[$key]))continue;$diagnostics[$key]=true;$sh['Контроль'][]=[$i['code']??'',($o['regnumber']??$o['objectId']).': '.($i['message']??$i['code']??'')];}if(($o['entitlements']??[])===[])$sh['Основания'][]=[$o['regnumber']??$o['objectId'],'Нет данных',$o['sourceEvidence']['progress']['source']['locator']??'Нет данных',$o['sourceEvidence']['progress']['source']['contentSha256']??'Нет данных','Нет данных',''];}
  $weightTotals=self::weightTotals($s['recipients']??[]);
  $agg=[];foreach($s['recipients']??[]as$r){$o=$objects[(string)$r['objectId']]??[];$personal=0;foreach($s['deductions']??[]as$d)if((string)($d['objectId']??'')===(string)$r['objectId']&&($d['employeeId']??null)!==null&&(string)$d['employeeId']===(string)$r['employeeId'])$personal+=(int)$d['amountCents'];$sh['Расчёт ОТиЗ'][]=[self::date($c['reportDate']),$o['regnumber']??'',self::ratio($o['shaftBp']??null),self::rub($o['plannedPremiumCents']??null),$r['name'],(string)$r['tabNumber'],self::ratio($o['confirmedBp']??null),self::rub($o['paidBeforeCents']??null),$o['daysLate']===null?'':(int)$o['daysLate'],self::ratio($o['kssBp']??null),self::rub($o['deadlineCents']??null),self::rub($o['grossCents']??null),self::contribution($r,$weightTotals),self::rub($r['preDeductionCents']??null),$personal/100,(int)$r['amountCents']/100,$o['responsibleName']??'',self::employment($r['employment']??null),self::change($o['change']??''),self::date($o['changeDate']??''),self::objectStatus($o['objectStatus']??null)];$sh['Работники'][]=[$o['regnumber']??(string)$r['objectId'],(string)$r['tabNumber'],$r['name'],(int)($r['originalWeight']??$r['weight']??0),(($o['payableCents']??0)>0?(int)$r['amountCents']/(int)$o['payableCents']:(int)($r['finalShareBp']??0)/10000),(int)$r['amountCents']/100];$k=(string)$r['employeeId'];$agg[$k]??=['tab'=>(string)$r['tabNumber'],'name'=>$r['name'],'cents'=>0,'basis'=>[]];$agg[$k]['cents']+=(int)$r['amountCents'];$agg[$k]['basis'][]=(string)($o['regnumber']??$r['objectId']);}
  foreach($agg as$a)if($a['cents']>0)$sh['Приложение к приказу'][]=[$a['tab'],$a['name'],$a['cents']/100,implode(', ',array_unique($a['basis']))];foreach($s['issues']??[]as$i){$code=$i['code']??$i['reasonCode']??'';$object=(string)($i['objectId']??'');$key=$object.'|'.$code;if(isset($diagnostics[$key]))continue;$diagnostics[$key]=true;$sh['Контроль'][]=[$code,$i['message']??$code];}foreach($s['deductions']??[]as$d)$sh['Удержания'][]=[$d['objectId']??'',$d['employeeId']??'',(int)$d['amountCents']/100,$d['reason']??'',$d['document']??''];foreach($s['decisions']??[]as$d)$sh['Решения по выплате'][]=[$d['employeeId']??'',self::decision($d['decision']??null),$d['reason']??'',$d['actorId']??'',$d['createdAt']??''];if($m==='history')$sh['Метаданные'][]=['Контекст','на момент выгрузки '.($s['exportedAt']??'')];
  $f=['[Content_Types].xml'=>self::types(count($sh)),'_rels/.rels'=>'<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>','xl/styles.xml'=>self::styles()];$w='<?xml version="1.0" encoding="UTF-8"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets>';$rels='<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">';$n=1;foreach($sh as$name=>$rows){$w.='<sheet name="'.self::xml($name).'" sheetId="'.$n.'" r:id="rId'.$n.'"/>';$rels.='<Relationship Id="rId'.$n.'" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet'.$n.'.xml"/>';$f['xl/worksheets/sheet'.$n.'.xml']=self::sheet($rows,$name==='Расчёт ОТиЗ');$n++;}$w.='</sheets><definedNames><definedName name="_xlnm.Print_Area" localSheetId="0">\'Расчёт ОТиЗ\'!$A$1:$U$'.count($sh['Расчёт ОТиЗ']).'</definedName><definedName name="_xlnm.Print_Titles" localSheetId="0">\'Расчёт ОТиЗ\'!$1:$2</definedName></definedNames></workbook>';$f['xl/workbook.xml']=$w;$f['xl/_rels/workbook.xml.rels']=$rels.'<Relationship Id="rIdStyles" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>';$fn='FMonitor-OTIZ-'.$c['id'].($m==='history'?'-История':($m==='payment'?'-К-выплате':'')).'.xlsx';if($m==='draft')$fn='FMonitor-OTIZ-Черновик-Не-основание-выплаты-'.$c['id'].'.xlsx';return['filename'=>$fn,'bytes'=>self::zip($f)];
 }
 // Original contribution belongs to the saved object slice, before payout decisions.
 private static function weightTotals(array $recipients): array {
  $totals=[];$unknown=[];
  foreach($recipients as $recipient){
   $id=(string)$recipient['objectId'];$weight=$recipient['originalWeight']??$recipient['weight']??null;
   if(!is_numeric($weight)||$weight<0){$unknown[$id]=true;continue;}
   $totals[$id]=($totals[$id]??0)+(int)$weight;
  }
  foreach($unknown as $id=>$_)$totals[$id]=null;
  return $totals;
 }
 private static function contribution(array $recipient,array $totals): array {
  $total=$totals[(string)$recipient['objectId']]??0;
  return ['value'=>$total>0?(int)($recipient['originalWeight']??$recipient['weight'])/$total:'','style'=>3];
 }
 private static function employment(?string $value): string {
  return match($value){'employed'=>'Трудоустроен','dismissed'=>'Уволен',default=>'Нет данных'};
 }
 private static function objectStatus(?string $value): string {
  return match($value){
   'needs_assignment_order','assignment_order_prepared'=>'Требуется распоряжение',
   'ready_to_open'=>'Готов к открытию',
   'working','installation'=>'Монтажные работы',
   'document_closeout'=>'Документарное закрытие',
   'completed'=>'Работы завершены',
   'needs_assignment_change','assignment_change_prepared'=>'Требуется изменение',
   'Требуется распоряжение','Готов к открытию','Монтажные работы','Документарное закрытие','Работы завершены','Требуется изменение'=>$value,
   default=>'Нет данных',
  };
 }
 private static function decision(?string $value): string {
  return match($value){'pay'=>'Платить','do_not_pay'=>'Не платить',default=>'Нет данных'};
 }
 private static function kind(?string $value): string {
  return match($value){'progress'=>'Выполненные работы','pto','pto_act'=>'Акт ПТО','declaration'=>'Декларация',default=>'Нет данных'};
 }
 private static function change(string $value): string {
  return preg_match('/^object_details_revision_(\d+)$/D',$value,$match)===1?'Изменение реквизитов объекта № '.$match[1]:$value;
 }
 private static function date(mixed$v):array{if(!is_string($v)||preg_match('/^\d{4}-\d{2}-\d{2}$/D',$v)!==1)return['value'=>'','style'=>1];$d=new \DateTimeImmutable($v,new \DateTimeZone('UTC'));$base=new \DateTimeImmutable('1899-12-30',new \DateTimeZone('UTC'));return['value'=>(int)$base->diff($d)->days,'style'=>1];}private static function ratio(mixed$v):array{return['value'=>$v===null?'':(int)$v/10000,'style'=>2];}private static function rub(mixed$v):array{return['value'=>$v===null?'':(int)$v/100,'style'=>3];}
 private static function sheet(array$rows,bool$main):string{$x='<?xml version="1.0" encoding="UTF-8"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><cols>';$widths=$main?[14,14,13,18,30,13,12,20,14,13,18,18,13,18,18,18,30,18,24,18,18]:[18,28,28,18,18,18,18];foreach($widths as$i=>$v)$x.='<col min="'.($i+1).'" max="'.($i+1).'" width="'.$v.'" customWidth="1"/>';$headers=$rows[$main?1:0]??[];$x.='</cols><sheetViews><sheetView workbookViewId="0"><pane ySplit="'.($main?2:1).'" topLeftCell="'.($main?'A3':'A2').'" state="frozen"/></sheetView></sheetViews><sheetData>';$rn=1;foreach($rows as$row){$x.='<row r="'.$rn.'">';foreach($row as$ci=>$v){$style=is_array($v)?(int)$v['style']:(($main?$rn===2:$rn===1)?4:0);if($main&&$rn>2&&in_array($ci,[2,3,7,9,10,11,13,14,15],true))$style=3;if(!$main&&$rn>1&&str_contains((string)($headers[$ci]??''),'Сумма'))$style=3;if(!$main&&$rn>1&&($headers[$ci]??'')==='Доля, б.п.')$style=2;$v=is_array($v)?$v['value']:$v;$num=(is_int($v)||is_float($v))&&$v!=='';$ref=self::col($ci+1).$rn;$x.=$num?'<c r="'.$ref.'" s="'.$style.'" t="n"><v>'.$v.'</v></c>':'<c r="'.$ref.'" s="'.$style.'" t="inlineStr"><is><t>'.self::xml($v).'</t></is></c>';}$x.='</row>';$rn++;}$last=self::col(count($headers?:[1]));return$x.'</sheetData>'.($main?'<mergeCells count="1"><mergeCell ref="A1:U1"/></mergeCells>':'').'<autoFilter ref="A'.($main?2:1).':'.$last.count($rows).'"/><pageMargins left="0.25" right="0.25" top="0.5" bottom="0.5" header="0.2" footer="0.2"/><pageSetup orientation="landscape" fitToWidth="1" fitToHeight="0"/></worksheet>';}
 private static function styles():string{return'<?xml version="1.0" encoding="UTF-8"?><styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><numFmts count="3"><numFmt numFmtId="164" formatCode="yyyy-mm-dd"/><numFmt numFmtId="165" formatCode="0.00%"/><numFmt numFmtId="166" formatCode="0.00"/></numFmts><fonts count="2"><font><sz val="11"/></font><font><b/><sz val="11"/></font></fonts><fills count="2"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FFD9EAF7"/></patternFill></fill></fills><borders count="1"><border/></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles><cellXfs count="5"><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/><xf numFmtId="164" fontId="0" fillId="0" borderId="0" xfId="0"/><xf numFmtId="165" fontId="0" fillId="0" borderId="0" xfId="0"/><xf numFmtId="166" fontId="0" fillId="0" borderId="0" xfId="0"/><xf numFmtId="0" fontId="1" fillId="1" borderId="0" xfId="0"/></cellXfs></styleSheet>';}
 private static function col(int$n):string{$o='';while($n>0){$n--;$o=chr(65+$n%26).$o;$n=intdiv($n,26);}return$o?:'A';}private static function xml(mixed$v):string{return htmlspecialchars((string)$v,ENT_XML1|ENT_QUOTES,'UTF-8');}private static function types(int$n):string{$x='<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/>';for($i=1;$i<=$n;$i++)$x.='<Override PartName="/xl/worksheets/sheet'.$i.'.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>';return$x.'</Types>';}private static function zip(array$f):string{$b='';$c='';$o=0;foreach($f as$n=>$d){$crc=(int)sprintf('%u',crc32($d));$l=strlen($d);$nl=strlen($n);$local=pack('VvvvvvVVVvv',0x04034b50,20,0,0,0,0,$crc,$l,$l,$nl,0).$n.$d;$b.=$local;$c.=pack('VvvvvvvVVVvvvvvVV',0x02014b50,20,20,0,0,0,0,$crc,$l,$l,$nl,0,0,0,0,0,$o).$n;$o+=strlen($local);}return$b.$c.pack('VvvvvVVv',0x06054b50,0,0,count($f),count($f),strlen($c),strlen($b),0);}
}
