<?php
declare(strict_types=1);
namespace FMonitor2\YiiRuntime\Controllers;

use DomainException;
use FMonitor2\Otiz\{MariaDbOtizSettlementView,ObjectRegister,OtizSettlement};
use Yii;
use yii\filters\{AccessControl,VerbFilter};
use yii\web\{ForbiddenHttpException,NotFoundHttpException,Response};

final class OtizSettlementController extends PilotController
{
 public $layout=false;
 public function behaviors():array{return['verbs'=>['class'=>VerbFilter::class,'actions'=>['index'=>['GET'],'objects'=>['GET'],'payments'=>['GET'],'history'=>['GET'],'snapshot'=>['GET'],'export'=>['GET'],'discipline'=>['POST'],'complete'=>['POST'],'reverse'=>['POST']]],'access'=>['class'=>AccessControl::class,'rules'=>[['allow'=>true,'roles'=>['otiz.manage']]],'denyCallback'=>function():void{if(!Yii::$app->user->isGuest)throw new ForbiddenHttpException();$path=Yii::$app->request->pathInfo;$return=Yii::$app->request->isGet?Yii::$app->request->url:(preg_match('#^pilot/otiz/snapshots/(\d+)/#D',$path,$m)?'/pilot/otiz/snapshots/'.$m[1]:'/pilot/otiz');Yii::$app->user->setReturnUrl($return);Yii::$app->response->statusCode=303;Yii::$app->response->headers->set('Location','/pilot/otiz/login');}]];}
 public function actionIndex():string{return$this->objects();}public function actionObjects():string{return$this->objects();}public function actionPayments():string{return$this->payments();}public function actionHistory():string{return$this->overview('Архив расчётов');}
 public function actionSnapshot(int$id):string{$p=$this->view()->snapshot($id);if($p===false)throw new NotFoundHttpException();$ledger=null;$recovery=Yii::$app->request->get('error')==='closure';if(Yii::$app->request->get('object')!==null&&!$recovery){$object=$this->positiveDecimal(Yii::$app->request->get('object'));$page=$this->positiveDecimal(Yii::$app->request->get('ledgerPage',1));if($object===null||$page===null||($ledger=$this->view()->objectLedgerHistory($id,$object,$page))===false)throw new NotFoundHttpException();}$formState=$recovery?$this->recoveryState($id,$p):null;return$this->render('@app/app/YiiRuntime/Views/otiz-snapshot',['identity'=>Yii::$app->user->identity,'projection'=>$p,'ledger'=>$ledger,'csrf'=>Yii::$app->request->csrfToken,'query'=>Yii::$app->request->get(),'formState'=>$formState]);}
 public function actionDiscipline(int$id):Response{$object=$this->positiveDecimal(Yii::$app->request->post('objectId'));if($object===null)return$this->go($id,'error=closure');$projection=$this->view()->snapshot($id);if($projection===false||!$this->hasObject($projection,$object))throw new NotFoundHttpException();$state=OtizSettlementForm::fromPost($id,$object,Yii::$app->request->post());if($state['errors']!==[]){$this->saveRecovery($state);return$this->go($id,'error=closure&object='.$object);}try{$this->owner()->recordDiscipline($this->actor(),$id,$object,$state['cents'],trim($state['basis']),trim($state['artifact']),$state['operationId']);Yii::$app->session->remove(OtizSettlementForm::FLASH_KEY);return$this->go($id,'closed=1');}catch(DomainException$e){if($e->getMessage()==='NOT_FOUND')throw new NotFoundHttpException();$this->saveRecovery(OtizSettlementForm::domainError($state,$e->getMessage()));return$this->go($id,'error=closure&object='.$object);}}
 public function actionComplete(int$id):Response{try{$r=$this->owner()->completeSnapshotPayments($this->actor(),$id,(string)Yii::$app->request->post('operationId',''));return$this->go($id,$r['status']==='no_change'?'paid=duplicate':'paid=1');}catch(DomainException$e){if($e->getMessage()==='STALE_CALCULATION'){$r=Yii::$app->response;$r->statusCode=409;$r->format=Response::FORMAT_HTML;$r->headers->set('Content-Type','text/html; charset=UTF-8');$r->headers->set('Cache-Control','no-store');$r->content=$this->render('@app/app/YiiRuntime/Views/otiz-settlement-stale',['identity'=>Yii::$app->user->identity,'snapshotId'=>$id]);return$r;}return$this->go($id,'error=payment');}}
 public function actionReverse(int$id):Response{$basis=trim((string)Yii::$app->request->post('basis',''));if($basis===''||mb_strlen($basis)>500)return$this->path('/pilot/otiz?error=reverse-basis');try{$r=$this->owner()->reverse($this->actor(),$id,$basis,(string)Yii::$app->request->post('operationId',''));$snapshot=$this->view()->snapshotForClosure((int)$r['closureId']);if($snapshot===false)throw new \RuntimeException();return$this->go($snapshot,'reversed=1');}catch(DomainException$e){if($e->getMessage()==='NOT_FOUND')throw new NotFoundHttpException();return$this->path('/pilot/otiz?error=reverse-basis');}}
 public function actionExport(int$id):Response{$book=$this->view()->workbook($id);if($book===false)throw new NotFoundHttpException();$r=Yii::$app->response;$r->format=Response::FORMAT_RAW;$r->headers->set('Content-Type','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');$r->headers->set('Content-Disposition','attachment; filename="'.$book['filename'].'"');$r->headers->set('Cache-Control','no-store');$r->content=$book['bytes'];return$r;}
 private function payments():string{return$this->render('@app/app/YiiRuntime/Views/otiz',['identity'=>Yii::$app->user->identity,'mode'=>'payments','title'=>'Выполнение расчёта','date'=>(new \DateTimeImmutable('now',new \DateTimeZone('Europe/Moscow')))->format('Y-m-d'),'snapshots'=>$this->view()->snapshots(),'csrf'=>Yii::$app->request->csrfToken]);}
 private function objects():string{$db=$this->mysqli();$legacy=(string)(getenv('FMONITOR_LEGACY_TABLE_PREFIX')?:$this->prefix());try{$register=(new ObjectRegister($db,$this->prefix(),$legacy))->read($this->actor(),Yii::$app->request->get());}catch(DomainException$e){if($e->getMessage()==='REGISTER_PAGE_NOT_FOUND')throw new NotFoundHttpException();if($e->getMessage()==='REGISTER_FORBIDDEN')throw new ForbiddenHttpException();Yii::$app->response->statusCode=400;return'<!doctype html><html lang="ru"><body><p role="alert">Проверьте параметры реестра.</p></body></html>';}return$this->render('@app/app/YiiRuntime/Views/otiz',['identity'=>Yii::$app->user->identity,'mode'=>'objects','title'=>'Экономика объектов','register'=>$register,'snapshots'=>$this->view()->snapshots(),'hasError'=>Yii::$app->request->get('error')!==null]);}
 private function overview(string$title):string{return$this->render('@app/app/YiiRuntime/Views/otiz',['identity'=>Yii::$app->user->identity,'mode'=>'history','title'=>$title,'snapshots'=>$this->view()->snapshots(),'hasError'=>Yii::$app->request->get('error')!==null]);}
 private function owner():OtizSettlement{return new OtizSettlement(Yii::$app->db,$this->prefix(),static fn():string=>(new \DateTimeImmutable('now',new \DateTimeZone('Europe/Moscow')))->format('Y-m-d\TH:i:sP'));}private function view():MariaDbOtizSettlementView{return new MariaDbOtizSettlementView(Yii::$app->db,$this->prefix());}
 private function actor():int{return(int)Yii::$app->user->id;}private function prefix():string{$p=(string)getenv('FMONITOR_PROCESS_TABLE_PREFIX');if(preg_match('/^[A-Za-z0-9_]{0,25}$/D',$p)!==1)throw new \RuntimeException();return$p;}
 private function mysqli():\mysqli{mysqli_report(MYSQLI_REPORT_ERROR|MYSQLI_REPORT_STRICT);$db=new \mysqli(getenv('FMONITOR_DB_HOST')?:'127.0.0.1',getenv('FMONITOR_DB_USER')?:'',getenv('FMONITOR_DB_PASSWORD')?:'',getenv('FMONITOR_DB_NAME')?:'',(int)(getenv('FMONITOR_DB_PORT')?:3306));$db->set_charset('utf8mb4');return$db;}
 private function hasObject(array$projection,int$objectId):bool{foreach($projection['objects']as$object)if((int)$object['object_id']===$objectId)return true;return false;}
 private function saveRecovery(array$state):void{unset($state['cents']);Yii::$app->session->set(OtizSettlementForm::FLASH_KEY,$state);}
 private function recoveryState(int$snapshotId,array$projection):?array{$state=Yii::$app->session->get(OtizSettlementForm::FLASH_KEY);if(!is_array($state)||(int)($state['snapshotId']??0)!==$snapshotId||!$this->hasObject($projection,(int)($state['objectId']??0)))return null;Yii::$app->session->remove(OtizSettlementForm::FLASH_KEY);return$state;}
 private function positiveDecimal(mixed$value):?int{if((!is_string($value)&&!is_int($value))||preg_match('/^[1-9][0-9]*$/D',(string)$value)!==1)return null;$number=filter_var($value,FILTER_VALIDATE_INT,['options'=>['min_range'=>1]]);return$number===false?null:(int)$number;}
 private function go(int$id,string$q):Response{return$this->path('/pilot/otiz/snapshots/'.$id.'?'.$q);}private function path(string$path):Response{$r=Yii::$app->response;$r->statusCode=303;$r->headers->set('Location',$path);return$r;}
}
