<?php
declare(strict_types=1);
namespace FMonitor2\YiiRuntime\Controllers;
use DomainException;use FMonitor2\Otiz\{MariaDbOtizSettlementV2Access,OtizSettlementV2,OtizSettlementV2DraftBuilder,OtizSettlementV2Workbook};use Yii;use yii\filters\{AccessControl,VerbFilter};use yii\web\{ForbiddenHttpException,NotFoundHttpException,Response};
final class OtizSettlementV2Controller extends PilotController
{
 public $layout=false;public function behaviors():array{return['verbs'=>['class'=>VerbFilter::class,'actions'=>['calculation'=>['GET'],'export'=>['GET'],'create'=>['POST'],'delete'=>['POST'],'refresh'=>['POST'],'cancel'=>['POST'],'replace'=>['POST'],'legacy-payment'=>['POST'],'reverse'=>['POST'],'decision'=>['POST'],'decision-preview'=>['POST'],'deduction'=>['POST'],'deduction-preview'=>['POST'],'deduction-remove'=>['POST'],'accept'=>['POST'],'payment'=>['POST']]],'access'=>['class'=>AccessControl::class,'rules'=>[['allow'=>true,'roles'=>['otiz.manage']]],'denyCallback'=>function():void{if(!Yii::$app->user->isGuest)throw new ForbiddenHttpException();Yii::$app->user->setReturnUrl('/pilot/otiz/payments');Yii::$app->response->statusCode=303;Yii::$app->response->headers->set('Location','/pilot/otiz/login');}]];}
 public function actionCalculation(int$id):string{return$this->renderCalculation($id);}
 public function actionCreate():Response{$date=(string)Yii::$app->request->post('reportDate');$parsed=\DateTimeImmutable::createFromFormat('!Y-m-d',$date);if(!$parsed||$parsed->format('Y-m-d')!==$date)return$this->redirectTo('/pilot/otiz/payments?error=date');try{$input=(new OtizSettlementV2DraftBuilder(Yii::$app->db,$this->prefix(),(string)(getenv('FMONITOR_LEGACY_TABLE_PREFIX')?:$this->prefix())))->build($this->actor(),$date);$result=$this->owner()->createDraft($this->actor(),$input,(string)Yii::$app->request->post('operationId'));return$this->redirectTo('/pilot/otiz/calculations/'.$result['calculationId'].'?created=1');}catch(DomainException$e){if($e->getMessage()==='EMPTY_CALCULATION')return$this->redirectTo('/pilot/otiz/payments?error=empty');throw$e;}}
 public function actionDelete(int$id):Response{return$this->command($id,fn($o,$r,$op)=>$o->deleteDraft($this->actor(),$id,$r,(string)Yii::$app->request->post('reason'),$op),'deleted=1');}
 public function actionRefresh(int$id):Response{$existing=$this->owner()->read($id);$builder=new OtizSettlementV2DraftBuilder(Yii::$app->db,$this->prefix(),(string)(getenv('FMONITOR_LEGACY_TABLE_PREFIX')?:$this->prefix()));$date=(string)Yii::$app->request->post('reportDate');$input=$existing['replacesCalculationId']===null?$builder->build($this->actor(),$date):$builder->buildReplacement($this->actor(),$date,(int)$existing['replacesCalculationId']);return$this->command($id,fn($o,$r,$op)=>$o->refreshDraft($this->actor(),$id,$r,$input,$op),'refreshed=1');}
 public function actionCancel(int$id):Response{return$this->command($id,fn($o,$r,$op)=>$o->cancel($this->actor(),$id,$r,(string)Yii::$app->request->post('reason'),$op),'cancelled=1');}
 public function actionReplace(int$id):Response{$input=(new OtizSettlementV2DraftBuilder(Yii::$app->db,$this->prefix(),(string)(getenv('FMONITOR_LEGACY_TABLE_PREFIX')?:$this->prefix())))->buildReplacement($this->actor(),(string)Yii::$app->request->post('reportDate'),$id);try{$candidate=$this->owner()->createReplacementDraft($this->actor(),$id,(int)Yii::$app->request->post('expectedRevision'),$input,(string)Yii::$app->request->post('reason'),(string)Yii::$app->request->post('operationId'));return$this->redirectTo('/pilot/otiz/calculations/'.$candidate['calculationId'].'?replacement=1');}catch(DomainException$e){$r=Yii::$app->response;$r->statusCode=409;$r->content=$e->getMessage();return$r;}}
 public function actionReverse(int$id):Response{$calculation=(new MariaDbOtizSettlementV2Access(Yii::$app->db,$this->prefix()))->calculationForPayment($id);if($calculation<1)throw new NotFoundHttpException();$this->owner()->reversePayment($this->actor(),$id,(string)Yii::$app->request->post('reason'),(string)Yii::$app->request->post('operationId'),(string)Yii::$app->request->post('kind','financial'));return$this->redirectTo('/pilot/otiz/calculations/'.$calculation.'?reversed=1');}
 public function actionLegacyPayment(int$id):Response{$r=Yii::$app->response;$r->statusCode=409;$r->content='<main><p role="alert">LEGACY_PAYMENT_ROUTE_RETIRED. Требуется новый расчёт.</p></main>';return$r;}
 public function actionDecision(int$id):Response{return$this->command($id,fn($o,$r,$op)=>$o->saveDecision($this->actor(),$id,$r,(string)Yii::$app->request->post('employeeId'),(string)Yii::$app->request->post('decision'),(string)Yii::$app->request->post('reason'),$op));}
 public function actionDeduction(int$id):Response{return$this->command($id,function($o,$r,$op)use($id){try{$amount=\FMonitor\Otiz\OtizSettlementV2Math::parseRubles((string)Yii::$app->request->post('amount'));}catch(\InvalidArgumentException){throw new DomainException('INVALID_MONEY');}return$o->saveDeduction($this->actor(),$id,$r,(int)Yii::$app->request->post('objectId'),Yii::$app->request->post('employeeId')!==null&&Yii::$app->request->post('employeeId')!==''?(string)Yii::$app->request->post('employeeId'):null,$amount,(string)Yii::$app->request->post('reason'),(string)Yii::$app->request->post('document',''),$op);});}
 public function actionDecisionPreview(int$id):Response{return$this->preview($id,'decision',fn($o,$r)=>$o->previewDecision($this->actor(),$id,$r,(string)Yii::$app->request->post('employeeId'),(string)Yii::$app->request->post('decision'),(string)Yii::$app->request->post('reason')));}
 public function actionDeductionPreview(int$id):Response{return$this->preview($id,'deduction',function($o,$r)use($id){try{$amount=\FMonitor\Otiz\OtizSettlementV2Math::parseRubles((string)Yii::$app->request->post('amount'));}catch(\InvalidArgumentException){throw new DomainException('INVALID_MONEY');}return$o->previewDeduction($this->actor(),$id,$r,(int)Yii::$app->request->post('objectId'),Yii::$app->request->post('employeeId')!==null&&Yii::$app->request->post('employeeId')!==''?(string)Yii::$app->request->post('employeeId'):null,$amount,(string)Yii::$app->request->post('reason'),(string)Yii::$app->request->post('document',''));});}
 public function actionDeductionRemove(int$id,int$deductionId):Response{return$this->command($id,fn($o,$r,$op)=>$o->removeDeduction($this->actor(),$id,$r,$deductionId,(string)Yii::$app->request->post('reason'),$op));}
 public function actionAccept(int$id):Response{return$this->command($id,fn($o,$r,$op)=>$o->accept($this->actor(),$id,$r,$op));}public function actionPayment(int$id):Response{return$this->command($id,fn($o,$r,$op)=>$o->markPaid($this->actor(),$id,$r,(string)Yii::$app->request->post('paymentDate'),$op),'paid=1');}
 public function actionExport(int$id):Response{try{$owner=$this->owner();$s=$owner->read($id);$mode=(string)Yii::$app->request->get('mode','history');if($mode==='payment')$owner->assertPaymentExportAllowed($this->actor(),$id);}catch(DomainException$e){if($e->getMessage()==='NOT_FOUND')throw new NotFoundHttpException();$r=Yii::$app->response;$r->statusCode=409;return$r;}$book=OtizSettlementV2Workbook::build(['calculation'=>['id'=>$s['calculationId'],'status'=>$s['status'],'reportDate'=>$s['reportDate'],'revision'=>$s['revision'],'rulesVersion'=>'otiz-v2','totalCents'=>$s['totalCents'],'contentHash'=>$s['contentHash'],'acceptedAt'=>$s['acceptedAt'],'acceptedBy'=>$s['acceptedBy']],'objects'=>$s['objects'],'recipients'=>$s['recipients'],'deductions'=>$s['deductions'],'decisions'=>$s['decisions'],'issues'=>$this->issues($s),'mode'=>$mode,'exportedAt'=>(new \DateTimeImmutable())->format(DATE_ATOM)]);$r=Yii::$app->response;$r->format=Response::FORMAT_RAW;$r->headers->set('Content-Type','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');$r->headers->set('Content-Disposition','attachment; filename="'.$book['filename'].'"');$r->content=$book['bytes'];return$r;}
 private function command(int$id,callable$f,string$q='saved=1'):Response{try{$f($this->owner(),(int)Yii::$app->request->post('expectedRevision'),(string)Yii::$app->request->post('operationId'));$r=Yii::$app->response;$r->statusCode=303;$r->headers->set('Location','/pilot/otiz/calculations/'.$id.'?'.$q);return$r;}catch(DomainException$e){if($e->getMessage()==='NOT_FOUND')throw new NotFoundHttpException();$r=Yii::$app->response;$r->format=Response::FORMAT_HTML;$r->statusCode=in_array($e->getMessage(),['STALE_REVISION','STALE_CALCULATION','COMPOSITION_MISMATCH','ADMISSION_UNKNOWN','SNAPSHOT_REPLACEMENT_REQUIRED'],true)?409:422;$r->headers->set('Cache-Control','no-store');$message=match($e->getMessage()){'STALE_REVISION','STALE_CALCULATION'=>'Расчёт изменился. Обновите страницу, проверьте суммы и повторите действие.','REASON_REQUIRED'=>'Укажите причину',default=>$e->getMessage()};$r->content=$this->renderCalculation($id,['error'=>$message,'post'=>Yii::$app->request->post()]);return$r;}}
 private function preview(int$id,string$kind,callable$f):Response{$owner=$this->owner();try{$before=$owner->read($id);$after=$f($owner,(int)Yii::$app->request->post('expectedRevision'));$rows=[];$prior=[];foreach($before['recipients']as$r)$prior[(string)$r['objectId'].'|'.(string)$r['employeeId']]=$r;foreach($after['recipients']as$r){$key=(string)$r['objectId'].'|'.(string)$r['employeeId'];$old=$prior[$key]??$r;$rows[]=['objectId'=>(int)$r['objectId'],'employeeId'=>(string)$r['employeeId'],'regnumber'=>$this->regnumber($after,(int)$r['objectId']),'name'=>(string)$r['name'],'beforeCents'=>(int)$old['amountCents'],'afterCents'=>(int)$r['amountCents']];}$html=$this->renderCalculation($id,['post'=>Yii::$app->request->post()],$before,['kind'=>$kind,'totalCents'=>(int)$after['totalCents'],'rows'=>$rows]);$response=Yii::$app->response;$response->format=Response::FORMAT_HTML;$response->headers->set('Cache-Control','no-store');$response->content=$html;return$response;}catch(DomainException$e){$response=Yii::$app->response;$response->format=Response::FORMAT_HTML;$response->statusCode=$e->getMessage()==='STALE_REVISION'?409:422;$response->headers->set('Cache-Control','no-store');$response->content=$this->renderCalculation($id,['error'=>$e->getMessage(),'post'=>Yii::$app->request->post()]);return$response;}}
 private function renderCalculation(int$id,?array$recovery=null,?array$calculation=null,?array$preview=null):string{try{$c=$calculation??$this->owner()->read($id);}catch(DomainException){throw new NotFoundHttpException();}if($c['status']==='accepted')foreach($c['objects']as$o){$a=$this->admission((int)$o['objectId']);if(($a['decision']??'unknown')!=='allow'){$c['blockedReason']=$this->reason((string)($a['reasonCode']??'ADMISSION_UNKNOWN'));break;}}$grouping=$this->grouping($c,Yii::$app->request->get());return$this->render('@app/app/YiiRuntime/Views/otiz-calculation-v2',['identity'=>Yii::$app->user->identity,'calculation'=>$c,'csrf'=>Yii::$app->request->csrfToken,'queryParams'=>Yii::$app->request->get(),'recovery'=>$recovery,'preview'=>$preview,'grouping'=>$grouping]);}
 private function grouping(array$c,array$raw):array{$group=in_array(($raw['group']??'objects'),['objects','employees'],true)?(string)($raw['group']??'objects'):'objects';$q=is_string($raw['q']??'')?trim((string)($raw['q']??'')):'';if(mb_strlen($q)>120)$q=mb_substr($q,0,120);$sort=in_array(($raw['sort']??'amount_desc'),['amount_asc','amount_desc'],true)?(string)($raw['sort']??'amount_desc'):'amount_desc';$pageSize=in_array((int)($raw['pageSize']??25),[1,25,50],true)?(int)($raw['pageSize']??25):25;$page=max(1,(int)($raw['page']??1));$objects=[];foreach($c['objects']as$o)$objects[(string)$o['objectId']]=['parent'=>$o,'children'=>[],'subtotalCents'=>0];$employees=[];foreach($c['recipients']as$r){$ok=(string)$r['objectId'];if(isset($objects[$ok])){$objects[$ok]['children'][]=$r;$objects[$ok]['subtotalCents']+=(int)$r['amountCents'];}$ek=(string)$r['employeeId'];$employees[$ek]??=['parent'=>$r,'children'=>[],'subtotalCents'=>0];$employees[$ek]['children'][]=$r;$employees[$ek]['subtotalCents']+=(int)$r['amountCents'];}$filter=static function(array$rows)use($q):array{if($q==='')return array_values($rows);$needle=mb_strtolower($q);return array_values(array_filter($rows,static function(array$e)use($needle):bool{$hay=json_encode([$e['parent'],$e['children']],JSON_UNESCAPED_UNICODE);return str_contains(mb_strtolower((string)$hay),$needle);}));};$sorter=static function(array&$rows)use($sort):void{usort($rows,static fn($a,$b)=>($sort==='amount_desc'?-1:1)*(($a['subtotalCents']<=>$b['subtotalCents'])?:strcmp((string)($a['parent']['regnumber']??$a['parent']['name']),(string)($b['parent']['regnumber']??$b['parent']['name']))));};$build=static function(array$rows)use($filter,$sorter,$page,$pageSize):array{$rows=$filter($rows);$sorter($rows);$total=count($rows);$pages=max(1,(int)ceil($total/$pageSize));$actual=min($page,$pages);return['rows'=>array_slice($rows,($actual-1)*$pageSize,$pageSize),'page'=>$actual,'pages'=>$pages,'total'=>$total];};return['query'=>compact('group','q','sort','pageSize'),'objects'=>$build($objects),'employees'=>$build($employees)];}
 private function regnumber(array$c,int$id):string{foreach($c['objects']as$o)if((int)$o['objectId']===$id)return(string)$o['regnumber'];return(string)$id;}
 private function issues(array$s):array{$issues=[];foreach($s['objects']??[]as$o)foreach($o['issues']??[]as$i)$issues[]=$i+['objectId'=>(int)$o['objectId'],'regnumber'=>(string)$o['regnumber'],'message'=>(string)$o['regnumber'].': '.(string)($i['message']??$i['code']??'')];foreach($s['excludedObjects']??[]as$i)$issues[]=$i+['message'=>'Объект '.(string)($i['objectId']??'').': '.(string)($i['message']??$i['reasonCode']??'')];return$issues;}
 private function reason(string$code):string{return match($code){'COMPOSITION_MISMATCH'=>'Несоответствие состава','PRODUCER_UNKNOWN','ADMISSION_UNKNOWN'=>'Основание выплаты не подтверждено',default=>$code};}
 private function owner():OtizSettlementV2{return new OtizSettlementV2(Yii::$app->db,$this->prefix(),static fn()=>(new \DateTimeImmutable('now',new \DateTimeZone('Europe/Moscow')))->format(DATE_ATOM),fn(int$o,string$p)=>$this->admission($o),(string)(getenv('FMONITOR_LEGACY_TABLE_PREFIX')?:$this->prefix()));}private function admission(int$o):array{return(new MariaDbOtizSettlementV2Access(Yii::$app->db,$this->prefix()))->admission($o);}private function admissionFor(array$c):string{foreach($c['objects']as$o)if(($this->admission((int)$o['objectId'])['decision']??'unknown')!=='allow')return'blocked';return'allow';}private function redirectTo(string$path):Response{$r=Yii::$app->response;$r->statusCode=303;$r->headers->set('Location',$path);return$r;}private function actor():int{return(int)Yii::$app->user->id;}private function prefix():string{return(string)getenv('FMONITOR_PROCESS_TABLE_PREFIX');}
}
