<?php
declare(strict_types=1);
namespace FMonitor2\YiiRuntime\Controllers;
use DomainException;use FMonitor2\Otiz\MariaDbOtizSettlementView;use FMonitor2\Otiz\OtizSettlement;use Yii;use yii\filters\AccessControl;use yii\filters\VerbFilter;use yii\web\ForbiddenHttpException;use yii\web\NotFoundHttpException;use yii\web\Response;
final class OtizSettlementController extends PilotController
{
 public $layout=false;
 public function behaviors():array{return['verbs'=>['class'=>VerbFilter::class,'actions'=>['index'=>['GET'],'objects'=>['GET'],'payments'=>['GET'],'history'=>['GET'],'snapshot'=>['GET'],'export'=>['GET'],'discipline'=>['POST'],'complete'=>['POST'],'reverse'=>['POST']]],'access'=>['class'=>AccessControl::class,'rules'=>[['allow'=>true,'roles'=>['otiz.manage']]],'denyCallback'=>function():void{if(Yii::$app->user->isGuest){Yii::$app->user->setReturnUrl(Yii::$app->request->url);Yii::$app->response->statusCode=303;Yii::$app->response->headers->set('Location','/pilot/login');}else throw new ForbiddenHttpException();}]];}
 public function actionIndex():string{return$this->overview('Расчёты ОТиЗ');}public function actionObjects():string{return$this->overview('Экономика объектов');}public function actionPayments():string{return$this->overview('Подготовка выплат');}public function actionHistory():string{return$this->overview('Архив расчётов');}
 public function actionSnapshot(int$id):string
 {
  $projection=$this->view()->snapshot($id);if($projection===false)throw new NotFoundHttpException();return$this->renderSnapshot($projection);
 }
 public function actionDiscipline(int$id):Response
 {
  $object=filter_var(Yii::$app->request->post('objectId'),FILTER_VALIDATE_INT,['options'=>['min_range'=>1]]);$cents=$this->money(Yii::$app->request->post('discipline'));$basis=trim((string)Yii::$app->request->post('basis',''));$artifact=trim((string)Yii::$app->request->post('artifact',''));$operation=(string)Yii::$app->request->post('operationId','');if($object===false||$cents===null||$basis===''||mb_strlen($basis)>500||mb_strlen($artifact)>300)return$this->go($id,'error=closure');try{$this->owner()->recordDiscipline($this->actor(),$id,(int)$object,$cents,$basis,$artifact,$operation);return$this->go($id,'closed=1');}catch(DomainException){return$this->go($id,'error=closure');}
 }
 public function actionComplete(int$id):Response{try{$r=$this->owner()->completeSnapshotPayments($this->actor(),$id,(string)Yii::$app->request->post('operationId',''));return$this->go($id,$r['status']==='no_change'?'paid=duplicate':'paid=1');}catch(DomainException){return$this->go($id,'error=payment');}}
 public function actionReverse(int$id):Response{$basis=trim((string)Yii::$app->request->post('basis',''));if($basis===''||mb_strlen($basis)>500)return$this->path('/pilot/otiz?error=reverse-basis');try{$r=$this->owner()->reverse($this->actor(),$id,$basis,(string)Yii::$app->request->post('operationId',''));$snapshot=$this->view()->snapshotForClosure((int)$r['closureId']);if($snapshot===false)throw new \RuntimeException();return$this->go($snapshot,'reversed=1');}catch(DomainException$e){if($e->getMessage()==='NOT_FOUND')throw new NotFoundHttpException();return$this->path('/pilot/otiz?error=reverse-basis');}}
 public function actionExport(int$id):Response{$book=$this->view()->workbook($id);if($book===false)throw new NotFoundHttpException();$r=Yii::$app->response;$r->format=Response::FORMAT_RAW;$r->headers->set('Content-Type','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');$r->headers->set('Content-Disposition','attachment; filename="'.$book['filename'].'"');$r->headers->set('Cache-Control','no-store');$r->content=$book['bytes'];return$r;}
 private function overview(string$title):string{$rows=$this->view()->snapshots();$body='<!doctype html><html lang="ru"><head><meta charset="utf-8"><title>'.$this->e($title).'</title></head><body><nav><a href="/pilot/otiz/objects">Экономика объектов</a><a href="/pilot/otiz/payments">Подготовка выплат</a><a href="/pilot/otiz/history">Архив расчётов</a></nav><h1>'.$this->e($title).'</h1>'.(isset($_GET['error'])?'<p role="alert">Действие не выполнено.</p>':'').'<ul>';foreach($rows as$row)$body.='<li><a href="/pilot/otiz/snapshots/'.(int)$row['id'].'">Расчёт на '.$this->date((string)$row['report_date']).'</a> · '.$this->rub((int)$row['total_pool_cents']).'</li>';return$body.'</ul></body></html>';}
 private function renderSnapshot(array$p):string
 {
  $s=$p['snapshot'];$id=(int)$s['id'];$csrf=$this->e(Yii::$app->request->csrfToken);$flash=isset($_GET['closed'])?'Удержание добавлено к выплате по объекту.':(isset($_GET['reversed'])?'Предыдущая отметка о выплате отменена.':(($_GET['paid']??'')==='1'?'Выплаты отмечены выполненными и учтены по объектам.':(($_GET['paid']??'')==='duplicate'?'Эти выплаты уже были отмечены выполненными.':(isset($_GET['error'])?'Действие не выполнено. Устраните замечания по объектам и проверьте доступную сумму.':''))));
  $total=0;foreach($p['objects']as$o)if($o['calculation_state']!=='blocked')$total+=max(0,(int)$o['accrued_cents']-(int)$o['global_closed_cents']);$role=isset($_GET['error'])?'alert':'status';$body='<!doctype html><html lang="ru"><head><meta charset="utf-8"><title>Выплаты на '.$this->date((string)$s['report_date']).'</title></head><body><nav><a href="/pilot/otiz/objects">Экономика объектов</a><a href="/pilot/otiz/payments">Подготовка выплат</a><a href="/pilot/otiz/history">Архив расчётов</a></nav><h1>Выплаты на '.$this->date((string)$s['report_date']).'</h1><span>'.($s['status']==='accepted'?'Готовы к выплате':'На проверке').'</span>'.($flash!==''?'<p role="'.$role.'">'.$this->e($flash).'</p>':'').'<a href="/pilot/otiz/snapshots/'.$id.'/export.xlsx">Скачать реестр XLSX</a><section class="fm2-otiz-summary">К выплате '.$this->rub($total).'</section>';
  foreach($p['objects']as$o){$available=max(0,(int)$o['accrued_cents']-(int)$o['global_closed_cents']);$body.='<section class="fm2-otiz-object-row"><h2>'.$this->e((string)$o['regnumber']).'</h2><p>'.$this->e((string)$o['address']).'</p><p>Начислено: '.$this->rub((int)$o['accrued_cents']).'</p><p>Доступно: '.$this->rub($available).'</p>'.$this->trace($o).$this->allocations($o).$this->issues($o);if($s['status']==='accepted'&&$o['calculation_state']!=='blocked'&&$available>0)$body.='<details><summary>Добавить дисциплинарное удержание</summary><form method="post" action="/pilot/otiz/snapshots/'.$id.'/closures"><input type="hidden" name="_csrf" value="'.$csrf.'"><input type="hidden" name="operationId" value="'.$this->uuid().'"><input type="hidden" name="objectId" value="'.(int)$o['object_id'].'"><input name="discipline"><input name="basis"><input name="artifact"><button type="submit">Добавить удержание</button></form></details>';elseif($o['calculation_state']==='blocked')$body.='<p>Требует данных</p>';else$body.='<p>Выплата по объекту выполнена.</p>';$body.='</section>';}
  if($s['status']==='accepted'&&$total>0)$body.='<form method="post" action="/pilot/otiz/snapshots/'.$id.'/payments/complete"><input type="hidden" name="_csrf" value="'.$csrf.'"><input type="hidden" name="operationId" value="'.$this->uuid().'"><button type="submit">Отметить выплаты выполненными</button></form>';
  if($p['closures']!==[])$body.='<section class="fm2-otiz-ledger"><h2>Выполненные выплаты и удержания</h2><table><thead><tr><th>Дата</th><th>Объект</th><th>Выплачено</th><th>Удержано по дисциплине</th><th>Удержано за сроки</th><th>Основание</th><th></th></tr></thead><tbody>';foreach($p['closures']as$c){$reversal=(int)($c['reverses_payment_closure_id']??0)>0;$body.='<tr><td>'.$this->date((string)$c['closed_on']).'</td><td>'.$this->e((string)$c['regnumber']).'</td><td>'.$this->rub((int)$c['paid_cents']).'</td><td>'.$this->rub((int)$c['discipline_cents']).'</td><td>'.$this->rub((int)$c['deadline_cents']).'</td><td>'.$this->e((string)$c['basis']).($reversal?' Сторно записи № '.(int)$c['reverses_payment_closure_id']:'').'</td><td>';if(!$reversal)$body.='<form method="post" action="/pilot/otiz/closures/'.(int)$c['id'].'/reverse"><input type="hidden" name="_csrf" value="'.$csrf.'"><input type="hidden" name="operationId" value="'.$this->uuid().'"><input name="basis" aria-label="Основание сторно"><button type="submit">Сторнировать</button></form>';$body.='</td></tr>';}if($p['closures']!==[])$body.='</tbody></table></section>';return$body.'</body></html>';
 }
 private function trace(array$o):string{$inputs=json_decode((string)$o['inputs_json'],true);$calculation=$inputs['premiumCalculation']??null;$trace=is_array($calculation)?($calculation['formulaTrace']??[]):[];if(!is_array($trace)||$trace===[])return'';$labels=['fund'=>'Премиальный фонд','progress'=>'Начислено за прогресс','deadline'=>'С учётом сроков','closed'=>'Выплачено ранее','pool'=>'К выплате'];$exclusions=$calculation['exclusions']??[];$h='<details class="fm2-otiz-trace"><summary>Как рассчитана сумма</summary><p>'.$this->e($exclusions===[]?'Расчёт допущен к распределению.':'Исключено: '.implode(', ',array_column($exclusions,'code'))).'</p><ol>';foreach($trace as$step){$key=(string)($step['step']??'');$value=isset($step['resultCents'])?$this->rub((int)$step['resultCents']):number_format((int)($step['resultBp']??0)/100,0,',',' ').'%';$h.='<li>'.$this->e($labels[$key]??'Этап расчёта').': '.$value.'</li>';}return$h.'</ol></details>';}
 private function allocations(array$o):string{$h='<div class="fm2-otiz-allocation"><h3>Начисления работникам</h3>';foreach($o['allocations']as$a){$ktu=(int)($a['effective_ktu_bp']??0);if((int)($a['base_ktu_bp']??0)===(int)($a['contribution_bp']??0)&&$ktu===(int)($a['contribution_bp']??0)&&str_contains((string)($a['participation_basis']??''),'коэффициент 1,00'))$ktu=10000;$h.='<p>'.$this->e((string)$a['full_name']).' · таб. '.$this->e((string)$a['tab_id']).' · КТУ '.number_format($ktu/10000,2,',',' ').' · '.$this->rub((int)$a['amount_cents']).'</p>';}return$h.'</div>';}
 private function issues(array$o):string{$h='<div class="fm2-otiz-issues">';foreach($o['issues']as$i)$h.='<p>'.($i['severity']==='blocker'?'Нужно исправить':'Обратите внимание').': '.$this->e((string)$i['message']).' · '.$this->e((string)$i['owner_role']).'</p>';return$h.'</div>';}
 private function e(string$v):string{return htmlspecialchars($v,ENT_QUOTES|ENT_HTML5,'UTF-8');}private function rub(int$c):string{return($c<0?'−':'').number_format(abs($c)/100,2,',',' ').' ₽';}private function date(string$v):string{return preg_match('/^(\d{4})-(\d{2})-(\d{2})/D',$v,$m)?$m[3].'.'.$m[2].'.'.$m[1]:$this->e($v);}
 private function owner():OtizSettlement{return new OtizSettlement(Yii::$app->db,$this->prefix(),static fn():string=>(new \DateTimeImmutable('now',new \DateTimeZone('Europe/Moscow')))->format('Y-m-d\TH:i:sP'));}private function view():MariaDbOtizSettlementView{return new MariaDbOtizSettlementView(Yii::$app->db,$this->prefix());}
 private function actor():int{return(int)Yii::$app->user->id;}private function prefix():string{$p=(string)getenv('FMONITOR_PROCESS_TABLE_PREFIX');if(preg_match('/^[A-Za-z0-9_]{0,25}$/D',$p)!==1)throw new \RuntimeException();return$p;}
 private function money(mixed$v):?int{if(!is_string($v)||preg_match('/^(0|[1-9][0-9]{0,9})\.([0-9]{2})$/D',$v,$m)!==1)return null;$c=(int)$m[1]*100+(int)$m[2];return$c>0?$c:null;}
 private function go(int$id,string$q):Response{return$this->path('/pilot/otiz/snapshots/'.$id.'?'.$q);}private function path(string$path):Response{$r=Yii::$app->response;$r->statusCode=303;$r->headers->set('Location',$path);return$r;}private function uuid():string{$b=random_bytes(16);$b[6]=chr((ord($b[6])&15)|64);$b[8]=chr((ord($b[8])&63)|128);return vsprintf('%s%s-%s-%s-%s-%s%s%s',str_split(bin2hex($b),4));}
}
