<?php
declare(strict_types=1);
namespace FMonitor2\YiiRuntime\Controllers;

use DomainException;
use FMonitor2\Otiz\{MariaDbOtizSettlementView,ObjectRegister,OtizSettlement};
use Yii;
use yii\filters\{AccessControl,VerbFilter};
use yii\web\{ForbiddenHttpException,NotFoundHttpException,Response};

final class OtizSettlementController extends PilotController
{
 public $layout=false;
 public function behaviors():array{return['verbs'=>['class'=>VerbFilter::class,'actions'=>['index'=>['GET'],'objects'=>['GET'],'payments'=>['GET'],'history'=>['GET'],'snapshot'=>['GET'],'export'=>['GET'],'discipline'=>['POST'],'complete'=>['POST'],'reverse'=>['POST']]],'access'=>['class'=>AccessControl::class,'rules'=>[['allow'=>true,'roles'=>['otiz.manage']]],'denyCallback'=>function():void{if(!Yii::$app->user->isGuest)throw new ForbiddenHttpException();$path=Yii::$app->request->pathInfo;$return=Yii::$app->request->isGet?Yii::$app->request->url:(preg_match('#^pilot/otiz/snapshots/(\d+)/#D',$path,$m)?'/pilot/otiz/snapshots/'.$m[1]:'/pilot/otiz');Yii::$app->user->setReturnUrl($return);Yii::$app->response->statusCode=303;Yii::$app->response->headers->set('Location','/pilot/otiz/login');}]];}
 public function actionIndex():string{return$this->objects();}public function actionObjects():string{return$this->objects();}public function actionPayments():string{return$this->payments();}public function actionHistory():string{return$this->overview('Архив расчётов');}
 public function actionSnapshot(int$id):string{$p=$this->view()->snapshot($id);if($p===false)throw new NotFoundHttpException();return$this->render('@app/app/YiiRuntime/Views/otiz-snapshot',['identity'=>Yii::$app->user->identity,'projection'=>$p,'csrf'=>Yii::$app->request->csrfToken,'query'=>Yii::$app->request->get()]);}
 public function actionDiscipline(int$id):Response{$object=filter_var(Yii::$app->request->post('objectId'),FILTER_VALIDATE_INT,['options'=>['min_range'=>1]]);$cents=$this->money(Yii::$app->request->post('discipline'));$basis=trim((string)Yii::$app->request->post('basis',''));$artifact=trim((string)Yii::$app->request->post('artifact',''));$operation=(string)Yii::$app->request->post('operationId','');if($object===false||$cents===null||$basis===''||mb_strlen($basis)>500||mb_strlen($artifact)>300)return$this->go($id,'error=closure');try{$this->owner()->recordDiscipline($this->actor(),$id,(int)$object,$cents,$basis,$artifact,$operation);return$this->go($id,'closed=1');}catch(DomainException){return$this->go($id,'error=closure');}}
 public function actionComplete(int$id):Response{try{$r=$this->owner()->completeSnapshotPayments($this->actor(),$id,(string)Yii::$app->request->post('operationId',''));return$this->go($id,$r['status']==='no_change'?'paid=duplicate':'paid=1');}catch(DomainException$e){if($e->getMessage()==='STALE_CALCULATION'){Yii::$app->response->statusCode=409;Yii::$app->response->content='Требуется новый расчёт.';return Yii::$app->response;}return$this->go($id,'error=payment');}}
 public function actionReverse(int$id):Response{$basis=trim((string)Yii::$app->request->post('basis',''));if($basis===''||mb_strlen($basis)>500)return$this->path('/pilot/otiz?error=reverse-basis');try{$r=$this->owner()->reverse($this->actor(),$id,$basis,(string)Yii::$app->request->post('operationId',''));$snapshot=$this->view()->snapshotForClosure((int)$r['closureId']);if($snapshot===false)throw new \RuntimeException();return$this->go($snapshot,'reversed=1');}catch(DomainException$e){if($e->getMessage()==='NOT_FOUND')throw new NotFoundHttpException();return$this->path('/pilot/otiz?error=reverse-basis');}}
 public function actionExport(int$id):Response{$book=$this->view()->workbook($id);if($book===false)throw new NotFoundHttpException();$r=Yii::$app->response;$r->format=Response::FORMAT_RAW;$r->headers->set('Content-Type','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');$r->headers->set('Content-Disposition','attachment; filename="'.$book['filename'].'"');$r->headers->set('Cache-Control','no-store');$r->content=$book['bytes'];return$r;}
 private function payments():string{return$this->render('@app/app/YiiRuntime/Views/otiz',['identity'=>Yii::$app->user->identity,'mode'=>'payments','title'=>'Выполнение расчёта','date'=>(new \DateTimeImmutable('now',new \DateTimeZone('Europe/Moscow')))->format('Y-m-d'),'snapshots'=>$this->view()->snapshots(),'csrf'=>Yii::$app->request->csrfToken]);}
 private function objects():string{$db=$this->mysqli();$legacy=(string)(getenv('FMONITOR_LEGACY_TABLE_PREFIX')?:$this->prefix());try{$register=(new ObjectRegister($db,$this->prefix(),$legacy))->read($this->actor(),Yii::$app->request->get());}catch(DomainException$e){if($e->getMessage()==='REGISTER_PAGE_NOT_FOUND')throw new NotFoundHttpException();if($e->getMessage()==='REGISTER_FORBIDDEN')throw new ForbiddenHttpException();Yii::$app->response->statusCode=400;return'<!doctype html><html lang="ru"><body><p role="alert">Проверьте параметры реестра.</p></body></html>';}return$this->render('@app/app/YiiRuntime/Views/otiz',['identity'=>Yii::$app->user->identity,'mode'=>'objects','title'=>'Экономика объектов','register'=>$register,'snapshots'=>$this->view()->snapshots(),'hasError'=>Yii::$app->request->get('error')!==null]);}
 private function overview(string$title):string{return$this->render('@app/app/YiiRuntime/Views/otiz',['identity'=>Yii::$app->user->identity,'mode'=>'history','title'=>$title,'snapshots'=>$this->view()->snapshots(),'hasError'=>Yii::$app->request->get('error')!==null]);}
 private function owner():OtizSettlement{return new OtizSettlement(Yii::$app->db,$this->prefix(),static fn():string=>(new \DateTimeImmutable('now',new \DateTimeZone('Europe/Moscow')))->format('Y-m-d\TH:i:sP'));}private function view():MariaDbOtizSettlementView{return new MariaDbOtizSettlementView(Yii::$app->db,$this->prefix());}
 private function actor():int{return(int)Yii::$app->user->id;}private function prefix():string{$p=(string)getenv('FMONITOR_PROCESS_TABLE_PREFIX');if(preg_match('/^[A-Za-z0-9_]{0,25}$/D',$p)!==1)throw new \RuntimeException();return$p;}
 private function mysqli():\mysqli{mysqli_report(MYSQLI_REPORT_ERROR|MYSQLI_REPORT_STRICT);$db=new \mysqli(getenv('FMONITOR_DB_HOST')?:'127.0.0.1',getenv('FMONITOR_DB_USER')?:'',getenv('FMONITOR_DB_PASSWORD')?:'',getenv('FMONITOR_DB_NAME')?:'',(int)(getenv('FMONITOR_DB_PORT')?:3306));$db->set_charset('utf8mb4');return$db;}
 private function money(mixed$v):?int{if(!is_string($v)||preg_match('/^(0|[1-9][0-9]{0,9})\.([0-9]{2})$/D',$v,$m)!==1)return null;$c=(int)$m[1]*100+(int)$m[2];return$c>0?$c:null;}
 private function go(int$id,string$q):Response{return$this->path('/pilot/otiz/snapshots/'.$id.'?'.$q);}private function path(string$path):Response{$r=Yii::$app->response;$r->statusCode=303;$r->headers->set('Location',$path);return$r;}
}
