<?php declare(strict_types=1);
use yii\helpers\Html;
$object=$ledger['object'];$totals=$ledger['totals'];$objectId=(int)$object['object_id'];$page=(int)$ledger['page'];$pages=max(1,(int)ceil((int)$ledger['total']/(int)$ledger['page_size']));
?>
<section class="fm2-otiz-surface fm2-otiz-ledger" data-otiz-object-ledger-history>
<h2>Все выплаты и удержания по объекту</h2>
<p><strong><?=Html::encode((string)$object['regnumber'])?></strong> · <?=Html::encode((string)$object['address'])?></p>
<dl class="fm2-otiz-facts"><div><dt>Сохранено в расчёте #<?=$snapshotId?></dt><dd><?=$rub((int)$object['closed_before_cents'])?></dd></div><div><dt>Выплачено сейчас</dt><dd><?=$rub((int)$totals['paid_cents'])?></dd></div><div><dt>Удержано по дисциплине сейчас</dt><dd><?=$rub((int)$totals['discipline_cents'])?></dd></div><div><dt>Удержано за сроки сейчас</dt><dd><?=$rub((int)$totals['deadline_cents'])?></dd></div><div><dt>Итого учтено сейчас</dt><dd><?=$rub((int)$totals['global_closed_cents'])?></dd></div></dl>
<h3>Учтено сейчас по всем расчётам</h3><p>История включает более поздние записи и не восстанавливает состояние ledger на расчётную дату. Всего <?=$ledger['total']?> <?=((int)$ledger['total']===1)?'запись':(((int)$ledger['total']>=2&&(int)$ledger['total']<=4)?'записи':'записей')?>.</p>
<?php if(!$ledger['rows']):?><p>Выплат и удержаний пока нет.</p><?php else:?>
<div class="shlz-table-wrap" data-mobile-strategy="contained-scroll" tabindex="0" aria-label="Все выплаты и удержания по объекту"><table class="shlz-table"><thead class="shlz-table__head"><tr class="shlz-table__row"><?php foreach(['Тип','Дата','Выплачено','Удержано по дисциплине','Удержано за сроки','Основание','Исходный расчёт']as$heading):?><th class="shlz-table__cell" scope="col"><?=$heading?></th><?php endforeach?></tr></thead><tbody>
<?php foreach($ledger['rows']as$row):$kind=['reversal'=>'Сторно','payment'=>'Выплата','deduction'=>'Удержание'][(string)$row['presentation_kind']];?>
<tr id="closure-<?=(int)$row['id']?>" class="shlz-table__row" data-otiz-object-ledger-row data-closure-id="<?=(int)$row['id']?>"><td class="shlz-table__cell" data-ledger-field="type"><?=$kind?></td><td class="shlz-table__cell" data-ledger-field="date"><?=$date((string)$row['closed_on'])?></td><td class="shlz-table__cell shlz-table__cell--numeric" data-ledger-field="paid"><?=$rub((int)$row['paid_cents'])?></td><td class="shlz-table__cell shlz-table__cell--numeric" data-ledger-field="discipline"><?=$rub((int)$row['discipline_cents'])?></td><td class="shlz-table__cell shlz-table__cell--numeric" data-ledger-field="deadline"><?=$rub((int)$row['deadline_cents'])?></td><td class="shlz-table__cell" data-ledger-field="basis"><?=Html::encode((string)$row['basis'])?></td><td class="shlz-table__cell" data-ledger-field="source"><a href="/pilot/otiz/snapshots/<?=(int)$row['snapshot_id']?>?object=<?=$objectId?>&amp;ledgerPage=1">Расчёт #<?=(int)$row['snapshot_id']?> от <?=$date((string)$row['source_report_date'])?></a><?php if($row['local_reversal_id']!==null):?><br><a href="#closure-<?=(int)$row['local_reversal_id']?>">Исходная запись № <?=(int)$row['local_reversal_id']?> · Сторно записи № <?=(int)$row['local_reversal_id']?></a><?php endif?></td></tr>
<?php endforeach?></tbody></table></div><?php endif?>
<?php if($pages>1):?><nav data-otiz-object-ledger-pagination aria-label="Страницы истории"><?php for($number=1;$number<=$pages;$number++):?><a href="/pilot/otiz/snapshots/<?=$snapshotId?>?object=<?=$objectId?>&amp;ledgerPage=<?=$number?>"<?=$number===$page?' aria-current="page"':''?>>Страница <?=$number?></a> <?php endfor?></nav><?php endif?>
</section>
