<?php
declare(strict_types=1);
use yii\helpers\Html;
FMonitor2\YiiRuntime\Assets\AuthAssetBundle::register($this);
$title=$done?'Учётная запись активирована':'Активация учётной записи';$this->beginPage();
?><!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=Html::encode($title)?> — FMonitor</title><link rel="icon" type="image/svg+xml" href="/pilot/assets/favicon.svg"><?php $this->head()?></head><body class="shlz-scope fm2-auth-page"><?php $this->beginBody()?>
<main class="fm2-auth-layout"><section class="fm2-auth-brand" aria-label="FMonitor"><img src="/pilot/assets/favicon.svg" alt="" width="56" height="56"><div><strong>FMonitor</strong><span>Управление монтажными работами</span></div></section><section class="fm2-auth-card"><div class="fm2-auth-heading"><span class="fm2-auth-kicker">ЩЛЗ · защищённый контур</span><h1><?=Html::encode($title)?></h1><?php if(!$done):?><p>Задайте пароль для входа в FMonitor.</p><?php endif?></div>
<?php if($done):?><p>Пароль сохранён. Теперь вы можете войти с корпоративным email.</p><a class="shlz-button shlz-button--primary fm2-auth-submit" href="/pilot/login">Войти</a>
<?php elseif($entry!==null):?><div class="fm2-auth-identity"><span class="fm2-auth-avatar" aria-hidden="true"><?=Html::encode(mb_strtoupper(mb_substr($entry['email'],0,1)))?></span><span><strong>Приглашённый пользователь</strong><small><?=Html::encode($entry['email'])?></small></span></div><form method="post" action="/pilot/activate" class="fm2-auth-form"><input type="hidden" name="<?=Html::encode(Yii::$app->request->csrfParam)?>" value="<?=Html::encode(Yii::$app->request->csrfToken)?>"><input type="hidden" name="token" value="<?=Html::encode($token)?>"><label class="shlz-field"><span class="shlz-field__label">Пароль</span><span class="shlz-field__control"><input class="shlz-input" type="password" name="password" autocomplete="new-password" minlength="14" maxlength="200" required autofocus></span></label><label class="shlz-field"><span class="shlz-field__label">Повторите пароль</span><span class="shlz-field__control"><input class="shlz-input" type="password" name="passwordConfirmation" autocomplete="new-password" minlength="14" maxlength="200" required></span></label><?php if($error!==''):?><p class="fm2-auth-error" role="alert"><?=Html::encode($error)?></p><?php endif?><button class="shlz-button shlz-button--primary fm2-auth-submit" type="submit">Активировать</button></form>
<?php else:?><p class="fm2-auth-error" role="alert"><?=Html::encode($error?:'Ссылка активации недействительна или истекла.')?></p><a class="fm2-auth-back" href="/pilot/login">Перейти ко входу</a><?php endif?></section><p class="fm2-auth-note">Пароль хранится только в виде необратимого криптографического хэша.</p></main>
<?php $this->endBody()?></body></html><?php $this->endPage()?>
