<?php declare(strict_types=1);use FMonitor2\YiiRuntime\MainNavigation;use FMonitor2\YiiRuntime\ViewSupport;use yii\helpers\Html;$pagination=$objects[0]['_pagination']??['page'=>1,'pages'=>1,'total'=>0];$failedInspection=$failedInspection??[];$inspectionMessage=$inspectionMessage??'';$canSchedule=$canSchedule??false;$today=$today??(new DateTimeImmutable('now',new DateTimeZone('Europe/Moscow')))->format('Y-m-d');$activity=static function(?string$value):?array{if($value===null||trim($value)==='')return null;try{$instant=(new DateTimeImmutable($value))->setTimezone(new DateTimeZone('Europe/Moscow'));return['source'=>$value,'date'=>$instant->format('d.m.Y'),'time'=>$instant->format('H:i')];}catch(Throwable){return null;}};ViewSupport::begin($this,'Стройконтроль',$identity,'construction-control','wide');?>
<section class="fm2-control-queue" data-control-queue data-user-id="<?=(int)$identity->getId()?>">
<header class="fm2-control-header">
<div><h1>Стройконтроль</h1><p class="fm2-control-description">Объекты, закреплённые за инженерами, и актуальное состояние чек-листов.</p></div>
<span data-result-count>
<?=$pagination['total']?> объектов</span>
</header>
<form class="fm2-control-tools fm2-control-toolbar" method="get" action="/pilot/construction-control" data-control-filter-form>
<label class="shlz-field fm2-control-search"><span class="shlz-field__label">Поиск объектов</span><span class="shlz-field__control"><img src="/pilot/assets/shlz-icons/search.svg" data-shlz-icon="search" alt=""><input class="shlz-input" type="search" name="query" value="<?=Html::encode($filters['query'])?>" data-control-search placeholder="Адрес, регистрационный или заводской номер"></span></label>
<div class="fm2-control-filters"><fieldset class="shlz-segment shlz-segment--sm" aria-label="Принадлежность объектов">
<label class="shlz-segment__option"><input class="shlz-segment__input" type="radio" name="ownership" value="mine" <?=$filters['ownership']==='mine'?'checked':''?>><span class="shlz-segment__label">Мои</span></label>
<label class="shlz-segment__option"><input class="shlz-segment__input" type="radio" name="ownership" value="all" <?=$filters['ownership']==='all'?'checked':''?>><span class="shlz-segment__label">Все</span></label>
</fieldset>
<label class="shlz-choice fm2-completed-switch"><input class="shlz-checkbox" type="checkbox" name="completed" value="1" data-show-completed <?=$filters['completed']==='1'?'checked':''?>><span>Показывать завершённые</span></label><button class="shlz-button shlz-button--secondary" type="button" data-clear-filters>Сбросить фильтры</button></div>
</form>
<div class="fm2-control-surface shlz-table-wrap" tabindex="0" aria-label="Объекты стройконтроля"><table class="shlz-table fm2-control-table"><thead class="shlz-table__head"><tr class="shlz-table__row"><th class="shlz-table__cell" scope="col">Объект</th><th class="shlz-table__cell" scope="col">Последняя активность</th><th class="shlz-table__cell" scope="col"><span class="fm2-visually-hidden">Отгрузка и техническая документация</span></th><th class="shlz-table__cell" scope="col">Инженер</th><th class="shlz-table__cell" scope="col"><span class="fm2-visually-hidden">Открыть</span></th></tr></thead>
<tbody>
<?php foreach($objects as$o):$engineer=$o['controlEngineer'];$factoryNumber=trim((string)($o['factoryNumber']??''));$factoryLabel=$factoryNumber!==''&&$factoryNumber!=='0'?'Зав. № '.$factoryNumber:'Заводской номер не указан';$shipmentDate=$o['fullShipmentDate']??$o['firstShipmentDate']??null;$shipmentState=($o['fullShipmentDate']??null)!==null?'full':(($o['firstShipmentDate']??null)!==null?'partial':'unknown');$shipmentTitle=$shipmentState==='full'?'Полностью отгружен':($shipmentState==='partial'?'Частично отгружен':'Не известно');$shipmentLabel=$shipmentDate===null?$shipmentTitle:$shipmentTitle.', '.(new DateTimeImmutable((string)$shipmentDate))->format('d.m.Y');$plan=$o['inspectionPlan']??null;?>
<tr class="fm2-control-row" data-control-row data-object-id="<?=$o['id']?>" data-engineer-id="<?=(int)($engineer['userId']??0)?>" data-completed="<?=$o['completed']?'true':'false'?>" data-document-status="<?=Html::encode($o['technicalDocumentStatus'])?>"<?php if($o['technicalDocumentStatus']==='available'):?> data-has-document="true"<?php endif?> data-search="<?=Html::encode(mb_strtolower($o['address'].' '.$o['registrationNumber'].' '.$factoryNumber))?>">
<td class="fm2-object-cell"><div class="fm2-control-identity"><span class="fm2-control-address"><?=Html::encode($o['address'])?></span><span class="fm2-control-reg"><?php if(trim((string)$o['entrance'])!==''):?><span class="fm2-control-entrance">Подъезд <?=Html::encode((string)$o['entrance'])?></span><?php endif?><span>Рег. № <?=Html::encode($o['registrationNumber'])?></span><span><?=Html::encode($factoryLabel)?></span></span></div>
<div class="fm2-control-plan-label"><?php if(($o['inspectionToday']??false)===true):?><strong>Инспекция сегодня</strong><?php elseif(is_array($plan)):?><span>Инспекция запланирована на <?=Html::encode((new DateTimeImmutable($plan['inspectionDate']))->format('d.m.Y'))?></span><?php endif?></div></td>
<?php $lastActivity=$activity($o['lastChecklistActivityAt']);$activityState=$lastActivity!==null?'recorded':(($o['ready']??false)?'ready':'empty');?><td data-activity-state="<?=$activityState?>">
<?php if($activityState==='ready'):?><span class="fm2-activity fm2-activity--ready">Готов к открытию</span><?php else:?><span class="fm2-activity-line"><span class="fm2-local-sync" data-local-sync>
<span class="fm2-visually-hidden">Синхронизировано</span>
</span><?php if($lastActivity!==null):?><time class="fm2-activity" datetime="<?=Html::encode($lastActivity['source'])?>"><span class="fm2-activity-date"><?=Html::encode($lastActivity['date'])?></span><small class="fm2-activity-time"><?=Html::encode($lastActivity['time'])?></small></time><?php else:?><span class="fm2-activity fm2-activity--never">Инспекций ещё не было</span><?php endif?></span><?php endif?>
</td>
<td class="fm2-shipment-cell" data-shipment-state="<?=$shipmentState?>"><span class="fm2-control-status-actions"><span class="fm2-shipment-status" aria-label="<?=Html::encode($shipmentLabel)?>" title="<?=Html::encode($shipmentLabel)?>">
<?php if($shipmentState!=='unknown'):?><span class="fm2-shipment-icon-stack" aria-hidden="true">
<img class="fm2-shipment-icon" src="/pilot/assets/shlz-icons/delivery-box.svg" alt="">
</span><?php endif?></span><?php if($o['technicalDocumentStatus']==='available'):?><a class="shlz-button shlz-button--primary shlz-button--icon fm2-control-document-action" href="<?=Html::encode((string)$o['technicalDocument']['url'])?>" target="_blank" rel="noopener noreferrer" aria-label="Открыть техническую документацию" title="Открыть техническую документацию"><?=MainNavigation::icon('folder-file-open','fm2-control-document-action-icon')?></a><?php else:?><button class="shlz-button shlz-button--icon fm2-control-document-action" type="button" disabled aria-label="Техническая документация недоступна" title="Техническая документация недоступна"><?=MainNavigation::icon('folder-file-open','fm2-control-document-action-icon')?></button><?php endif?><?php if(($o['canSchedule']??false)===true):?><?php if(is_array($plan)):?><button class="fm2-control-inspection-action fm2-control-inspection-action--planned shlz-button shlz-button--icon" type="button" data-inspection-action="reschedule" data-reschedule-label="Перенести" data-inspection-object-id="<?=$o['id']?>" data-plan-id="<?=$plan['scheduleId']?>" data-plan-version="<?=$plan['version']?>" data-inspection-date="<?=Html::encode($plan['inspectionDate'])?>" aria-label="Изменить план инспекции" title="Изменить план инспекции"><?=MainNavigation::icon('calendar-interface')?></button><?php else:?><button class="fm2-control-inspection-action shlz-button shlz-button--primary shlz-button--icon" type="button" data-inspection-action="create" data-inspection-object-id="<?=$o['id']?>" data-plan-id="" data-plan-version="0" data-inspection-date="<?=$today?>" aria-label="Запланировать инспекцию" title="Запланировать инспекцию"><?=MainNavigation::icon('calendar-interface')?></button><?php endif?><?php endif?></span>
</td>
<td>
<?=Html::encode((string)($engineer['fullName']??'Инженер не назначен'))?>
</td>
<td class="fm2-row-action"><a class="fm2-control-checklist-rail" href="/pilot/construction-control/objects/<?=$o['id']?>/checklist" aria-label="Открыть чек-лист"><?=MainNavigation::icon('chevron-right-duo')?></a></td>
</tr>
<?php endforeach?>
</tbody>
</table>
<div class="fm2-empty fm2-control-empty" data-control-empty <?=$pagination['total']===0?'':'hidden'?>>
<strong>Объекты не найдены</strong>
</div>
<footer class="fm2-control-footer"><span data-list-summary>Показано <?=count($objects)?> из <?=$pagination['total']?></span><?=ViewSupport::pagination('/pilot/construction-control',(int)$pagination['page'],(int)$pagination['pages'],(int)$pagination['total'],50,$filters,'Страницы стройконтроля')?></footer></div></section>
<script src="/pilot/assets/control-queue.js" defer>
</script>
<?php if($canSchedule):?><dialog class="shlz-modal fm2-inspection-dialog" data-inspection-dialog<?=($failedInspection!==[]?' data-inspection-failed':'')?> aria-labelledby="inspection-dialog-title"><form method="post" class="shlz-modal__surface fm2-inspection-dialog__surface" data-inspection-form><header class="shlz-modal__header"><div><h2 class="shlz-modal__title" id="inspection-dialog-title" data-inspection-title>Запланировать инспекцию</h2><p>Инспекция появится в календаре и списке стройконтроля.</p></div><button class="shlz-modal__close" type="button" aria-label="Закрыть" data-inspection-close>×</button></header><div class="shlz-modal__body fm2-inspection-dialog__body"><?php if($inspectionMessage!==''):?><p role="alert"><?=Html::encode($inspectionMessage)?></p><?php endif?><?=Html::hiddenInput(Yii::$app->request->csrfParam,Yii::$app->request->csrfToken)?><?=Html::hiddenInput('action',(string)($failedInspection['action']??'create'),['data-inspection-command'=>true])?><?=Html::hiddenInput('planId',(string)($failedInspection['planId']??''))?><?=Html::hiddenInput('expectedVersion',(string)($failedInspection['expectedVersion']??'0'))?><?=Html::hiddenInput('requestId',(string)($failedInspection['requestId']??ViewSupport::uuid()))?><?=Html::hiddenInput('ownership',(string)$filters['ownership'])?><?=Html::hiddenInput('query',(string)$filters['query'])?><?=Html::hiddenInput('completed',(string)$filters['completed'])?><div class="fm2-date-picker" data-inspection-date-field data-inspection-date-picker data-value="<?=Html::encode((string)($failedInspection['inspectionDate']??$today))?>"></div></div><footer class="shlz-modal__footer"><button class="shlz-button" type="button" data-inspection-close>Закрыть</button><button class="shlz-button shlz-button--secondary" type="button" data-inspection-cancel hidden>Отменить инспекцию</button><button class="shlz-button shlz-button--primary" type="submit" data-inspection-submit>Запланировать</button></footer></form></dialog>
<script type="module" src="/pilot/assets/inspection-schedule.js"></script><?php endif?>
<?php ViewSupport::end($this);
