<?php

declare(strict_types=1);

use FMonitor2\YiiRuntime\Assets\InstallerDirectoryAssetBundle;
use yii\helpers\Html;

InstallerDirectoryAssetBundle::register($this);
$csrf = Html::hiddenInput(Yii::$app->request->csrfParam, Yii::$app->request->csrfToken);
$parts = preg_split('/\s+/u', trim((string) $identity->displayName), -1, PREG_SPLIT_NO_EMPTY) ?: [];
$initials = implode('', array_map(static fn(string $part): string => mb_strtoupper(mb_substr($part, 0, 1)), array_slice($parts, 0, 2)));
$dateTime = static function (?string $value): string {
    if ($value === null || $value === '') return 'Неизвестно';
    return (new DateTimeImmutable($value))->setTimezone(new DateTimeZone('Europe/Moscow'))->format('d.m.Y H:i');
};
$date = static function (?string $value): string {
    if ($value === null || $value === '') return 'Дата увольнения неизвестна';
    return (new DateTimeImmutable($value))->format('d.m.Y');
};
$source = static fn(string $value): string => $value === 'one_c_zup_via_bitrix' ? '1С ЗУП через Битрикс' : $value;
$statusControl = Html::dropDownList('status', $filters['status'], ['' => 'Все', 'employed' => 'Работает', 'dismissed' => 'Уволен'], ['class' => 'shlz-select']);
$availabilityControl = Html::dropDownList('availability', $filters['availability'], ['' => 'Все', 'assigned' => 'Закреплён', 'free' => 'Свободен'], ['class' => 'shlz-select']);
$query = static function (int $page) use ($filters): string {
    $values = array_filter(['q' => $filters['q'], 'status' => $filters['status'], 'availability' => $filters['availability'], 'page' => $page], static fn($value, $key): bool => $value !== '' && !($key === 'page' && $value === 1), ARRAY_FILTER_USE_BOTH);
    return '/pilot/installers' . ($values === [] ? '' : '?' . http_build_query($values, '', '&', PHP_QUERY_RFC3986));
};
$this->beginPage();
?><!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Монтажники · FMonitor 2.0</title><link rel="icon" href="/pilot/assets/favicon.svg"><?php $this->head() ?></head>
<body class="shlz-scope"><?php $this->beginBody() ?><a class="fm2-skip shlz-link" href="#main-content">Перейти к содержанию</a>
<div class="fm2-shell"><aside class="fm2-sidebar"><div class="fm2-nav-body"><a class="fm2-logo" href="/pilot/objects" aria-label="FMonitor 2.0"><svg class="fm2-logo-mark" viewBox="0 0 32 32" aria-hidden="true"><rect class="fm2-logo-rail" x="5" y="4" width="4" height="24"/><rect class="fm2-logo-rail" x="23" y="4" width="4" height="24"/><rect class="fm2-logo-progress" x="11" y="10" width="10" height="12"/></svg><span class="fm2-logo-name">FMonitor 2.0</span></a>
<nav class="fm2-primary-nav" aria-label="Основная навигация"><span class="fm2-nav-group">Монтаж</span><a class="fm2-nav-item" href="/pilot/objects"><span class="fm2-nav-text">Объекты монтажа</span></a><a class="fm2-nav-item" href="/pilot/installers" aria-current="page"><span class="fm2-nav-text">Монтажники</span></a><?php if ($canControl): ?><a class="fm2-nav-item" href="/pilot/construction-control"><span class="fm2-nav-text">Стройконтроль</span></a><?php endif ?><?php if ($canAdmin): ?><span class="fm2-nav-group">Администрирование</span><a class="fm2-nav-item" href="/pilot/admin/users"><span class="fm2-nav-text">Пользователи</span></a><a class="fm2-nav-item" href="/pilot/admin/roles"><span class="fm2-nav-text">Роли</span></a><?php endif ?></nav></div>
<div class="fm2-sidebar-user"><span class="shlz-avatar shlz-avatar--32 fm2-sidebar-avatar"><?= Html::encode($initials) ?></span><span class="fm2-sidebar-user-copy"><strong><?= Html::encode($identity->displayName) ?></strong><small><?= Html::encode($identity->email) ?></small></span><form id="installer-directory-logout" method="post" action="/pilot/logout" class="fm2-logout-form"><?= $csrf ?></form><button class="fm2-logout" type="submit" form="installer-directory-logout" aria-label="Выйти"><span class="fm2-logout-text">Выйти</span></button></div><details class="fm2-nav-state" open><summary class="fm2-nav-trigger"><span class="fm2-nav-trigger-text">Свернуть меню</span></summary></details></aside>
<div class="fm2-workspace"><main class="fm2-main" id="main-content" tabindex="-1"><div class="fm2-page-header"><div><h1>Монтажники</h1><p>Кадровый статус и действующие закрепления</p></div><span class="fm2-result-count"><?= (int) $filters['total'] ?> сотрудников</span></div>
<section class="fm2-directory-summary"><div><strong data-directory-summary="total"><?= (int) $summary['total'] ?></strong><span>Всего</span></div><div><strong data-directory-summary="working"><?= (int) $summary['working'] ?></strong><span>Работают</span></div><div><strong data-directory-summary="dismissed"><?= (int) $summary['dismissed'] ?></strong><span>Уволены</span></div><div><strong data-directory-summary="assigned"><?= (int) $summary['assigned'] ?></strong><span>Закреплены</span></div><p><b>Снимок 1С ЗУП:</b> <?= Html::encode($dateTime($summary['updatedAt'])) ?></p></section>
<section class="fm2-list-surface" data-filter-query="<?= Html::encode(http_build_query(array_filter(['q' => $filters['q'], 'status' => $filters['status'], 'availability' => $filters['availability']], static fn($value): bool => $value !== ''), '', '&', PHP_QUERY_RFC3986)) ?>"><form method="get" action="/pilot/installers" class="fm2-user-toolbar"><label class="shlz-field"><span class="shlz-field__label">Поиск</span><span class="shlz-field__control"><input class="shlz-input" type="search" name="q" maxlength="120" value="<?= Html::encode($filters['q']) ?>" placeholder="ФИО или табельный номер"></span></label><label class="shlz-field"><span class="shlz-field__label">Кадровый статус</span><span class="shlz-field__control"><?= $statusControl ?></span></label><label class="shlz-field"><span class="shlz-field__label">Закрепление</span><span class="shlz-field__control"><?= $availabilityControl ?></span></label><button class="shlz-button shlz-button--primary" type="submit">Показать</button><?php if ($filters['q'] !== '' || $filters['status'] !== '' || $filters['availability'] !== ''): ?><a class="shlz-button shlz-button--secondary" href="/pilot/installers">Сбросить</a><?php endif ?></form>
<?php if ((int) $summary['total'] === 0): ?><p class="shlz-table__empty">Каталог монтажников пока не загружен</p><?php elseif ($rows === []): ?><p class="shlz-table__empty">Ничего не найдено</p><?php else: ?><div class="shlz-table-wrap fm2-installer-table-scroll"><table class="shlz-table fm2-installer-table"><thead class="shlz-table__head"><tr class="shlz-table__row"><th class="shlz-table__cell">Монтажник</th><th class="shlz-table__cell">Должность</th><th class="shlz-table__cell">Кадровый статус</th><th class="shlz-table__cell">Действующие закрепления</th><th class="shlz-table__cell">Источник</th></tr></thead><tbody><?php foreach ($rows as $row): ?><tr class="shlz-table__row"><td class="shlz-table__cell" data-label="Монтажник"><strong><?= Html::encode(trim($row['fio'])) ?></strong><small>таб. <?= str_pad((string) $row['installer_tab_id'], 6, '0', STR_PAD_LEFT) ?></small></td><td class="shlz-table__cell" data-label="Должность"><?= Html::encode(trim($row['position'])) ?></td><td class="shlz-table__cell" data-label="Кадровый статус"><span class="fm2-employment fm2-employment--<?= $row['employment_status'] === 'employed' ? 'active' : 'dismissed' ?>"><?= $row['employment_status'] === 'employed' ? 'Работает' : 'Уволен' ?></span><?php if ($row['employment_status'] === 'dismissed'): ?><small><?= Html::encode($date($row['dismissal_effective_at'])) ?></small><?php endif ?></td><td class="shlz-table__cell" data-label="Действующие закрепления"><?php if ($row['assignments'] === []): ?><span class="shlz-table__empty">Нет действующих закреплений</span><?php else: ?><?php foreach ($row['assignments'] as $assignment): ?><a class="shlz-link fm2-assignment-link" href="/pilot/objects/<?= (int) $assignment['object_id'] ?>"><strong><?= Html::encode($assignment['registration_number']) ?></strong><span><?= Html::encode($assignment['address']) ?></span></a><?php endforeach ?><?php endif ?></td><td class="shlz-table__cell" data-label="Источник"><strong><?= Html::encode($source($row['workforce_source'])) ?></strong><small><?= Html::encode($dateTime($row['workforce_source_updated_at'])) ?></small></td></tr><?php endforeach ?></tbody></table></div><?php endif ?>
<?php if ((int) $filters['pages'] > 1): ?><nav class="fm2-pagination" aria-label="Страницы"><?php for ($page = 1; $page <= $filters['pages']; $page++): ?><a class="shlz-button shlz-button--sm" href="<?= Html::encode($query($page)) ?>"<?= $page === $filters['page'] ? ' aria-current="page" data-current-page="true"' : '' ?>><?= $page ?></a><?php endfor ?></nav><?php endif ?></section></main></div></div>
<?php $this->endBody() ?></body></html><?php $this->endPage();
