<?php
declare(strict_types=1);
use FMonitor2\YiiRuntime\Assets\ShellAssetBundle;
use FMonitor2\YiiRuntime\ViewSupport;
use yii\helpers\Html;
ShellAssetBundle::register($this);
ViewSupport::begin($this, 'Состояние интеграций', $identity, 'admin-integrations');
$date=static function(?string$value):string{if($value===null||$value==='')return'Не регистрируется';try{return(new DateTimeImmutable($value))->setTimezone(new DateTimeZone('Europe/Moscow'))->format('d.m.Y H:i');}catch(Throwable){return'Не регистрируется';}};
$run=static function(?array$r,string$type)use($date):string{if($r===null)return'<span class="shlz-status">Не запускалась</span>';if(($r['status']??'')==='completed'){$counts=[];if($type==='workforce')$counts=['Доставлено: '.(int)($r['delivered_count']??0),'Изменено: '.(int)($r['material_change_count']??0),'Отсутствуют: '.(int)($r['missing_count']??0)];else{$c=$r['counts']??[];$counts=['Успешно обработано: '.((int)($c['matched']??0)+(int)($c['changed']??0)+(int)($c['unchanged']??0)),'Не найдены: '.(int)($c['unmatched']??0),'Неоднозначны: '.(int)($c['ambiguous']??0)];}return'<span class="shlz-status">Успешно</span><small>'.Html::encode($date((string)($r['observed_at']??$r['completed_at']??''))).' · '.Html::encode(implode(' · ',$counts)).'</small>';}$reason=(string)($r['failure_code']??$r['reason']??'Ошибка источника');return'<span class="shlz-status">Ошибка</span><small>'.Html::encode($date((string)($r['completed_at']??$r['observed_at']??''))).' · '.Html::encode($reason).'</small>';};
$url=static function(string$name,int$value,array$pages):string{$query=['workforcePage'=>$pages['workforce'],'equipmentPage'=>$pages['equipment'],'jobsPage'=>$pages['jobs']];$query[$name]=$value;return'/pilot/admin/integrations?'.http_build_query($query,'','&',PHP_QUERY_RFC3986);};
$pager=static function(string$name,array$data,array$pages,int$pageSize)use($url):string{$page=(int)($data['page']??1);$last=max(1,(int)ceil((int)$data['total']/$pageSize));if($last===1)return'';$html='<nav aria-label="Страницы списка"><span>Страница '.$page.' из '.$last.'</span>';if($page>1)$html.='<a class="shlz-link" aria-label="Предыдущая страница" href="'.Html::encode($url($name,$page-1,$pages)).'">Назад</a>';if($page<$last)$html.='<a class="shlz-link" aria-label="Следующая страница" href="'.Html::encode($url($name,$page+1,$pages)).'">Далее</a>';return$html.'</nav>';};
?>
<header class="fm2-page-header"><div><h1>Состояние интеграций</h1><p>Сохранённые результаты обмена и очереди ошибок</p></div></header>
<section aria-labelledby="workforce-summary"><h2 id="workforce-summary">Кадровая интеграция Bitrix</h2><?php if(!$workforce['available']):?><p class="shlz-alert shlz-alert--danger">Данные недоступны</p><?php else:?><dl><div><dt>Последняя попытка</dt><dd><?=$run($workforce['attempt'],'workforce')?></dd></div><div><dt>Последний успех</dt><dd><?=$run($workforce['success'],'workforce')?></dd></div></dl><?php endif?></section>
<section aria-labelledby="equipment-summary"><h2 id="equipment-summary">ERP по оборудованию</h2><?php if(!$equipment['available']):?><p class="shlz-alert shlz-alert--danger">Данные недоступны</p><?php else:?><dl><div><dt>Последняя попытка</dt><dd><?=$run($equipment['attempt'],'equipment')?></dd></div><div><dt>Последний успех</dt><dd><?=$run($equipment['success'],'equipment')?></dd></div></dl><?php endif?></section>
<section aria-labelledby="workforce-list"><h2 id="workforce-list">Не сопоставленные работники</h2><p>Конфликты идентичности: детали не регистрируются.</p><?php if(!$workforce['available']):?><p class="shlz-alert shlz-alert--danger">Данные недоступны</p><?php elseif($workforce['rows']===[]):?><div class="shlz-empty-state shlz-empty-state--simple"><div class="shlz-empty-state__content"><p>Не сопоставленных работников нет.</p></div></div><?php else:?><div class="shlz-table-wrap" data-mobile-strategy="contained-scroll" tabindex="0"><table class="shlz-table"><thead class="shlz-table__head"><tr class="shlz-table__row"><th class="shlz-table__cell">Табельный номер</th><th class="shlz-table__cell">Работник</th><th class="shlz-table__cell">Должность</th><th class="shlz-table__cell">Обновлено</th></tr></thead><tbody><?php foreach($workforce['rows']as$r):?><tr class="shlz-table__row"><td class="shlz-table__cell"><?=(int)$r['installer_tab_id']?></td><td class="shlz-table__cell"><?=Html::encode((string)$r['fio'])?></td><td class="shlz-table__cell"><?=Html::encode((string)$r['position'])?></td><td class="shlz-table__cell"><?=Html::encode($date((string)$r['workforce_source_updated_at']))?></td></tr><?php endforeach?></tbody></table></div><?=$pager('workforcePage',$workforce,$pages,$pageSize)?><?php endif?></section>
<section aria-labelledby="equipment-list"><h2 id="equipment-list">Диагностика ERP</h2><?php if(!$equipment['available']):?><p class="shlz-alert shlz-alert--danger">Данные недоступны</p><?php elseif($equipment['rows']===[]):?><div class="shlz-empty-state shlz-empty-state--simple"><div class="shlz-empty-state__content"><p>Диагностических записей ERP нет.</p></div></div><?php else:?><div class="shlz-table-wrap" data-mobile-strategy="contained-scroll" tabindex="0"><table class="shlz-table"><thead class="shlz-table__head"><tr class="shlz-table__row"><th class="shlz-table__cell">Заказ (HMAC)</th><th class="shlz-table__cell">Причина</th><th class="shlz-table__cell">Создано</th></tr></thead><tbody><?php foreach($equipment['rows']as$r):?><tr class="shlz-table__row"><td class="shlz-table__cell"><?=Html::encode(substr((string)$r['source_order_hmac'],0,12))?></td><td class="shlz-table__cell"><?=Html::encode((string)$r['reason'])?></td><td class="shlz-table__cell"><?=Html::encode($date((string)$r['created_at']))?></td></tr><?php endforeach?></tbody></table></div><?=$pager('equipmentPage',$equipment,$pages,$pageSize)?><?php endif?></section>
<section aria-labelledby="jobs-list"><h2 id="jobs-list">Неуспешные фоновые задания</h2><?php if(!$jobs['available']):?><p class="shlz-alert shlz-alert--danger">Данные заданий недоступны</p><?php elseif($jobs['rows']===[]):?><div class="shlz-empty-state shlz-empty-state--simple"><div class="shlz-empty-state__content"><p>Неуспешных фоновых заданий нет.</p></div></div><?php else:?><div class="shlz-table-wrap" data-mobile-strategy="contained-scroll" tabindex="0"><table class="shlz-table"><thead class="shlz-table__head"><tr class="shlz-table__row"><th class="shlz-table__cell">ID</th><th class="shlz-table__cell">Тип</th><th class="shlz-table__cell">Попытка</th><th class="shlz-table__cell">Код ошибки</th><th class="shlz-table__cell">Завершено</th></tr></thead><tbody><?php foreach($jobs['rows']as$r):?><tr class="shlz-table__row"><td class="shlz-table__cell"><?=(int)$r['job_id']?></td><td class="shlz-table__cell"><?=Html::encode((string)$r['job_type'])?></td><td class="shlz-table__cell"><?=(int)$r['attempt']?></td><td class="shlz-table__cell"><?=Html::encode((string)$r['failure_code'])?></td><td class="shlz-table__cell"><?=Html::encode($date((string)$r['completed_at_utc']))?></td></tr><?php endforeach?></tbody></table></div><?=$pager('jobsPage',$jobs,$pages,$pageSize)?><?php endif?></section>
<section class="shlz-empty-state shlz-empty-state--simple"><div class="shlz-empty-state__content"><h2>Границы первого этапа</h2><p>Состояние настройки: Не регистрируется. Детали конфликтов кадровой идентичности также пока не сохраняются. Повторный запуск и остальные интеграции остаются в задаче #30.</p></div></section>
<?php ViewSupport::end($this); ?>
