<?php
declare(strict_types=1);
use yii\helpers\Html;
use FMonitor2\YiiRuntime\Assets\ObjectQueueAssetBundle;
ObjectQueueAssetBundle::register($this);
$f=$filters;$csrf=Html::hiddenInput(Yii::$app->request->csrfParam,Yii::$app->request->csrfToken);
$statuses=[''=>'Все статусы','needs_assignment_order'=>'Требуется распоряжение','ready_to_open'=>'Готов к открытию','installation'=>'Монтажные работы','document_closeout'=>'Документарное закрытие','completed'=>'Работы завершены','needs_assignment_change'=>'Требуется изменение'];
$query=static fn(int$page):string=>'/pilot/objects?'.http_build_query(array_filter(['q'=>$f['q'],'status'=>$f['status'],'page'=>$page],static fn($v,$k)=>$v!==''&&($k!=='page'||$v!==1),ARRAY_FILTER_USE_BOTH),'','&',PHP_QUERY_RFC3986);
$initials='';foreach(array_slice(preg_split('/\s+/u',trim($identity->displayName),-1,PREG_SPLIT_NO_EMPTY)?:[],0,2)as$part)$initials.=mb_strtoupper(mb_substr($part,0,1));
$canAdmin=Yii::$app->canonicalAccess->checkAccess((int)$identity->id,'access.administer');
$statusClasses=['Требуется распоряжение'=>'shlz-status--orange','Готов к открытию'=>'shlz-status--source-blue','Монтажные работы'=>'shlz-status--cyan','Документарное закрытие'=>'shlz-status--purple','Работы завершены'=>'shlz-status--bright-green','Требуется изменение'=>'shlz-status--pink'];
$this->beginPage();
?><!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Объекты монтажа · FMonitor 2.0</title><link rel="icon" href="/pilot/assets/favicon.svg"><?php $this->head()?></head><body class="shlz-scope"><?php $this->beginBody()?>
<a class="fm2-skip shlz-link" href="#main-content">Перейти к содержанию</a>
<div class="fm2-shell"><aside class="fm2-sidebar"><div class="fm2-nav-body"><a class="fm2-logo" href="/pilot/objects"><svg class="fm2-logo-mark" viewBox="0 0 32 32" aria-hidden="true"><rect class="fm2-logo-rail" x="5" y="4" width="4" height="24"/><rect class="fm2-logo-rail" x="23" y="4" width="4" height="24"/><rect class="fm2-logo-progress" x="11" y="10" width="10" height="12"/></svg><span class="fm2-logo-name">FMonitor 2.0</span></a><nav class="fm2-primary-nav" aria-label="Основная навигация"><span class="fm2-nav-group">Монтаж</span><a class="fm2-nav-item" href="/pilot/objects" aria-current="page" aria-label="Объекты монтажа"><svg class="fm2-nav-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M4 20V8l8-5 8 5v12H4Zm5 0v-6h6v6"/></svg><span class="fm2-nav-text">Объекты монтажа</span></a><?php if($canAdmin):?><span class="fm2-nav-group">Администрирование</span><a class="fm2-nav-item" href="/pilot/admin/users" aria-label="Пользователи"><svg class="fm2-nav-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M10.6 2h2.8l.6 2.5 2 .8 2.2-1.3 2 2-1.3 2.2.8 2 2.3.6v2.8l-2.3.6-.8 2 1.3 2.2-2 2-2.2-1.3-2 .8-.6 2.5h-2.8l-.6-2.5-2-.8-2.2 1.3-2-2 1.3-2.2-.8-2-2.3-.6v-2.8l2.3-.6.8-2L3.8 6l2-2L8 5.3l2-.8.6-2.5Z"/></svg><span class="fm2-nav-text">Пользователи</span></a><a class="fm2-nav-item" href="/pilot/admin/roles" aria-label="Роли"><svg class="fm2-nav-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M6 3.5a3.5 3.5 0 1 0 0 7 3.5 3.5 0 0 0 0-7Zm12 0a3.5 3.5 0 1 0 0 7 3.5 3.5 0 0 0 0-7ZM2 19.5c.3-4.2 1.7-6.5 4-6.5s3.7 2.3 4 6.5H2Zm12 0c.3-4.2 1.7-6.5 4-6.5s3.7 2.3 4 6.5h-8Z"/></svg><span class="fm2-nav-text">Роли</span></a><?php endif?></nav></div>
<div class="fm2-sidebar-user"><span class="shlz-avatar shlz-avatar--32 fm2-sidebar-avatar"><?=Html::encode($initials)?></span><span class="fm2-sidebar-user-copy"><strong><?=Html::encode($identity->displayName)?></strong><small><?=Html::encode($identity->email)?></small></span><form method="post" action="/pilot/logout" class="fm2-logout-form"><?=$csrf?><button class="fm2-logout" type="submit" aria-label="Выйти"><svg class="fm2-user-logout-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M10 4H5v16h5M14 8l4 4-4 4m4-4H9" fill="none" stroke="currentColor" stroke-width="1.7"/></svg><span class="fm2-logout-text">Выйти</span></button></form></div><details class="fm2-nav-state" open><summary class="fm2-nav-trigger"><span class="fm2-nav-trigger-text">Свернуть меню</span></summary></details></aside>
<div class="fm2-workspace"><main class="fm2-main" id="main-content" tabindex="-1"><div class="fm2-page-header"><div><h1>Объекты монтажа</h1><p>Найдите объект и перейдите к следующему действию</p></div><span class="fm2-result-count"><?=$f['total']?> объектов</span></div>
<?php if($notice!==''):$date=new DateTimeImmutable($notice);?><p class="fm2-inspection-notice" role="status">Инспекция запланирована на <?=$date->format('d.m.Y')?>.</p><?php endif?>
<section class="fm2-list-surface"><div class="fm2-list-toolbar"><form class="fm2-object-filters" method="get" action="/pilot/objects">
<label class="shlz-field"><span class="shlz-field__label">Поиск</span><span class="shlz-field__control"><?=Html::input('search','q',$f['q'],['class'=>'shlz-input','maxlength'=>120,'placeholder'=>'ID, регномер, адрес или подъезд'])?></span></label>
<label class="shlz-field"><span class="shlz-field__label">Статус</span><span class="shlz-field__control"><?=Html::dropDownList('status',$f['status'],$statuses,['class'=>'shlz-select'])?></span></label>
<button class="shlz-button shlz-button--primary" type="submit">Найти</button><a class="shlz-link" href="/pilot/objects">Сбросить</a></form></div>
<?php if($objects===[]):?><div class="fm2-queue-empty"><h2>Объекты не найдены</h2><p>Измените поиск или сбросьте фильтры.</p><a class="shlz-link" href="/pilot/objects">Сбросить</a></div><?php else:?>
<div class="shlz-table-wrap"><table class="shlz-table fm2-queue-table"><thead><tr><th>Объект</th><th>Адрес</th><th>План</th><th>Статус</th><th>Следующий шаг</th><th></th></tr></thead><tbody>
<?php foreach($objects as$object):?><tr><td data-label="Объект"><a class="fm2-object-link" href="/pilot/objects/<?=$object['id']?>"><strong><?=Html::encode($object['registrationNumber'])?></strong><small>ID <?=$object['id']?></small></a></td><td data-label="Адрес"><?=Html::encode($object['address'])?><small>Подъезд <?=Html::encode($object['entrance'])?></small></td><td data-label="План"><?=Html::encode($object['plannedStartDate'])?><small>до <?=Html::encode($object['plannedFinishDate'])?></small></td><td data-label="Статус"><span class="shlz-status <?=$statusClasses[$object['status']]??'shlz-status--neutral'?>"><?=Html::encode($object['status'])?></span></td><td data-label="Следующий шаг"><?=Html::encode($object['nextStep'])?></td><td class="fm2-row-action fm2-inspection-action"><?php if($canSchedule&&$object['status']==='Монтажные работы'):?><button class="shlz-button shlz-button--sm fm2-schedule-button" type="button" data-inspection-schedule data-object-id="<?=$object['id']?>" data-object-label="<?=Html::encode($object['registrationNumber'])?>" aria-label="Запланировать инспекцию"><svg viewBox="0 0 24 24" aria-hidden="true"><rect x="4" y="6" width="16" height="14" rx="2"/><path d="M8 3v6M16 3v6M4 10h16"/></svg></button><?php endif?></td></tr><?php endforeach?></tbody></table></div><?php endif?>
<?php if($f['pages']>1):?><nav class="fm2-pagination" aria-label="Страницы"><?php for($page=1;$page<=$f['pages'];$page++):?><a class="shlz-button shlz-button--sm" href="<?=Html::encode($query($page))?>"<?=$page===$f['page']?' aria-current="page"':''?>><?=$page?></a><?php endfor?></nav><?php endif?></section></main></div></div>
<dialog class="fm2-inspection-dialog" data-inspection-dialog><form method="post" class="fm2-inspection-dialog__surface" data-inspection-form><header><div><h2>Запланировать инспекцию</h2><p data-inspection-object></p></div><button type="button" aria-label="Закрыть" data-inspection-close>×</button></header><div class="fm2-inspection-dialog__body"><?=$csrf?><label class="shlz-field"><span class="shlz-field__label">Дата инспекции</span><span class="shlz-field__control"><?=Html::input('date','inspectionDate',$today,['class'=>'shlz-input','min'=>$today,'required'=>true])?></span><span class="shlz-field__secondary">Инспекция появится в календаре назначенного инженера.</span></label></div><footer><button class="shlz-button" type="button" data-inspection-close>Отмена</button><button class="shlz-button shlz-button--primary" type="submit">Запланировать</button></footer></form></dialog>
<?php $this->endBody()?></body></html><?php $this->endPage()?>
