<?php
declare(strict_types=1);
use FMonitor2\YiiRuntime\Controllers\OtizV2TraceHtml;
use FMonitor2\YiiRuntime\ViewSupport;
use yii\helpers\Html;
$rub=static fn(int$c):string=>($c<0?'−':'').number_format(abs($c)/100,2,',',' ').' ₽';
$date=static fn(string$v):string=>preg_match('/^(\d{4})-(\d{2})-(\d{2})/D',$v,$m)?$m[3].'.'.$m[2].'.'.$m[1]:Html::encode($v);
$snapshot=$projection['snapshot'];$id=(int)$snapshot['id'];$total=0;
foreach($projection['objects']as$object)if($object['calculation_state']!=='blocked')$total+=max(0,(int)$object['accrued_cents']-(int)$object['global_closed_cents']);
$flash=isset($query['created'])?'Расчёт подготовлен. Проверьте суммы и замечания по объектам.':(isset($query['accepted'])?'Расчёт подтверждён и готов к оформлению выплаты.':(isset($query['closed'])?'Удержание добавлено к выплате по объекту.':(isset($query['reversed'])?'Предыдущая отметка о выплате отменена.':(($query['paid']??'')==='1'?'Выплаты отмечены выполненными и учтены по объектам.':(($query['paid']??'')==='duplicate'?'Эти выплаты уже были отмечены выполненными.':(isset($query['error'])?'Действие не выполнено. Устраните замечания по объектам и проверьте доступную сумму.':''))))));
$this->registerJsFile('/pilot/assets/otiz.js',['type'=>'module','position'=>\yii\web\View::POS_END]);
ViewSupport::begin($this,'Выплаты на '.$date((string)$snapshot['report_date']),$identity,'otiz');
?>
<div class="fm2-otiz fm2-otiz-page">
<?= $this->render('_otiz-nav',['current'=>'snapshot']) ?>
<section class="fm2-otiz-workflow fm2-otiz-summary" data-otiz-workflow-header><div><h1>Выплаты на <?= $date((string)$snapshot['report_date']) ?></h1><span class="shlz-status"><?= $snapshot['status']==='accepted'?'Готовы к выплате':($snapshot['status']==='paid'?'Выплачено':'На проверке') ?></span><p>Итого по доступным объектам <strong><?= $rub($total) ?></strong></p></div><div class="fm2-otiz-workflow-actions">
<?php if($snapshot['status']==='draft'): ?><form method="post" action="/pilot/otiz/snapshots/<?= $id ?>/accept"><input type="hidden" name="_csrf" value="<?= Html::encode($csrf) ?>"><button class="shlz-button shlz-button--primary" type="submit">Подтвердить расчёт</button></form>
<?php elseif($snapshot['status']==='accepted'&&$total>0): ?><form method="post" action="/pilot/otiz/snapshots/<?= $id ?>/payments/complete"><input type="hidden" name="_csrf" value="<?= Html::encode($csrf) ?>"><input type="hidden" name="operationId" value="<?= ViewSupport::uuid() ?>"><button class="shlz-button shlz-button--primary" type="submit">Отметить выплаты выполненными</button></form><a class="shlz-button shlz-button--secondary" href="/pilot/otiz/snapshots/<?= $id ?>/export.xlsx">Скачать реестр XLSX</a>
<?php else: ?><a class="shlz-button shlz-button--secondary" href="/pilot/otiz/snapshots/<?= $id ?>/export.xlsx">Скачать реестр XLSX</a><?php endif ?>
</div></section>
<?php if($flash!==''): ?><p class="fm2-otiz-feedback" role="<?= isset($query['error'])?'alert':'status' ?>"><?= Html::encode($flash) ?></p><?php endif ?>
<?php foreach($projection['objects']as$object): $available=max(0,(int)$object['accrued_cents']-(int)$object['global_closed_cents']);$oid=(int)$object['object_id']; ?>
<section class="fm2-otiz-object-row" data-otiz-object="<?= $oid ?>" aria-labelledby="otiz-object-<?= $oid ?>"><header><div><h2 id="otiz-object-<?= $oid ?>"><?= Html::encode((string)$object['regnumber']) ?></h2><p><?= Html::encode((string)$object['address']) ?></p></div><dl><div><dt>Начислено</dt><dd><?= $rub((int)$object['accrued_cents']) ?></dd></div><div><dt>Доступно</dt><dd><?= $rub($available) ?></dd></div></dl></header>
<?php $trace=OtizV2TraceHtml::render($object);if($trace!==''): ?><?= $trace ?><?php else: ?><details class="fm2-otiz-trace"><summary>Как рассчитана сумма</summary><p>Подробная трассировка для этого расчёта не сохранена. Использованы зафиксированные суммы периода.</p></details><?php endif ?>
<div class="fm2-otiz-allocation"><h3>Начисления работникам</h3><?php if($object['allocations']===[]): ?><p data-empty="allocations">Начислений работникам пока нет.</p><?php else: foreach($object['allocations']as$allocation): $ktu=(int)($allocation['effective_ktu_bp']??0);if((int)($allocation['base_ktu_bp']??0)===(int)($allocation['contribution_bp']??0)&&$ktu===(int)($allocation['contribution_bp']??0)&&str_contains((string)($allocation['participation_basis']??''),'коэффициент 1,00'))$ktu=10000; ?><p data-allocation><?= Html::encode((string)$allocation['full_name']) ?> · таб. <?= Html::encode((string)$allocation['tab_id']) ?> · КТУ <?= number_format($ktu/10000,2,',',' ') ?> · <?= $rub((int)$allocation['amount_cents']) ?></p><?php endforeach;endif ?></div>
<div class="fm2-otiz-issues"><h3>Замечания</h3><?php if($object['issues']===[]): ?><p data-empty="issues">Замечаний нет.</p><?php else:foreach($object['issues']as$issue): ?><p data-severity="<?= Html::encode((string)$issue['severity']) ?>"><strong><?= $issue['severity']==='blocker'?'Нужно исправить':'Обратите внимание' ?></strong>: <?= Html::encode((string)$issue['message']) ?> · ответственный: <?= Html::encode((string)$issue['owner_role']) ?></p><?php endforeach;endif ?></div>
<?php if($snapshot['status']==='accepted'&&$object['calculation_state']!=='blocked'&&$available>0): ?><section class="fm2-otiz-discipline"><h3>Дисциплинарное удержание</h3><form method="post" action="/pilot/otiz/snapshots/<?= $id ?>/closures"><input type="hidden" name="_csrf" value="<?= Html::encode($csrf) ?>"><input type="hidden" name="operationId" value="<?= ViewSupport::uuid() ?>"><input type="hidden" name="objectId" value="<?= $oid ?>"><label>Сумма<input class="shlz-input" name="discipline" inputmode="decimal" placeholder="0.00"></label><label>Основание<input class="shlz-input" name="basis"></label><label>Документ<input class="shlz-input" name="artifact"></label><button class="shlz-button shlz-button--secondary" type="submit">Добавить удержание</button></form></section>
<?php elseif($object['calculation_state']==='blocked'): ?><p class="fm2-otiz-state"><strong>Требует данных.</strong> Устраните замечания, указанные выше.</p><?php else: ?><p class="fm2-otiz-state">Выплата по объекту выполнена.</p><?php endif ?>
</section><?php endforeach ?>
<?php if($projection['closures']!==[]): ?><section class="fm2-otiz-ledger"><h2>Выполненные выплаты и удержания</h2><div class="shlz-table-wrap" data-mobile-strategy="contained-scroll" aria-label="Реестр выплат и удержаний" tabindex="0"><table class="shlz-table"><thead><tr><th>Действие</th><th>Дата</th><th>Объект</th><th>Выплачено</th><th>Удержано по дисциплине</th><th>Удержано за сроки</th><th>Основание</th></tr></thead><tbody>
<?php foreach($projection['closures']as$closure):$reversal=(int)($closure['reverses_payment_closure_id']??0)>0; ?><tr><td><?php if(!$reversal): ?><form method="post" action="/pilot/otiz/closures/<?= (int)$closure['id'] ?>/reverse"><input type="hidden" name="_csrf" value="<?= Html::encode($csrf) ?>"><input type="hidden" name="operationId" value="<?= ViewSupport::uuid() ?>"><input class="shlz-input" name="basis" aria-label="Основание сторно"><button class="shlz-button shlz-button--danger" type="submit">Сторнировать</button></form><?php endif ?></td><td><?= $date((string)$closure['closed_on']) ?></td><td><?= Html::encode((string)$closure['regnumber']) ?></td><td><?= $rub((int)$closure['paid_cents']) ?></td><td><?= $rub((int)$closure['discipline_cents']) ?></td><td><?= $rub((int)$closure['deadline_cents']) ?></td><td><?= Html::encode((string)$closure['basis']) ?><?= $reversal?' Сторно записи № '.(int)$closure['reverses_payment_closure_id']:'' ?></td></tr><?php endforeach ?>
</tbody></table></div></section><?php endif ?>
</div>
<?php ViewSupport::end($this); ?>
