<?php
declare(strict_types=1);

namespace FMonitor2\PilotHttp;

final class ChecklistSync
{
    private const SECTION_ITEMS=[1=>[28,29,30,31,32,33,34,35,36],2=>[37,38,39,40,41],3=>[1,2,3,4,5,6],4=>[7,8,9,10],5=>[11,12,13,14,15],6=>[16,17,18,19,20,21],7=>[22,23,24,25,26,27],8=>[42]];
    public function __construct(private readonly \mysqli $db,private readonly string $prefix,private readonly string $storageRoot,private readonly string $now){}

    public function ensureSchema():void
    {
        $p=$this->prefix;
        $this->db->query("CREATE TABLE IF NOT EXISTS `{$p}fm2_checklist_revisions`(installation_case_id BIGINT UNSIGNED NOT NULL PRIMARY KEY,revision_no BIGINT UNSIGNED NOT NULL DEFAULT 0,updated_at VARCHAR(40) NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
        $this->db->query("CREATE TABLE IF NOT EXISTS `{$p}fm2_checklist_operations`(id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,installation_case_id BIGINT UNSIGNED NOT NULL,client_operation_id CHAR(36) NOT NULL,device_installation_id CHAR(36) NOT NULL,operation_type VARCHAR(40) NOT NULL,section_id TINYINT UNSIGNED NOT NULL,item_id SMALLINT UNSIGNED NULL,actor_user_id BIGINT UNSIGNED NOT NULL,device_time VARCHAR(40) NOT NULL,server_received_at VARCHAR(40) NOT NULL,base_revision BIGINT UNSIGNED NOT NULL,accepted_revision BIGINT UNSIGNED NOT NULL,payload_json TEXT NOT NULL,UNIQUE KEY(client_operation_id),KEY(installation_case_id,id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
        $this->db->query("CREATE TABLE IF NOT EXISTS `{$p}fm2_checklist_photos`(id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,installation_case_id BIGINT UNSIGNED NOT NULL,section_id TINYINT UNSIGNED NOT NULL,upload_operation_id CHAR(36) NOT NULL,sha256 CHAR(64) NOT NULL,mime_type VARCHAR(40) NOT NULL,byte_size INT UNSIGNED NOT NULL,original_name VARCHAR(255) NOT NULL,storage_name VARCHAR(255) NOT NULL,actor_user_id BIGINT UNSIGNED NOT NULL,device_time VARCHAR(40) NOT NULL,server_received_at VARCHAR(40) NOT NULL,revoked_at VARCHAR(40) NULL,UNIQUE KEY(upload_operation_id),UNIQUE KEY(installation_case_id,section_id,sha256),KEY(installation_case_id,section_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
    }

    public function projection(int $objectId):array
    {
        $case=$this->case($objectId,false);if($case===null)throw new \OutOfBoundsException();$caseId=(int)$case['id'];$revision=$this->revision($caseId);
        $s=$this->db->prepare("SELECT client_operation_id,operation_type,section_id,item_id,actor_user_id,device_time,server_received_at,accepted_revision,payload_json FROM `{$this->prefix}fm2_checklist_operations` WHERE installation_case_id=? ORDER BY id");$s->bind_param('i',$caseId);$s->execute();$rows=$s->get_result()->fetch_all(MYSQLI_ASSOC);
        $items=[];$completed=[];foreach($rows as$r){if($r['operation_type']==='item_completed')$items[(string)$r['item_id']]=['clientOperationId'=>$r['client_operation_id'],'actorUserId'=>(int)$r['actor_user_id'],'deviceTime'=>$r['device_time'],'serverReceivedAt'=>$r['server_received_at'],'revision'=>(int)$r['accepted_revision']];if($r['operation_type']==='section_completed')$completed[(string)$r['section_id']]=['clientOperationId'=>$r['client_operation_id'],'serverReceivedAt'=>$r['server_received_at'],'revision'=>(int)$r['accepted_revision']];}
        $s=$this->db->prepare("SELECT id,section_id,upload_operation_id,sha256,mime_type,byte_size,original_name,actor_user_id,device_time,server_received_at FROM `{$this->prefix}fm2_checklist_photos` WHERE installation_case_id=? AND revoked_at IS NULL ORDER BY id");$s->bind_param('i',$caseId);$s->execute();$photos=[];foreach($s->get_result()->fetch_all(MYSQLI_ASSOC)as$r)$photos[]=['id'=>(int)$r['id'],'sectionId'=>(int)$r['section_id'],'clientOperationId'=>$r['upload_operation_id'],'sha256'=>$r['sha256'],'mime'=>$r['mime_type'],'size'=>(int)$r['byte_size'],'originalName'=>$r['original_name'],'actorUserId'=>(int)$r['actor_user_id'],'deviceTime'=>$r['device_time'],'serverReceivedAt'=>$r['server_received_at']];
        return ['revision'=>$revision,'items'=>$items,'photos'=>$photos,'completedSections'=>$completed];
    }

    public function accept(int $objectId,HttpUser $actor,array $operation,?string $bytes=null):array
    {
        $id=(string)($operation['clientOperationId']??'');$device=(string)($operation['deviceInstallationId']??'');$type=(string)($operation['type']??'');$deviceTime=(string)($operation['deviceTime']??'');$base=$operation['baseRevision']??null;$section=$operation['sectionId']??null;
        if(!self::uuid($id)||!self::uuid($device)||!self::instant($deviceTime)||!\is_int($base)||$base<0||!\is_int($section)||!isset(self::SECTION_ITEMS[$section]))return ['status'=>'rejected','message'=>'Некорректные данные операции.'];
        $duplicate=$this->duplicate($id);if($duplicate!==null)return ['status'=>'duplicate','revision'=>(int)$duplicate['accepted_revision']];
        $this->db->begin_transaction();try{
            $case=$this->case($objectId,true);if($case===null){$this->db->rollback();return ['status'=>'rejected','message'=>'Объект не найден.'];}if($case['process_state']!=='working'){ $this->db->rollback();return ['status'=>'rejected','message'=>'Работы на объекте не открыты.'];}$caseId=(int)$case['id'];$revision=$this->revision($caseId,true);if($base>$revision){$this->db->rollback();return ['status'=>'conflict','message'=>'Данные изменились на другом устройстве.','revision'=>$revision];}
            $item=null;$payload=[];
            if($type==='item_completed'){$item=$operation['itemId']??null;if(!\is_int($item)||!\in_array($item,self::SECTION_ITEMS[$section],true)){ $this->db->rollback();return ['status'=>'rejected','message'=>'Пункт не относится к разделу.'];}}
            elseif($type==='photo_uploaded'){$result=$this->storePhoto($caseId,$section,$id,$actor,$deviceTime,$operation,$bytes);if($result!==null){$this->db->rollback();return $result;}$payload=['sha256'=>$operation['sha256'],'mime'=>$operation['mime'],'size'=>$operation['size'],'originalName'=>$operation['originalName']];}
            elseif($type==='photo_revoked'){$photoId=$operation['photoId']??null;if(!\is_int($photoId)||!$this->revokePhoto($caseId,$section,$photoId)){ $this->db->rollback();return ['status'=>'rejected','message'=>'Фотография не найдена.'];}$payload=['photoId'=>$photoId];}
            elseif($type==='section_completed'){if(!$this->sectionReady($caseId,$section)){ $this->db->rollback();return ['status'=>'rejected','message'=>'Для завершения нужны все работы и минимум одно принятое фото.'];}}
            else{$this->db->rollback();return ['status'=>'rejected','message'=>'Неизвестная операция.'];}
            $next=$revision+1;$json=\json_encode($payload,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR);$s=$this->db->prepare("INSERT INTO `{$this->prefix}fm2_checklist_operations`(installation_case_id,client_operation_id,device_installation_id,operation_type,section_id,item_id,actor_user_id,device_time,server_received_at,base_revision,accepted_revision,payload_json) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)");$actorId=$actor->id;$receivedAt=$this->now;$s->bind_param('isssiisssiis',$caseId,$id,$device,$type,$section,$item,$actorId,$deviceTime,$receivedAt,$base,$next,$json);$s->execute();$this->setRevision($caseId,$next);$this->db->commit();return ['status'=>'accepted','revision'=>$next];
        }catch(\mysqli_sql_exception $e){$this->db->rollback();$duplicate=$this->duplicate($id);if($duplicate!==null)return ['status'=>'duplicate','revision'=>(int)$duplicate['accepted_revision']];throw $e;}catch(\Throwable $e){$this->db->rollback();throw $e;}
    }

    private function storePhoto(int $caseId,int $section,string $id,HttpUser $actor,string $deviceTime,array $o,?string $bytes):?array
    {
        $mime=$o['mime']??null;$size=$o['size']??null;$sha=$o['sha256']??null;$name=$o['originalName']??null;$image=\is_string($bytes)?@\getimagesizefromstring($bytes):false;if(!\is_string($bytes)||!\in_array($mime,['image/jpeg','image/png','image/webp'],true)||!\is_array($image)||($image['mime']??null)!==$mime||!\is_int($size)||$size<1||$size>5*1024*1024||\strlen($bytes)!==$size||!\is_string($sha)||\preg_match('/^[a-f0-9]{64}$/D',$sha)!==1||!\hash_equals($sha,\hash('sha256',$bytes))||!\is_string($name)||$name===''||\mb_strlen($name)>255||\preg_match('/[\x00-\x1f\x7f]/u',$name)===1)return ['status'=>'rejected','message'=>'Фотография не прошла проверку типа или размера.'];
        $existing=$this->db->prepare("SELECT id FROM `{$this->prefix}fm2_checklist_photos` WHERE installation_case_id=? AND section_id=? AND sha256=? AND revoked_at IS NULL LIMIT 1");$existing->bind_param('iis',$caseId,$section,$sha);$existing->execute();if($existing->get_result()->fetch_assoc()!==null)return ['status'=>'duplicate','revision'=>$this->revision($caseId)];
        $count=$this->db->prepare("SELECT COUNT(*) n FROM `{$this->prefix}fm2_checklist_photos` WHERE installation_case_id=? AND section_id=? AND revoked_at IS NULL");$count->bind_param('ii',$caseId,$section);$count->execute();if((int)$count->get_result()->fetch_assoc()['n']>=10)return ['status'=>'rejected','message'=>'В разделе уже 10 фотографий.'];
        $directory=$this->storageRoot.'/checklist';if(!\is_dir($directory)&&!@\mkdir($directory,0700,true)&&!\is_dir($directory))throw new PilotHttpInfrastructureUnavailable();$storage=$sha.'.bin';$path=$directory.'/'.$storage;if(!\is_file($path)){if(\file_put_contents($path,$bytes,LOCK_EX)!==$size){@\unlink($path);throw new PilotHttpInfrastructureUnavailable();}@\chmod($path,0600);}
        $s=$this->db->prepare("INSERT INTO `{$this->prefix}fm2_checklist_photos`(installation_case_id,section_id,upload_operation_id,sha256,mime_type,byte_size,original_name,storage_name,actor_user_id,device_time,server_received_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)");$actorId=$actor->id;$receivedAt=$this->now;$s->bind_param('iisssississ',$caseId,$section,$id,$sha,$mime,$size,$name,$storage,$actorId,$deviceTime,$receivedAt);$s->execute();return null;
    }
    private function revokePhoto(int $caseId,int $section,int $photoId):bool{$s=$this->db->prepare("UPDATE `{$this->prefix}fm2_checklist_photos` SET revoked_at=? WHERE id=? AND installation_case_id=? AND section_id=? AND revoked_at IS NULL");$now=$this->now;$s->bind_param('siii',$now,$photoId,$caseId,$section);$s->execute();return $s->affected_rows===1;}
    private function sectionReady(int $caseId,int $section):bool{$ids=self::SECTION_ITEMS[$section];$marks=$this->db->prepare("SELECT COUNT(DISTINCT item_id) n FROM `{$this->prefix}fm2_checklist_operations` WHERE installation_case_id=? AND operation_type='item_completed' AND item_id IN(".\implode(',',$ids).')');$marks->bind_param('i',$caseId);$marks->execute();$markCount=(int)$marks->get_result()->fetch_assoc()['n'];$photos=$this->db->prepare("SELECT COUNT(*) n FROM `{$this->prefix}fm2_checklist_photos` WHERE installation_case_id=? AND section_id=? AND revoked_at IS NULL");$photos->bind_param('ii',$caseId,$section);$photos->execute();return $markCount===\count($ids)&&(int)$photos->get_result()->fetch_assoc()['n']>0;}
    private function duplicate(string $id):?array{$s=$this->db->prepare("SELECT accepted_revision FROM `{$this->prefix}fm2_checklist_operations` WHERE client_operation_id=? LIMIT 1");$s->bind_param('s',$id);$s->execute();return $s->get_result()->fetch_assoc()?:null;}
    private function case(int $objectId,bool $lock):?array{$sql="SELECT id,process_state FROM `{$this->prefix}fm2_installation_cases` WHERE legacy_installation_object_id=? LIMIT 2".($lock?' FOR UPDATE':'');$s=$this->db->prepare($sql);$s->bind_param('i',$objectId);$s->execute();$rows=$s->get_result()->fetch_all(MYSQLI_ASSOC);return \count($rows)===1?$rows[0]:null;}
    private function revision(int $caseId,bool $lock=false):int{$this->db->query("INSERT IGNORE INTO `{$this->prefix}fm2_checklist_revisions`(installation_case_id,revision_no,updated_at) VALUES({$caseId},0,'".$this->db->real_escape_string($this->now)."')");$sql="SELECT revision_no FROM `{$this->prefix}fm2_checklist_revisions` WHERE installation_case_id=?".($lock?' FOR UPDATE':'');$s=$this->db->prepare($sql);$s->bind_param('i',$caseId);$s->execute();return (int)$s->get_result()->fetch_assoc()['revision_no'];}
    private function setRevision(int $caseId,int $revision):void{$s=$this->db->prepare("UPDATE `{$this->prefix}fm2_checklist_revisions` SET revision_no=?,updated_at=? WHERE installation_case_id=?");$now=$this->now;$s->bind_param('isi',$revision,$now,$caseId);$s->execute();}
    private static function uuid(string $v):bool{return \preg_match('/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/D',$v)===1;}
    private static function instant(string $v):bool{try{$d=new \DateTimeImmutable($v);return $v!==''&&\strlen($v)<=40&&$d->format('c')!=='';}catch(\Throwable){return false;}}
}
