<?php declare(strict_types=1);
namespace FMonitor2\PilotHttp;

final class ProductionChecklistRenderer
{
    private const SECTIONS=[
        ['id'=>1,'name'=>'Демонтаж старого оборудования','items'=>[[28,'Зачистка шахты, переделка кабины',2],[29,'Демонтаж направляющих',2],[30,'Демонтаж кронштейнов',2],[31,'Демонтаж ДШ',2],[32,'Демонтаж МП (СУ; СПЧ; ВУ)',1],[33,'Демонтаж каркаса кабины',1],[34,'Демонтаж противовеса',2],[35,'Демонтаж приямка, НУ',1],[36,'Демонтаж лебёдки, ОС',2]]],
        ['id'=>2,'name'=>'Монтаж направляющих','items'=>[[37,'Монтаж основных кронштейнов',3],[38,'Монтаж кронштейнов противовеса',3],[39,'Монтаж основных направляющих',3],[40,'Монтаж направляющих противовеса',3],[41,'Выверка направляющих, зачистка стыков',2]]],
        ['id'=>3,'name'=>'Монтаж кабины и противовеса','items'=>[[1,'Монтаж каркаса кабины',2],[2,'Монтаж противовеса',2],[3,'Загрузка противовеса',1],[4,'Сборка купе кабины',2],[5,'Установка привода и ДК',1],[6,'Монтаж буферов',1]]],
        ['id'=>4,'name'=>'Монтаж ДШ','items'=>[[7,'Сборка порталов',2],[8,'Монтаж ДШ',5],[9,'Установка фартуков',1],[10,'Монтаж вызывных постов и этажных указателей',1]]],
        ['id'=>5,'name'=>'Монтаж в МП','items'=>[[11,'Монтаж лебёдки',3],[12,'Запасовка канатов',2],[13,'Монтаж ОС; НУ (запасовка)',2],[14,'Монтаж СУЛ с ПЧ; ВУ',1],[15,'Разварка контура МП; шахты; приямка',2]]],
        ['id'=>6,'name'=>'ПНР','items'=>[[16,'Электромонтаж по шахте',4],[17,'Электроразводка по МП',4],[18,'Наладка ДШ',3],[19,'Установка шунтов и датчиков',3],[20,'Пуск лифта в «нормальную» работу',3],[21,'Диспетчеризация',2]]],
        ['id'=>7,'name'=>'Стройотделка','items'=>[[22,'Установка ОДШЛ; порогов (покраска)',3],[23,'СОР МП; шахты; приямка',2],[24,'Примыкания ДШ (в шахте)',1],[25,'Покраска сварных соединений, контура, шахты',1],[26,'Освещение МП; шахты',1],[27,'Установка противопожарных дверей; люков',1]]],
        ['id'=>8,'name'=>'Акты','items'=>[[42,'Акт ввода лифта в эксплуатацию',15]]],
    ];

    public function render(HttpUser $user,array $case,bool $roleAccess=false,array $projection=['revision'=>0,'items'=>[],'photos'=>[],'completedSections'=>[]],string $csrf='',bool $fromConstructionControl=false):string
    {
        $e=[PilotView::class,'e'];$id=(int)$case['id'];$sections='';
        foreach(self::SECTIONS as $index=>$section){$weight=\array_sum(\array_column($section['items'],2));$items='';foreach($section['items']as[$itemId,$name,$share])$items.='<div class="fm2-check-item" data-check-item="'.$itemId.'" data-weight="'.$share.'"><button class="fm2-check-toggle" type="button" role="checkbox" aria-checked="false"><span class="fm2-check-box" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="m6 12 4 4 8-9"/></svg></span><span class="fm2-check-label">'.$e($name).'<small data-item-sync>Не отмечено</small></span><span class="fm2-check-weight">+'.$share.'%</span></button><button class="fm2-item-installers" type="button" data-installer-edit><span data-installer-summary>Все монтажники объекта</span><small>Изменить исполнителей</small></button></div>';
            $sections.='<section class="fm2-check-section" data-check-section="'.$section['id'].'" data-section-weight="'.$weight.'"><button class="fm2-check-section-head fm2-section-toggle" type="button" aria-expanded="false"><span class="fm2-section-title"><strong>'.$e($section['name']).'</strong><small><span data-section-count>0 из '.\count($section['items']).'</span><span aria-hidden="true">·</span><span data-section-progress>0 из '.$weight.'%</span><span class="fm2-section-work-state" data-section-state>Не начат</span></small></span><svg class="fm2-section-chevron" viewBox="0 0 24 24" aria-hidden="true"><path d="m7 10 5 5 5-5"/></svg></button><div class="fm2-check-section-body"><div class="fm2-check-items"><button class="fm2-check-all" type="button" data-check-all><span class="fm2-check-box" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="m6 12 4 4 8-9"/></svg></span><span>Отметить все работы раздела</span></button>'.$items.'</div><div class="fm2-photo-zone"><div class="fm2-photo-copy"><strong>Фото раздела</strong><span>Минимум одно фото для завершения</span></div><div class="fm2-photo-actions"><label class="shlz-button fm2-camera-action"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 7h3l1.5-2h7L17 7h3v12H4V7Zm8 3.2a3 3 0 1 0 0 6 3 3 0 0 0 0-6Z"/></svg>Снять фото<input type="file" accept="image/*" capture="environment" data-photo-input></label><label class="fm2-file-action">Выбрать с устройства<input type="file" accept="image/jpeg,image/png,image/webp" multiple data-photo-input></label></div><div class="fm2-photo-strip" data-photo-strip><span class="fm2-photo-empty">Фотографий пока нет</span></div></div></div></section>';
        }
        $opened=(bool)($case['opened']??false);$assignedEngineerId=(int)($case['controlEngineer']['userId']??0);$available=$opened&&($assignedEngineerId===$user->id||$roleAccess);
        $gate=$available?'':($opened?'<div class="fm2-check-gate" role="status"><strong>Чек-лист доступен только уполномоченным ролям</strong><span>Отмечать работы и добавлять фото могут инженеры строительного контроля, руководители и администраторы.</span></div>':'<div class="fm2-check-gate" role="status"><strong>Чек-лист пока недоступен</strong><span>Сначала откройте монтажные работы по зарегистрированному распоряжению.</span></div>');
        $backHref=$fromConstructionControl?'/pilot/construction-control':'/pilot/objects/'.$id;$backLabel=$fromConstructionControl?'Стройконтроль':'Карточка объекта';
        $body='<div class="fm2-check-page" data-checklist data-object-id="'.$id.'" data-enabled="'.($available?'true':'false').'"><header class="fm2-check-hero"><div class="fm2-check-topline"><a class="fm2-back-link" href="'.$backHref.'"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="m15 5-7 7 7 7"/></svg>'.$backLabel.'</a><div class="fm2-sync-banner" data-sync-banner role="status"><span class="fm2-sync-dot" aria-hidden="true"></span><span data-sync-copy>Синхронизировано</span><button type="button" data-sync-now hidden>Повторить отправку</button></div></div><div class="fm2-check-object"><h1>'.$e($case['address']).', подъезд '.$e($case['entrance']).'</h1><p>Рег. № '.$e($case['registrationNumber']).'</p></div><div class="fm2-progress-summary"><strong><span data-total-progress>0</span>%</strong><span><span data-total-items>0</span> из 42 работ</span></div></header>'.$gate.'<main class="fm2-check-layout"'.($available?'':' inert').'><div class="fm2-check-content">'.$sections.'</div></main><button class="fm2-all-photos" type="button" data-open-gallery>Все фото <span data-photo-total>0</span></button><section class="fm2-gallery-page" data-gallery hidden><div class="fm2-gallery-head"><button type="button" data-close-gallery><svg viewBox="0 0 24 24" aria-hidden="true"><path d="m15 5-7 7 7 7"/></svg>К чек-листу</button><h2>Все фото</h2></div><div class="fm2-gallery-content" data-gallery-content></div></section><div class="fm2-toast" role="status" aria-live="polite" data-toast hidden></div></div>';
        $dialog='<dialog class="fm2-confirm-dialog" data-bulk-dialog aria-labelledby="fm2-bulk-title"><div class="fm2-confirm-dialog__content"><h2 id="fm2-bulk-title">Отметить весь раздел?</h2><p>Все невыполненные работы в разделе <strong data-bulk-section-name></strong> будут отмечены за всеми монтажниками объекта.</p><div class="fm2-confirm-dialog__actions"><button class="shlz-button" type="button" data-bulk-cancel>Отмена</button><button class="shlz-button shlz-button--primary" type="button" data-bulk-confirm>Отметить все</button></div></div></dialog><dialog class="fm2-installer-dialog" data-installer-dialog aria-labelledby="fm2-installer-title"><div class="fm2-installer-dialog__surface"><header><div><h2 id="fm2-installer-title">Исполнители работы</h2><p data-installer-item-name></p></div><button type="button" data-installer-cancel aria-label="Закрыть">×</button></header><div class="fm2-installer-dialog__body"><p class="fm2-installer-help">По умолчанию выбраны все закреплённые монтажники. Оставьте только тех, кто фактически выполнил эту работу.</p><div data-installer-options></div><p class="fm2-installer-error" data-installer-error hidden>Выберите хотя бы одного монтажника.</p></div><footer><button class="shlz-button" type="button" data-installer-cancel>Отмена</button><button class="shlz-button shlz-button--primary" type="button" data-installer-save>Сохранить состав</button></footer></div></dialog>';
        $body=\str_replace('<div class="fm2-toast"',$dialog.'<div class="fm2-toast"',$body);
        $projectionJson=\base64_encode(\json_encode($projection,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR));
        $body=\str_replace(' data-enabled=',' data-user-id="'.$user->id.'" data-csrf="'.$e($csrf).'" data-projection="'.$e($projectionJson).'" data-enabled=',$body);
        $links=$fromConstructionControl?[['Стройконтроль','/pilot/construction-control']]:[['Объекты монтажа','/pilot/objects'],['Объект № '.$id,'/pilot/objects/'.$id]];$document=PilotView::document($user,'Чек-лист объекта № '.$id,$fromConstructionControl?'Стройконтроль':'Объекты монтажа',PilotView::breadcrumb($links,'Чек-лист'),$body);
        return \str_replace('</body>','<script src="/pilot/assets/checklist.js?v=20260829-18" defer></script></body>',$document);
    }
}
