<?php declare(strict_types=1);
namespace FMonitor2\PilotHttp;

final class ProductionChecklistRenderer
{
    private const SECTIONS=[
        ['id'=>1,'name'=>'Демонтаж старого оборудования','items'=>[[28,'Зачистка шахты, переделка кабины',2],[29,'Демонтаж направляющих',2],[30,'Демонтаж кронштейнов',2],[31,'Демонтаж ДШ',2],[32,'Демонтаж МП (СУ; СПЧ; ВУ)',1],[33,'Демонтаж каркаса кабины',1],[34,'Демонтаж противовеса',2],[35,'Демонтаж приямка, НУ',1],[36,'Демонтаж лебёдки, ОС',2]]],
        ['id'=>2,'name'=>'Монтаж направляющих','items'=>[[37,'Монтаж основных кронштейнов',3],[38,'Монтаж кронштейнов противовеса',3],[39,'Монтаж основных направляющих',3],[40,'Монтаж направляющих противовеса',3],[41,'Выверка направляющих, зачистка стыков',2]]],
        ['id'=>3,'name'=>'Монтаж кабины и противовеса','items'=>[[1,'Монтаж каркаса кабины',2],[2,'Монтаж противовеса',2],[3,'Загрузка противовеса',1],[4,'Сборка купе кабины',2],[5,'Установка привода и ДК',1],[6,'Монтаж буферов',1]]],
        ['id'=>4,'name'=>'Монтаж ДШ','items'=>[[7,'Сборка порталов',2],[8,'Монтаж ДШ',5],[9,'Установка фартуков',1],[10,'Монтаж вызывных постов и этажных указателей',1]]],
        ['id'=>5,'name'=>'Монтаж в МП','items'=>[[11,'Монтаж лебёдки',3],[12,'Запасовка канатов',2],[13,'Монтаж ОС; НУ (запасовка)',2],[14,'Монтаж СУЛ с ПЧ; ВУ',1],[15,'Разварка контура МП; шахты; приямка',2]]],
        ['id'=>6,'name'=>'ПНР','items'=>[[16,'Электромонтаж по шахте',4],[17,'Электроразводка по МП',4],[18,'Наладка ДШ',3],[19,'Установка шунтов и датчиков',3],[20,'Пуск лифта в «нормальную» работу',3],[21,'Диспетчеризация',2]]],
        ['id'=>7,'name'=>'Стройотделка','items'=>[[22,'Установка ОДШЛ; порогов (покраска)',3],[23,'СОР МП; шахты; приямка',2],[24,'Примыкания ДШ (в шахте)',1],[25,'Покраска сварных соединений, контура, шахты',1],[26,'Освещение МП; шахты',1],[27,'Установка противопожарных дверей; люков',1]]],
        ['id'=>8,'name'=>'Акты','items'=>[[42,'Акт ввода лифта в эксплуатацию',15]]],
    ];

    public function render(HttpUser $user,array $case,bool $roleAccess=false,array $projection=['revision'=>0,'items'=>[],'photos'=>[],'completedSections'=>[]],string $csrf=''):string
    {
        $e=[PilotView::class,'e'];$id=(int)$case['id'];$sections='';
        foreach(self::SECTIONS as $index=>$section){$weight=\array_sum(\array_column($section['items'],2));$items='';foreach($section['items']as[$itemId,$name,$share])$items.='<button class="fm2-check-item" type="button" role="checkbox" aria-checked="false" data-check-item="'.$itemId.'" data-weight="'.$share.'"><span class="fm2-check-box" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="m6 12 4 4 8-9"/></svg></span><span class="fm2-check-label">'.$e($name).'<small data-item-sync>Не отмечено</small></span><span class="fm2-check-weight">+'.$share.'%</span></button>';
            $sections.='<section class="fm2-check-section'.($index===0?' is-open':'').'" data-check-section="'.$section['id'].'" data-section-weight="'.$weight.'"><button class="fm2-check-section-head" type="button" aria-expanded="'.($index===0?'true':'false').'"><span class="fm2-section-sequence">'.($index+1).'</span><span class="fm2-section-title"><strong>'.$e($section['name']).'</strong><small><span data-section-count>0 из '.\count($section['items']).'</span> · <span data-section-progress>0 из '.$weight.'%</span></small></span><span class="fm2-section-state" data-section-state>Не начат</span><svg class="fm2-section-chevron" viewBox="0 0 24 24" aria-hidden="true"><path d="m7 10 5 5 5-5"/></svg></button><div class="fm2-check-section-body"><div class="fm2-check-items">'.$items.'</div><div class="fm2-photo-zone"><div class="fm2-photo-copy"><strong>Фото раздела</strong><span>Минимум одно фото для завершения</span></div><div class="fm2-photo-actions"><label class="shlz-button fm2-camera-action"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 7h3l1.5-2h7L17 7h3v12H4V7Zm8 3.2a3 3 0 1 0 0 6 3 3 0 0 0 0-6Z"/></svg>Снять фото<input type="file" accept="image/*" capture="environment" data-photo-input></label><label class="fm2-file-action">Выбрать с устройства<input type="file" accept="image/jpeg,image/png,image/webp" multiple data-photo-input></label></div><div class="fm2-photo-strip" data-photo-strip><span class="fm2-photo-empty">Фотографий пока нет</span></div></div><button class="shlz-button shlz-button--primary fm2-complete-section" type="button" disabled data-complete-section>Завершить раздел</button></div></section>';
        }
        $opened=(bool)($case['opened']??false);$assignedEngineerId=(int)($case['controlEngineer']['userId']??0);$available=$opened&&($assignedEngineerId===$user->id||$roleAccess);
        $gate=$available?'':($opened?'<div class="fm2-check-gate" role="status"><strong>Чек-лист доступен только уполномоченным ролям</strong><span>Отмечать работы и добавлять фото могут инженеры строительного контроля, руководители и администраторы.</span></div>':'<div class="fm2-check-gate" role="status"><strong>Чек-лист пока недоступен</strong><span>Сначала откройте монтажные работы по зарегистрированному распоряжению.</span></div>');
        $body='<div class="fm2-check-page" data-checklist data-object-id="'.$id.'" data-enabled="'.($available?'true':'false').'"><header class="fm2-check-hero"><div class="fm2-check-object"><a class="fm2-back-link" href="/pilot/objects/'.$id.'"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="m15 5-7 7 7 7"/></svg>Карточка объекта</a><h1>'.$e($case['address']).', подъезд '.$e($case['entrance']).'</h1><p>Рег. № '.$e($case['registrationNumber']).'</p></div><div class="fm2-progress-summary"><strong><span data-total-progress>0</span>%</strong><span><span data-total-items>0</span> из 42 работ</span></div></header><div class="fm2-sync-banner" data-sync-banner role="status"><span class="fm2-sync-dot" aria-hidden="true"></span><span data-sync-copy>Синхронизировано</span><button type="button" data-sync-now hidden>Повторить отправку</button></div>'.$gate.'<main class="fm2-check-layout"'.($available?'':' inert').'><div class="fm2-check-content">'.$sections.'</div></main><div class="fm2-toast" role="status" aria-live="polite" data-toast hidden></div></div>';
        $projectionJson=\base64_encode(\json_encode($projection,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR));
        $body=\str_replace(' data-enabled=',' data-user-id="'.$user->id.'" data-csrf="'.$e($csrf).'" data-projection="'.$e($projectionJson).'" data-enabled=',$body);
        $document=PilotView::document($user,'Чек-лист объекта № '.$id,'Объекты монтажа',PilotView::breadcrumb([['Объекты монтажа','/pilot/objects'],['Объект № '.$id,'/pilot/objects/'.$id]],'Чек-лист'),$body);
        return \str_replace('</body>','<script src="/pilot/assets/checklist.js" defer></script></body>',$document);
    }
}
