<?php
declare(strict_types=1);
namespace FMonitor2\PilotHttp;
require_once __DIR__.'/PilotView.php';
final class FreshOrderSelectionView
{
 public static function path(int$id):string{return'/pilot/objects/'.$id.'/assignment-order/selection';}
 public static function hidden(array$fields):string{$html='';foreach($fields as$name=>$value)foreach(is_array($value)?$value:[$value]as$item){$key=$name.(is_array($value)?'[]':'');$html.='<input type="hidden" name="'.PilotView::e($key).'" value="'.PilotView::e($item).'">';}return$html;}
 public static function render(HttpUser$user,array$m,string$csrf):string
 {
  $e=PilotView::e(...);$id=(int)$m['objectId'];$path=self::path($id);$latest=$m['latest'];$object=$m['object'];$b=random_bytes(16);$b[6]=chr((ord($b[6])&15)|64);$b[8]=chr((ord($b[8])&63)|128);$h=bin2hex($b);$request=substr($h,0,8).'-'.substr($h,8,4).'-'.substr($h,12,4).'-'.substr($h,16,4).'-'.substr($h,20);$pending=$latest!==null&&!$latest['hasAcceptedOriginal'];$selected=$latest['installers']??[];$engineer=$latest['engineer']['userId']??null;
  $summary='<div class="fm2-order-object"><strong>Объект монтажа № '.$id.'</strong><span>'.$e($object['objectRegistrationNumber']).' · '.$e($object['address']).', подъезд '.$e($object['entrance']).'</span><small>Плановый период: '.$e($object['plannedStartDate']).' — '.$e($object['plannedFinishDate']).'</small></div>';
  $chips='';foreach($selected as$w)$chips.='<span class="fm2-picker-chip" data-selected-installer data-tab-id="'.$e($w['tabId']).'" data-full-name="'.$e($w['fullName']).'" data-position="'.$e($w['position']).'" data-source="'.$e($w['source']??'').'" data-updated-at="'.$e($w['updatedAt']??'').'"><span>'.$e($w['fullName']).'</span><small>№ '.$e(str_pad((string)$w['tabId'],6,'0',STR_PAD_LEFT)).'</small><button type="button" data-remove-installer aria-label="Убрать '.$e($w['fullName']).'"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="m7 7 10 10M17 7 7 17"/></svg></button><input type="hidden" name="installerTabIds[]" value="'.$e($w['tabId']).'"></span>';if($chips==='')$chips='<span class="fm2-picker-selection-empty" data-selection-empty>Монтажники ещё не выбраны</span>';
  $current='';if($latest!==null){$current='<div class="fm2-order-current"><div><strong>Текущий состав · версия '.$e($latest['version']).'</strong><span>'.$e(implode(', ',array_column($latest['installers'],'fullName'))).'</span><small>Инженер: '.$e($latest['engineer']['fullName']).' · '.($pending?'Ожидается подписанный оригинал':'Подписанный оригинал принят').'</small></div>';if(isset($m['originalSubmission']))$current.='<a class="shlz-link" href="'.OriginalUploadView::path($id,$latest['orderId']).'/submit">'.($m['originalSubmission']['mode']==='initial'?'Загрузить оригинал':'Исправить оригинал').'</a>';$current.='</div>';}
  $engineers='';foreach($m['engineers']as$c)$engineers.='<label class="shlz-choice fm2-engineer-choice"><input class="shlz-radio" type="radio" name="controlEngineerUserId" value="'.$e($c['userId']).'"'.($c['userId']===$engineer?' checked':'').' required><span>'.$e($c['fullName']).' · '.$e($c['position']).'</span></label>';if($engineers==='')$engineers='<div class="shlz-empty-state"><p>Нет доступных инженеров строительного контроля.</p></div>';
  $template=$latest===null?'':'<form id="fresh-template-form" method="post" action="/pilot/objects/'.$id.'/assignment-orders/'.$latest['orderId'].'/template" target="_blank">'.self::hidden(['csrfToken'=>$csrf]).'</form>';$lastTemplate=$latest!==null&&($m['lastTemplateDate']??null)!==null?'<small>Последний шаблон: <time datetime="'.$e($m['lastTemplateDate']).'">'.$e($m['lastTemplateDate']).'</time></small>':'';$helper='<aside class="fm2-order-helper"><div class="fm2-order-helper-icon" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="M7 3h7l4 4v14H7V3Zm7 0v5h4M10 13h5m-5 4h5"/></svg></div><div><h2>Нужен шаблон?</h2><p>'.($latest===null?'Сначала сохраните состав. После этого PDF-шаблон можно сформировать отдельно.':'Сформируем PDF с текущим составом. Это необязательный шаг.').'</p>'.$lastTemplate.'</div>'.($latest===null?'':'<button class="shlz-button" type="submit" form="fresh-template-form">Сформировать шаблон</button>').'</aside>';
  $dialog='<dialog class="shlz-modal fm2-selection-modal" data-installer-dialog aria-labelledby="installer-dialog-title"><div class="shlz-modal__surface"><header class="shlz-modal__header"><div><h2 class="shlz-modal__title" id="installer-dialog-title">Выбор монтажников</h2><p>Поиск по ФИО или табельному номеру</p></div><button class="shlz-modal__close" type="button" data-dialog-close aria-label="Закрыть"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="m7 7 10 10M17 7 7 17"/></svg></button></header><div class="shlz-modal__body"><div class="fm2-picker-modal-selection"><strong data-picker-count>Выбрано: '.count($selected).'</strong><div class="fm2-picker-selection" data-modal-selection></div></div><label class="fm2-search-field"><span>Поиск монтажника</span><input class="shlz-input" type="search" data-picker-search data-installer-search placeholder="Введите минимум 2 символа" autocomplete="off"></label><p class="fm2-picker-result-meta" data-installer-status aria-live="polite">Введите минимум 2 символа</p><div class="fm2-picker-results" data-installer-results></div><button class="shlz-button" type="button" data-installer-more hidden>Показать ещё</button></div><footer class="shlz-modal__footer"><button class="shlz-button shlz-button--primary" type="button" data-dialog-apply>Готово</button></footer></div></dialog>';
  $body='<div class="fm2-page-header fm2-order-heading"><div><h1>'.($pending?'Изменить состав распоряжения':'Выбрать состав распоряжения').'</h1><p>Укажите монтажников и подтвердите инженера строительного контроля.</p></div></div>'.$template.'<form id="form-errors" class="fm2-order-form" method="post" action="'.$path.'" data-selection-picker data-search-url="/pilot/objects/'.$id.'/assignment-order/installers">'.self::hidden(['csrfToken'=>$csrf,'requestId'=>$request,'mode'=>$pending?'replace_pending':'new_order','expectedSelectionRevision'=>$m['selectionRevision']]).'<fieldset class="fm2-order-surface"><header>'.$summary.'</header>'.$current.'<section class="fm2-order-team" aria-labelledby="installers"><div class="fm2-order-section-head"><div><h2 id="installers">Монтажники</h2><p>Найдите сотрудников кадрового каталога и добавьте их в состав.</p></div></div><div class="fm2-order-selection"><div class="fm2-picker-selection" data-main-selection aria-live="polite">'.$chips.'</div><button class="shlz-button shlz-button--primary" type="button" data-dialog-open>Выбрать монтажников</button></div></section><aside class="fm2-order-engineer"><div><span>Инженер строительного контроля</span><small>Выберите одного ответственного и подтвердите выбор</small></div><div><fieldset>'.$engineers.'</fieldset><label class="shlz-choice fm2-engineer-confirmation"><input class="shlz-checkbox" type="checkbox" name="controlEngineerConfirmed" value="yes" required><span>Подтверждаю выбор инженера</span></label></div></aside><footer class="fm2-order-actions"><a class="shlz-link" href="/pilot/objects/'.$id.'">Отмена</a><button class="shlz-button shlz-button--primary" type="submit">'.($pending?'Заменить ожидающий состав':'Сохранить состав').'</button></footer></fieldset>'.$helper.$dialog.'</form><p class="fm2-order-followup"><a class="shlz-link" href="/pilot/objects/'.$id.'/execution">Применение состава и открытие работ</a></p><script src="/pilot/assets/selection-picker.js" defer></script>';
  return PilotView::document($user,'Выбор состава','Объекты монтажа',PilotView::breadcrumb([['Объекты монтажа','/pilot/objects'],['Объект монтажа № '.$id,'/pilot/objects/'.$id]],'Распоряжение'),$body);
 }
 public static function error(string$reason,int$object,?array$retry=null):string{$messages=['csrf_invalid'=>'Срок действия формы истёк. Откройте её заново.','authorization_denied'=>'Недостаточно полномочий для выбора состава.','installer_required'=>'Выберите хотя бы одного монтажника.','control_engineer_required'=>'Выберите инженера строительного контроля.','confirmation_required'=>'Подтвердите выбор инженера строительного контроля.','installer_not_in_catalog'=>'Монтажник отсутствует в кадровом каталоге.','installer_not_employed'=>'Монтажник недоступен по кадровым данным.','control_engineer_not_eligible'=>'Выбранный инженер недоступен.','stale_selection'=>'Состав уже изменился. Откройте актуальную форму.','target_not_current'=>'Это распоряжение уже заменено.','request_id_conflict'=>'Этот запрос уже использован для другого выбора. Откройте форму заново.','dependency_unavailable'=>'Данные временно недоступны. Повторите запрос позже.','object_not_found'=>'Объект монтажа не найден.','order_not_found'=>'Распоряжение не найдено.','no_changes'=>'Состав не изменился.','object_has_pto_act'=>'По объекту уже зарегистрирован Акт ПТО.','object_completed'=>'Работы по объекту завершены.','pending_selection_exists'=>'Сначала замените ожидающий оригинала состав.','original_already_accepted'=>'Оригинал уже принят. Создайте новое распоряжение.','request_too_large'=>'Форма превышает допустимый размер.','unsupported_media'=>'Неподдерживаемый формат формы.'];$message=$messages[$reason]??'Не удалось выполнить действие. Проверьте форму или повторите запрос позже.';$html='<!doctype html><html lang="ru"><head><meta charset="utf-8"><title>Распоряжение — FMonitor</title><link rel="stylesheet" href="/pilot/assets/shlz.css"><link rel="stylesheet" href="/pilot/assets/pilot.css"></head><body class="shlz-scope"><main class="fm2-main"><p role="alert" data-error-code="'.PilotView::e($reason).'">'.PilotView::e($message).'</p>';if($retry!==null)$html.='<form method="post" action="'.self::path($object).'">'.self::hidden($retry).'<button class="shlz-button shlz-button--primary" type="submit">Повторить запрос</button></form>';return$html.'<a class="shlz-link" href="'.self::path($object).'">Вернуться к форме</a></main></body></html>';}
}
