<?php declare(strict_types=1);
namespace FMonitor2\PilotHttp;
final class MariaDbInstallerDirectoryReader
{
 public function __construct(private readonly \mysqli $db,private readonly string $p,private readonly string $l){}
 public function read(string $day):array
 {
  try{$catalog=$this->db->query("SELECT installer_tab_id,fio,position,employment_status,workforce_source_updated_at,dismissal_effective_at FROM `{$this->p}fm2_workforce_catalog` WHERE reconciliation_state='delivered' ORDER BY fio,installer_tab_id LIMIT 5001")->fetch_all(MYSQLI_ASSOC);if(count($catalog)>5000)throw new PilotHttpInfrastructureUnavailable();$d=$this->db->real_escape_string($day);$rows=$this->db->query("SELECT oi.installer_tab_id,o.registration_number,c.legacy_installation_object_id,l.regnumber,l.ordadr_address FROM `{$this->p}fm2_order_installers` oi JOIN `{$this->p}fm2_assignment_orders` o ON o.id=oi.assignment_order_id JOIN `{$this->p}fm2_installation_cases` c ON c.id=o.installation_case_id JOIN `{$this->l}fm_maintable` l ON l.id=c.legacy_installation_object_id WHERE o.status='registered' AND o.version_no=(SELECT MAX(x.version_no) FROM `{$this->p}fm2_assignment_orders` x WHERE x.installation_case_id=o.installation_case_id) AND oi.change_action<>'release' AND oi.valid_from<='{$d}' AND (oi.valid_to IS NULL OR oi.valid_to>='{$d}') ORDER BY oi.valid_from,c.legacy_installation_object_id")->fetch_all(MYSQLI_ASSOC);}catch(PilotHttpInfrastructureUnavailable $e){throw$e;}catch(\Throwable $e){throw new PilotHttpInfrastructureUnavailable('',0,$e);}
  $by=[];foreach($rows as$r){$tab=self::id($r['installer_tab_id']);$object=self::id($r['legacy_installation_object_id']);if($tab===null||$object===null)throw new PilotHttpInfrastructureUnavailable();$by[$tab][]=['objectId'=>$object,'registrationNumber'=>self::text($r['regnumber']),'address'=>self::text($r['ordadr_address']),'orderNumber'=>self::text($r['registration_number'])];}
  $out=[];$seen=[];foreach($catalog as$r){$tab=self::id($r['installer_tab_id']);$status=$r['employment_status'];if($tab===null||isset($seen[$tab])||!in_array($status,['employed','dismissed'],true))throw new PilotHttpInfrastructureUnavailable();$seen[$tab]=true;$out[]=['tabId'=>$tab,'fullName'=>self::text($r['fio']),'position'=>self::text($r['position']),'status'=>$status,'updatedAt'=>self::time($r['workforce_source_updated_at']),'dismissalEffectiveAt'=>$r['dismissal_effective_at']===null?null:self::date($r['dismissal_effective_at']),'assignments'=>$by[$tab]??[]];}return$out;
 }
 private static function text(mixed$v):string{$v=trim((string)$v);if($v==='')throw new PilotHttpInfrastructureUnavailable();return$v;}private static function id(mixed$v):?int{$x=filter_var($v,FILTER_VALIDATE_INT,['options'=>['min_range'=>1]]);return$x===false?null:$x;}private static function date(mixed$v):string{$v=(string)$v;if(preg_match('/^(\d{4})-(\d{2})-(\d{2})$/D',$v,$m)!==1||!checkdate((int)$m[2],(int)$m[3],(int)$m[1]))throw new PilotHttpInfrastructureUnavailable();return$v;}private static function time(mixed$v):string{$v=(string)$v;try{new \DateTimeImmutable($v);}catch(\Throwable){throw new PilotHttpInfrastructureUnavailable();}return$v;}
}
final class ProductionInstallerDirectoryRenderer
{
 public function render(HttpUser$user,array$all):string
 {
  $e=[PilotView::class,'e'];$working=count(array_filter($all,fn($x)=>$x['status']==='employed'));$body='<div class="fm2-page-header"><div><h1>Монтажники</h1><p>Кадровый статус, актуальные закрепления и источник данных</p></div><span class="fm2-result-count">'.count($all).' сотрудников</span></div><section class="fm2-directory-summary"><div><strong>'.count($all).'</strong><span>Всего</span></div><div><strong>'.$working.'</strong><span>Работают</span></div><div><strong>'.(count($all)-$working).'</strong><span>Уволены</span></div><p><b>Источник:</b> 1С ЗУП → Битрикс<br><span>Полный последний доставленный снимок</span></p></section>';
  if($all===[])$body.='<section class="shlz-empty-state fm2-empty"><strong>Каталог монтажников пока не загружен</strong></section>';else{$rows='';foreach($all as$x){$active=$x['status']==='employed';$links='';foreach($x['assignments']as$a)$links.='<a class="shlz-link fm2-assignment-link" href="/pilot/objects/'.$e($a['objectId']).'"><strong>'.$e($a['registrationNumber']).'</strong><span>'.$e($a['address']).' · № '.$e($a['orderNumber']).'</span></a>';if($links==='')$links='<span class="fm2-assignment-empty">Нет действующих закреплений</span>';$rows.='<tr><td data-label="Монтажник"><span class="fm2-installer-person"><span class="fm2-person-mark">'.PilotView::initials($x['fullName']).'</span><span><strong>'.$e($x['fullName']).'</strong><small>таб. '.$e($x['tabId']).'</small></span></span></td><td data-label="Статус"><span class="fm2-employment fm2-employment--'.($active?'active':'dismissed').'">'.($active?'Работает':'Уволен').'</span>'.(!$active&&$x['dismissalEffectiveAt']===null?'<small>Дата увольнения не передана</small>':'').'</td><td data-label="Должность">'.$e($x['position']).'</td><td data-label="Закрепления"><span class="fm2-assignment-stack">'.$links.'</span></td><td data-label="Обновлено"><time>'.$e((new \DateTimeImmutable($x['updatedAt']))->format('d.m.Y H:i')).'</time><small>1С ЗУП → Битрикс</small></td></tr>';}$body.='<section class="fm2-list-surface"><div class="fm2-installer-table-scroll"><table class="shlz-table fm2-installer-table"><thead><tr><th>Монтажник</th><th>Статус</th><th>Должность</th><th>Действующие закрепления</th><th>Обновлено</th></tr></thead><tbody>'.$rows.'</tbody></table></div><footer class="fm2-table-footer"><span>Показано '.count($all).' из '.count($all).'</span><span>Актуальный снимок</span></footer></section>';}
  return PilotView::document($user,'Монтажники','Монтажники','',$body);
 }
}
