<?php declare(strict_types=1);
namespace FMonitor2\PilotHttp;

final class MariaDbInstallerDirectoryReader
{
    public function __construct(private readonly \mysqli $db,private readonly string $processPrefix,private readonly string $legacyPrefix){}
    public function read(string $processDate):array
    {
        try{$catalog=$this->db->query("SELECT installer_tab_id,fio,position,employment_status,workforce_source,workforce_source_updated_at,dismissal_effective_at,first_observed_dismissed_at FROM `{$this->processPrefix}fm2_workforce_catalog` ORDER BY fio,installer_tab_id LIMIT 2001")->fetch_all(MYSQLI_ASSOC);if(count($catalog)>2000)throw new PilotHttpInfrastructureUnavailable();$date=$this->db->real_escape_string($processDate);$assignmentRows=$this->db->query("SELECT oi.installer_tab_id,oi.valid_from,oi.valid_to,o.registration_number,c.legacy_installation_object_id,l.regnumber,l.ordadr_address,l.entrance FROM `{$this->processPrefix}fm2_order_installers` oi JOIN `{$this->processPrefix}fm2_assignment_orders` o ON o.id=oi.assignment_order_id JOIN `{$this->processPrefix}fm2_installation_cases` c ON c.id=o.installation_case_id JOIN `{$this->legacyPrefix}fm_maintable` l ON l.id=c.legacy_installation_object_id WHERE o.status='registered' AND o.version_no=(SELECT MAX(current.version_no) FROM `{$this->processPrefix}fm2_assignment_orders` current WHERE current.installation_case_id=o.installation_case_id) AND oi.change_action<>'release' AND oi.valid_from<='{$date}' AND (oi.valid_to IS NULL OR oi.valid_to>='{$date}') ORDER BY oi.valid_from,c.legacy_installation_object_id")->fetch_all(MYSQLI_ASSOC);}catch(PilotHttpInfrastructureUnavailable $e){throw $e;}catch(\Throwable $e){throw new PilotHttpInfrastructureUnavailable('',0,$e);}
        $assignments=[];foreach($assignmentRows as$row){$tab=self::id($row['installer_tab_id']);$object=self::id($row['legacy_installation_object_id']);if($tab===null||$object===null)throw new PilotHttpInfrastructureUnavailable();$assignments[$tab][]=['objectId'=>$object,'registrationNumber'=>self::text($row['regnumber']),'address'=>self::text($row['ordadr_address']),'entrance'=>self::text($row['entrance']),'validFrom'=>self::date($row['valid_from']),'validTo'=>$row['valid_to']===null?null:self::date($row['valid_to']),'orderNumber'=>self::text($row['registration_number'])];}
        $result=[];$seen=[];foreach($catalog as$row){$tab=self::id($row['installer_tab_id']);$status=$row['employment_status'];if($tab===null||isset($seen[$tab])||!in_array($status,['employed','dismissed'],true))throw new PilotHttpInfrastructureUnavailable();$seen[$tab]=true;$result[]=['tabId'=>$tab,'fullName'=>self::text($row['fio']),'position'=>self::text($row['position']),'status'=>$status,'source'=>self::text($row['workforce_source']),'updatedAt'=>self::time($row['workforce_source_updated_at']),'dismissalEffectiveAt'=>$row['dismissal_effective_at']===null?null:self::date($row['dismissal_effective_at']),'assignments'=>$assignments[$tab]??[]];}return$result;
    }
    private static function text(mixed $v):string{$v=trim((string)$v);if($v==='')throw new PilotHttpInfrastructureUnavailable();return$v;}
    private static function id(mixed $v):?int{$x=filter_var($v,FILTER_VALIDATE_INT,['options'=>['min_range'=>1]]);return$x===false?null:$x;}
    private static function date(mixed $v):string{$v=(string)$v;if(preg_match('/^(\d{4})-(\d{2})-(\d{2})$/D',$v,$m)!==1||!checkdate((int)$m[2],(int)$m[3],(int)$m[1]))throw new PilotHttpInfrastructureUnavailable();return$v;}
    private static function time(mixed $v):string{$v=(string)$v;try{new \DateTimeImmutable($v);}catch(\Throwable){throw new PilotHttpInfrastructureUnavailable();}return$v;}
}

final class ProductionInstallerDirectoryRenderer
{
    public function render(HttpUser $user,array $installers):string
    {
        $e=[PilotView::class,'e'];$employed=count(array_filter($installers,static fn($x)=>$x['status']==='employed'));$dismissed=count($installers)-$employed;$body='<div class="fm2-page-header"><div><h1>Монтажники</h1><p>Кадровый статус, актуальные закрепления и источник данных</p></div><span class="fm2-result-count">'.count($installers).' сотрудников</span></div><section class="fm2-directory-summary" aria-label="Сводка каталога"><div><strong>'.count($installers).'</strong><span>Всего</span></div><div><strong>'.$employed.'</strong><span>Работают</span></div><div><strong>'.$dismissed.'</strong><span>Уволены</span></div><p><b>Источник:</b> 1С ЗУП → Битрикс<br><span>Показан последний доставленный кадровый снимок</span></p></section>';
        if($installers===[])$body.='<section class="shlz-empty-state fm2-empty"><strong>Каталог монтажников пока не загружен</strong><p>Запустите локальный read-only импорт кадрового снимка.</p></section>';else{$cards='';foreach($installers as$x){$working=$x['status']==='employed';$source=$x['source']==='one_c_zup_via_bitrix'?'1С ЗУП → Битрикс':$x['source'];$updated=(new \DateTimeImmutable($x['updatedAt']))->setTimezone(new \DateTimeZone('Europe/Moscow'))->format('d.m.Y H:i');$items='';foreach($x['assignments']as$a)$items.='<li><a class="shlz-link" href="/pilot/objects/'.$e($a['objectId']).'"><strong>'.$e($a['registrationNumber']).'</strong> · '.$e($a['address']).', подъезд '.$e($a['entrance']).'</a><span>Распоряжение № '.$e($a['orderNumber']).' · с '.PilotView::date($a['validFrom']).($a['validTo']===null?'':' по '.PilotView::date($a['validTo'])).'</span></li>';if($items==='')$items='<li class="fm2-assignment-empty">Нет действующих закреплений</li>';$dismissal=!$working?'<p class="fm2-dismissal-note">'.($x['dismissalEffectiveAt']===null?'Фактическая дата увольнения источником не передана':'Уволен с '.PilotView::date($x['dismissalEffectiveAt'])).'</p>':'';$cards.='<article class="fm2-installer-card"><header><span class="fm2-person-mark" aria-hidden="true">'.PilotView::initials($x['fullName']).'</span><div><h2 class="fm2-db-text">'.$e($x['fullName']).'</h2><p>таб. '.$e($x['tabId']).' · <span class="fm2-db-text">'.$e($x['position']).'</span></p></div><span class="fm2-employment fm2-employment--'.($working?'active':'dismissed').'">'.($working?'Работает':'Уволен').'</span></header>'.$dismissal.'<div class="fm2-installer-meta"><span>Источник <b>'.$e($source).'</b></span><span>Снимок обновлён <time datetime="'.$e($x['updatedAt']).'">'.$updated.'</time></span></div><section><h3>Действующие закрепления</h3><ul>'.$items.'</ul></section></article>';}$body.='<div class="fm2-installer-grid">'.$cards.'</div>';}
        return PilotView::document($user,'Монтажники','Монтажники','',$body);
    }
}
