<?php declare(strict_types=1);
namespace FMonitor2\PilotHttp;

final class ProductionObjectCardRenderer implements ObjectCardRenderer,CompatibilityObjectCardRenderer
{
    public function render(HttpUser $user,array $c):string
    {
        $e=[PilotView::class,'e'];$id=$e($c['id']);$order=$c['order'];$date=static fn(mixed $value):string=>'<time datetime="'.$e($value).'">'.PilotView::date($value).'</time>';
        $notice=isset($c['flash'])&&$c['flash']?'<div class="fm2-alert" role="status">'.$e($c['flash']['message']).'</div>':'';
        [$command,$downloads]=$this->command($c,$id,$order);
        $actualStart=($c['actualStartDateUnknownAtCutover']??false)?'Фактическая дата начала неизвестна на момент cutover':($c['actualStartDate']?$date($c['actualStartDate']):'Не зафиксировано');
        $dates=$this->panel('Сроки работ',PilotView::dl([['Плановое начало',$c['plannedStartDate']?$date($c['plannedStartDate']):'Неизвестно на момент cutover'],['Плановое окончание',$c['plannedFinishDate']?$date($c['plannedFinishDate']):'Неизвестно на момент cutover'],['Фактическое начало',$actualStart]]));
        $hasSignedOriginal=$order!==null&&count(array_filter($order['artifacts']??[],static fn(array $a):bool=>($a['type']??null)==='signed_original'))===1;
        $docs=$this->panel('Распоряжение',$order===null?'<div class="fm2-quiet-empty"><strong>Распоряжение не сформировано</strong><span>Шаблон появится после выбора монтажников.</span></div>':PilotView::dl([['Дата распоряжения',PilotView::date($order['orderDate'])],['Версия',$e($order['version'])],['Подписанный оригинал',$hasSignedOriginal?'Загружен':'Ожидается']]).$downloads);
        $engineer=$c['controlEngineer']??null;$engineerValue=$engineer===null?'Не назначен':$e($engineer['fullName']).' · '.$e($engineer['position']);$engineerForm='';if($c['canAssignEngineer']??false){$options='<option value="">Выберите пользователя</option>';foreach($c['engineers']as$x)$options.='<option value="'.$e($x['userId']).'"'.(($engineer['userId']??null)===$x['userId']?' selected':'').'>'.$e($x['fullName']).'</option>';$engineerForm='<form class="fm2-engineer-form" method="post" action="/pilot/objects/'.$id.'/control-engineer"><input type="hidden" name="csrfToken" value="'.$e($c['csrfToken']).'"><input type="hidden" name="processRevision" value="'.$e($c['processRevision']).'"><label class="shlz-field shlz-field--select"><span class="shlz-field__label">Инженер строительного контроля</span><span class="shlz-field__control"><select class="shlz-select" name="controlEngineerUserId" required>'.$options.'</select></span></label><button class="shlz-button shlz-button--primary" type="submit">Назначить</button><small>Доступны активные пользователи с ролью «Строительный контроль».</small></form>';}$teamRows=[['Инженер стройконтроля',$engineerValue]];if($order===null)$teamRows[]=['Монтажники','Ещё не назначены'];else foreach($order['installers']as$x)$teamRows[]=['Монтажник',$e($x['fullName']).' · таб. '.$e($x['tabId']).' · '.$e($x['position'])];$team=$this->panel('Команда объекта',PilotView::dl($teamRows).$engineerForm);
        $eventLabels=['assignment_order_prepared'=>'Шаблон распоряжения сформирован','assignment_order_registered'=>'Распоряжение зарегистрировано в 1С ДО','assignment_order_signed_original_uploaded'=>'Подписанный оригинал загружен','assignment_order_prepare_rejected'=>'Формирование распоряжения отклонено','installation_opened'=>'Монтажные работы открыты','control_engineer_changed'=>'Инженер стройконтроля изменён'];
        $history='<div class="fm2-event-list">';if($c['events']===[])$history.='<div class="fm2-quiet-empty"><strong>Событий пока нет</strong><span>Значимые действия появятся здесь автоматически.</span></div>';else foreach(\array_slice($c['events'],0,5)as$x)$history.='<div class="fm2-event"><time>'.$e($x['occurredAt']).'</time><div><strong>'.$e($x['label']??$eventLabels[$x['type']]??$x['type']).'</strong><small>Пользователь '.$e($x['actorId']).'</small></div></div>';$history.='</div>';$history=$this->panel('Последние события',$history);
        $problems=$this->panel('Проблемы',$order===null&&($c['controlEngineer']??null)===null?'<div class="fm2-problem"><strong>Не назначен инженер стройконтроля</strong><span>Назначьте инженера, чтобы сформировать распоряжение.</span></div>':'<div class="fm2-quiet-empty"><strong>Открытых проблем нет</strong><span>Блокирующие условия не обнаружены.</span></div>');
        $origins=['migration_native'=>['Нативный импорт','shlz-status--bright-green'],'migration_active'=>['Активен с cutover','shlz-status--blue'],'demo_fixture'=>['Демо-данные','shlz-status--orange'],'local_audit'=>['Локальная проверка','shlz-status--orange']];$origin=$origins[$c['dataOrigin']??'local_audit'];$originNotice=($c['dataOrigin']??null)==='demo_fixture'?'<div class="fm2-alert fm2-origin-notice" role="note"><strong>Демонстрационный объект.</strong> Данные созданы для локальной проверки интерфейса и не являются результатом legacy-миграции.</div>':'';$statusPaint=$c['opened']?'shlz-status--bright-green':'shlz-status--orange';$body='<header class="fm2-object-identity"><div><h1>Объект монтажа № '.$id.'</h1><p>'.$e($c['address']).', подъезд '.$e($c['entrance']).'</p><span>Регистрационный номер '.$e($c['registrationNumber']).'</span></div><div class="fm2-object-badges"><span class="shlz-status '.$origin[1].'">'.$origin[0].'</span><span class="shlz-status '.$statusPaint.'">'.$e($c['status']).'</span></div></header>'.$originNotice.$notice.'<section class="fm2-next-action" aria-label="Ближайшее действие">'.$command.'</section><div class="fm2-object-dashboard"><main><div class="fm2-section-grid">'.$dates.$team.'</div>'.$docs.'</main><aside>'.$problems.$history.'</aside></div>';
        $field=$c['flash']['field']??null;if(\in_array($field,['registrationNumber','signedOriginal','actualStartDate'],true)){$errorId=$field.'-error';$body=\str_replace('role="status"','role="status" id="'.$errorId.'"',$body);$body=\str_replace('name="'.$field.'"','name="'.$field.'" aria-invalid="true" aria-describedby="'.$errorId.'"',$body);}
        return PilotView::document($user,'Объект монтажа № '.$id,'Объекты монтажа',PilotView::breadcrumb([['Объекты монтажа','/pilot/objects']],'Объект монтажа № '.$id),$body);
    }

    private function command(array $c,string $id,?array $order):array
    {
        $e=[PilotView::class,'e'];$downloads='';
        if(isset($c['activeCaseProvenance'])&&\is_array($c['activeCaseProvenance'])){$p=$c['activeCaseProvenance'];$reasons=\implode(', ',\array_map($e,$p['classificationReasons']));$proof='<dl class="fm2-definition-list"><dt>Baseline</dt><dd>#'.$e($p['baselineId']).' · <code>'.$e($p['baselineHash']).'</code></dd><dt>Cutover</dt><dd>'.$e($p['cutoverAt']).'</dd><dt>Шаблон чек-листа</dt><dd>'.$e($p['templateVersion']).' · <code>'.$e($p['templateHash']).'</code></dd><dt>Причины классификации</dt><dd>'.$reasons.'</dd></dl>';return['<div><h2>Нативная история продолжается после cutover</h2><p><strong>Фактическая дата начала неизвестна на момент cutover.</strong> Baseline и шаблон зафиксированы неизменяемо; это не создаёт событие начала работ.</p>'.$proof.'</div><a class="fm2-primary-link" href="/pilot/objects/'.$id.'/checklist">Открыть чек-лист</a>',''];}
        if($order===null)return ['<div><h2>Загрузите распоряжение</h2><p>'.(($c['controlEngineer']??null)===null?'Сначала назначьте инженера в карточке объекта, затем выберите монтажников.':'Прикрепите подписанный PDF и укажите закреплённых монтажников. Шаблон можно сформировать там же при необходимости.').'</p></div>'.((($c['canPrepare']??false)&&!($c['hasPtoAct']??false)&&($c['controlEngineer']??null)!==null)?'<a class="shlz-link" href="/pilot/objects/'.$id.'/assignment-order/prepare">Загрузить распоряжение</a>':''),''];
        $base='/pilot/objects/'.$id.'/assignment-orders/'.$e($order['version']);$downloads='<div class="shlz-document-list fm2-order-documents">';
        foreach($order['artifacts']??[] as $artifact){$type=$artifact['type']??null;$media=$artifact['mediaType']??null;if(!in_array($type,['order','appendix','signed_original'],true))continue;$isPdf=$media==='application/pdf';$filename=$type==='signed_original'?'Подписанный оригинал.pdf':($type==='order'&&$isPdf?'Шаблон распоряжения.pdf':(string)($artifact['filename']??'Документ'));$href=$base.'/artifacts/'.$e($type);$extension=$isPdf?'PDF':'HTML';$size=$this->fileSize((int)($artifact['size']??0));$modified=(new \DateTimeImmutable((string)$order['preparedAt']))->setTimezone(new \DateTimeZone('Europe/Moscow'))->format('d.m.Y, H:i');$visual=$isPdf?'<img src="/pilot/assets/icons/file-pdf-default.svg" alt="">':'';$downloads.='<div class="shlz-document-row" data-file-type="'.($isPdf?'pdf-default':'document').'"><span class="shlz-document-row__visual" aria-hidden="true">'.$visual.'</span><span class="shlz-document-row__content"><a class="shlz-document-row__title" href="'.$href.'" title="'.$e($filename).'"'.($isPdf?' target="_blank"':'').'>'.$e($filename).'</a><span class="shlz-document-row__meta">'.$extension.' · '.$e($size).' · Версия '.$e($order['version']).'</span><span class="shlz-document-row__modified">'.($type==='signed_original'?'Загружен':'Сформирован').' '.$e($modified).'</span></span><span class="shlz-document-row__actions"><a class="shlz-document-row__action" href="'.$href.'" download="'.$e($filename).'" aria-label="Скачать '.$e($filename).'"><img src="/pilot/assets/icons/download.svg" alt=""></a></span></div>';}
        $downloads.='</div>';
        if($order['status']==='prepared'&&($c['canRegister']??false)){$form='<form class="fm2-inline-form fm2-registration-form" method="post" enctype="multipart/form-data" action="'.$base.'/registration">'.$this->hidden($c,$order).'<label for="signedOriginal">Подписанный оригинал распоряжения</label><input id="signedOriginal" type="file" name="signedOriginal" accept="application/pdf,.pdf" required><small>PDF, не более 25 МБ</small><button class="shlz-button shlz-button--primary" type="submit">Загрузить оригинал</button></form>';return ['<div><h2>'.($c['opened']?'Завершите изменение состава':'Загрузите подписанный оригинал').'</h2><p>Скачайте сформированный шаблон в разделе «Распоряжение», подпишите его и загрузите скан. До загрузки действует предыдущая зарегистрированная версия.</p></div>'.$form,$downloads];}
        if(!$c['opened']&&$order['status']==='registered'&&($c['canOpen']??false)){$form='<form class="fm2-inline-form" method="post" action="/pilot/objects/'.$id.'/open">'.$this->hidden($c,$order).'<label for="actualStartDate">Фактическая дата начала работ</label><input id="actualStartDate" type="date" name="actualStartDate" required><small>Не раньше даты распоряжения и не позже сегодняшней даты</small><button class="shlz-button shlz-button--primary" type="submit">Открыть работы</button></form>';return ['<div><h2>Откройте монтажные работы</h2><p>Подписанный оригинал загружен.</p></div>'.$form,$downloads];}
        if(!$c['opened']&&$order['status']==='prepared')return ['<div><h2>Шаблон распоряжения подготовлен</h2><p>Работы ещё не открыты. Подписанный оригинал может загрузить пользователь с соответствующим полномочием.</p></div>',$downloads];
        if(!$c['opened']&&$order['status']==='registered')return ['<div><h2>Подписанный оригинал загружен</h2><p>Работы ещё не открыты. Открыть их может пользователь с соответствующим полномочием.</p></div>',$downloads];
        $changeLink=($c['canPrepare']??false)?'<a class="shlz-link" href="/pilot/objects/'.$id.'/assignment-order/prepare">Изменить состав новым распоряжением</a>':'';
        return ['<div><h2>Работы открыты</h2><p>Стройконтроль может фиксировать ход монтажа и фотоотчёт. Изменение состава оформляется только новой версией распоряжения.</p></div><div class="fm2-action-stack"><a class="fm2-primary-link" href="/pilot/objects/'.$id.'/checklist">Открыть чек-лист</a>'.$changeLink.'</div>',$downloads];
    }
    private function hidden(array $c,array $order):string{$e=[PilotView::class,'e'];return '<input type="hidden" name="csrfToken" value="'.$e($c['csrfToken']).'"><input type="hidden" name="processRevision" value="'.$e($c['processRevision']).'"><input type="hidden" name="assignmentOrderVersion" value="'.$e($order['version']).'">';}
    private function fileSize(int $bytes):string{if($bytes<1024)return $bytes.' Б';if($bytes<1048576)return number_format($bytes/1024,$bytes<10240?1:0,',','').' КБ';return number_format($bytes/1048576,1,',','').' МБ';}
    private function panel(string $title,string $content):string{return '<section class="fm2-panel"><h2>'.$title.'</h2>'.$content.'</section>';}
    public function renderCompatibility(HttpUser $user,array $c):string{return $this->render($user,$c);}
}
