<?php declare(strict_types=1);
namespace FMonitor2\PilotHttp;
// Owns the object-card <main composition supplied to the shared document shell.
final class ProductionObjectCardRenderer implements ObjectCardRenderer,CompatibilityObjectCardRenderer
{
    public function render(HttpUser $user,array $c):string
    {
        $e=[PilotView::class,'e'];$id=$e($c['id']);$pair=static fn(string $term,string $value):array=>[$term,$value];$order=$c['order'];$team=[];
        if($order===null){$team[]=$pair('Распоряжение','Распоряжение ещё не сформировано');$team[]=$pair('Команда','Подтверждённая команда ещё не сформирована');$action=(($c['canPrepare']??false)&&!($c['hasPtoAct']??false)&&$c['status']==='Требуется распоряжение')?'<p class="fm2-next"><a class="shlz-link fm2-primary-link" href="/pilot/objects/'.$id.'/assignment-order/prepare">Сформировать распоряжение</a></p>':'';}
        else{$document=$order['status']==='prepared'?'Ожидается номер 1С ДО':'Зарегистрировано в 1С ДО';$caption=$order['registrationNumber']===null?'Распоряжение от '.$e($order['orderDate']).' · версия '.$e($order['version']):'Распоряжение № '.$e($order['registrationNumber']).' от '.$e($order['orderDate']).' · версия '.$e($order['version']);if($order['status']==='registered'&&$c['status']!=='В работе'){$team[]=$pair('Распоряжение',$caption);$team[]=$pair('Статус распоряжения',$document);}else{$team[]=$pair('Статус распоряжения',$document);$team[]=$pair('Распоряжение',$caption);}$team[]=$pair('Инженер',$e($order['engineer']['fullName']).' · '.$e($order['engineer']['position']).' · '.$e($order['engineer']['userId']));foreach($order['installers']as$installer)$team[]=$pair('Исполнитель',$e($installer['tabId']).' · '.$e($installer['fullName']).' · '.$e($installer['position']).' · '.$e($installer['status']));$team[]=$pair('Форма организации труда',$order['organizationType']==='brigade'?'Бригадная':'Индивидуальная');$base='/pilot/objects/'.$id.'/assignment-orders/'.$e($order['version']);$action='<div class="fm2-actions"><span class="shlz-tag">Версия '.$e($order['version']).'</span><a class="shlz-link" href="'.$base.'/artifacts/order">Скачать распоряжение</a><a class="shlz-link" href="'.$base.'/artifacts/appendix">Скачать приложение</a></div>';if(!$c['opened']&&isset($c['csrfToken'])&&$order['status']==='prepared'&&($c['canRegister']??false))$action.='<form class="fm2-inline-form" method="post" action="'.$base.'/registration"><input type="hidden" name="csrfToken" value="'.$e($c['csrfToken']).'"><input type="hidden" name="processRevision" value="'.$e($c['processRevision']).'"><input type="hidden" name="assignmentOrderVersion" value="'.$e($order['version']).'"><label for="registrationNumber">Номер распоряжения в 1С ДО</label><input id="registrationNumber" name="registrationNumber" maxlength="120" required><button class="shlz-button" type="submit">Сохранить номер 1С ДО</button></form>';if(!$c['opened']&&isset($c['csrfToken'])&&$order['status']==='registered'&&($c['canOpen']??false))$action.='<form class="fm2-inline-form" method="post" action="/pilot/objects/'.$id.'/open"><input type="hidden" name="csrfToken" value="'.$e($c['csrfToken']).'"><input type="hidden" name="processRevision" value="'.$e($c['processRevision']).'"><input type="hidden" name="assignmentOrderVersion" value="'.$e($order['version']).'"><label for="actualStartDate">Фактическая дата начала работ</label><input id="actualStartDate" type="date" name="actualStartDate" required><small>Дата должна быть не раньше даты распоряжения и не позже сегодняшней даты.</small><button class="shlz-button" type="submit">Открыть работы</button></form>';}
        $work=$c['opened']?[$pair('Фактическое начало','Фактическое начало '.$e($c['actualStartDate'])),$pair('Аудит открытия','Открыто: '.$e($c['openedAt']).' · Открыл пользователь: '.$e($c['openedByName']??$c['openedByUserId'])),$pair('Чек-лист','Чек-лист: Доступен')]:[$pair('Состояние работ','Работы ещё не открыты')];$events=[];if($c['events']===[])$events[]=$pair('История','Событий пока нет');else foreach($c['events']as$event)$events[]=$pair('Событие',$e($event['type']).' · '.$e($event['occurredAt']).' · '.$e($event['actorId']));
        $section=static fn(string $title,array $rows,string $extra=''):string=>'<section><h2>'.$title.'</h2>'.PilotView::dl($rows).$extra.'</section>';
        $notice=isset($c['flash'])&&$c['flash']?'<div class="fm2-alert" role="status">'.$e($c['flash']['message']).'</div>':'';$next=$c['opened']&&$order!==null?'<section class="fm2-next"><h2>Следующий шаг</h2><p>Инженеру строительного контроля: провести первую инспекцию объекта.</p><strong>Ответственный: '.$e($order['engineer']['fullName']).'</strong></section>':'';$body='<div class="fm2-page-header"><h1>Объект монтажа № '.$id.'</h1><span class="shlz-status">'.$e($c['status']).'</span></div>'.$notice.$next.'<div class="fm2-object-layout">'.$section('Идентификация',[$pair('Регистрационный номер',$e($c['registrationNumber'])),$pair('Адрес',$e($c['address'])),$pair('Подъезд','Подъезд '.$e($c['entrance']))]).$section('Сроки',[$pair('Плановое начало','Плановое начало '.$e($c['plannedStartDate'])),$pair('Плановое окончание','Плановое окончание '.$e($c['plannedFinishDate']))]).$section('Распоряжение и команда',$team,$action).$section('Работы',$work).$section('Последние события',$events).'</div>';
        return PilotView::document($user,'Объект монтажа № '.$id,'Объекты монтажа',PilotView::breadcrumb([['Объекты монтажа','/pilot/objects']],'Объект монтажа № '.$id),$body);
    }
    public function renderCompatibility(HttpUser $user,array $c):string
    {
        $id=PilotView::e($c['id']);$shared=$this->render($user,$c);$start=\strpos($shared,'<main class="fm2-main" id="main-content" tabindex="-1">');$end=\strrpos($shared,'</main>');if($start===false||$end===false)throw new \LogicException();$start=\strpos($shared,'>',$start)+1;$navEnd=\strpos($shared,'</nav>',$start);if($navEnd!==false)$start=$navEnd+6;$body=\substr($shared,$start,$end-$start);
        $body=\preg_replace('#<div class="fm2-actions">.*?</div>#s','',$body)??$body;
        return '<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Объект монтажа № '.$id.' — FMonitor 2.0</title><link rel="stylesheet" href="/pilot/assets/shlz.css"></head><body class="shlz-scope"><a class="shlz-link" href="#main-content">Перейти к содержанию</a><header><strong>FMonitor 2.0</strong><span>'.PilotView::e($user->displayName).'</span></header><nav aria-label="Основная навигация"><a class="shlz-link" href="/pilot/">Моя работа</a><span aria-current="page">Объект монтажа</span></nav><main id="main-content" tabindex="-1">'.$body.'</main></body></html>';
    }
}
