<?php
declare(strict_types=1);
namespace FMonitor2\PilotHttp;
require_once __DIR__.'/PilotView.php';
final class OriginalUploadView
{
 public static function path(int$object,int$order):string{return'/pilot/objects/'.$object.'/assignment-orders/'.$order.'/originals';}
 public static function render(HttpUser$user,array$m,string$csrf):string
 {
  $e=PilotView::e(...);$object=(int)$m['objectId'];$path=self::path($object,$m['orderId']);$current=$m['current'];$title=$current===null?'Загрузить оригинал':'Исправить оригинал';$b=random_bytes(16);$b[6]=chr((ord($b[6])&15)|64);$b[8]=chr((ord($b[8])&63)|128);$h=bin2hex($b);$request=substr($h,0,8).'-'.substr($h,8,4).'-'.substr($h,12,4).'-'.substr($h,16,4).'-'.substr($h,20);
  $summary='<div class="fm2-order-object"><strong>Объект монтажа № '.$object.'</strong><span>Распоряжение · версия '.$e($m['orderVersion']).'</span><small>Выбранный состав сохранён отдельно от файла оригинала</small></div>';
  $names=implode(', ',array_column($m['composition']['installers'],'fullName'));$composition='<section class="fm2-order-team"><div class="fm2-order-section-head"><div><h2>Выбранный состав</h2><p>'.$e($names).'</p></div></div><p class="fm2-order-engineer-line"><strong>Инженер строительного контроля</strong><span>'.$e($m['composition']['engineer']['fullName']).'</span></p></section>';
  $history='';if($current!==null)$history='<div class="fm2-order-current"><div><strong>Принятый оригинал · редакция '.$e($current['revisionNumber']).'</strong><span>Дата документа: '.$e($current['documentDate']).'</span><small>Предыдущий файл и дата сохранятся в истории.</small></div><a class="shlz-link" href="'.$path.'/history">История и PDF</a></div>';
  $fields=FreshOrderSelectionView::hidden(['csrfToken'=>$csrf,'requestId'=>$request,'mode'=>$m['mode'],'rootOriginalId'=>$current['rootId']??'','targetRevisionId'=>$current['revisionId']??'','expectedCurrentRevisionId'=>$current['revisionId']??'']);if($current===null)$fields.=FreshOrderSelectionView::hidden(['correctionReason'=>'']);
  $correction=$current===null?'':'<label class="shlz-field"><span class="shlz-field__label">Причина исправления</span><span class="shlz-field__control"><input class="shlz-input" type="text" name="correctionReason" maxlength="500" required></span><span class="shlz-field__secondary">Кратко укажите, почему выпускается новая редакция.</span></label>';
  $upload='<section class="fm2-order-upload" aria-labelledby="signed-original"><div class="fm2-order-section-head"><div><h2 id="signed-original">Подписанный оригинал</h2><p>Загрузите один PDF-файл и укажите дату, напечатанную в документе.</p></div><span class="shlz-status shlz-status--blue">До 20 МиБ</span></div><label class="fm2-file-drop" data-file-drop><input type="file" name="original" accept="application/pdf,.pdf" required data-file-input><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 16V4m0 0L7.5 8.5M12 4l4.5 4.5M5 14v5h14v-5"/></svg><span><strong><u>Выберите</u> или перетащите сюда файл</strong><small data-file-name>PDF, не более 20 МиБ</small></span></label></section>';
  $form='<form class="fm2-order-form" data-original-upload-form data-return-url="'.$path.'/submit" action="'.$path.'">'.$fields.'<fieldset class="fm2-order-surface" data-original-fields disabled><header>'.$summary.'</header>'.$history.$upload.$composition.'<section class="fm2-order-team fm2-original-details"><label class="shlz-field"><span class="shlz-field__label">Дата распоряжения</span><span class="shlz-field__control"><input class="shlz-input" type="date" name="documentDate" value="'.$e($m['suggestedDocumentDate']).'" required></span><span class="shlz-field__secondary">Проверьте дату, напечатанную в оригинале.</span></label>'.$correction.'<label class="shlz-choice"><input class="shlz-checkbox" type="checkbox" name="compositionConfirmed" required><span>Подтверждаю соответствие оригинала выбранному составу</span></label><p>Загрузка сохраняет оригинал. Открытие работ выполняется отдельно.</p></section><footer class="fm2-order-actions"><a class="shlz-link" href="'.FreshOrderSelectionView::path($object).'">К составу</a><button class="shlz-button shlz-button--primary" type="submit" data-original-submit>'.$title.'</button></footer></fieldset><aside class="fm2-order-helper"><div class="fm2-order-helper-icon" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="M12 3v18M3 12h18"/></svg></div><div><h2>После загрузки</h2><p>Проверьте документ, примените состав и отдельно откройте работы.</p></div><a class="shlz-button" href="/pilot/objects/'.$object.'/execution">Перейти к применению</a></aside><noscript><p>Для загрузки оригинала включите JavaScript в браузере и обновите страницу.</p></noscript><p class="fm2-original-status" role="status" aria-live="polite" data-original-status></p></form>';
  $body='<div class="fm2-page-header fm2-order-heading"><div><h1>'.$title.'</h1><p>Проверьте выбранный состав и приложите оформленный документ.</p></div></div>'.$form.'<script src="/pilot/assets/original-upload.js" defer></script>';
  return PilotView::document($user,$title,'Объекты монтажа',PilotView::breadcrumb([['Объекты монтажа','/pilot/objects'],['Объект монтажа № '.$object,'/pilot/objects/'.$object],['Состав',FreshOrderSelectionView::path($object)]],$title),$body);
 }
}
