<?php declare(strict_types=1);
namespace FMonitor2\PilotHttp;

final class ProductionPrepareFormRenderer implements PrepareFormRenderer,CompatibilityPrepareFormRenderer
{
    public function render(HttpUser $user,array $f):string
    {
        $e=[PilotView::class,'e'];$id=$e($f['id']);$selected=$f['selected']??[];$selectedInstallers=\array_map('strval',$selected['installers']??[]);$selectedEngineer=isset($selected['engineer'])?(string)$selected['engineer']:null;
        $installerOptions='';foreach($f['installers']as$x){$value=(string)$x['tabId'];$installerOptions.='<option value="'.$e($value).'"'.(\in_array($value,$selectedInstallers,true)?' selected':'').'>'.$e($x['fio']).' · таб. '.$e($value).' · '.$e($x['position']).($x['busyUntil']?' · занят до '.$e($x['busyUntil']):'').'</option>';}
        $engineerOptions='';foreach($f['engineers']as$x){$value=(string)$x['userId'];$chosen=$selectedEngineer!==null?$selectedEngineer===$value:(bool)$x['prefilled'];$engineerOptions.='<option value="'.$e($value).'"'.($chosen?' selected':'').'>'.$e($x['fio']).' · '.$e($x['position']).'</option>';}
        $command=isset($f['csrfToken']);$route='/pilot/objects/'.$id.'/assignment-order/prepare';$hidden=$command?'<input type="hidden" name="csrfToken" value="'.$e($f['csrfToken']).'"><input type="hidden" name="processRevision" value="'.$e($f['processRevision']).'">':'';
        $summary=PilotView::dl([['Регистрационный номер',$e($f['registrationNumber'])],['Адрес',$e($f['address'])],['Подъезд',$e($f['entrance'])],['Плановый период',PilotView::date($f['plannedStartDate']).' — '.PilotView::date($f['plannedFinishDate'])]]);
        $flash=$f['flash']??null;$notice=$flash?'<div class="fm2-alert" role="status"><a href="#'.($e($flash['field']??'form-errors')).'">'.$e($flash['message']).'</a></div>':'';
        $installers=$f['installers']===[]?'<div class="shlz-empty-state"><p>Нет допустимых монтажников.</p></div>':'<div class="fm2-picker"><button class="shlz-button" type="button" popovertarget="installer-picker">Добавить монтажников</button><div class="fm2-picker-dialog" id="installer-picker" popover><div class="fm2-picker-head"><div><h3>Монтажники</h3><p>Тысячи сотрудников не выводятся флагами: используйте поиск списка и выберите нужных.</p></div><button type="button" popovertarget="installer-picker" popovertargetaction="hide">Закрыть</button></div><label>Поиск по ФИО или табельному номеру<input type="search" placeholder="Начните вводить имя или табельный номер" autocomplete="off"></label><label>Результаты<select name="installerTabIds[]" multiple size="8" required>'.$installerOptions.'</select></label><small>Ctrl / Cmd — выбрать несколько сотрудников. В списке работает быстрый поиск с клавиатуры.</small></div></div>';
        $engineers=$f['engineers']===[]?'<div class="shlz-empty-state"><p>Нет доступных инженеров.</p></div>':'<div class="fm2-picker"><button class="shlz-button" type="button" popovertarget="engineer-picker">Добавить стройконтроль</button><div class="fm2-picker-dialog" id="engineer-picker" popover><div class="fm2-picker-head"><div><h3>Инженер строительного контроля</h3><p>Найдите и выберите одного ответственного.</p></div><button type="button" popovertarget="engineer-picker" popovertargetaction="hide">Закрыть</button></div><label>Поиск по ФИО<input type="search" placeholder="Начните вводить фамилию" autocomplete="off"></label><label>Результаты<select name="controlEngineerUserId" size="7" required>'.$engineerOptions.'</select></label></div></div>';
        $confirmation=$f['installers']!==[]&&$f['engineers']!==[]?'<label class="shlz-choice fm2-confirm"><input class="shlz-checkbox" type="checkbox" name="controlEngineerConfirmed" value="yes"'.(($selected['confirmed']??false)?' checked':'').'>Подтверждаю выбранный состав и инженера строительного контроля</label>':'';
        $submit=$command&&$f['installers']!==[]&&$f['engineers']!==[]?'<button class="shlz-button fm2-submit" type="submit">Сформировать распоряжение</button>':'';
        $body='<div class="fm2-page-header"><div><h1>Формирование распоряжения</h1><p>Выберите состав и сформируйте неизменяемую версию документа.</p></div></div>'.$notice.'<div class="fm2-form-layout"><aside class="fm2-panel"><h2>Объект монтажа № '.$id.'</h2>'.$summary.'</aside><form id="form-errors" class="fm2-form fm2-form-card" method="'.($command?'post':'get').'" action="'.$route.'">'.$hidden.'<section><span class="fm2-step-number">1</span><div><h2 id="installers">Монтажники</h2><p>Выберите одного или нескольких сотрудников.</p>'.$installers.'</div></section><section><span class="fm2-step-number">2</span><div><h2 id="engineer">Строительный контроль</h2><p>Назначьте одного инженера.</p>'.$engineers.'</div></section><section><span class="fm2-step-number">3</span><div id="confirmation"><h2>Подтверждение</h2>'.$confirmation.'<div class="fm2-actions">'.$submit.'<a class="shlz-link" href="/pilot/objects/'.$id.'">Отмена</a></div></div></section></form></div>';
        return PilotView::document($user,'Формирование распоряжения','Объекты монтажа',PilotView::breadcrumb([['Объекты монтажа','/pilot/objects'],['Объект монтажа № '.$id,'/pilot/objects/'.$id]],'Распоряжение'),$body);
    }
    public function renderCompatibility(HttpUser $user,array $f):string{return $this->render($user,$f);}
}
