<?php declare(strict_types=1);
namespace FMonitor2\PilotHttp;

final class ProductionPrepareFormRenderer implements PrepareFormRenderer,CompatibilityPrepareFormRenderer
{
    public function render(HttpUser $user,array $f):string
    {
        $e=[PilotView::class,'e'];$id=$e($f['id']);$selected=$f['selected']??[];$selectedInstallers=\array_map('strval',$selected['installers']??[]);$engineer=$f['engineer']??null;
        $installerData='';foreach($f['installers']as$x){$value=(string)$x['tabId'];$tab=\str_pad($value,6,'0',STR_PAD_LEFT);$installerData.='<span data-id="'.$e($value).'" data-name="'.$e($x['fio']).'" data-tab="'.$e($tab).'" data-position="'.$e($x['position']).'" data-busy="'.$e($x['busyUntil']??'').'" data-selected="'.(\in_array($value,$selectedInstallers,true)?'1':'0').'"></span>';}
        $command=isset($f['csrfToken']);$route='/pilot/objects/'.$id.'/assignment-order/prepare';$hidden=$command?'<input type="hidden" name="csrfToken" value="'.$e($f['csrfToken']).'"><input type="hidden" name="processRevision" value="'.$e($f['processRevision']).'">':'';
        $summary='<div class="fm2-order-object"><strong>Объект монтажа № '.$id.'</strong><span>'.$e($f['registrationNumber']).' · '.$e($f['address']).', подъезд '.$e($f['entrance']).'</span><small>Плановый период: '.PilotView::date($f['plannedStartDate']).' — '.PilotView::date($f['plannedFinishDate']).'</small></div>';
        $flash=$f['flash']??null;$notice=$flash?'<div class="fm2-alert" role="status"><a href="#'.($e($flash['field']??'form-errors')).'">'.$e($flash['message']).'</a></div>':'';
        $installers=$f['installers']===[]?'<div class="shlz-empty-state"><p>Нет допустимых монтажников.</p></div>':'<div class="fm2-picker fm2-installer-picker" data-installer-picker><div class="fm2-picker-selection" data-picker-selection><span class="fm2-picker-selection-empty">Монтажники ещё не выбраны</span></div><button class="shlz-button" type="button" popovertarget="installer-picker">Выбрать монтажников</button><div class="fm2-picker-dialog" id="installer-picker" popover><div class="fm2-picker-head"><div><h3>Выбор монтажников</h3><p>Поиск по ФИО или шестизначному табельному номеру</p></div><button class="fm2-picker-x" type="button" aria-label="Закрыть окно" popovertarget="installer-picker" popovertargetaction="hide">×</button></div><div class="fm2-picker-modal-selection"><strong>Выбрано</strong><div class="fm2-picker-selection" data-picker-modal-selection><span class="fm2-picker-selection-empty">Пока никого</span></div></div><label class="fm2-search-field"><span class="fm2-visually-hidden">Поиск монтажника</span><input type="search" data-picker-search placeholder="Фамилия или табельный номер" autocomplete="off" autofocus></label><div class="fm2-picker-result-meta" data-picker-meta>Введите минимум 2 символа</div><div class="fm2-picker-results" data-picker-results aria-live="polite" aria-label="Результаты поиска"></div><footer class="fm2-picker-footer"><span data-picker-count>Выбрано: 0</span><button class="shlz-button" type="button" popovertarget="installer-picker" popovertargetaction="hide">Готово</button></footer></div><template data-picker-data>'.$installerData.'</template><div data-picker-inputs></div></div>';
        $engineerInfo=$engineer===null?'<div class="shlz-empty-state"><p>Инженер не назначен. Вернитесь в карточку объекта.</p></div>':'<div class="fm2-reference-person"><span class="shlz-avatar shlz-avatar--32" aria-hidden="true">'.PilotView::initials($engineer['fio']).'</span><span><strong>'.$e($engineer['fio']).'</strong><small>'.$e($engineer['position']).' · справочно из карточки объекта</small></span></div>';
        $submit=$command&&$f['installers']!==[]&&$engineer!==null?'<button class="shlz-button fm2-submit" type="submit">Сформировать распоряжение</button>':'';
        $body='<div class="fm2-page-header fm2-order-heading"><div><h1>Сформировать распоряжение</h1><p>Выберите монтажников. После формирования состав и дата документа станут неизменяемыми.</p></div></div>'.$notice.'<form id="form-errors" class="fm2-order-surface" method="'.($command?'post':'get').'" action="'.$route.'">'.$hidden.'<header>'.$summary.'</header><section class="fm2-order-team" aria-labelledby="installers"><div class="fm2-order-section-head"><div><h2 id="installers">Монтажники</h2><p>В распоряжение войдёт текущий выбранный состав.</p></div></div><div class="fm2-order-selection">'.$installers.'</div></section><aside class="fm2-order-engineer"><div><span>Инженер строительного контроля</span><small>Назначен в карточке объекта и в этом распоряжении не изменяется</small></div>'.$engineerInfo.'</aside><footer class="fm2-order-actions"><div><strong>Распоряжение будет сформировано одной версией</strong><span>Проверьте состав перед подтверждением.</span></div><div class="fm2-actions">'.$submit.'<a class="shlz-link" href="/pilot/objects/'.$id.'">Отмена</a></div></footer></form>';
        $body.='<script src="/pilot/assets/picker.js" defer></script>';
        return PilotView::document($user,'Формирование распоряжения','Объекты монтажа',PilotView::breadcrumb([['Объекты монтажа','/pilot/objects'],['Объект монтажа № '.$id,'/pilot/objects/'.$id]],'Распоряжение'),$body);
    }
    public function renderCompatibility(HttpUser $user,array $f):string{return $this->render($user,$f);}
}
