<?php declare(strict_types=1);
namespace FMonitor2\PilotHttp;

final class ProductionPrepareFormRenderer implements PrepareFormRenderer,CompatibilityPrepareFormRenderer
{
    public function render(HttpUser $user,array $f):string
    {
        $e=[PilotView::class,'e'];$id=$e($f['id']);$selected=$f['selected']??[];$selectedInstallers=\array_map('strval',$selected['installers']??[]);$selectedEngineer=isset($selected['engineer'])?(string)$selected['engineer']:null;
        $installerData='';foreach($f['installers']as$x){$value=(string)$x['tabId'];$tab=\str_pad($value,6,'0',STR_PAD_LEFT);$installerData.='<span data-id="'.$e($value).'" data-name="'.$e($x['fio']).'" data-tab="'.$e($tab).'" data-position="'.$e($x['position']).'" data-busy="'.$e($x['busyUntil']??'').'" data-selected="'.(\in_array($value,$selectedInstallers,true)?'1':'0').'"></span>';}
        $engineerOptions='';foreach($f['engineers']as$x){$value=(string)$x['userId'];$chosen=$selectedEngineer!==null?$selectedEngineer===$value:(bool)$x['prefilled'];$engineerOptions.='<option value="'.$e($value).'"'.($chosen?' selected':'').'>'.$e($x['fio']).' · '.$e($x['position']).'</option>';}
        $command=isset($f['csrfToken']);$route='/pilot/objects/'.$id.'/assignment-order/prepare';$hidden=$command?'<input type="hidden" name="csrfToken" value="'.$e($f['csrfToken']).'"><input type="hidden" name="processRevision" value="'.$e($f['processRevision']).'">':'';
        $summary=PilotView::dl([['Регистрационный номер',$e($f['registrationNumber'])],['Адрес',$e($f['address'])],['Подъезд',$e($f['entrance'])],['Плановый период',PilotView::date($f['plannedStartDate']).' — '.PilotView::date($f['plannedFinishDate'])]]);
        $flash=$f['flash']??null;$notice=$flash?'<div class="fm2-alert" role="status"><a href="#'.($e($flash['field']??'form-errors')).'">'.$e($flash['message']).'</a></div>':'';
        $installers=$f['installers']===[]?'<div class="shlz-empty-state"><p>Нет допустимых монтажников.</p></div>':'<div class="fm2-picker fm2-installer-picker" data-installer-picker><div class="fm2-picker-selection" data-picker-selection><span class="fm2-picker-selection-empty">Монтажники ещё не выбраны</span></div><button class="shlz-button" type="button" popovertarget="installer-picker">Выбрать монтажников</button><div class="fm2-picker-dialog" id="installer-picker" popover><div class="fm2-picker-head"><div><h3>Выбор монтажников</h3><p>Поиск по ФИО или шестизначному табельному номеру</p></div><button class="fm2-picker-x" type="button" aria-label="Закрыть окно" popovertarget="installer-picker" popovertargetaction="hide">×</button></div><label class="fm2-search-field"><span class="fm2-visually-hidden">Поиск монтажника</span><input type="search" data-picker-search placeholder="Фамилия или табельный номер" autocomplete="off" autofocus></label><div class="fm2-picker-result-meta" data-picker-meta>Введите минимум 2 символа</div><div class="fm2-picker-results" data-picker-results aria-live="polite" aria-label="Результаты поиска"></div><footer class="fm2-picker-footer"><span data-picker-count>Выбрано: 0</span><button class="shlz-button" type="button" popovertarget="installer-picker" popovertargetaction="hide">Готово</button></footer></div><template data-picker-data>'.$installerData.'</template><div data-picker-inputs></div></div>';
        $engineers=$f['engineers']===[]?'<div class="shlz-empty-state"><p>Нет доступных инженеров.</p></div>':'<div class="fm2-picker"><button class="shlz-button" type="button" popovertarget="engineer-picker">Добавить стройконтроль</button><div class="fm2-picker-dialog" id="engineer-picker" popover><div class="fm2-picker-head"><div><h3>Инженер строительного контроля</h3><p>Найдите и выберите одного ответственного.</p></div><button type="button" popovertarget="engineer-picker" popovertargetaction="hide">Закрыть</button></div><label>Поиск по ФИО<input type="search" placeholder="Начните вводить фамилию" autocomplete="off"></label><label>Результаты<select name="controlEngineerUserId" size="7" required>'.$engineerOptions.'</select></label></div></div>';
        $confirmation=$f['installers']!==[]&&$f['engineers']!==[]?'<label class="shlz-choice fm2-confirm"><input class="shlz-checkbox" type="checkbox" name="controlEngineerConfirmed" value="yes"'.(($selected['confirmed']??false)?' checked':'').'>Подтверждаю выбранный состав и инженера строительного контроля</label>':'';
        $submit=$command&&$f['installers']!==[]&&$f['engineers']!==[]?'<button class="shlz-button fm2-submit" type="submit">Сформировать распоряжение</button>':'';
        $body='<div class="fm2-page-header"><div><h1>Формирование распоряжения</h1><p>Выберите состав и сформируйте неизменяемую версию документа.</p></div></div>'.$notice.'<div class="fm2-form-layout"><aside class="fm2-panel"><h2>Объект монтажа № '.$id.'</h2>'.$summary.'</aside><form id="form-errors" class="fm2-form fm2-form-card" method="'.($command?'post':'get').'" action="'.$route.'">'.$hidden.'<section><span class="fm2-step-number">1</span><div><h2 id="installers">Монтажники</h2><p>Выберите одного или нескольких сотрудников.</p>'.$installers.'</div></section><section><span class="fm2-step-number">2</span><div><h2 id="engineer">Строительный контроль</h2><p>Назначьте одного инженера.</p>'.$engineers.'</div></section><section><span class="fm2-step-number">3</span><div id="confirmation"><h2>Подтверждение</h2>'.$confirmation.'<div class="fm2-actions">'.$submit.'<a class="shlz-link" href="/pilot/objects/'.$id.'">Отмена</a></div></div></section></form></div>';
        $body.='<script src="/pilot/assets/picker.js" defer></script>';
        return PilotView::document($user,'Формирование распоряжения','Объекты монтажа',PilotView::breadcrumb([['Объекты монтажа','/pilot/objects'],['Объект монтажа № '.$id,'/pilot/objects/'.$id]],'Распоряжение'),$body);
    }
    public function renderCompatibility(HttpUser $user,array $f):string{return $this->render($user,$f);}
}
